import json
import os

# Complete 75 Berlin Spots Data
spots = [
    # 1. Brandenburger Tor
    {
        "id": "b_1",
        "name": "Brandenburger Tor（ブランデンブルク門）",
        "category": "Landmark", "rating": "★4.8", "locationZone": "city",
        "lat": 52.5163, "lng": 13.3777, "kids": True, "rain": False, "shopping": False, "free": True,
        "desc_en": "18th-century Neoclassical sandstone monument topped by the Quadriga chariot, iconic symbol of German unity and Cold War history.",
        "desc_ja": "18世紀末建造の新古典主義様式の砂岩城門。頂上に勝利の女神クアドリガが輝き、冷戦の東西分断とドイツ再統一の象徴。",
        "desc_es": "Monumento neoclásico del siglo XVIII coronado por la Cuadriga, símbolo icónico de la reunificación alemana.",
        "desc_zh": "建于18世纪末的新古典主义沙岩城门，顶端矗立胜利女神四马战车，是德国冷战分断与重新统一的象征。",
        "desc_fr": "Monument néoclassique du XVIIIe siècle surmonté du Quadrige, symbole emblématique de la réunification allemande.",
        "desc_de": "Neoklassizistisches Sandsteinmonument des 18. Jahrhunderts mit der Quadriga, weltberühmtes Symbol der deutschen Einheit.",
        "tip_en": "📸 Visit at dusk when blue hour lighting illuminates Pariser Platz, or early morning at 7:00 AM to take photos without crowds.",
        "tip_ja": "📸 パリ広場のライトアップが灯る日没直後のブルーアワーの訪問が最高！人混みを避けて門の全景を撮るなら早朝7:00前が狙い目です。",
        "tip_es": "📸 Visítala al atardecer cuando la iluminación azul ilumina la plaza, o a las 7:00 h para fotos sin multitud.",
        "tip_zh": "📸 推荐黄昏蓝调时刻前往拍摄华灯初上的巴黎广场！若想拍到没有游人的空旷全景，建议早晨7点前抵达。",
        "tip_fr": "📸 Admirez l'illumination à l'heure bleue sur la Pariser Platz, ou venez dès 7h du matin pour des photos sans la foule.",
        "tip_de": "📸 Zur blauen Stunde besuchen, wenn der Platz beleuchtet ist, oder morgens vor 7:00 Uhr für Fotos ohne Menschenmassen.",
        "price_en": "Free Entry", "price_ja": "見学無料", "price_es": "Entrada libre", "price_zh": "免费参观", "price_fr": "Accès libre", "price_de": "Kostenlos",
        "name_en": "Brandenburg Gate", "name_ja": "Brandenburger Tor（ブランデンブルク門）", "name_es": "Puerta de Brandeburgo", "name_zh": "勃兰登堡门", "name_fr": "Porte de Brandebourg", "name_de": "Brandenburger Tor"
    },
    # 2. Reichstagsgebäude
    {
        "id": "b_2",
        "name": "Reichstagsgebäude（連邦議会議事堂）",
        "category": "Landmark", "rating": "★4.7", "locationZone": "city",
        "lat": 52.5186, "lng": 13.3761, "kids": True, "rain": True, "shopping": False, "free": True,
        "desc_en": "Historic parliament building redesigned by Norman Foster featuring a spectacular glass dome with a mirrored light cone.",
        "desc_ja": "1894年建造の歴史的議事堂。ノーマン・フォスター設計のガラスドーム内部の螺旋スロープと中央鏡面コーンが見事。",
        "desc_es": "Edificio del parlamento rediseñado por Norman Foster con una cúpula de cristal y un cono de espejos.",
        "desc_zh": "由诺曼·福斯特主持翻修的历史国会大厦，拥有巨大的玻璃穹顶与中央倒立螺旋镜面光锥。",
        "desc_fr": "Bâtiment historique du parlement réaménagé par Norman Foster avec un cône de miroirs sous un dôme de verre.",
        "desc_de": "Historisches Parlamentsgebäude mit der von Norman Foster gestalteten Glaskuppel und Spiegel-Lichtkegel.",
        "tip_en": "🎟️ Free web registration on the Bundestag portal is REQUIRED 2-4 weeks in advance! Bring your valid original passport for security check.",
        "tip_ja": "🎟️ 公式サイトでの完全無料の事前Web日時予約が絶対必須！入場時はパスポート（原本）の本人確認が厳格に行われます。",
        "tip_es": "🎟️ ¡Es OBLIGATORIO registrarse gratis en la web con 2-4 semanas de antelación! Trae tu pasaporte original para el control.",
        "tip_zh": "🎟️ 必须提前2-4周在联邦议会官网进行免费预约登记！入场安检必须出示护照原件进行身份核对。",
        "tip_fr": "🎟️ Réservation GRATUITE obligatoire 2 à 4 semaines à l'avance sur le site web ! Passeport original obligatoire.",
        "tip_de": "🎟️ Kostenlose Online-Registrierung 2–4 Wochen im Voraus Pflicht! Gültigen Reisepass zur Sicherheitskontrolle mitbringen.",
        "price_en": "Free (Online Booking Required)", "price_ja": "無料（要事前Web予約）", "price_es": "Gratis (Reserva previa)", "price_zh": "免费（须提前网约）", "price_fr": "Gratuit (Sur réservation)", "price_de": "Kostenlos (Anmeldung erforderlich)",
        "name_en": "Reichstag Building", "name_ja": "Reichstagsgebäude（連邦議会議事堂）", "name_es": "Edificio del Reichstag", "name_zh": "德国国会大厦", "name_fr": "Palais du Reichstag", "name_de": "Reichstagsgebäude"
    },
    # 3. Museumsinsel (UNESCO)
    {
        "id": "b_3",
        "name": "Museumsinsel (UNESCO)（博物館島）",
        "category": "Museum & Gallery", "rating": "★4.8", "locationZone": "city",
        "lat": 52.5206, "lng": 13.3969, "kids": True, "rain": True, "shopping": False, "free": False,
        "desc_en": "UNESCO World Heritage island in the Spree river grouping 5 prestigious museums housing 6,000 years of art & archaeology.",
        "desc_ja": "シュプレー川の中州に位置するユネスコ世界遺産の博物館群。5つの殿堂ミュージアムが集結する人類文明の宝庫。",
        "desc_es": "Isla en el río Spree patrimonio UNESCO que alberga 5 prestigiosos museos con 6.000 años de arte y arqueología.",
        "desc_zh": "矗立于施普雷河中洲的世界遗产博物馆群。汇聚了5座世界级博物馆，陈列着跨越6000年的文明瑰宝。",
        "desc_fr": "Île sur la Spree classée UNESCO regroupant 5 grands musées retraçant 6 000 ans d'histoire de l'art.",
        "desc_de": "UNESCO-Welterbe-Museumsensemble auf der Spreeinsel mit 5 weltberühmten Museen für Kunst und Archäologie.",
        "tip_en": "🎟️ Buy the 'Museum Island 1-Day Pass' (€24) to visit all 5 museums. Walk through James-Simon-Galerie central entrance hub.",
        "tip_ja": "🎟️ 5館共通1日チケット（1-Day Museum Island Pass €24）の購入が圧倒的にお得。新中央入口『ジェームズ・サイモン・ギャラリー』から入場するのが快適。",
        "tip_es": "🎟️ Compra el pase de 1 día de la Isla de los Museos (24€) para visitar los 5 museos desde el centro James-Simon-Galerie.",
        "tip_zh": "🎟️ 购买通吃5馆的“博物馆岛一日通票”（24欧元）最划算。推荐从崭新的 James-Simon-Galerie 中央入口穿行。",
        "tip_fr": "🎟️ Achetez le Pass 1 jour Île des Musées (24 €) pour accéder aux 5 musées via la James-Simon-Galerie.",
        "tip_de": "🎟️ Das 1-Tages-Ticket Museumsinsel (24 €) nutzen und zentral über die James-Simon-Galerie einsteigen.",
        "price_en": "Pass: €24", "price_ja": "通票: 24ユーロ", "price_es": "Pase: 24€", "price_zh": "通票：24 欧元", "price_fr": "Pass : 24 €", "price_de": "Museumspass: 24 €",
        "name_en": "Museum Island", "name_ja": "Museumsinsel (UNESCO)（博物館島）", "name_es": "Isla de los Museos", "name_zh": "博物馆岛", "name_fr": "Île des Musées", "name_de": "Museumsinsel"
    },
    # 4. Pergamonmuseum
    {
        "id": "b_4",
        "name": "Pergamonmuseum（ペルガモン博物館）",
        "category": "Museum & Gallery", "rating": "★4.8", "locationZone": "city",
        "lat": 52.5212, "lng": 13.3969, "kids": True, "rain": True, "shopping": False, "free": False,
        "desc_en": "World-renowned museum famed for full-scale reconstructed ancient monuments including the Babylon Ishtar Gate and Market Gate of Miletus.",
        "desc_ja": "青いバビロニアの『イシュタール門』や『ミレトスの市場門』など、古代遺跡の実物大再構築展示で知られる世界最高峰の博物館。",
        "desc_es": "Museo famoso por reconstrucciones de monumentos antiguos como la Puerta de Ishtar de Babilonia y la Puerta de Mileto.",
        "desc_zh": "以等比例重构古代庞大建筑闻名于世，陈列着蓝色的巴比伦伊什塔尔城门与米利都市场大门。",
        "desc_fr": "Musée célèbre pour ses reconstitutions monumentales dont la Porte d'Ishtar de Babylone et la Porte de Milet.",
        "de": "Weltberühmtes Museum mit imposanten Rekonstruktionen antiker Bauwerke wie dem Babylonischen Ischtar-Tor.",
        "tip_en": "⚠️ Note: North wing under major renovation until 2027 (Pergamon Altar closed); Das Panorama 360° temporary exhibition hall is open opposite!",
        "tip_ja": "⚠️ 現在北翼（ペルガモン祭壇）が大規模改修工事中（2027年まで）。対岸にある Yadegar Asisi 制作の『ペルガモン360°パノラマ館』の見学がセットで人気！",
        "tip_es": "⚠️ El Altar de Pérgamo está cerrado por obras hasta 2027. ¡Visita la exposición temporal 360° Das Panorama enfrente!",
        "tip_zh": "⚠️ 北翼帕加马祭坛正在大修中（预计至2027年）。建议前往对岸参观 Yadegar Asisi 创作的“360度3D全景体验馆”。",
        "tip_fr": "⚠️ L'autel de Pergame est fermé pour rénovation jusqu'en 2027. Visitez l'exposition 360° Das Panorama en face !",
        "tip_de": "⚠️ Das Pergamonaltar-Gebäude ist bis 2027 wegen Sanierung geschlossen. Die 360°-Panorama-Schau gegenüber besuchen!",
        "price_en": "Entry: €12", "price_ja": "入場料: 12ユーロ", "price_es": "Entrada: 12€", "price_zh": "门票：12 欧元", "price_fr": "Entrée : 12 €", "price_de": "Eintritt: 12 €",
        "name_en": "Pergamon Museum", "name_ja": "Pergamonmuseum（ペルガモン博物館）", "name_es": "Museo de Pérgamo", "name_zh": "佩加蒙博物馆", "name_fr": "Musée de Pergame", "name_de": "Pergamonmuseum"
    },
    # 5. Neues Museum
    {
        "id": "b_5",
        "name": "Neues Museum（新博物館）",
        "category": "Museum & Gallery", "rating": "★4.7", "locationZone": "city",
        "lat": 52.5202, "lng": 13.3977, "kids": True, "rain": True, "shopping": False, "free": False,
        "desc_en": "David Chipperfield-restored museum exhibiting Egyptian artifacts, prehistory collections, and the world-famous Bust of Nefertiti.",
        "desc_ja": "エジプト考古学コレクションを展示。3300年前の奇跡の美を誇る『王妃ネフェルティティの胸像』を所蔵する殿堂。",
        "desc_es": "Museo restaurado por David Chipperfield que alberga artefactos egipcios y el mundialmente famoso Busto de Nefertiti.",
        "desc_zh": "由 David Chipperfield 修缮的博物馆，展示古代埃及珍贵文物、先史时代遗物与举世闻名的“纳芙蒂蒂王后胸像”。",
        "desc_fr": "Musée restauré par David Chipperfield abritant des antiquités égyptiennes et le buste de Néfertiti.",
        "desc_de": "Von David Chipperfield saniertes Museum mit ägyptischen Sammlungen und der weltberühmten Büste der Nofretete.",
        "tip_en": "📸 Photography is STRICTLY PROHIBITED inside the Octagonal Room housing the Nefertiti Bust—enjoy looking with your own eyes!",
        "tip_ja": "📸 ネフェルティティの胸像が展示されている『八角形の間』の内部は写真・動画撮影が完全禁止！ガードマンの監視の元、自分の目でじっくり鑑賞しましょう。",
        "tip_es": "📸 ¡Está ESTRICTAMENTE PROHIBIDO fotografiar el busto de Nefertiti en la sala octogonal! Disfruta la vista en persona.",
        "tip_zh": "📸 纳芙蒂蒂胸像陈列的“八面体主厅”内严禁任何形式的拍照录像！请放下手机用肉眼近距离打量这一3300年的美学奇迹。",
        "tip_fr": "📸 Les photos sont STRICTEMENT INTERDITES dans la salle octogonale abritant le buste de Néfertiti.",
        "tip_de": "📸 Fotografieren im achteckigen Raum mit der Büste der Nofretete ist STRENGSTENS VERBOTEN!",
        "price_en": "Entry: €14", "price_ja": "入場料: 14ユーロ", "price_es": "Entrada: 14€", "price_zh": "门票：14 欧元", "price_fr": "Entrée : 14 €", "price_de": "Eintritt: 14 €",
        "name_en": "Neues Museum", "name_ja": "Neues Museum（新博物館）", "name_es": "Museo Nuevo", "name_zh": "新博物馆", "name_fr": "Nouveau Musée", "name_de": "Neues Museum"
    },
    # 6. Alte Nationalgalerie
    {
        "id": "b_5b",
        "name": "Alte Nationalgalerie（旧国立美術館）",
        "category": "Museum & Gallery", "rating": "★4.7", "locationZone": "city",
        "lat": 52.5208, "lng": 13.3982, "kids": True, "rain": True, "shopping": False, "free": False,
        "desc_en": "Greek temple-style museum exhibiting 19th-century European masterworks by Caspar David Friedrich, Monet, Renoir, and Rodin.",
        "desc_ja": "古代ギリシャ神殿風の建築。カスパー・ダーヴィト・フリードリヒのロマン派絵画やモネ、マネ、ロダンの19世紀美術を展示。",
        "desc_es": "Museo de estilo templo griego que exhibe obras maestras del siglo XIX de Friedrich, Monet y Rodin.",
        "desc_zh": "希腊神庙式建筑博物馆，陈列着19世纪浪漫主义大师 Caspar David Friedrich 绘画及莫奈、罗丹的巅峰杰作。",
        "desc_fr": "Musée en forme de temple grec présentant des chefs-d'œuvre du XIXe siècle de Friedrich, Monet et Rodin.",
        "de": "Museum im Stile eines griechischen Tempels mit Meisterwerken des 19. Jahrhunderts von Friedrich, Monet und Rodin.",
        "tip_en": "🖼️ Head to Room 3.06 to see Caspar David Friedrich's iconic romantic painting 'The Monk by the Sea' and 'Abbey in the Oakwood'.",
        "tip_ja": "🖼️ 3.06展示室へ直行！ドイツ・ロマン派の巨匠フリードリヒの代表作『海辺の修道士』と『オークの森の修道院』が並んで鑑賞できます。",
        "tip_es": "🖼️ Ve a la sala 3.06 para ver la pintura icónica de Caspar David Friedrich 'El monje junto al mar'.",
        "tip_zh": "🖼️ 直奔 3.06 展厅！亲眼观赏德国浪漫主义巨匠 Friedrich 的传世名画《海边的僧侣》与《橡树林中的修道院》。",
        "tip_fr": "🖼️ Rendez-vous dans la salle 3.06 pour admirer le tableau mythique de Caspar David Friedrich 'Le Moine au bord de la mer'.",
        "tip_de": "🖼️ In den Raum 3.06 gehen, um Caspar David Friedrichs Meisterwerke 'Der Mönch am Meer' und 'Abtei im Eichwald' zu sehen.",
        "price_en": "Entry: €12", "price_ja": "入場料: 12ユーロ", "price_es": "Entrada: 12€", "price_zh": "门票：12 欧元", "price_fr": "Entrée : 12 €", "price_de": "Eintritt: 12 €",
        "name_en": "Alte Nationalgalerie", "name_ja": "Alte Nationalgalerie（旧国立美術館）", "name_es": "Antigua Galería Nacional", "name_zh": "旧国家画廊", "name_fr": "Ancienne Galerie Nationale", "name_de": "Alte Nationalgalerie"
    },
    # 7. Bode-Museum
    {
        "id": "b_5c",
        "name": "Bode-Museum（ボーデ博物館）",
        "category": "Museum & Gallery", "rating": "★4.7", "locationZone": "city",
        "lat": 52.5218, "lng": 13.3947, "kids": True, "rain": True, "shopping": False, "free": False,
        "desc_en": "Neo-Baroque museum on the northern tip of Museum Island housing medieval and Renaissance sculptures, Byzantine art, and ancient coins.",
        "desc_ja": "博物館島の北端に立つネオ・バロック様式の水上美館。中世・ルネサンス彫刻、ビザンツ美術、世界有数のコインコレクションを所蔵。",
        "desc_es": "Museo neobarroco en el extremo norte de la Isla de los Museos con esculturas medievales, arte bizantino y monedas.",
        "desc_zh": "屹立于博物馆岛最北端的中世纪水上新巴洛克宫殿。收藏有中世纪与文艺复兴雕塑、拜占庭艺术及古钱币。",
        "desc_fr": "Musée néo-baroque à la pointe nord de l'île abritant des sculptures médiévales et la collection de pièces de monnaie.",
        "de": "Neobarockes Museum an der Nordspitze der Museumsinsel mit Skulpturen vom Mittelalter bis zur Renaissance.",
        "tip_en": "📸 Walk across Monbijoubrücke bridge for a fairytale photo of the museum dome pointing directly out over the Spree river currents.",
        "tip_ja": "📸 モンビジュー橋（Monbijoubrücke）の上からの撮影が最高！川の分岐点に立つ巨大ドームが水面に反射する素晴らしいアングルです。",
        "tip_es": "📸 Camina por el puente Monbijoubrücke para una foto del dôme sobre las aguas del río Spree.",
        "tip_zh": "📸 站在 Monbijoubrücke 铁桥之上！可拍到巨大的巴洛克圆顶矗立于两水交汇处的经典镜头。",
        "tip_fr": "📸 Traversez le pont Monbijoubrücke pour photographier le dôme du musée surgissant au-dessus de la rivière.",
        "tip_de": "📸 Auf der Monbijoubrücke fotografieren für den besten Blick auf die majestätische Kuppel an der Flussspitze.",
        "price_en": "Entry: €10", "price_ja": "入場料: 10ユーロ", "price_es": "Entrada: 10€", "price_zh": "门票：10 欧元", "price_fr": "Entrée : 10 €", "price_de": "Eintritt: 10 €",
        "name_en": "Bode Museum", "name_ja": "Bode-Museum（ボーデ博物館）", "name_es": "Museo Bode", "name_zh": "博德博物馆", "name_fr": "Musée de Bode", "name_de": "Bode-Museum"
    },
    # 8. Altes Museum
    {
        "id": "b_5d",
        "name": "Altes Museum（旧博物館）",
        "category": "Museum & Gallery", "rating": "★4.6", "locationZone": "city",
        "lat": 52.5194, "lng": 13.3989, "kids": True, "rain": True, "shopping": False, "free": False,
        "desc_en": "Karl Friedrich Schinkel's Neoclassical masterpiece featuring 18 Ionic columns facing the Lustgarten, housing Greek and Roman antiquities.",
        "desc_ja": "建築家シンケル設計の新古典主義の最高峰。18本のイオニア式柱が並ぶファサードと古代ギリシャ・ローマ彫刻コレクション。",
        "desc_es": "Obra maestra neoclásica de Schinkel con 18 columnas jónicas frente al Lustgarten con antigüedades grecorromanas.",
        "desc_zh": "建筑大师 Schinkel 设计的新古典主义奠基之作，正面拥有18根长廊爱奥尼柱，陈列古希腊古罗马雕像艺术。",
        "desc_fr": "Chef-d'œuvre néoclassique de Schinkel aux 18 colonnes ioniques abritant des antiquités grecques et romaines.",
        "de": "Neoklassizistisches Meisterwerk von Schinkel mit 18 ionischen Säulen zum Lustgarten hin.",
        "tip_en": " Step inside the central Rotunda modeled directly after Rome's Pantheon to view Roman marble statues beneath a coffered dome.",
        "tip_ja": " ローマのパンテオンを模して造られた中央ロトンダ（円形大ホール）の吹き抜けへ！古代神像が大理石ドームの下に並ぶ空間は壮観です。",
        "tip_es": " Entra en la Rotonda central inspirada en el Panteón de Roma para ver estatuas de mármol bajo la cúpula.",
        "tip_zh": " 步入仿照罗马万神殿建造的中央圆顶主厅（Rotunda）！罗马大理石神像环绕于穹顶光影之下，气势不凡。",
        "tip_fr": " Entrez dans la Rotonde centrale inspirée du Panthéon de Rome pour voir les statues sous la cúpule.",
        "tip_de": " Die nach dem Vorbild des römischen Pantheons gestaltete Rotunde im Zentrum besichtigen.",
        "price_en": "Entry: €10", "price_ja": "入場料: 10ユーロ", "price_es": "Entrada: 10€", "price_zh": "门票：10 欧元", "price_fr": "Entrée : 10 €", "price_de": "Eintritt: 10 €",
        "name_en": "Altes Museum", "name_ja": "Altes Museum（旧博物館）", "name_es": "Museo Antiguo", "name_zh": "旧博物馆", "name_fr": "Ancien Musée", "name_de": "Altes Museum"
    },
    # 9. Berliner Dom
    {
        "id": "b_6",
        "name": "Berliner Dom（ベルリン大聖堂）",
        "category": "Landmark", "rating": "★4.7", "locationZone": "city",
        "lat": 52.5190, "lng": 13.4010, "kids": True, "rain": True, "shopping": False, "free": False,
        "desc_en": "Monumental 19th-century Neo-Renaissance Protestant cathedral with a glowing turquoise dome, Hohenzollern crypt, and panoramic climb.",
        "desc_ja": "シュプレー川沿いに建つ壮麗なプロテスタント大聖堂。緑のドーム屋根、ホーエンツォレルン家の地下墓所、270段の展望回廊が見どころ。",
        "desc_es": "Catedral protestante neorrenacentista del siglo XIX con una cúpula turquesa, cripta real y mirador panorámico.",
        "desc_zh": "耸立于施普雷河畔的宏伟新文艺复兴风格新教大教堂。拥有松石绿穹顶、霍亨索伦皇室地下陵墓与270级观景步道。",
        "desc_fr": "Cathédrale protestante néo-renaissance du XIXe siècle avec un dôme turquoise, la crypte royale et un chemin de ronde.",
        "de": "Monumentaler neurenaissance-evangelischer Dom des 19. Jahrhunderts mit türkisblauer Kuppel und Hohenzollern-Gruft.",
        "tip_en": "📸 Climb the 270 steps up to the Dome Walkway (Domkuppel) for an open-air 360-degree panorama over Museum Island and Television Tower.",
        "tip_ja": "📸 270段の階段を登ってドーム外周のドーム・ウォークウェイ（Domkuppel）へ！博物館島とテレビ塔を見下ろす360度オープンエア展望が楽しめます。",
        "tip_es": "📸 Sube los 270 escalones hasta el mirador exterior de la cúpula para una vista de 360° de la Isla de los Museos y la Torre de TV.",
        "tip_zh": "📸 攀登270级台阶直达穹顶外围回廊（Domkuppel）！360度无遮挡俯瞰博物馆岛与电视塔。",
        "tip_fr": "📸 Montez les 270 marches jusqu'à la galerie extérieure du dôme pour une vue panoramique sur l’Île des Musées.",
        "tip_de": "📸 Die 270 Stufen zum Kuppelumgang aufsteigen für einen 360-Grad-Rundumblick auf die Museumsinsel und den Fernsehturm.",
        "price_en": "Entry: €10", "price_ja": "入場料: 10ユーロ", "price_es": "Entrada: 10€", "price_zh": "门票：10 欧元", "price_fr": "Entrée : 10 €", "price_de": "Eintritt: 10 €",
        "name_en": "Berlin Cathedral", "name_ja": "Berliner Dom（ベルリン大聖堂）", "name_es": "Catedral de Berlín", "name_zh": "柏林大教堂", "name_fr": "Cathédrale de Berlin", "name_de": "Berliner Dom"
    },
    # 10. Humboldt Forum & Berliner Schloss
    {
        "id": "b_6b",
        "name": "Humboldt Forum & Berliner Schloss（フンボルト・フォーラム）",
        "category": "Museum & Gallery", "rating": "★4.7", "locationZone": "city",
        "lat": 52.5175, "lng": 13.4028, "kids": True, "rain": True, "shopping": False, "free": True,
        "desc_en": "Reconstructed Berlin Palace combining baroque facades with modern architecture, housing non-European art collections and rooftop views.",
        "desc_ja": "再建された旧ベルリン王宮（バロック建築と現代建築の融合）。アジア美術館、民族学博物館、屋上展望テラスを備える巨大複合空間。",
        "desc_es": "Palacio de Berlín reconstruido que combina fachadas barrocas con arquitectura moderna, albergando colecciones etnológicas.",
        "desc_zh": "全面重建的柏林王宫。融合巴洛克雕花外墙与现代通透空间，内设亚洲艺术博物馆、民族学博物馆与顶层视界露台。",
        "desc_fr": "Palais de Berlin reconstruit alliant façades barroques et architecture moderne, abritant les collections d'art asiatique.",
        "de": "Rekonstruiertes Berliner Schloss als modernes Kulturzentrum mit den Sammlungen des Ethnologischen Museums.",
        "tip_en": "🎟️ Permanent collections (Ethnological Museum & Asian Art) are 100% FREE! Take the elevator up to the Rooftop Terrace for river views.",
        "tip_ja": "🎟️ アジア美術館と民族学博物館の常設展は入場完全無料！エレベーターで屋上テラス（Rooftop Terrace）へ登るとシュプレー川と大聖堂を見渡せます。",
        "tip_es": "🎟️ ¡Las colecciones permanentes de arte asiático y etnología son 100% GRATIS! Sube en ascensor a la terraza del tejado.",
        "tip_zh": "🎟️ 亚洲艺术馆与民族学博物馆常设展完全免费！乘电梯登顶 Rooftop Terrace 屋顶露台可俯瞰施普雷河与柏林大教堂。",
        "tip_fr": "🎟️ Les collections permanentes sont 100% GRATUITES ! Prenez l'ascenseur jusqu'au toit-terrasse pour la vue sur la rivière.",
        "tip_de": "🎟️ Freier Eintritt zu den Dauerausstellungen des Ethnologischen Museums! Mit dem Aufzug auf die Dachterrasse fahren.",
        "price_en": "Free (Rooftop €3)", "price_ja": "無料（屋上テラス3ユーロ）", "price_es": "Gratis (Azotea 3€)", "price_zh": "免费（屋顶露台3欧）", "price_fr": "Gratuit (Terrasse 3 €)", "price_de": "Kostenlos (Dachterrasse 3 €)",
        "name_en": "Humboldt Forum", "name_ja": "Humboldt Forum & Berliner Schloss（フンボルト・フォーラム）", "name_es": "Foro Humboldt", "name_zh": "洪堡论坛", "name_fr": "Humboldt Forum", "name_de": "Humboldt Forum"
    },
    # 11. East Side Gallery
    {
        "id": "b_7",
        "name": "East Side Gallery（イーストサイドギャラリー）",
        "category": "Landmark", "rating": "★4.6", "locationZone": "city",
        "lat": 52.5050, "lng": 13.4397, "kids": True, "rain": False, "shopping": False, "free": True,
        "desc_en": "1.3km stretch of the original Berlin Wall along the Spree turned into the world's longest open-air mural gallery with 100+ paintings.",
        "desc_ja": "シュプレー川沿いに残る1.3kmのベルリンの壁実物。世界各国のアーティストによる100以上の壁画が並ぶオープンエアギャラリー。",
        "desc_es": "Tramo de 1.3 km del Muro de Berlín transformado en la galería al aire libre más larga del mundo con más de 100 murales.",
        "desc_zh": "沿施普雷河伸展的1.3公里柏林墙遗址。来自世界各地的艺术家在此创作了100多幅巨幅露天涂鸦壁画。",
        "desc_fr": "Tronçon de 1,3 km du Mur de Berlin le long de la Spree transformé en la plus longue galerie à ciel ouvert du monde.",
        "de": "1,3 km langes Originalstück der Berliner Mauer an der Spree, umgestaltet zur längsten Open-Air-Galerie der Welt.",
        "tip_en": "📸 Walk from Ostbahnhof station towards Oberbaumbrücke to find Dmitri Vrubel's famous 'Fraternal Kiss' mural ('My God, Help Me to Survive This Deadly Love').",
        "tip_ja": "📸 オストバーンホフ駅からオーバーバウム橋に向かって歩くと、旧ソ連のブレジネフと東独ホネッカーの有名な壁画『兄弟のキス』があります！",
        "tip_es": "📸 Camina desde Ostbahnhof hacia Oberbaumbrücke para ver el famoso mural 'Beso Fraterno' entre Brézhnev y Honecker.",
        "tip_zh": "📸 从 Ostbahnhof 火车站方向走向 Oberbaumbrücke 桥，即可找到鼎鼎大名《兄弟之吻》（勃列日涅夫与昂纳克拥吻）壁画！",
        "tip_fr": "📸 Marchez depuis la gare Ostbahnhof vers le pont Oberbaumbrücke pour photographier la célèbre fresque du 'Baiser Fraternel'.",
        "tip_de": "📸 Vom Ostbahnhof in Richtung Oberbaumbrücke spazieren, um das berühmte Wandbild 'Bruderkuss' zu fotografieren.",
        "price_en": "Free Access", "price_ja": "見学無料", "price_es": "Acceso libre", "price_zh": "免费参观", "price_fr": "Accès libre", "price_de": "Kostenlos",
        "name_en": "East Side Gallery", "name_ja": "East Side Gallery（イーストサイドギャラリー）", "name_es": "Galería del Lado Este", "name_zh": "东边画廊", "name_fr": "East Side Gallery", "name_de": "East Side Gallery"
    },
    # 12. Gedenkstätte Berliner Mauer
    {
        "id": "b_8",
        "name": "Gedenkstätte Berliner Mauer（ベルリンの壁記念館）",
        "category": "Landmark", "rating": "★4.7", "locationZone": "city",
        "lat": 52.5352, "lng": 13.3903, "kids": True, "rain": False, "shopping": False, "free": True,
        "desc_en": "Open-air memorial site along Bernauer Straße preserving an authentic original strip of the Berlin Wall, watchtower, and border 'death strip'.",
        "desc_ja": "ベルナウアー通り沿いの広大な野外記念施設。無人地帯（Death Strip）や監視塔、分断された街の歴史がそのままの姿で保存されている。",
        "desc_es": "Sitio conmemorativo al aire libre que conserva un tramo del muro, torre de vigilancia y la 'franja de la muerte'.",
        "desc_zh": "位于 Bernauer 街的露天纪念馆。完整保留了原汁原味的柏林墙、铁丝网、监视塔与昔日无人走廊“死亡地带”。",
        "desc_fr": "Mémorial en plein air le long de la Bernauer Straße conservant un tronçon authentique du Mur et son 'No Man's Land'.",
        "de": "Gedenkstätte an der Bernauer Straße mit dem letzten erhaltenen Stück der Berliner Mauer samt Todesstreifen und Wachturm.",
        "tip_en": "📸 Climb to the 5th-floor observation tower inside the Documentation Centre for a top-down view straight into the preserved 'Death Strip' border section.",
        "tip_ja": "📸 通りの向かいにあるドキュメンテーションセンター5階の無料展望タワーへ！保存された『無人地帯（Death Strip）』の構造を真上から俯瞰できます。",
        "tip_es": "📸 Sube a la torre de observación en la 5ª planta del Centro de Documentación para ver la 'Franja de la Muerte' desde arriba.",
        "tip_zh": "📸 登上一路之隔的档案中心5楼免费展望塔！从高处直视完整保存的“死亡地带”防护铁丝网与监视塔。",
        "tip_fr": "📸 Montez à la tour d'observation du 5e étage du Centre de Documentation pour voir le 'No Man's Land' conservé d'en haut.",
        "tip_de": "📸 Auf den Aussichtsturm im 5. Stock des Dokumentationszentrums steigen, um den erhaltenen 'Todesstreifen' von oben zu sehen.",
        "price_en": "Free Entry", "price_ja": "入場無料", "price_es": "Entrada libre", "price_zh": "免费开放", "price_fr": "Gratuit", "price_de": "Kostenlos",
        "name_en": "Berlin Wall Memorial", "name_ja": "Gedenkstätte Berliner Mauer（ベルリンの壁記念館）", "name_es": "Memorial del Muro de Berlín", "name_zh": "柏林墙纪念馆", "name_fr": "Mémorial du Mur de Berlin", "name_de": "Gedenkstätte Berliner Mauer"
    },
    # 13. Checkpoint Charlie & Mauermuseum
    {
        "id": "b_10b",
        "name": "Checkpoint Charlie & Mauermuseum（チェックポイント・チャーリー＆壁博物館）",
        "category": "Landmark", "rating": "★4.4", "locationZone": "city",
        "lat": 52.5075, "lng": 13.3903, "kids": True, "rain": True, "shopping": False, "free": True,
        "desc_en": "Famed Cold War border crossing between US and Soviet sectors, featuring the iconic guard house and Mauermuseum detailing escape stories.",
        "desc_ja": "冷戦時代の米ソ軍対立の最前線検問所跡。星条旗と兵士の顔写真ボード、東独からの命がけの脱出装置を展示する壁博物館。",
        "desc_es": "Famoso paso fronterizo de la Guerra Fría entre los sectores estadounidense y soviético con la caseta de guardia.",
        "desc_zh": "冷战时期美苏两大阵营对峙的前沿界线关卡。保存有当年岗亭设施与展示各种惊险脱逃载具的墙博物馆。",
        "desc_fr": "Poste-frontière emblématique de la Guerre Froide entre les secteurs américain et soviétique avec son musée des évadés.",
        "de": "Bekanntester ehemaliger Grenzübergang der Kalten Krieges zwischen dem US-amerikanischen und sowjetischen Sektor.",
        "tip_en": "📸 Photographing the outdoor guard booth and border signs is FREE. Avoid paying scam actors dressed in fake military uniforms for photos!",
        "tip_ja": "📸 地上の警備小屋や有名な「You are leaving the American Sector」看板の写真撮影は無料。軍服を着て有料写真を請求してくるストリート俳優には注意！",
        "tip_es": "📸 Fotografiar la caseta exterior es GRATIS. ¡Evita pagar a actores disfrazados de soldados por tomar fotos!",
        "tip_zh": "📸 街头岗亭与标志牌拍照完全免费！请注意切勿理会搭讪并讨要拍照费用的军装扮演人员。",
        "tip_fr": "📸 La photo de la aubette extérieure est GRATUITE. Évitez de payer les comédiens déguisés en soldats !",
        "tip_de": "📸 Das Fotografieren des Kontrollhäuschens ist KOSTENLOS. Lassen Sie sich nicht von gefälschten 'Grenzsoldaten' abkassieren!",
        "price_en": "Street Free (Museum €17.50)", "price_ja": "街頭無料（博物館17.50ユーロ）", "price_es": "Calle gratis (Museo 17,50€)", "price_zh": "街头免费（博物馆17.50欧）", "price_fr": "Rue gratuite (Musée 17,50 €)", "price_de": "Platz frei (Museum 17,50 €)",
        "name_en": "Checkpoint Charlie", "name_ja": "Checkpoint Charlie & Mauermuseum（チェックポイント・チャーリー＆壁博物館）", "name_es": "Checkpoint Charlie", "name_zh": "查理检查站", "name_fr": "Checkpoint Charlie", "name_de": "Checkpoint Charlie"
    },
    # 14. Topographie des Terrors
    {
        "id": "b_9",
        "name": "Topographie des Terrors（トポグラフィー・オブ・テラー）",
        "category": "Museum & Gallery", "rating": "★4.7", "locationZone": "city",
        "lat": 52.5065, "lng": 13.3838, "kids": False, "rain": True, "shopping": False, "free": True,
        "desc_en": "Free documentation center built on the former headquarters of the Gestapo and SS, detailing Nazi war crimes and state terror.",
        "desc_ja": "第二次大戦中のゲシュタポおよびSS（親衛隊）本部跡地にある歴史ドキュメンテーションセンター。ナチス恐怖政治の歴史を伝える重要な無料施設。",
        "desc_es": "Centro de documentación gratuito construido en la antigua sede de la Gestapo y las SS sobre los crímenes nazis.",
        "desc_zh": "建于盖世太保（Gestapo）与党卫军（SS）总部旧址的免费历史档案中心。严谨反思纳粹国家恐怖统治历史。",
        "desc_fr": "Centre de documentation gratuit construit sur l'ancien siège de la Gestapo et des SS retraçant la terreur nazie.",
        "de": "Kostenloses Dokumentationszentrum auf dem ehemaligen Gelände des Reichssicherheitshauptamts von Gestapo und SS.",
        "tip_en": "🚶 Walk along the outer trench wall exhibition facing Niederkirchnerstraße—one of the longest preserved original sections of the Berlin Wall stands directly above!",
        "tip_ja": "🚶 屋内展示だけでなく、屋外の壕沿いにあるパネル展示と、その真上に残る柏林の壁（ベルリンの壁）の原形を合わせて見学するのがポイントです。",
        "tip_es": "🚶 Recorre la exposición al aire libre junto al foso para ver el tramo del Muro de Berlín que se conserva justo encima.",
        "tip_zh": "🚶 除了室内展厅，请务必漫步于壕沟外侧露天长廊展区，正上方即保留着长达数百米的柏林墙混凝土原貌。",
        "tip_fr": "🚶 Parcourez l'exposition extérieure le long de la tranchée pour voir le tronçon du Mur conservé juste au-dessus.",
        "tip_de": "🚶 Den Außenrundgang an der Grabenwand entlanggehen: Direkt darüber steht ein langes Originalstück der Berliner Mauer.",
        "price_en": "Free Entry", "price_ja": "入場無料", "price_es": "Entrada libre", "price_zh": "免费参观", "price_fr": "Gratuit", "price_de": "Kostenlos",
        "name_en": "Topography of Terror", "name_ja": "Topographie des Terrors（トポグラフィー・オブ・テラー）", "name_es": "Topografía del Terror", "name_zh": "恐怖地形图", "name_fr": "Topographie de la Terreur", "name_de": "Topographie des Terrors"
    },
    # 15. Holocaust-Mahnmal
    {
        "id": "b_10",
        "name": "Holocaust-Mahnmal（ホロコースト慰霊碑）",
        "category": "Landmark", "rating": "★4.7", "locationZone": "city",
        "lat": 52.5139, "lng": 13.3786, "kids": False, "rain": False, "shopping": False, "free": True,
        "desc_en": "Moving memorial consisting of 2,711 grey concrete stelae arranged in a grid pattern on a sloping field, with an underground Information Centre.",
        "desc_ja": "2,711基の灰色コンクリートの石柱（ステレ）が並ぶ傾斜地。地下には犠牲となったユダヤ人の手紙や写真を展示する地下情報センターを併設。",
        "desc_es": "Monumento formado por 2.711 estelas de hormigón gris con un Centro de Información subterráneo.",
        "desc_zh": "由2711块高低起伏的灰色混凝土柱巨阵构成的追思网格。地下设有展现受害者信件与照片地下信息中心。",
        "desc_fr": "Mémorial poignant composé de 2 711 stèles en béton gris disposées en réseau avec un centre d'information souterrain.",
        "de": "Denkmal aus 2.711 grauen Betonstelen auf einem wellenförmigen Feld mit unterirdischem Ort der Information.",
        "tip_en": "🧥 Respectful behavior is strictly required (no running, climbing, or jumping on stelae). Visit the underground Information Centre via the southeast corner stairs.",
        "tip_ja": "🧥 コンクリート柱の上に乗ったり跳び移る行為は厳禁！南東角の階段から地下の無料情報センター（Information Centre）へ入り、犠牲者の手紙や記録を静かに閲覧しましょう。",
        "tip_es": "🧥 ¡Está prohibido subirse o saltar entre las estelas! Visita el Centro de Información subterráneo por la esquina sureste.",
        "tip_zh": "🧥 庄重提示：严禁攀爬或在水泥柱间跳跃！请从东南角的阶梯下至地下免费信息中心，静心阅读历史文献。",
        "tip_fr": "🧥 Interdiction absolue de grimper sur les stèles ! Descendez au centre d'information souterrain par l'escalier sud-est.",
        "tip_de": "🧥 Das Besteigen und Springen auf den Stelen ist streng untersagt! Das kostenlose unterirdische Ort der Information besuchen.",
        "price_en": "Free Entry", "price_ja": "入場無料", "price_es": "Entrada libre", "price_zh": "免费参观", "price_fr": "Gratuit", "price_de": "Kostenlos",
        "name_en": "Memorial to the Murdered Jews of Europe", "name_ja": "Holocaust-Mahnmal（ホロコースト慰霊碑）", "name_es": "Memorial del Holocausto", "name_zh": "欧洲被害犹太人纪念碑", "name_fr": "Mémorial aux Juifs assassinés d'Europe", "name_de": "Holocaust-Mahnmal"
    },
    # 16. Berliner Fernsehturm
    {
        "id": "b_11",
        "name": "Berliner Fernsehturm（ベルリンテレビ塔）",
        "category": "Landmark", "rating": "★4.5", "locationZone": "city",
        "lat": 52.5208, "lng": 13.4094, "kids": True, "rain": True, "shopping": False, "free": False,
        "desc_en": "Germany's tallest structure (368m) built in 1969 with an observation deck at 203m and a 360° rotating sphere restaurant.",
        "desc_ja": "高さ368mを誇るドイツ最高の建造物。地上203mの展望台と、1時間に1回転する球形回転レストラン『Sphere』からベルリンを一望。",
        "desc_es": "La estructura más alta de Alemania (368m) con mirador a 203m y un restaurante giratorio.",
        "desc_zh": "高368米的德国第一高建筑。203米高处设有全景观景台与每小时旋转一周的“Sphere”球形旋转餐厅。",
        "desc_fr": "La plus haute structure d'Allemagne (368m) avec plateforme d'observation à 203m et restaurant panoramique tournant.",
        "de": "Das höchste Bauwerk Deutschlands (368m) mit einer Aussichtsetage auf 203m und einem rotierenden Kugelrestaurant.",
        "tip_en": "🎟️ Fast-track time-slot ticket booked online is ESSENTIAL to skip the 2-hour queue for the high-speed elevator!",
        "tip_ja": "🎟️ 高速エレベーターの2時間待ち行列を回避するため、日時指定の『Fast Track Ticket』をネットで事前購入するのが鉄則です！",
        "tip_es": "🎟️ ¡Es IMPRESCINDIBLE comprar la entrada Fast View por internet para saltarte las 2 horas de cola del ascensor!",
        "tip_zh": "🎟️ 强烈建议提前在官网预订免排队定时票（Fast View Ticket）！否则现场等候高速电梯排队通常长达2小时。",
        "tip_fr": "🎟️ Réservation d'un billet coupe-file en ligne INDISPENSABLE pour éviter 2h de file d'attente à l'ascenseur !",
        "tip_de": "🎟️ Fast-View-Ticket unbedingt vorab online buchen, um bis zu 2 Stunden Wartezeit am Aufzug zu vermeiden!",
        "price_en": "Entry: €22.50", "price_ja": "入場料: 22.50ユーロ", "price_es": "Entrada: 22,50€", "price_zh": "门票：22.50 欧元", "price_fr": "Entrée : 22,50 €", "price_de": "Eintritt: 22,50 €",
        "name_en": "Berlin TV Tower", "name_ja": "Berliner Fernsehturm（ベルリンテレビ塔）", "name_es": "Torre de Televisión de Berlín", "name_zh": "柏林电视塔", "name_fr": "Tour de télévision de Berlin", "name_de": "Berliner Fernsehturm"
    },
    # 17. Alexanderplatz & Weltzeituhr
    {
        "id": "b_11b",
        "name": "Alexanderplatz & Weltzeituhr（アレクサンダー広場＆世界時計）",
        "category": "Landmark", "rating": "★4.5", "locationZone": "city",
        "lat": 52.5219, "lng": 13.4132, "kids": True, "rain": False, "shopping": True, "free": True,
        "desc_en": "Bustling central square of former East Berlin featuring Erich John's 1969 World Clock (Weltzeituhr) showing times in 148 cities.",
        "desc_ja": "旧東ベルリンの中心大広場。148の都市の現在時刻を同時に表示する1969年設置のレトロモダンな『世界時計（Weltzeituhr）』がシンボル。",
        "desc_es": "Gran plaza del antiguo Berlín Oriental con el Reloj Mundial de 1969 que muestra la hora de 148 ciudades.",
        "desc_zh": "昔日东柏林的核心大广场。矗立着建于1969年的古董“世界时钟”（Weltzeituhr），可同时显示全球148个城市的时间。",
        "desc_fr": "Grande place centrale de l'ancien Berlin-Est avec l'Horloge Universelle de 1969 indiquant l'heure dans 148 villes.",
        "de": "Zentraler Platz im ehemaligen Ost-Berlin mit der berühmten Weltzeituhr von 1969 mit 148 Städtenamen.",
        "tip_en": "📸 Stand beneath the rotating 24-hour metal cylinder of the Weltzeituhr to locate your home timezone engraved on the brass ring!",
        "tip_ja": "📸 くるくる回転する24時間の金属製シリンダーの下に立ち、リングに刻まれた自分のホーム都市のタイムゾーンを探すのがお約束の撮影スタイル！",
        "tip_es": "📸 Pónte debajo del cilindro giratorio de 24 horas del Reloj Mundial para buscar la zona horaria de tu ciudad.",
        "tip_zh": "📸 站在旋转的24小时金属圆环下方，抬头寻找刻在黄铜环上的自己家乡城市的时区与名字！",
        "tip_fr": "📸 Mettez-vous sous le cylindre rotatif de l'Horloge Universelle pour repérer le nom de votre ville d'origine.",
        "tip_de": "📸 Unter den rotierenden Zylinder der Weltzeituhr stellen und die Heimatzeitzone am Metallring suchen.",
        "price_en": "Free Access", "price_ja": "見学無料", "price_es": "Acceso libre", "price_zh": "免费参观", "price_fr": "Accès libre", "price_de": "Kostenlos",
        "name_en": "Alexanderplatz & World Clock", "name_ja": "Alexanderplatz & Weltzeituhr（アレクサンダー広場＆世界時計）", "name_es": "Alexanderplatz y Reloj Mundial", "name_zh": "亚历山大广场与世界时钟", "name_fr": "Alexanderplatz et Horloge Universelle", "name_de": "Alexanderplatz & Weltzeituhr"
    },
    # 18. Gendarmenmarkt
    {
        "id": "b_11c",
        "name": "Gendarmenmarkt（ジャンダルメンマルクト）",
        "category": "Landmark", "rating": "★4.8", "locationZone": "city",
        "lat": 52.5136, "lng": 13.3928, "kids": True, "rain": False, "shopping": False, "free": True,
        "desc_en": "Europe's most harmonious square framed by the French Cathedral (Französischer Dom), German Cathedral (Deutscher Dom), and Konzerthaus.",
        "desc_ja": "フランス大聖堂、ドイツ大聖堂、コンツェルトハウス（劇場）が完璧な左右対称で並ぶヨーロッパで最も美しい広場の一つ。",
        "desc_es": "Una de las plazas más bellas de Europa enmarcada por la Catedral Francesa, Catedral Alemana y el Konzerthaus.",
        "desc_zh": "欧洲最为和谐优美的古典广场之一。由对称分布的法国大教堂、德国大教堂与音乐厅围合而成。",
        "desc_fr": "L'une des plus belles places d'Europe bordée par le Dôme Français, le Dôme Allemand et le Konzerthaus.",
        "de": "Einer der schönsten Plätze Europas, eingerahmt vom Französischen Dom, Deutschen Dom und dem Konzerthaus.",
        "tip_en": "☕ Enjoy hot chocolate and handmade pralines at Rausch Schokoladenhaus directly on the corner facing the square!",
        "tip_ja": "☕ 広場の角にある老舗高級チョコ店『Rausch Schokoladenhaus』2階のカフェテラスで、広場を眺めながらいただく濃厚なホットチョコレートが絶品！",
        "tip_es": "☕ ¡Disfruta de chocolate caliente y pralinés en la chocolatería Rausch Schokoladenhaus en la esquina de la plaza!",
        "tip_zh": "☕ 推荐在广场转角处的百乐经典巧克力总店 Rausch Schokoladenhaus 2楼选座，品尝纯正浓郁的热巧克力。",
        "tip_fr": "☕ Dégustez un chocolat chaud et des pralinés chez Rausch Schokoladenhaus au coin de la place !",
        "tip_de": "☕ Im berühmten Rausch Schokoladenhaus an der Platzecke heiße Trinkschokolade und Pralinen genießen!",
        "price_en": "Free Access", "price_ja": "見学無料", "price_es": "Acceso libre", "price_zh": "免费参观", "price_fr": "Accès libre", "price_de": "Kostenlos",
        "name_en": "Gendarmenmarkt", "name_ja": "Gendarmenmarkt（ジャンダルメンマルクト）", "name_es": "Gendarmenmarkt", "name_zh": "御林广场", "name_fr": "Gendarmenmarkt", "name_de": "Gendarmenmarkt"
    },
    # 19. Kaiser-Wilhelm-Gedächtniskirche
    {
        "id": "b_11d",
        "name": "Kaiser-Wilhelm-Gedächtniskirche（カイザー・ヴィルヘルム記念教会）",
        "category": "Landmark", "rating": "★4.6", "locationZone": "city",
        "lat": 52.5047, "lng": 13.3353, "kids": True, "rain": True, "shopping": False, "free": True,
        "desc_en": "Symbol of West Berlin featuring the hollow ruined spire of the 1895 Neo-Romanesque church damaged in WWII next to Egon Eiermann's blue glass hexagonal chapel.",
        "desc_ja": "第二次大戦の空襲で破壊された旧教会の尖塔廃墟（虫歯の塔）と、エゴン・アイアーマン設計の青いガラスが神秘的な新教会。",
        "desc_es": "Símbolo de Berlín Oeste con la torre en ruinas de la iglesia de 1895 junto a la capilla hexagonal moderna de cristal azul.",
        "desc_zh": "西柏林标志建筑。保留有二战空袭中被炸毁的旧教堂空心尖塔废墟，与旁边以蓝光玻璃打造的六角形现代新教堂。",
        "desc_fr": "Symbole de Berlin-Ouest avec le clocher en ruine de l'église de 1895 et la nouvelle chapelle hexagonale aux dalles de verre bleu.",
        "de": "Wahrzeichen West-Berlins mit der Turmruine der alten Kirche von 1895 und der modernen blauen Wabenkapelle.",
        "tip_en": "☀️ Step inside the new octagonal chapel next to the ruined tower—20,000 blue stained-glass tiles from Chartres illuminate the interior in intense azure light (Free entry).",
        "tip_ja": "☀️ 廃墟の塔の横にある8角形の新教会内部へお入りください！フランス・シャルトル製の2万枚の青いステンドグラスが創り出す神秘的な青い光の空間は必見（無料）。",
        "tip_es": "☀️ ¡Entra a la capilla octogonal junto a la torre! Las 20.000 vidrieras de cristal azul de Chartres iluminan el interior.",
        "tip_zh": "☀️ 务必步入废墟塔楼旁新的八角形新教堂！内墙镶嵌着20000块法国沙特尔蓝色彩绘玻璃，透射出深邃圣洁的湛蓝光芒。免费。",
        "tip_fr": "☀️ Entrez dans la nouvelle chapelle hexagonale : 20 000 dalles de verre bleu de Chartres baignent l'espace d'une lumière bleue féerique (gratuit).",
        "tip_de": "☀️ Das Innere der neuen Wabenkapelle betreten: 20.000 blaue Glassteine aus Chartres tauchen den Raum in mystisches blaues Licht (kostenlos).",
        "price_en": "Free Entry", "price_ja": "入場無料", "price_es": "Entrada libre", "price_zh": "免费参观", "price_fr": "Gratuit", "price_de": "Kostenlos",
        "name_en": "Kaiser Wilhelm Memorial Church", "name_ja": "Kaiser-Wilhelm-Gedächtniskirche（カイザー・ヴィルヘルム記念教会）", "name_es": "Iglesia Conmemorativa Kaiser Wilhelm", "name_zh": "威廉皇帝纪念教堂", "name_fr": "Église du Souvenir de Berlin", "name_de": "Kaiser-Wilhelm-Gedächtniskirche"
    },
    # 20. Schloss Charlottenburg
    {
        "id": "b_12",
        "name": "Schloss Charlottenburg（シャルロッテンブルク宮殿）",
        "category": "Landmark", "rating": "★4.7", "locationZone": "city",
        "lat": 52.5206, "lng": 13.2956, "kids": True, "rain": True, "shopping": False, "free": False,
        "desc_en": "Sumptuous 17th-century Baroque and Rococo royal palace of the Hohenzollern dynasty surrounded by expansive French and English gardens.",
        "desc_ja": "プロイセン王家ホーエンツォレルン家の本宮殿。豪華なバロック・ロココ調の室内、磁器の間、広大な宮殿庭園が広がる。",
        "desc_es": "Suntuoso palacio barroco y rococó del siglo XVII de la dinastía Hohenzollern con amplios jardines.",
        "desc_zh": "霍亨索伦皇室奢华的17世纪巴洛克与洛可可风格宫殿，拥有瓷器展厅与广阔的法式英式宫廷花园。",
        "desc_fr": "Somptueux palais royal des Hohenzollern des XVIIe et XVIIIe siècles entouré de vastes jardins à la française et à l'anglaise.",
        "de": "Prachtvolles Barock- und Rokokoschloss der Hohenzollern-Dynastie aus dem 17. Jahrhundert mit weitläufiger Gartenanlage.",
        "tip_en": "📸 Stroll into the palace gardens for FREE behind the palace; walk around the lake to photograph the palace dome reflecting in the water.",
        "tip_ja": "📸 宮殿裏手の広大な庭園エリア（Schlossgarten）は入園無料！池の反対側へ回り込むと、水面にドーム屋根が映る絵はがき写真が撮れます。",
        "tip_es": "📸 El acceso al gran jardín trasero es GRATUITO. Camina alrededor del lago para fotografiar el palacio reflejado.",
        "tip_zh": "📸 宫殿后方的皇家公立花园完全免费开放！绕湖半周，可拍到浅翠绿宫殿穹顶倒映在湖面上的绝佳视角。",
        "tip_fr": "📸 L'accès aux grands jardins à l'arrière est GRATUIT. Faites le tour du lac pour photographier le château.",
        "tip_de": "📸 Der weitläufige Schlossgarten auf der Rückseite ist KOSTENLOS zugänglich. Spaziergang um den See machen!",
        "price_en": "Palace: €17 (Gardens Free)", "price_ja": "宮殿: 17ユーロ（庭園無料）", "price_es": "Palacio: 17€ (Jardines gratis)", "price_zh": "宫殿：17 欧元（花园免费）", "price_fr": "Palais : 17 € (Jardins gratuits)", "price_de": "Schloss: 17 € (Garten frei)",
        "name_en": "Charlottenburg Palace", "name_ja": "Schloss Charlottenburg（シャルロッテンブルク宮殿）", "name_es": "Palacio de Charlottenburg", "name_zh": "夏洛滕堡宫", "name_fr": "Château de Charlottenburg", "name_de": "Schloss Charlottenburg"
    },
    # 21. Kulturforum & Gemäldegalerie
    {
        "id": "b_12b",
        "name": "Kulturforum & Gemäldegalerie（絵画館）",
        "category": "Museum & Gallery", "rating": "★4.8", "locationZone": "city",
        "lat": 52.5086, "lng": 13.3653, "kids": True, "rain": True, "shopping": False, "free": False,
        "desc_en": "World-class art museum holding one of the finest collections of European Old Master paintings from the 13th to 18th centuries including Vermeer, Rembrandt, and Raphael.",
        "desc_ja": "13〜18世紀のヨーロッパ古典絵画の最高峰。フェルメール（2点）、レンブラント（16点）、ラファエロ、ボッティチェッリの名作が一堂に集結。",
        "desc_es": "Gran museo de arte con una de las mejores colecciones de maestros clásicos europeos del siglo XIII al XVIII.",
        "desc_zh": "欧洲古典油画最高殿堂之一，藏有13至18世纪巨匠杰作，包含维米尔（2幅）、伦勃朗（16幅）与拉斐尔珍品。",
        "desc_fr": "Musée d'art majeur abritant une collection exceptionnelle de peintures européennes du XIIIe au XVIIIe siècle.",
        "de": "Weltberühmte Gemäldegalerie mit einer der bedeutendsten Sammlungen europäischer Malerei des 13. bis 18. Jahrhunderts.",
        "tip_en": "🖼️ Head straight to Room 18 to view Johannes Vermeer's breathtaking 'Woman with a Pearl Necklace' and 'The Glass of Wine'.",
        "tip_ja": "🖼️ 第18展示室へ直行！世界に約35点しか現存しないヨハネス・フェルメールの『真珠の首飾りの女』と『ワイングラスを持つ娘』を静かに鑑賞できます。",
        "tip_es": "🖼️ Dirígete a la sala 18 para ver las obras maestras de Johannes Vermeer 'Joven con collar de perlas' y 'La copa de vino'.",
        "tip_zh": "🖼️ 直奔18号展厅！近距离独享维米尔传世名画《戴珍珠项链的女人》与《拿酒杯的少女》。",
        "tip_fr": "🖼️ Rendez-vous dans la salle 18 pour admirer les chefs-d'œuvre de Vermeer 'La Dame au collier de perles' et 'Le Verre de vin'.",
        "tip_de": "🖼️ Direkt in Raum 18 gehen, um Johannes Vermeers Meisterwerke 'Junge Dame mit Perlenhalsband' und 'Das Glas Wein' zu sehen.",
        "price_en": "Entry: €14", "price_ja": "入場料: 14ユーロ", "price_es": "Entrada: 14€", "price_zh": "门票：14 欧元", "price_fr": "Entrée : 14 €", "price_de": "Eintritt: 14 €",
        "name_en": "Gemäldegalerie", "name_ja": "Kulturforum & Gemäldegalerie（絵画館）", "name_es": "Gemäldegalerie de Berlín", "name_zh": "柏林画廊", "name_fr": "Gemäldegalerie", "name_de": "Gemäldegalerie"
    },
    # 22. Neue Nationalgalerie
    {
        "id": "b_12c",
        "name": "Neue Nationalgalerie（新国立美術館）",
        "category": "Museum & Gallery", "rating": "★4.7", "locationZone": "city",
        "lat": 52.5066, "lng": 13.3675, "kids": True, "rain": True, "shopping": False, "free": False,
        "desc_en": "Mies van der Rohe's iconic glass-and-steel modernist pavilion reopened in 2021 after David Chipperfield renovation, exhibiting 20th-century art.",
        "desc_ja": "モダニズム建築の巨匠ミース・ファン・デル・ローエ晩年の傑作（ガラスと黒い鉄骨の空中殿堂）。20世紀のモダンアート作品を展示。",
        "desc_es": "Pabellón modernista de cristal y acero diseñado por Mies van der Rohe dedicado al arte del siglo XX.",
        "desc_zh": "现代主义建筑大师密斯·凡·德·罗（Mies van der Rohe）的封山之作，黑钢与通透大玻璃外墙与20世纪先锋艺术在此交融。",
        "desc_fr": "Pavillon moderniste en verre et acier de Mies van der Rohe abritant les collections d'art du XXe siècle.",
        "de": "Ikone der klassischen Moderne von Ludwig Mies van der Rohe mit Ausstellungen zur Kunst des 20. Jahrhunderts.",
        "tip_en": " Order coffee and pastry at the cafe in the lower garden level to admire the sunken sculpture garden by Calder and Moore.",
        "tip_ja": " 地下の彫刻庭園を見下ろすカフェでコーヒー休憩！アレクサンダー・カルダーやヘンリー・ムーアの巨大彫刻が並ぶ静かな中庭空間です。",
        "tip_es": " Toma un café en la planta inferior contemplando el jardín de esculturas de Alexander Calder y Henry Moore.",
        "tip_zh": " 在地下通往雕塑庭园的咖啡厅选座！隔窗观赏 Alexander Calder 与 Henry Moore 的大型现代雕塑长廊。",
        "tip_fr": " Prenez un café au niveau inférieur donnant sur le jardin de sculptures d'Alexander Calder.",
        "tip_de": " Im Untergeschoss im Café mit Blick auf den abgesenkten Skulpturengarten von Calder und Moore entspannen.",
        "price_en": "Entry: €14", "price_ja": "入場料: 14ユーロ", "price_es": "Entrada: 14€", "price_zh": "门票：14 欧元", "price_fr": "Entrée : 14 €", "price_de": "Eintritt: 14 €",
        "name_en": "Neue Nationalgalerie", "name_ja": "Neue Nationalgalerie（新国立美術館）", "name_es": "Nueva Galería Nacional", "name_zh": "新国家画廊", "name_fr": "Nouvelle Galerie Nationale", "name_de": "Neue Nationalgalerie"
    },
    # 23. Hamburger Bahnhof
    {
        "id": "b_18",
        "name": "Hamburger Bahnhof - Nationalgalerie der Gegenwart（ハンブルガー・バーンホフ現代美術館）",
        "category": "Museum & Gallery", "rating": "★4.6", "locationZone": "city",
        "lat": 52.5283, "lng": 13.3722, "kids": True, "rain": True, "shopping": False, "free": False,
        "desc_en": "Contemporary art museum housed in a converted 1847 historic railway station displaying works by Joseph Beuys, Andy Warhol, and Cy Twombly.",
        "desc_ja": "1847年建造の旧鉄道駅ネオ・レネサンス館をリノベした現代美術館。ヨーゼフ・ボイス、アンディ・ウォーホル、キース・ヘリングの大作を展示。",
        "desc_es": "Museo de arte contemporáneo en una antigua estación de tren de 1847 con obras de Warhol y Joseph Beuys.",
        "desc_zh": "利用1847年旧火车站大楼重构的当代美术馆。展示 Joseph Beuys、Andy Warhol 及 Keith Haring 等战后先锋艺术大作。",
        "desc_fr": "Musée d'art contemporain installé dans une ancienne gare ferroviaire de 1847 (œuvres de Beuys, Warhol).",
        "de": "Museum für Gegenwartskunst im historischen Bahnhofsgebäude von 1847 mit Werken von Beuys, Warhol und Kiefer.",
        "tip_en": " Double-check your ticket for access to the Rieckhallen rear galleries—huge industrial halls showcasing massive light & video installations!",
        "tip_ja": " リニューアルした奥の旧貨物保管倉庫『Rieckhallen』大ホールへの移動をお忘れなく！巨大な光や映像の体験型インスタレーションが展示されています。",
        "tip_es": " ¡No olvides visitar las galerías Rieckhallen en la parte posterior con grandes instalaciones de luz y vídeo!",
        "tip_zh": " 务必走入后方的 Rieckhallen 工业铁道长廊！展出庞大的光影、声学与大型装置跨界艺术展。",
        "tip_fr": " Ne manquez pas les grandes hales de la Rieckhallen à l'arrière avec leurs installations monumentales !",
        "tip_de": " Unbedingt die riesigen Ausstellungshallen der Rieckhallen im hinteren Bereich mit Rauminstallationen besuchen!",
        "price_en": "Entry: €14", "price_ja": "入場料: 14ユーロ", "price_es": "Entrada: 14€", "price_zh": "门票：14 欧元", "price_fr": "Entrée : 14 €", "price_de": "Eintritt: 14 €",
        "name_en": "Hamburger Bahnhof Museum", "name_ja": "Hamburger Bahnhof - Nationalgalerie der Gegenwart（ハンブルガー・バーンホフ現代美術館）", "name_es": "Hamburger Bahnhof", "name_zh": "汉堡车站现代艺术馆", "name_fr": "Hamburger Bahnhof", "name_de": "Hamburger Bahnhof"
    },
    # 24. Jüdisches Museum Berlin
    {
        "id": "b_13",
        "name": "Jüdisches Museum Berlin（ユダヤ博物館）",
        "category": "Museum & Gallery", "rating": "★4.6", "locationZone": "city",
        "lat": 52.5023, "lng": 13.3949, "kids": True, "rain": True, "shopping": False, "free": True,
        "desc_en": "Architectural masterpiece by Daniel Libeskind with a zigzag shape, featuring the Holocaust Tower and interactive exhibits on German-Jewish history.",
        "desc_ja": "ダニエル・リベスキンド設計のジグザグ建築。ホロコーストの塔や『落ち葉（Shalechet）』の体験型アートで知られる博物館。",
        "desc_es": "Obra maestra arquitectónica de Daniel Libeskind con diseño en zigzag y la sobrecogedora Torre del Holocausto.",
        "desc_zh": "由 Daniel Libeskind 设计的解构主义锯齿状标志建筑，包含震撼人心的“大屠杀高塔”与“落叶”互动装置艺术。",
        "desc_fr": "Chef-d'œuvre architectural de Daniel Libeskind en forme de zigzag présentant l'histoire des Juifs en Allemagne.",
        "de": "Architektonisches Meisterwerk von Daniel Libeskind im Zickzack-Design zur deutsch-jüdischen Geschichte.",
        "tip_en": "🎟️ Permanent exhibition entrance is 100% FREE! Step on Menashe Kadishman's 10,000 screaming metal face plates in the Memory Void.",
        "tip_ja": "🎟️ 常設展示は完全入場無料！空間芸術『記憶の真空（Memory Void）』で、1万個の叫ぶ金属顔プレートの上を歩く体験は鳥肌モノの衝撃です。",
        "tip_es": "🎟️ ¡La entrada a la exposición permanente es 100% GRATUITA! Camina sobre las 10.000 caras de metal en la sala Memory Void.",
        "tip_zh": "🎟️ 常设展完全免费！走入“记忆真空”（Memory Void）展厅，亲脚踩踏在10000块发出尖锐金属碰撞声的面具金属片之上，震撼人心。",
        "tip_fr": "🎟️ L'exposition permanente est 100% GRATUITE ! Marchez sur les 10 000 visages en métal dans l'espace Memory Void.",
        "tip_de": "🎟️ Die Dauerausstellung ist 100% KOSTENLOS! Das begehbare Kunstwerk 'Schalechet' (Memory Void) im Untergeschoss erleben.",
        "price_en": "Free (Permanent Exhibition)", "price_ja": "無料（常設展）", "price_es": "Gratis (Exposición permanente)", "price_zh": "免费（常设展）", "price_fr": "Gratuit (Expo permanente)", "price_de": "Kostenlos (Dauerausstellung)",
        "name_en": "Jewish Museum Berlin", "name_ja": "Jüdisches Museum Berlin（ユダヤ博物館）", "name_es": "Museo Judío de Berlín", "name_zh": "柏林犹太人博物馆", "name_fr": "Musée juif de Berlin", "name_de": "Jüdisches Museum Berlin"
    },
    # 25. Deutsches Historisches Museum (DHM)
    {
        "id": "b_13b",
        "name": "Deutsches Historisches Museum (DHM)（ドイツ歴史博物館）",
        "category": "Museum & Gallery", "rating": "★4.7", "locationZone": "city",
        "lat": 52.5178, "lng": 13.3969, "kids": True, "rain": True, "shopping": False, "free": False,
        "desc_en": "Germany's national history museum housed in the 1695 Zeughaus arsenal and I. M. Pei's stunning glass spiral exhibition hall.",
        "desc_ja": "1695年建造の旧軍事兵器庫（ツォイクハウス）と建築家イオ・ミン・ペイ設計のガラス螺旋階段新館からなるドイツ歴史博物館。",
        "desc_es": "Museo de historia nacional de Alemania ubicado en el antiguo arsenal de 1695 y el pabellón de cristal de I. M. Pei.",
        "desc_zh": "德国国家历史博物馆，设于1695年旧兵工厂与建筑大师贝聿铭（I. M. Pei）设计的通透玻璃螺旋楼梯新馆中。",
        "desc_fr": "Musée national d'histoire allemande installé dans l'arsenal du XVIIe siècle et le pavillon en verre d'I. M. Pei.",
        "de": "Deutsches Nationalmuseum im Zeughaus von 1695 und der gläsernen Spirale von I. M. Pei.",
        "tip_en": "📸 Walk up the glass spiral staircase in the I. M. Pei Hall for beautiful reflections of the baroque Zeughaus inner courtyard.",
        "tip_ja": "📸 建築家イオ・ミン・ペイ（I.M.Pei）が手掛けた新館のガラス張りガラス螺旋階段へ！光とガラスの幾何学構造が美しい人気の建築写真スポットです。",
        "tip_es": "📸 Sube por la escalera de caracol de cristal diseñada por I. M. Pei para tomar fotos de la arquitectura barroca.",
        "tip_zh": "📸 拾级而上攀登贝聿铭设计的玻璃螺旋楼梯！感受阳光打在几何透明幕墙与老馆重厚雕花上的视觉碰撞。",
        "tip_fr": "📸 Montez l'escalier en colimaçon de verre de l'aile I. M. Pei pour admirer la rencontre des architectures.",
        "tip_de": "📸 Die von I. M. Pei entworfene gläserne Wendeltreppe für tolle Architekturfotos nutzen.",
        "price_en": "Entry: €10", "price_ja": "入場料: 10ユーロ", "price_es": "Entrada: 10€", "price_zh": "门票：10 欧元", "price_fr": "Entrée : 10 €", "price_de": "Eintritt: 10 €",
        "name_en": "German Historical Museum", "name_ja": "Deutsches Historisches Museum (DHM)（ドイツ歴史博物館）", "name_es": "Museo Histórico Alemán", "name_zh": "德国历史博物馆", "name_fr": "Musée historique allemand", "name_de": "Deutsches Historisches Museum"
    },
    # 26. Deutsches Technikmuseum & Spectrum
    {
        "id": "b_13c",
        "name": "Deutsches Technikmuseum & Spectrum（ドイツ技術博物館＆スペクトラム科学館）",
        "category": "Museum & Gallery", "rating": "★4.8", "locationZone": "city",
        "lat": 52.4986, "lng": 13.3775, "kids": True, "rain": True, "shopping": False, "free": False,
        "desc_en": "Sprawling technology museum housed in former railyards featuring real steam locomotives, vintage planes, ships, and hands-on physics experiments at Spectrum.",
        "desc_ja": "鉄道転車台と貨物駅跡地。蒸気機関車、実機飛行機（C-47）、船舶、コンピュータ歴史が広がるヨーロッパ最大級の技術博物館。",
        "desc_es": "Gran museo de tecnología en antiguas cocheras de trenes con locomotoras de vapor, aviones reales y experimentos en Spectrum.",
        "desc_zh": "利用旧车辆段改建的庞大科技展馆。陈列着真实古董蒸汽机车群、C-47运粮飞机、船只及Spectrum互动实验大楼。",
        "desc_fr": "Grand musée des techniques dans d'anciennes remises ferroviaires avec locomotives à vapeur et avions réels.",
        "de": "Riesiges Technikmuseum auf dem ehemaligen Bahngelände mit echten Dampflokomotiven, Flugzeugen und dem Spectrum Science Center.",
        "tip_en": "📸 Look up at the roof to spot the authentic 1948 'Rosinenbomber' (Raisin Bomber C-47) aircraft suspended directly over the entrance facade!",
        "tip_ja": "📸 屋外の建物屋上に注目！1948年のベルリン封鎖時に空中空輸を行った本物のC-47輸送機『ロジーネンボムバー（干しぶどう爆撃機）』が建物外壁に吊り下げられています。",
        "tip_es": "📸 ¡Mira al tejado para ver el avión real C-47 'Rosinenbomber' de 1948 colgado sobre la fachada principal!",
        "tip_zh": "📸 抬头张望主馆大楼屋顶！一架1948年冷战空运时期真正的C-47“葡萄干轰炸机”悬挂在建筑立面上空。",
        "tip_fr": "📸 Regardez le toit pour admirer l'authentique avion C-47 'Rosinenbomber' de 1948 suspendu au-dessus de la façade !",
        "tip_de": "📸 Auf das Dach schauen: Dort hängt der berühmte 'Rosinenbomber' C-47 aus dem Jahr 1948 direkt über der Fassade!",
        "price_en": "Entry: €12", "price_ja": "入場料: 12ユーロ", "price_es": "Entrada: 12€", "price_zh": "门票：12 欧元", "price_fr": "Entrée : 12 €", "price_de": "Eintritt: 12 €",
        "name_en": "German Museum of Technology", "name_ja": "Deutsches Technikmuseum & Spectrum（ドイツ技術博物館＆スペクトラム科学館）", "name_es": "Museo Alemán de la Tecnología", "name_zh": "德国科技馆与光谱科学中心", "name_fr": "Musée allemand des techniques", "name_de": "Deutsches Technikmuseum & Science Center Spectrum"
    },
    # 27. Museum für Naturkunde
    {
        "id": "b_13d",
        "name": "Museum für Naturkunde（ベルリン自然史博物館）",
        "category": "Museum & Gallery", "rating": "★4.7", "locationZone": "city",
        "lat": 52.5297, "lng": 13.3797, "kids": True, "rain": True, "shopping": False, "free": False,
        "desc_en": "World-famous natural history museum housing 'Giraffatitan' (the world's tallest mounted dinosaur skeleton at 13.27m), 'Tristan' T-Rex, and wet fossil collections.",
        "desc_ja": "世界一高い全身化石骨格『ギラファティタン（高さ13.27m）』やティラノサウルスの『トリスタン』、27万点の液体標本瓶が並ぶ自然史の殿堂。",
        "desc_es": "Famoso museo con el esqueleto de dinosaurio montado más alto del mundo (Giraffatitan de 13.27m) y el T-Rex Tristan.",
        "desc_zh": "拥有世界组装装配最高恐龙骨架化石“Giraffatitan”（高达13.27米）、暴龙Tristan与装满27万瓶液体标本的高耸玻璃墙。",
        "desc_fr": "Musée célèbre abritant le plus grand squelette de dinosaure monté du monde (Giraffatitan de 13,27 m) et le T-Rex Tristan.",
        "de": "Naturkundemuseum mit dem weltweit höchsten aufgebauten Dinosaurierskelett (Giraffatitan, 13,27m) und dem T-Rex Tristan.",
        "tip_en": "📸 Walk straight into the Dinosaur Hall to stand beneath the towering 13.27-meter tall Giraffatitan brachiosaur skeleton!",
        "tip_ja": "📸 入場してすぐの中央恐竜ホールへ！高さ13.27mを誇るギネス記録の巨大ブラキオサウルス骨格を見上げる光景は圧巻です。",
        "tip_es": "📸 ¡Entra directamente a la Sala de Dinosaurios para colocarte debajo del enorme esqueleto Giraffatitan de 13.27 metros!",
        "tip_zh": "📸 步入一楼中央恐龙大厅！站在高达13.27米的 Giraffatitan 巨型腕龙化石正下方仰望，冲击力绝伦。",
        "tip_fr": "📸 Entrez dans la Grande Salle des Dinosaures pour vous tenir sous le squelette géant de 13,27m de haut !",
        "tip_de": "📸 Direkt in den Dinosauriersaal gehen und sich unter das 13,27 Meter hohe Giraffatitan-Skelett stellen!",
        "price_en": "Entry: €11", "price_ja": "入場料: 11ユーロ", "price_es": "Entrada: 11€", "price_zh": "门票：11 欧元", "price_fr": "Entrée : 11 €", "price_de": "Eintritt: 11 €",
        "name_en": "Natural History Museum Berlin", "name_ja": "Museum für Naturkunde（ベルリン自然史博物館）", "name_es": "Museo de Historia Natural", "name_zh": "柏林自然历史博物馆", "name_fr": "Musée d'Histoire naturelle de Berlin", "name_de": "Museum für Naturkunde Berlin"
    },
    # 28. Futurium
    {
        "id": "b_13e",
        "name": "Futurium（フトゥリウム）",
        "category": "Museum & Gallery", "rating": "★4.7", "locationZone": "city",
        "lat": 52.5244, "lng": 13.3742, "kids": True, "rain": True, "shopping": False, "free": True,
        "desc_en": "Cutting-edge free interactive museum dedicated to future visions, sustainability, robotics, and human-nature-technology innovation.",
        "desc_ja": "『未来』をテーマにした連邦政府主導の最新体験型ミュージアム。持続可能な都市、ロボット技術、未来の食卓を完全無料で体験。",
        "desc_es": "Museo interactivo gratuito de vanguardia dedicado al futuro, la sostenibilidad, la robótica y la tecnología.",
        "desc_zh": "以“未来”为主题的顶级免费互动科技馆。涵盖未来城市、人工智能机器人与可持续环境生态实验室。",
        "desc_fr": "Musée interactif gratuit futuriste dédié au développement durable, à la robotique et aux innovations de demain.",
        "de": "Zukunftsmuseum mit interaktiver Ausstellung zu Nachhaltigkeit, Robotik und den Lebenswelten von morgen.",
        "tip_en": "🎟️ Admission is 100% FREE! Pick up a free wristband at the entrance to interact with digital stations and save your customized future ideas.",
        "tip_ja": "🎟️ 入場完全無料！入口で配布されるICリストバンドを受け取ると、館内の様々な体験端末で自分の未来アイデアを記録・タッチ操作できます。",
        "tip_es": "🎟️ ¡La entrada es 100% GRATIS! Recoge una pulsera digital en la entrada para guardar tus ideas sobre el futuro.",
        "tip_zh": "🎟️ 100%免费开放！入口处可免费领取智能感应手环，刷手环可在各个展台记录属于自己的未来科技方案。",
        "tip_fr": "🎟️ L'entrée est 100% GRATUITE ! Prenez un bracelet numérique gratuit à l'entrée pour interagir avec les stations.",
        "tip_de": "🎟️ Der Eintritt ist 100% KOSTENLOS! Am Eingang ein digitales Armband mitnehmen, um an den Stationen mitzumachen.",
        "price_en": "Free Entry", "price_ja": "入場無料", "price_es": "Entrada libre", "price_zh": "免费开放", "price_fr": "Gratuit", "price_de": "Kostenlos",
        "name_en": "Futurium", "name_ja": "Futurium（フトゥリウム）", "name_es": "Futurium", "name_zh": "未来博物馆", "name_fr": "Futurium", "name_de": "Futurium"
    },
    # 29. Computerspielemuseum
    {
        "id": "b_13f",
        "name": "Computerspielemuseum（コンピュータゲーム博物館）",
        "category": "Museum & Gallery", "rating": "★4.6", "locationZone": "city",
        "lat": 52.5175, "lng": 13.4419, "kids": True, "rain": True, "shopping": False, "free": False,
        "desc_en": "Interactive video game museum featuring playable original arcade machines, vintage home consoles, 1980s retro rooms, and gaming milestones.",
        "desc_ja": "レトロゲームから最新VRまで。1980年代のアーケードゲーム筐体や歴代ゲーム機を実際にプレイして遊べる体験型ミュージアム。",
        "desc_es": "Museo interactivo de videojuegos con máquinas recreativas jugables, consolas retro y salas de los años 80.",
        "desc_zh": "沉浸式电子游戏主题博物馆。拥有一系列可上手操纵玩的古董街机、历代经典游戏机与1980年代复古游戏房间。",
        "desc_fr": "Musée interactif du jeu vidéo présentant des bornes d'arcade jouables et des consoles de jeux vintage.",
        "de": "Interaktives Spielemuseum mit funktionierenden originalen Arcade-Automaten, Konsolen und 80er-Jahre-Zimmern.",
        "tip_en": "🎮 Play original arcade classics like Nimrod, Pac-Man, Space Invaders, and Pong on authentic coin-op hardware!",
        "tip_ja": "🎮 1951年の最初期のゲーム機『Nimrod』や、パックマン、スペースインベーダーの実機筐体を無料でプレイし放題！大人も子供も夢中になります。",
        "tip_es": "🎮 ¡Juega a clásicos como Pac-Man, Space Invaders y Pong en máquinas recreativas originales con monedas!",
        "tip_zh": "🎮 展厅内所有古董街机如《吃豆人》（Pac-Man）、《太空侵略者》（Space Invaders）均可免费无限次投币试玩！",
        "tip_fr": "🎮 Jouez gratuitement aux grands classiques de l'arcade comme Pac-Man et Space Invaders sur les vraies machines !",
        "tip_de": "🎮 Klassiker wie Pac-Man, Space Invaders und Pong an funktionierenden Original-Automaten ausprobieren!",
        "price_en": "Entry: €11", "price_ja": "入場料: 11ユーロ", "price_es": "Entrada: 11€", "price_zh": "门票：11 欧元", "price_fr": "Entrée : 11 €", "price_de": "Eintritt: 11 €",
        "name_en": "Computerspielemuseum", "name_ja": "Computerspielemuseum（コンピュータゲーム博物館）", "name_es": "Museo de los Videojuegos", "name_zh": "电子游戏博物馆", "name_fr": "Musée du jeu vidéo", "name_de": "Computerspielemuseum"
    },
    # 30. Spionagemuseum
    {
        "id": "b_13g",
        "name": "Spionagemuseum (German Spy Museum)（ドイツスパイ博物館）",
        "category": "Museum & Gallery", "rating": "★4.6", "locationZone": "city",
        "lat": 52.5097, "lng": 13.3789, "kids": True, "rain": True, "shopping": False, "free": False,
        "desc_en": "High-tech spy museum at Potsdamer Platz exploring espionage history from WWII to the Cold War with interactive laser mazes and Enigma ciphers.",
        "desc_ja": "ポツダム広場にあるハイテクスパイ博物館。本物のエニグマ暗号機、スパイカメラ、レーザー障害物コース体験が人気。",
        "desc_es": "Museo de espionaje interactivo en Potsdamer Platz con la máquina Enigma y un laberinto de rayos láser.",
        "desc_zh": "位于 Potsdamer 广场的高科技间谍博物馆。展示二战真正的“恩尼格玛”（Enigma）密码机、微型偷拍相机与激光迷宫。",
        "desc_fr": "Musée de l'espionnage interactif présentant des machines Enigma originales et un parcours d'obstacles à laser.",
        "de": "Interaktives Spionagemuseum am Potsdamer Platz mit originaler Enigma-Chiffriermaschine und Laserparcours.",
        "tip_en": "🕵️ Test your agility in the 'Laser Maze' challenge—dodge moving red laser beams to press buttons before time runs out!",
        "tip_ja": "🕵️ 映画のような『レーザー迷路（Laser Maze）』に挑戦！赤外線レーザーに触れないよう体をくねらせてボタンを押すアトラクションが一番盛り上がります。",
        "tip_es": "🕵️ ¡Pone a prueba tu agilidad en el laberinto láser esquivando los rayos rojos para lograr la mejor puntuación!",
        "tip_zh": "🕵️ 亲身体验如特工发散的“激光迷宫”（Laser Maze）过关！在不触发移动红外光束的前提下跨越障碍击中按钮。",
        "tip_fr": "🕵️ Testez votre agilité dans le parcours d'obstacles laser en esquivant les rayons rouges !",
        "tip_de": "🕵️ Die Geschicklichkeit im Laserparcours testen und versuchen, die Laserstrahlen ohne Berührung zu überwinden!",
        "price_en": "Entry: €15", "price_ja": "入場料: 15ユーロ", "price_es": "Entrada: 15€", "price_zh": "门票：15 欧元", "price_fr": "Entrée : 15 €", "price_de": "Eintritt: 15 €",
        "name_en": "German Spy Museum", "name_ja": "Spionagemuseum (German Spy Museum)（ドイツスパイ博物館）", "name_es": "Museo del Espionaje de Alemania", "name_zh": "德国间谍博物馆", "name_fr": "Musée de l'espionnage allemand", "name_de": "Deutsches Spionagemuseum"
    },
    # 31. Berliner Unterwelten
    {
        "id": "b_13h",
        "name": "Berliner Unterwelten（ベルリン地下世界ツアー）",
        "category": "Landmark", "rating": "★4.8", "locationZone": "city",
        "lat": 52.5486, "lng": 13.3886, "kids": False, "rain": True, "shopping": False, "free": False,
        "desc_en": "Guided underground tours through preserved WWII air-raid shelters, subterranean flak towers, and Cold War escape tunnels beneath Gesundbrunnen.",
        "desc_ja": "ゲズントブルンネン駅地下に眠る地下世界。防空壕、冷戦期の地下シェルター、脱出トンネルを専門ガイドと巡る人気ツアー。",
        "desc_es": "Tours guiados subterráneos por refugios antiaéreos de la II Guerra Mundial y túneles de escape de la Guerra Fría.",
        "desc_zh": "由专人导览穿行于 Gesundbrunnen 地下二战防空防爆掩体、冷战防核避难所与越境逃生地道。",
        "desc_fr": "Visites guidées souterraines des abris anti-aériens de la Seconde Guerre mondiale et tunnels d'évasion.",
        "de": "Geführte Touren durch historische Bunkeranlagen, Flaktürme und Flucht-Bunker unter der Stadt.",
        "tip_en": "🧥 Bring a warm jacket and sturdy closed shoes! The underground bunkers stay at a cold 10°C–12°C year-round regardless of summer heat.",
        "tip_ja": "🧥 年中10〜12℃のひんやりした無暖房地下空間を歩くため、夏場でも羽織る上着と歩きやすいスニーカーが必須です（事前Web予約推奨）。",
        "tip_es": "🧥 ¡Lleva una chaqueta abrigada y calzado cerrado! Los búnkeres subterráneos se mantienen a 10°C-12°C todo el año.",
        "tip_zh": "🧥 防寒提醒：请务必带上一件保暖外套与舒适运动鞋！即使在炎热夏季，地下地道内也维持在10°C–12°C的寒意中。",
        "tip_fr": "🧥 Prévoyez une veste chaude ! Les bunkers souterrains restent à 10°C-12°C toute l'année, même en plein été.",
        "tip_de": "🧥 Warme Jacke & festes Schuhwerk mitnehmen! In den unterirdischen Bunkern herrscht ganzjährig eine Kälte von 10°C–12°C.",
        "price_en": "Tour: €16", "price_ja": "ツアー: 16ユーロ", "price_es": "Tour: 16€", "price_zh": "导览：16 欧元", "price_fr": "Visite : 16 €", "price_de": "Führung: 16 €",
        "name_en": "Berlin Underground Tours", "name_ja": "Berliner Unterwelten（ベルリン地下世界ツアー）", "name_es": "Berliner Unterwelten", "name_zh": "柏林地下世界导览", "name_fr": "Berliner Unterwelten", "name_de": "Berliner Unterwelten"
    },
    # 32. Siegessäule & Großer Tiergarten
    {
        "id": "b_8b",
        "name": "Siegessäule & Großer Tiergarten（戦勝記念塔＆大ティーアガルテン）",
        "category": "Landmark", "rating": "★4.7", "locationZone": "city",
        "lat": 52.5145, "lng": 13.3501, "kids": True, "rain": False, "shopping": False, "free": True,
        "desc_en": "67m Victory Column topped by the golden statue of Victoria, set inside Berlin's vast 520-acre Tiergarten central forest park.",
        "desc_ja": "大ティーアガルテン公園の中心に立つ高さ67mの塔。頂上で金色の勝利の女神ヴィクトリア像（金のエルゼ）が輝く歴史的シンボル。",
        "desc_es": "Columna de la Victoria de 67m coronada por la estatua dorada de Victoria en el centro del gran parque Tiergarten.",
        "desc_zh": "矗立于蒂尔加藤国家森林公园中心高67米的战胜纪念塔。塔顶端坐着金光闪闪的胜利女神维多利亚雕像。",
        "desc_fr": "Colonne de la Victoire de 67m surmontée de la statue dorée de la déesse Victoria au cœur du grand parc du Tiergarten.",
        "de": "67m hohe Siegessäule mit der goldenen Viktoria ('Goldene Else') im Herzen des Tiergartens.",
        "tip_en": "📸 Climb the 285 spiral steps inside the column to reach the open viewing platform right beneath Goldene Else's feet for a view down Strasse des 17. Juni!",
        "tip_ja": "📸 塔内部の285段の螺旋階段を登って展望台へ！『6月17日通り』が真っ直ぐブランデンブルク門へと伸びる絶景写真が撮影できます。",
        "tip_es": "📸 Sube los 285 escalones en espiral hasta el mirador justo debajo de la estatua dorada para ver la avenida recta hasta la Puerta de Brandeburgo.",
        "tip_zh": "📸 攀登塔内285级螺旋阶梯登顶观景台！直视“6月17日大道”穿过森林直达勃兰登堡门的宏伟轴线大片。",
        "tip_fr": "📸 Montez les 285 marches pour la vue sur la grandiose rue du 17 Juin filant vers la porte de Brandebourg.",
        "tip_de": "📸 285 Stufen zur Aussichtsplattform unter den Füßen der 'Goldenen Else' aufsteigen – Blick auf die Straße des 17. Juni!",
        "price_en": "Tower: €4 (Park Free)", "price_ja": "塔登頂: 4ユーロ（公園無料）", "price_es": "Torre: 4€ (Parque gratis)", "price_zh": "登塔：4 欧元（公园免费）", "price_fr": "Tour : 4 € (Parc gratuit)", "price_de": "Turm: 4 € (Park frei)",
        "name_en": "Victory Column & Tiergarten", "name_ja": "Siegessäule & Großer Tiergarten（戦勝記念塔＆大ティーアガルテン）", "name_es": "Columna de la Victoria y Tiergarten", "name_zh": "战胜纪念塔与蒂尔加滕公园", "name_fr": "Colonne de la Victoire et Tiergarten", "name_de": "Siegessäule & Großer Tiergarten"
    },
    # 33. Potsdamer Platz & Sony Center
    {
        "id": "b_13i",
        "name": "Potsdamer Platz & Sony Center（ポツダム広場＆ソニーセンター）",
        "category": "Landmark", "rating": "★4.6", "locationZone": "city",
        "lat": 52.5097, "lng": 13.3761, "kids": True, "rain": True, "shopping": True, "free": True,
        "desc_en": "Futuristic modern urban center featuring Helmut Jahn's Mount Fuji-inspired glass tent roof over the Sony Center, cinemas, and skyscrapers.",
        "desc_ja": "かつての無人地帯が最新高層ビル街へ変貌した超モダン地区。富士山を模した巨大なガラスのテント屋根『ソニーセンター』が見どころ。",
        "desc_es": "Futurista centro urbano moderno con la cubierta de cristal inspirada en el Monte Fuji sobre el Sony Center.",
        "desc_zh": "由冷战废墟重构的未来主义现代摩天楼街区。包含建筑大师 Helmut Jahn 仿照富士山造型设计的 Sony Center 巨型玻璃飞檐顶。",
        "desc_fr": "Centre urbain moderniste au toit de verre en forme de Mont Fuji au-dessus du Sony Center.",
        "de": "Futuristischer moderner Platz mit dem spektakulären zeltartigen Glasdach des Sony Centers.",
        "tip_en": " Ride Europe's fastest elevator at Kollhoff Tower (Panoramapunkt) to reach the 24th-floor open-air terrace in just 20 seconds!",
        "tip_ja": " コルホフタワー（Kollhoff Tower）にある『ヨーロッパ最速エレベーター（Panoramapunkt）』で僅か20秒で24階オープンエア展望台へ登る体験が爽快！",
        "tip_es": " Subete al ascensor más rápido de Europa en la Kollhoff Tower para llegar al piso 24 en solo 20 segundos.",
        "tip_zh": " 搭乘 Kollhoff 大楼内“全欧洲速度最快电梯”（Panoramapunkt），仅需20秒直达24层露天赤砂岩展望台！",
        "tip_fr": " Prenez l'ascenseur le plus rapide d'Europe à la Kollhoff Tower pour atteindre la terrasse du 24e étage en 20 secondes !",
        "tip_de": " Mit dem schnellsten Aufzug Europas im Kollhoff-Tower (Panoramapunkt) in 20 Sekunden auf die Aussichtsplattform im 24. Stock!",
        "price_en": "Free (Panoramapunkt €9)", "price_ja": "無料（展望台9ユーロ）", "price_es": "Gratis (Mirador 9€)", "price_zh": "免费（观景台9欧）", "price_fr": "Gratuit (Panoramapunkt 9 €)", "price_de": "Kostenlos (Panoramapunkt 9 €)",
        "name_en": "Potsdamer Platz", "name_ja": "Potsdamer Platz & Sony Center（ポツダム広場＆ソニーセンター）", "name_es": "Potsdamer Platz", "name_zh": "波茨坦广场", "name_fr": "Potsdamer Platz", "name_de": "Potsdamer Platz & Sony Center"
    },
    # 34. Hackesche Höfe
    {
        "id": "b_13",
        "name": "Hackesche Höfe & Hackescher Markt（ハッケシャー・ヘーフェ）",
        "category": "Landmark", "rating": "★4.7", "locationZone": "city",
        "lat": 52.5242, "lng": 13.4022, "kids": True, "rain": True, "shopping": True, "free": True,
        "desc_en": "Interconnected complex of 8 historic Art Nouveau courtyards restored with glazed tile facades, independent designer boutiques, and cafes.",
        "desc_ja": "アール・ヌーヴォー様式の美しい釉薬タイルが広がる8つの連結中庭複合施設。若手デザイナーのセレクトショップやカフェが点在。",
        "desc_es": "Complejo de 8 patios históricos de estilo Art Nouveau con fachadas de azulejos, boutiques de diseño y cafés.",
        "desc_zh": "由8座被艺术瓷砖饰面环绕的连通中庭构成的旧工业建筑群。聚集着大量独立设计师画廊、精品手作店与咖啡馆。",
        "desc_fr": "Ensemble de 8 cours intérieures Art Nouveau restaurées avec boutiques de créateurs, cinémas et cafés.",
        "de": "Malerischer Komplex aus 8 miteinander verbundenen Jugendstil-Höfen mit Designer-Boutiquen und Cafés.",
        "tip_en": "📸 Walk straight into Hof 1 to admire August Endell's polychrome Art Nouveau glazed tile facade, then stroll into neighboring Haus Schwarzenberg for raw street art murals!",
        "tip_ja": "📸 中庭Hof 1の青と白のアール・ヌーヴォータイルの装飾壁画は撮影必至！すぐ隣の『Haus Schwarzenberg』の細道へ足を伸ばすとディープなストリートアート空間が広がります。",
        "tip_es": "📸 Entra en Hof 1 para ver los azulejos Art Nouveau y luego entra en el pasaje Haus Schwarzenberg con arte urbano.",
        "tip_zh": "📸 走入1号中庭（Hof 1）拍摄蓝色新艺术瓷砖大楼！随后推开相邻的 Haus Schwarzenberg 小门，直达冷战涂鸦文化长廊。",
        "tip_fr": "📸 Entrez dans la cour Hof 1 pour admirer les azulejos Art Nouveau, puis découvrez le passage street art d'à côté !",
        "tip_de": "📸 Im Hof 1 die blau-weiße Jugendstil-Fassade fotografieren und nebenan das Haus Schwarzenberg mit Streetart erkunden.",
        "price_en": "Free Access", "price_ja": "散策無料", "price_es": "Acceso libre", "price_zh": "免费游览", "price_fr": "Accès libre", "price_de": "Kostenlos",
        "name_en": "Hackesche Höfe", "name_ja": "Hackesche Höfe & Hackescher Markt（ハッケシャー・ヘーフェ）", "name_es": "Hackesche Höfe", "name_zh": "哈克雪庭院", "name_fr": "Hackesche Höfe", "name_de": "Hackesche Höfe"
    },
    # 35. Mauerpark & Flohmarkt
    {
        "id": "b_13j",
        "name": "Mauerpark & Flohmarkt（マウアーパーク＆日曜蚤の市）",
        "category": "Scenery & Walk", "rating": "★4.6", "locationZone": "city",
        "lat": 52.5408, "lng": 13.4022, "kids": True, "rain": False, "shopping": True, "free": True,
        "desc_en": "Vibrant public park built on the former Berlin Wall border strip, famous for its massive Sunday vintage flea market and open-air Bearpit Karaoke.",
        "desc_ja": "ベルリンの壁跡地に造られた公園。毎週日曜日に開催される巨大な骨董蚤の市と、円形野外ステージでの大人気『ベアピット・カラオケ』が有名。",
        "desc_es": "Parque en la antigua franja del Muro famoso por su gran mercado de pulgas de los domingos y el karaoke al aire libre.",
        "desc_zh": "坐落于昔日柏林墙划界废墟上的文化公园。每周日举办全柏林规模最大的复古跳蚤集市与万人野外露天卡拉OK（Bearpit Karaoke）。",
        "desc_fr": "Parc populaire sur l'ancien tracé du Mur célèbre pour son grand marché aux puces du dimanche et son karaoké géant.",
        "de": "Beliebter Park auf dem ehemaligen Grenzstreifen mit dem riesigen Sonntags-Flohmarkt und dem weltberühmten Bearpit-Karaoke.",
        "tip_en": "🎤 Visit on Sunday afternoon at 3:00 PM to watch hundreds of people cheer at the open-air Bearpit Karaoke at the stone amphitheatre!",
        "tip_ja": "🎤 日曜15:00に石造りの円形劇場へ！名物ホストJoeが仕切る『Bearpit Karaoke』で、一般人が数百人の聴衆の前で熱唱する熱気が最高です。",
        "tip_es": "🎤 ¡Ven el domingo a las 15:00 h para ver el famoso karaoke al aire libre Bearpit Karaoke en el anfiteatro!",
        "tip_zh": "🎤 必须在周日下午15点准时围观石雕露天剧场！全城热情的游客在 Bearpit Karaoke 现场登台欢唱，气氛热烈爆棚。",
        "tip_fr": "🎤 Venez le dimanche à 15h à l'amphithéâtre pour assister au mythique Bearpit Karaoke en plein air !",
        "tip_de": "🎤 Sonntags um 15:00 Uhr zum Stein-Amphitheater kommen für das legendäre Bearpit-Outdoor-Karaoke!",
        "price_en": "Free Access", "price_ja": "入場無料", "price_es": "Acceso libre", "price_zh": "免费参观", "price_fr": "Accès libre", "price_de": "Kostenlos",
        "name_en": "Mauerpark & Flea Market", "name_ja": "Mauerpark & Flohmarkt（マウアーパーク＆日曜蚤の市）", "name_es": "Mauerpark y Mercado de Pulgas", "name_zh": "墙公园与周日跳蚤市场", "name_fr": "Mauerpark et marché aux puces", "name_de": "Mauerpark & Flohmarkt"
    },
    # 36. Markthalle Neun
    {
        "id": "b_32",
        "name": "Markthalle Neun（マルクトハレ・ノイン）",
        "category": "Café & Bistro", "rating": "★4.6", "locationZone": "city",
        "lat": 52.5019, "lng": 13.4319, "kids": True, "rain": True, "shopping": True, "free": True,
        "desc_en": "Historic 1891 covered market hall in Kreuzberg celebrating artisanal food, organic regional produce, and international street food events.",
        "desc_ja": "クロイツベルク地区にある1891年開業の歴史的屋内市場。職人技のチーズ、パン、クラフトビール、木曜夜のストリートフードナイトが人気。",
        "desc_es": "Mercado cubierto de 1891 en Kreuzberg famoso por su comida artesanal y eventos de Street Food Thursday.",
        "desc_zh": "位于 Kreuzberg 街区始于1891年的古老室内集市。主打手工面包干酪、精酿啤酒与逢周四晚举办的“街头美食之夜”（Street Food Thursday）。",
        "desc_fr": "Halle couverte de 1891 à Kreuzberg célèbre pour ses produits artisanaux et son Street Food Thursday.",
        "de": "Historische Markthalle von 1891 in Kreuzberg mit handwerklichen Lebensmitteln und dem Street Food Thursday.",
        "tip_en": "🍽️ Visit on Thursday evening (5:00 PM – 10:00 PM) for the world-famous 'Street Food Thursday' to sample bao buns, tacos, oysters, and craft beer under one roof!",
        "tip_ja": "🍽️ 木曜日の17:00〜22:00限定で開催される『Street Food Thursday』に狙いを定めて訪問を！世界各国の絶品屋台フードとクラフト生ビールが集結します。",
        "tip_es": "🍽️ ¡Ven el jueves por la tarde (17:00 a 22:00 h) para el Street Food Thursday y prueba tacos, bao y cerveza artesanal!",
        "tip_zh": "🍽️ 务必锁定每周四傍晚17:00–22:00的“Street Food Thursday”！汇聚全球特色小吃与当地精酿啤酒。",
        "tip_fr": "🍽️ Venez le jeudi soir (17h–22h) pour le mythique Street Food Thursday et goûtez aux spécialités du monde !",
        "tip_de": "🍽️ Donnerstags ab 17:00 Uhr zum 'Street Food Thursday' kommen und internationale Spezialitäten probieren!",
        "price_en": "Free Entry (Dishes €5–€12)", "price_ja": "入場無料（料理5〜12ユーロ）", "price_es": "Entrada libre (Platos 5€–12€)", "price_zh": "免费进场（小吃5–12欧）", "price_fr": "Gratuit (Plats 5 €–12 €)", "price_de": "Eintritt frei (Gerichte 5 €–12 €)",
        "name_en": "Markthalle Neun", "name_ja": "Markthalle Neun（マルクトハレ・ノイン）", "name_es": "Markthalle Neun", "name_zh": "第九集市大厅", "name_fr": "Markthalle Neun", "name_de": "Markthalle Neun"
    },
    # 37. Tempelhofer Feld
    {
        "id": "b_13k",
        "name": "Tempelhofer Feld（テンペルホーフ空港跡地公園）",
        "category": "Scenery & Walk", "rating": "★4.8", "locationZone": "city",
        "lat": 52.4731, "lng": 13.4039, "kids": True, "rain": False, "shopping": False, "free": True,
        "desc_en": "Former 1920s Nazi and Airlift airport transformed into the world's largest inner-city park (386 hectares) with intact runways open for cycling and kitesurfing.",
        "desc_ja": "ベルリン空輸の歴史を誇る旧テンペルホーフ空港の広大な滑走路をそのまま開放した386ヘクタールの市民公園（入場無料）。",
        "desc_es": "Antiguo aeropuerto reconvertido en el parque urbano más grande del mundo (386 hectáreas) con pistas de aterrizaje abiertas.",
        "desc_zh": "由冷战时期大名鼎鼎的 Tempelhof 机场停用后全面开放的386公顷巨型城市公共公园。两条庞大的沥青飞机跑道完全开放给市民溜冰骑行。",
        "desc_fr": "Ancien aéroport transformé en le plus grand parc urbain du monde (386 ha) avec pistes de décollage ouvertes aux vélos.",
        "de": "Ehemaliges Flughafengelände, umgestaltet zum größten innerstädtischen Park der Welt mit intakten Startbahnen.",
        "tip_en": "🚴 Rent a city bike or inline skates to ride at full speed down the massive 2km long main runway without any traffic!",
        "tip_ja": "🚴 自転車やインラインスケートをレンタルして、障害物のない全長2kmの巨大な滑走路本線をフルスピードで駆け抜ける体験が最高に爽快！",
        "tip_es": "🚴 ¡Alquila una bicicleta o patines para recorrer la gran pista de 2 km a toda velocidad sin coches!",
        "tip_zh": "🚴 租一辆城市自行车或直排轮滑鞋，在没有任何车辆干扰的2公里巨型飞机主跑道上全速飙车！",
        "tip_fr": "🚴 Louez un vélo ou des roller-skates pour filer à toute vitesse le long de la piste principale de 2 km !",
        "tip_de": "🚴 Ein Fahrrad oder Inlineskates mieten und mit Vollgas die 2 km lange Hauptstartbahn entlangflitzen!",
        "price_en": "Free Access", "price_ja": "入場無料", "price_es": "Acceso libre", "price_zh": "免费开放", "price_fr": "Accès libre", "price_de": "Kostenlos",
        "name_en": "Tempelhof Field", "name_ja": "Tempelhofer Feld（テンペルホーフ空港跡地公園）", "name_es": "Campo de Tempelhof", "name_zh": "滕佩尔霍夫公园", "name_fr": "Tempelhofer Feld", "name_de": "Tempelhofer Feld"
    },
    # 38. KaDeWe
    {
        "id": "b_13l",
        "name": "KaDeWe (Kaufhaus des Westens)（カーデーヴェー）",
        "category": "Shopping", "rating": "★4.7", "locationZone": "city",
        "lat": 52.5014, "lng": 13.3411, "kids": True, "rain": True, "shopping": True, "free": True,
        "desc_en": "Europe's largest department store operating since 1907 near Ku'damm, famed for its legendary 6th floor gourmet food hall featuring 35,000 delicacies.",
        "desc_ja": "1907年創業のヨーロッパ最大規模の老舗百貨店。特に6階にある『グルメフロア』は、世界中の最高級食材や生牡蠣バーが並ぶ食の天国。",
        "desc_es": "El gran almacén más grande de Europa continental desde 1907 con su legendaria 6ª planta gourmet.",
        "desc_zh": "始于1907年全欧洲最大的老牌高档百货公司。其6楼拥有聚集了35000余种珍馐美食与现开生蚝吧的传奇美食大厅。",
        "desc_fr": "Le plus grand grand magasin d'Europe continentale depuis 1907, célèbre pour son 6e étage gourmand mythique.",
        "de": "Größtes Warenhaus Kontinentaleuropas seit 1907 nahe dem Ku'damm mit der weltberühmten Feinkost-Etage im 6. Stock.",
        "tip_en": "🍽️ Head straight to the 6th floor (Feinschmeckeretage) to sit at the Austernbar (Oyster Bar) for fresh oysters and a glass of Champagne!",
        "tip_ja": "🍽️ 6階グルメフロア（Feinschmeckeretage）の『オイスターバー（Austernbar）』へ直行！最高級生牡蠣と冷えたシャンパンをカウンターで味わうのが究極の贅沢。",
        "tip_es": "🍽️ ¡Subete a la 6ª planta (Feinschmeckeretage) y siéntate en la Austernbar a comer ostras frescas con champán!",
        "tip_zh": "🍽️ 建议直奔6楼美食大厅（Feinschmeckeretage）的 Austernbar 生蚝吧选座，现场享用现开顶级生蚝与冰镇香槟！",
        "tip_fr": "🍽️ Foncez au 6e étage gourmand pour vous installer à l'Austernbar et déguster des huîtres fraîches avec du champagne !",
        "tip_de": "🍽️ Direkt in den 6. Stock (Feinschmeckeretage) fahren und an der Austernbar frische Austern mit Champagner genießen!",
        "price_en": "Free Entry (Shopping)", "price_ja": "入館無料（ショッピング）", "price_es": "Entrada libre (Compras)", "price_zh": "免费入馆（购物）", "price_fr": "Entrée libre", "price_de": "Freier Eintritt",
        "name_en": "KaDeWe Department Store", "name_ja": "KaDeWe (Kaufhaus des Westens)（カーデーヴェー）", "name_es": "KaDeWe", "name_zh": "西方百货 KaDeWe", "name_fr": "KaDeWe", "name_de": "KaDeWe (Kaufhaus des Westens)"
    },
    # 39. Spree-Schifffahrt
    {
        "id": "b_13m",
        "name": "Spree-Schifffahrt (Spree River Cruise)（シュプレー川観光クルーズ船）",
        "category": "Scenery & Walk", "rating": "★4.6", "locationZone": "city",
        "lat": 52.5175, "lng": 13.4022, "kids": True, "rain": False, "shopping": False, "free": False,
        "desc_en": "1-hour glass-topped boat cruise along the Spree river passing Museum Island, Berlin Cathedral, Reichstag, and Government District.",
        "desc_ja": "博物館島、ベルリン大聖堂、連邦議会議事堂、首相官邸など、ベルリンの主要観光名所を水上から巡る定番の1時間クルーズ船。",
        "desc_es": "Crucero fluvial en barco panorámico por el Spree pasando por la Isla de los Museos y el Parlamento.",
        "desc_zh": "1小时全景玻璃水上游船航线。沿施普雷河穿行于博物馆岛、柏林大教堂、国会大厦与联邦总理府之间。",
        "desc_fr": "Croisière fluviale de 1h sur la Spree passant au pied des monuments phares de l'Île des Musées et du Reichstag.",
        "de": "1-stündige Schiffsrundfahrt auf der Spree vorbei an der Museumsinsel, dem Berliner Dom und dem Regierungsviertel.",
        "tip_en": "📸 Board from Friedrichstraße or Nikolai Quarter pier; sit on the upper open-air deck for untruncated photo angles of the Reichstag glass dome over the water!",
        "tip_ja": "📸 フリードリヒシュトラーセ駅前またはニコライ地区の乗り場から乗船！オープンエアの2階デッキ席から見上げる議事堂ガラスドームと水面の反射が絶景です。",
        "tip_es": "📸 Embarca en Friedrichstraße y siéntate en la cubierta superior descubierta para tomar las mejores fotos.",
        "tip_zh": "📸 推荐从 Friedrichstraße 码头登船！选座顶层露天甲板，可拍摄水面倒影中的国会大厦玻璃穹顶。",
        "tip_fr": "📸 Embarquez depuis Friedrichstraße et installez-vous sur le pont supérieur découvert pour de belles photos.",
        "tip_de": "📸 An der Anlegestelle Friedrichstraße einsteigen und auf das Freideck setzen für tolle Fotos vom Regierungsviertel.",
        "price_en": "Cruise: €18–€22", "price_ja": "クルーズ: 18〜22ユーロ", "price_es": "Crucero: 18€–22€", "price_zh": "游船：18–22 欧元", "price_fr": "Croisière : 18 €–22 €", "price_de": "Schiffsfahrt: 18 €–22 €",
        "name_en": "Spree River Cruise", "name_ja": "Spree-Schifffahrt (Spree River Cruise)（シュプレー川観光クルーズ船）", "name_es": "Crucero por el Río Spree", "name_zh": "施普雷河游船", "name_fr": "Croisière sur la Spree", "name_de": "Spree-Schifffahrt"
    },
    # 40. Badeschiff
    {
        "id": "b_13n",
        "name": "Badeschiff（バーデシッフ）",
        "category": "Kids & Family", "rating": "★4.5", "locationZone": "city",
        "lat": 52.4969, "lng": 13.4531, "kids": True, "rain": False, "shopping": False, "free": False,
        "desc_en": "Floating swimming pool constructed inside a converted 30-meter barge cargo ship moored on the Spree river, featuring a wooden lounge deck and beach bar.",
        "desc_ja": "シュプレー川の上に浮かぶ全幅30mの船上プール！木製ウッドデッキ、白砂のビーチバー、DJ音楽が流れる夏限定の人気スポット。",
        "desc_es": "Piscina flotante construida en una barcaza amarrada en el río Spree con cubierta de madera y bar de playa.",
        "desc_zh": "浮于施普雷河面之上的30米改建货船水上游泳池！自带木质甲板与沙滩露天酒吧，为夏日时尚消暑地标。",
        "desc_fr": "Piscine flottante aménagée dans une péniche amarrée sur la Spree avec pont en bois et bar de plage.",
        "de": "Schwimmendes Poolschiff in einem Frachtkahn auf der Spree mit Holzdeck und Strandbar.",
        "tip_en": "🎟️ Open May to September; time-slot ticket MUST be booked online in advance! Bring your own towel and swimsuit.",
        "tip_ja": "🎟️ 5月〜9月の夏季限定営業。公式サイトでの日時指定チケットの事前予約が必須！バスタオルと水着は必ず持参しましょう。",
        "tip_es": "🎟️ Abierto de mayo a septiembre. ¡Es OBLIGATORIO comprar la entrada por internet previamente!",
        "tip_zh": "🎟️ 仅在5月至9月夏季开放！必须提前在官网预订入场场次门票，自备毛巾与泳衣。",
        "tip_fr": "🎟️ Ouvert de mai à septembre ; billet à créneau horraire obligatoire en ligne. Apportez votre serviette !",
        "tip_de": "🎟️ Mai bis September geöffnet; Online-Zeitfensterticket ist Pflicht! Badetuch & Badesachen mitbringen.",
        "price_en": "Entry: €7", "price_ja": "入場料: 7ユーロ", "price_es": "Entrada: 7€", "price_zh": "门票：7 欧元", "price_fr": "Entrée : 7 €", "price_de": "Eintritt: 7 €",
        "name_en": "Badeschiff Floating Pool", "name_ja": "Badeschiff（バーデシッフ）", "name_es": "Piscina Flotante Badeschiff", "name_zh": "施普雷河水上泳池", "name_fr": "Piscine flottante Badeschiff", "name_de": "Badeschiff Berlin"
    }
]

# Write to data/cities/berlin.json
fpath = "data/cities/berlin.json"
data = {
    "cityName": "Berlin, Germany",
    "spots": spots
}

with open(fpath, 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print(f"🎉 Successfully created {len(spots)} spots in data/cities/berlin.json")
