import json

frankfurt_spots = [
    # 1. Römerberg & Rathaus Römer
    {
        "id": "f_1",
        "name": "Römerberg & Rathaus Römer（レーマー広場＆旧市庁舎レーマー）",
        "category": "Landmark", "rating": "★4.8", "locationZone": "city",
        "lat": 50.1103, "lng": 8.6821, "kids": True, "rain": False, "shopping": False, "free": True,
        "desc_en": "Picturesque medieval central square surrounded by timber-framed gabled houses, featuring the 15th-century Rathaus Römer town hall and Fountain of Justice.",
        "desc_ja": "木骨造りの階段状切妻屋根の旧市庁舎『レーマー』と正義の女神像の噴水が立つ、フランクフルトの歴史的中心広場。",
        "desc_es": "Pintoresca plaza medieval flanqueada por casas de entramado de madera, el ayuntamiento Römer del siglo XV y la Fuente de la Justicia.",
        "desc_zh": "由木骨架梯形屋顶古建围合而成的中世纪大广场，屹立着15世纪 Römer 旧市政厅与正义女神喷泉。",
        "desc_fr": "Place médiévale pittoresque entourée de maisons à colombages, avec l'hôtel de ville Römer du XVe siècle et la Fontaine de la Justice.",
        "desc_de": "Historischer Hauptplatz mit den charakteristischen Fachwerkhäusern, dem Römer-Rathaus aus dem 15. Jahrhundert und dem Gerechtigkeitsbrunnen.",
        "tip_en": "📸 Visit early morning before 8:30 AM to photograph the colorful gabled facades without tour groups blocking the fountain center.",
        "tip_ja": "📸 団体ツアー客が到着する前の早朝8:30前に訪問するのが鉄則！正義の女神像の正面から木骨造りの建物をバックにした広角写真が撮影できます。",
        "tip_es": "📸 Visítala temprano antes de las 8:30 h para fotografiar las fachadas de entramado de madera sin grupos de turistas.",
        "tip_zh": "📸 建议早晨8:30之前抵达！立于正义女神喷泉正面，可拍摄没有游人遮挡的半木结构古彩房子广角画面。",
        "tip_fr": "📸 Venez tôt le matin avant 8h30 pour photographier les façades à colombages sans la foule autour de la fontaine.",
        "tip_de": "📸 Morgens vor 8:30 Uhr kommen, um die bunten Fachwerkfassaden ohne Reisegruppen vor dem Brunnen zu fotografieren.",
        "price_en": "Free Access", "price_ja": "見学無料", "price_es": "Acceso libre", "price_zh": "免费参观", "price_fr": "Accès libre", "price_de": "Kostenlos",
        "name_en": "Römerberg & City Hall", "name_ja": "Römerberg & Rathaus Römer（レーマー広場＆旧市庁舎レーマー）", "name_es": "Römerberg y Ayuntamiento", "name_zh": "罗马人广场与旧市政厅", "name_fr": "Place du Römerberg", "name_de": "Römerberg & Rathaus Römer"
    },
    # 2. Kaiserdom St. Bartholomäus
    {
        "id": "f_2",
        "name": "Kaiserdom St. Bartholomäus（聖バルトロメウス大聖堂）",
        "category": "Landmark", "rating": "★4.7", "locationZone": "city",
        "lat": 50.1106, "lng": 8.6853, "kids": True, "rain": True, "shopping": False, "free": True,
        "desc_en": "Gothic red-sandstone cathedral where Holy Roman Emperors were elected and crowned, featuring a 95-meter tower.",
        "desc_ja": "神聖ローマ皇帝の選挙と戴冠式が執り行われた赤砂岩のゴシック様式大聖堂（カイザードーム）。高さ95mの塔がそびえる。",
        "desc_es": "Catedral gótica de arenisca roja donde se elegía y coronaba a los emperadores del Sacro Imperio Romano Germánico.",
        "desc_zh": "由红砂岩打造的哥特式大教堂。昔日神圣罗马帝国皇帝在此举行选举与加冕典礼，拥有95米高的尖塔。",
        "desc_fr": "Cathédrale gothique en grès rouge où étaient élus et couronnés les empereurs du Saint-Empire.",
        "de": "Gotischer Rotsandstein-Dom, in dem die Kaiser des Heiligen Römischen Reiches gewählt und gekrönt wurden.",
        "tip_en": "📸 Climb the 328 steep steps up the Domturm (Cathedral Tower) for a view down over Römerberg and the Main river bank!",
        "tip_ja": "📸 大聖堂の塔（Domturm）内部の328段の急階段を登って展望スペースへ！レーマー広場の赤屋根とマイン川沿いの街並みが真下に広がります。",
        "tip_es": "📸 Sube los 328 escalones empinados de la torre del Domturm para contemplar la vista panorámica del río y del casco antiguo.",
        "tip_zh": "📸 攀登塔楼内部328级陡峭阶梯登顶 Domturm 展望台！俯瞰红屋顶集聚的旧城区与平缓流淌的美因河畔。",
        "tip_fr": "📸 Montez les 328 marches de la tour pour une vue imprenable sur le Römerberg et la rivière.",
        "tip_de": "📸 Die 328 Stufen des Domturms aufsteigen für einen Panoramablick auf den Römerberg und das Mainufer.",
        "price_en": "Church Free (Tower €3.50)", "price_ja": "聖堂無料（塔登頂: 3.50ユーロ）", "price_es": "Catedral gratis (Torre 3,50€)", "price_zh": "教堂免费（登塔3.50欧）", "price_fr": "Cathédrale gratuite (Tour 3,50 €)", "price_de": "Dom frei (Turm 3,50 €)",
        "name_en": "Frankfurt Cathedral", "name_ja": "Kaiserdom St. Bartholomäus（聖バルトロメウス大聖堂）", "name_es": "Catedral de Fráncfort", "name_zh": "法兰克福皇帝大教堂", "name_fr": "Cathédrale de Francfort", "name_de": "Kaiserdom St. Bartholomäus"
    },
    # 3. Goethe-Haus & Deutsches Romantik-Museum
    {
        "id": "f_3",
        "name": "Goethe-Haus & Deutsches Romantik-Museum（ゲーテハウス＆ドイツ・ロマン派博物館）",
        "category": "Museum & Gallery", "rating": "★4.6", "locationZone": "city",
        "lat": 50.1114, "lng": 8.6775, "kids": True, "rain": True, "shopping": False, "free": False,
        "desc_en": "Reconstructed 18th-century birthplace of Johann Wolfgang von Goethe, displaying his childhood standing desk and adjacent Romanticism museum.",
        "desc_ja": "文豪ヨハン・ヴォルフガング・フォン・ゲーテが生まれ育った18世紀の邸宅。『若きウェルテルの悩み』を執筆した書斎と隣接博物館が見どころ。",
        "desc_es": "Casa natal reconstruida del siglo XVIII del escritor Johann Wolfgang von Goethe con su escritorio de infancia y museo romántico.",
        "desc_zh": "文学巨擘歌德（Goethe）诞生与成长的18世纪老宅。保存有其创作《少年维特之烦恼》的书房与相邻的德国浪漫主义博物馆。",
        "desc_fr": "Maison natale reconstituée du XVIIIe siècle de l'écrivain Goethe abritant son bureau et le musée du Romantisme.",
        "de": "Recht im Originalstil wiederaufgebautes Geburtshaus von Johann Wolfgang von Goethe mit Arbeitszimmer und Romantik-Museum.",
        "tip_en": " Examine the 3rd-floor writing room (Schreibzimmer) to stand right in front of the standing desk where Goethe penned 'The Sorrows of Young Werther'.",
        "tip_ja": " 3階の書斎（Schreibzimmer）へ！立ち作業用のデスク『立ち机』が展示されており、世界的名作『若きウェルテルの悩み』が生まれた歴史的空間を間近で観察できます。",
        "tip_es": " Contempla en la 3ª planta el escritorio de pie original donde Goethe escribió 'Las cuitas del joven Werther'.",
        "tip_zh": " 走入3楼书房（Schreibzimmer）！站在歌德当年立姿倾情撰写名著《少年维特之烦恼》的复古立式书桌正前方。",
        "tip_fr": " Admirez au 3e étage le bureau debout où Goethe rédigea 'Les Souffrances du jeune Werther'.",
        "tip_de": " Im 3. Stock das Schreibzimmer besichtigen, in dem Goethe am Stehpult 'Die Leiden des jungen Werthers' verfasste.",
        "price_en": "Entry: €10", "price_ja": "入場料: 10ユーロ", "price_es": "Entrada: 10€", "price_zh": "门票：10 欧元", "price_fr": "Entrée : 10 €", "price_de": "Eintritt: 10 €",
        "name_en": "Goethe House & Museum", "name_ja": "Goethe-Haus & Deutsches Romantik-Museum（ゲーテハウス＆ドイツ・ロマン派博物館）", "name_es": "Casa-Museo de Goethe", "name_zh": "歌德故居与浪漫主义博物馆", "name_fr": "Maison-Musée de Goethe", "name_de": "Goethe-Haus & Deutsches Romantik-Museum"
    },
    # 4. Städel Museum
    {
        "id": "f_4",
        "name": "Städel Museum（シュテーデル美術館）",
        "category": "Museum & Gallery", "rating": "★4.8", "locationZone": "city",
        "lat": 50.1031, "lng": 8.6742, "kids": True, "rain": True, "shopping": False, "free": False,
        "desc_en": "One of Germany's premier art museums housing 700 years of European masterpieces including Vermeer's 'The Geographer', Botticelli, Monet, and Tischbein's Goethe portrait.",
        "desc_ja": "700年にわたる欧州美術の殿堂。フェルメールの『地理学者』、ボッティチェッリ、モネ、ティシュバイン描く『ローマの郊外のゲーテ』を所蔵。",
        "desc_es": "Uno de los mejores museos de arte de Alemania con 700 años de obras maestras europeas como 'El geógrafo' de Vermeer.",
        "desc_zh": "德国极负盛名的艺术殿堂之一。收藏有维米尔的绝世珍品《地理学家》、波提切利、莫奈及提施拜因所绘的歌德巨幅肖像画。",
        "desc_fr": "L'un des plus grands musées d'art d'Allemagne abritant 700 ans de chefs-d'œuvre européens dont 'Le Géographe' de Vermeer.",
        "de": "Bedeutendes Kunstmuseum mit 700 Jahren europäischer Meisterwerke wie Vermeers 'Der Geograph' und Tischbeins Goethe-Porträt.",
        "tip_en": "🖼️ Walk down into the underground extension (Gartenhallen) to see contemporary art displayed beneath circular ceiling skylights embedded in the lawn above!",
        "tip_ja": "🖼️ 地下新館『Gartenhallen』へ！地上庭園の芝生に埋め込まれた195個の丸い天窓からやわらかな自然光が注ぐ幻想的な空間でモダンアートを鑑賞できます。",
        "tip_es": "🖼️ Baje a la ampliación subterránea Gartenhallen iluminada por 195 tragaluces circulares incrustados en el césped exterior.",
        "tip_zh": "🖼️ 务必向下走入地下新馆 Gartenhallen！仰望嵌入上方草坪的195个圆形穹顶采光天窗，在自然漫射光中观赏当代艺术。",
        "tip_fr": "🖼️ Descendez dans l'extension souterraine Gartenhallen baignée par les puits de lumière circulaires du jardin.",
        "tip_de": "🖼️ In den unterirdischen Neubau (Gartenhallen) hinabsteigen und Kunst unter den kreisrunden Deckenaugen erleben.",
        "price_en": "Entry: €16", "price_ja": "入場料: 16ユーロ", "price_es": "Entrada: 16€", "price_zh": "门票：16 欧元", "price_fr": "Entrée : 16 €", "price_de": "Eintritt: 16 €",
        "name_en": "Städel Museum", "name_ja": "Städel Museum（シュテーデル美術館）", "name_es": "Museo Städel", "name_zh": "施泰德美术馆", "name_fr": "Musée Städel", "name_de": "Städel Museum"
    },
    # 5. Main Tower
    {
        "id": "f_5",
        "name": "Main Tower（マインタワー）",
        "category": "Landmark", "rating": "★4.7", "locationZone": "city",
        "lat": 50.1114, "lng": 8.6722, "kids": True, "rain": True, "shopping": False, "free": False,
        "desc_en": "200-meter skyscraper in Frankfurt's financial district featuring the city's only open-air rooftop observation deck at 198m.",
        "desc_ja": "金融街に立つ高さ200mの超高層ビル。地上198mにあるフランクフルト唯一のオープンエア屋上展望デッキから摩天楼を一望。",
        "desc_es": "Rascacielos de 200m en el distrito financiero con el único mirador al aire libre en la azotea a 198m.",
        "desc_zh": "耸立于金融区的200米高摩天大楼。拥有法兰克福唯一位于198米高处的露天全景屋顶观景台。",
        "desc_fr": "Gratte-ciel de 200m dans le quartier financier doté de la seule plateforme d'observation en plein air à 198m.",
        "de": "200 Meter hoher Wolkenkratzer im Bankenviertel mit der einzigen öffentlich zugänglichen Freiluft-Aussichtsplattform auf 198m.",
        "tip_en": "📸 Visit 30 minutes before sunset to capture the high-speed elevator ride up and watch the dusk lights turn on across the bank skyscrapers!",
        "tip_ja": "📸 日没の30分前に入場するのが黄金法則！刻々と変わりゆく夕焼けと、周囲の摩天楼に明かりが灯る美しい夜景の変化を撮影できます。",
        "tip_es": "📸 Entra 30 minutos antes del atardecer para ver cómo se encienden las luces de los rascacielos al caer la noche.",
        "tip_zh": "📸 推荐于日落前30分钟购票登顶！饱览从日落余晖到金融区金融大厦亮起繁星灯火的壮丽变幻夜景。",
        "tip_fr": "📸 Montez 30 minutes avant le coucher du soleil pour admirer la métamorphose des lumières de la skyline.",
        "tip_de": "📸 30 Minuten vor Sonnenuntergang hochfahren, um das Aufleuchten der Banken-Skyline zur blauen Stunde zu fotografieren.",
        "price_en": "Entry: €9", "price_ja": "入場料: 9ユーロ", "price_es": "Entrada: 9€", "price_zh": "门票：9 欧元", "price_fr": "Entrée : 9 €", "price_de": "Eintritt: 9 €",
        "name_en": "Main Tower Observatory", "name_ja": "Main Tower（マインタワー）", "name_es": "Torre Main Tower", "name_zh": "美因塔观景台", "name_fr": "Tour Main Tower", "name_de": "Main Tower"
    },
    # 6. Eiserner Steg
    {
        "id": "f_6",
        "name": "Eiserner Steg（アイゼルナー・シュテグ鉄橋）",
        "category": "Landmark", "rating": "★4.6", "locationZone": "city",
        "lat": 50.1086, "lng": 8.6817, "kids": True, "rain": False, "shopping": False, "free": True,
        "desc_en": "Historic 1869 iron footbridge spanning the Main river, decorated with thousands of love padlocks and Greek Homer inscription.",
        "desc_ja": "1869年建造のマイン川に架かるネオ・ゴシック風の歩行者専用鉄橋。数千個の「愛の南京錠」とホメロスのギリシャ語碑文が刻まれる。",
        "desc_es": "Puente peatonal de hierro histórico de 1869 sobre el río Meno decorado con miles de candados de amor.",
        "desc_zh": "始于1869年横跨美因河的历史铁索人行桥。桥上挂满了成千上万锁住爱情的连心锁，刻有荷马史诗诗句。",
        "desc_fr": "Passerelle piétonne historique en fer de 1869 sur le Meno couverte de milliers de cadenas d'amour.",
        "de": "Historische Fußgänger-Eisenbrücke von 1869 über den Main mit tausenden Liebesschlössern und Homer-Zitat.",
        "tip_en": "📸 Walk to the middle of the bridge looking north to align Frankfurt's skyscraper skyline behind the gabled roofs of Römerberg!",
        "tip_ja": "📸 橋の中央部から北側（旧市街方向）を振り返って撮影！伝統的なレーマー広場の屋根の背後に、現代の摩天楼ビル群が聳えるコントラスト写真が撮れます。",
        "tip_es": "📸 Camina hasta el centro del puente mirando hacia el norte para encuadrar los rascacielos detrás de los tejados del casco antiguo.",
        "tip_zh": "📸 步至铁桥中央面向北方！将旧城区古朴的红斜屋顶与背景高耸入云的金融区现代摩天大楼重叠连拍。",
        "tip_fr": "📸 Placez-vous au milieu du pont en regardant vers le nord pour cadrer les rascacielos derrière les toits anciens.",
        "tip_de": "📸 Auf der Brückenmitte nach Norden schauen: Perfektes Fotomotiv mit den altstädtischen Dächern vor der Hochhaus-Kulisse.",
        "price_en": "Free Access", "price_ja": "通行無料", "price_es": "Acceso libre", "price_zh": "免费通行", "price_fr": "Accès libre", "price_de": "Kostenlos",
        "name_en": "Iron Footbridge", "name_ja": "Eiserner Steg（アイゼルナー・シュテグ鉄橋）", "name_es": "Puente de Hierro", "name_zh": "铁桥", "name_fr": "Passerelle en fer Eiserner Steg", "name_de": "Eiserner Steg"
    },
    # 7. Paulskirche
    {
        "id": "f_7",
        "name": "Paulskirche（聖パウロ教会）",
        "category": "Landmark", "rating": "★4.5", "locationZone": "city",
        "lat": 50.1111, "lng": 8.6808, "kids": True, "rain": True, "shopping": False, "free": True,
        "desc_en": "Historic red-sandstone church where Germany's first freely elected National Assembly met in 1848, revered as the cradle of German democracy.",
        "desc_ja": "1848年にドイツ初の自由選挙による国民議会が開催された歴史的赤砂岩教会。ドイツ民主主義の揺籃の地として無料公開されている。",
        "desc_es": "Iglesia de arenisca roja donde se reunió la primera Asamblea Nacional alemana en 1848, cuna de la democracia.",
        "desc_zh": "始于1848年德国首届由自由选举产生的国民议会召开地。被誉为德国现代民主宪政的摇篮（免费开放）。",
        "desc_fr": "Église en grès rouge où s'est réuni le premier parlement allemand en 1848, berceau de la démocratie.",
        "de": "Historische Rotsandsteinkirche und Tagungsort der ersten deutschen Nationalversammlung von 1848, Wiege der deutschen Demokratie.",
        "tip_en": " Walk upstairs into the main circular assembly hall to view Johannes Grützke's 33-meter continuous mural painting 'The Procession of People's Representatives'.",
        "tip_ja": " 2階の円形本会議堂内部へ！壁面をぐるりと囲むヨハネス・グリュツケ制作の長大壁画『民衆の代表者の行進』をじっくり鑑賞しましょう（入場無料）。",
        "tip_es": " Entra a la sala circular de la planta superior para contemplar el gran mural de 33 metros 'La procesión de los representantes del pueblo'.",
        "tip_zh": " 走入2楼主圆厅内！环顾欣赏由画家 Johannes Grützke 创作长达33米的巨幅环形壁画《人民代表的游行》。（免费进场）",
        "tip_fr": " Montez dans la grande salle circulaire pour admirer la fresque murale géante de 33 mètres de long.",
        "tip_de": " In den rundförmigen Hauptsaal im Obergeschoss gehen und das 33 Meter lange Wandgemälde von Johannes Grützke betrachten.",
        "price_en": "Free Entry", "price_ja": "入場無料", "price_es": "Entrada libre", "price_zh": "免费参观", "price_fr": "Gratuit", "price_de": "Kostenlos",
        "name_en": "St. Paul's Church", "name_ja": "Paulskirche（聖パウロ教会）", "name_es": "Iglesia de San Pablo", "name_zh": "圣保罗教堂", "name_fr": "Église Saint-Paul", "name_de": "Paulskirche"
    },
    # 8. Alte Oper
    {
        "id": "f_8",
        "name": "Alte Oper（アルテ・オーパー旧オペラ座）",
        "category": "Landmark", "rating": "★4.7", "locationZone": "city",
        "lat": 50.1158, "lng": 8.6719, "kids": True, "rain": True, "shopping": False, "free": True,
        "desc_en": "Grand 1880 Neo-Renaissance concert hall rebuilt after WWII, bearing the inscription 'Dem Wahren, Schönen, Guten' (To the True, the Beautiful, the Good).",
        "desc_ja": "1880年建造の壮麗なネオ・ルネサンス様式の旧オペラ座。『真・美・善のために』と刻まれたファサードと大噴水が象徴的。",
        "desc_es": "Gran sala de conciertos neorrenacentista de 1880 reconstruida tras la II Guerra Mundial frente a una plaza con fuente.",
        "desc_zh": "建于1880年的宏伟新文艺复兴风格旧歌剧院。立面上刻有“献给真实、美好与善良”的铭文，正对喷泉大广场。",
        "desc_fr": "Grande salle de concert néo-renaissance de 1880 reconstruite après-guerre avec sa devise 'Dem Wahren, Schönen, Guten'.",
        "de": "Prachtvolles Neurenaissance-Konzertgebäude von 1880 mit der berühmten Inschrift 'Dem Wahren, Schönen, Guten'.",
        "tip_en": "☕ Sit at the outdoor terrace cafe on Opernplatz in front of the Lucae Fountain to enjoy coffee while looking up at the illuminated golden statues.",
        "tip_ja": "☕ オペラ広場（Opernplatz）の噴水前にあるオープンカフェでコーヒー休憩！黄金像がライトアップされる夕暮れ時の雰囲気がロマンチックです。",
        "tip_es": "☕ Disfruta de un café en la terraza exterior de la plaza Opernplatz contemplando la fuente y las estatuas doradas.",
        "tip_zh": "☕ 推荐在 Opernplatz 广场卢卡喷泉旁的露天咖啡座选座，一边喝咖啡一边仰望夜幕下点亮的金色雕像外墙。",
        "tip_fr": "☕ Prenez un café en terrasse sur la place de l'Opéra en admirant la fontaine et les statues illuminées.",
        "tip_de": "☕ Auf der Terrasse des Cafés am Opernplatz vor dem Lucae-Brunnen sitzen und das beleuchtete Gebäude genießen.",
        "price_en": "Square Free (Concerts Varies)", "price_ja": "広場無料（公演により異なる）", "price_es": "Plaza gratis (Conciertos varía)", "price_zh": "广场免费（演出票价另计）", "price_fr": "Place gratuite (Concerts variable)", "price_de": "Platz frei (Konzertkarten variieren)",
        "name_en": "Old Opera House", "name_ja": "Alte Oper（アルテ・オーパー旧オペラ座）", "name_es": "Antigua Ópera de Fráncfort", "name_zh": "老歌剧院", "name_fr": "Opéra de Francfort", "name_de": "Alte Oper"
    },
    # 9. Palmengarten
    {
        "id": "f_9",
        "name": "Palmengarten（パルメンガルテン植物園）",
        "category": "Scenery & Walk", "rating": "★4.7", "locationZone": "city",
        "lat": 50.1239, "lng": 8.6575, "kids": True, "rain": True, "shopping": False, "free": False,
        "desc_en": "22-hectare botanical park featuring the historic 1869 iron-and-glass Palmenhaus greenhouse with tropical palms, exotic orchids, and a boating lake.",
        "desc_ja": "1869年建造の鉄とガラスの大温室『パルメンハウス』を中心に、熱帯植物や珍しいラン、ボート池が広がる22ヘクタールの広大な植物園。",
        "desc_es": "Jardín botánico de 22 hectáreas con el invernadero de hierro y cristal Palmenhaus de 1869 y plantas tropicales.",
        "desc_zh": "占地22公顷的巨型植物园。以始于1869年的铁艺玻璃大温室（Palmenhaus）、热带雨林植物与划船湖泊闻名。",
        "desc_fr": "Jardin botanique de 22 hectares abritant la grande serre en fer et verre de 1869 aux palmiers tropicaux.",
        "de": "22 Hektar großer botanischer Garten mit dem historischen Palmenhaus von 1869 und tropischen Pflanzensammlungen.",
        "tip_en": " Step inside the historic 1869 Palmenhaus glasshouse to experience tropical humidity, giant waterfall, and towering prehistoric tree ferns year-round!",
        "tip_ja": " 1869年建造の大温室『パルメンハウス（Palmenhaus）』内部へ！年間を通じて20℃以上に保たれた熱帯密林と滝のマイナスイオンを体感できます。",
        "tip_es": " Entra en el invernadero Palmenhaus para experimentar el clima tropical y ver la cascada artificial interior.",
        "tip_zh": " 步入古董级玻璃温室 Palmenhaus！感受全年维持在20℃以上的热带湿润雨林与人工瀑布水雾。",
        "tip_fr": " Entrez dans la grande serre Palmenhaus pour vivre le climat tropical et admirer la cascade intérieure !",
        "tip_de": " Das historische Palmenhaus betreten, um das tropische Gewächshausklima mit Wasserfall mitten im Park zu erleben.",
        "price_en": "Entry: €7", "price_ja": "入場料: 7ユーロ", "price_es": "Entrada: 7€", "price_zh": "门票：7 欧元", "price_fr": "Entrée : 7 €", "price_de": "Eintritt: 7 €",
        "name_en": "Palmengarten Botanical Garden", "name_ja": "Palmengarten（パルメンガルテン植物園）", "name_es": "Jardín Botánico Palmengarten", "name_zh": "棕榈园植物园", "name_fr": "Jardin botanique Palmengarten", "name_de": "Palmengarten Frankfurt"
    },
    # 10. Historisches Museum Frankfurt
    {
        "id": "f_10",
        "name": "Historisches Museum Frankfurt（フランクフルト歴史博物館）",
        "category": "Museum & Gallery", "rating": "★4.7", "locationZone": "city",
        "lat": 50.1097, "lng": 8.6828, "kids": True, "rain": True, "shopping": False, "free": False,
        "desc_en": "State-of-the-art city history museum next to Römerberg combining medieval buildings with a modern exhibition wing and interactive 800-year models.",
        "desc_ja": "中世の建築群と最新の現代翼が融合した都市史博物館。800年にわたるフランクフルトの歩みと模型ジオラマを展示。",
        "desc_es": "Museo de historia urbana de vanguardia junto a Römerberg con maquetas interactivas de la ciudad desde la Edad Media.",
        "desc_zh": "紧邻 Römer 广场的顶尖城市历史博物馆。融合中世纪古建筑与现代新馆，通过立体模型全景展示法兰克福800年变迁。",
        "desc_fr": "Musée d'histoire moderne de la ville combinant bâtiments médiévaux et aile moderne avec maquettes géantes.",
        "de": "Modernes Stadtmuseum direkt am Römerberg mit interaktiven Stadtmodellen von den Anfängen bis zur Gegenwart.",
        "tip_en": " Head to the 2nd floor of the modern wing to interact with the motorized 800-year 3D scale model of Frankfurt shifting through history!",
        "tip_ja": " 新館2階にある巨大3D都市模型へ！ボタン操作で中世から現代、そして未来のフランクフルトの街並みが動的に変形・点灯するギミックが素晴らしいです。",
        "tip_es": " Interactúa con la maqueta 3D motorizada de la ciudad en la 2ª planta del ala moderna para ver la evolución urbana.",
        "tip_zh": " 前往新馆2楼观赏可互动的巨型3D城市比例模型！点击控制台即可动态观察800年来法兰克福城市天际线的变迁过程。",
        "tip_fr": " Interagissez avec la grande maquette 3D de la ville au 2e étage pour voir l'évolution de la cité.",
        "tip_de": " Im 2. Stock des Neubaus das bewegliche 3D-Stadtmodell ausprobieren, das die Entwicklung der Stadt zeigt.",
        "price_en": "Entry: €12", "price_ja": "入場料: 12ユーロ", "price_es": "Entrada: 12€", "price_zh": "门票：12 欧元", "price_fr": "Entrée : 12 €", "price_de": "Eintritt: 12 €",
        "name_en": "Frankfurt History Museum", "name_ja": "Historisches Museum Frankfurt（フランクフルト歴史博物館）", "name_es": "Museo Histórico de Fráncfort", "name_zh": "法兰克福历史博物馆", "name_fr": "Musée d'histoire de Francfort", "name_de": "Historisches Museum Frankfurt"
    },
    # 17. Kleinmarkthalle
    {
        "id": "f_17",
        "name": "Kleinmarkthalle（クラインマルクトハレ屋内市場）",
        "category": "Shopping", "rating": "★4.7", "locationZone": "city",
        "lat": 50.1119, "lng": 8.6833, "kids": True, "rain": True, "shopping": True, "free": True,
        "desc_en": "Bustling 1954 indoor food market with 150+ stalls selling regional sausages, green sauce herbs, cheeses, wine, and gourmet international bites.",
        "desc_ja": "150以上の店舗がひしめく1954年開業の歴史的屋内市場。フランクフルトソーセージ、特産名物『グリューネ・ザウセ（緑のソース）』の新鮮ハーブが集結。",
        "desc_es": "Mercado cubierto vibrante de 1954 con más de 150 puestos de salchichas locales, salsa verde, quesos y vinos.",
        "desc_zh": "始于1954年的传统室内食品集市。拥有150多个摊位，汇聚著名的法兰克福特产法兰克福香肠与“绿酱”（Grüne Soße）七草。",
        "desc_fr": "Halle couverte vivante de 1954 avec plus de 150 étals de saucisses régionales, sauce verte et vins.",
        "de": "Buntschillernde Markthalle von 1954 mit über 150 Ständen für Frankfurter Wurst, Grüne Soße und Feinkost.",
        "tip_en": "🍽️ Stand in line at 'Schreiber-Schreiber' on the ground floor to order a hot Fleischwurst sausage served with mustard on paper for €3.50!",
        "tip_ja": "🍽️ 1階の名物肉屋『Schreiber-Schreiber』の行列へ！熱々のフライシュヴルスト（特大ソーセージ）にマスタードを添えた地元の食べ歩きが超絶品（€3.50）。",
        "tip_es": "🍽️ Pide una salchicha caliente Fleischwurst con mostaza en el puesto Schreiber-Schreiber en la planta baja.",
        "tip_zh": "🍽️ 认准一楼肉铺 Schreiber-Schreiber 摊位！排队购买刚出锅配黄芥末酱的热 Fleischwurst 特大香肠（3.50欧）。",
        "tip_fr": "🍽️ Commandez une saucisse chaude Fleischwurst avec de la moutarde chez Schreiber-Schreiber au rez-de-chaussée !",
        "tip_de": "🍽️ Anstehen beim Stand Schreiber im Erdgeschoss für eine heiße Fleischwurst mit Senf auf die Hand!",
        "price_en": "Free Entry (Snacks €3–€8)", "price_ja": "入場無料（軽食3〜8ユーロ）", "price_es": "Entrada libre (Snacks 3€–8€)", "price_zh": "免费进场（小吃3-8欧）", "price_fr": "Gratuit (Snacks 3 €–8 €)", "price_de": "Eintritt frei (Imbiss 3 €–8 €)",
        "name_en": "Kleinmarkthalle Market", "name_ja": "Kleinmarkthalle（クラインマルクトハレ屋内市場）", "name_es": "Mercado Kleinmarkthalle", "name_zh": "小市场大厅", "name_fr": "Marché Kleinmarkthalle", "name_de": "Kleinmarkthalle Frankfurt"
    },
    # 18. Neue Altstadt
    {
        "id": "f_18",
        "name": "Neue Altstadt（新旧市街）",
        "category": "Landmark", "rating": "★4.7", "locationZone": "city",
        "lat": 50.1108, "lng": 8.6836, "kids": True, "rain": False, "shopping": False, "free": True,
        "desc_en": "Reconstructed 7,000sqm historical quarter between Römerberg and Cathedral, featuring 35 meticulously rebuilt medieval and renaissance timber houses.",
        "desc_ja": "戦災で失われた中世・ルネサンス期の木骨造り街並みを精密に再建した『新旧市街（Dom-Römer Quarter）』。石畳の小路とカフェが広がる。",
        "desc_es": "Barrio histórico reconstruido de 35 casas medievales entre el Römerberg y la Catedral con callejones empedrados.",
        "desc_zh": "重建于 Römer 广场与大教堂之间的古城区。35座忠实还原中世纪与文艺复興风格的半木结构建筑与石板路小巷交织。",
        "desc_fr": "Quartier historique reconstruit de 35 maisons médiévales entre le Römerberg et la Cathédrale.",
        "de": "Neu aufgebautes historisches Quartier ('Dom-Römer-Areal') mit 35 fachmännisch rekonstruierten Altstadthäusern.",
        "tip_en": "📸 Stroll down the narrow alleyway 'Hühnermarkt' to capture the Goldene Waage (Golden Scales) renaissance facade with its timber overhangs.",
        "tip_ja": "📸 小路『Hühnermarkt（ニワトリ市場）』の中央へ！黄金の秤の館『Goldene Waage』の精緻なルネサンス様式の張り出し彫刻が見事なフォトスポットです。",
        "tip_es": "📸 Pasea por el callejón Hühnermarkt para fotografiar la casa renacentista Goldene Waage.",
        "tip_zh": "📸 步入 Hühnermarkt（鸡市场）小巷深处！拍摄复刻极尽雕琢的 Renaissance 风格建筑 Goldene Waage（黄金天平之屋）。",
        "tip_fr": "📸 Parcourez la ruelle Hühnermarkt pour photographier la superbe façade renaissance Goldene Waage.",
        "tip_de": "📸 Durch die Gasse Hühnermarkt schlendern und das prächtige Renaissance-Haus 'Goldene Waage' fotografieren.",
        "price_en": "Free Access", "price_ja": "散策無料", "price_es": "Acceso libre", "price_zh": "免费游览", "price_fr": "Accès libre", "price_de": "Kostenlos",
        "name_en": "New Old Town", "name_ja": "Neue Altstadt（新旧市街）", "name_es": "Nuevo Casco Antiguo", "name_zh": "新旧城区", "name_fr": "Nouvelle Vieille Ville", "name_de": "Neue Altstadt Frankfurt"
    },
    # 19. Sachsenhausen & Apfelwein-Kneipen
    {
        "id": "f_19",
        "name": "Sachsenhausen & Apfelwein-Kneipen（ザクセンハウゼン＆アプフェルヴァイン居酒屋街）",
        "category": "Café & Bistro", "rating": "★4.6", "locationZone": "city",
        "lat": 50.1039, "lng": 8.6908, "kids": False, "rain": False, "shopping": False, "free": True,
        "desc_en": "Atmospheric historic district south of the Main river famous for cobble streets and traditional taverns serving local Ebbelwoi (cider) in Bembel earthenware jugs.",
        "desc_ja": "マイン川南岸の石畳の古風な居酒屋街。伝統の青い素焼きピッチャー『ベンベル（Bembel）』で注ぐ名物リンゴ酒（Apfelwein）の名所。",
        "desc_es": "Barrio histórico al sur del río famoso por sus tabernas tradicionales de sidra de manzana (Apfelwein) servida en jarras Bembel.",
        "desc_zh": "位于美因河南岸的古朴小巷酒吧区。以使用特制蓝色土陶壶（Bembel）斟倒当地苹果酒（Apfelwein/Ebbelwoi）闻名。",
        "desc_fr": "Quartier historique au sud du fleuve célèbre pour ses tavernes traditionnelles de cidre (Apfelwein) servi en pichet Bembel.",
        "de": "Alt-Sachsenhausen mit seinen historischen Pflastergassen und traditionellen Apfelwein-Lokalen.",
        "tip_en": "🍽️ Sit at a shared wooden bench inside 'Zum Gemalten Haus' or 'Atschel' and order a 'Sauergespritzter' (cider with sparkling water) paired with Frankfurte Grüne Soße & schnitzel!",
        "tip_ja": "🍽️ 老舗『Zum Gemalten Haus』か『Atschel』の木製長ベンチへ！炭酸水割りのリンゴ酒（Sauergespritzter）と緑のソース（Grüne Soße）付きシュニッツェルを注文するのが鉄板。",
        "tip_es": "🍽️ Pide una jarra de Apfelwein con agua con gas (Sauergespritzter) y un escalope con salsa verde en 'Zum Gemalten Haus'.",
        "tip_zh": "🍽️ 入座老字号“Zum Gemalten Haus”长木桌！点上一壶加气泡水稀释的爽口苹果酒（Sauergespritzter）与搭配特制七草绿酱的炸猪排。",
        "tip_fr": "🍽️ Installez-vous sur les bancs en bois de 'Zum Gemalten Haus' et commandez un pichet d'Apfelwein avec un schnitzel à la sauce verte !",
        "tip_de": "🍽️ Im 'Zum Gemalten Haus' oder 'Atschel' Platz nehmen und Apfelwein (Sauergespritzter) mit Frankfurter Grüner Soße bestellen!",
        "price_en": "Cider: €2.80–€3.50", "price_ja": "リンゴ酒: 2.80〜3.50ユーロ", "price_es": "Sidra: 2,80€–3,50€", "price_zh": "苹果酒：2.80-3.50欧", "price_fr": "Cidre : 2,80 €–3,50 €", "price_de": "Apfelwein: 2,80 €–3,50 €",
        "name_en": "Sachsenhausen Cider District", "name_ja": "Sachsenhausen & Apfelwein-Kneipen（ザクセンハウゼン＆アプフェルヴァイン居酒屋街）", "name_es": "Distrito de la Sidra de Sachsenhausen", "name_zh": "萨克森豪森苹果酒街区", "name_fr": "Quartier du cidre de Sachsenhausen", "name_de": "Sachsenhausen & Apfelwein-Kneipen"
    },
    # 27. Senckenberg Naturmuseum
    {
        "id": "f_27",
        "name": "Senckenberg Naturmuseum（ゼンケンベルク自然博物館）",
        "category": "Museum & Gallery", "rating": "★4.7", "locationZone": "city",
        "lat": 50.1175, "lng": 8.6517, "kids": True, "rain": True, "shopping": False, "free": False,
        "desc_en": "One of Europe's largest natural history museums housing Europe's most comprehensive dinosaur skeleton collection, Diplodocus, and Messel pit fossils.",
        "desc_ja": "欧州最大級の自然史博物館。ディプロドクスやティラノサウルスの全身骨格標本、メッセル坑出土の古生物化石コレクションを所蔵。",
        "desc_es": "Uno de los museos de historia natural más grandes de Europa con la mayor colección de dinosaurios del continente.",
        "desc_zh": "欧洲规模最大的自然历史博物馆之一。拥有全欧洲最完整的梁龙（Diplodocus）与暴龙骨架标本及世界遗产麦塞尔化石坑出土文物。",
        "desc_fr": "L'un des plus grands musées d'histoire naturelle d'Europe avec la plus vaste collection de squelettes de dinosaures du continent.",
        "de": "Eines der größten Naturkundemuseen Europas mit der umfangreichsten Dinosaurier-Ausstellung des Kontinents.",
        "tip_en": "📸 Walk straight into Hall 1 to photograph the original Diplodocus dinosaur skeleton standing alongside the armored Stegosaurus!",
        "tip_ja": "📸 入場してすぐの第1展示ホールへ！巨大なディプロドクス（Diplodocus）とステゴサウルスの本物化石骨格が並ぶ圧巻の展示を見上げることができます。",
        "tip_es": "📸 ¡Entra directamente al Hall 1 para fotografiar el esqueleto de Diplodocus gigante al lado del Stegosaurus!",
        "tip_zh": "📸 步入1号展厅主廊！在巨大的真实梁龙（Diplodocus）与剑龙骨架化石正下方拍照合影。",
        "tip_fr": "📸 Entrez dans la salle 1 pour photographier le squelette géant de Diplodocus à côté du Stégosaure !",
        "tip_de": "📸 Direkt in Saal 1 gehen für Fotos des riesigen Diplodocus-Skeletts direkt neben dem Stegosaurus.",
        "price_en": "Entry: €12", "price_ja": "入場料: 12ユーロ", "price_es": "Entrada: 12€", "price_zh": "门票：12 欧元", "price_fr": "Entrée : 12 €", "price_de": "Eintritt: 12 €",
        "name_en": "Senckenberg Natural History Museum", "name_ja": "Senckenberg Naturmuseum（ゼンケンベルク自然博物館）", "name_es": "Museo de Historia Natural Senckenberg", "name_zh": "森肯贝格自然博物馆", "name_fr": "Musée d'histoire naturelle Senckenberg", "name_de": "Senckenberg Naturmuseum Frankfurt"
    },
    # 29. Euro-Skulptur
    {
        "id": "f_29",
        "name": "Euro-Skulptur (Willy-Brandt-Platz)（巨大ユーロマーク像）",
        "category": "Landmark", "rating": "★4.5", "locationZone": "city",
        "lat": 50.1092, "lng": 8.6739, "kids": True, "rain": False, "shopping": False, "free": True,
        "desc_en": "Iconic 14-meter-tall blue-and-yellow neon Euro symbol sculpture standing in front of the former European Central Bank headquarters.",
        "desc_ja": "旧欧州中央銀行（ECB）本部の前に立つ高さ14mの青と黄色の巨大ユーロマーク彫刻。フランクフルトの金融都市の象徴。",
        "desc_es": "Escultura icónica del símbolo del euro de 14 metros de altura frente a la antigua sede del Banco Central Europeo.",
        "desc_zh": "矗立于旧欧洲中央银行总部前的14米高蓝黄双色巨型欧元符号（€）雕塑。法兰克福金融风云的标志。",
        "desc_fr": "Sculpture emblématique de 14 mètres de haut du symbole de l'Euro devant l'ancien siège de la Banque Centrale Européenne.",
        "de": "Skulptur des Euro-Symbols vor dem ehemaligen Sitz der Europäischen Zentralbank am Willy-Brandt-Platz.",
        "tip_en": "📸 Visit after dark when all 12 yellow stars glowing around the blue € sign light up in vibrant neon against the skyscraper backdrop!",
        "tip_ja": "📸 ネオンが灯る日没後の夜間訪問が映える！青い€マークの周囲にある12個の黄色い星の光が摩天楼ビル群を背に鮮やかに浮かび上がります。",
        "tip_es": "📸 Visítala de noche cuando las 12 estrellas amarillas se iluminan con neón frente a los rascacielos.",
        "tip_zh": "📸 推荐华灯初上的夜晚前往！周遭12颗黄星点亮霓虹色彩，背景即是摩天楼流光溢彩的金融天际线。",
        "tip_fr": "📸 Venez à la nuit tombée quand les 12 étoiles jaunes s'illuminent au néon devant les rascacielos !",
        "tip_de": "📸 Nach Einbruch der Dunkelheit besuchen, wenn die 12 gelben Sterne des Euro-Symbols im Neonlicht leuchten.",
        "price_en": "Free Access", "price_ja": "見学無料", "price_es": "Acceso libre", "price_zh": "免费参观", "price_fr": "Accès libre", "price_de": "Kostenlos",
        "name_en": "Euro Sculpture", "name_ja": "Euro-Skulptur (Willy-Brandt-Platz)（巨大ユーロマーク像）", "name_es": "Escultura del Euro", "name_zh": "巨大欧元符号雕塑", "name_fr": "Sculpture de l'Euro", "name_de": "Euro-Skulptur Frankfurt"
    },
    # 45. Ebbelwei-Express
    {
        "id": "f_45",
        "name": "Historische Straßenbahn Frankfurt (Ebbelwei-Express)（エッベルヴァイ・エクスプレス）",
        "category": "Kids & Family", "rating": "★4.6", "locationZone": "city",
        "lat": 50.1119, "lng": 8.6886, "kids": True, "rain": True, "shopping": False, "free": False,
        "desc_en": "Historic 1970s colorful tram offering weekend loop tours around Frankfurt while serving traditional cider (Apfelwein) and pretzels on board.",
        "desc_ja": "1977年から運航するレトロなカラフル市電。リンゴ酒とプレッツェルを車内で味わいながらフランクフルト市内を1周する観光電車。",
        "desc_es": "Tranvía histórico de los años 70 que ofrece recorridos los fines de semana sirviendo sidra y pretzels a bordo.",
        "desc_zh": "始于1977年的复古彩色有轨观光电车。周末运行，在车厢内一边享用送上的苹果酒与咸普雷结一边穿行于全市主要景点。",
        "desc_fr": "Tramway historique coloré des années 70 proposant des circuits le week-end avec cidre et bretzels servis à bord.",
        "de": "Historische bunte Straßenbahn, die an Wochenenden Stadtrundfahrten mit Apfelwein und Brezeln an Bord anbietet.",
        "tip_en": "🎟️ Board from Hauptbahnhof or Römerberg on weekends; ticket includes 1 bottle of cider (or apple juice) + a bag of mini pretzels!",
        "tip_ja": "🎟️ 週末（土・日・祝日）限定運行！乗車券（€8）には小瓶のリンゴ酒1本（またはリンゴジュース）とプレッツェル袋がセットで付いてきます。",
        "tip_es": "🎟️ ¡Sube los fines de semana desde Hauptbahnhof o Römerberg! La entrada incluye una botella de sidra y minipretzels.",
        "tip_zh": "🎟️ 仅在周末运行！可在 Central Station（中央车站）或 Römer 站上车，车票费用（8欧）已包含一瓶小瓶苹果酒与一袋切糕点心。",
        "tip_fr": "🎟️ Embarquez le week-end depuis la gare centrale ! Le billet inclut une bouteille de cidre et des bretzels.",
        "tip_de": "🎟️ An Wochenenden am Hauptbahnhof oder Römerberg einsteigen – Billet enthält 1 Flasche Apfelwein und Brezeln!",
        "price_en": "Tram Tour: €8", "price_ja": "市電ツアー: 8ユーロ", "price_es": "Tour en tranvía: 8€", "price_zh": "电车游览：8 欧元", "price_fr": "Circuit en tram : 8 €", "price_de": "Straßenbahn-Tour: 8 €",
        "name_en": "Ebbelwei-Express Tram", "name_ja": "Historische Straßenbahn Frankfurt (Ebbelwei-Express)（エッベルヴァイ・エクスプレス）", "name_es": "Tranvía Ebbelwei-Express", "name_zh": "苹果酒观光电车", "name_fr": "Tramway Ebbelwei-Express", "name_de": "Ebbelwei-Express Frankfurt"
    },
    # 46. Rüdesheim am Rhein (Suburban)
    {
        "id": "f_46",
        "name": "Rüdesheim am Rhein & Drosselgasse（リューデスハイム＆つぐみ横丁）",
        "category": "Landmark", "rating": "★4.8", "locationZone": "suburban",
        "lat": 49.9786, "lng": 7.9222, "kids": True, "rain": False, "shopping": False, "free": True,
        "desc_en": "UNESCO Upper Middle Rhine Valley wine town famous for the narrow 144m Drosselgasse alley packed with wine taverns, cable car to Niederwald monument, and river cruises.",
        "desc_ja": "世界遺産ライン渓谷の拠点都市。わずか144mの狭い路地にワイン酒場や生演奏が響く『つぐみ横丁（Drosselgasse）』と葡萄畑を登るロープウェイが名物。",
        "desc_es": "Pueblo vinícola del valle del Rino (UNESCO) famoso por el estrecho callejón Drosselgasse con tabernas de vino y teleférico sobre viñedos.",
        "desc_zh": "联合国教科文组织莱茵河谷名镇。拥有长144米的狭窄酒巷“画眉鸟巷”（Drosselgasse）、缆车与葡萄园梯田。",
        "desc_fr": "Ville viticole de la vallée du Rhin (UNESCO) célèbre pour sa ruelle Drosselgasse avec ses guinguettes et son téléphérique.",
        "de": "Weltberühmte Rheingau-Weinstadt im UNESCO-Welterbe mit der Drosselgasse, Seilbahn zum Niederwalddenkmal und Rheinschifffahrt.",
        "tip_en": " Ride the open two-seater cable car up over the terraced Riesling vineyards to the Niederwald Monument for a panoramic view down the Rhine river bend!",
        "tip_ja": " 2人乗りオープンロープウェイでブドウ畑の上空を空中散歩！頂上のニーダーヴァルト記念碑（Niederwalddenkmal）から見下ろすライン川の曲流ビューは大絶景です。",
        "tip_es": " Sube al teleférico abierto de dos plazas sobre los viñedos de Riesling hasta el Monumento Niederwald para contemplar el río Rino.",
        "tip_zh": " 乘双人露天缆车越过梯田葡萄园！登顶 Niederwald 纪念碑俯瞰莱茵河转弯处的惊艳流向。",
        "tip_fr": " Montez dans le téléphérique ouvert au-dessus des vignobles de Riesling pour la vue sur le Rhin !",
        "tip_de": " Mit der Kabinenseilbahn über die Reben zum Niederwalddenkmal schweben – traumhafter Blick auf das Rheintal!",
        "price_en": "Town Free (Cable Car €10)", "price_ja": "街散策無料（ロープウェイ: 10ユーロ）", "price_es": "Pueblo gratis (Teleférico 10€)", "price_zh": "小镇免费（缆车10欧）", "price_fr": "Ville gratuite (Téléphérique 10 €)", "price_de": "Stadt frei (Seilbahn 10 €)",
        "name_en": "Rüdesheim Rhine Valley", "name_ja": "Rüdesheim am Rhein & Drosselgasse（リューデスハイム＆つぐみ横丁）", "name_es": "Rüdesheim en el Rino", "name_zh": "吕德斯海姆与画眉鸟巷", "name_fr": "Rüdesheim am Rhein", "name_de": "Rüdesheim am Rhein & Drosselgasse"
    },
    # 47. Burg Eltz (Suburban)
    {
        "id": "f_47",
        "name": "Burg Eltz & Rheinburgen（エルツ城＆ライン川・モーゼル川古城群）",
        "category": "Landmark", "rating": "★4.9", "locationZone": "suburban",
        "lat": 50.2053, "lng": 7.3364, "kids": True, "rain": True, "shopping": False, "free": False,
        "desc_en": "Fairytale 12th-century untouched medieval castle hidden deep in a forested valley on a 70m rock outcrop, held by the same family for 33 generations.",
        "desc_ja": "森の奥深くに佇む12世紀のおとぎ話のような中世の古城（無破壊の奇跡の城）。同じ貴族家系が33代800年にわたり所有・保存。",
        "desc_es": "Castillo medieval de ensueño del siglo XII escondido en un valle boscoso sobre una roca de 70m, conservado por la misma familia durante 33 generaciones.",
        "desc_zh": "深藏于森林山谷之中的12世纪童话古堡。历经800年无战火摧残，由同一贵族家族传承33代至今。",
        "desc_fr": "Château médiéval féerique du XIIe siècle caché dans une vallée boisée sur un éperon rocheux de 70m, préservé par la même famille.",
        "de": "Märchenhafte, nie zerstörte Höhenburg aus dem 12. Jahrhundert im Elzbach-Tal, seit 33 Generationen im selben Familienbesitz.",
        "tip_en": "📸 Walk down the paved access road from the upper car park to hit the bend where the castle spire suddenly appears surrounded by dense green forest!",
        "tip_ja": "📸 駐車場からの坂道を徒歩で下る途中の曲がり角がベストアングル！密林の中から突如現れる8つの尖塔を持つ城の絵はがきビューが撮れます。",
        "tip_es": "📸 Camina por el camino pavimentado desde el aparcamiento para fotografiar la vista icónica del castillo emergiendo del bosque.",
        "tip_zh": "📸 沿上层停车场侧的石板坡道步行下山！在弯道处可拍摄古堡八座高耸尖塔从浓密绿林中突兀立起的明信片角度。",
        "tip_fr": "📸 Descendez le chemin pavé desde le parking pour la photo légendaire du château émergeant de la forêt.",
        "tip_de": "📸 Den Fußweg vom Parkplatz hinabgehen: An der Kurve zeigt sich der klassische Postkartenblick auf die Burg im Wald.",
        "price_en": "Entry: €14", "price_ja": "入場料: 14ユーロ", "price_es": "Entrada: 14€", "price_zh": "门票：14 欧元", "price_fr": "Entrée : 14 €", "price_de": "Eintritt: 14 €",
        "name_en": "Eltz Castle", "name_ja": "Burg Eltz & Rheinburgen（エルツ城＆ライン川・モーゼル川古城群）", "name_es": "Castillo de Eltz", "name_zh": "埃尔茨城堡", "name_fr": "Château d'Eltz", "name_de": "Burg Eltz"
    },
    # 48. Mainz Dom & Gutenberg Museum (Suburban)
    {
        "id": "f_48",
        "name": "Mainz: Dom St. Martin & Gutenberg-Museum（マインツ：大聖堂＆グーテンベルク博物館）",
        "category": "Landmark", "rating": "★4.7", "locationZone": "suburban",
        "lat": 49.9989, "lng": 8.2739, "kids": True, "rain": True, "shopping": False, "free": False,
        "desc_en": "Historic Rhine city featuring the 1000-year-old Romanesque Cathedral of St. Martin, Chagall blue stained-glass windows at St. Stephan, and original 1450s printing press Bibles at Gutenberg Museum.",
        "desc_ja": "千年以上の歴史を誇る大聖堂と、活版印刷の発明者グーテンベルクの博物館。聖シュテファン教会の美しいシャガール・ブルーのステンドグラスが見どころ。",
        "desc_es": "Ciudad histórica del Rino con la catedral románica de San Martín, las vidrieras azules de Chagall y el Museo Gutenberg.",
        "desc_zh": "千年罗曼式主教堂所在地。拥有 Chagall 创作的湛蓝彩绘玻璃（圣史蒂芬教堂）与印刷术发明家古腾堡博物馆。",
        "desc_fr": "Ville rhénane historique avec la cathédrale mille-naire Saint-Martin, les vitraux bleus de Chagall et le musée Gutenberg.",
        "de": "Historische Domstadt am Rhein mit dem tausendjährigen Dom St. Martin, den Chagall-Fenstern in St. Stephan und dem Gutenberg-Museum.",
        "tip_en": "📜 Walk into the Gutenberg Museum vault to admire two original 1450s printed Gutenberg Bibles on vellum, the world's most valuable books!",
        "tip_ja": "📜 グーテンベルク博物館（Gutenberg-Museum）の重厚な地下金庫室へ！1450年代に印刷された本物の『グーテンベルク聖書』原本2冊を間近で閲覧できます。",
        "tip_es": "📜 Entra en la caja fuerte del Museo Gutenberg para ver las dos Biblias originales impresas en pergamino hacia 1450.",
        "tip_zh": "📜 步入古腾堡博物馆特制地下保险库！亲眼观赏1450年代印制的两册羊皮纸《古腾堡圣书》印刷原本。",
        "tip_fr": "📜 Entrez dans la salle coffre-fort du musée Gutenberg pour admirer les deux Bibles originales de 1450 !",
        "tip_de": "📜 Im Tresorraum des Gutenberg-Museums zwei originale Gutenberg-Bibel-Drucke aus dem Jahr 1450 im Original betrachten.",
        "price_en": "Museum Entry: €5", "price_ja": "博物館入場料: 5ユーロ", "price_es": "Entrada museo: 5€", "price_zh": "博物馆门票：5 欧元", "price_fr": "Entrée musée : 5 €", "price_de": "Museum Eintritt: 5 €",
        "name_en": "Mainz Cathedral & Gutenberg Museum", "name_ja": "Mainz: Dom St. Martin & Gutenberg-Museum（マインツ：大聖堂＆グーテンベルク博物館）", "name_es": "Catedral de Maguncia y Museo Gutenberg", "name_zh": "美因茨大教堂与古腾堡博物馆", "name_fr": "Cathédrale de Mayence et musée Gutenberg", "name_de": "Mainz: Dom St. Martin & Gutenberg-Museum"
    },
    # 58. Kloster Eberbach (Suburban)
    {
        "id": "f_58",
        "name": "Kloster Eberbach（エバーバッハ修道院）",
        "category": "Landmark", "rating": "★4.8", "locationZone": "suburban",
        "lat": 50.0425, "lng": 8.0461, "kids": True, "rain": True, "shopping": False, "free": False,
        "desc_en": "1136 Romanesque and Gothic Cistercian monastery in the Rheingau, famed as the filming location for the movie 'The Name of the Rose' and top Riesling wine estate.",
        "desc_ja": "1136年創建のシトー会修道院。映画『薔薇の名前（ショーン・コネリー主演）』のロケ地であり、独屈指のリースリングワイン醸造所。",
        "desc_es": "Monasterio cisterciense de 1136 en el Rheingau famoso como escenario de la película 'El nombre de la rosa' y bodega de vino Riesling.",
        "desc_zh": "始于1136年的熙笃会修道院。为电影《玫瑰之名》（Sean Connery 主演）实景拍摄地，兼具古老雷司令葡萄酒酒庄。",
        "desc_fr": "Abbaye cistercienne de 1136 célèbre comme lieu de tournage du film 'Le Nom de la Rose' et domaine viticole de Riesling.",
        "de": "Ehemalige Zisterzienser-Abtei von 1136 im Rheingau, berühmter Drehort des Films 'Der Name der Rose' und Spitzen-Weingut.",
        "tip_en": "🍷 Visit the historical wine press house (Laienrefektorium) to see 17th-century massive wooden wine presses, then taste Riesling in the monastic cellar shop!",
        "tip_ja": "🍷 17世紀の超巨大な木製ワイン圧搾機がズラリと並ぶ『修道士の食堂』を見学後、修道院直営ショップで醸造されたリースリング白ワインを試飲するのが最高！",
        "tip_es": "🍷 Visita la sala de las prensas de vino históricas del siglo XVII y prueba una copa de vino Riesling en la tienda de la abadía.",
        "tip_zh": "🍷 走入直观陈列着17世纪巨型木质榨汁机的大厅！参观完毕后前往修道院直营酒窖品鉴纯正雷司令干白葡萄酒。",
        "tip_fr": "🍷 Visitez la salle des grands pressoirs à vin du XVIIe siècle puis dégustez un verre de Riesling à la boutique !",
        "tip_de": "🍷 Die riesigen historischen Holzkeltern im Laienrefektorium besichtigen und anschließend Riesling in der Kloster-Vinothek probieren.",
        "price_en": "Entry: €12", "price_ja": "入場料: 12ユーロ", "price_es": "Entrada: 12€", "price_zh": "门票：12 欧元", "price_fr": "Entrée : 12 €", "price_de": "Eintritt: 12 €",
        "name_en": "Eberbach Abbey", "name_ja": "Kloster Eberbach（エバーバッハ修道院）", "name_es": "Abadía de Eberbach", "name_zh": "埃伯巴赫修道院", "name_fr": "Abbaye d'Eberbach", "name_de": "Kloster Eberbach"
    },
    # 59. Darmstadt Mathildenhöhe (Suburban)
    {
        "id": "f_59",
        "name": "Darmstadt: Mathildenhöhe (UNESCO)（ダルムシュタット：マチルダの丘）",
        "category": "Landmark", "rating": "★4.7", "locationZone": "suburban",
        "lat": 49.8769, "lng": 8.6675, "kids": True, "rain": False, "shopping": False, "free": True,
        "desc_en": "UNESCO World Heritage Art Nouveau (Jugendstil) artists' colony in Darmstadt featuring Olbrich's 48m Wedding Tower and gold-domed Russian Chapel.",
        "desc_ja": "ユネスコ世界遺産のユーゲントシュティール（アール・ヌーヴォー）芸術家村。結婚記念塔（Hochzeitsturm）と金色のロシア教会がシンボル。",
        "desc_es": "Colonia de artistas del Art Nouveau (UNESCO) en Darmstadt con la Torre de la Boda de 48m y la capilla rusa con cúpula dorada.",
        "desc_zh": "联合国教科文组织新艺术运动（Jugendstil）艺术家村。拥有48米高的五指“结婚纪念塔”与金色圆顶俄罗斯教堂。",
        "desc_fr": "Colonie d'artistes Art Nouveau (UNESCO) à Darmstadt avec la Tour du Mariage de 48m et la chapelle russe aux dômes dorés.",
        "de": "UNESCO-Welterbe der Jugendstil-Künstlerkolonie Darmstadt mit dem 48m hohen Hochzeitsturm und der Russischen Kapelle.",
        "tip_en": "📸 Climb the 5-finger Wedding Tower (Hochzeitsturm) terrace for a view over the plane-tree grove and gilded mosaic Russian Chapel!",
        "tip_ja": "📸 5本の指の形をした結婚記念塔（Hochzeitsturm）のテラスへ！プラタナスの木立と金色に輝く玉ねぎ屋根のロシア教会を見下ろすアングルが最高です。",
        "tip_es": "📸 Sube a la terraza de la Torre de la Boda para contemplar el arboleda de plátanos y la capilla rusa dorada.",
        "tip_zh": "📸 登顶“五指结婚纪念塔”外侧露台！俯瞰繁茂的法国梧桐树林与金光闪闪的洋葱顶俄罗斯教堂。",
        "tip_fr": "📸 Montez sur la terrasse de la Tour du Mariage pour la vue sur le bosquet de platanes et la chapelle russe.",
        "tip_de": "📸 Auf die Aussichtsplattform des Fünffingerturms steigen für einen Blick auf den Platanenhain und die Russische Kapelle.",
        "price_en": "Grounds Free (Tower €5)", "price_ja": "敷地無料（塔登頂: 5ユーロ）", "price_es": "Recinto gratis (Torre 5€)", "price_zh": "园区免费（登塔5欧）", "price_fr": "Parc gratuit (Tour 5 €)", "price_de": "Areal frei (Turm 5 €)",
        "name_en": "Darmstadt Mathildenhöhe", "name_ja": "Darmstadt: Mathildenhöhe (UNESCO)（ダルムシュタット：マチルダの丘）", "name_es": "Mathildenhöhe en Darmstadt", "name_zh": "达姆施塔特玛蒂尔德丘", "name_fr": "Mathildenhöhe à Darmstadt", "name_de": "Darmstadt: Mathildenhöhe (UNESCO)"
    },
    # 61. Wertheim Village (Suburban)
    {
        "id": "f_61",
        "name": "Wertheim Village（ヴェルトハイム・ビレッジ）",
        "category": "Shopping", "rating": "★4.6", "locationZone": "suburban",
        "lat": 49.7719, "lng": 9.5772, "kids": True, "rain": True, "shopping": True, "free": True,
        "desc_en": "Luxury open-air outlet shopping village 1 hour from Frankfurt featuring 110+ designer fashion boutiques with up to 60% discounts.",
        "desc_ja": "フランクフルトから車・シャトルバスで1時間。110以上の世界的デザイナーブランドが最大60%オフで並ぶオープンエアのアウトレットモール。",
        "desc_es": "Villa de compras de outlet de lujo a 1 hora de Fráncfort con más de 110 boutiques de diseñadores con descuentos de hasta el 60%.",
        "desc_zh": "距离法兰克福1小时车程的大型露天名品折扣奥特莱斯购物村。汇聚110余家国际一线大牌，享有低至四折优惠。",
        "desc_fr": "Village outlet de luxe à 1h de Francfort proposant plus de 110 boutiques de designers avec des réductions jusqu'à 60%.",
        "de": "Luxus-Designer-Outlet-Village 1 Stunde von Frankfurt mit über 110 Boutiquen und bis zu 60% Rabatt.",
        "tip_en": "🚌 Take the official 'Shopping Express' shuttle bus direct from Frankfurt Hauptbahnhof (Central Station) on weekends for stress-free round-trip transport!",
        "tip_ja": "🚌 フランクフルト中央駅から直行運行する公式シャトルバス『Shopping Express』が圧倒的に快適！往復乗車券を事前購入すると便利です。",
        "tip_es": "🚌 Toma el autobús oficial 'Shopping Express' directo desde la estación central de Fráncfort Hauptbahnhof el fin de semana.",
        "tip_zh": "🚌 推荐于中央车站（Hauptbahnhof）搭乘官方“Shopping Express”直达穿梭巴士！往返便捷直达车门。",
        "tip_fr": "🚌 Prenez la navette officielle 'Shopping Express' depuis la gare centrale de Francfort le week-end !",
        "tip_de": "🚌 Den offiziellen 'Shopping Express'-Shuttlebus direkt vom Hauptbahnhof Frankfurt nutzen für eine entspannte Anreise.",
        "price_en": "Free Entry (Shopping)", "price_ja": "入館無料（ショッピング）", "price_es": "Entrada libre (Compras)", "price_zh": "免费入场（购物）", "price_fr": "Entrée libre", "price_de": "Freier Eintritt",
        "name_en": "Wertheim Village Outlet", "name_ja": "Wertheim Village（ヴェルトハイム・ビレッジ）", "name_es": "Wertheim Village Outlet", "name_zh": "威尔特海姆购物村", "name_fr": "Wertheim Village", "name_de": "Wertheim Village Outlet"
    }
]

# Write to data/cities/frankfurt.json
fpath = "data/cities/frankfurt.json"
data = {
    "cityName": "Frankfurt, Germany",
    "spots": frankfurt_spots
}

with open(fpath, 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print(f"🎉 Successfully created {len(frankfurt_spots)} spots in data/cities/frankfurt.json")
