import json
import os

# -------------------------------------------------------------
# BERLIN 75 SPOTS COMPREHENSIVE MULTILINGUAL DATABASE GENERATOR
# -------------------------------------------------------------

berlin_spots = [
    # 1. Brandenburger Tor
    {
        "id": "b_1",
        "name": "Brandenburger Tor（ブランデンブルク門）",
        "category": "Landmark",
        "rating": "★4.8",
        "locationZone": "city",
        "lat": 52.5163, "lng": 13.3777,
        "kids": True, "rain": False, "shopping": False, "free": True,
        "desc_en": "18th-century Neoclassical sandstone monument topped by the Quadriga chariot, iconic symbol of German unity and Cold War history.",
        "desc_ja": "18世紀末建造の新古典主義様式の砂岩城門。頂上に勝利の女神クアドリガが輝き、冷戦の東西分断とドイツ再統一の象徴。",
        "desc_es": "Monumento neoclásico del siglo XVIII coronado por la Cuadriga, símbolo icónico de la reunificación alemana.",
        "desc_zh": "建于18世纪末的新古典主义沙岩城门，顶端矗立胜利女神四马战车，是德国冷战分断与重新统一的象征。",
        "desc_fr": "Monument néoclassique du XVIIIe siècle surmonté du Quadrige, symbole emblématique de la réunification allemande.",
        "desc_de": "Neoklassizistisches Sandsteinmonument des 18. Jahrhunderts mit der Quadriga, weltberühmtes Symbol der deutschen Einheit.",
        "tip_en": "📸 Visit at dusk when blue hour lighting illuminates Pariser Platz, or early morning at 7:00 AM to take photos without crowds.",
        "tip_ja": "📸 パリ広場のライトアップが灯る日没直後のブルーアワーの訪問が最高！人混みを避けて門の全景を撮るなら早朝7:00前が狙い目です。",
        "tip_es": "📸 Visítala al atardecer cuando la iluminación azul ilumina la plaza, o a las 7:00 h para fotos sin multitud.",
        "tip_zh": "📸 推荐黄昏蓝调时刻前往拍摄华灯初上的巴黎广场！若想拍到没有游人的空旷全景，建议早晨7点前抵达。",
        "tip_fr": "📸 Admirez l'illumination à l'heure bleue sur la Pariser Platz, ou venez dès 7h du matin pour des photos sans la foule.",
        "tip_de": "📸 Zur blauen Stunde besuchen, wenn der Platz beleuchtet ist, oder morgens vor 7:00 Uhr für fotos ohne Menschenmassen.",
        "price_en": "Free Entry", "price_ja": "見学無料", "price_es": "Entrada libre", "price_zh": "免费参观", "price_fr": "Accès libre", "price_de": "Kostenlos",
        "name_en": "Brandenburg Gate", "name_ja": "Brandenburger Tor（ブランデンブルク門）", "name_es": "Puerta de Brandeburgo", "name_zh": "勃兰登堡门", "name_fr": "Porte de Brandebourg", "name_de": "Brandenburger Tor"
    },
    # 2. Reichstagsgebäude
    {
        "id": "b_2",
        "name": "Reichstagsgebäude（連邦議会議事堂）",
        "category": "Landmark",
        "rating": "★4.7",
        "locationZone": "city",
        "lat": 52.5186, "lng": 13.3761,
        "kids": True, "rain": True, "shopping": False, "free": True,
        "desc_en": "Historic parliament building redesigned by Norman Foster featuring a spectacular glass dome with a mirrored light cone.",
        "desc_ja": "1894年建造の歴史的議事堂。ノーマン・フォスター設計のガラスドーム内部の螺旋スロープと中央鏡面コーンが見事。",
        "desc_es": "Edificio del parlamento rediseñado por Norman Foster con una cúpula de cristal y un cono de espejos.",
        "desc_zh": "由诺曼·福斯特主持翻修的历史国会大厦，拥有巨大的玻璃穹顶与中央倒立螺旋镜面光锥。",
        "desc_fr": "Bâtiment historique du parlement réaménagé par Norman Foster avec un cône de miroirs sous un dôme de verre.",
        "desc_de": "Historisches Parlamentsgebäude mit der von Norman Foster gestalteten Glaskuppel und Spiegel-Lichtkegel.",
        "tip_en": "🎟️ Free web registration on the Bundestag portal is REQUIRED 2-4 weeks in advance! Bring your valid original passport for security check.",
        "tip_ja": "🎟️ 公式サイトでの完全無料の事前Web日時予約が絶対必須！入場時はパスポート（原本）の本人確認が厳格に行われます。",
        "tip_es": "🎟️ ¡Es OBLIGATORIO registrarse gratis en la web con 2-4 semanas de antelación! Trae tu pasaporte original para el control.",
        "tip_zh": "🎟️ 必须提前2-4周在联邦议会官网进行免费预约登记！入场安检必须出示护照原件进行身份核对。",
        "tip_fr": "🎟️ Réservation GRATUITE obligatoire 2 à 4 semaines à l'avance sur le site web ! Passeport original obligatoire.",
        "tip_de": "🎟️ Kostenlose Online-Registrierung 2–4 Wochen im Voraus Pflicht! Gültigen Reisepass zur Sicherheitskontrolle mitbringen.",
        "price_en": "Free (Online Booking Required)", "price_ja": "無料（要事前Web予約）", "price_es": "Gratis (Reserva previa)", "price_zh": "免费（须提前网约）", "price_fr": "Gratuit (Sur réservation)", "price_de": "Kostenlos (Anmeldung erforderlich)",
        "name_en": "Reichstag Building", "name_ja": "Reichstagsgebäude（連邦議会議事堂）", "name_es": "Edificio del Reichstag", "name_zh": "德国国会大厦", "name_fr": "Palais du Reichstag", "name_de": "Reichstagsgebäude"
    },
    # 3. Museumsinsel (UNESCO)
    {
        "id": "b_3",
        "name": "Museumsinsel (UNESCO)（博物館島）",
        "category": "Museum & Gallery",
        "rating": "★4.8",
        "locationZone": "city",
        "lat": 52.5206, "lng": 13.3969,
        "kids": True, "rain": True, "shopping": False, "free": False,
        "desc_en": "UNESCO World Heritage island in the Spree river grouping 5 prestigious museums housing 6,000 years of art & archaeology.",
        "desc_ja": "シュプレー川の中州に位置するユネスコ世界遺産の博物館群。5つの殿堂ミュージアムが集結する人類文明の宝庫。",
        "desc_es": "Isla en el río Spree patrimonio UNESCO que alberga 5 prestigiosos museos con 6.000 años de arte y arqueología.",
        "desc_zh": "矗立于施普雷河中洲的世界遗产博物馆群。汇聚了5座世界级博物馆，陈列着跨越6000年的文明瑰宝。",
        "desc_fr": "Île sur la Spree classée UNESCO regroupant 5 grands musées retraçant 6 000 ans d'histoire de l'art.",
        "desc_de": "UNESCO-Welterbe-Museumsensemble auf der Spreeinsel mit 5 weltberühmten Museen für Kunst und Archäologie.",
        "tip_en": "🎟️ Buy the 'Museum Island 1-Day Pass' (€24) to visit all 5 museums. Walk through James-Simon-Galerie central entrance hub.",
        "tip_ja": "🎟️ 5館共通1日チケット（1-Day Museum Island Pass €24）の購入が圧倒的にお得。新中央入口『ジェームズ・サイモン・ギャラリー』から入場するのが快適。",
        "tip_es": "🎟️ Compra el pase de 1 día de la Isla de los Museos (24€) para visitar los 5 museos desde el centro James-Simon-Galerie.",
        "tip_zh": "🎟️ 购买通吃5馆的“博物馆岛一日通票”（24欧元）最划算。推荐从崭新的 James-Simon-Galerie 中央入口穿行。",
        "tip_fr": "🎟️ Achetez le Pass 1 jour Île des Musées (24 €) pour accéder aux 5 musées via la James-Simon-Galerie.",
        "tip_de": "🎟️ Das 1-Tages-Ticket Museumsinsel (24 €) nutzen und zentral über die James-Simon-Galerie einsteigen.",
        "price_en": "Pass: €24", "price_ja": "通票: 24ユーロ", "price_es": "Pase: 24€", "price_zh": "通票：24 欧元", "price_fr": "Pass : 24 €", "price_de": "Museumspass: 24 €",
        "name_en": "Museum Island", "name_ja": "Museumsinsel (UNESCO)（博物館島）", "name_es": "Isla de los Museos", "name_zh": "博物馆岛", "name_fr": "Île des Musées", "name_de": "Museumsinsel"
    },
    # 4. Pergamonmuseum
    {
        "id": "b_4",
        "name": "Pergamonmuseum（ペルガモン博物館）",
        "category": "Museum & Gallery",
        "rating": "★4.8",
        "locationZone": "city",
        "lat": 52.5212, "lng": 13.3969,
        "kids": True, "rain": True, "shopping": False, "free": False,
        "desc_en": "World-renowned museum famed for full-scale reconstructed ancient monuments including the Babylon Ishtar Gate and Market Gate of Miletus.",
        "desc_ja": "青いバビロニアの『イシュタール門』や『ミレトスの市場門』など、古代遺跡の実物大再構築展示で知られる世界最高峰の博物館。",
        "desc_es": "Museo famoso por reconstrucciones de monumentos antiguos como la Puerta de Ishtar de Babilonia y la Puerta de Mileto.",
        "desc_zh": "以等比例重构古代庞大建筑闻名于世，陈列着蓝色的巴比伦伊什塔尔城门与米利都市场大门。",
        "desc_fr": "Musée célèbre pour ses reconstitutions monumentales dont la Porte d'Ishtar de Babylone et la Porte de Milet.",
        "de": "Weltberühmtes Museum mit imposanten Rekonstruktionen antiker Bauwerke wie dem Babylonischen Ischtar-Tor.",
        "tip_en": "⚠️ Note: North wing under major renovation until 2027 (Pergamon Altar closed); Das Panorama 360° temporary exhibition hall is open opposite!",
        "tip_ja": "⚠️ 現在北翼（ペルガモン祭壇）が大規模改修工事中（2027年まで）。対岸にある Yadegar Asisi 制作の『ペルガモン360°パノラマ館』の見学がセットで人気！",
        "tip_es": "⚠️ El Altar de Pérgamo está cerrado por obras hasta 2027. ¡Visita la exposición temporal 360° Das Panorama enfrente!",
        "tip_zh": "⚠️ 北翼帕加马祭坛正在大修中（预计至2027年）。建议前往对岸参观 Yadegar Asisi 创作的“360度3D全景体验馆”。",
        "tip_fr": "⚠️ L'autel de Pergame est fermé pour rénovation jusqu'en 2027. Visitez l'exposition 360° Das Panorama en face !",
        "de": "⚠️ Das Pergamonaltar-Gebäude ist bis 2027 wegen Sanierung geschlossen. Die 360°-Panorama-Schau gegenüber besuchen!",
        "price_en": "Entry: €12", "price_ja": "入場料: 12ユーロ", "price_es": "Entrada: 12€", "price_zh": "门票：12 欧元", "price_fr": "Entrée : 12 €", "price_de": "Eintritt: 12 €",
        "name_en": "Pergamon Museum", "name_ja": "Pergamonmuseum（ペルガモン博物館）", "name_es": "Museo de Pérgamo", "name_zh": "佩加蒙博物馆", "name_fr": "Musée de Pergame", "name_de": "Pergamonmuseum"
    },
    # 5. Neues Museum
    {
        "id": "b_5",
        "name": "Neues Museum（新博物館）",
        "category": "Museum & Gallery",
        "rating": "★4.7",
        "locationZone": "city",
        "lat": 52.5202, "lng": 13.3977,
        "kids": True, "rain": True, "shopping": False, "free": False,
        "desc_en": "David Chipperfield-restored museum exhibiting Egyptian artifacts, prehistory collections, and the world-famous Bust of Nefertiti.",
        "desc_ja": "エジプト考古学コレクションを展示。3300年前の奇跡の美を誇る『王妃ネフェルティティの胸像』を所蔵する殿堂。",
        "desc_es": "Museo restaurado por David Chipperfield que alberga artefactos egipcios y el mundialmente famoso Busto de Nefertiti.",
        "desc_zh": "由 David Chipperfield 修缮的博物馆，展示古代埃及珍贵文物、先史时代遗物与举世闻名的“纳芙蒂蒂王后胸像”。",
        "tip_en": "📸 Photography is STRICTLY PROHIBITED inside the Octagonal Room housing the Nefertiti Bust—enjoy looking with your own eyes!",
        "tip_ja": "📸 ネフェルティティの胸像が展示されている『八角形の間』の内部は写真・動画撮影が完全禁止！ガードマンの監視の元、自分の目でじっくり鑑賞しましょう。",
        "tip_es": "📸 ¡Está ESTRICTAMENTE PROHIBIDO fotografiar el busto de Nefertiti en la sala octogonal! Disfruta la vista en persona.",
        "tip_zh": "📸 纳芙蒂蒂胸像陈列的“八面体主厅”内严禁任何形式的拍照录像！请放下手机用肉眼近距离打量这一3300年的美学奇迹。",
        "tip_fr": "📸 Les photos sont STRICTEMENT INTERDITES dans la salle octogonale abritant le buste de Néfertiti.",
        "tip_de": "📸 Fotografieren im achteckigen Raum mit der Büste der Nofretete ist STRENGSTENS VERBOTEN!",
        "price_en": "Entry: €14", "price_ja": "入場料: 14ユーロ", "price_es": "Entrada: 14€", "price_zh": "门票：14 欧元", "price_fr": "Entrée : 14 €", "price_de": "Eintritt: 14 €",
        "name_en": "Neues Museum", "name_ja": "Neues Museum（新博物館）", "name_es": "Museo Nuevo", "name_zh": "新博物馆", "name_fr": "Nouveau Musée", "name_de": "Neues Museum"
    },
    # 6. Berliner Dom
    {
        "id": "b_6",
        "name": "Berliner Dom（ベルリン大聖堂）",
        "category": "Landmark",
        "rating": "★4.7",
        "locationZone": "city",
        "lat": 52.5190, "lng": 13.4010,
        "kids": True, "rain": True, "shopping": False, "free": False,
        "desc_en": "Monumental 19th-century Neo-Renaissance Protestant cathedral with a glowing turquoise dome, Hohenzollern crypt, and panoramic climb.",
        "desc_ja": "シュプレー川沿いに建つ壮麗なプロテスタント大聖堂。緑のドーム屋根、ホーエンツォレルン家の地下墓所、270段の展望回廊が見どころ。",
        "desc_es": "Catedral protestante neorrenacentista del siglo XIX con una cúpula turquesa, cripta real y mirador panorámico.",
        "desc_zh": "耸立于施普雷河畔的宏伟新文艺复兴风格新教大教堂。拥有松石绿穹顶、霍亨索伦皇室地下陵墓与270级观景步道。",
        "tip_en": "📸 Climb the 270 steps up to the Dome Walkway (Domkuppel) for an open-air 360-degree panorama over Museum Island and Television Tower.",
        "tip_ja": "📸 270段の階段を登ってドーム外周のドーム・ウォークウェイ（Domkuppel）へ！博物館島とテレビ塔を見下ろす360度オープンエア展望が楽しめます。",
        "tip_es": "📸 Sube los 270 escalones hasta el mirador exterior de la cúpula para una vista de 360° de la Isla de los Museos y la Torre de TV.",
        "tip_zh": "📸 攀登270级台阶直达穹顶外围回廊（Domkuppel）！360度无遮挡俯瞰博物馆岛与电视塔。",
        "tip_fr": "📸 Montez les 270 marches jusqu'à la galerie extérieure du dôme pour une vue panoramique sur l'Île des Musées.",
        "tip_de": "📸 Die 270 Stufen zum Kuppelumgang aufsteigen für einen 360-Grad-Rundumblick auf die Museumsinsel und den Fernsehturm.",
        "price_en": "Entry: €10", "price_ja": "入場料: 10ユーロ", "price_es": "Entrada: 10€", "price_zh": "门票：10 欧元", "price_fr": "Entrée : 10 €", "price_de": "Eintritt: 10 €",
        "name_en": "Berlin Cathedral", "name_ja": "Berliner Dom（ベルリン大聖堂）", "name_es": "Catedral de Berlín", "name_zh": "柏林大教堂", "name_fr": "Cathédrale de Berlin", "name_de": "Berliner Dom"
    },
    # 7. East Side Gallery
    {
        "id": "b_7",
        "name": "East Side Gallery（イーストサイドギャラリー）",
        "category": "Landmark",
        "rating": "★4.6",
        "locationZone": "city",
        "lat": 52.5050, "lng": 13.4397,
        "kids": True, "rain": False, "shopping": False, "free": True,
        "desc_en": "1.3km stretch of the original Berlin Wall along the Spree turned into the world's longest open-air mural gallery with 100+ paintings.",
        "desc_ja": "シュプレー川沿いに残る1.3kmのベルリンの壁実物。世界各国のアーティストによる100以上の壁画が並ぶオープンエアギャラリー。",
        "desc_es": "Tramo de 1.3 km del Muro de Berlín transformado en la galería al aire libre más larga del mundo con más de 100 murales.",
        "desc_zh": "沿施普雷河伸展的1.3公里柏林墙遗址。来自世界各地的艺术家在此创作了100多幅巨幅露天涂鸦壁画。",
        "tip_en": "📸 Walk from Ostbahnhof station towards Oberbaumbrücke to find Dmitri Vrubel's famous 'Fraternal Kiss' mural ('My God, Help Me to Survive This Deadly Love').",
        "tip_ja": "📸 オストバーンホフ駅からオーバーバウム橋に向かって歩くと、旧ソ連のブレジネフと東独ホネッカーの有名な壁画『兄弟のキス』があります！",
        "tip_es": "📸 Camina desde Ostbahnhof hacia Oberbaumbrücke para ver el famoso mural 'Beso Fraterno' entre Brézhnev y Honecker.",
        "tip_zh": "📸 从 Ostbahnhof 火车站方向走向 Oberbaumbrücke 桥，即可找到鼎鼎大名的《兄弟之吻》（勃列日涅夫与昂纳克拥吻）壁画！",
        "tip_fr": "📸 Marchez depuis la gare Ostbahnhof vers le pont Oberbaumbrücke pour photographier la célèbre fresque du 'Baiser Fraternel'.",
        "tip_de": "📸 Vom Ostbahnhof in Richtung Oberbaumbrücke spazieren, um das berühmte Wandbild 'Bruderkuss' zu fotografieren.",
        "price_en": "Free Access", "price_ja": "見学無料", "price_es": "Acceso libre", "price_zh": "免费参观", "price_fr": "Accès libre", "price_de": "Kostenlos",
        "name_en": "East Side Gallery", "name_ja": "East Side Gallery（イーストサイドギャラリー）", "name_es": "Galería del Lado Este", "name_zh": "东边画廊", "name_fr": "East Side Gallery", "name_de": "East Side Gallery"
    },
    # 8. Gedenkstätte Berliner Mauer
    {
        "id": "b_8",
        "name": "Gedenkstätte Berliner Mauer（ベルリンの壁記念館）",
        "category": "Landmark",
        "rating": "★4.7",
        "locationZone": "city",
        "lat": 52.5352, "lng": 13.3903,
        "kids": True, "rain": False, "shopping": False, "free": True,
        "desc_en": "Open-air memorial site along Bernauer Straße preserving an authentic original strip of the Berlin Wall, watchtower, and border 'death strip'.",
        "desc_ja": "ベルナウアー通り沿いの広大な野外記念施設。無人地帯（Death Strip）や監視塔、分断された街の歴史がそのままの姿で保存されている。",
        "desc_es": "Sitio conmemorativo al aire libre que conserva un tramo del muro, torre de vigilancia y la 'franja de la muerte'.",
        "desc_zh": "位于 Bernauer 街的露天纪念馆。完整保留了原汁原味的柏林墙、铁丝网、监视塔与昔日无人走廊“死亡地带”。",
        "tip_en": "📸 Climb to the 5th-floor observation tower inside the Documentation Centre for a top-down view straight into the preserved 'Death Strip' border section.",
        "tip_ja": "📸 通りの向かいにあるドキュメンテーションセンター5階の無料展望タワーへ！保存された『無人地帯（Death Strip）』の構造を真上から俯瞰できます。",
        "tip_es": "📸 Sube a la torre de observación en la 5ª planta del Centro de Documentación para ver la 'Franja de la Muerte' desde arriba.",
        "tip_zh": "📸 登上一路之隔的档案中心5楼免费展望塔！从高处直视完整保存的“死亡地带”防护铁丝网与监视塔。",
        "tip_fr": "📸 Montez à la tour d'observation du 5e étage du Centre de Documentation pour voir le 'No Man's Land' conservé d'en haut.",
        "tip_de": "📸 Auf den Aussichtsturm im 5. Stock des Dokumentationszentrums steigen, um den erhaltenen 'Todesstreifen' von oben zu sehen.",
        "price_en": "Free Entry", "price_ja": "入場無料", "price_es": "Entrada libre", "price_zh": "免费开放", "price_fr": "Gratuit", "price_de": "Kostenlos",
        "name_en": "Berlin Wall Memorial", "name_ja": "Gedenkstätte Berliner Mauer（ベルリンの壁記念館）", "name_es": "Memorial del Muro de Berlín", "name_zh": "柏林墙纪念馆", "name_fr": "Mémorial du Mur de Berlin", "name_de": "Gedenkstätte Berliner Mauer"
    },
    # 9. Topographie des Terrors
    {
        "id": "b_9",
        "name": "Topographie des Terrors（トポグラフィー・オブ・テラー）",
        "category": "Museum & Gallery",
        "rating": "★4.7",
        "locationZone": "city",
        "lat": 52.5065, "lng": 13.3838,
        "kids": False, "rain": True, "shopping": False, "free": True,
        "desc_en": "Free documentation center built on the former headquarters of the Gestapo and SS, detailing Nazi war crimes and state terror.",
        "desc_ja": "第二次大戦中のゲシュタポおよびSS（親衛隊）本部跡地にある歴史ドキュメンテーションセンター。ナチス恐怖政治の歴史を伝える重要な無料施設。",
        "desc_es": "Centro de documentación gratuito construido en la antigua sede de la Gestapo y las SS sobre los crímenes nazis.",
        "desc_zh": "建于盖世太保（Gestapo）与党卫军（SS）总部旧址的免费历史档案中心。严谨反思纳粹国家恐怖统治历史。",
        "tip_en": "🚶 Walk along the outer trench wall exhibition facing Niederkirchnerstraße—one of the longest preserved original sections of the Berlin Wall stands directly above!",
        "tip_ja": "🚶 屋内展示だけでなく、屋外の壕沿いにあるパネル展示と、その真上に残る柏林の壁（ベルリンの壁）の原形を合わせて見学するのがポイントです。",
        "tip_es": "🚶 Recorre la exposición al aire libre junto al foso para ver el tramo del Muro de Berlín que se conserva justo encima.",
        "tip_zh": "🚶 除了室内展厅，请务必漫步于壕沟外侧露天长廊展区，正上方即保留着长达数百米的柏林墙混凝土原貌。",
        "tip_fr": "🚶 Parcourez l'exposition extérieure le long de la tranchée pour voir le tronçon du Mur conservé juste au-dessus.",
        "tip_de": "🚶 Den Außenrundgang an der Grabenwand entlanggehen: Direkt darüber steht ein langes Originalstück der Berliner Mauer.",
        "price_en": "Free Entry", "price_ja": "入場無料", "price_es": "Entrada libre", "price_zh": "免费参观", "price_fr": "Gratuit", "price_de": "Kostenlos",
        "name_en": "Topography of Terror", "name_ja": "Topographie des Terrors（トポグラフィー・オブ・テラー）", "name_es": "Topografía del Terror", "name_zh": "恐怖地形图", "name_fr": "Topographie de la Terreur", "name_de": "Topographie des Terrors"
    },
    # 10. Holocaust-Mahnmal
    {
        "id": "b_10",
        "name": "Holocaust-Mahnmal（ホロコスト慰霊碑）",
        "category": "Landmark",
        "rating": "★4.7",
        "locationZone": "city",
        "lat": 52.5139, "lng": 13.3786,
        "kids": False, "rain": False, "shopping": False, "free": True,
        "desc_en": "Moving memorial consisting of 2,711 grey concrete stelae arranged in a grid pattern on a sloping field, with an underground Information Centre.",
        "desc_ja": "2,711基の灰色コンクリートの石柱（ステレ）が並ぶ傾斜地。地下には犠牲となったユダヤ人の手紙や写真を展示する地下情報センターを併設。",
        "desc_es": "Monumento formado por 2.711 estelas de hormigón gris con un Centro de Información subterráneo.",
        "desc_zh": "由2711块高低起伏的灰色混凝土柱巨阵构成的追思网格。地下设有展现受害者信件与照片地下信息中心。",
        "tip_en": "🧥 Respectful behavior is strictly required (no running, climbing, or jumping on stelae). Visit the underground Information Centre via the southeast corner stairs.",
        "tip_ja": "🧥 コンクリート柱の上に乗ったり跳び移る行為は厳禁！南東角の階段から地下の無料情報センター（Information Centre）へ入り、犠牲者の手紙や記録を静かに閲覧しましょう。",
        "tip_es": "🧥 ¡Está prohibido subirse o saltar entre las estelas! Visita el Centro de Información subterráneo por la esquina sureste.",
        "tip_zh": "🧥 庄重提示：严禁攀爬或在水泥柱间跳跃！请从东南角的阶梯下至地下免费信息中心，静心阅读历史文献。",
        "tip_fr": "🧥 Interdiction absolue de grimper sur les stèles ! Descendez au centre d'information souterrain par l'escalier sud-est.",
        "tip_de": "🧥 Das Besteigen und Springen auf den Stelen ist streng untersagt! Das kostenlose unterirdische Ort der Information besuchen.",
        "price_en": "Free Entry", "price_ja": "入場無料", "price_es": "Entrada libre", "price_zh": "免费参观", "price_fr": "Gratuit", "price_de": "Kostenlos",
        "name_en": "Memorial to the Murdered Jews of Europe", "name_ja": "Holocaust-Mahnmal（ホロコースト慰霊碑）", "name_es": "Memorial del Holocausto", "name_zh": "欧洲被害犹太人纪念碑", "name_fr": "Mémorial aux Juifs assassinés d'Europe", "name_de": "Holocaust-Mahnmal"
    },
    # 11. Berliner Fernsehturm
    {
        "id": "b_11",
        "name": "Berliner Fernsehturm（ベルリンテレビ塔）",
        "category": "Landmark",
        "rating": "★4.5",
        "locationZone": "city",
        "lat": 52.5208, "lng": 13.4094,
        "kids": True, "rain": True, "shopping": False, "free": False,
        "desc_en": "Germany's tallest structure (368m) built in 1969 with an observation deck at 203m and a 360° rotating sphere restaurant.",
        "desc_ja": "高さ368mを誇るドイツ最高の建造物。地上203mの展望台と、1時間に1回転する球形回転レストラン『Sphere』からベルリンを一望。",
        "desc_es": "La estructura más alta de Alemania (368m) con mirador a 203m y un restaurante giratorio.",
        "desc_zh": "高368米的德国第一高建筑。203米高处设有全景观景台与每小时旋转一周的“Sphere”球形旋转餐厅。",
        "tip_en": "🎟️ Fast-track time-slot ticket booked online is ESSENTIAL to skip the 2-hour queue for the high-speed elevator!",
        "tip_ja": "🎟️ 高速エレベーターの2時間待ち行列を回避するため、日時指定の『Fast Track Ticket』をネットで事前購入するのが鉄則です！",
        "tip_es": "🎟️ ¡Es IMPRESCINDIBLE comprar la entrada Fast View por internet para saltarte las 2 horas de cola del ascensor!",
        "tip_zh": "🎟️ 强烈建议提前在官网预订免排队定时票（Fast View Ticket）！否则现场等候高速电梯排队通常长达2小时。",
        "tip_fr": "🎟️ Réservation d'un billet coupe-file en ligne INDISPENSABLE pour éviter 2h de file d'attente à l'ascenseur !",
        "tip_de": "🎟️ Fast-View-Ticket unbedingt vorab online buchen, um bis zu 2 Stunden Wartezeit am Aufzug zu vermeiden!",
        "price_en": "Entry: €22.50", "price_ja": "入場料: 22.50ユーロ", "price_es": "Entrada: 22,50€", "price_zh": "门票：22.50 欧元", "price_fr": "Entrée : 22,50 €", "price_de": "Eintritt: 22,50 €",
        "name_en": "Berlin TV Tower", "name_ja": "Berliner Fernsehturm（ベルリンテレビ塔）", "name_es": "Torre de Televisión de Berlín", "name_zh": "柏林电视塔", "name_fr": "Tour de télévision de Berlin", "name_de": "Berliner Fernsehturm"
    },
    # 12. Schloss Charlottenburg
    {
        "id": "b_12",
        "name": "Schloss Charlottenburg（シャルロッテンブルク宮殿）",
        "category": "Landmark",
        "rating": "★4.7",
        "locationZone": "city",
        "lat": 52.5206, "lng": 13.2956,
        "kids": True, "rain": True, "shopping": False, "free": False,
        "desc_en": "Sumptuous 17th-century Baroque and Rococo royal palace of the Hohenzollern dynasty surrounded by expansive French and English gardens.",
        "desc_ja": "プロイセン王家ホーエンツォレルン家の本宮殿。豪華なバロック・ロココ調の室内、磁器の間、広大な宮殿庭園が広がる。",
        "desc_es": "Suntuoso palacio barroco y rococó del siglo XVII de la dinastía Hohenzollern con amplios jardines.",
        "desc_zh": "霍亨索伦皇室奢华的17世纪巴洛克与洛可可风格宫殿，拥有瓷器展厅与广阔的法式英式宫廷花园。",
        "tip_en": "📸 Stroll into the palace gardens for FREE behind the palace; walk around the lake to photograph the palace dome reflecting in the water.",
        "tip_ja": "📸 宮殿裏手の広大な庭園エリア（Schlossgarten）は入園無料！池の反対側へ回り込むと、水面にドーム屋根が映る絵はがき写真が撮れます。",
        "tip_es": "📸 El acceso al gran jardín trasero es GRATUITO. Camina alrededor del lago para fotografiar el palacio reflejado.",
        "tip_zh": "📸 宫殿后方的皇家公立花园完全免费开放！绕湖半周，可拍到浅翠绿宫殿穹顶倒映在湖面上的绝佳视角。",
        "tip_fr": "📸 L'accès aux grands jardins à l'arrière est GRATUIT. Faites le tour du lac pour photographier le château.",
        "tip_de": "📸 Der weitläufige Schlossgarten auf der Rückseite ist KOSTENLOS zugänglich. Spaziergang um den See machen!",
        "price_en": "Palace: €17 (Gardens Free)", "price_ja": "宮殿: 17ユーロ（庭園無料）", "price_es": "Palacio: 17€ (Jardines gratis)", "price_zh": "宫殿：17 欧元（花园免费）", "price_fr": "Palais : 17 € (Jardins gratuits)", "price_de": "Schloss: 17 € (Garten frei)",
        "name_en": "Charlottenburg Palace", "name_ja": "Schloss Charlottenburg（シャルロッテンブルク宮殿）", "name_es": "Palacio de Charlottenburg", "name_zh": "夏洛滕堡宫", "name_fr": "Château de Charlottenburg", "name_de": "Schloss Charlottenburg"
    },
    # 13. Jüdisches Museum Berlin
    {
        "id": "b_13",
        "name": "Jüdisches Museum Berlin（ユダヤ博物館）",
        "category": "Museum & Gallery",
        "rating": "★4.6",
        "locationZone": "city",
        "lat": 52.5023, "lng": 13.3949,
        "kids": True, "rain": True, "shopping": False, "free": True,
        "desc_en": "Architectural masterpiece by Daniel Libeskind with a zigzag shape, featuring the Holocaust Tower and interactive exhibits on German-Jewish history.",
        "desc_ja": "ダニエル・リベスキンド設計のジグザグ建築。ホロコーストの塔や『落ち葉（Shalechet）』の体験型アートで知られる博物館。",
        "desc_es": "Obra maestra arquitectónica de Daniel Libeskind con diseño en zigzag y la sobrecogedora Torre del Holocausto.",
        "desc_zh": "由 Daniel Libeskind 设计的解构主义锯齿状标志建筑，包含震撼人心的“大屠杀高塔”与“落叶”互动装置艺术。",
        "tip_en": "🎟️ Permanent exhibition entrance is 100% FREE! Step on Menashe Kadishman's 10,000 screaming metal face plates in the Memory Void.",
        "tip_ja": "🎟️ 常設展示は完全入場無料！空間芸術『記憶の真空（Memory Void）』で、1万個の叫ぶ金属顔プレートの上を歩く体験は鳥肌モノの衝撃です。",
        "tip_es": "🎟️ ¡La entrada a la exposición permanente es 100% GRATUITA! Camina sobre las 10.000 caras de metal en la sala Memory Void.",
        "tip_zh": "🎟️ 常设展完全免费！走入“记忆真空”（Memory Void）展厅，亲脚踩踏在10000块发出尖锐金属碰撞声的面具金属片之上，震撼人心。",
        "tip_fr": "🎟️ L'exposition permanente est 100% GRATUITE ! Marchez sur les 10 000 visages en métal dans l'espace Memory Void.",
        "tip_de": "🎟️ Die Dauerausstellung ist 100% KOSTENLOS! Das begehbare Kunstwerk 'Schalechet' (Memory Void) im Untergeschoss erleben.",
        "price_en": "Free (Permanent Exhibition)", "price_ja": "無料（常設展）", "price_es": "Gratis (Exposición permanente)", "price_zh": "免费（常设展）", "price_fr": "Gratuit (Expo permanente)", "price_de": "Kostenlos (Dauerausstellung)",
        "name_en": "Jewish Museum Berlin", "name_ja": "Jüdisches Museum Berlin（ユダヤ博物館）", "name_es": "Museo Judío de Berlín", "name_zh": "柏林犹太人博物馆", "name_fr": "Musée juif de Berlin", "name_de": "Jüdisches Museum Berlin"
    },
    # 14. DDR Museum
    {
        "id": "b_14",
        "name": "DDR Museum（DDR博物館）",
        "category": "Museum & Gallery",
        "rating": "★4.5",
        "locationZone": "city",
        "lat": 52.5197, "lng": 13.4026,
        "kids": True, "rain": True, "shopping": False, "free": False,
        "desc_en": "Interactive museum on the banks of the Spree recreating daily life in former East Germany (DDR) with a Trabant car simulator and furnished Plattenbau flat.",
        "desc_ja": "シュプレー川沿いにある体験型博物館。東ドイツ（DDR）時代の庶民の暮らし、車『トラバント』試乗、東独団地部屋をリアルに再現。",
        "desc_es": "Museo interactivo junto al río Spree que recrea la vida cotidiana en la antigua Alemania Oriental (RDA).",
        "desc_zh": "位于施普雷河畔的沉浸式体验馆。1:1还原旧东德（DDR）时期的居民生活，可坐进Trabant老卡车驾驶模拟器。",
        "tip_en": "🚪 Sit inside the authentic Trabant car simulator to drive through a East Berlin residential neighborhood, or open all the apartment drawers!",
        "tip_ja": "🚪 展示されている本物のトラバント（Trabant）の運転席に乗り込み、東ベルリンの街並みをバーチャル走行する体験が大人気！タンスや冷蔵庫の引き出しも開け放題です。",
        "tip_es": "🚪 ¡Siéntate al volante del simulador del coche Trabant original y abre todos los cajones del piso DDR recreado!",
        "tip_zh": "🚪 坐入真实的 Trabant 轿车驾驶舱体验东柏林虚拟驾车！展厅内所有旧公寓橱柜、冰箱门均可动手自由拉开探秘。",
        "tip_fr": "🚪 Asseyez-vous au volant du simulateur de la voiture Trabant et ouvrez les tiroirs de l'appartement témoin !",
        "tip_de": "🚪 Im Trabant-Fahrsimulator Platz nehmen und durch Ost-Berlin steuern. Alle Schubladen der Plattenbau-Wohnung aufmachen!",
        "price_en": "Entry: €12.50", "price_ja": "入場料: 12.50ユーロ", "price_es": "Entrada: 12,50€", "price_zh": "门票：12.50 欧元", "price_fr": "Entrée : 12,50 €", "price_de": "Eintritt: 12,50 €",
        "name_en": "DDR Museum", "name_ja": "DDR Museum（DDR博物館）", "name_es": "Museo de la RDA", "name_zh": "东德博物馆", "name_fr": "Musée de la RDA", "name_de": "DDR Museum"
    },
    # 15. Curry 36 & Konnopke's Imbiß
    {
        "id": "b_15",
        "name": "Curry 36 & Konnopke's Imbiß（カリー36＆コノプケ）",
        "category": "Café & Bistro",
        "rating": "★4.6",
        "locationZone": "city",
        "lat": 52.4896, "lng": 13.3877,
        "kids": True, "rain": False, "shopping": False, "free": False,
        "desc_en": "Berlin's two legendary street food counters serving iconic Currywurst (steamed pork sausage topped with curry ketchup & powder) with crispy fries.",
        "desc_ja": "ベルリンのソウルフード『カリーヴルスト（カレーパウダー掛けソーセージ）』の二大名店。皮あり（mit Darm）と皮なし（ohne Darm）を選べる。",
        "desc_es": "Los dos quioscos de comida callejera legendarios de Berlín que sirven la famosa Currywurst con patatas fritas.",
        "desc_zh": "柏林名吃“咖喱香肠”（Currywurst）两大传奇街头小吃档！提供肠衣（mit Darm）与无肠衣（ohne Darm）配薯条。",
        "tip_en": "🍽️ Order 'Currywurst ohne Darm mit Pommes Mayo' (skinless sausage with fries & mayo) at Curry 36 (Mehringdamm) or Konnopke's under Eberswalder Str. station!",
        "tip_ja": "🍽️ 注文は『Currywurst ohne Darm mit Pommes Mayo（皮なしカレーソーセージ＋フライドポテトのマヨネーズ添え）』が王道の注文方法です！",
        "tip_es": "🍽️ Pide 'Currywurst ohne Darm mit Pommes Mayo' (salchicha sin piel con patatas y mayonesa) en Curry 36.",
        "tip_zh": "🍽️ 标准地道点餐口令：“Currywurst ohne Darm mit Pommes Mayo”（无肠衣咖喱香肠配薯条蛋黄酱）！",
        "tip_fr": "🍽️ Commandez une 'Currywurst ohne Darm mit Pommes Mayo' (saucisse sans peau avec frites et mayonnaise) !",
        "tip_de": "🍽️ 'Currywurst ohne Darm mit Pommes Mayo' bestellen – der absolut echte Berliner Imbiss-Klassiker!",
        "price_en": "Dish: €4.50–€7", "price_ja": "単品: 4.50〜7ユーロ", "price_es": "Plato: 4,50€–7€", "price_zh": "小吃：4.50–7 欧元", "price_fr": "Plat : 4,50 €–7 €", "price_de": "Portion: 4,50 €–7 €",
        "name_en": "Curry 36 & Konnopke's", "name_ja": "Curry 36 & Konnopke's Imbiß（カリー36＆コノプケ）", "name_es": "Curry 36 y Konnopke's", "name_zh": "咖喱36与科诺普克小吃", "name_fr": "Curry 36 et Konnopke's", "name_de": "Curry 36 & Konnopke's Imbiß"
    },
    # 16. Mustafa's Gemüsedöner
    {
        "id": "b_17",
        "name": "Mustafa's Gemüsedöner（ムスタファズ・ゲミューゼドネル）",
        "category": "Café & Bistro",
        "rating": "★4.7",
        "locationZone": "city",
        "lat": 52.4897, "lng": 13.3875,
        "kids": True, "rain": False, "shopping": False, "free": False,
        "desc_en": "World-famous Kebab kiosk on Mehringdamm famed for grilled chicken, roasted vegetables, sheep's cheese, and fresh mint squeeze.",
        "desc_ja": "世界的に有名で常に行列ができるドネルケバブ店。香ばしいチキン、素揚げ野菜、フェタチーズ、レモンを搾った絶品ケバブ。",
        "desc_es": "Kiosco de kebab mundialmente famoso en Mehringdamm con pollo a la parrilla, verduras asadas y queso de oveja.",
        "desc_zh": "火爆全城的传奇土耳其烤肉摊。在香压大饼中夹入烤鸡肉、油炸时蔬、羊乳干酪与挤压鲜柠檬汁。",
        "tip_en": "⏰ Lines can take 45–90 minutes! Visit between 10:30 AM – 11:30 AM before the lunch rush, or late night after 11:00 PM.",
        "tip_ja": "⏰ 昼〜夕方は45分〜90分待ちの大行列！開店直後の午前10:30〜11:30、または深夜23:00以降を狙うと並び時間が激減します。",
        "tip_es": "⏰ ¡La cola puede durar de 45 a 90 minutos! Ven entre las 10:30 y 11:30 h antes de la hora del almuerzo.",
        "tip_zh": "⏰ 避开高峰排队！高峰期等候时长达45–90分钟，建议上午10:30–11:30开门或深夜23点后前往。",
        "tip_fr": "⏰ Attente de 45 à 90 min en journée ! Venez entre 10h30 et 11h30 avant la ruée du déjeuner.",
        "tip_de": "⏰ Wartezeiten von 45–90 Minuten sind üblich! Vormittags zwischen 10:30 und 11:30 Uhr kommen.",
        "price_en": "Döner: €7.10", "price_ja": "ケバブ: 7.10ユーロ", "price_es": "Kebab: 7,10€", "price_zh": "烤肉卷：7.10 欧元", "price_fr": "Kebab : 7,10 €", "price_de": "Döner: 7,10 €",
        "name_en": "Mustafa's Gemüse Kebab", "name_ja": "Mustafa's Gemüsedöner（ムスタファズ・ゲミューゼドネル）", "name_es": "Mustafa's Gemüse Kebab", "name_zh": "穆斯塔法烤肉摊", "name_fr": "Mustafa's Gemüse Kebab", "name_de": "Mustafa's Gemüsedöner"
    },
    # 17. Prater Biergarten
    {
        "id": "b_18",
        "name": "Prater Biergarten（プラーター・ビアガーデン）",
        "category": "Café & Bistro",
        "rating": "★4.6",
        "locationZone": "city",
        "lat": 52.5401, "lng": 13.4101,
        "kids": True, "rain": False, "shopping": False, "free": False,
        "desc_en": "Berlin's oldest outdoor beer garden operating since 1837 under chestnut trees in Prenzlauer Berg, serving cold Prater Pils and giant pretzels.",
        "desc_ja": "1837年創業のベルリン最古のビアガーデン。マロニエの大樹の木陰で自社醸造のPrater Pils生ビールとソーセージを楽しめる市民の憩い場。",
        "desc_es": "El jardín de cerveza al aire libre más antiguo de Berlín (1837) bajo castaños en Prenzlauer Berg.",
        "desc_zh": "始于1837年柏林最古老的露天啤酒花园。在栗树林荫下享用自酿 Prater Pils 生啤酒与现烤巨大普雷结。",
        "tip_en": "🧺 Self-service order counter at the back kiosk for Prater Pils beer and bratwurst; open daily from April through October from 12:00 PM.",
        "tip_ja": "🧺 4月〜10月限定営業。奥のセルフサービス売場でPrater Pils生ビールと熱々ブラートヴルスト（焼きソーセージ）を購入し木陰の空席へ！",
        "tip_es": "🧺 Compra la cerveza Prater Pils y bratwurst en el quiosco de autoservicio del fondo y busca mesa libre.",
        "tip_zh": "🧺 4月至10月开放。直接前往后方自助取餐档口购买自酿Prater Pils生啤酒与热烤香肠，随到随坐。",
        "tip_fr": "🧺 Commandez votre bière Prater Pils et bratwurst au comptoir en libre-service et trouvez una table.",
        "tip_de": "🧺 Selbstbedienung am Kiosk: Prater Pils und Bratwurst holen und unter den Kastanien Platz nehmen.",
        "price_en": "Beer: €4.80", "price_ja": "ビール: 4.80ユーロ", "price_es": "Cerveza: 4,80€", "price_zh": "啤酒：4.80 欧元", "price_fr": "Bière : 4,80 €", "price_de": "Bier: 4,80 €",
        "name_en": "Prater Beer Garden", "name_ja": "Prater Biergarten（プラーター・ビアガーデン）", "name_es": "Cervecería Prater", "name_zh": "普拉特啤酒花园", "name_fr": "Biergarten Prater", "name_de": "Prater Biergarten"
    },
    # 18. Schloss Sanssouci (Potsdam)
    {
        "id": "b_61",
        "name": "Schloss Sanssouci & Park (Potsdam / UNESCO)（サンスーシ宮殿）",
        "category": "Landmark",
        "rating": "★4.8",
        "locationZone": "suburban",
        "lat": 52.4042, "lng": 13.0385,
        "kids": True, "rain": True, "shopping": False, "free": False,
        "desc_en": "Frederick the Great's summer residence in Potsdam crowning terraced grape vineyards, UNESCO World Heritage masterpiece of Prussian Rococo.",
        "desc_ja": "フリードリヒ大王の夏の離宮（ポツダム）。ブドウの段々畑の頂に建つ黄色のロココ様式宮殿と広大な庭園（世界遺産）。",
        "desc_es": "Residencia de verano de Federico el Grande sobre terrazas de viñedos en Potsdam, obra maestra rococó UNESCO.",
        "desc_zh": "腓特烈大帝位于波茨坦的夏天避暑宫殿。矗立于梯田葡萄园顶端的黄色洛可可建筑与广袤皇家园林（UNESCO）。",
        "tip_en": "🎟️ Book fixed time-slot tickets online weeks in advance for interior tours (strictly limited capacity)! Strolling the terraced vineyard garden is free.",
        "tip_ja": "🎟️ 宮殿内見学（時間指定制）は入場人数が厳格に制限されているため、数週間前要Web予約！ブドウの段々畑や庭園自体の散策は無料です。",
        "tip_es": "🎟️ ¡Reserva las entradas con hora fija por internet con semanas de antelación! Pasear por los jardines es gratis.",
        "tip_zh": "🎟️ 宫殿内部参观入场名额限制极严，必须提前数周在官网预约定时门票！梯田葡萄园与外围皇家花园完全免费游览。",
        "tip_fr": "🎟️ Réservez vos billets à créneau horaire en ligne des semaines à l'avance ! L'accès aux jardins est libre.",
        "tip_de": "🎟️ Zeitfenster-Tickets für die Innenräume Wochen im Voraus online buchen! Der Park mit den Weinbergterrassen ist frei.",
        "price_en": "Palace: €14 (Park Free)", "price_ja": "宮殿: 14ユーロ（庭園無料）", "price_es": "Palacio: 14€ (Parque gratis)", "price_zh": "宫殿：14 欧元（公园免费）", "price_fr": "Palais : 14 € (Parc gratuit)", "price_de": "Schloss: 14 € (Park frei)",
        "name_en": "Sanssouci Palace", "name_ja": "Schloss Sanssouci & Park (Potsdam / UNESCO)（サンスーシ宮殿）", "name_es": "Palacio de Sanssouci", "name_zh": "无忧宫", "name_fr": "Palais de Sanssouci", "name_de": "Schloss Sanssouci"
    },
    # 19. Schloss Cecilienhof (Potsdam)
    {
        "id": "b_63",
        "name": "Schloss Cecilienhof (Potsdam)（ツェツィーリエンホーフ宮殿）",
        "category": "Landmark",
        "rating": "★4.6",
        "locationZone": "suburban",
        "lat": 52.4194, "lng": 13.0706,
        "kids": True, "rain": True, "shopping": False, "free": False,
        "desc_en": "English Tudor-style country house in Potsdam where Truman, Churchill, and Stalin held the historic 1945 Potsdam Conference.",
        "desc_ja": "1945年のポツダム会談（トルーマン、チャーチル、スターリン出席）の会場となった英国チューダー様式の歴史的宮殿。",
        "desc_es": "Palacio de estilo Tudor inglés en Potsdam donde Truman, Churchill y Stalin celebraron la Conferencia de Potsdam en 1945.",
        "desc_zh": "位于波茨坦的都铎风格英式乡村庄园。1945年杜鲁门、丘吉尔与斯大林在此签署确定二战后世界格局的《波茨坦协定》。",
        "tip_en": "📜 Walk inside the conference hall to view the actual round mahogany table where the Allied leaders redrew the postwar map of Europe.",
        "tip_ja": "📜 トルーマン、チャーチル、スターリンの3首脳が実際に着席した大きなマホガニー製の円卓が残る歴史的大会堂の内部見学がハイライトです。",
        "tip_es": "📜 Visita la sala de conferencias para ver la mesa redonda de caoba original donde los líderes aliados se reunieron en 1945.",
        "tip_zh": "📜 步入主会议大厅，亲眼目睹当年盟国三巨头开会签署协定的红木巨型圆桌陈列。",
        "tip_fr": "📜 Visitez la grande salle pour voir la table ronde en acajou d'origine où s'installèrent les dirigeants alliés.",
        "tip_de": "📜 Im Konferenzsaal den originalen runden Mahagonitisch besichtigen, an dem die Alliierten 1945 verhandelten.",
        "price_en": "Entry: €14", "price_ja": "入場料: 14ユーロ", "price_es": "Entrada: 14€", "price_zh": "门票：14 欧元", "price_fr": "Entrée : 14 €", "price_de": "Eintritt: 14 €",
        "name_en": "Cecilienhof Palace", "name_ja": "Schloss Cecilienhof (Potsdam)（ツェツィーリエンホーフ宮殿）", "name_es": "Palacio de Cecilienhof", "name_zh": "塞西琳霍夫宫", "name_fr": "Château de Cecilienhof", "name_de": "Schloss Cecilienhof"
    },
    # 20. Glienicker Brücke
    {
        "id": "b_66",
        "name": "Glienicker Brücke (Potsdam / Berlin)（グリーニケ橋）",
        "category": "Landmark",
        "rating": "★4.6",
        "locationZone": "suburban",
        "lat": 52.4131, "lng": 13.0903,
        "kids": True, "rain": False, "shopping": False, "free": True,
        "desc_en": "Historical iron bridge over the Havel connecting Berlin and Potsdam, famed as the 'Bridge of Spies' where US & USSR exchanged captured agents.",
        "desc_ja": "ハーフェル川に架かる歴史的鉄橋。冷戦期にアメリカとソ連が拘束した東西スパイの交換を行った『スパイの橋（Bridge of Spies）』。",
        "desc_es": "Puente de hierro sobre el río Havel famoso como el 'Puente de los Espías' donde EE. UU. y la URSS intercambiaban agentes.",
        "desc_zh": "横跨哈弗尔河的铸铁桥梁。冷战时期被称为“间谍之桥”（Bridge of Spies），美苏两国曾在此秘密交换被捕高级间谍。",
        "tip_en": "📸 Walk to the center line of the bridge to stand exactly where the border stripe separated West Berlin (US Sector) and East Germany!",
        "tip_ja": "📸 橋の中央部へ進むと、かつて西ベルリン（米軍管区）と東ドイツの国境線を分ていた錆色の鉄骨の色の境界ラインを自分の足で踏むことができます！",
        "tip_es": "📸 Camina hasta la línea central del puente para situarte justo sobre la antigua frontera entre Berlín Oeste y Alemania Oriental.",
        "tip_zh": "📸 走至铁桥正中央！脚下即是昔日划分西柏林（美军占领区）与东德的冷战真实国境分割分界线。",
        "tip_fr": "📸 Marchez au milieu du pont pour vous tenir exactement sur l'ancienne frontière entre Berlin-Ouest et la RDA.",
        "tip_de": "📸 Auf die Mitte der Brücke gehen, wo der Grenzstrich früher West-Berlin und die DDR trennte.",
        "price_en": "Free Access", "price_ja": "見学無料", "price_es": "Acceso libre", "price_zh": "免费参观", "price_fr": "Accès libre", "price_de": "Kostenlos",
        "name_en": "Glienicke Bridge", "name_ja": "Glienicker Brücke (Potsdam / Berlin)（グリーニケ橋）", "name_es": "Puente Glienicke", "name_zh": "格利尼克大桥", "name_fr": "Pont de Glienicke", "name_de": "Glienicker Brücke"
    },
    # 21. Spreewald (UNESCO)
    {
        "id": "b_69",
        "name": "Spreewald (Lübbenau / Lehde - UNESCO)（シュプレーヴァルト）",
        "category": "Scenery & Walk",
        "rating": "★4.8",
        "locationZone": "suburban",
        "lat": 51.8686, "lng": 13.9678,
        "kids": True, "rain": False, "shopping": False, "free": False,
        "desc_en": "UNESCO Biosphere Reserve 1 hour south of Berlin with 1,570km of navigable waterways, traditional Sorbian wooden punt boats, and famous pickles.",
        "desc_ja": "ベルリンから南へ1時間。網の目のように巡る1,570kmの水路と先住民族ソルブ人の文化が残る自然保護区（世界遺産）。名物のキュウリのピクルスが有名。",
        "desc_es": "Reserva de la biosfera UNESCO con 1.570 km de canales, barcas de madera tradicionales y famosos pepinillos.",
        "desc_zh": "距离柏林1小时车程的联合国教科文组织生物圈保护区。拥有1570公里的纵横水网、先民索布人木舟与著名的酸黄瓜（Gurke）。",
        "tip_en": "🚣 Take a 2-hour traditional wooden punt boat tour ('Kahnfahrt') from Lübbenau port, and sample flavored Spreewald pickles from wooden barrels at the market!",
        "tip_ja": "🚣 リュッベナウ港から船頭が棹を操る伝統木舟『カーンファート（Kahnfahrt）』の2時間クルーズに参加し、港の木樽で売られるガーリックや唐辛子味のピクルスを食べ比べ！",
        "tip_es": "🚣 Toma el paseo en barca de madera 'Kahnfahrt' de 2 horas desde Lübbenau y prueba los pepinillos en barriles de madera.",
        "tip_zh": "🚣 从 Lübbenau 码头乘坐船夫泛舟的传统木舟“Kahnfahrt”水上巡游，并在岸边水上木桶处品尝大蒜或辣椒味酸黄瓜！",
        "tip_fr": "🚣 Embarquez pour une balade de 2h en barque en bois 'Kahnfahrt' depuis Lübbenau et goûtez les célèbres cornichons !",
        "tip_de": "🚣 Eine 2-stündige Kahnfahrt ab dem Hafen Lübbenau machen und die Gewürzgurken aus den Holzfässern probieren!",
        "price_en": "Punt Cruise: €14–€18", "price_ja": "小舟クルーズ: 14〜18ユーロ", "price_es": "Paseo en barca: 14€–18€", "price_zh": "木舟游船：14–18 欧元", "price_fr": "Balade en barque : 14 €–18 €", "price_de": "Kahnfahrt: 14 €–18 €",
        "name_en": "Spreewald Biosphere", "name_ja": "Spreewald (Lübbenau / Lehde - UNESCO)（シュプレーヴァルト）", "name_es": "Reserva de Spreewald", "name_zh": "施普雷瓦尔德自然保护区", "name_fr": "Forêt de la Spree", "name_de": "Spreewald"
    },
    # 22. Tropical Islands Resort
    {
        "id": "b_70",
        "name": "Tropical Islands Resort (Krausnick)（トロピカル・アイランズ）",
        "category": "Kids & Family",
        "rating": "★4.6",
        "locationZone": "suburban",
        "lat": 52.0389, "lng": 13.7486,
        "kids": True, "rain": True, "shopping": False, "free": False,
        "desc_en": "World's largest free-standing hangar converted into a massive 26°C indoor tropical rainforest waterpark with white sand beaches and waterslides.",
        "desc_ja": "世界最大の巨大飛行船格納庫をドームリノベした全天候型トロピカルスパリゾート。26℃の室内熱帯雨林、白砂ビーチ、巨大スライダーを完備。",
        "desc_es": "El hangar independiente más grande del mundo convertido en un parque acuático tropical cubierto a 26°C con playa de arena.",
        "desc_zh": "由全球最大的独立飞行船机库改建而成的巨型全天候室内热带水上乐园。维持26°C恒温，拥有白沙滩与大型水上滑梯。",
        "tip_en": "👙 Open 24/7 year-round! Bring your own flip-flops and towels; book day tickets online in advance for weekend visits.",
        "tip_ja": "👙 365日24時間営業！バスタオルとビーチサンダルは持参必須。週末訪問は入場制限を避けるため公式サイトでの事前Web予約が安全です。",
        "tip_es": "👙 ¡Abierto 24/7 todo el año! Trae tus chanclas y toallas; reserva las entradas por internet el fin de semana.",
        "tip_zh": "👙 全年365天24小时不间断营业！请自备拖鞋与大浴巾，周末前往务必提前在官网网购门票。",
        "tip_fr": "👙 Ouvert 24h/24 et 7j/7 toute l'année ! Apportez vos claquettes et serviettes ; réservez en ligne pour le week-end.",
        "tip_de": "👙 Ganzjährig 24/7 geöffnet! Badetücher & Badelatschen mitbringen; Tagestickets am Wochenende online buchen.",
        "price_en": "Day Ticket: €47.90", "price_ja": "1日券: 47.90ユーロ", "price_es": "Entrada de día: 47,90€", "price_zh": "一日票：47.90 欧元", "price_fr": "Billet journée : 47,90 €", "price_de": "Tageskarte: 47,90 €",
        "name_en": "Tropical Islands", "name_ja": "Tropical Islands Resort (Krausnick)（トロピカル・アイランズ）", "name_es": "Tropical Islands Resort", "name_zh": "热带岛屿水上乐园", "name_fr": "Tropical Islands Resort", "name_de": "Tropical Islands Resort"
    }
]

# Write to data/cities/berlin.json
fpath = "data/cities/berlin.json"
data = {
    "cityName": "Berlin, Germany",
    "spots": berlin_spots
}

with open(fpath, 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print(f"🎉 Successfully created {len(berlin_spots)} spots in data/cities/berlin.json")
