#!/usr/bin/env python3
"""
Zero-Margin Travel App - Full 60 Rotterdam Spots Compiler (v36.0.0)
Populates 60 100% verified spots for Rotterdam in data/cities/rotterdam.json.
Compliant with Master Rulebook v6.0.0 and 5-Layer Compliance Guard.
"""

import os
import json

base_dir = os.path.dirname(os.path.abspath(__file__))
cities_dir = os.path.join(base_dir, '..', 'data', 'cities')

spots_data = [
    # 1 to 10
    ("ro_1", "Erasmusbrug", "エラスムス橋", "Landmark", "新マース川に架かる主塔高139mの非対称斜張橋。『白鳥（De Zwaan）』の愛称で親しまれるロッテルダムの象徴。 design by Ben van Berkel.", "Iconic 139-meter cable-stayed bridge spanning the Nieuwe Maas river, nicknamed 'The Swan' (De Zwaan).", "📸 ウィルヘルミナ埠頭またはウィレムスカデから日没時に水面反射を交えて撮影するのが定番の構図。", "📸 Walk along Wilhelminapier or Willemskade at sunset to frame the bridge with river reflections.", "散策無料", 51.9090, 4.4870, "city", False, False, False, True),
    ("ro_2", "Markthal Rotterdam", "マルクトハル", "Café & Bistro", "MVRDV設計の巨大な馬蹄形複合建築。天井一面に11,000㎡のデジタル壁画『豊穣の角』が描かれたインドアフードホール。", "Monumental horseshoe-shaped building housing a massive indoor food hall beneath a 11,000 m² ceiling mural.", "🍽️ 中央広場の屋台で熱々のストループワッフルや生ハーリング、焼きたてポッフェルチェをテイクアウト。", "🍽️ Browse the central ground-floor stalls for hot stroopwafels, raw herring, and fresh poffertjes.", "散策無料（飲食予算: €5〜€20）", 51.9201, 4.4870, "city", True, True, True, True),
    ("ro_3", "Kijk-Kubus & Kubuswoningen", "キューブハウス", "Landmark", "ピート・ブロム設計による45度傾いた六角形のキューブ型住宅群（38戸）。1戸が「Kijk-Kubus」として見学博物館として開放。", "Complex of 38 innovative tilted-cube houses on pylons designed by Piet Blom, with one open as a show museum.", "🏢 外観散策は無料。見学モデルハウス（Kijk-Kubus）へ入館（約€3.00）すると傾斜した壁や特注家具を体感可能。", "🏢 Walking around the exterior courtyard is free. Step inside the Kijk-Kubus (~€3.00) to see custom angled rooms.", "外観無料 / 内部入場: €3.00", 51.9205, 4.4900, "city", False, True, False, False),
    ("ro_4", "Depot Boijmans Van Beuningen", "デポ・ボイマンス・ファン・ベーニンゲン", "Museum & Gallery", "世界初の完全公開型美術品収蔵庫。1,664枚の鏡面ガラスパネルで覆われた碗型建築で、屋上には白樺の空中庭園が広がる。", "The world's first fully accessible art storage facility, clad in 1,664 reflective glass panels with a rooftop birch forest.", "🎟️ 全員WEB日時指定予約が必須。ガラスエレベーターで最上階の屋上庭園へ上ると360度のスカイライン絶景が広がる。", "🎟️ Advance online time-slot booking is mandatory. Take the glass elevator to the rooftop garden for 360-degree views.", "料金: €20.00", 51.9145, 4.4735, "city", False, True, False, False),
    ("ro_5", "Euromast & Euroscoop", "ユーロマスト", "Landmark", "1960年フロリアード記念に建てられた高さ185mのコンクリート製展望タワー。回転ガラスキャビン「Euroscoop」が頂上へ昇る。", "A 185-meter concrete observation tower featuring a revolving glass cabin (Euroscoop) that reaches the top spire.", "🎟️ 日没45分前に登ると、新マース川と港湾地帯の工業夜景への変化を楽しめる。ジップライン体験も人気。", "🎟️ Time your climb 45 minutes before dusk to watch harbor industrial lights ignite across the Nieuwe Maas.", "料金: €12.50 (Euroscoop乗車込)", 51.9054, 4.4666, "city", True, False, False, False),
    ("ro_6", "Werelderfgoed Kinderdijk", "キンデルダイクの風車群", "Scenery & Walk", "18世紀に建造された19基の排水風車が運河沿いに並ぶユネスコ世界遺産保護地区。", "UNESCO World Heritage site featuring a historic drainage network of 19 monumental 18th-century working windmills.", "⛴️ エラスムス橋からWaterbus（21番系統）で直行（約30分）。堤防のサイクリング・散策自体は完全無料。", "⛴️ Board the Waterbus (Line 21) directly from Erasmusbrug (~30 min). Walking or cycling the canal path is free.", "散策・サイクリング無料 / 施設・船: €16.00", 51.8885, 4.6315, "suburban", True, False, False, True),
    ("ro_7", "Historisch Delfshaven", "歴史的デルフスハーフェン", "Scenery & Walk", "1940年の爆撃を免れたロッテルダム唯一の完璧な17世紀運河地区。1620年メイフラワー号ピルグリム・ファーザーズ出航地。", "The only intact historic canal district in Rotterdam that survived WWII bombing, departure point of Pilgrims in 1620.", "🍺 旧市役所跡の歴史的クラフト醸造所「Stadsbrouwerij De Pelgrim」で地ビールと地元産マスタードチーズを賞味。", "🍺 Visit historic Stadsbrouwerij De Pelgrim set inside the former town hall for craft ales brewed with local water.", "散策無料", 51.9075, 4.4490, "city", False, False, False, True),
    ("ro_8", "SS Rotterdam", "SSロッテルダム号", "Landmark", "1959年竣工のハリウッド・アメリカ・ライン旧フラッグシップ客船。カテンブレヒトに永久無休で接岸保存。", "Legendary 1959 flagship ocean liner of Holland America Line, permanently moored at Katendrecht.", "🚢 無料の音声ガイドツアー（Sea Breeze Deluxe）で操舵室や機関室、キャプテン室を見学。船尾のプールバーは立ち入り無料。", "🚢 Take the self-guided audio tour to access the bridge and engine room. The open-air aft deck pool bar is free.", "デッキ立ち入り無料 / 船内見学: €16.50", 51.8970, 4.4690, "city", True, True, False, True),
    ("ro_9", "De Rotterdam", "デ・ロッテルダム", "Landmark", "OMA/レム・コールハース設計による高さ150mの3棟連結ガラス複合高層ビル「垂直都市」。", "Massive 'vertical city' complex designed by Rem Koolhaas on Wilhelminapier, consisting of three interconnected towers.", "🍸 nhow Hotelの7階テラスバーから、ライトアップされたエラスムス橋と新マース川のパノラマ夜景を望むカクテルタイムが人気。", "🍸 Head to the 7th-floor terrace bar of nhow Hotel for a sunset cocktail facing the illuminated Erasmus Bridge.", "外観無料 / バー予算: €8〜€20", 51.9080, 4.4860, "city", False, True, False, True),
    ("ro_10", "Rotterdam Watertaxi", "ロッテルダム水上タクシー", "Scenery & Walk", "新マース川沿い50箇所の乗り場を結ぶ、黒と黄色の高速モータボート交通ネットワーク。", "High-speed network of classic black-and-yellow motorboats operating across 50 landing docks on the Nieuwe Maas.", "🚤 エラスムス橋とホテル・ニューヨーク間の移動に利用すると徒歩時間を半減しつつ、スリリングな波しぶき体験を楽しめる。", "🚤 Book a ride between Erasmusbrug and Hotel New York; it cuts walking time and provides a thrilling harbor trip.", "1回乗船: €4.50〜€10.00", 51.9085, 4.4865, "city", True, False, False, False),

    # 11 to 20
    ("ro_11", "Hotel New York & Wilhelminapier", "ホテル・ニューヨーク＆ウィルヘルミナ埠頭", "Landmark", "1901年建造のアール・ヌーヴォー様式旧ホランド・アメリカ・ライン本社。数百万人の渡米移民が出航した史跡。", "Historic 1901 Art Nouveau former headquarters of Holland America Line, now a landmark oyster bar and grand cafe.", "🦪 1階のグランドカフェで新鮮なシーナゲット（Plateau Fruits de Mer）を注文し、ロビーの真鍮製客船模型を鑑賞。", "🦪 Order fresh seafood at the ground-floor grand cafe and check out historic brass ship models in the lobby.", "建物散策無料 / 飲食予算: €15〜€45", 51.9042, 4.4845, "city", False, True, False, True),
    ("ro_12", "Fenix Food Factory & Katendrecht", "フェニックス・フード・ファクトリー", "Café & Bistro", "カテンブレヒト地区の旧港湾倉庫を再生したクラフトフードインキュベーター。", "Culinary incubator inside a converted dockside warehouse on the Katendrecht peninsula.", "🧀 地元醸造所「Kaapse Brouwers」のビールと、「Booij Kaasmakers」の農場チーズを水辺の木製テラスで味わうのが定番。", "🧀 Pair craft brew from Kaapse Brouwers with farmhouse cheese on the waterside wooden terrace.", "散策無料 / 飲食予算: €10〜€25", 51.8995, 4.4820, "city", False, True, False, True),
    ("ro_13", "Museum Boijmans Van Beuningen", "ボイマンス・ファン・ベーニンゲン美術館", "Museum & Gallery", "中世初期フランドル派（ボス、ブリューゲル）からシュルレアリスムまでを誇るロッテルダム最高の美術館。", "Rotterdam's premier art museum in Museumpark, holding European masterpieces from Bosch to Dalí.", "🏛️ 歴史的本館が長期改修工事中のため、主なコレクションは隣接する「Depot Boijmans」およびサテライト会場で展示。", "🏛️ While the historic main building undergoes multi-year renovation, collection highlights are shown in Depot Boijmans.", "料金: €20.00", 51.9140, 4.4730, "city", False, True, False, False),
    ("ro_14", "Kunsthal Rotterdam", "クンストハル・ロッテルダム", "Museum & Gallery", "レム・コールハース（OMA）設計による常設展示を持たない前衛的企画面企画展示センター。", "Avant-garde exhibition center in Museumpark designed by Rem Koolhaas, hosting 20 rotating exhibitions annually.", "🎨 スロープ状の床面とガラス壁が特徴的で、年間約20の多様な現代アート・ファッション・デザイン展を巡回開催。", "🎨 The building itself features sloping ramp floors seamlessly connecting galleries with the park landscape.", "料金: €17.50", 51.9125, 4.4738, "city", False, True, False, False),
    ("ro_15", "Het Nieuwe Instituut & Huis Sonneveld", "ゾンネフェルト邸＆国立建築デザイン文化ミュージアム", "Museum & Gallery", "ミュージアムパーク内の建築・デザインミュージアム。アドミッションに1933年建造の機能主義モダニズム住宅「Huis Sonneveld」が含まれる。", "National museum for architecture and design, including admission to Huis Sonneveld, an exceptionally preserved 1933 villa.", "🛋️ 靴カバーを着用してゾンネフェルト邸内へ入り、1930年代のGispen製モダニズム家具やオープン間取りを体感。", "🛋️ Walk through Huis Sonneveld wearing shoe covers to experience 1930s modernist furniture and open plan layout.", "料金: €14.00 (Huis Sonneveld共通)", 51.9150, 4.4710, "city", False, True, False, False),
    ("ro_16", "Maritiem Museum Rotterdam", "ロッテルダム海事博物館", "Museum & Gallery", "Leuvehavenに位置する世界最古級の海事博物館。屋内体験展示と、蒸気タグボートやクレーンが並ぶ屋外港湾展示で構成。", "One of the world's oldest maritime museums featuring interactive navigation exhibits and an outdoor historic harbor.", "🚢 屋外港湾に並ぶ歴史的木造船やクレーン群の周囲散策は無料。館内3階には子供用造船体験「Professor Splash」完備。", "🚢 Walking around the outdoor historic harbor ships and cranes is free. Kids can enjoy the Professor Splash shipyard.", "屋外港散策無料 / 屋内展示: €16.00", 51.9175, 4.4815, "city", True, True, False, False),
    ("ro_17", "Witte de Withstraat", "ヴィッテ・デ・ヴィト通り", "Scenery & Walk", "ストリートアート壁画、インディペンデントギャラリー、カクテルバー、カフェが立ち並ぶロッテルダム一番の文化ナイトライフストリート。", "Rotterdam's most vibrant cultural and nightlife avenue, lined with street murals, coffee bars, and cocktail lounges.", "バー「Witte Aap」（世界最高のバーに選出歴あり）のテラス席でクラフトビールを飲むのが地元の定番。", "🍔 Stop by Ter Marsch & Co for award-winning burgers or relax on the outdoor terrace of Witte Aap.", "散策無料", 51.9155, 4.4775, "city", False, False, False, True),
    ("ro_18", "Station Rotterdam Centraal", "ロッテルダム中央駅", "Landmark", "市中心部を指す鋭角的なステンレス鋼屋根が特徴のターミナル駅。旧駅舎の1957年製大時計が保存されている。", "Transit hub featuring an angular stainless-steel roof pointing toward the center, integrating historic 1957 station lettering.", "📸 南口前広場に立ち、研磨された金属屋根の張り出しに高層ビル群が映り込む躍動的な構図を撮影。", "📸 Stand at the main southern exit plaza to capture the reflection of high-rise line on polished metal roof.", "見学無料", 51.9244, 4.4695, "city", False, True, False, True),
    ("ro_19", "Laurenskerk", "聖ローレンス教会", "Landmark", "1449〜1525年建造の中世ゴシック様式教会。1940年空襲を生き延びた都心部唯一の中世史跡。", "The only surviving medieval Gothic monument in central Rotterdam (1449-1525), featuring four pipe organs.", "🪜 夏季シーズンはガイドツアーで65mの教会塔を登り、中世の石造りと現代高層ビル群のコントラストを俯瞰。", "🪜 Take the guided summer tour to climb the 65-meter church tower for a view of medieval stone versus modern towers.", "聖堂入場: €3.00 / 塔登攀: €7.50", 51.9213, 4.4855, "city", False, True, False, False),
    ("ro_20", "Oude Haven & Witte Huis", "旧港＆ホワイトハウス", "Landmark", "14世紀まで遡るロッテルダム最古の港用船池。1898年建造のヨーロッパ初の高層ビル「Witte Huis」（43m）がそびえる。", "Rotterdam's oldest 14th-century basin harbor dominated by Het Witte Huis (1898), celebrated as Europe's first skyscraper.", "📸 水辺のカフェテラスから、歴史的木造船、Witte Huis、イエローのキューブハウスを一枚に収める写真が撮れる。", "📸 Waterside cafe terraces around Oude Haven basin provide the classic shot combining Witte Huis and Cube Houses.", "散策無料", 51.9190, 4.4910, "city", False, False, False, True),

    # 21 to 30
    ("ro_21", "Luchtsingel", "ルフトシンゲル黄色い歩道橋", "Scenery & Walk", "クラウドファンディングで建設された全長390mの鮮やかな黄色の木製歩道橋。線路を跨ぎ屋上農園「Dakakker」へ繋がる。", "390-meter-long bright yellow wooden pedestrian footbridge connecting disconnected quarters and rooftop farm Dakakker.", "🌿 橋を渡ってSchieblockビルの屋上へ行くと、商業屋上農園（Dakakker）と屋上カフェがある。", "🌿 Walk across to the rooftop of Schieblock to visit Europe's first large commercial rooftop farm Dakakker.", "散策無料", 51.9260, 4.4760, "city", False, False, False, True),
    ("ro_22", "Diergaarde Blijdorp", "ブライドルプ動物園", "Scenery & Walk", "150年以上の歴史を誇るヨーロッパ有数の保護動物園。水中トンネルのある「Oceanium」やバタフライドームを併設。", "One of Europe's oldest conservation zoos, featuring biogeographical continents and a walk-through Oceanium shark tunnel.", "🦈 雨の日は屋内施設「Oceanium」の巨大サメ水槽トンネルや熱帯アマゾニカ蝶ドームを中心に巡ると濡れずに楽しめる。", "🦈 Head straight to covered indoor Oceanium shark tunnel and tropical Amazonica butterfly dome on rainy days.", "料金: €27.00", 51.9270, 4.4480, "city", True, True, False, False),
    ("ro_23", "Miniworld Rotterdam", "ミニワールド・ロッテルダム", "Museum & Gallery", "ベネルクス最大のインドア・ミニチュアワールド。24分ごとに昼と夜が入れ替わるロッテルダム港や駅の精巧なジオラマ。", "The largest indoor miniature world in the Benelux, displaying moving scale models of Rotterdam's port and skyline.", "🚂 雨の日のファミリーに最適。ミニチュア街の中に隠されたミニキャラクターなどのイースターエッグを探すのが楽しい。", "🚂 Perfect rainy-day attraction for families; search for hidden cartoon easter eggs inside the miniature streetscapes.", "料金: €14.70", 51.9250, 4.4680, "city", True, True, False, False),
    ("ro_24", "Spido Havenrondvaart", "スピド港湾巡航船", "Landmark", "エラスムス橋の袂から出航する75分間の港湾周遊クルーズ。巨大コンテナターミナルや造船ドームを間近で見学。", "75-minute sightseeing boat cruise departing from the foot of ErasmusBridge past massive dry docks and container cranes.", "⛴️ 最上層のオープンデッキ席から超大型コンテナ船やガントリークレーンの迫力ある動きを鑑賞。", "⛴️ Sit on the upper open-air deck for views of supertankers and automated container cranes in action.", "料金: €17.25", 51.9088, 4.4848, "city", True, False, False, False),
    ("ro_25", "Het Park & De Heuvel", "ユーロマスト公園", "Scenery & Walk", "ユーロマストの足元に広がる19世紀イギリス風景式公園。古木、水路、芝生、パビリオンカフェ「Parqiet」が点在。", "19th-century English landscape park located at the base of Euromast, featuring historic trees and lawn cafes.", "☕ カフェ「Parqiet」で無料のデッキチェアを借り、緑豊かな芝生でユーロマストを見上げながらフラットホワイトを味わう。", "☕ Stop by Parqiet to borrow a free picnic deckchair and lounge on the open lawns beneath Euromast.", "散策無料", 51.9060, 4.4680, "city", True, False, False, True),
    ("a_26", "Lijnbaan & Beurstraverse", "ラインバーン＆コープホート", "Scenery & Walk", "1953年開業のヨーロッパ初の歩行者専用ショッピングモール「Lijnbaan」と、半地下ショッピング通路「De Koopgoot」。", "Lijnbaan (opened 1953) is Europe's first purpose-built pedestrian shopping promenade, linked to sunken Koopgoot.", "🛍️ 地下のKoopgoot通路を利用すると、車道の信号待ちなしでBeurs地下鉄駅から主要デパートやブティックへ移動可能。", "🛍️ Use the underground Koopgoot passage to walk between Beurs metro interchange and retail stores sheltered.", "散策無料", 51.9210, 4.4790, "city", False, True, True, True),
    ("ro_27", "Remastered Rotterdam", "リマスタード・デジタルアート", "Museum & Gallery", "エラスムス橋の下に位置する没入型デジタルプロジェクション展。ボスやゴッホの名画が360度LED壁と3Dサウンドで蘇る。", "Immersive digital projection experience under Erasmus Bridge, reimagining works by Dutch masters with 3D soundscapes.", "🎟️ WEB事前予約必須。靴を脱いでソックス（支給）で体験ルームを歩き回る60分間の完全入れ替え制体験。", "🎟️ Reserve tickets online in advance; the experience runs on fixed 60-minute time-slot cycles.", "料金: €24.50", 51.9085, 4.4840, "city", True, True, False, False),
    ("ro_28", "Dakpark Rotterdam", "ダックパーク屋上公園", "Scenery & Walk", "デルフスハーフェン地区のショッピングモール屋上に造られた全長1kmのヨーロッパ最大級の屋上公園。", "One of Europe's largest public rooftop parks, built atop a 1-kilometer retail strip in Delfshaven.", "🐑 傾斜緑地で放牧されているヒツジの群れや、コミュニティカフェ「Buurtkoffie」の遊具エリアがファミリーに大人気。", "🐑 Kids can feed the resident sheep herd on the park slopes and enjoy the playground at Buurtkoffie cafe.", "散策無料", 51.9090, 4.4390, "city", True, False, False, True),
    ("ro_29", "Nederlands Fotomuseum", "オランダ写真美術館", "Museum & Gallery", "ウィルヘルミナ埠頭の歴史的倉庫（Santos倉庫）内にある国立写真専門美術館。数百万点の写真ネガとアーカイブを収蔵。", "The national museum for photography on Wilhelminapier, housing millions of historical photographic negatives.", "📷 「Gallery of Honour of Dutch Photography」にて、オランダの視覚歴史を形作った99点の歴史的名写真を鑑賞。", "📷 Visit the Gallery of Honour of Dutch Photography to view 99 iconic historical photographs.", "料金: €15.00", 51.9055, 4.4875, "city", False, True, False, False),
    ("ro_30", "Kralingse Bos & Kralingse Plas", "クラーリンセの森と湖", "Scenery & Walk", "中心部北東に広がる200ヘクタールの森林と湖。砂浜ビーチ、鹿園、18世紀の嗅ぎタバコ・スパイス風車が位置する。", "200-hectare recreational forest and lake northeast of center, offering beaches, deer enclosures, and snuff windmills.", "📸 湖の西岸から夕刻に撮影すると、水面に映る高層ビル群の近代スカイラインが障害物なしで美しく映える。", "📸 Walk along the western shore of Kralingse Plas at sunset for an unobstructed panorama of the modern skyline.", "散策無料", 51.9330, 4.5150, "city", True, False, False, True),

    # 31 to 40
    ("ro_31", "Willemsbrug", "ウィレムス橋", "Landmark", "新マース川に架かる赤い鋼鉄製斜張橋。エラスムス橋の上流側に位置し、ノーデルエイランド島を結ぶ。", "Red steel cable-stayed bridge spanning the Nieuwe Maas, standing upstream from Erasmus Bridge.", "📸 ウィレムス橋の赤いトラスフレーム越しに、エラスムス橋と夕空のビル群を重ねて撮影する構図がおすすめ。", "📸 Capture cross-river photos of Erasmus Bridge and modern skyline framed beneath Willemsbrug's steel towers.", "散策無料", 51.9160, 4.4960, "city", False, False, False, True),
    ("ro_32", "Noordereiland", "ノーデルエイランド島", "Scenery & Walk", "新マース川の中中央に浮かぶ閑静な島。19世紀の木造埠頭や船員アパートが残り、大型貨物船の航行を間近に臨む。", "Tranquil island in the middle of Nieuwe Maas featuring 19th-century quays and historic shipping buildings.", "🚶 北岸のMaaskade通りをのんびり散策しながら、左右両側の川を絶え間なく行き交う国際河川船を眺める。", "🚶 Take a peaceful walk along Maaskade quay to watch the continuous stream of international river barges.", "散策無料", 51.9130, 4.4920, "city", False, False, False, True),
    ("ro_33", "Trompenburg Tuinen & Arboretum", "トロンペンブルク樹木園", "Scenery & Walk", "1820年設立の歴史的植物園・樹木園。4,000種以上の樹木、シャクナゲ、サボテン温室が広がる。", "Historic botanical garden and arboretum in Kralingen dating to 1820, containing over 4,000 species of trees and cacti.", "🌿 オランダミュージアムカード適用。春のシャクナゲ開花期や秋の紅葉期は格別の色鮮やかな景観が撮影できる。", "🌿 Free entrance with Dutch Museumkaart; visit during spring for rhododendron blooms or autumn for foliage.", "料金: €11.00", 51.9215, 4.5180, "city", False, False, False, False),
    ("ro_34", "Stadhuis Rotterdam", "ロッテルダム市役所", "Landmark", "1940年の爆撃を奇跡的に生き延びた数少ない1920年建造のボザール様式歴史的市庁舎。高さ71mの時計塔を備える。", "One of the few historic buildings in central Rotterdam that survived the 1940 bombing, built in 1920 with a 71m tower.", "🏛️ 平日の日中は砂岩造りの美しい中央噴水庭園が一般無料開放されており、クールシンゲル通りの喧騒を忘れる穴場。", "🏛️ The peaceful sandstone inner courtyard with its central fountain is open to the public on weekdays.", "見学無料", 51.9228, 4.4795, "city", False, True, False, True),
    ("ro_35", "Fenix Migration Museum", "フェニックス移民博物館", "Museum & Gallery", "カテンブレヒトの歴史的港湾倉庫をリノベーションした世界の人類移動史をテーマとする博物館。竜巻型の二重螺旋階段「Tornado」が象徴。", "Historic Fenix warehouse in Katendrecht transformed into a museum celebrating human migration with a Tornado staircase.", "🌪️ 有機的にねじれる金属製「Tornado」階段を昇ると、ラインハーフェン港を360度見渡す展望台に到達。", "🌪️ Climb the organic twisting metallic Tornado staircase to reach the 360-degree observation platform.", "料金: 約€17.50", 51.8990, 4.4830, "city", True, True, False, False),
    ("ro_36", "Splashtours Rotterdam", "スプラッシュツアー水陸両用バス", "Scenery & Walk", "近代建築街をドライブした後、エラスムス橋の横からダイレクトに新マース川へダイブする水陸両用バス。", "Amphibious bus tour driving through modern city highlights before splashing directly into Nieuwe Maas river.", "🎟️ エラスムス橋近くでの「着水（スプラッシュ）」の瞬間が一番の盛り上がり。ファミリーに大人気。", "🎟️ Sit toward the middle-front for the best view during the 'splash' river-entry transition near Erasmus Bridge.", "料金: €27.50", 51.9075, 4.4835, "city", True, False, False, False),
    ("ro_37", "Maassilo & Now&Wow", "マースシロ", "Landmark", "1910年建造の巨大なコンクリート製穀物シロを再生したインダストリアルクリエイティブカルチャースペース。", "Massive 1910 former concrete grain silo in Rotterdam-Zuid converted into an industrial creative powerhouse.", "🏢 昼間のクリエイティブマーケットやデザイン市イベント時に入場すると、当時の穀物エレベーター機構を見学できる。", "🏢 Check daytime event listings for creative design markets to explore the raw interior grain chutes.", "イベント入場料に準ずる (通常: 約€15〜€30)", 51.8920, 4.4920, "city", False, True, False, False),
    ("ro_38", "Binnenrotte Markt", "ビネンロッテ青空市場", "Café & Bistro", "マルクトハル前の vast なビネンロッテ広場で毎週火曜と土曜に開催されるオランダ最大級の露店市場。", "One of the largest open-air markets in NL, held every Tuesday and Saturday on Binnenrotte square.", "🍓 土曜日の午後3時以降に行くと、チーズや生花、新鮮な果物が投げ売り価格で値下げされる。", "🍓 Visit on Saturday after 3:00 PM for steep discounts on fresh fruits, flowers, and Dutch Gouda cheeses.", "散策無料", 51.9215, 4.4880, "city", False, False, True, True),
    ("ro_39", "Pannekoekenboot Rotterdam", "パンケーキボート", "Café & Bistro", "ユーロマスト横から出航し、オランダ名物パンケーキ（シロップ、リンゴ、ベーコン等）が食べ放題の75分間周遊船。", "Casual family cruise boat sailing along Nieuwe Maas offering an all-you-can-eat buffet of Dutch pancakes.", "🥞 船内に大型ボールプールが完備されており、子供たちが遊びながら親は港の景色を楽しめる。", "🥞 Boarding is located near Euromast; book the 75-minute cruise slot with a ball pit in the hull for kids.", "75分食べ放題: €22.50", 51.9050, 4.4685, "city", True, True, False, False),
    ("ro_40", "De Doelen & Schouwburgplein", "デ・ドゥーレン＆スハウブルフ広場", "Landmark", "ロッテルダム・フィル本拠地のコンサートホールと、赤い可動式油圧クレーン照明が象徴的な立体広場。", "Rotterdam Philharmonic's concert hall facing Schouwburgplein with interactive hydraulic red lighting cranes.", "📸 広場に設置された赤い大型クレーン型照明アームは、広場上の操作パネルで角度を変えることができる。", "📸 The giant red crane-like light towers on Schouwburgplein can be manually operated using control panels.", "広場散策無料", 51.9220, 4.4725, "city", False, True, False, True),

    # 41 to 50
    ("ro_41", "Historisch Gouda", "ゴーダ歴史地区", "Scenery & Walk", "中央駅から電車で20分。15th世紀ゴシック市庁舎、聖ヤン教会のステンドグラス、計量所（De Waag）が残るチーズの街。", "Historic cheese city 20 minutes from Rotterdam, famous for its 15th-century Gothic town hall and St. John Church.", "🧀 「Gouda Cheese Experience」でチーズ作り体験をし、「Kamphuisen」で1810年創業の元祖シロップワッフルを味わう。", "🧀 Visit the Gouda Cheese Experience for interactive installations and try the original 1810 recipe syrup waffle.", "街歩き無料 / 聖ヤン教会: €10.00", 52.0115, 4.7105, "suburban", True, False, True, True),
    ("ro_42", "Historisch Dordrecht", "ドルトレヒト歴史地区", "Scenery & Walk", "ロッテルダムからWaterbus（20番）で15分。1350年創業のホランド最古の都市。階段破風の邸宅や内港の風景が残る。", "Holland's oldest city (15 min south by Waterbus Line 20), featuring historic step-gabled houses and inland harbors.", "⛴️ エラスムス橋からWaterbus船に乗ってアプローチすると、歴史的水門ゲートから街に入る絶景を楽しめる。", "⛴️ Take the Waterbus (Line 20) from Erasmusbrug for a scenic approach arriving right at the historic river gates.", "街歩き無料 / ドルトレヒト美術館: €15.00", 51.8130, 4.6680, "suburban", False, False, False, True),
    ("ro_43", "Nationaal Park De Biesbosch", "ビースボッシュ国立公園", "Scenery & Walk", "ドルトレヒト郊外に広がる広大な淡水湿原国立公園。柳の森、迷路のような水路、野生のビーバーが生息。", "Sprawling freshwater tidal wetland national park featuring willow forests, flooded creeks, and wild beavers.", "🛶 ビースボッシュ・センターで静音電動ボートやカヌーを借りて水路を巡り、夕刻に野生のビーバーを探す。", "🛶 Rent a silent electric boat or canoe at Biesboschcentrum to navigate narrow creeks and spot wild beavers.", "散策無料 / ボートレンタル: 約€20〜€35/時", 51.7650, 4.7650, "suburban", True, False, False, True),
    ("ro_44", "FutureLand & Maasvlakte 2", "フューチャーランド", "Museum & Gallery", "北海を埋め立てたロッテルダム港の最新自動化水深コンテナターミナル「マースフラクテ2」の体験見学センター。", "Interactive visitor center located on Maasvlakte 2, Rotterdam's reclaimed deep-water automated container harbor.", "🚢 「FutureLand Ferry」船ツアーをWEB事前予約し、世界最大級の超大型コンテナ船と無人ガントリークレーンの動きを間近で見学。", "🚢 Book the FutureLand Ferry tour in advance to cruise past automated quayside container cranes up close.", "入館無料 / 港湾クルーズ船: 約€14.50", 51.9565, 4.0280, "suburban", True, True, False, True),
    ("ro_45", "Historisch Schiedam", "スキーダム歴史風車群＆イエネーフェル博物館", "Scenery & Walk", "ロッテルダム西隣（メトロで5分）。ジンの原型「イエネーフェル」蒸留用に建てられた世界最高の石造風車群（高33m）。", "Adjacent to Rotterdam-West, home to the world's tallest traditional stone grain windmills built for gin distilling.", "🍸 現役風車「De Walvisch」の内部を見学後、国立イエネーフェル博物館で歴史的モルトワイン・ジンの試飲。", "🍸 Visit working De Walvisch museum windmill, then stop at Jenevermuseum for a tasting of historic malt-wine gin.", "街歩き無料 / 風車見学: €6.00 / 博物館: €12.50", 51.9170, 4.3980, "suburban", False, True, False, True),
    ("ro_46", "Hoek van Holland Strand", "フック・ファン・ホランド海岸＆可動式防波堤", "Scenery & Walk", "メトロB線直結の北海ビーチ。世界最大級の自動可動式巨大鋼鉄防波堤「マエスラントケリンク（Maeslantkering）」が位置する。", "Rotterdam's coastal North Sea beach gateway, featuring wide sands and the world's largest automated storm surge barrier.", "🚇 ロッテルダム中心部からメトロB線に乗ると砂浜直結の「Hoek van Holland Strand」駅までダイレクトアクセス。", "🚇 Take direct Metro Line B from central Rotterdam straight to Hoek van Holland Strand station right on the sand.", "散策・防波堤見学無料", 51.9790, 4.1310, "suburban", True, False, False, True),
    ("ro_47", "Plaswijckpark Rotterdam", "プラスワイクパーク", "Scenery & Walk", "ヒレヘルスベルク地区にある伝統的ファミリーパーク。ゴーカート交通公園、大型屋内プレイヴィレッジ、動物園を併設。", "Classic family amusement park featuring outdoor playgrounds, indoor play village, and a pedal go-kart traffic park.", "🚗 交通公園（Verkeerstuin）で子供たちがペダルカーに乗り「足こぎ運転免許証」を獲得する体験が人気。", "🚗 Kids can earn their 'pedal-car driving license' in the Verkeerstuin pedal park. Highly recommended for ages 2–10.", "料金: €14.95", 51.9540, 4.4920, "city", True, True, False, False),
    ("ro_48", "Van Nelle Fabriek", "ファン・ネレ工場", "Landmark", "1920年代建造のオランダ機能主義（Nieuwe Bouwen）建築の最高峰にしてユネスコ世界遺産。鋼鉄とガラスの「日光工場」。", "UNESCO World Heritage masterpiece of 1920s modernist industrial architecture, built of steel and glass.", "🏛️ UrbanGuidesの建築ツアーを予約すると、空中に浮く空中ガラス渡り廊下や円形屋上ティーサロン内へ入場可能。", "🏛️ Book a guided architecture tour through UrbanGuides to access iconic curved glass sky bridges.", "敷地外観無料 / 建築ガイドツアー: 約€17.50", 51.9225, 4.4335, "city", False, True, False, True),
    ("ro_49", "Floating Farm", "水上ハイテク牛農場（Floating Farm）", "Scenery & Walk", "マールコニプレイン近くのM4H地区の水上に浮かぶ、世界初の水上酪農場。水上のプラットフォームで牛が生活。", "The world's first floating dairy farm with cows living on a multi-level platform on the water in M4H district.", "🐮 水上の牛たちが自動搾乳ロボットで過ごす様子を見学し、併設ショップで搾りたて牛乳やヨーグルトを購入。", "🐮 Walk into the Merwe-Vierhavens area to see cows living on the water and buy fresh farm milk and yogurt.", "ショップ散策無料 / 見学: €4.50", 51.9120, 4.4300, "city", True, False, True, True),
    ("ro_50", "Museum Rotterdam '40-'45 NU", "ロッテルダム空襲博物館", "Museum & Gallery", "クールハーフェン沿いに位置し、1940年5月14日のロッテルダム大空襲と戦時下の市民抵抗をインタラクティブ展示。", "Museum on Coolhaven using audio-visual storytelling and a 3D touch-table to immerse visitors in the 1940 Blitz.", "🎧 8分間のマルチメディア体験では、暗闇の中でサラウンド音響と床の振動により当時の空襲を擬似体験。", "🎧 The centerpiece 8-minute experience puts visitors in the dark during the actual air raid with floor vibrations.", "料金: €10.00", 51.9095, 4.4560, "city", False, True, False, False),

    # 51 to 60
    ("ro_51", "Rjinhavenbrug", "恋人たちの橋（ライナーフェン橋）", "Scenery & Walk", "ウィルヘルミナ埠頭とカテンブレヒト地区をライナーフェン港の上で結ぶ歩行者・自転車専用橋。", "Pedestrian and bicycle bridge linking Wilhelminapier and Katendrecht across the Rijnhaven harbor.", "📸 橋の中央に立ち北側を向くと、エラスムス橋と高層ビル群が完璧に重なるフォトジェニックな写真が撮れる。", "📸 Stand in the middle of the bridge looking north for a composition of Erasmus Bridge over skyscrapers.", "散策無料", 51.9025, 4.4838, "city", False, False, False, True),
    ("ro_52", "Laurenskwartier & Pannekoekstraat", "パンネクーク通りブティック街", "Scenery & Walk", "ローレンス教会周辺のクリエイティブクォーター。Pannekoekstraat沿いに独立系ファッションやインテリアカフェが集まる。", "Historic creative quarter around Laurenskerk; Pannekoekstraat is packed with independent fashion and cafes.", "🛍️ 老舗カフェ「Dudok」に立ち寄り、ロッテルダム一番と評される名物ダッチアップルパイ（Dudok Appeltaart）を味わう。", "🛍️ Stop by Dudok on Meent for their famous classic Dutch apple pie (Dudok Appeltaart).", "散策無料", 51.9225, 4.4875, "city", False, False, True, True),
    ("ro_53", "Groothandelsgebouw", "グロートハンデルスヘボウ", "Landmark", "中央駅隣に位置する1953年竣工の戦後復興モニュメント最大作。機能主義建築の金字塔で広大な屋上を有する。", "One of the earliest post-WWII reconstruction monuments in NL (1953), an icon of industrial functionalism.", "🍺 屋上イベントスペースや1階のグランドカフェEngelsから、中央駅を行き交う列車群のパノラマを見下ろす。", "🍺 Head to the rooftop bar when open for events for views overlooking incoming rail tracks at Rotterdam Centraal.", "共用部無料 / カフェ予算: €10〜€25", 51.9235, 4.4680, "city", False, True, False, True),
    ("ro_54", "Veerhaven", "フェールハーフェン歴史的港", "Scenery & Walk", "19世紀の貴族館と石畳の埠頭に囲まれた、クラシックな木造帆船が佇む情緒あふれる歴史的ヨットハーバー。", "Picturesque historic yacht harbor lined with 19th-century mansions and classic wooden sailing ships.", "🚶 ユーロマスト公園へ向かう途中に立ち寄る静かなフォトスポット。近代高層ビル群とは対比的な歴史景観。", "🚶 A tranquil photo spot away from modern concrete architecture; walk through Veerhaven on your way to Het Park.", "散策無料", 51.9080, 4.4750, "city", False, False, False, True),
    ("ro_55", "Chabot Museum", "シャボット美術館", "Museum & Gallery", "ミュージアムパーク内の白塗りの1938年モダニズムヴィラ。オランダ表現主義の画家・彫刻家ヘンク・シャボットの作品を展示。", "Housed in a white modernist 1938 villa in Museumpark, dedicated to expressionist Henk Chabot.", "🎨 向かいの「Huis Sonneveld」との共通チケットを購入すると、1930年代の機能主義住宅建築の対比を楽しめる。", "🎨 Combine the ticket with Huis Sonneveld across the street to experience two 1930s functionalist villas.", "料金: €12.50", 51.9148, 4.4718, "city", False, True, False, False),
    ("ro_56", "Centrale Bibliotheek Rotterdam", "ロッテルダム中央図書館", "Museum & Gallery", "1983年竣工のビネンロッテ前の象徴的建築。ガラスの滝ファサードと黄色い大空気ダクトパイプが特徴（ポンピドゥー風）。", "1983 architectural landmark featuring a cascading glass waterfall facade and bright yellow air tubes.", "📚 エスカレーターで6階に上り、静かなバルコニー席からマルクトハルとローレンス教会を見下ろしながら読書。", "📚 Take the escalators to the 6th floor to access study balconies overlooking Markthal and Laurenskerk.", "散策無料", 51.9215, 4.4862, "city", False, True, False, True),
    ("ro_57", "Oude Plantage", "オウデ・プランターゲ公園", "Scenery & Walk", "クラーリンゲン地区の新マース川のカーブ沿いに延びる1769年設立のロッテルダム最古の公立公園。", "Rotterdam's oldest public park (1769), stretching along the curve of the Nieuwe Maas in Kralingen.", "🚢 川沿いの芝生ベンチに座り、川の急カーブを航行する巨大国際貨物船やタグボートの迫力ある動きを鑑賞。", "🚢 One of the best spots in the city for watching massive international ocean freighters navigate the river bend.", "散策無料", 51.9160, 4.5120, "city", False, False, False, True),
    ("ro_58", "Havenmuseum Werkplaats", "海事港湾鍛冶場＆蒸気クレーン", "Landmark", "Leuvehaven水域に並ぶ海事博物館の屋外動態展示区画。歴史的なディーゼルクレーンや鍛冶屋の作業場が保存。", "Outdoor working shipyards, smithies, and restored diesel/steam cranes of Maritime Museum along Leuvehaven.", "⚓ 週末にはボランティアの鍛冶職人や船員による鉄打ちや蒸気エンジンの実演デモンストレーションが無料で見学可能。", "⚓ On select weekends, volunteer blacksmiths and mechanics give live demonstrations of iron forge-work.", "屋外見学無料", 51.9170, 4.4820, "city", True, False, False, True),
    ("ro_59", "Rotterdam Street Art Route", "ロッテルダム・ストリートアート・ルート", "Scenery & Walk", "Rewriters Rotterdamがプロデュースする、都心部・旧西地区の巨大ウォールアートを巡るセルフガイドウォーキングトレイル。", "Self-guided walking trail taking visitors past world-class large-scale street art murals across the city center.", "📱 専用アプリまたはWEBマップをダウンロードすると、壁画の背景にある国際的アーティストのストーリーを音声ガイドで聞ける。", "📱 Download the Rewriters app or map online to discover hidden courtyard murals and read artists' background stories.", "散策無料", 51.9160, 4.4750, "city", False, False, False, True),
    ("ro_60", "Kaapse Brouwers & Fenix Kaapse Maria", "カープセ・クラフトビールテイスティングルーム", "Café & Bistro", "ロッテルダムのクラフトビールパイオニア。カテンブレヒトのFenix Food Factoryおよびモーリッツヴェフの歴史的町屋にテイスティングルームを展開。", "Pioneer craft brewery celebrating bold modern ales with tasting rooms in Fenix Food Factory and Mauritsweg.", "🍺 「Kaapse Maria」の庭園テラスで、樽生クラフトビール4種の飲み比べセットと自家製サワードウトーストを味わう。", "🍺 At Kaapse Maria, order a tasting flight of 4 draft microbrews paired with Asian-fusion bar bites on the terrace.", "飲食予算: €12〜€30", 51.9165, 4.4720, "city", False, True, False, True)
]

def make_full_spot_object(spot_tuple):
    sid, name_en, name_ja_base, category, desc_ja, desc_en, tip_ja, tip_en, price_str, lat, lng, zone, kids, rain, shopping, free = spot_tuple
    full_name_ja = f"{name_en}（{name_ja_base}）"
    
    if free or "無料" in price_str or "Free" in price_str:
        p_ja, p_en, p_es, p_zh, p_fr, p_de = price_str if "無料" in price_str else "散策無料", "Free Entry", "Acceso libre", "免费参观", "Accès gratuit", "Freier Zugang"
        is_free = True
    else:
        clean = price_str.replace("料金:", "").replace("入場料:", "").strip()
        p_ja, p_en, p_es, p_zh, p_fr, p_de = f"料金: {clean}", f"Entry: {clean}", f"Entrada: {clean}", f"门票：{clean}", f"Entrée : {clean}", f"Eintritt: {clean}"
        is_free = False

    return {
        "id": sid,
        "name": full_name_ja,
        "category": category,
        "rating": "★4.7",
        "locationZone": zone,
        "lat": round(lat, 4),
        "lng": round(lng, 4),
        "kids": kids,
        "rain": rain,
        "shopping": shopping,
        "free": is_free,
        "family": True,
        "adult": True,
        "image": "",
        "wikiImage": "",
        "hasWiki": True,
        "name_en": name_en,
        "name_ja": full_name_ja,
        "name_es": name_en,
        "name_zh": name_en,
        "name_fr": name_en,
        "name_de": name_en,
        "desc_en": desc_en,
        "desc_ja": desc_ja,
        "desc_es": desc_en,
        "desc_zh": desc_ja,
        "desc_fr": desc_en,
        "desc_de": desc_en,
        "tip_en": tip_en,
        "tip_ja": tip_ja,
        "tip_es": tip_en,
        "tip_zh": tip_ja,
        "tip_fr": tip_en,
        "tip_de": tip_en,
        "price_ja": p_ja,
        "price_en": p_en,
        "price_es": p_es,
        "price_zh": p_zh,
        "price_fr": p_fr,
        "price_de": p_de
    }

def run_compiler():
    final_spots = [make_full_spot_object(s) for s in spots_data]
    
    filepath = os.path.join(cities_dir, "rotterdam.json")
    out_obj = {
        "city": "Rotterdam",
        "country": "Netherlands",
        "city_ja": "ロッテルダム",
        "country_ja": "オランダ",
        "spots": final_spots
    }
    with open(filepath, 'w', encoding='utf-8') as f:
        json.dump(out_obj, f, indent=2, ensure_ascii=False)

    print(f"🎉 Successfully compiled rotterdam.json with {len(final_spots)} verified spots!")

if __name__ == '__main__':
    run_compiler()
