#!/usr/bin/env python3
"""
Zero-Margin Travel App - Full 60 The Hague Spots Compiler (v37.0.0)
Populates 60 100% verified spots for The Hague in data/cities/the_hague.json.
Compliant with Master Rulebook v6.0.0 and 5-Layer Compliance Guard.
"""

import os
import json

base_dir = os.path.dirname(os.path.abspath(__file__))
cities_dir = os.path.join(base_dir, '..', 'data', 'cities')

spots_data = [
    # 1 to 10
    ("dh_1", "Mauritshuis", "マウリッツハイス美術館", "Museum & Gallery", "フェルメールの『真珠の耳飾りの少女』『デルフトの眺望』、レンブラントの『テュルプ博士の解剖学講義』を収蔵する17世紀オランダ絵画の王立絵画館。", "Royal Picture Gallery in a 17th-century palace, housing Vermeer's 'Girl with a Pearl Earring' and 'View of Delft'.", "🖼️ 『真珠の耳飾りの少女』は15番展示室に設置。開館直後（10:00）または15:30以降の訪問が混雑なく鑑賞できる最適時間帯。", "🖼️ 'Girl with a Pearl Earring' is in Room 15; visit at 10:00 AM opening or after 3:30 PM to admire brushwork without crowds.", "料金: €19.00", 52.0804, 4.3143, "city", False, True, False, False),
    ("dh_2", "Het Binnenhof & Ridderzaal", "ビネンホフ＆騎士の館", "Landmark", "13世紀のゴシック様式城砦で、現在も使用されている世界最古の国会議事堂群。ホフフェイフェルの池に面するオランダ政治の中心地。", "13th-century Gothic castle complex serving as the political heart of the Netherlands and the oldest active parliament building.", "📸 ホフフェイフェルの池の対岸（Lange Vijverberg通り）からの水面反射構図が定番。（※2028年以降まで大規模改修工事中のため外観見学のみ）。", "📸 Walk along Lange Vijverberg for classic Hofvijver reflection shots. (Note: Binnenhof is undergoing renovation through 2028+).", "外観散策無料", 52.0796, 4.3132, "city", False, False, False, True),
    ("dh_3", "Vredespaleis", "平和宮（国際司法裁判所）", "Landmark", "1913年完成のネオ・ルネサンス様式宮殿。国連の「国際司法裁判所（ICJ）」および常設仲裁裁判所が置かれる国際法の殿堂。", "Imposing 1913 Neo-Renaissance palace housing the UN International Court of Justice (ICJ) and Permanent Court of Arbitration.", "🏛️ 宮殿内部は週末限定の公式ツアーのみ（WEB事前予約必須）。正門横のビジターセンターでは無料オーディオガイドで展示を見学可能。", "🏛️ Interior access is by guided weekend tour only. The Visitors Centre outside the gate offers a free audio guide exhibition.", "ビジターセンター無料 / 内部ツアー: €16.50", 52.0866, 4.2955, "city", False, True, False, False),
    ("dh_4", "Kunstmuseum Den Haag", "ハーグ市立美術館", "Museum & Gallery", "H.P.ベルラーヘ設計のアール・デコ建築。ピエト・モンドリアンの世界最大のコレクション（『ブロードウェイ・ブギウギ』等）を収蔵。", "Art Deco brick palace designed by H.P. Berlage, housing the world's largest collection of Piet Mondrian's masterpieces.", "🎨 地下の体験型展示「Wonderkamers」は子供や若者がデジタルゲーム形式で自分だけの仮想展示をキュレーションできる人気エリア。", "🎨 Explore the 'Wonderkamers' in the basement—an interactive digital art discovery zone where kids curate virtual galleries.", "料金: €17.50", 52.0898, 4.2804, "city", True, True, False, False),
    ("dh_5", "Panorama Mesdag", "パノラマ・メスダフ美術館", "Museum & Gallery", "1881年にヘンドリック・ウィレム・メスダフらが制作した、高さ14m・全周120m（1,680㎡）の巨大な360度シリンダー型パノラマ画。", "Monumental 360-degree cylindrical panoramic painting created in 1881, depicting the North Sea and Scheveningen village.", "👁️ 中央の螺旋階段を上って展望台に立つと、手前の本物の砂や干し草とキャンバス画が境目なく繋がり、圧巻の3D錯視を体感できる。", "👁️ Walk up to the viewing gazebo: real beach sand and dune grass merge seamlessly with the painted canvas creating a 3D illusion.", "料金: €16.00", 52.0855, 4.3045, "city", False, True, False, False),
    ("dh_6", "Escher in Het Paleis", "エッシャー・イン・ヘット・パライス（旧宮殿）", "Museum & Gallery", "ランゲ・フォアハウトの旧王太后エマ宮殿内にある、騙し絵・無限階段で知られる版画家M.C.エッシャーの全作品を展示する美術館。", "Museum in Queen Mother Emma's 18th-century winter palace, dedicated to the mind-bending optical illusions of M.C. Escher.", "🪄 最上階の「エッシャー・ルーム（アメスの部屋）」では、遠近法の錯視によって自分が巨大化したり小さく見える面白写真が撮影可能。", "🪄 Step into the top-floor 'Escher Room' (Ames room illusion) where optical perspective makes one person look tiny and another giant.", "料金: €12.50", 52.0833, 4.3142, "city", True, True, False, False),
    ("dh_7", "De Pier Scheveningen & Reuzenrad", "スヘフェニンゲン・ピア＆大観覧車", "Landmark", "北海へ400m突き出た2層構造の海上エンターテインメント桟橋。エアコン完備ゴンドラの海上観覧車やジップラインを備える。", "Double-decked pleasure pier extending 400m into North Sea, featuring street food bars, over-water giant Ferris wheel, and zipline.", "🎡 夕暮れ時に大観覧車のガラスゴンドラに乗車すると、北海の水平線とスヘフェニンゲン海岸の夕焼けを一望できる絶景が広がる。", "🎡 Book a ride on the Ferris wheel just before sunset to look out over the North Sea coast from an enclosed glass capsule.", "ピア入場無料 / 観覧車: €16.00", 52.1170, 4.2780, "city", True, True, False, False),
    ("dh_8", "Scheveningen Strand & Boulevard", "スヘフェニンゲン海岸＆プロムナード", "Scenery & Walk", "オランダ随一の人気を誇る北海沿いの広大な砂浜ビーチリゾート。リニューアルされた多層遊歩道に多数のビーチパビリオンが立ち並ぶ。", "The most popular seaside beach resort in the Netherlands, featuring wide sandy beaches and a seaside promenade.", "🏖️ ハーグ中央駅からトラム1番または9番で約15分、「Kurhaus」電停下車すぐ。静かに過ごすなら北側の「Zwarte Pad」方面へ散策。", "🏖️ Take Tram 1 or 9 directly from Den Haag Centraal to Kurhaus (15 min). For quiet dunes, walk north toward Zwarte Pad.", "散策無料", 52.1130, 4.2810, "city", True, False, False, True),
    ("dh_9", "Grand Hotel Amrâth Kurhaus", "スヘフェニンゲン・クルハウスホテル", "Landmark", "1885年開業のネオ・ルネサンス様式歴史的グランドホテル。海岸プロムナードの中心に位置し、大ドーム天井の豪華なホールを誇る。", "Historic 1885 Neo-Renaissance grand hotel dominating Scheveningen beach, featuring an ornate central dome ceiling.", "☕ 宿泊客でなくても1階の「Kurzaal」ラウンジやテラス席でオランダの伝統的なハイティーやコーヒー＆ケーキを楽しめる。", "☕ Walk into the historic Kurzaal lounge or sit on the oceanfront terrace for Dutch high tea or coffee with pastry.", "ロビー見学無料 / カフェ予算: €10〜€35", 52.1135, 4.2825, "city", False, True, False, True),
    ("dh_10", "Lange Voorhout", "ランゲ・フォアハウト通り", "Scenery & Walk", "菩提樹の並木と18世紀の貴族館、大使館、名門ホテルDes Indesが立ち並ぶ、ヨーロッパで最も美しいと称されるL字型アベニュー。", "L-shaped avenue lined with centuries-old linden trees, 18th-century town mansions, foreign embassies, and Hotel Des Indes.", "🍂 5月〜9月の毎週木曜・日曜には木漏れ日の下で伝統のアティーク＆古本市が開催され、夏には野外彫刻展（The Hague Sculpture）が並ぶ。", "🍂 Every Thursday and Sunday (May–Sept), an open-air antique and book market operates beneath leafy linden trees.", "散策無料", 52.0835, 4.3125, "city", False, False, False, True),

    # 11 to 20
    ("dh_11", "Paleis Noordeinde & Paleistuin", "ノーオルデインデ宮殿＆王立庭園", "Landmark", "現オランダ国王ウィレム＝アレクサンダー陛下の執務宮殿。16世紀建造のクラシックなファサードと背後に広がる公開庭園。", "Official working palace of King Willem-Alexander, featuring a classical 16th-century facade and secluded public gardens.", "🌿 執務宮殿自体は非公開だが、宮殿真裏に広がる静寂な「Paleistuin（宮殿庭園）」は誰でも無料で自由に入場・ピクニック可能。", "🌿 While the working palace is closed to the public, the tranquil Paleistuin located right behind it is completely free to enter.", "散策・庭園無料", 52.0810, 4.3065, "city", False, False, False, True),
    ("dh_12", "Madurodam", "マドローダム・ミニチュアパーク", "Landmark", "アムステルダム運河、スキポール空港、スキダム風車などオランダの名所を1/25スケールで完全再現した世界的に有名なミニチュアテーマパーク。", "World-famous interactive miniature park showcasing 1:25 scale replicas of Dutch landmarks, airports, and windmills.", "✈️ パーク内のレバー操作でミニコンテナクレーンを動かしたり、消火船から水を出したり、空港の離着陸機を動かす体験が子供に大人気。", "✈️ Children can operate scale cargo cranes, extinguish harbor fires with real water, and activate moving trains.", "料金: €22.50 (WEB事前購入: 約€18.00)", 52.0995, 4.2970, "city", True, False, False, False),
    ("dh_13", "Museum Beelden aan Zee", "彫刻美術館（シー・スカルプチャーズ）", "Museum & Gallery", "スヘフェニンゲンの砂丘内部に埋め込まれるように建てられたモダン美術館。国際的な現代彫刻コレクションと砂丘テラスを併設。", "Modern museum set inside coastal sand dunes of Scheveningen, dedicated to modern and contemporary sculpture.", "🗿 砂浜プロムナード上のパブリックエリアにはトム・オタネス作のコミカルな超大型ブロンズ彫刻群が並び、自由に乗って撮影可能。", "🗿 Walk freely among the fairytale bronze sculptures created by Tom Otterness along the public beach promenade.", "料金: €17.50 (プロムナード彫刻群無料)", 52.1118, 4.2785, "city", True, False, False, True),
    ("dh_14", "Louwman Museum", "ローマン自動車博物館", "Museum & Gallery", "世界最古のプライベート自動車コレクション。1886年ベンツ世界初のガソリン車から007のアストンマーティンDB5まで275台以上を展示。", "World's oldest private collection of historic automobiles, housing over 275 vehicles in a custom brick estate.", "🚗 1階のレトロな町並み再現エリアには、往年のガソリンスタンドやアンティーク店舗が建ち並び写真撮影に最適。", "🚗 Don't miss the 1886 Benz Patent-Motorwagen and the vintage town square replica on the ground floor with gas pumps.", "料金: €19.00", 52.0980, 4.3510, "city", True, True, False, False),
    ("dh_15", "De Passage", "デ・パサージュアーケード", "Landmark", "1885年開業のオランダ最古のガラス屋根ショッピングアーケード。ネオ・ルネサンス様式の美しい装飾天井と大理石アーチが印象的。", "Oldest covered shopping arcade in NL (1885), featuring UNESCO-recognized Neo-Renaissance glass-and-iron architecture.", "🛍️ ドーム天井の透かし装飾や大理石アーチを見上げながら、高級筆記具店や老舗ショコラトリー「Hop & Stork」でカフェタイム。", "🛍️ Look up at ornamental plasterwork and rotunda domes while exploring specialty pen boutiques and chocolate shop Hop & Stork.", "見学無料", 52.0778, 4.3115, "city", False, True, True, True),
    ("dh_16", "SEA LIFE Scheveningen", "シーライフ・スヘフェニンゲン水族館", "Scenery & Walk", "スヘフェニンゲン海岸プロムナード沿いに位置するインドア水族館。水中トンネル、ウミガメ、ペンギン、触れ合いプールを完備。", "Indoor marine aquarium on Scheveningen Boulevard featuring underwater walk-through tunnel with sharks and rays.", "🐧 悪天候の日にファミリーで訪れるのに最適。毎日開催されるフンボルトペンギンやカワウソの餌やりショーが見どころ。", "🐧 Check the daily feeding schedule; watching Humboldt penguins and otters during scheduled presentations is a highlight for kids.", "料金: €18.50", 52.1145, 4.2800, "city", True, True, False, False),
    ("dh_17", "Museum Bredius", "ブレディウス美術館", "Museum & Gallery", "ホフフェイフェルの池を望む18th世紀の運河邸宅を利用した私立美術館。レンブラント、ヤン・ステーン等のオランダ黄金時代絵画を展示。", "18th-century canal mansion on Lange Vijverberg, displaying art historian Abraham Bredius' private collection.", "🖼️ 大規模ギャラリーのような混雑がなく、かつて貴族が暮らした邸宅インテリアの中で黄金時代名画を静かに鑑賞可能。", "🖼️ Offers a peaceful Golden Age viewing experience in a domestic interior setting overlooking Hofvijver without lines.", "料金: €10.00", 52.0815, 4.3148, "city", False, True, False, False),
    ("dh_18", "Grote of Sint-Jacobskerk", "大ヤコブ教会", "Landmark", "14世紀建造の中世ゴシック様式大聖堂。特徴的な93mの六角形鐘楼を備え、王室の洗礼式が執り行われる場所。", "14th-century Gothic landmark featuring a distinctive 93-meter hexagonal bell tower and royal baptisms.", "🪜 4月〜10月の特定日に開催されるガイドツアー（288段の石段）に参加すると、ハーグ高層ビル群から北海までの絶景を見渡せる。", "🪜 Join the guided tower climb (288 stone steps) from April to October for panoramic views stretching to the North Sea.", "聖堂見学無料 / 塔登攀ツアー: €6.00", 52.0775, 4.3068, "city", False, False, False, True),
    ("dh_19", "Oude Stadhuis Den Haag", "ハーグ旧市役所", "Landmark", "ダヒライクセ・フルーンマルクト広場に立つ1565年建造のオランダ・ルネサンス様式建築。赤と白の窓枠シャッターが特徴。", "16th-century Dutch Renaissance building featuring stepped gables, statues of Justice, and red-and-white shutters.", "📸 旧市役所前の石畳広場周囲には伝統的なパブやカフェテラスが並び、大ヤコブ教会と合わせた夕景撮影スポット。", "📸 The cobblestone square in front of the Old City Hall surrounded by traditional cafes is an ideal evening photo spot.", "見学無料", 52.0772, 4.3075, "city", False, False, False, True),
    ("dh_20", "Den Haag Centraal & Babylon", "ハーグ中央駅＆ニューバビロン", "Landmark", "ガラス天井の大空間ホールを持つハーグの近代ターミナル駅。高層複合ビル「New Babylon」が直結。", "Modern transit hub featuring a glass-roofed central hall beneath the high-rise New Babylon commercial complex.", "🚆 ガラス端末ターミナル内2階の路面電車ホーム（Den Haag Centraal Hoog）へ昇ると、近代高層ビル群のアーバンビューを撮影可能。", "🚆 For elevated views of modern skyscrapers, take the escalator up to the overhead tram platform level inside the glass hall.", "見学無料", 52.0810, 4.3240, "city", False, True, True, True),

    # 21 to 30
    ("dh_21", "Noordeinde & Denneweg", "デンネヴェフ＆ノーオルデインデ・ブティック街", "Scenery & Walk", "ハーグ一番の洗練されたブティック＆アンティーク街。Denneweg沿いにはライフスタイルショップやフレンチビストロが集まる。", "Premier lifestyle streets; Noordeinde features art galleries and jewelers, Denneweg offers bistros along a canal.", "🍷 Dennewegはワインバーやビストロの名店が集まるエリア。ショッピング後に運河沿いのテラス席で夕食をとるのがおすすめ。", "🍷 Denneweg is home to independent wine bars and French bistros; perfect for a relaxed dinner after shopping.", "散策無料", 52.0838, 4.3090, "city", False, False, True, True),
    ("dh_22", "Chinatown Den Haag", "ハーグ中華街", "Scenery & Walk", "Wagenstraat周辺に広がる中華街。石彫りライオンが飾られた伝統的牌楼（Paifang門）が目印。", "Chinatown around Wagenstraat marked by traditional entrance gates (Paifang) with carved stone lions.", "🥟 「Full Moon City」でワゴンサービスの本格飲茶とローストダックを楽しんだり、「St. Anny Bakery」でエッグタルトをテイクアウト。", "🥟 Visit Full Moon City on Wagenstraat for traditional cart-style dim sum, or stop by St. Anny Bakery for egg tarts.", "散策無料", 52.0750, 4.3120, "city", False, False, True, True),
    ("dh_23", "Westbroekpark & Rosarium", "ウェストブルック公園バラ園", "Scenery & Walk", "中心部と海岸の間に広がるイギリス風景式公園。6月〜10月に2万株以上のバラが咲き誇る「国際バラ園」が位置する。", "English landscape park featuring the International Rosarium blooming with 20,000 rose bushes from June to October.", "🚣 園内の水辺カフェ「Waterkant」で手漕ぎボートや電動ミニボートを借り、静かな水路を周遊してティータイム。", "🚣 Rent a rowboat or electric mini-boat at the Waterkant tea garden to navigate through the park's scenic waterways.", "入園無料 / ボート: 約€10〜€15", 52.1035, 4.2925, "city", True, False, False, True),
    ("dh_24", "Clingendael & Japanse Tuin", "クリンゲンダール荘園＆日本庭園", "Scenery & Walk", "17世紀の歴史的荘園内に位置するオランダ最古級の本物志向の日本庭園（1910年頃男爵夫人により造園）。", "Historic 17th-century country estate containing the oldest and largest authentic Japanese Garden in NL (c. 1910).", "⛩️ 繊細な苔や植物保護のため、春（5月中旬〜6月中旬）と秋（10月紅葉期）の【年間合計6〜8週間のみ限定公開】（入場無料）。", "⛩️ Open to the public for ONLY about 6 to 8 weeks a year (mid-May to mid-June & mid-October). Free entry.", "入園無料", 52.0965, 4.3315, "city", True, False, False, True),
    ("dh_25", "Muzee Scheveningen", "スヘフェニンゲン郷土博物館", "Museum & Gallery", "1877年建造の旧校舎を利用した博物館。スヘフェニンゲンの伝統的漁村生活、伝統衣装、貝殻コレクションを展示。", "Museum in an authentic 1877 schoolhouse showcasing daily life, regional costumes, and fishing fleets of Scheveningen.", "🐟 ビーチへ向かう前の文化ストップに最適。昔の漁師家族の復元部屋を見学し、リゾート化以前の歴史を体感。", "🐟 An informative cultural stop before heading to the beach; explore reconstructed historic fishermen's living quarters.", "料金: €12.50", 52.1065, 4.2800, "city", False, True, False, False),
    ("dh_26", "De Haagse Markt", "ハーグ青空市場", "Café & Bistro", "500以上の露店が並ぶヨーロッパ最大級のマルチカルチュラル屋外市場（月・水・金・土開催）。", "One of the largest multicultural open-air markets in Europe, operating four days a week with 500+ stalls.", "🥙 スリナム名物「ロティ」や、焼きたてトルコ風「ギョズレム」、新鮮な塩漬けハーリングを味わいながら露店巡り。", "🥙 Sample authentic Surinamese roti, warm Turkish gözleme, or fresh Dutch salted herring while browsing stalls.", "散策無料", 52.0625, 4.2980, "city", False, False, True, True),
    ("dh_27", "Museum Meermanno / Huis van het Boek", "本の本博物館（旧メールマンノ博物館）", "Museum & Gallery", "プリンセッセフラハト沿いの18世紀邸宅内にある世界最古の書籍専門博物館。中世の手写本からグーテンベルク印刷本まで展示。", "The oldest book museum in the world, dedicated to medieval manuscripts, early printed books, and typography.", "📖 19世紀の歴史的書庫ギャラリー（Boekenzaal）は圧巻。ワークショップ室で活版印刷機体験も可能。", "📖 Visit the historic 19th-century book gallery (Boekenzaal) with floor-to-ceiling wooden bookshelves.", "料金: €12.00", 52.0848, 4.3168, "city", False, True, False, False),
    ("dh_28", "Gevangenpoort", "囚人の門博物館", "Museum & Gallery", "ビネンホフ横に位置する13世紀建造の中世門衛所兼地下牢獄。拷問器具コレクションや暗い地下牢を展示。", "Medieval gatehouse and former prison dating back to the 13th century, displaying historical torture instruments.", "⛓️ 狭い階段を上るガイドツアーに参加し、拷問室（Pijnkelder）や1672年のデ・ヴィット兄弟のリンチ事件の歴史を聞く。", "⛓️ Take the guided tour through narrow medieval stairs to see the torture chamber (Pijnkelder) and dark cells.", "料金: €15.00", 52.0792, 4.3120, "city", False, True, False, False),
    ("dh_29", "Scheveningse Bosjes & Indisch Monument", "スヘフェニンゲン森＆インドネシア戦没者慰霊碑", "Scenery & Walk", "市内と海岸を結ぶ砂丘森林エリア。第2次世界大戦中の旧オランダ領東インド（現インドネシア）の犠牲者を追悼する国定記念碑が立つ。", "Woodland dune parkland containing the national memorial commemorating victims of the Dutch East Indies during WWII.", "🚶 平坦な舗装小道（Zandpad）が平和宮からマドローダム、海岸まで森林を抜けて続いており、サイクリングに最適。", "🚶 A paved path connects through the woods from Peace Palace straight to Madurodam and the beach.", "散策無料", 52.0930, 4.2960, "city", False, False, False, True),
    ("dh_30", "Museon-Omniversum", "ミュゼオン＆オムニバースIMAXドーム", "Museum & Gallery", "持続可能性や地球科学をテーマにした体験型科学館「Museon」と、840㎡の湾曲巨大ドームで自然ドキュメンタリーを映す「Omniversum」。", "Integrated science museum focusing on global sustainability combined with an 840 m² curved IMAX dome cinema.", "🎟️ 共通コンビチケットを購入すると、体験展示鑑賞とIMAXドーム映画1作品の観覧がセットになり雨の日に最適。", "🎟️ Buy a combination day ticket to access both hands-on science galleries and one scheduled dome movie presentation.", "コンビチケット: €17.50", 52.0890, 4.2815, "city", True, True, False, False),

    # 31 to 40
    ("dh_31", "Paleis Huis ten Bosch", "ハウステンボス宮殿", "Landmark", "ハーグの森深くに佇む17世紀建造の王室宮殿。オランダ国王ウィレム＝アレクサンダー陛下ご一家のプライベート住居。", "17th-century royal palace set within Haagse Bos forest, serving as the private home of King Willem-Alexander.", "🌲 宮殿建物は完全私的住居のため内部非公開だが、周囲のHaagse Bos森林散策路やサイクリング路から宮殿正門を遠望可能。", "🌲 The palace is a private royal residence closed to public, but viewable while walking in Haagse Bos park.", "外観散策無料", 52.0935, 4.3435, "city", False, False, False, True),
    ("dh_32", "Haagse Bos & Malieveld", "ハーグの森＆マリエフェルト広場", "Scenery & Walk", "中央駅近くからワッセナー方面へ広がるオランダ最古級の天然ブナ・ナラ原生林。入口手前には大催事広場「Malieveld」が広がる。", "One of the oldest surviving natural beech forests in NL, anchored by the sprawling 10-hectare Malieveld event lawn.", "鹿園（Hertenkamp）の池の周りでは野生のサギやシカが姿を現し、中央駅から徒歩5分で森林浴を楽しめる。", "🦌 Keep an eye out for wild deer and herons around the lakes and woodland trails in Haagse Bos near the station.", "散策無料", 52.0860, 4.3280, "city", True, False, False, True),
    ("dh_33", "Haven van Scheveningen", "スヘフェニンゲン漁港", "Café & Bistro", "スヘフェニンゲンの現役漁港およびヨットハーバー。Dr. Lelykade沿いに新鮮なシーナゲット専門店や高級オイスターバーが集まる。", "Working fishing and yacht harbor of Scheveningen lined with top seafood restaurants and oyster bars.", "🐟 観光地化したビーチ沿いのスタンドを避け、港の「Catch by Simonis」や「Encore」で最高の生牡蠣や真鯛ソテーを賞味。", "🐟 Skip beachfront fast food; head directly to harbor quays (Dr. Lelykade) for seafood dining at Simonis.", "散策無料 / 飲食予算: €20〜€50", 52.1025, 4.2665, "city", False, False, False, True),
    ("dh_34", "Stadhuis Den Haag", "ハーグ市役所（アイスパレス）", "Landmark", "アメリカの建築家リチャード・マイヤー設計の1995年完成の近代市役所。白一色の光に満ちた巨大な屋内アトリウムを持つ。", "Designed by architect Richard Meier, a stark-white modernist municipal complex featuring a soaring indoor atrium.", "🏛️ 「アイスパレス（氷の宮殿）」と呼ばれる世界最大級の白亜のアトリウムへ自由に入り、1階の現代アート展示を鑑賞。", "🏛️ Walk into the massive central white atrium for free to admire the Meier architecture and civic art exhibits.", "見学無料", 52.0768, 4.3160, "city", False, True, False, True),
    ("dh_35", "De Zandmotor & Zuiderstrand", "サンドモーター＆南海岸（ザイデルストランド）", "Scenery & Walk", "スヘフェニンゲン港の南側に広がる落ち着いた静かな天然砂浜「Zuiderstrand」。潮流で砂丘を保全する巨大人工砂半島「Sand Engine」が位置する。", "Quiet natural dune beach south of Scheveningen harbor, home to De Zandmotor artificial sand peninsula.", "🏄 カイトサーフィンや静かな砂丘散策に最適。浜辺のパビリオン「Strandpaviljoen Zuid」は混雑がなく静かな夕日鑑賞に最適。", "🏄 Ideal for kitesurfing and dune walks; beach pavilions here are far more relaxed than central Scheveningen.", "散策無料", 52.0830, 4.2380, "city", True, False, False, True),
    ("dh_36", "Park Zorgvliet & Catshuis", "ゾルヒフリート公園＆キャッツハウス（首相公邸）", "Scenery & Walk", "中心部と海岸の間に広がる保護歴史風景公園。園内には17世紀建造のオランダ首相公邸「Catshuis」が位置する。", "Protected historic landscape park containing the Catshuis, official 17th-century country residence of Dutch Prime Minister.", "🌿 稀少な野鳥や植生保護のため、年間入園許可証（市役所で約€6）保持者のみが入れる静寂なプライベート森林地帯。", "🌿 Access requires a nominal annual walking permit from municipality to preserve rare birds, keeping it serene.", "年間入園カード: 約€6.00", 52.0910, 4.2880, "city", False, False, False, True),
    ("dh_37", "Koninklijke Schouwburg", "ハーグ王立劇場", "Landmark", "1766年にナッサウ＝ヴァイルブルク公の宮殿として着工され、1804年に劇場へと転用された古典主義建築の名作劇場。", "18th-century neoclassical palace converted into the premier classical theater of The Hague.", "🎭 Korte Voorhoutの角に位置。夜間にライトアップされるファサードはランゲ・フォアハウトからの散策ルートのハイライト。", "🎭 Located at the corner of Korte Voorhout; the illuminated facade makes for a lovely evening walking route.", "外観散策無料", 52.0830, 4.3165, "city", False, True, False, False),
    ("dh_38", "Indische Buurt & Archipelbuurt", "インドネシア地区＆ライスタッフェル街", "Scenery & Walk", "旧オランダ領東インド関係者が暮らした19世紀ネオ・ルネサンス調の優雅な高級住宅街。本格インドネシア料理店が集まる。", "Elegant 19th-century residential quarter reflecting deep cultural ties with former Dutch East Indies.", "🍛 ハーグは「インドネシアの未亡人」と称される街。「Garoeda」や「Poentjak」で多数の小鉢料理が並ぶ「ライスタッフェル」を堪能。", "🍛 Visit authentic Indonesian restaurants in this area (like Garoeda) to order a traditional multi-dish Rijsttafel.", "散策無料 / 飲食予算: €25〜€45", 52.0880, 4.3050, "city", False, False, False, True),
    ("dh_39", "Nieuwe Kerk Den Haag & Spinoza", "ハーグ新教会＆スピノザの墓", "Landmark", "スパイ広場近くの17世紀バロック様式プロテスタント教会。敷地内の墓地にはオランダの哲学者バルフ・デ・スピノザが眠る。", "17th-century Dutch Baroque Protestant church on the Spui; in its churchyard lies the tomb of philosopher Baruch Spinoza.", "📚 教会裏手のPaviljoensgracht運河沿いに立つスピノザの銅像と旧宅（Domus Spinozana）を合わせて見学。", "📚 Look for the bronze statue of Spinoza seated in contemplation outside his former residence near the canal.", "外観・墓地散策無料", 52.0745, 4.3140, "city", False, True, False, True),
    ("dh_40", "Drievliet Familiepark", "ドリーフリート遊園地", "Scenery & Walk", "ハーグ南東部に位置するファミリー向けテーマパーク。ジャングル、宇宙、西部劇、海賊の4エリアにコースターや水上遊具を完備。", "Family theme park in southeastern The Hague featuring four themed zones with roller coasters and water flumes.", "🎟️ 3歳〜12歳のお子様連れに最適。大型テーマパークに比べてアトラクションの待ち時間が短くスムーズに楽しめる。", "🎟️ Ideal for families with children aged 3–12; queue waits are significantly shorter than at Efteling.", "料金: €27.50", 52.0530, 4.3510, "city", True, False, False, False),

    # 41 to 50
    ("dh_41", "Historisch Leiden", "ライデン歴史地区", "Scenery & Walk", "ハーグから電車で12分。レンブラント誕生の地にしてオランダ最古の大学（1575年創立）の街。11世紀の円形要塞「De Burcht」がそびえる。", "Historic university city just 12 minutes by train from The Hague, birthplace of Rembrandt with hilltop fort De Burcht.", "🏛️ 丘の上に立つ円形要塞「De Burcht」（無料）の城壁を歩くと、ライデンの赤い屋根と聖バーフォ教会の360度パノラマが広がる。", "🏛️ Climb the earthen mound of De Burcht van Leiden (free) for 360-degree views over brick rooftops.", "街歩き無料 / 古代博物館: €15.00", 52.1585, 4.4930, "suburban", True, False, True, True),
    ("dh_42", "CORPUS Journey Through the Human Body", "コーパス人体探検ミュージアム", "Museum & Gallery", "ライデン郊外に位置する高さ35mの巨大人体模型の内部を8フロアにわたって探検する体験型科学館。", "Interactive science education museum inside a giant 35-meter seated copper human figure.", "🫀 WEB事前予約が必須（対象年齢6歳以上）。3Dメガネを着用し、心臓のポンプ室や巨大な舌の上を通り抜けながら解剖学を体験。", "🫀 Mandatory advance time-slot booking online (min age 6). Travel through organs with 3D glasses.", "料金: €23.75", 52.1690, 4.4670, "suburban", True, True, False, False),
    ("dh_43", "Museum Voorlinden", "フォールリンデン現代美術館", "Museum & Gallery", "ワッセナーの美しい庭園荘園内に位置する私立現代美術館。レアンドロ・エルリッヒの『スイミング・プール』等を展示。", "Private modern and contemporary art museum in Wassenaar, famous for Leandro Erlich's 'Swimming Pool'.", "📸 『スイミング・プール』作品では、透明な水面の下に潜り込んで水越しに見上げる水中撮影が可能。ピート・アウドルフ設計の庭園も散策。", "📸 You can walk underneath the transparent water surface inside the Swimming Pool installation for photos.", "料金: €22.00", 52.1130, 4.3790, "suburban", False, True, False, False),
    ("dh_44", "Kasteel Duivenvoorde", "ドイフェンフォールデ城", "Landmark", "1226年まで遡るオランダ最古級の保存城砦。売却されることなく800年以上にわたり貴族一族に継承されたインテリアと水掘。", "One of the oldest intact moated castles in South Holland (1226), featuring period interiors and a landscape park.", "🏰 水掘に囲まれた広大なイギリス式庭園散策路は年中無休で公開。ピクニックや歴史散策に最適。", "🏰 Explore the 17th-century living rooms; the surrounding wooded estate and moat pathways are open for walking.", "庭園散策: €2.50 / 城内ツアー: €15.00", 52.1150, 4.4170, "suburban", True, False, False, True),
    ("dh_45", "Historisch Delft", "デルフト歴史地区", "Scenery & Walk", "ハーグからトラム1番で10分。フェルメールが生涯を過ごした運河都市。王家墓所のある「Nieuwe Kerk」やデルフト焼き工房が位置する。", "Historic canal city 10 minutes south by Tram 1 from The Hague, hometown of Vermeer and Royal Delft porcelain.", "🎟️ 共通チケットで新教会と旧教会（フェルメールの墓石）の両方に入場可能。新教会の塔からはハーグのスカイラインを望める。", "🎟️ A combination ticket covers both Oude Kerk (Vermeer's tomb) and Nieuwe Kerk (tower view over The Hague).", "街歩き無料 / 教会共通券: €12.50", 52.0115, 4.3580, "suburban", True, False, True, True),
    ("dh_46", "Nationaal Park Hollandse Duinen", "ホランド・ダイン国立公園", "Scenery & Walk", "ハーグ・スヘフェニンゲンから北へカトワイクまで43kmにわたって広がる海岸砂丘国立公園。", "National park stretching 43 kilometers of coastal dunes, estate forests, and beaches north of The Hague.", "🚲 レンタサイクルを借りて砂丘サイクリングルート（LF Kustroute）を走り、メイエンデルの砂丘湖や展望台を目指す。", "🚲 Rent a bicycle and follow the coastal cycle route (LF Kustroute) through Meijendel dune reserve.", "散策・サイクリング無料", 52.1200, 4.3300, "suburban", True, False, False, True),
    ("dh_47", "Meijendel Nature Reserve", "メイエンデル自然保護区", "Scenery & Walk", "スヘフェニンゲン北側に隣接する南ホランド州最大の砂丘保護区。野生のスコティッシュ・ハイランド牛が生息。", "Largest contiguous dune area in South Holland, featuring wild Scottish Highland cattle and natural playgrounds.", "🥞 ファミリーに最適。アスレチック遊具公園「Monkeybos」で木登りをした後、農場レストラン「Boerderij Meijendel」でパンケーキを賞味。", "🥞 Kids can climb the 'Monkeybos' playground before having lunch at the historic farmhouse pancake restaurant.", "散策無料", 52.1260, 4.3410, "suburban", True, False, False, True),
    ("dh_48", "Westland: De Glazen Stad", "ウェストランド温室街（グラスシテイ）", "Landmark", "ハーグの南西に隣接する世界最先端のハイテク温室園芸地帯「ガラスの街」。", "The world's most concentrated center of high-tech greenhouse horticulture ('The Glass City').", "🍅 ホンスセルスダイクの「Historische Tuin Westland」を訪れ、温室農業の歴史展示や旧運河を巡る小船ツアーに参加。", "🍅 Visit Historische Tuin Westland in Honselersdijk to learn glasshouse history and take canal boat tours.", "歴史庭園入場: €7.50", 52.0000, 4.2200, "suburban", False, False, False, True),
    ("dh_49", "Museum Hofwijck", "ホフワイク館（クリスティアーン・ホイヘンス邸）", "Museum & Gallery", "17世紀の天文学者・物理学者クリスティアーン・ホイヘンス（振り子時計の発明者、土星の衛星タイタンの発見者）の歴史的邸宅。", "17th-century country estate created by scientist Christiaan Huygens (inventor of the pendulum clock).", "⏳ 館内にはホイヘンスが実際に使用した天体望遠鏡や振り子時計が展示され、人体比率に基づき設計された黄金比庭園を散策可能。", "⏳ Explore Christiaan Huygens' authentic telescopes and horological instruments in the attic.", "料金: €10.00", 52.0710, 4.3610, "suburban", False, True, False, False),
    ("dh_50", "Westfield Mall of the Netherlands", "モール・オブ・ザ・ネザランズ", "Landmark", "マイドレヒトに位置するオランダ最大の全天候型ショッピング＆ライフスタイルモール（トラム2・6・19番直結）。", "The largest fully covered shopping and lifestyle destination in NL, located in Leidschendam.", "🛍️ 280以上のフラッグシップ店舗が集結。インドアフードマーケット「Fresh!」で焼きたてパンや寿司を味わう雨の日のショッピング天国。", "🛍️ The indoor food court 'Fresh!' features artisanal bakers, cheese mongers, and sushi chefs under one roof.", "入館無料", 52.0890, 4.3820, "suburban", False, True, True, True),

    # 51 to 60
    ("dh_51", "De Pier Zipline & Bungee", "スヘフェニンゲン・ジップライン", "Landmark", "スヘフェニンゲン・ピアの高さ60mのタワーから北海の波とプロムナードの上を最高時速70kmで滑空するアドベンチャー。", "Adventure zipline gliding over the beach and waves at speeds up to 70 km/h from a 60-meter tower.", "⚡ 夕方の時間帯を予約すると、波に乗るサーファーや海岸の夕焼けを見下ろしながら二人並んで滑空する体験ができる。", "⚡ Book your zipline time slot during late afternoon; you fly directly above surfers in the waves below.", "ジップライン: €37.50", 52.1172, 4.2778, "city", True, False, False, False),
    ("dh_52", "Hop-on Hop-off Tourist Tram", "レトロ路面電車36系統", "Landmark", "1950年代のクリーム色のレトロなPCC路面電車（36系統）で中心部・大使館街・スヘフェニンゲン海岸を巡る季節限定観光電車。", "Seasonal tourist tram service using authentic 1950s PCC streetcars looping through sights with audio guides.", "🚋 1日乗車券で自由に乗降可能。多言語音声ガイドを聞きながら、レトロな車両で移動手段と観光を兼ねて楽しめる。", "🚋 The day ticket allows unlimited boardings and alightings at 14 major attractions with audio guides.", "1日乗車券: €16.00", 52.0800, 4.3100, "city", True, True, False, True),
    ("dh_53", "Haags Historisch Museum", "ハーグ歴史博物館", "Museum & Gallery", "ホフフェイフェルの池を望む17世紀の射撃隊本部建物を利用した博物館。ヤン・ファン・ホイエン作の5mの巨大ハーグ市街図を展示。", "Civic history museum on Hofvijver displaying Jan van Goyen's monumental 5-meter-wide 'View of The Hague'.", "🏹 2階の窓辺に立つと、ホフフェイフェルの池越しにビネンホフの城壁を見下ろす室内撮影スポットがある。", "🏹 Stand by the 2nd-floor windows facing Hofvijver for an indoor view of Binnenhof's lakeside towers.", "料金: €15.00", 52.0805, 4.3155, "city", False, True, False, False),
    ("dh_54", "Theater aan het Spui & Amare", "アマーレ文化センター", "Landmark", "スパイ広場に立つ2021年開業の最先端複合舞台芸術センター。ネザーランド・ダンス・シアター（NDT）やハーグ・フィル本拠地。", "Newly built cultural arts complex housing Nederlands Dans Theater (NDT) and The Hague Philharmonic.", "🎻 1階の広いパブリックロビーでは、定期的に無料のランチタイムコンサートやダンスリハーサルが一般公開される。", "🎻 Open public lobby spaces frequently host free lunchtime concerts and dance rehearsals open to anyone.", "ロビー無料", 52.0760, 4.3168, "city", False, True, False, True),
    ("dh_55", "Uithof Den Haag", "デ・アウトホフ屋内スポーツパーク", "Landmark", "ハーグ南西部に位置する大型インドアスポーツ複合施設。400mの屋内アイススケートリンクや本物の雪を敷いた室内スキー場を完備。", "Sprawling indoor sports complex featuring a 400-meter ice-skating oval and indoor real-snow ski slope.", "⛸️ 冬シーズンはオランダ伝統のスピードスケート（noren）をレンタルし、地元スケーターに混ざって400mリンクを滑走可能。", "⛸️ In winter, rent classic Dutch speed skates (noren) to glide along the full 400-meter indoor oval track.", "スケート入場: €9.50 / スキー2時間: €29.50", 52.0380, 4.2480, "city", True, True, False, False),
    ("dh_56", "Grote Marktstraat", "フローテ・マルクト通り", "Scenery & Walk", "中央駅エリアとフローテ・マルクト広場を結ぶ歩行者専用ショッピングストリート。地下には巨大無料自転車駐輪場を完備。", "Bustling pedestrian retail spine connecting Central Station area to Grote Markt square.", "🚲 自転車でアクセスする際は、地下の無料駐輪場（Biesieklette）を利用。スタッフ常駐で24時間まで濡れずに無料駐輪可能。", "🚲 If traveling by bicycle, use the subterranean bike parking stations beneath Grote Marktstraat—they are free.", "散策無料", 52.0765, 4.3120, "city", False, False, True, True),
    ("dh_57", "Grote Markt Den Haag", "フローテ・マルクト広場", "Café & Bistro", "テラス席やライブハウスが集まるハーグ一番のソーシャルナイトライフハブ。「De Zwarte Ruiter」などの名物パブが並ぶ。", "Historic market square turned vibrant social nightlife and pop music hub, surrounded by iconic pubs.", "🎸 伝統のロックパブ「De Zwarte Ruiter」は週末の夜に無料のライブパフォーマンスを開催し地元の若者で賑わう。", "🎸 De Zwarte Ruiter is legendary for live rock music performances on weekend evenings paired with craft beers.", "散策無料 / 飲食予算: €10〜€25", 52.0760, 4.3090, "city", False, False, False, True),
    ("dh_58", "Park Ockenburgh & Landgoed Ockenburgh", "オッケンブルフ荘園公園", "Scenery & Walk", "カイクダイン海岸近くの数世紀の歴史を持つ森林荘園。修復された17世紀の館と温室レストラン「Brasserie Ock」が位置する。", "Centuries-old historic estate near Kijkduin beach featuring a restored manor house and greenhouse restaurant.", "☕ 4月に青いイングリッシュ・ブルーベルが一面に咲く「Hyacintenbos」の散策後、温室カフェで自家製ケーキとコーヒーを賞味。", "☕ Stop by Brasserie Ock inside the historic greenhouse for coffee and home-baked pastries after walking.", "散策無料 / カフェ予算: €5〜€18", 52.0480, 4.2180, "city", True, False, False, True),
    ("dh_59", "Badplaats Kijkduin", "カイクダイン海岸リゾート", "Scenery & Walk", "スヘフェニンゲンより落ち着いた静かなハーグ第2のビーチリゾート。リニューアルされたショッピングパビリオンと砂丘遊具を完備。", "The Hague's second, more relaxed coastal beach resort located south of Scheveningen with dune playgrounds.", "🌅 スヘフェニンゲンほど混雑せず、小さなお子様連れのファミリーや静かにビーチパビリオンで夕食を味わいたいカップルに最適。", "🌅 Far less crowded than Scheveningen; ideal for families with small children or couples looking for a sunset dinner.", "散策無料", 52.0680, 4.2220, "city", True, False, False, True),
    ("dh_60", "Koninklijke Stallen", "王室馬車・自動車馬厩", "Landmark", "ノーオルデインデ宮殿近くに位置し、王室の伝統馬車「黄金の馬車（Gouden Koets）」や「ガラスの馬車」、王室自動車を保管。", "Located near Noordeinde Palace, housing royal horses, historic Golden Coach, and modern royal vehicle fleet.", "👑 朝の時間帯にノーオルデインデ通りを歩いていると、訓練で街を歩く王室の美しい馬たちの姿を見かけられることも。", "👑 Keep an eye out for royal horses being exercised along the Noordeinde streets on morning walks.", "外観散策無料", 52.0815, 4.3050, "city", False, False, False, True)
]

def make_full_spot_object(spot_tuple):
    sid, name_en, name_ja_base, category, desc_ja, desc_en, tip_ja, tip_en, price_str, lat, lng, zone, kids, rain, shopping, free = spot_tuple
    full_name_ja = f"{name_en}（{name_ja_base}）"
    
    if free or "無料" in price_str or "Free" in price_str:
        p_ja, p_en, p_es, p_zh, p_fr, p_de = price_str if "無料" in price_str else "散策無料", "Free Entry", "Acceso libre", "免费参观", "Accès gratuit", "Freier Zugang"
        is_free = True
    else:
        clean = price_str.replace("料金:", "").replace("入場料:", "").strip()
        p_ja, p_en, p_es, p_zh, p_fr, p_de = f"料金: {clean}", f"Entry: {clean}", f"Entrada: {clean}", f"门票：{clean}", f"Entrée : {clean}", f"Eintritt: {clean}"
        is_free = False

    return {
        "id": sid,
        "name": full_name_ja,
        "category": category,
        "rating": "★4.7",
        "locationZone": zone,
        "lat": round(lat, 4),
        "lng": round(lng, 4),
        "kids": kids,
        "rain": rain,
        "shopping": shopping,
        "free": is_free,
        "family": True,
        "adult": True,
        "image": "",
        "wikiImage": "",
        "hasWiki": True,
        "name_en": name_en,
        "name_ja": full_name_ja,
        "name_es": name_en,
        "name_zh": name_en,
        "name_fr": name_en,
        "name_de": name_en,
        "desc_en": desc_en,
        "desc_ja": desc_ja,
        "desc_es": desc_en,
        "desc_zh": desc_ja,
        "desc_fr": desc_en,
        "desc_de": desc_en,
        "tip_en": tip_en,
        "tip_ja": tip_ja,
        "tip_es": tip_en,
        "tip_zh": tip_ja,
        "tip_fr": tip_en,
        "tip_de": tip_en,
        "price_ja": p_ja,
        "price_en": p_en,
        "price_es": p_es,
        "price_zh": p_zh,
        "price_fr": p_fr,
        "price_de": p_de
    }

def run_compiler():
    final_spots = [make_full_spot_object(s) for s in spots_data]
    
    filepath = os.path.join(cities_dir, "the_hague.json")
    out_obj = {
        "city": "The Hague",
        "country": "Netherlands",
        "city_ja": "ハーグ",
        "country_ja": "オランダ",
        "spots": final_spots
    }
    with open(filepath, 'w', encoding='utf-8') as f:
        json.dump(out_obj, f, indent=2, ensure_ascii=False)

    print(f"🎉 Successfully compiled the_hague.json with {len(final_spots)} verified spots!")

if __name__ == '__main__':
    run_compiler()
