#!/usr/bin/env python3
"""
Patch build_dresden_spots.py to insert dr_27 to dr_40 between dr_26 and dr_41.
"""

dr_27_to_40 = [
    # dr_27
    {
        "id": "dr_27",
        "name": "Albertinum（アルベルティヌム / 近代名画館・彫刻館）",
        "category": "Museum & Gallery",
        "rating": "★4.8",
        "locationZone": "city",
        "lat": 51.0520, "lng": 13.7442,
        "kids": False, "rain": True, "shopping": False, "free": False, "family": True, "adult": True,
        "desc_en": "Renaissance Revival museum building on Brühl's Terrace housing the Galerie Neue Meister and Sculpture Collection, showcasing masterpieces from Romanticism (Caspar David Friedrich) to modern art (Gerhard Richter).",
        "desc_ja": "ブリュールのテラス沿いに立つルネサンス復古様式の美術館。カスパー・ダーヴィト・フリードリヒのロマン派絵画からゲルハルト・リヒター等の現代アートまでを収蔵する新マスターギャラリー（Galerie Neue Meister）と彫刻館。",
        "desc_es": "Museo de estilo neorrenacentista en la Terraza de Brühl que alberga la Galerie Neue Meister y la Colección de Escultura, con obras maestras del Romanticismo (Caspar David Friedrich) y arte moderno.",
        "desc_zh": "坐落于布吕尔平台上的新文艺复兴风格美术馆，包含新大师画廊（Galerie Neue Meister）与雕塑馆，收藏从浪漫主义画派（卡斯帕·大卫·弗里德里希）至当代大师（格哈德·里希特）的艺术杰作。",
        "desc_fr": "Musée de style néo-renaissance situé sur la terrasse de Brühl, abritant la Galerie Neue Meister et la Collection de Sculptures, avec des chefs-d'œuvre du romantisme et de l'art moderne.",
        "desc_de": "Moderne Kunsthalle auf der Brühlschen Terrasse für die Galerie Neue Meister und die Skulpturensammlung, bekannt für Werke von Caspar David Friedrich, Otto Dix und Gerhard Richter.",
        "tip_en": "🎨 Don't miss the dedicated Caspar David Friedrich rooms containing iconic Romantic landscape masterpieces, as well as the contemporary Gerhard Richter archive rooms.",
        "tip_ja": "🎨 ロマン派画家カスパー・ダーヴィト-フリードリヒの代表作が集まる展示室と、ドレスデン出身の現代美術最高峰ゲルハルト・リヒターの常設アーカイブ展示室は必見です。",
        "tip_es": "🎨 No te pierdas las salas dedicadas a Caspar David Friedrich con sus icónicos paisajes románticos, así como el archivo permanente del artista contemporáneo Gerhard Richter.",
        "tip_zh": "🎨 切勿错过展出浪漫主义巨匠卡斯帕·大卫·弗里德里希代表作的专室，以及当代艺术巨匠格哈德·里希特的常设展厅。",
        "tip_fr": "🎨 Ne manquez pas les salles consacrées aux paysages romantiques de Caspar David Friedrich et les espaces d'exposition permanente dédiés à Gerhard Richter.",
        "tip_de": "🎨 Die Säle mit den Hauptwerken von Caspar David Friedrich sowie das Gerhard Richter Archiv mit Werken des weltberühmten Dresdner Künstlers besichtigen.",
        "price_en": "Adults: €12 / Reduced: €9.50 / Under 17 Free",
        "price_ja": "大人: 12€ / 割引: 9.50€ / 17歳未満無料",
        "price_es": "Adultos: 12€ / Reducida: 9,50€ / Menores de 17 gratis",
        "price_zh": "成人：12 欧元 / 优惠票：9.50 欧元 / 17岁以下免费",
        "price_fr": "Adultes : 12 € / Réduit : 9,50 € / Moins de 17 ans gratuit",
        "price_de": "Erwachsene: 12 € / Ermäßigt: 9,50 € / Unter 17 frei",
        "name_en": "Albertinum (Galerie Neue Meister & Sculpture Collection)",
        "name_ja": "Albertinum（アルベルティヌム / 近代名画館・彫刻館）",
        "name_es": "Albertinum (Galería de Nuevos Maestros y Colección de Escultura)",
        "name_zh": "Albertinum (阿尔伯蒂努姆博物馆 / 新大师画廊与雕塑馆)",
        "name_fr": "Albertinum (Galerie des Nouveaux Maîtres et Collection de Sculptures)",
        "name_de": "Albertinum (Galerie Neue Meister & Skulpturensammlung)"
    },
    # dr_28
    {
        "id": "dr_28",
        "name": "Verkehrsmuseum Dresden (Johanneum)（ドレスデン交通博物館）",
        "category": "Museum & Gallery",
        "rating": "★4.7",
        "locationZone": "city",
        "lat": 51.0515, "lng": 13.7392,
        "kids": True, "rain": True, "shopping": False, "free": False, "family": True, "adult": True,
        "desc_en": "Comprehensive transport museum housed in the historic Johanneum building at Neumarkt, showcasing centuries of mobility history across railway, maritime, road, and aviation exhibits.",
        "desc_ja": "ノイマルクト広場の歴史的建造物ヨハネウム（Johanneum）内にある総合交通博物館。鉄道、自動車、船舶、航空の4分野にわたり、ドイツの交通発達史を実物展示で紹介。",
        "desc_es": "Museo del transporte ubicado en el histórico edificio Johanneum en Neumarkt, que exhibe siglos de historia de la movilidad en ferrocarril, automoción, navegación y aviación.",
        "desc_zh": "位于新市场广场历史建筑约汉内姆宫（Johanneum）内的综合交通博物馆，通过丰富实物展示涵盖铁路、公路交通、航运及航空四大领域的交通史。",
        "desc_fr": "Musée des transports situé dans le bâtiment historique Johanneum sur la Neumarkt, retraçant l'histoire de la mobilité à travers le chemin de fer, la route, la mer et l'aviation.",
        "desc_de": "Verkehrsmuseum im historischen Johanneum am Neumarkt, das auf 5.000 qm Ausstellungsfläche die Geschichte von Eisenbahn, Straßenverkehr, Schifffahrt und Luftfahrt präsentiert.",
        "tip_en": "🚂 Features Germany's oldest preserved steam locomotive 'Saxonia' (1838) and a huge 325-square-meter model railway layout; ideal hands-on interactive area for families with kids.",
        "tip_ja": "🚂 1838年製のドイツ最古の蒸気機関車「サクソニア号」実物展示や、面積325㎡に及ぶ超大型鉄道模型レイアウトが見所。子供向け体験操作エリアも充実しています。",
        "tip_es": "🚂 Contempla la locomotora de vapor 'Saxonia' de 1838 (la más antigua de Alemania) y una enorme maqueta de trenes de 325 m² con trenes en funcionamiento.",
        "tip_zh": "🚂 馆内藏有1838年制造的德国最古老蒸汽机车“萨克森号（Saxonia）”实物，并设有面积达325平方米的超大型动态模型铁路场景。",
        "tip_fr": "🚂 Admirez la plus ancienne locomotive à vapeur d'Allemagne 'Saxonia' (1838) et un réseau miniature géant de 325 m² avec trains en circulation.",
        "tip_de": "🚂 Die älteste im Original erhaltene deutsche Dampflokomotive „Saxonia“ von 1838 und die 325 qm große Spur-0-Modelleisenbahnanlage bewundern.",
        "price_en": "Adults: €11 / Reduced: €5 / Family: €22",
        "price_ja": "大人: 11€ / 割引: 5€ / ファミリー: 22€",
        "price_es": "Adultos: 11€ / Reducida: 5€ / Familia: 22€",
        "price_zh": "成人：11 欧元 / 优惠票：5 欧元 / 家庭票：22 欧元",
        "price_fr": "Adultes : 11 € / Réduit : 5 € / Famille : 22 €",
        "price_de": "Erwachsene: 11 € / Ermäßigt: 5 € / Familienkarte: 22 €",
        "name_en": "Verkehrsmuseum Dresden (Dresden Transport Museum)",
        "name_ja": "Verkehrsmuseum Dresden (Johanneum)（ドレスデン交通博物館）",
        "name_es": "Verkehrsmuseum Dresden (Museo del Transporte de Dresde)",
        "name_zh": "Verkehrsmuseum Dresden (德累斯顿交通博物馆)",
        "name_fr": "Verkehrsmuseum Dresden (Musée des Transports de Dresde)",
        "name_de": "Verkehrsmuseum Dresden (im Johanneum)"
    },
    # dr_29
    {
        "id": "dr_29",
        "name": "Gläserne Manufaktur (Volkswagen)（フォルクスワーゲンガラス張り透明工場）",
        "category": "Landmark",
        "rating": "★4.7",
        "locationZone": "city",
        "lat": 51.0442, "lng": 13.7645,
        "kids": True, "rain": True, "shopping": False, "free": False, "family": True, "adult": True,
        "desc_en": "Futuristic glass automotive factory built by Volkswagen in 2001 adjacent to Großer Garten, where visitors can watch high-tech electric vehicle assembly through transparent walls.",
        "desc_ja": "グローサー・ガルテンの隣に2001年にVW社が建設した未来型ガラス張り自動車工場。カナダ産楓材のピカピカ床の上で電気自動車（ID.シリーズ）が静音組み立てされる工程を見学可能。",
        "desc_es": "Futurista fábrica de automóviles de cristal construida por Volkswagen en 2001 junto al parque Großer Garten, donde se observa el ensamblaje de vehículos eléctricos a través de paredes transparentes.",
        "desc_zh": "大众汽车于2001年在大花园旁建造的未来主义全玻璃外墙汽车透明工厂，游客可在枫木地板的洁净无尘车间旁近距离观摩纯电动汽车（ID.系列）的高科技装配全过程。",
        "desc_fr": "Usine automobile futuriste entièrement vitrée construite par Volkswagen en 2001 près du Großer Garten, où l'on observe l'assemblage des véhicules électriques à travers des parois transparentes.",
        "desc_de": "Gläserne Produktionsstätte von Volkswagen am Straßburger Platz im Großen Garten, in der Besucher die Fertigung von Elektrofahrzeugen hautnah miterleben können.",
        "tip_en": "🚗 Book a 75-minute guided factory walking tour in advance on the official website; test driving current VW electric vehicle models on site is available with a valid driver's license.",
        "tip_ja": "🚗 公式WEBサイトで75分間の英語・ドイツ語ガイドツアーを事前予約して訪問。日本の運転免許証（国際免許）持参でVW最新EVモデルの試乗体験も申し込み可能です。",
        "tip_es": "🚗 Reserva con antelación en su web una visita guiada de 75 minutos por las líneas de montaje; se ofrecen pruebas de conducción de vehículos eléctricos VW con carné de conducir.",
        "tip_zh": "🚗 建议提前在官网预订75分钟的工厂导览游；持有效驾驶执照还可现场免费申请试驾大众最新款纯电动车型。",
        "tip_fr": "🚗 Réservez à l'avance sur le site officiel une visite guidée de 75 minutes de la ligne d'assemblage ; des essais de véhicules électriques VW sont proposés aux titulaires du permis.",
        "tip_de": "🚗 Eine 75-minütige Führung durch die Fertigung vorab online buchen; Inhaber eines Führerscheins können vor Ort Probefahrten mit den neusten VW-Elektromodellen buchen.",
        "price_en": "Guided Tour: €9 / Reduced: €6 / Family: €20",
        "price_ja": "ガイドツアー: 9€ / 割引: 6€ / ファミリー: 20€",
        "price_es": "Visita guiada: 9€ / Reducida: 6€ / Familia: 20€",
        "price_zh": "导览游：9 欧元 / 优惠票：6 欧元 / 家庭票：20 欧元",
        "price_fr": "Visite guidée : 9 € / Réduit : 6 € / Famille : 20 €",
        "price_de": "Führung: 9 € / Ermäßigt: 6 € / Familienkarte: 20 €",
        "name_en": "Gläserne Manufaktur (Volkswagen Transparent Factory)",
        "name_ja": "Gläserne Manufaktur (Volkswagen)（フォルクスワーゲンガラス張り透明工場）",
        "name_es": "Gläserne Manufaktur (Fábrica Cristalina de Volkswagen)",
        "name_zh": "Gläserne Manufaktur (大众汽车透明工厂)",
        "name_fr": "Gläserne Manufaktur (Usine Vitrée Volkswagen)",
        "name_de": "Gläserne Manufaktur (Volkswagen Dresden)"
    },
    # dr_30
    {
        "id": "dr_30",
        "name": "Sächsische Dampfschiffahrt（エルベ川蒸気船クルーズ）",
        "category": "Scenery & Walk",
        "rating": "★4.8",
        "locationZone": "city",
        "lat": 51.0538, "lng": 13.7412,
        "kids": True, "rain": False, "shopping": False, "free": False, "family": True, "adult": True,
        "desc_en": "World's oldest and largest paddle-steamer fleet operating since 1836, offering historic Elbe river cruises past Dresden's skyline, river palaces, and sandstone cliffs.",
        "desc_ja": "1836年に設立された、現役としては世界最古・最大規模を誇る外輪蒸気船（パドルスチーマー）船団。旧市街の桟橋からピルニッツ宮殿やザクセン・スイス方面へ情緒あふれる川の旅を提供。",
        "desc_es": "La flota de barcos de vapor con ruedas de paletas más antigua y grande del mundo, en funcionamiento desde 1836, que ofrece cruceros por el Elba contemplando los palacios y la silueta de Dresde.",
        "desc_zh": "成立于1836年的全球现存最古老、规模最大的侧明轮蒸气客船船团。从旧城平台码头出发，沿易北河穿行于巴洛克宫殿群与易北河砂岩山脉之间。",
        "desc_fr": "La plus ancienne et plus grande flotte de bateaux à vapeur à roues de pale au monde, en service depuis 1836, proposant des croisières romantiques sur l'Elbe au fil des palais.",
        "desc_de": "Die älteste und größte Raddampferflotte der Welt (gegründet 1836) mit 9 historischen Raddampfern, die Fahrten entlang der Dresdner Elbschlösser bis zur Sächsischen Schweiz anbietet.",
        "tip_en": "⛴️ Board the 1.5-hour Dresden City Sightseeing Cruise (Stadtrundfahrt) from the Terrassenufer pier below Brühl's Terrace for views of the river palaces and famous bridges.",
        "tip_ja": "⛴️ ブリュールのテラス下にあるTerrassenufer乗船場から1.5時間の「市内見どころクルーズ（Stadtrundfahrt）」に乗船。船上で地ビールを飲みながら川からの絶景を写真撮影できます。",
        "tip_es": "⛴️ Sube al crucero turístico de 1,5 horas desde el embarcadero de Terrassenufer, bajo la Terraza de Brühl, para contemplar los tres palacios del Elba y los puentes históricos.",
        "tip_zh": "⛴️ 推荐从布吕尔平台下方的 Terrassenufer 码头登船体验1.5小时的“城市观光巡航”，在船上伴着拉格啤酒拍摄水上视角的三宫殿与名桥。",
        "tip_fr": "⛴️ Embarquez pour la croisière panoramique de 1h30 depuis l'embarcadère de Terrassenufer au pied de la terrasse de Brühl pour admirer les palais du bord de l'Elbe.",
        "tip_de": "⛴️ Am Anleger Terrassenufer unterhalb der Brühlschen Terrasse zu einer 1,5-stündigen Stadtrundfahrt an Bord eines historischen Raddampfers ablegen.",
        "price_en": "City Cruise: €22 / Castle Cruise to Pillnitz: €28",
        "price_ja": "1.5時間市内クルーズ: 22€ / ピルニッツ城航路: 28€",
        "price_es": "Crucero ciudad: 22€ / Crucero al Palacio Pillnitz: 28€",
        "price_zh": "1.5小时城市巡航：22 欧元 / 皮尔尼茨城堡航线：28 欧元",
        "price_fr": "Croisière ville : 22 € / Croisière château Pillnitz : 28 €",
        "price_de": "Stadtfahrt (90 Min.): 22 € / Schlösserfahrt nach Pillnitz: 28 €",
        "name_en": "Sächsische Dampfschiffahrt (Saxon Steamship Paddle Steamer Fleet)",
        "name_ja": "Sächsische Dampfschiffahrt（エルベ川蒸気船クルーズ）",
        "name_es": "Sächsische Dampfschiffahrt (Vapores de Ruedas del Elba)",
        "name_zh": "Sächsische Dampfschiffahrt (萨克森易北河蒸汽轮船船队)",
        "name_fr": "Sächsische Dampfschiffahrt (Bateaux à Vapeur de l'Elbe)",
        "name_de": "Sächsische Dampfschiffahrt (Sächsische Dampfschiffahrts-GmbH)"
    },
    # dr_31
    {
        "id": "dr_31",
        "name": "Loschwitz & Blaues Wunder (Loschwitzer Brücke)（ロスヴィッツ地区＆青い奇跡橋）",
        "category": "Scenery & Walk",
        "rating": "★4.8",
        "locationZone": "city",
        "lat": 51.0536, "lng": 13.8101,
        "kids": True, "rain": False, "shopping": True, "free": True, "family": True, "adult": True,
        "desc_en": "Upscale hillside villa district known for 'Blaues Wunder' (Blue Wonder)—a 280-meter blue steel cantilever truss bridge engineered in 1893 without river piers.",
        "desc_ja": "高級住宅地ロスヴィッツとエルベ川対岸のブラーゼヴィッツを結ぶ1893年建造の「青い奇跡（Blaues Wunder）」と呼ばれる鉄橋。川の中に橋脚を置かない当時の革新的トラス構造で知られる。",
        "desc_es": "Elegante distrito residencial en la colina famoso por el 'Milagro Azul' (Blaues Wunder), un puente cantilever de acero azul de 280 metros construido en 1893 sin pilares en el cauce.",
        "desc_zh": "位于易北河右岸的高雅山麓别墅区，以建于1893年、全长280米的“蓝色奇迹（Blaues Wunder）”钢铁悬臂桁架桥闻名，该桥因河床中无立柱的突破性结构而得名。",
        "desc_fr": "Quartier résidentiel huppé à flanc de colline célèbre pour le 'Miracle Bleu' (Blaues Wunder), un pont cantilever en acier bleu de 280 mètres construit en 1893 sans pile dans le fleuve.",
        "desc_de": "Villenviertel am Elbhang mit der Loschwitzer Brücke („Blaues Wunder“) – einer 280 Meter langen Stahlfachwerkbrücke von 1893, die als technisches Wunderwerk ohne Strompfeiler auskommt.",
        "tip_en": "🌉 Cross the bridge on foot for sunset photos over the Elbe river bend, then explore Körnerplatz square lined with historic cafes, bakeries, and craft boutiques.",
        "tip_ja": "🌉 夕暮れ時に徒歩で橋を渡ると、夕日を浴びるエルベ川の蛇行と山の手のブドウ畑の絶景が撮影可能。橋の袂のケルナープラッツ（Körnerplatz）の可愛いカフェ散策もおすすめ。",
        "tip_es": "🌉 Cruza el puente a pie al atardecer para fotografiar los meandros del Elba; luego explora la plaza Körnerplatz llena de cafeterías históricas y boutiques de artesanía.",
        "tip_zh": "🌉 建议傍晚时分步行穿过钢桥，站在桥侧拍摄被夕阳染红的易北河弯道；随后可前往桥头柯尔纳广场（Körnerplatz）体验老牌咖啡馆与精品小店。",
        "tip_fr": "🌉 Traversez le pont à pied au coucher du soleil pour photographier les méandres de l'Elbe ; puis explorez la place Körnerplatz et ses cafés historiques.",
        "tip_de": "🌉 Zu Fuß über das Blaue Wunder spazieren und am Körnerplatz in den gemütlichen Fachwerkhäusern Kaffee und Dresdner Eierschecke genießen.",
        "price_en": "Bridge & District Walk: Free",
        "price_ja": "青い奇跡橋・地区散策無料",
        "price_es": "Paseo por el puente y distrito: Gratis",
        "price_zh": "蓝色奇迹桥与街区漫步：免费",
        "price_fr": "Promenade pont et quartier : Gratuit",
        "price_de": "Brückenüberquerung & Areal frei",
        "name_en": "Loschwitz District & Blue Wonder Bridge (Blaues Wunder)",
        "name_ja": "Loschwitz & Blaues Wunder (Loschwitzer Brücke)（ロスヴィッツ地区＆青い奇跡橋）",
        "name_es": "Loschwitz & Blaues Wunder (Distrito de Loschwitz y Puente Milagro Azul)",
        "name_zh": "Loschwitz & Blaues Wunder (洛斯维茨街区与蓝色奇迹大桥)",
        "name_fr": "Loschwitz & Blaues Wunder (Quartier Loschwitz et Pont du Miracle Bleu)",
        "name_de": "Loschwitz & Blaues Wunder (Loschwitzer Brücke)"
    },
    # dr_32
    {
        "id": "dr_32",
        "name": "Standseilbahn Dresden & Schwebebahn Dresden（ドレスデンケーブルカー＆懸垂式モノレール）",
        "category": "Landmark",
        "rating": "★4.8",
        "locationZone": "city",
        "lat": 51.0545, "lng": 13.8122,
        "kids": True, "rain": False, "shopping": False, "free": False, "family": True, "adult": True,
        "desc_en": "Two world-record historic hillside railways in Loschwitz: the 1895 Standseilbahn funicular and the 1901 Schwebebahn—the world's oldest suspended monorail designed by Eugen Langen.",
        "desc_ja": "ロスヴィッツの山麓に位置する歴史的山岳鉄道。1895年開業のケーブルカー（Standseilbahn）と、オイゲン・ランゲン設計による1901年開業の「世界最古の懸垂式モノレール（Schwebebahn）」の2路線。",
        "desc_es": "Dos ferrocarriles montañosos históricos de récord en Loschwitz: el funicular Standseilbahn de 1895 y el Schwebebahn de 1901, el monorraíl suspendido más antiguo del mundo.",
        "desc_zh": "位于洛斯维茨的两个打破世界纪录的历史山地轨道：1895年开通的斜升缆车（Standseilbahn）以及1901年建成的由欧根·朗根设计的全球最古老悬挂式单轨列车（Schwebebahn）。",
        "desc_fr": "Deux chemins de fer de montagne historiques à Loschwitz : le funiculaire Standseilbahn de 1895 et le Schwebebahn de 1901, le plus ancien monorail suspendu au monde.",
        "desc_de": "Zwei historische Bergbahnen in Loschwitz: die Standseilbahn von 1895 und die älteste Schwebebahn der Welt von 1901 (Stahlkonstruktion nach Eugen Langen).",
        "tip_en": "🚟 Take the Schwebebahn up to the top station roof terrace for a panoramic view over the Elbe river valley and Blue Wonder bridge; a combined ticket covers both unique vintage rides.",
        "tip_ja": "🚟 懸垂式モノレール（Schwebebahn）で山頂駅へ登ると、屋上展望台からドレスデン市街とエルベ川、青い奇跡橋のパノラマを一望できます。2路線乗車券が便利です。",
        "tip_es": "🚟 Sube en el monorraíl suspendido Schwebebahn hasta la terraza superior para disfrutar de vistas panorámicas sobre el valle del Elba; hay billetes combinados.",
        "tip_zh": "🚟 建议乘坐悬挂式单轨（Schwebebahn）到达山顶站观景台，俯瞰易北河谷与蓝色奇迹桥；售有包含两条路线的便利组合车票。",
        "tip_fr": "🚟 Empruntez le monorail suspendu Schwebebahn jusqu'à la terrasse de la station supérieure pour embrasser la vue sur la vallée de l'Elbe ; billets combinés disponibles.",
        "tip_de": "🚟 Mit der Schwebebahn zur Bergstation fahren und von der Aussichtsplattform den Panoramablick über das Elbtal und das Blaue Wunder genießen.",
        "price_en": "Single Ride: €5 / Return Trip: €6.50",
        "price_ja": "片道: 5€ / 往復: 6.50€",
        "price_es": "Solo ida: 5€ / Ida y vuelta: 6,50€",
        "price_zh": "单程票：5 欧元 / 往返票：6.50 欧元",
        "price_fr": "Aller simple : 5 € / Aller-retour : 6,50 €",
        "price_de": "Berg- oder Talversetzung: 5 € / Berg- und Talfahrt: 6,50 €",
        "name_en": "Standseilbahn & Schwebebahn Dresden (Funicular & Oldest Suspended Monorail)",
        "name_ja": "Standseilbahn Dresden & Schwebebahn Dresden（ドレスデンケーブルカー＆懸垂式モノレール）",
        "name_es": "Standseilbahn & Schwebebahn Dresden (Funicular y Monorraíl Suspendido)",
        "name_zh": "Standseilbahn & Schwebebahn Dresden (德累斯顿缆车与悬挂式单轨电车)",
        "name_fr": "Standseilbahn & Schwebebahn Dresden (Funiculaire et Monorail Suspendu)",
        "name_de": "Standseilbahn Dresden & Schwebebahn Dresden (Dresdner Bergbahnen)"
    },
    # dr_33
    {
        "id": "dr_33",
        "name": "Schloss Albrechtsberg, Lingnerschloss & Schloss Eckberg（エルベ高台の三宮殿）",
        "category": "Landmark",
        "rating": "★4.8",
        "locationZone": "city",
        "lat": 51.0602, "lng": 13.7975,
        "kids": False, "rain": False, "shopping": False, "free": True, "family": True, "adult": True,
        "desc_en": "Trio of 19th-century grand palaces perched on the terraced Elbe river slopes (Elbschchlösser), featuring Prussian Classical and Tudor Revival architecture with vineyard parklands.",
        "desc_ja": "エルベ川右岸の高台緑地に連なる19世紀建造の「エルベ三宮殿（Elbschlößer）」。プロイセン古典主義のアルブレヒトベルク城、リングナー城、およびネオゴシック・チューダー様式のエックベルク城からなる。",
        "desc_es": "Trío de palacios del siglo XIX encaramados en las laderas aterrazadas del Elba (Elbschlößer), de estilo neoclásico prusiano y tudor con parque de viñedos.",
        "desc_zh": "坐落于易北河右岸高地阶梯葡萄园内的19世纪三大奢华宫殿群（Elbschlößer），包含普鲁士古典主义风格的阿尔布雷希特斯堡宫、林格纳宫与都铎复古风格的埃克贝格宫。",
        "desc_fr": "Trio de grands palais du XIXe siècle perchés sur les terrasses du bord de l'Elbe, mêlant architecture néoclassique prussienne et néo-tudor entourée de vignobles.",
        "desc_de": "Die drei historischen Elbschchlösser am Loschwitzer Elbhang: Schloss Albrechtsberg (spätklassizistisch), Lingnerschloss (Villa Stockhausen) und Schloss Eckberg (neugotisch).",
        "tip_en": "🏰 Stroll the free-access terraced vineyard paths connecting all three castles; stop at Lingnerschloss beer garden for affordable draught beer with sweeping river valley views.",
        "tip_ja": "🏰 3つの城を繋ぐ段々ブドウ畑の散策路は入園無料。リングナー城（Lingnerschloss）のカフェ・ビアガーデンテラスでエルベ川のパノラマを見下ろしながらのビール休憩が至福です。",
        "tip_es": "🏰 Pasea gratis por los senderos entre viñedos que conectan los tres castillos; haz una pausa en la terraza del Lingnerschloss para tomar una cerveza con vistas al río.",
        "tip_zh": "🏰 贯通三座城堡的阶梯葡萄园公园步道【免费开放】；推荐在林格纳宫（Lingnerschloss）露天啤酒花园边喝精酿边俯瞰易北河曲流。",
        "tip_fr": "🏰 Promenez-vous gratuitement sur les sentiers en terrasses reliant les trois châteaux ; arrêtez-vous à la terrasse du Lingnerschloss pour boire une bière avec vue sur le fleuve.",
        "tip_de": "🏰 Durch die terrassierten Weinberge der drei Elbschlößer wandern; die Sonnenterrasse am Lingnerschloss bietet Gastronomie mit sagenhaftem Elbblick.",
        "price_en": "Park & Vineyard Trail: Free",
        "price_ja": "三宮殿公園＆ブドウ畑散策無料",
        "price_es": "Parque y viñedos: Gratis",
        "price_zh": "宫殿园区与葡萄园步道：免费",
        "price_fr": "Parc et vignobles : Gratuit",
        "price_de": "Parkanlagen & Wege frei",
        "name_en": "Elbe Palaces: Schloss Albrechtsberg, Lingnerschloss & Schloss Eckberg",
        "name_ja": "Schloss Albrechtsberg, Lingnerschloss & Schloss Eckberg（エルベ高台の三宮殿）",
        "name_es": "Tres Palacios del Elba (Schloss Albrechtsberg, Lingnerschloss y Schloss Eckberg)",
        "name_zh": "Schloss Albrechtsberg, Lingnerschloss & Schloss Eckberg (易北河三宫殿)",
        "name_fr": "Trois Palais de l'Elbe (Schloss Albrechtsberg, Lingnerschloss et Schloss Eckberg)",
        "name_de": "Die drei Elbschlößer (Albrechtsberg, Lingnerschloss, Eckberg)"
    },
    # dr_34
    {
        "id": "dr_34",
        "name": "Prager Straße（プラーガー通り歩行者天国）",
        "category": "Scenery & Walk",
        "rating": "★4.6",
        "locationZone": "city",
        "lat": 51.0435, "lng": 13.7368,
        "kids": True, "rain": False, "shopping": True, "free": True, "family": True, "adult": True,
        "desc_en": "Dresden's primary modern pedestrian shopping boulevard connecting the Hauptbahnhof central station to Altmarkt, famed for post-war modernist architecture and water fountains.",
        "desc_ja": "ドレスデン中央駅とアルトマルクト広場を結ぶ歩行者天国メインショッピングストリート。戦後のモダン都市計画を代表するオープンな広場空間に噴水や大型商業施設が並ぶ。",
        "desc_es": "El principal bulevar peatonal comercial de Dresde que conecta la estación central Hauptbahnhof con Altmarkt, famoso por su arquitectura modernista de posguerra y sus fuentes.",
        "desc_zh": "连接德累斯顿中央火车站与老市场广场的核心现代步行商业街，以二战后东德现代主义建筑风格、宽阔的广场喷泉及各大知名品牌购物中心著称。",
        "desc_fr": "La principale artère commerçante piétonne de Dresde reliant la gare centrale à la Neumarkt, réputée pour son architecture moderniste d'après-guerre et ses fontaines.",
        "desc_de": "Moderne Fußgängerzone und Haupteinkaufsstraße Dresdens zwischen Hauptbahnhof und Altmarkt, geprägt von ostmoderner Architektur, Wasserspielen und Centren.",
        "tip_en": "🛍️ Great entry point for arrival by train; houses major retail malls (Centrum Galerie and Rundkino) along with street musicians and seasonal outdoor markets.",
        "tip_ja": "🛍️ 鉄道到着時の市内中心部へのアクセスルート。大型モール「Centrum Galerie」や円形映画館「Rundkino」があり、カフェのオープンテラスが賑わいます。",
        "tip_es": "🛍️ Excelente punto de entrada si llegas en tren; alberga grandes centros comerciales (Centrum Galerie) y amplias terrazas de cafeterías.",
        "tip_zh": "🛍️ 乘火车抵达主站后的首选城中通道；沿街汇聚 Centrum Galerie 等大型购物商场、圆顶影院与露天咖啡小憩区。",
        "tip_fr": "🛍️ Point d'entrée idéal en arrivant par la gare ; accueille les grands centres commerciaux (Centrum Galerie) et de magnifiques fontaines.",
        "tip_de": "🛍️ Beliebte Flaniermeile vom Hauptbahnhof mit den Einkaufszentren Centrum Galerie und Galerie Wiener Platz sowie gemütlichen Gastronomie-Außenbereichen.",
        "price_en": "Boulevard Access: Free",
        "price_ja": "通り散策無料",
        "price_es": "Acceso al bulevar: Gratis",
        "price_zh": "商业街漫步：免费",
        "price_fr": "Accès au boulevard : Gratuit",
        "price_de": "Fußgängerzone frei",
        "name_en": "Prager Straße (Pedestrian Shopping Boulevard)",
        "name_ja": "Prager Straße（プラーガー通り歩行者天国）",
        "name_es": "Prager Straße (Bulevar Peatonal Comercial)",
        "name_zh": "Prager Straße (普拉格商业步行街)",
        "name_fr": "Prager Straße (Boulevard Piéton Commerçant)",
        "name_de": "Prager Straße (Fußgängerzone)"
    },
    # dr_35
    {
        "id": "dr_35",
        "name": "Altmarkt-Galerie Dresden（アルトマルクト・ギャラリー・ショッピングモール）",
        "category": "Café & Bistro",
        "rating": "★4.6",
        "locationZone": "city",
        "lat": 51.0498, "lng": 13.7362,
        "kids": True, "rain": True, "shopping": True, "free": True, "family": True, "adult": True,
        "desc_en": "Vast indoor shopping center with over 200 stores and restaurants right on Altmarkt square, integrating historic facades with modern glass shopping arcades.",
        "desc_ja": "アルトマルクト広場に直結する200店舗以上を擁する市内最大級の全天候型ショッピングモール。歴史的ファサードとガラス張りの現代アーケードが融合した大複合施設。",
        "desc_es": "Gran centro comercial cubierto con más de 200 tiendas y restaurantes en la misma plaza Altmarkt, que combina fachadas históricas con pasajes comerciales modernos.",
        "desc_zh": "直通老市场广场的拥有200多家店铺与餐饮的德累斯顿市中心大型全天候购物中心，巧妙将历史建筑外墙与现代玻璃长廊融为一体。",
        "desc_fr": "Vaste centre commercial couvert comptant plus de 200 boutiques et restaurants sur la place Altmarkt, alliant façades historiques et galeries vitrées modernes.",
        "desc_de": "Großes überdachtes Einkaufszentrum direkt am Altmarkt mit über 200 Fachgeschäften, Restaurants und Dienstleistern auf drei Etagen.",
        "tip_en": "☕ Ideal refuge on rainy days for international shopping, Meissen porcelain souvenir buying, and regional Saxon cuisine at the extensive lower-level food court.",
        "tip_ja": "☕ 雨の日のショッピングやマイセン磁器の土産物選びに最適。地下のフードコートではザクセン風の郷土料理やスウィーツを手軽に味わえます。",
        "tip_es": "☕ Refugio perfecto en días de lluvia para comprar souvenirs de porcelana de Meissen y probar especialidades sajonas en su zona de restauración.",
        "tip_zh": "☕ 雨天选购迈森瓷器纪念品与国际品牌的理想温床；地下多功能美食广场汇聚丰富多元的萨克森地方小吃与餐馆。",
        "tip_fr": "☕ Refuge idéal les jours de pluie pour le shopping et l'achat de souvenirs en porcelaine de Meissen dans l'aire de restauration du sous-sol.",
        "tip_de": "☕ Perfekt bei Regenwetter zum Shoppen; im Untergeschoss bietet die Food-Lounge ein breites Gastronomieangebot von sächsisch bis international.",
        "price_en": "Mall Entry: Free",
        "price_ja": "館内入場無料",
        "price_es": "Entrada al centro: Gratis",
        "price_zh": "商场商圈：免费",
        "price_fr": "Entrée du centre : Gratuit",
        "price_de": "Eintritt frei",
        "name_en": "Altmarkt-Galerie Dresden (Shopping Mall)",
        "name_ja": "Altmarkt-Galerie Dresden（アルトマルクト・ギャラリー・ショッピングモール）",
        "name_es": "Altmarkt-Galerie Dresden (Centro Comercial Altmarkt)",
        "name_zh": "Altmarkt-Galerie Dresden (老市场长廊购物中心)",
        "name_fr": "Altmarkt-Galerie Dresden (Centre Commercial Altmarkt)",
        "name_de": "Altmarkt-Galerie Dresden"
    },
    # dr_36
    {
        "id": "dr_36",
        "name": "Kutscherschänke & Pulverturm an der Frauenkirche（聖母教会横の伝統居酒屋＆火薬塔レストラン）",
        "category": "Café & Bistro",
        "rating": "★4.7",
        "locationZone": "city",
        "lat": 51.0518, "lng": 13.7428,
        "kids": True, "rain": True, "shopping": False, "free": False, "family": True, "adult": True,
        "desc_en": "Two iconic historic themed taverns adjacent to Frauenkirche: Kutscherschänke serving Saxon rustic food, and Pulverturm set inside 16th-century fortress vaults with costumed waiters.",
        "desc_ja": "聖母教会の目の前に位置する人気の歴史的テーマレストラン群。素朴なザクセン郷土料理を味わえる「クッチァーシェンケ」と、16世紀の要塞火薬庫の地下穹窿で中世衣装の給仕がもてなす「プルヴァートゥルム（Pulverturm）」。",
        "desc_es": "Dos emblemáticas tabernas históricas junto a la Frauenkirche: Kutscherschänke (comida sajona rústica) y Pulverturm, ambientada en las bóvedas de un polvorín del siglo XVI.",
        "desc_zh": "圣母教堂旁两家极具特色的历史主题餐馆：提供地道萨克森农家菜的御者酒馆（Kutscherschänke）以及设于16世纪古堡火药库穹顶地窖内、身着中世纪服饰侍者服务火药塔餐馆（Pulverturm）。",
        "desc_fr": "Deux tavernes historiques emblématiques près de la Frauenkirche : Kutscherschänke pour la cuisine saxonne rustique, et Pulverturm située dans les voûtes de la poudrière du XVIe siècle.",
        "desc_de": "Erlebnisgastronomie am Neumarkt: Die rustikale Kutscherschänke und der historische Pulverturm an der Frauenkirche im Gewölbekeller des einstigen Festungspolverturms.",
        "tip_en": "🍖 Try the famous Saxon roast pork knuckle (Sächsischer Mutzbraten) or sauerbraten with red cabbage and potato dumplings, served with freshly tapped Radeberger Pilsner beer.",
        "tip_ja": "🍖 ザクセン風ポークロースト（Mutzbraten）や赤キャベツとジャガイモ団子を添えたザウアーブラーテンを、搾りたてのラーデベルガー・ピルスナー生ビールと共に堪能してください。",
        "tip_es": "🍖 Prueba el codillo de cerdo sajón roast (Mutzbraten) o el Sauerbraten con col lombarda y dumplings de patata, acompañado de cerveza Radeberger recien tirada.",
        "tip_zh": "🍖 强烈推荐招牌萨克森烤猪肉（Mutzbraten）或搭配紫甘蓝与马铃薯球的酸软炖牛肉（Sauerbraten），配上一杯冰镇 Radeberger 扎啤。",
        "tip_fr": "🍖 Dégustez le rôti de porc saxon (Mutzbraten) ou le Sauerbraten servi avec du chou rouge et des quenelles de pommes de terre, accompagné d'une bière Radeberger.",
        "tip_de": "🍖 Deftige sächsische Hausmannskost wie Dresdner Sauerbraten oder Mutzbraten im Gewölbekeller genießen, serviert mit frisch gezapftem Radeberger Pilsner.",
        "price_en": "Mains: €16–€28 / Draft Beer (0.5L): €5.50",
        "price_ja": "主菜: 16€〜28€ / 生ビール(0.5L): 5.50€",
        "price_es": "Platos: 16€–28€ / Cerveza (0,5L): 5,50€",
        "price_zh": "主菜：16-28 欧元 / 扎啤(0.5L)：5.50 欧元",
        "price_fr": "Plats : 16 €–28 € / Bière (0,5L) : 5,50 €",
        "price_de": "Hauptgerichte: 16 €–28 € / Pils (0,5l): 5,50 €",
        "name_en": "Kutscherschänke & Pulverturm an der Frauenkirche (Historic Saxon Taverns)",
        "name_ja": "Kutscherschänke & Pulverturm an der Frauenkirche（聖母教会横の伝統居酒屋＆火薬塔レストラン）",
        "name_es": "Kutscherschänke & Pulverturm (Tabernas Históricas de la Frauenkirche)",
        "name_zh": "Kutscherschänke & Pulverturm (圣母教堂御者酒馆与火药塔主题餐馆)",
        "name_fr": "Kutscherschänke & Pulverturm (Tavernes Historiques de la Frauenkirche)",
        "name_de": "Kutscherschänke & Pulverturm an der Frauenkirche"
    },
    # dr_37
    {
        "id": "dr_37",
        "name": "Sophienkeller im Taschenbergpalais（タッシェンベルク宮殿地下ゾフィエンケラー）",
        "category": "Café & Bistro",
        "rating": "★4.8",
        "locationZone": "city",
        "lat": 51.0522, "lng": 13.7361,
        "kids": True, "rain": True, "shopping": False, "free": False, "family": True, "adult": True,
        "desc_en": "Extravagant Baroque vault tavern in the basement of the 5-star Hotel Taschenbergpalais Kempinski, recreating the lavish 18th-century court feasts of Augustus the Strong.",
        "desc_ja": "高級ホテル「タッシェンベルク宮殿ケンピンスキー」の地下に広がる絢爛豪華なバロックテーマの地下レストラン。18世紀アウグスト強王時代の宮廷宮宴の雰囲気をそのまま再現。",
        "desc_es": "Extravagante taberna barroca en las bóvedas subterráneas del hotel de 5 estrellas Taschenbergpalais Kempinski, que recrea los suntuosos banquetes cortesanos del siglo XVIII.",
        "desc_zh": "位于五星级塔什博格宫凯宾斯基酒店地窖内的奢华巴洛克主题宫廷饭庄，完美再现18世纪强力王奥古斯特时期的传奇宫廷盛宴气氛。",
        "desc_fr": "Taverne baroque extravagante située dans les voûtes du Taschenbergpalais Kempinski, récréant les fastueux banquets de la cour d'Auguste le Fort au XVIIIe siècle.",
        "desc_de": "Prachtvolles Barock-Erlebnisrestaurant in den Gewölben des Taschenbergpalais gegenüber dem Zwinger, das das Lebensgefühl der Augusteischen Epoche spürbar macht.",
        "tip_en": "🏰 Dine inside a giant revolving carrousel seating area or a historic guild vault; jugglers, musicians, and costumed court entertainers perform at your table.",
        "tip_ja": "🏰 回転木馬風の円形回転テーブル席やギルド（職人組合）のVault席で食事が可能。中世の衣装を着た大道芸人や音楽師が各テーブルを訪れて宴を盛り上げます。",
        "tip_es": "🏰 Cena dentro de un tiovivo giratorio de madera o en las bóvedas de los gremios; malabaristas y músicos con trajes de época actúan entre las mesas.",
        "tip_zh": "🏰 可在旋转木马造型的圆桌或古老公会地窖内用餐；杂技演员、乐师与身着巴洛克华服的宫廷艺人会在桌旁穿梭表演。",
        "tip_fr": "🏰 Dînez dans un carrousel en bois tournant ou dans les voûtes des corporations ; des jongleurs et musiciens en costume animent le repas.",
        "tip_de": "🏰 Auf dem historischen Karussell oder im Zunftgewölbe speisen, während Gaukler, Barden und Hofköche für Unterhaltung an den Tischen sorgen.",
        "price_en": "Baroque Feast Mains: €18–€32 / Beer (0.5L): €5.80",
        "price_ja": "バロックコース・主菜: 18€〜32€ / 生ビール: 5.80€",
        "price_es": "Platos fiesta barroca: 18€–32€ / Cerveza: 5,80€",
        "price_zh": "宫廷盛宴主菜：18-32 欧元 / 啤酒：5.80 欧元",
        "price_fr": "Plats fête baroque : 18 €–32 € / Bière : 5,80 €",
        "price_de": "Barocke Hauptgerichte: 18 €–32 € / Bier (0,5l): 5,80 €",
        "name_en": "Sophienkeller im Taschenbergpalais (Baroque Court Vault Restaurant)",
        "name_ja": "Sophienkeller im Taschenbergpalais（タッシェンベルク宮殿地下ゾフィエンケラー）",
        "name_es": "Sophienkeller im Taschenbergpalais (Restaurante Bóveda Barroca)",
        "name_zh": "Sophienkeller im Taschenbergpalais (塔什博格宫巴洛克地下酒廊)",
        "name_fr": "Sophienkeller im Taschenbergpalais (Restaurant Vôute Baroque)",
        "name_de": "Sophienkeller im Taschenbergpalais"
    },
    # dr_38
    {
        "id": "dr_38",
        "name": "Dresdner Eierschecke & Stollen: Café Kreutzkamm & Coselpalais（ドレスデン名物アイアーシェッケ＆シュトレン）",
        "category": "Café & Bistro",
        "rating": "★4.8",
        "locationZone": "city",
        "lat": 51.0519, "lng": 13.7422,
        "kids": True, "rain": True, "shopping": True, "free": False, "family": True, "adult": True,
        "desc_en": "Famous pastry culture institutions in Dresden Old Town: Café Kreutzkamm (est. 1825) and Grand Café Coselpalais, celebrated for traditional Dresdner Eierschecke three-layer cake and Original Dresdner Christstollen.",
        "desc_ja": "1825年創業の老舗カフェ「カファ・クロイツカム」とバロック庭園に囲まれた「コーゼルパレー」。ドレスデン伝統の三層ケーキ「アイアーシェッケ（Eierschecke）」と最高峰の「ドレスドナー・シュトレン」の聖地。",
        "desc_es": "Instituciones de la repostería tradicional en el casco antiguo: Café Kreutzkamm (fundado en 1825) y Grand Café Coselpalais, célebres por el pastel de tres capas Eierschecke y el Stollen original.",
        "desc_zh": "老城名声赫赫的历史糕点名店：成立于1825年的克罗伊茨卡姆咖啡馆（Café Kreutzkamm）与科塞尔宫大咖啡馆，以传统三层金黄“鸡蛋雪克蛋糕（Eierschecke）”与正宗德累斯顿圣诞糖雪史多伦（Christstollen）名扬全德。",
        "desc_fr": "Institutions de la pâtisserie traditionnelle dans la vieille ville : Café Kreutzkamm (fondé en 1825) et Grand Café Coselpalais, réputés pour le gâteau à trois couches Eierschecke et le Stollen.",
        "desc_de": "Traditionelle Dresdner Kaffeehauskultur im Café Kreutzkamm (seit 1825 am Altmarkt) und im Grand Café im Coselpalais an der Frauenkirche, berühmt für Dresdner Eierschecke und Christstollen.",
        "tip_en": "🍰 Order the authentic Dresdner Eierschecke (three-layer cake with yeast base, cheesecake core, and fluffy egg-vanilla pudding top); Erich Kästner famously declared: 'The Eierschecke is a cake type that causes harm to humanity when withheld.'",
        "tip_ja": "🍰 クッキー生地・カッテージチーズ・ふわふわの卵泡バニラプリンの3層からなる伝統ケーキ「アイアーシェッケ」をコーヒーと共に注文。文豪エーリヒ・ケストナーも絶賛した逸品です。",
        "tip_es": "🍰 Pide la auténtica Dresdner Eierschecke (tarta de tres capas con base de levadura, queso y crema de huevo y vainilla); disfrútala con un café filtrado artesanal.",
        "tip_zh": "🍰 必点地道三层结构的德累斯顿鸡蛋雪克蛋糕（底面为发酵饼底、中间为芝士层、顶层为打发蛋黄香草奶油泡）；著名作家凯斯特纳曾盛赞其为“不能从人类手中剥夺的绝品糕点”。",
        "tip_fr": "🍰 Commandez l'authentique Dresdner Eierschecke (gâteau à trois couches avec base briochée, fromage blanc et mousse vanillée aux œufs) avec un café.",
        "tip_de": "🍰 Ein Stück dreischichtige Dresdner Eierschecke (Hefeteig, Quark, Eierschecken-Masse) mit einem Schälchen Heißen Kaffe genießen; im Winter echten Dresdner Christstollen probieren.",
        "price_en": "Eierschecke Slice: €4.50 / Coffee: €3.80 / Stollen Box: €18–€35",
        "price_ja": "アイアーシェッケ1片: 4.50€ / コーヒー: 3.80€ / シュトレン箱: 18€〜35€",
        "price_es": "Porción Eierschecke: 4,50€ / Café: 3,80€ / Caja Stollen: 18€–35€",
        "price_zh": "鸡蛋雪克切片：4.50 欧元 / 咖啡：3.80 欧元 / 史多伦礼盒：18-35 欧元",
        "price_fr": "Part d'Eierschecke : 4,50 € / Café : 3,80 € / Boîte Stollen : 18 €–35 €",
        "price_de": "Stück Eierschecke: 4,50 € / Tasse Kaffee: 3,80 € / Christstollen (1kg): 22 €",
        "name_en": "Dresdner Eierschecke & Stollen (Café Kreutzkamm & Coselpalais)",
        "name_ja": "Dresdner Eierschecke & Stollen: Café Kreutzkamm & Coselpalais（ドレスデン名物アイアーシェッケ＆シュトレン）",
        "name_es": "Café Kreutzkamm & Coselpalais (Especialidad Dresdner Eierschecke & Stollen)",
        "name_zh": "Café Kreutzkamm & Coselpalais (德累斯顿三层糕点与圣诞史多伦名店)",
        "name_fr": "Café Kreutzkamm & Coselpalais (Pâtisserie Dresdner Eierschecke & Stollen)",
        "name_de": "Dresdner Eierschecke & Stollen (Café Kreutzkamm & Coselpalais)"
    },
    # dr_39
    {
        "id": "dr_39",
        "name": "Yenidze（イェニツェ / 旧オリエンタル風タバコ工場）",
        "category": "Landmark",
        "rating": "★4.6",
        "locationZone": "city",
        "lat": 51.0592, "lng": 13.7268,
        "kids": False, "rain": True, "shopping": False, "free": False, "family": True, "adult": True,
        "desc_en": "Striking 1909 former cigarette factory designed in the style of a colorful Ottoman mosque, complete with a 62-meter glass dome and minaret-shaped exhaust chimneys.",
        "desc_ja": "1909年に建設されたオリエンタルモスク風の旧タバコ工場。高さ62mのカラフルなステンドグラスドームとミナレット（光塔）の形をした煙突を持つ、建築規制を回避するための独創的デザイン。",
        "desc_es": "Sorprendente antigua fábrica de cigarrillos de 1909 diseñada al estilo de una mezquita otomana, con una cúpula de cristal de 62 metros y chimeneas con forma de minarete.",
        "desc_zh": "建造于1909年的前卷烟工厂建筑奇观，外部被设计成带有62米高彩色玻璃圆顶与宣礼塔造型烟囱的奥斯曼伊斯兰清真寺外观，旨在绕过当时市区工厂烟囱的建造限制。",
        "desc_fr": "Déroutante ancienne manufacture de cigarettes de 1909 conçue dans le style d'une mosquée ottomane, avec un dôme en verre de 62 mètres et des cheminées en forme de minarets.",
        "desc_de": "Ehemaliges Zigarettenfabrikgebäude von 1909 im ostasiatisch-orientalischen Moscheestil mit 62 Meter hoher verglaster Kuppel und als Minarette getarnten Schornsteinen.",
        "tip_en": "🕌 Ride the elevator to the glass dome top for the 'Kuppelrestaurant' (Dome Restaurant) and open-air rooftop terrace offering 360-degree panorama of Dresden's Elbe skyline.",
        "tip_ja": "🕌 エレベーターでステンドグラスドーム直下のドームレストラン（Kuppelrestaurant）と屋上テラスへ登ると、ドレスデンの旧市街とエルベ川を360度見渡す隠れた穴場展望台となります。",
        "tip_es": "🕌 Sube en ascensor a la cúpula de cristal para visitar el restaurante de la cúpula y su terraza panorámica de 360 grados sobre el perfil urbano de Dresde.",
        "tip_zh": "🕌 可直升至玻璃圆顶顶层的“圆顶全景餐厅（Kuppelrestaurant）”与露天观景台，360度无死角俯瞰德累斯顿老城与易北河天际线。",
        "tip_fr": "🕌 Prenez l'ascenseur jusqu'au dôme en verre pour accéder au restaurant et à la terrasse panoramique à 360° offrant une vue imprenable sur Dresde.",
        "tip_de": "🕌 Mit dem Fahrstuhl unter die bunte Glaskuppel zum Kuppelrestaurant fahren; die Dachterrasse bietet einen einzigartigen 360-Grad-Blick über Dresdens Altstadt.",
        "price_en": "Rooftop Terrace Access: Free / Restaurant Dining Variable",
        "price_ja": "屋上テラス見学無料 / レストラン飲食代実費",
        "price_es": "Acceso a la terraza: Gratis",
        "price_zh": "屋顶露台观景：免费",
        "price_fr": "Accès à la terrasse : Gratuit",
        "price_de": "Zugang zur Dachterrasse frei",
        "name_en": "Yenidze (Former Mosque-Style Tobacco Factory)",
        "name_ja": "Yenidze（イェニツェ / 旧オリエンタル風タバコ工場）",
        "name_es": "Yenidze (Antigua Fábrica de Tabacos de Estilo Oriental)",
        "name_zh": "Yenidze (耶尼采清真寺风旧卷烟厂建筑)",
        "name_fr": "Yenidze (Ancienne Manufacture de Tabac de Style Oriental)",
        "name_de": "Yenidze (Tabakmoschee)"
    },
    # dr_40
    {
        "id": "dr_40",
        "name": "Lingnerstadt & Blüherpark（リングナーシュタット＆ブリューアー公園）",
        "category": "Scenery & Walk",
        "rating": "★4.6",
        "locationZone": "city",
        "lat": 51.0438, "lng": 13.7485,
        "kids": True, "rain": False, "shopping": False, "free": True, "family": True, "adult": True,
        "desc_en": "Peaceful central parklands surrounding the Deutsches Hygiene-Museum, featuring historic 18th-century Baroque gardens, lime tree avenues, and modern urban recreation spaces.",
        "desc_ja": "ドイツ衛生博物館を包み込む緑豊かな中央都市公園。18世紀のバロック庭園遺構（ブリューアー公園）と菩提樹の並木道、近代的なスポーツ・市民憩いの広場からなる。",
        "desc_es": "Tranquilo parque central que rodea el Museo Alemán de la Higiene, con jardines barrocos del siglo XVIII, avenidas de tilos y espacios de recreo urbano.",
        "desc_zh": "环绕德国卫生博物馆的清幽市中心城市公园绿地，保存有18世纪巴洛克式园林遗迹（Blüherpark）、椴树绿荫步道与现代都市休闲绿洲。",
        "desc_fr": "Paisible parc central entourant le Musée Allemand de l'Hygiène, doté de jardins baroques du XVIIIe siècle, d'allées de tilleuls et d'espaces de loisirs.",
        "desc_de": "Parkanlage südlich des Pirnaischen Platzes rund um das Hygiene-Museum, bestehend aus dem historischen Blüherpark mit Barockskulpturen und dem Lingnerplatz.",
        "tip_en": "🌳 Great relaxing green break between visiting Hygiene-Museum and Großer Garten; features shaded walking paths, sculpture fountains, and children's playgrounds.",
        "tip_ja": "🌳 ドイツ衛生博物館見学後の休憩や、グローサー・ガルテンへの散策途中の緑のオアシス。木陰のベンチや彫刻噴水があり、静かに過ごしたい旅行者におすすめ。",
        "tip_es": "🌳 Estupendo descanso verde entre el Museo de la Higiene y el Großer Garten; cuenta con paseos a la sombra, fuentes escultóricas y zonas infantiles.",
        "tip_zh": "🌳 参观卫生博物馆与漫步大花园之间的惬意绿色休憩站；分布着树荫步道、喷泉雕塑与儿童游乐绿地。",
        "tip_fr": "🌳 Excellente pause verdure entre le musée de l'Hygiène et le Großer Garten ; comprend des sentiers ombragés et des fontaines sculpteés.",
        "tip_de": "🌳 Schöner grüner Verbindungsweg zwischen Altstadt und Großem Garten mit alten Baumbeständen, Brunnen und Spielplätzen.",
        "price_en": "Park Access: Free",
        "price_ja": "公園散策無料",
        "price_es": "Acceso al parque: Gratis",
        "price_zh": "公园园区：免费",
        "price_fr": "Accès au parc : Gratuit",
        "price_de": "Park frei",
        "name_en": "Lingnerstadt & Blüherpark (Central City Park)",
        "name_ja": "Lingnerstadt & Blüherpark（リングナーシュタット＆ブリューアー公園）",
        "name_es": "Lingnerstadt & Blüherpark (Parque Central Blüherpark)",
        "name_zh": "Lingnerstadt & Blüherpark (林格纳城与布吕尔公园)",
        "name_fr": "Lingnerstadt & Blüherpark (Parc Central Blüherpark)",
        "name_de": "Lingnerstadt & Blüherpark"
    }
]

with open("scripts/build_dresden_spots.py", "r", encoding="utf-8") as f:
    content = f.read()

import re

# Insert dr_27_to_40 right before "# dr_41"
split_marker = "        # dr_41"
if split_marker in content:
    parts = content.split(split_marker)
    
    # format dr_27_to_40 list entries to string without brackets
    import json
    formatted_entries = []
    for spot in dr_27_to_40:
        spot_str = "        " + json.dumps(spot, ensure_ascii=False, indent=12).replace("\n", "\n        ")
        formatted_entries.append(f"        # {spot['id']}\n{spot_str}")
        
    inserted_text = ",\n".join(formatted_entries) + ",\n"
    
    new_content = parts[0] + inserted_text + split_marker + parts[1]
    
    with open("scripts/build_dresden_spots.py", "w", encoding="utf-8") as f:
        f.write(new_content)
    print("Successfully patched build_dresden_spots.py with dr_27 to dr_40!")
else:
    print("Marker # dr_41 not found!")
