import json

toulouse_data = {
  "cityKey": "toulouse",
  "cityName": "Toulouse, France",
  "country": "France",
  "spots": [
    # 🏛️ LANDMARKS - CITY
    {
      "id": "to_1",
      "name": "Place du Capitole & Capitole de Toulouse",
      "category": "Landmark",
      "rating": "★4.7",
      "locationZone": "city",
      "price": "Free square / €5 tour",
      "wikipediaTitle": "Capitole de Toulouse",
      "desc_en": "Iconic pink-brick central square flanked by 18th-century neoclassical Capitole palace housing Salle Henri-Martin frescoes.",
      "desc_ja": "18世紀新古典主義の市庁舎が建つピンクレンガの表広場。アンリ・マルタンの間の壁画群が見どころ。",
      "desc_es": "Icónica plaza central de ladrillos rosados con el palacio neoclásico del Capitole del siglo XVIII.",
      "desc_zh": "粉红砖砌成的市中心标志性广场，周围环绕着18世纪新古典主义风格的市政厅府邸。",
      "desc_fr": "Grand-place emblématique en briques roses bordée par le palais néoclassique du Capitole du XVIIIe siècle.",
      "desc_de": "Ikonischer zentraler Platz aus rosafarbenen Backsteinen mit dem neoklassizistischen Capitole-Palast.",
      "tip_en": "Visit Salle Henri-Martin inside the Capitole for stunning historical frescoes.",
      "tip_ja": "市庁舎内部の「アンリ・マルタンの間」のフレスコ画は無料で見学可能です。",
      "tip_es": "Visita la Salle Henri-Martin dentro del Capitole para admirar sus magníficos frescos.",
      "tip_zh": "务必前往市政厅内部的 Salle Henri-Martin 欣赏壮丽的壁画艺术。",
      "tip_fr": "Ne manquez pas la Salle Henri-Martin à l’intérieur du Capitole pour ses magnifiques fresques.",
      "tip_de": "Besuchen Sie den Salle Henri-Martin im Capitole für seine beeindruckenden Wandgemälde."
    },
    {
      "id": "to_2",
      "name": "Basilique Saint-Sernin",
      "category": "Landmark",
      "rating": "★4.7",
      "locationZone": "city",
      "price": "Free entry / €2.50 crypt",
      "wikipediaTitle": "Basilique Saint-Sernin, Toulouse",
      "desc_en": "UNESCO World Heritage Romanesque basilica on Saint James Way, largest remaining Romanesque church in Europe.",
      "desc_ja": "サンティアゴ巡礼路上にある世界遺産。西欧に現存する最大級の壮麗なロマネスク様式バシリカ。",
      "desc_es": "Basílica románica Patrimonio de la Humanidad en el Camino de Santiago, la iglesia románica más grande de Europa.",
      "desc_zh": "圣雅各朝圣之路上的世界文化遗产，也是欧洲现存规模最大的罗曼式大教堂。",
      "desc_fr": "Basilique romane inscrite à l’UNESCO sur le chemin de Compostelle, la plus grande église romane conservée en Europe.",
      "desc_de": "UNESCO-Weltkulturerbe-Basilika am Jakobsweg, die größte erhaltene romanische Kirche Europas.",
      "tip_en": "Explore the crypt underneath to see ancient reliquaries.",
      "tip_ja": "地下聖堂（クリプト）には貴重な聖遺物箱が安置されています。",
      "tip_es": "Explora la cripta subterránea para ver antiguos relicarios.",
      "tip_zh": "建议游览地下圣堂，观赏珍贵的圣物箱。",
      "tip_fr": "Explorez la crypte située sous le chœur pour y découvrir les précieux reliquaires.",
      "tip_de": "Erkunden Sie die Krypta unter dem Chor mit ihren historischen Reliquien."
    },
    {
      "id": "to_3",
      "name": "Couvent des Jacobins",
      "category": "Landmark",
      "rating": "★4.7",
      "locationZone": "city",
      "price": "Free church / €5 cloister",
      "wikipediaTitle": "Church of the Jacobins, Toulouse",
      "desc_en": "Masterpiece of Southern French Gothic architecture featuring famed palm-tree vaulted ceiling and serene cloister.",
      "desc_ja": "南仏ゴシックの最高峰。1本の柱から22本のリブが広がる「ヤシの木」ヴォールト天井と静謐な回廊。",
      "desc_es": "Obra maestra del gótico meridional con su famosa bóveda en forma de palmera y su sereno claustro.",
      "desc_zh": "南法哥特式建筑的巅峰之作，以形似棕榈树的肋架拱顶与宁静的回廊闻名。",
      "desc_fr": "Chef-d’œuvre du gothique méridional célèbre pour son voûtement en palmier à 22 nervures et son cloître paisible.",
      "desc_de": "Meisterwerk der südfranzösischen Gotik mit dem berühmten Palmen-Rippengewölbe und ruhigen Kreuzgang.",
      "tip_en": "Look at the central pillar mirror to view the double palm vault ceiling effortlessly.",
      "tip_ja": "柱の足元にある鏡を覗き込むと、首を痛めずにヤシの木天井を観賞できます。",
      "tip_es": "Mira el espejo en la base del pilar para admirar la bóveda sin forzar el cuello.",
      "tip_zh": "可以通过立柱基部的镜子轻松仰望壮丽的棕榈树拱顶。",
      "tip_fr": "Regardez le miroir placé au pied du pilier pour admirer la voûte sans vous fatiguer le cou.",
      "tip_de": "Nutzen Sie den Spiegel am Pfeilerfuß, um das Palmengewölbe entspannt zu betrachten."
    },
    {
      "id": "to_4",
      "name": "Pont Neuf Toulouse",
      "category": "Landmark",
      "rating": "★4.6",
      "locationZone": "city",
      "price": "Free access",
      "wikipediaTitle": "Pont Neuf, Toulouse",
      "desc_en": "Historic 16th-century stone bridge spanning Garonne river with flood-resisting asymmetrical arches.",
      "desc_ja": "16〜17世紀にガロンヌ川に架けられた市内最古の石橋。洪水対策の水抜き穴を持つ堅固な建造物。",
      "desc_es": "Histórico puente de piedra del siglo XVI sobre el río Garona con arcos asimétricos resistentes a inundaciones.",
      "desc_zh": "跨越加龙河的16世纪历史石桥，拥有防御洪水的非对称拱门设计。",
      "desc_fr": "Pont en pierre historique du XVIe siècle enjambant la Garonne avec des arches asymétriques anti-crue.",
      "desc_de": "Historische Steinbrücke aus dem 16. Jahrhundert über die Garonne mit hochwassersicheren Bögen.",
      "tip_en": "Best sunset views over the Garonne river and pink brick city skyline.",
      "tip_ja": "ドラード河岸側からの夕日と石橋のコラボレーションは絶景です。",
      "tip_es": "Excelente punto para contemplar el atardecer sobre el río Garona.",
      "tip_zh": "傍晚在河岸旁欣赏落日与加龙河石桥是绝佳体验。",
      "tip_fr": "Point de vue parfait pour admirer le coucher de soleil sur la Garonne.",
      "tip_de": "Ideal für den Sonnenuntergang über der Garonne und der rosa Stadt."
    },
    {
      "id": "to_5",
      "name": "Cathédrale Saint-Étienne de Toulouse",
      "category": "Landmark",
      "rating": "★4.6",
      "locationZone": "city",
      "price": "Free entry",
      "wikipediaTitle": "Toulouse Cathedral",
      "desc_en": "Unique hybrid cathedral combining Romanesque nave and Gothic choir merged in an asymmetrical layout.",
      "desc_ja": "ロマネスク様式の身廊とゴシック様式の内陣が変則的に結合したユニークな大聖堂。",
      "desc_es": "Catedral híbrida única que combina una nave románica con un coro gótico en un diseño asimétrico.",
      "desc_zh": "独一无二的混合风格大教堂，融合了罗曼式饰廊与哥特式圣坛。",
      "desc_fr": "Cathédrale atypique mariant une nef romane et un chœur gothique dans un ensemble asymétrique.",
      "desc_de": "Einzigartige Kathedrale, die ein romanisches Langhaus mit einem gotischen Chor verbindet.",
      "tip_en": "Notice the unusual shift in axis between the Romanesque nave and Gothic choir.",
      "tip_ja": "身廊と内陣の中心軸が斜めにズレている建築美に注目してください。",
      "tip_es": "Observa el curioso desvío de eje entre la nave románica y el coro gótico.",
      "tip_zh": "注意观察罗曼式主廊与哥特圣坛之间交错的独特轴线。",
      "tip_fr": "Remarquez le décalage d’axe fascinant entre la nef romane et le chœur gothique.",
      "tip_de": "Achten Sie auf den ungewöhnlichen Achsenversatz zwischen Schiff und Chor."
    },
    {
      "id": "to_6",
      "name": "Hôtel d'Assézat",
      "category": "Landmark",
      "rating": "★4.7",
      "locationZone": "city",
      "price": "Free courtyard / €10 museum",
      "wikipediaTitle": "Hôtel d'Assézat",
      "desc_en": "Splendid 16th-century Renaissance mansion built by woad dye merchant, housing Bemberg Foundation art.",
      "desc_ja": "16世紀のパステル（青色染料）貿易で富を築いた豪商のルネサンス大邸宅。バンベルグ財団美術館を併設。",
      "desc_es": "Espléndida mansión renacentista del siglo XVI construida por un comerciante de glasto, sede de la Fundación Bemberg.",
      "desc_zh": "16世纪富商建立的文艺复兴式宅邸，如今作为班贝格基金会艺术馆使用。",
      "desc_fr": "Hôtel particulier Renaissance du XVIe siècle bâti par un négociant de pastel, abritant la Fondation Bemberg.",
      "desc_de": "Prachtvolles Renaissance-Palais aus dem 16. Jahrhundert, heute Sitz der Fondation Bemberg.",
      "tip_en": "Enter the courtyard freely to admire the classic French Renaissance columns.",
      "tip_ja": "中庭までは入場無料。ルネサンス柱廊の壮麗な彫刻を楽しめます。",
      "tip_es": "Entra gratis al patio para contemplar las elegantes columnas renacentistas.",
      "tip_zh": "庭院免费开放，可以欣赏精美绝伦的文艺复兴式柱廊。",
      "tip_fr": "L’accès à la cour intérieure est libre pour admirer l’architecture Renaissance.",
      "tip_de": "Der Innenhof ist frei zugänglich und zeigt klassische Renaissance-Architektur."
    },
    {
      "id": "to_7",
      "name": "Chapelle des Carmélites",
      "category": "Landmark",
      "rating": "★4.7",
      "locationZone": "city",
      "price": "Free entry",
      "wikipediaTitle": "Chapelle des Carmélites de Toulouse",
      "desc_en": "Hidden 17th-century chapel featuring breathtaking painted wooden ceilings, nicknamed Toulouse's Sistine Chapel.",
      "desc_ja": "17世紀の天井画と壁画が全面を覆い、「トゥールーズのシスティーナ礼拝堂」と称される隠れた名所。",
      "desc_es": "Capilla oculta del siglo XVII con techos de madera pintados, apodada la Capilla Sixtina de Toulouse.",
      "desc_zh": "隐藏于市区的17世纪礼拜堂，绘满精美木质天井画，被称为“图卢兹的西斯廷礼拜堂”。",
      "desc_fr": "Joyau caché du XVIIe siècle recouvert de peints sur bois, surnommé la Chapelle Sixtine toulousaine.",
      "desc_de": "Versteckte Kapelle aus dem 17. Jahrhundert mit bemalten Holzdecken, genannt die Sixtinische Kapelle von Toulouse.",
      "tip_en": "Quiet hidden gem with free entry right near Saint-Sernin.",
      "tip_ja": "サン・セルナン大聖堂近くの静かな隠れスポット。無料で見学可能です。",
      "tip_es": "Gema oculta muy tranquila con entrada gratuita cerca de Saint-Sernin.",
      "tip_zh": "位于圣塞尔南大教堂附近的静谧秘境，免费供公众参观。",
      "tip_fr": "Havre de paix gratuit idéalement situé à quelques pas de Saint-Sernin.",
      "tip_de": "Ein ruhiger Geheimtipp mit freiem Eintritt unweit von Saint-Sernin."
    },
    {
      "id": "to_8",
      "name": "Hôtel-Dieu Saint-Jacques",
      "category": "Landmark",
      "rating": "★4.6",
      "locationZone": "city",
      "price": "Free exterior",
      "wikipediaTitle": "Hôtel-Dieu Saint-Jacques",
      "desc_en": "12th-century UNESCO World Heritage hospital complex along Garonne river with striking night illumination.",
      "desc_ja": "ガロンヌ川沿いに建つ12世紀起源の世界遺産旧病院。夜間のライトアップと川面に映る姿が美しい。",
      "desc_es": "Complejo hospitalario Patrimonio de la Humanidad del siglo XII junto al Garona con iluminación nocturna.",
      "desc_zh": "加龙河畔的12世纪世界遗产旧医院，夜间灯光映照于水面十分绚丽。",
      "desc_fr": "Ancien hôpital du XIIe siècle classé à l’UNESCO au bord de la Garonne, magnifique illuminé la nuit.",
      "desc_de": "UNESCO-Weltkulturerbe-Spitalkomplex aus dem 12. Jahrhundert an der Garonne.",
      "tip_en": "Cross to Pont Saint-Pierre at dusk for the best panoramic photos.",
      "tip_ja": "夕暮れ時にポン・サン・ピエール橋から撮影するのが最高のビューポイントです。",
      "tip_es": "Cruza al Pont Saint-Pierre al atardecer para capturar las mejores fotos.",
      "tip_zh": "傍晚前往 Pont Saint-Pierre 桥上是捕捉全景照片的最佳角度。",
      "tip_fr": "Traversez le Pont Saint-Pierre au crépuscule pour la meilleure vue panoramique.",
      "tip_de": "Überqueren Sie bei Dämmerung die Pont Saint-Pierre für das beste Panorama."
    },
    {
      "id": "to_9",
      "name": "Cité de Carcassonne",
      "category": "Landmark",
      "rating": "★4.8",
      "locationZone": "suburban",
      "price": "Free citadel / €9.50 castle",
      "wikipediaTitle": "Cité de Carcassonne",
      "desc_en": "Iconic UNESCO World Heritage medieval fortified city with 52 towers and double ring walls (Day Trip).",
      "desc_ja": "二重の城壁と52の塔を持つ欧州最大級の中世城塞都市（世界遺産 / トゥールーズから日帰り圏）。",
      "desc_es": "Ciudad medieval fortificada Patrimonio de la Humanidad con 52 torres y murallas dobles (Excursión).",
      "desc_zh": "拥有52座塔楼与双重城墙的世界遗产中世城堡都市（一日游推荐）。",
      "desc_fr": "Cité médiévale fortifiée classée à l’UNESCO avec 52 tours et une double enceinte (Excursion d’un jour).",
      "desc_de": "Weltberühmte UNESCO-Mittelalterfestung mit 52 Türmen und doppelter Stadtmauer (Tagesausflug).",
      "tip_en": "45 minutes by train from Toulouse Matabiau station.",
      "tip_ja": "トゥールーズ・マナビオ駅からTER列車で約45分でアクセス可能です。",
      "tip_es": "A solo 45 minutos en tren desde la estación de Toulouse Matabiau.",
      "tip_zh": "从图卢兹 Matabiau 火车站乘坐火车约45分钟直达。",
      "tip_fr": "Accessible en 45 minutes de train TER depuis la gare de Toulouse-Matabiau.",
      "tip_de": "In nur 45 Zugminuten vom Bahnhof Toulouse Matabiau aus erreichbar."
    },
    {
      "id": "to_10",
      "name": "Cité Épiscopale d'Albi & Cathédrale Sainte-Cécile",
      "category": "Landmark",
      "rating": "★4.8",
      "locationZone": "suburban",
      "price": "Free cathedral / €10 Lautrec museum",
      "wikipediaTitle": "Albi Cathedral",
      "desc_en": "UNESCO World Heritage red-brick episcopal city dominated by world's largest brick cathedral & Toulouse-Lautrec museum.",
      "desc_ja": "赤レンガ造りとしては世界最大の要塞型大聖堂（世界遺産）とロートレック美術館（日帰り圏）。",
      "desc_es": "Ciudad episcopal Patrimonio de la Humanidad con la catedral de ladrillo más grande del mundo (Excursión).",
      "desc_zh": "红砖建造的世界最大堡垒式大教堂及罗特列克美术馆（日游推荐）。",
      "desc_fr": "Cité épiscopale de briques en réseau UNESCO dominée par la plus grande cathédrale de briques au monde.",
      "desc_de": "UNESCO-Weltkulturerbe-Bischofsstadt mit der größten Backsteinkathedrale der Welt.",
      "tip_en": "1 hour by train from Toulouse, don't miss the Toulouse-Lautrec Museum in Berbie Palace.",
      "tip_ja": "トゥールーズから電車の旅で1時間。バルビー宮殿内のロートレック美術館は必見。",
      "tip_es": "A 1 hora en tren desde Toulouse, no te pierdas el Museo Toulouse-Lautrec.",
      "tip_zh": "乘火车1小时可达，千万不要错过帕比宫内的罗特列克艺术馆。",
      "tip_fr": "À 1 heure en train, ne manquez pas le musée Toulouse-Lautrec au palais de la Berbie.",
      "tip_de": "1 Stunde mit dem Zug entfernt, besuchen Sie das Toulouse-Lautrec Museum."
    },

    # 🎨 MUSEUMS - CITY & SUBURBAN
    {
      "id": "to_11",
      "name": "Musée des Augustins",
      "category": "Museum & Art",
      "rating": "★4.6",
      "locationZone": "city",
      "price": "€6–€8",
      "wikipediaTitle": "Musée des Augustins",
      "desc_en": "Fine arts museum set in a 14th-century Augustinian convent featuring medieval Romanesque sculptures.",
      "desc_ja": "14世紀の旧修道院を利用した名門美術館。中世の柱頭彫刻群およびフランス絵画の名品を収蔵。",
      "desc_es": "Museo de bellas artes en un convento agustino del siglo XIV con esculturas románicas medievales.",
      "desc_zh": "设立于14世纪奥古斯丁修道院旧址的名画美术馆，收藏珍贵的中世纪罗曼式雕塑。",
      "desc_fr": "Musée des beaux-arts dans un couvent augustin du XIVe siècle réputé pour sa sculpture romane.",
      "desc_de": "Kunstmuseum in einem Augustinerkloster aus dem 14. Jahrhundert mit mittelalterlicher Skulpturensammlung.",
      "tip_en": "Stroll through the tranquil Gothic cloister and gargoyle garden.",
      "tip_ja": "ゴシック様式の回廊とガーゴイルが飾られた庭園を散策してください。",
      "tip_es": "Pasea por el tranquilo claustro gótico y el jardín de gárgolas.",
      "tip_zh": "可以在静谧的哥特式回廊和兽首雕塑庭院中漫步。",
      "tip_fr": "Promenez-vous dans le calme du cloître gothique et son jardin de gargouilles.",
      "tip_de": "Flanieren Sie durch den gotischen Kreuzgang und den Garten mit Wasserspeiern."
    },
    {
      "id": "to_12",
      "name": "Fondation Bemberg",
      "category": "Museum & Art",
      "rating": "★4.7",
      "locationZone": "city",
      "price": "€10",
      "wikipediaTitle": "Fondation Bemberg",
      "desc_en": "Prestigious private art collection inside Hôtel d'Assézat featuring Renaissance & Impressionist masters (Bonnard, Monet, Matisse).",
      "desc_ja": "アセザ館内のプライベートコレクション。ルネサンス絵画からボナール、モネ、マティス等の名作群。",
      "desc_es": "Colección privada de arte en el Hôtel d'Assézat con maestros del Renacimiento e Impresionistas.",
      "desc_zh": "位于阿塞扎大宅内的顶尖私家艺术馆，展出文艺复兴与印象派大师画作。",
      "desc_fr": "Prestigieuse collection privée au sein de l’Hôtel d’Assézat exposant Bonnard, Monet et Matisse.",
      "desc_de": "Renommierte Kunstsammlung im Hôtel d'Assézat mit Meisterwerken von Monet, Bonnard und Matisse.",
      "tip_en": "Features one of Europe's finest permanent collections of Pierre Bonnard paintings.",
      "tip_ja": "ピエール・ボナールの常設絵画コレクションは欧州有数の規模を誇ります。",
      "tip_es": "Alberga una de las mejores colecciones permanentes de obras de Pierre Bonnard.",
      "tip_zh": "拥有欧洲规模最大的皮埃尔·博纳尔常设画作收藏之一。",
      "tip_fr": "Abrite l’une des plus remarquables collections permanentes de tableaux de Pierre Bonnard.",
      "tip_de": "Besitzt eine der bedeutendsten Sammlungen von Werken Pierre Bonnards."
    },
    {
      "id": "to_13",
      "name": "Les Abattoirs, Musée - Frac Occitanie Toulouse",
      "category": "Museum & Art",
      "rating": "★4.5",
      "locationZone": "city",
      "price": "€9",
      "wikipediaTitle": "Les Abattoirs",
      "desc_en": "Modern and contemporary art museum housed in converted 19th-century slaughterhouses featuring Picasso's giant stage curtain.",
      "desc_ja": "19世紀の旧屠殺場を改装した現代美術館。ピカソの巨大舞台幕『ミノタウロスのミノセルクス』を所蔵。",
      "desc_es": "Museo de arte moderno y contemporáneo en antiguos mataderos del siglo XIX con el telón monumental de Picasso.",
      "desc_zh": "由19世纪旧屠宰场改建的当代艺术馆，藏有毕加索巨大的巨型舞台幕布作品。",
      "desc_fr": "Musée d’art moderne et contemporain dans d’anciens abattoirs du XIXe conservant le monumental rideau de Picasso.",
      "desc_de": "Museum für moderne und zeitgenössische Kunst in ehemaligen Schlachthöfen aus dem 19. Jahrhundert.",
      "tip_en": "Check if Picasso's fragile giant curtain is currently on exhibition in the lower gallery.",
      "tip_ja": "ピカソの巨大幕は保存のため期間限定で特別展示されます。",
      "tip_es": "Comprueba si el monumental telón de Picasso está expuesto durante tu visita.",
      "tip_zh": "毕加索的巨幅幕布作品因保护限制，会在特定时期对外特别陈列。",
      "tip_fr": "Vérifiez si l’immense rideau de scène de Picasso est actuellement visible en galerie.",
      "tip_de": "Prüfen Sie, ob Picassos riesiger Bühnenvorhang aktuell ausgestellt ist."
    },
    {
      "id": "to_14",
      "name": "Musée Saint-Raymond",
      "category": "Museum & Art",
      "rating": "★4.6",
      "locationZone": "city",
      "price": "€5",
      "wikipediaTitle": "Musée Saint-Raymond",
      "desc_en": "Archaeological museum next to Saint-Sernin featuring impressive collection of Roman marble busts & mythological reliefs.",
      "desc_ja": "サン・セルナン大聖堂隣接の考古学博物館。古代ローマのヴィラから出土した彫刻や大理石胸像群。",
      "desc_es": "Museo arqueológico junto a Saint-Sernin con una impresionante colección de bustos romanos de mármol.",
      "desc_zh": "毗邻圣塞尔南大教堂的考古博物馆，集中展示古代罗马时期的理石胸像与大理石雕塑。",
      "desc_fr": "Musée d’archéologie jouxtant Saint-Sernin présentant d’exceptionnels portraits en marbre romains.",
      "desc_de": "Archäologisches Museum neben Saint-Sernin mit römischen Marmorbüsten und Reliefs.",
      "tip_en": "Don't miss the famous Roman marble busts discovered at the Chiragan Villa.",
      "tip_ja": "チラガン・ヴィラ遺跡から発見された皇帝たちの大理石胸像群は必見。",
      "tip_es": "No te pierdas los famosos bustos románicos de mármol de la Villa Chiragan.",
      "tip_zh": "绝不能错过在 Chiragan 别遗址发掘出的古罗马皇帝大理石胸像。",
      "tip_fr": "Admirez les célèbres bustes d’empereurs romains mis au jour à la villa de Chiragan.",
      "tip_de": "Verpassen Sie nicht die römischen Büsten aus der Villa Chiragan."
    },
    {
      "id": "to_15",
      "name": "Muséum de Toulouse",
      "category": "Museum & Art",
      "rating": "★4.6",
      "locationZone": "city",
      "price": "€9 (Includes Botanical Garden)",
      "wikipediaTitle": "Muséum de Toulouse",
      "desc_en": "France's second-largest natural history museum featuring interactive palaeontology & ethnography exhibits linked to Botanical Gardens.",
      "desc_ja": "パリに次ぐ規模を誇る自然史博物館。植物園に隣接し古生物・人類学のインタラクティブ展示が充実。",
      "desc_es": "El segundo museo de historia natural más grande de Francia con exposiciones interactivas junto al Jardín Botánico.",
      "desc_zh": "规模仅次于巴黎的法国第二大自然历史博物馆，结合植物园提供丰富互动展。",
      "desc_fr": "Deuxième muséum d’histoire naturelle de France avec des galeries interactives jouxtant le Jardin botanique.",
      "desc_de": "Zweitgrößtes Naturhistorisches Museum Frankreichs mit interaktiven Ausstellungen.",
      "tip_en": "Great combined visit with the lush Jardin des Plantes outdoors.",
      "tip_ja": "隣接するグラン・ロン植物園公園での散策と組み合わせるのがおすすめです。",
      "tip_es": "Excelente combinación para visitar junto con el Jardín de las Plantas.",
      "tip_zh": "适合与紧邻的植物园相结合安排一段舒适的半日游行程。",
      "tip_fr": "Combo parfait avec la promenade dans le Jardin des Plantes adjacent.",
      "tip_de": "Perfekt kombinierbar mit einem Spaziergang im angrenzenden Jardin des Plantes."
    },
    {
      "id": "to_16",
      "name": "Musée Paul-Dupuy",
      "category": "Museum & Art",
      "rating": "★4.5",
      "locationZone": "city",
      "price": "€5",
      "wikipediaTitle": "Musée Paul-Dupuy",
      "desc_en": "Decorative arts and horology museum inside a 17th-century townhouse featuring medieval crafts & automaton clocks.",
      "desc_ja": "17世紀の館内にある装飾芸術・時計博物館。中世の工芸品から精密なオートマタ（自動人形）まで展示。",
      "desc_es": "Museo de artes decorativas y Relojería en una casona del siglo XVII con autómatas y piezas medievales.",
      "desc_zh": "设立于17世纪宅邸内的装饰艺术与钟表博物馆，展出中世纪工艺品与精密自动机械人形。",
      "desc_fr": "Musée des arts décoratifs et de l’horlogerie abritant d’anciens automates et objets précieux.",
      "desc_de": "Museum für Angewandte Kunst und Uhrenkunst in einem Stadtpalais aus dem 17. Jahrhundert.",
      "tip_en": "Fascinating collection of intricate 18th & 19th-century mechanical clocks.",
      "tip_ja": "18〜19世紀の複雑で美しいからくり時計のコレクションが充実しています。",
      "tip_es": "Fascinante colección de intrincados relojes mecánicos de los siglos XVIII y XIX.",
      "tip_zh": "馆内收藏的18-19世纪精致机械时钟令人赞叹。",
      "tip_fr": "Collection captivante d’horloges mécaniques et d’automates d’époque.",
      "tip_de": "Faszinierende Sammlung historischer mechanischer Uhren und Automaten."
    },
    {
      "id": "to_17",
      "name": "Aeroscopia Aviation Museum",
      "category": "Museum & Art",
      "rating": "★4.7",
      "locationZone": "suburban",
      "price": "€14",
      "wikipediaTitle": "Aeroscopia",
      "desc_en": "World-class aviation museum presenting legendary aircraft including two supersonic Concordes, Airbus A380 & Super Guppy.",
      "desc_ja": "超音速機「コンコルド」、世界最大の「エアバスA380」、「スーパーグッピー」などの実機に乗れる航空ミュージアム。",
      "desc_es": "Museo aeronáutico con aviones legendarios como el Concorde, el Airbus A380 y el Super Guppy.",
      "desc_zh": "世界顶尖的航空工程博物馆，展出包括协和式客机、空客 A380 及超级彩虹鱼在内的经典实机。",
      "desc_fr": "Musée aéronautique d’exception abritant deux Concorde, l’Airbus A380 et le Super Guppy.",
      "desc_de": "Weltklasse-Luftfahrtmuseum mit legendären Flugzeugen wie Concorde, Airbus A380 und Super Guppy.",
      "tip_en": "Located in Blagnac near airport; accessible via Tram T1.",
      "tip_ja": "トラムT1線でアクセス可能。実際にコンコルドやA380の機内に入れます。",
      "tip_es": "Ubicado en Blagnac, accesible en el tranvía T1 desde el centro.",
      "tip_zh": "位于 Blagnac，可搭乘电车 T1 线轻松前往，可登上协和号参观机舱内部。",
      "tip_fr": "Accessible facilement en tramway T1; vous pouvez monter à bord du Concorde.",
      "tip_de": "Direkt in Blagnac gelegen, mit der Straßenbahn T1 erreichbar; Sie können die Concorde betreten."
    },
    {
      "id": "to_18",
      "name": "Let's Visit Airbus Tour",
      "category": "Museum & Art",
      "rating": "★4.7",
      "locationZone": "suburban",
      "price": "€16 (Advance booking mandatory)",
      "wikipediaTitle": "Airbus",
      "desc_en": "Exclusive guided industrial tour of Airbus final assembly lines (A350/A380) in Blagnac aerospace hub.",
      "desc_ja": "エアバス社の最終組立ライン（A350等）をガイド付きで見学できる世界屈指の産業観光ツアー。",
      "desc_es": "Exclusiva visita guiada a las líneas de ensamblaje final de los aviones Airbus (A350) en Blagnac.",
      "desc_zh": "独家导览的空客飞机工厂最终组装线（A350等）工业参观之旅（需提前预约）。",
      "desc_fr": "Visite guidée industrielle exclusive des chaînes d’assemblage final des avions Airbus.",
      "desc_de": "Exklusive geführte Fabriktour zu den Airbus-Endmontagelinien in Blagnac.",
      "tip_en": "Book online weeks in advance; passport or ID card is strictly required on arrival.",
      "tip_ja": "事前にオンライン予約が必須。当日はパスポートの提示が義務付けられています。",
      "tip_es": "Reserva online con semanas de antelación; es obligatorio llevar pasaporte.",
      "tip_zh": "必须提前数周在网上预约，入场时需出示护照原件。",
      "tip_fr": "Réservation en ligne obligatoire plusieurs semaines à l’avance; passeport requis.",
      "tip_de": "Wochen im Voraus online buchen; Reisepass ist beim Einlass zwingend erforderlich."
    },

    # ☕ CAFÉ & DINING
    {
      "id": "to_19",
      "name": "Marché Victor Hugo",
      "category": "Café & Dining",
      "rating": "★4.6",
      "locationZone": "city",
      "price": "€15–€30 lunch",
      "wikipediaTitle": "Marché Victor Hugo",
      "desc_en": "Toulouse's gastronomic heartbeat with fresh local meats & cheeses on ground level, and vibrant bistro restaurants upstairs.",
      "desc_ja": "トゥールーズの食の中心地。1階は鴨・フォアグラ・ソセージの市場、2階は市場直送の活気あるビストロ街。",
      "desc_es": "El corazón gastronómico de Toulouse con productos frescos en la planta baja y bistrós en el piso superior.",
      "desc_zh": "图卢兹美食的心脏地带，一楼为新鲜鸭肝与香肠市场，二楼拥挤着直供食材的爆款小馆。",
      "desc_fr": "Cœur gourmand de Toulouse abritant des étals de produits locaux au rez-de-chaussée et des bistrots à l’étage.",
      "desc_de": "Kulinarisches Herz von Toulouse mit Marktständen unten und gemütlichen Bistros im Obergeschoss.",
      "tip_en": "Head to the 2nd-floor bistros around 12:30 PM for freshly caught seafood and Toulouse sausages.",
      "tip_ja": "ランチタイムは2階のビストロで新鮮な海鮮や本場のトゥールーズソーセージを堪能してください。",
      "tip_es": "Sube al segundo piso sobre las 12:30 para almorzar salchichas locales y mariscos frescos.",
      "tip_zh": "中午12:30左右前往二楼的小馆体验地道的图卢兹风味香肠与海鲜午餐。",
      "tip_fr": "Montez à l’étage vers 12h30 pour savourer une véritable saucisse de Toulouse.",
      "tip_de": "Gehen Sie gegen 12:30 Uhr in den 1. Stock für frische Meeresfrüchte und echte Toulouse-Wurst."
    },
    {
      "id": "to_20",
      "name": "Le Bibent",
      "category": "Café & Dining",
      "rating": "★4.5",
      "locationZone": "city",
      "price": "€5 coffee / €35 meal",
      "wikipediaTitle": "Le Bibent",
      "desc_en": "Historic 1843 brasserie on Place du Capitole featuring opulent Belle Époque frescoes and gilded stucco ceilings.",
      "desc_ja": "キャピトル広場に面した1843年創業の歴史的ブラッスリー。天井一面のベル・エポック調フレスコ画が壮麗。",
      "desc_es": "Histórica brasserie de 1843 en la Place du Capitole con lujosos frescos de la Belle Époque.",
      "desc_zh": "位于市政厅广场的1843年老牌小酒馆，内部满饰壮丽的“美好时代”胡桃木与金箔壁画。",
      "desc_fr": "Brasserie historique de 1843 située sur le Capitole au décor Belle Époque spectaculaire.",
      "desc_de": "Historische Brasserie von 1843 am Place du Capitole mit opulenter Belle-Époque-Einrichtung.",
      "tip_en": "Stop by for an afternoon coffee and pastry just to admire the incredible interior.",
      "tip_ja": "午後のカフェタイムにコーヒーとスウィーツを楽しみながら内装を観賞するのがおすすめ。",
      "tip_es": "Tómate un café por la tarde solo para contemplar su increíble interior.",
      "tip_zh": "可以在下午茶时间点一杯咖啡，悠闲地欣赏令人惊叹的宫殿级内饰。",
      "tip_fr": "Faites une pause café l’après-midi simplement pour contempler son plafond sculpté.",
      "tip_de": "Trinken Sie nachmittags einen Kaffee, um das fantastische Interieur zu bewundern."
    },
    {
      "id": "to_21",
      "name": "Le Colombier Cassoulet",
      "category": "Café & Dining",
      "rating": "★4.6",
      "locationZone": "city",
      "price": "€24–€32",
      "wikipediaTitle": "Cassoulet",
      "desc_en": "Famous institution renowned for authentic Toulouse Cassoulet slow-baked with duck confit, pork & Tarbais white beans.",
      "desc_ja": "伝統的なカスレ（Cassoulet）の最高峰老舗。鴨のコンフィと白インゲン豆を専用土鍋で焼き上げた逸品。",
      "desc_es": "Famosa institución conocida por su auténtico Cassoulet de Toulouse cocinado a fuego lento en cazuela de barro.",
      "desc_zh": "图卢兹传统土锅油封鸭炖白豆（Cassoulet）的至尊老字号餐厅。",
      "desc_fr": "Institution mythique réputée pour servir le véritable Cassoulet toulousain mijoté en cassole.",
      "desc_de": "Berühmte Institution für authentisches Toulouse-Cassoulet im traditionellen Tontopf.",
      "tip_en": "Order the signature Cassoulet au Confit de Canard served hot in clay dish.",
      "tip_ja": "専用の土鍋（カソール）でぐつぐつ焼き上げられた鴨コンフィのカスレが名物です。",
      "tip_es": "Pide su plato estrella: Cassoulet con confit de pato servido bien caliente.",
      "tip_zh": "必点招牌热气腾腾的土锅鸭肉干焖白豆。",
      "tip_fr": "Commandez le Cassoulet traditionnel au confit de canard gratiné au four.",
      "tip_de": "Bestellen Sie das Spezial-Cassoulet mit Entenconfit aus dem Ofen."
    },
    {
      "id": "to_22",
      "name": "La Maison de la Violette",
      "category": "Café & Dining",
      "rating": "★4.6",
      "locationZone": "city",
      "price": "€3–€15 violet products",
      "wikipediaTitle": "Canal du Midi",
      "desc_en": "Unique houseboat shop moored on Canal du Midi dedicated to Toulouse's emblem: candied violets, teas & violet liqueurs.",
      "desc_ja": "ミディ運河に浮かぶボートショップ。トゥールーズの象徴「スミレ」の砂糖漬け、リキュール、紅茶の専門店。",
      "desc_es": "Tienda única en un barco flotante en el Canal du Midi dedicada a las violetas confitadas y té de violeta.",
      "desc_zh": "停泊于米迪运河上的船屋小店，专营图卢兹市花“紫罗兰”糖渍花瓣、紫罗兰茶与香水。",
      "desc_fr": "Boutique originale sur une péniche du Canal du Midi dédiée aux bonbons et douceurs à la violette.",
      "desc_de": "Einzigartiges Hausboot-Geschäft auf dem Canal du Midi mit Veichen-Spezialitäten und Liqueurs.",
      "tip_en": "Try the traditional crystallised violet petals (Fleurs de Violettes Crystallisées).",
      "tip_ja": "トゥールーズ伝統の「スミレの花びらの砂糖漬け」はお土産に最適です。",
      "tip_es": "Prueba los tradicionales pétalos de violeta cristalizados con azúcar.",
      "tip_zh": "传统手工水晶结晶紫罗兰花瓣是图卢兹非常特别的伴手礼。",
      "tip_fr": "Goûtez aux authentiques fleurs de violettes cristallisées au sucre.",
      "tip_de": "Probieren Sie die traditionellen kandierten Veilchenblüten."
    },
    {
      "id": "to_23",
      "name": "Marché des Carmes",
      "category": "Café & Dining",
      "rating": "★4.5",
      "locationZone": "city",
      "price": "€5–€20",
      "wikipediaTitle": "Marché des Carmes",
      "desc_en": "Vibrant covered circular market surrounded by trendy wine bars, tapas joints and artisanal bakeries in Carmes district.",
      "desc_ja": "カルム地区の中心にある円形屋内市場。周辺にはトレンディなワインバーやタパスビストロが集結。",
      "desc_es": "Vibrante mercado cubierto circular rodeado de bares de vinos y tapas de moda en el barrio de Carmes.",
      "desc_zh": "卡尔姆区域中心的圆形室内集市，周边环绕着时尚葡萄酒酒吧与西班牙小吃摊。",
      "desc_fr": "Marché couvert circulaire très animé entouré de comptoirs à vin et bistros tendance.",
      "desc_de": "Lebendiger überdachter Rundmarkt umgeben von modernen Weinbars und Tapas-Bistros.",
      "tip_en": "Popular Sunday morning spot for locals enjoying wine and oysters.",
      "tip_ja": "日曜日の午前に地元民が集まり生牡蠣と白ワインを楽しむ名所です。",
      "tip_es": "El lugar perfecto los domingos por la mañana para tomar ostras y vino blanco.",
      "tip_zh": "周日上午当地人最喜欢聚集于此享用新鲜生蚝与白葡萄酒。",
      "tip_fr": "Rendez-vous dominical très prisé pour déguster des huîtres avec un verre de blanc.",
      "tip_de": "Sonntagsmorgens ein beliebter Treffpunkt für frische Austern und Weißwein."
    },
    {
      "id": "to_24",
      "name": "Maison Pillon & Pâtisserie Bault",
      "category": "Café & Dining",
      "rating": "★4.7",
      "locationZone": "city",
      "price": "€4–€8 pastries",
      "wikipediaTitle": "Pastry",
      "desc_en": "Iconic pastry shops crafting refined French gateaux, violet chocolates & artisanal macarons.",
      "desc_ja": "トゥールーズ伝統の極上パティスリー。スミレ風味のショコラやマカロンを提供する名門。",
      "desc_es": "Pastelerías emblemáticas que elaboran refinados pasteles franceses y chocolates de violeta.",
      "desc_zh": "制作精美法式蛋糕、紫罗兰巧克力与手作马卡龙的图卢兹传奇甜品店。",
      "desc_fr": "Pâtisserie d’exception créant de délicieux gâteaux raffinés et chocolats à la violette.",
      "desc_de": "Traditionelle Konditorei für erstklassige französische Törtchen und Veilchen-Schokolade.",
      "tip_en": "Taste the signature Le Pavé du Capitole chocolate praline specialty.",
      "tip_ja": "名物ショコラ「ル・パヴェ・デュ・キャピトル（キャピトルの石畳）」は絶品。",
      "tip_es": "Prueba el praliné de chocolate especial Le Pavé du Capitole.",
      "tip_zh": "推荐尝尝著名的市政厅石砖榛果果仁巧克力。",
      "tip_fr": "Dégustez la spécialité chocolatée Le Pavé du Capitole.",
      "tip_de": "Probieren Sie die Schokoladenspezialität Le Pavé du Capitole."
    },
    {
      "id": "to_25",
      "name": "Domaine de Montjoie & Fronton Wineries",
      "category": "Café & Dining",
      "rating": "★4.6",
      "locationZone": "suburban",
      "price": "€10–€25 tasting",
      "wikipediaTitle": "Fronton AOC",
      "desc_en": "Historic Fronton wine estates north of Toulouse producing unique red & rosé wines from ancient Négrette grape variety.",
      "desc_ja": "トゥールーズ北部特産の古代品種「ネグレット」種から作られるフルーティーなワイン生産ドメーヌ群。",
      "desc_es": "Bodegas históricas de Fronton que producen vinos tintos y rosados únicos de la uva Négrette.",
      "desc_zh": "图卢兹北部使用古老葡萄品种 Négrette 酿造特色红酒与桃红酒的历史酒庄群（日游）。",
      "desc_fr": "Domaines viticoles de l’AOP Fronton élaborant des vins uniques issus du cépage Négrette.",
      "desc_de": "Historische Weingüter in Fronton, bekannt für Weine aus der Négrette-Traube.",
      "tip_en": "30 minutes drive north; Négrette wines pair amazingly with Toulouse Cassoulet.",
      "tip_ja": "車で30分。ネグレット種の赤ワインは地元名物カスレとの相性が抜群です。",
      "tip_es": "A 30 minutos en coche; el vino Négrette marida perfectamente con el Cassoulet.",
      "tip_zh": "驱车向北30分钟即可到达，Négrette 红酒与图卢兹土锅炖白豆是绝配。",
      "tip_fr": "À 30 minutes au nord; les vins de Négrette s’accordent à merveille avec le Cassoulet.",
      "tip_de": "30 Autominuten nördlich; Négrette-Weine passen hervorragend zum Cassoulet."
    },

    # 🌅 SCENERY & WALK
    {
      "id": "to_26",
      "name": "Quai de la Daurade & Promenade de la Garonne",
      "category": "Scenery & Walk",
      "rating": "★4.7",
      "locationZone": "city",
      "price": "Free access",
      "wikipediaTitle": "Garonne",
      "desc_en": "Toulouse's most popular riverside promenade offering magnificent sunset panoramas over Pont Neuf & Pont Saint-Pierre.",
      "desc_ja": "ポン・ヌフと夕日を眺めながら地元民が寛ぐ、市内随一のリバーサイド絶景スポット。",
      "desc_es": "El paseo marítimo más popular junto al río con hermosas puestas de sol sobre el Pont Neuf.",
      "desc_zh": "图卢兹最受欢迎的加龙河畔游步道，拥有远眺新桥与落日日落的无敌全景。",
      "desc_fr": "Promenade riveraine la plus prisée de Toulouse offrant un panorama grandiose au soleil couchant.",
      "desc_de": "Die beliebteste Uferpromenade in Toulouse mit herrlichem Blick auf die Pont Neuf bei Sonnenuntergang.",
      "tip_en": "Bring a picnic or drinks at dusk to join locals on the grassy banks.",
      "tip_ja": "夕暮れ時にドリンクを持参して芝生で寛ぐのが地元の定番スタイルの楽しみ方です。",
      "tip_es": "Lleva un picnic al atardecer para unirte a los locales en la hierba junto al agua.",
      "tip_zh": "傍晚买些小食或饮品坐在草坪上，体验图卢兹当地人的悠闲水岸生活。",
      "tip_fr": "Apportez un pique-nique au crépuscule pour vous joindre aux Toulousains sur la pelouse.",
      "tip_de": "Bringen Sie bei Dämmerung ein Picknick mit und genießen Sie die Atmosphäre am Ufer."
    },
    {
      "id": "to_27",
      "name": "Quartier des Carmes & Quartier Saint-Étienne",
      "category": "Scenery & Walk",
      "rating": "★4.7",
      "locationZone": "city",
      "price": "Free walk",
      "wikipediaTitle": "Toulouse",
      "desc_en": "Charming historic quarter filled with cobblestone alleys, Renaissance mansions & boutique antique shops.",
      "desc_ja": "ルネサンス期のピンクレンガの貴族邸宅が立ち並ぶ、最もエレガントな石畳の路地エリア。",
      "desc_es": "Barrio histórico lleno de adoquines, mansiones renacentistas y tiendas de antigüedades.",
      "desc_zh": "充满石板小巷、文艺复兴红砖古宅与精致古董店的图卢兹最典雅古老街区。",
      "desc_fr": "Quartier historique plein de charme aux ruelles pavées border d’hôtels particuliers en brique rose.",
      "desc_de": "Charmantes historisches Viertel mit Kopfsteinpflaster-Gassen und Renaissance-Palais.",
      "tip_en": "Look for hidden courtyard doors that are often left open during daytime.",
      "tip_ja": "昼間に開いている重厚な木門の奥にある隠れた中庭を覗いてみてください。",
      "tip_es": "Busca los patios interiores escondidos detrás de las portones de madera.",
      "tip_zh": "白天可以轻推开木质大门，探寻藏在后方的幽静私人院落。",
      "tip_fr": "Jetez un coup d’œil à travers les cochers ouverts pour apercevoir de superbes cours.",
      "tip_de": "Achten Sie tagsüber auf offen stehende Tore zu den historischen Innenhöfen."
    },
    {
      "id": "to_28",
      "name": "Canal du Midi (Port de l'Embouchure)",
      "category": "Scenery & Walk",
      "rating": "★4.7",
      "locationZone": "city",
      "price": "Free access",
      "wikipediaTitle": "Canal du Midi",
      "desc_en": "17th-century UNESCO World Heritage canal lined with plane trees, ideal for scenic walks & cycling.",
      "desc_ja": "地中海と大西洋を結ぶ17世紀の世界遺産運河。プラタナスの並木道沿いの遊歩道・サイクリングロード。",
      "desc_es": "Canal del siglo XVII Patrimonio de la Humanidad rodeado de plátanos, ideal para pasear y andar en bici.",
      "desc_zh": "连接地中海与大西洋的17世纪世界遗产运河，沿岸悬铃木成荫，非常适合骑行散步。",
      "desc_fr": "Canal du XVIIe siècle classé à l’UNESCO bordé de platanes, parfait pour la vélo et les balades.",
      "desc_de": "UNESCO-Weltkulturerbe-Kanal aus dem 17. Jahrhundert mit schattigen Platanen-Alleen.",
      "tip_en": "Rent a VélôToulouse city bike to ride along the paved towpath.",
      "tip_ja": "レンタル自転車（VélôToulouse）で運河沿いをサイクリングするのが爽快です。",
      "tip_es": "Alquila una bici VélôToulouse para recorrer el camino de sirga arbolado.",
      "tip_zh": "推荐租用 VélôToulouse 公共自行车沿林荫运河小径骑行。",
      "tip_fr": "Louez un VélôToulouse pour pédaler le long de l’ancien chemin de halage.",
      "tip_de": "Mieten Sie ein VélôToulouse-Fahrrad für eine Tour am Kanalufer."
    },
    {
      "id": "to_29",
      "name": "Place Saint-Georges",
      "category": "Scenery & Walk",
      "rating": "★4.6",
      "locationZone": "city",
      "price": "Free access",
      "wikipediaTitle": "Place Saint-Georges (Toulouse)",
      "desc_en": "Picturesque square filled with half-timbered houses, lively open-air café terraces & relaxing fountain.",
      "desc_ja": "木骨造りの家屋とカフェのオープンテラスが密集する、落ち着いた雰囲気の人気の広場。",
      "desc_es": "Pintoresca plaza con casas de entramado de madera y terrazas de café muy animadas.",
      "desc_zh": "汇聚半木构古民居与热闹露天咖啡座的风景如画小广场。",
      "desc_fr": "Place pittoresque bordée de maisons à colombages et de nombreuses terrasses agréables.",
      "desc_de": "Malerischer Platz mit Fachwerkhäusern und belebten Café-Terrassen.",
      "tip_en": "One of the best places in town for people-watching over a sunny drink.",
      "tip_ja": "晴れた日にカフェテラスでドリンクを飲みながら街の雰囲気を楽しむのに最適です。",
      "tip_es": "Uno de los mejores sitios para sentarse a tomar algo al sol y ver pasar la gente.",
      "tip_zh": "阳光明媚的日子在露天座喝一杯，是观察街头人群的最佳角落。",
      "tip_fr": "L’endroit idéal pour prendre un verre en terrasse sous le soleil toulousain.",
      "tip_de": "Einer der besten Orte der Stadt, um bei einem Drink in der Sonne zu entspannen."
    },
    {
      "id": "to_30",
      "name": "Jardin Japonais Pierre Baudis",
      "category": "Scenery & Walk",
      "rating": "★4.7",
      "locationZone": "city",
      "price": "Free entry",
      "wikipediaTitle": "Jardin japonais de Toulouse",
      "desc_en": "Serene Japanese stroll garden inside Compans-Caffarelli park with red bridge, tea house & koi pond.",
      "desc_ja": "京都の庭園を模して作られた池泉回遊式庭園。赤い太鼓橋、茶室、石庭が調和する癒やしスポット。",
      "desc_es": "Sereno jardín japonés en el parque Compans-Caffarelli con puente rojo, casa de té y estanque.",
      "desc_zh": "位于 Compans-Caffarelli 公园内的日式庭园，建有红色拱桥、茶室与锦鲤池。",
      "desc_fr": "Jardin japonais zen au cœur du parc Compans-Caffarelli avec pont rouge et pavillon de thé.",
      "desc_de": "Ruhiger Japanischer Garten im Park Compans-Caffarelli mit roter Brücke und Teehaus.",
      "tip_en": "Free peaceful oasis perfect for a quiet afternoon break.",
      "tip_ja": "入場無料で静寂を味わえる、街中の素晴らしいオアシスです。",
      "tip_es": "Un oasis de tranquilidad totalmente gratuito en pleno centro de la ciudad.",
      "tip_zh": "市中心完全免费开放的禅意小公园，非常适合安安静静小憩。",
      "tip_fr": "Oasis de sérénité gratuit idéal pour une pause au calme en pleine ville.",
      "tip_de": "Eine kostenfreie Friedensoase mitten in der Stadt für eine entspannte Pause."
    },
    {
      "id": "to_31",
      "name": "Bateaux Toulousains Cruise",
      "category": "Scenery & Walk",
      "rating": "★4.5",
      "locationZone": "city",
      "price": "€12–€16 cruise",
      "wikipediaTitle": "Garonne",
      "desc_en": "Guided river cruise departing Quai de la Daurade navigating Garonne river & Canal du Midi locks.",
      "desc_ja": "ドラード河岸から発着し、ポン・ヌフの下をくぐり運河の水門を体験する定番水上クルーズ。",
      "desc_es": "Crucero guiado por el río que sale del Quai de la Daurade y pasa bajo los puentes históricos.",
      "desc_zh": "从 Daurade 码头出发的观光游船，途径加龙河新桥并体验米迪运河船闸。",
      "desc_fr": "Croisière guidée au départ du Quai de la Daurade passant sous le Pont Neuf et les écluses.",
      "desc_de": "Geführte Bootsfahrt ab Quai de la Daurade über die Garonne und durch Schleusen.",
      "tip_en": "Offers unique photography perspectives of Toulouse's red brick riverfront from the water.",
      "tip_ja": "川の上からピンクの街並みと歴史的石橋を撮影できる人気のボートツアーです。",
      "tip_es": "Ofrece espectaculares vistas desde el agua de los edificios de ladrillo rosa.",
      "tip_zh": "在船上可拍摄图卢兹粉红砖水岸与古桥梁的独特视角。",
      "tip_fr": "Permet d’admirer les façades de briques roses depuis le milieu du fleuve.",
      "tip_de": "Bietet tolle Fotoperspektiven auf die Backsteinfassaden vom Wasser aus."
    },
    {
      "id": "to_32",
      "name": "Canal de Brienne",
      "category": "Scenery & Walk",
      "rating": "★4.6",
      "locationZone": "suburban",
      "price": "Free access",
      "wikipediaTitle": "Canal de Brienne",
      "desc_en": "Historic canal connecting Garonne river to Canal du Midi shaded by magnificent centuries-old plane trees.",
      "desc_ja": "ガロンヌ川とミディ運河を繋ぐ水路。美しい水門と樹齢数百年の巨木並木が続く静寂の散策路。",
      "desc_es": "Canal histórico que conecta el río Garona con el Canal du Midi a la sombra de plátanos centenarios.",
      "desc_zh": "连接加龙河与米迪运河的历史水渠，林荫蔽日，环境十分幽静。",
      "desc_fr": "Canal historique ombragé reliant la Garonne au Canal du Midi bordé d’arbres majestueux.",
      "desc_de": "Historischer Kanal mit jahrhundertealten Platanen, der die Garonne mit dem Canal du Midi verbindet.",
      "tip_en": "Quiet alternative walk starting near Port Saint-Sauveur.",
      "tip_ja": "観光客が少なく静かに緑を楽しめる穴場の散策ルートです。",
      "tip_es": "Paseo muy tranquilo ideal para evitar las aglomeraciones de turistas.",
      "tip_zh": "避开游人群体、静静漫步绿荫水渠的宝藏小径。",
      "tip_fr": "Promenade ombragée très paisible pour s’éloigner de l’agitation.",
      "tip_de": "Ruhiger Spazierweg abseits der belebten Pfade."
    },
    {
      "id": "to_33",
      "name": "Cordes-sur-Ciel",
      "category": "Scenery & Walk",
      "rating": "★4.8",
      "locationZone": "suburban",
      "price": "Free village entry",
      "wikipediaTitle": "Cordes-sur-Ciel",
      "desc_en": "Breathtaking hilltop medieval Gothic village appearing to float above the clouds (Day Trip).",
      "desc_ja": "「天空のコルド」と呼ばれる雲海の上に浮かぶ丘の上の美しい中世ゴシック村（フランスの最も美しい村）。",
      "desc_es": "Impresionante pueblo medieval gótico en la cima de una colina que parece flotar sobre las nubes (Excursión).",
      "desc_zh": "栖息于山顶的中世纪哥特村落，晨雾缭绕时宛如浮于云端（“天空之城”一日游）。",
      "desc_fr": "Bousculante cité médiévale perchée au-dessus des nuages classée parmi les Plus Beaux Villages de France.",
      "desc_de": "Spektakuläres gotisches Bergdorf, das wie über den Wolken zu schweben scheint (Tagesausflug).",
      "tip_en": "1 hour 15 min drive from Toulouse; wear comfortable walking shoes for steep cobblestones.",
      "tip_ja": "トゥールーズから車で約1時間15分。急な石畳の坂道があるため歩きやすい靴が必須。",
      "tip_es": "A 1h15m en coche; lleva calzado cómodo para sus empinadas calles empedradas.",
      "tip_zh": "驱车约1小时15分钟，坡度陡峭，务必穿舒适易走的鞋。",
      "tip_fr": "À 1h15 en voiture; prévoyez de bonnes chaussures pour grimper ses ruelles escarpées.",
      "tip_de": "1 Std. 15 Min. mit dem Auto; festes Schuhwerk für die steilen Pflasterstraßen empfohlen."
    },

    # 🎠 KIDS & FAMILY - STRICTLY FILTERED (Zoos, Science, Theme Parks, Playgrounds)
    {
      "id": "to_34",
      "name": "Cité de l'Espace",
      "category": "Kids & Family",
      "kids": True,
      "rating": "★4.7",
      "locationZone": "city",
      "price": "€24.50 adults / €18 kids",
      "wikipediaTitle": "Cité de l'Espace",
      "desc_en": "Europe's premier space theme park with full-scale Ariane 5 rocket, Mir space station, moonwalk simulator & IMAX planetarium.",
      "desc_ja": "実物大のアリアン5ロケット、宇宙ステーション「ミール」、月面歩行シミュレーターを備えた欧州屈指の宇宙テーマパーク。",
      "desc_es": "El parque temático del espacio líder en Europa con el cohete Ariane 5, la estación Mir y simuladores.",
      "desc_zh": "欧洲首屈一指的航天主题公园，拥有实物比例的阿丽亚娜5号火箭、和平号空间站与月球步履模拟器。",
      "desc_fr": "Parc de l’aventure spatiale avec la fusée Ariane 5 grandeur nature, la station Mir et le planétarium IMAX.",
      "desc_de": "Europas führender Weltraum-Themenpark mit echter Ariane 5 Rakete, Raumstation Mir und IMAX-Planetarium.",
      "tip_en": "Plan a full day; interactive Moonwalk experience is a highlight for kids and adults alike.",
      "tip_ja": "1日中楽しめる巨大施設。月面歩行体験「Moonwalk」は子供から大人まで大人気です。",
      "tip_es": "Planifica un día entero; el simulador de paseo lunar es una experiencia inolvidable.",
      "tip_zh": "建议安排整整一天行程，月球步履模拟器是亲子游览的重头戏。",
      "tip_fr": "Prévoyez la journée complète; la simulation de marche lunaire est incontournable.",
      "tip_de": "Planen Sie einen ganzen Tag ein; die Mondschein-Simulation begeistert Kinder und Erwachsene."
    },
    {
      "id": "to_35",
      "name": "La Halle de la Machine",
      "category": "Kids & Family",
      "kids": True,
      "rating": "★4.8",
      "locationZone": "city",
      "price": "€9.50 exhibit / €14 with Minotaur ride",
      "wikipediaTitle": "La Halle de la Machine",
      "desc_en": "Awe-inspiring experiential park featuring giant kinetic mechanical beasts including a 14-meter rideable Minotaur & Spider.",
      "desc_ja": "巨大な機械仕掛けの怪獣（高さ14mのミノタウロスや巨大クモ）が動いて実際に背中に乗れる体験型アートパーク。",
      "desc_es": "Parque interactivo con impresionantes bestias mecánicas gigantes, incluido un Minotauro de 14 metros.",
      "desc_zh": "令人震撼的机械艺术体验园，包含高达14米可实际骑乘的巨型机械牛头怪与巨蛛。",
      "desc_fr": "Hangar spectacle abritant de géantes créatures mécaniques animées dont un Minotaure de 14m chevauchable.",
      "desc_de": "Erlebnispark mit gigantischen kinetischen Maschinenwesen, darunter ein 14 Meter hoher Minotaurus zum Mitfahren.",
      "tip_en": "Book tickets online to ride on the back of the giant Minotaur as it breathes steam.",
      "tip_ja": "蒸気を吐きながら街を歩く巨大ミノタウロスの背乗体験チケットは事前のオンライン予約がおすすめ。",
      "tip_es": "Reserva billetes online para subir a lomos del Minotauro gigante mientras echa vapor.",
      "tip_zh": "提前在网上预订喷吐蒸汽的巨型机械牛头怪骑乘体验票。",
      "tip_fr": "Réservez en ligne pour monter sur le dos du gigantesque Minotaure crachant de la vapeur.",
      "tip_de": "Buchen Sie Tickets online für die Fahrt auf dem dampfenden Minotaurus."
    },
    {
      "id": "to_36",
      "name": "L'Envol des Pionniers",
      "category": "Kids & Family",
      "kids": True,
      "rating": "★4.6",
      "locationZone": "city",
      "price": "€8.50",
      "wikipediaTitle": "L'Envol des Pionniers",
      "desc_en": "Interactive aviation history museum telling the heroic story of the Aéropostale mail pilots (Saint-Exupéry).",
      "desc_ja": "サン＝テグジュペリらも所属した伝説の航空郵便事業「アエロポスタル」の歴史を体験するミュージアム。",
      "desc_es": "Museo interactivo de aviación que cuenta la historia de los pioneros del correo aéreo como Saint-Exupéry.",
      "desc_zh": "展示传奇航空邮政 Aéropostale 英雄历史的互动航空博物馆（圣埃克苏佩里曾供职于此）。",
      "desc_fr": "Musée d’histoire aéronautique retraçant l’épopée héroïque des pionniers de l’Aéropostale.",
      "desc_de": "Interaktives Luftfahrt-Museum über die kühnen Pioniere der legendären Aéropostale.",
      "tip_en": "Kids love trying the flight simulator and morse code telegraph stations.",
      "tip_ja": "飛行シミュレーターやモールス信号電報体験は子供たちに大人気です。",
      "tip_es": "A los niños les encanta probar el simulador de vuelo y las estaciones de código morse.",
      "tip_zh": "飞行模拟器与摩尔斯电码体验站深受小朋友喜爱。",
      "tip_fr": "Les enfants adorent les simulateurs de vol et les ateliers de télégraphie Morse.",
      "tip_de": "Kinder lieben die Flugsimulatoren und die Morsecode-Stationen."
    },
    {
      "id": "to_37",
      "name": "Jardin des Plantes & Le Grand Rond",
      "category": "Kids & Family",
      "kids": True,
      "rating": "★4.7",
      "locationZone": "city",
      "price": "Free park / €2 pony rides",
      "wikipediaTitle": "Jardin des Plantes (Toulouse)",
      "desc_en": "Expansive interconnected botanical parks featuring footbridges, swan ponds, pony rides & large children's playgrounds.",
      "desc_ja": "歩道橋で連結された広大な緑地公園。白鳥の池、ポニー乗馬、大型プレイグラウンド、ミニトレイン完備。",
      "desc_es": "Parques botánicos conectados con cisnes, paseos en pony, tren infantil y grandes áreas de juego.",
      "desc_zh": "由人行天桥相连的大型城市植物公园，设有天鹅池、骑小马体验、儿童游乐场及观光小火车。",
      "desc_fr": "Grands parcs reliés par une passerelle avec étangs aux cygnes, poney, manèges et grands jeux pour enfants.",
      "desc_de": "Weitläufige Parkanlage mit Schwanenteichen, Ponyreiten, Karussell und Kinderspielplätzen.",
      "tip_en": "Great spot for families to relax with ice cream near the playground.",
      "tip_ja": "公園内のカフェでアイスクリームを買い、子供を遊具で遊ばせるファミリー定番の癒やしスポット。",
      "tip_es": "Un lugar ideal para que las familias se relajen con un helado junto a los juegos.",
      "tip_zh": "带小朋友吃冰淇淋、在游乐设施嬉戏放松的经典亲子公园。",
      "tip_fr": "Lieu idéal en famille pour déguster une glace près de l’aire de jeux.",
      "tip_de": "Ideal für Familien für ein Eis am großen Kinderspielplatz."
    },
    {
      "id": "to_38",
      "name": "Animaparc Occitanie",
      "category": "Kids & Family",
      "kids": True,
      "rating": "★4.6",
      "locationZone": "suburban",
      "price": "€16.50",
      "wikipediaTitle": "Toulouse",
      "desc_en": "Family theme park combining a life-size moving Dinosaur Forest, petting farm & 30+ kid-friendly rides (Suburban).",
      "desc_ja": "動く恐竜の森、動物ふれあいファーム、30以上のアトラクションが融合した大型ファミリーパーク（郊外）。",
      "desc_es": "Parque familiar que combina un Bosque de Dinosauros a tamaño real, granja y más de 30 atracciones.",
      "desc_zh": "集实物等大动态恐龙森林、亲近小动物农场及30多项亲子游乐设施于一体的大型公园（郊外日游）。",
      "desc_fr": "Parc familial combinant une Forêt des Dinosaures grandeur nature, une ferme et 30+ attractions.",
      "desc_de": "Familien-Freizeitpark mit lebensgroßem Dinosaurier-Wald, Streichelzoo und über 30 Attraktionen.",
      "tip_en": "35 minutes drive west of Toulouse; ideal for young children aged 2–12.",
      "tip_ja": "トゥールーズから西へ車で約35分。2歳〜12歳のお子様連れに最適です。",
      "tip_es": "A 35 minutos en coche al oeste; ideal para niños de 2 a 12 años.",
      "tip_zh": "驱车向西约35分钟，非常适合带2-12岁的小朋友前往。",
      "tip_fr": "Situé à 35 min à l’ouest; idéal pour les enfants de 2 à 12 ans.",
      "tip_de": "35 Autominuten westlich; perfekt für Kinder im Alter von 2 bis 12 Jahren."
    },
    {
      "id": "to_39",
      "name": "Le Labyrinthe de Merville",
      "category": "Kids & Family",
      "kids": True,
      "rating": "★4.6",
      "locationZone": "suburban",
      "price": "€10.50 adults / €8.50 kids",
      "wikipediaTitle": "Château de Merville (Haute-Garonne)",
      "desc_en": "Europe's largest boxwood hedge maze spanning 10km of shaded trails around a 18th-century château (Suburban).",
      "desc_ja": "18世紀のお城の敷地に広がる、欧州最大級のツゲの生垣巨大迷路（全長10kmの冒険コース / 郊外）。",
      "desc_es": "El laberinto de setos de boj más grande de Europa con 10 km de senderos en un castillo del siglo XVIII.",
      "desc_zh": "欧洲规模最大的黄杨树生垣巨大迷宫，围绕18世纪古堡延绵10公里林荫探险步道（郊外）。",
      "desc_fr": "Le plus grand labyrinthe de buis d’Europe s’étendant sur 10 km d’allées autour d’un château du XVIIIe.",
      "desc_de": "Größter Buchsbaum-Heckenirrgarten Europas mit 10 km Wegen rund um ein Schloss aus dem 18. Jhd.",
      "tip_en": "Includes interactive treasure hunt riddles to solve as you navigate the maze.",
      "tip_ja": "迷路を解き進みながらクイズや宝探しを楽しめるインタラクティブな設計になっています。",
      "tip_es": "Incluye un divertido juego de pistas e historias para resolver mientras buscas la salida.",
      "tip_zh": "包含边走边解谜的寻宝游戏，沿途趣味十足。",
      "tip_fr": "Comprend un jeu de piste captivant à résoudre en famille tout au long du parcours.",
      "tip_de": "Enthält ein unterhaltsames Rätsel-Suchspiel für die ganze Familie."
    }
  ]
}

with open("data/cities/toulouse.json", "w", encoding="utf-8") as f:
    json.dump(toulouse_data, f, indent=2, ensure_ascii=False)

print(f"✅ Successfully created data/cities/toulouse.json with {len(toulouse_data['spots'])} curated spots!")
