import json

hamburg_spots = [
    # 1. Miniatur Wunderland
    {
        "id": "h_1",
        "name": "Miniatur Wunderland（ミニチュアワンダーランド）",
        "category": "Kids & Family", "rating": "★4.9", "locationZone": "city",
        "lat": 53.5438, "lng": 9.9888, "kids": True, "rain": True, "shopping": False, "free": False,
        "desc_en": "World's largest model railway exhibition in Speicherstadt featuring over 1,100 trains, interactive daytime/nighttime lighting cycles, and miniature airport.",
        "desc_ja": "シュパイヒャーシュタット内にある世界最大の動く鉄道模型・ジオラマテーマパーク。1,100編成超の列車、15分毎の昼夜ライティング、ミニ飛行機離着陸が精巧。",
        "desc_es": "La exposición de ferromodelismo más grande del mundo en Speicherstadt con más de 1.100 trenes y un aeropuerto en miniatura a escala.",
        "desc_zh": "坐落于仓库城的全球最大动态微缩景观模型世界。拥有1100多列运行列车、15分钟昼夜交替灯光系统与飞行飞机的微型机场。",
        "desc_fr": "La plus grande exposition de modélisme ferroviaire du monde à Speicherstadt avec plus de 1 100 trains et son aéroport miniature.",
        "de": "Größte Modellbahnanlage der Welt in der Speicherstadt mit über 1.100 Zügen, Knopfdruckaktionen und Knuffingen Airport.",
        "tip_en": "🎟️ Book fixed time-slot tickets online 3-6 weeks in advance! Visiting during late-night extended opening hours (after 8:00 PM) offers zero waiting and nighttime illuminations.",
        "tip_ja": "🎟️ 公式サイトでの数週間前Web事前予約が絶対必須！夜間特別営業枠（20:00以降）を狙うと並び時間ゼロで幻想的なジオラマ夜景を楽しめます。",
        "tip_es": "🎟️ ¡Reserva las entradas con hora fija por internet con 3 a 6 semanas de antelación! Ven pasadas las 20:00 h sin esperas.",
        "tip_zh": "🎟️ 必须提前3-6周在官网预订定时门票！特别推荐晚间延长营业场次（20:00后），免去排队且可独享夜景灯光秀。",
        "tip_fr": "🎟️ Réservez vos billets à créneau horaire en ligne des semaines à l'avance ! Privilégiez les nocturnes après 20h.",
        "tip_de": "🎟️ Zeitfenster-Tickets 3–6 Wochen im Voraus online buchen! Die Abendschichten ab 20:00 Uhr ohne Wartezeiten nutzen.",
        "price_en": "Entry: €20", "price_ja": "入場料: 20ユーロ", "price_es": "Entrada: 20€", "price_zh": "门票：20 欧元", "price_fr": "Entrée : 20 €", "price_de": "Eintritt: 20 €",
        "name_en": "Miniatur Wunderland", "name_ja": "Miniatur Wunderland（ミニチュアワンダーランド）", "name_es": "Miniatur Wunderland", "name_zh": "微缩景观世界", "name_fr": "Miniatur Wunderland", "name_de": "Miniatur Wunderland"
    },
    # 2. Elbphilharmonie Hamburg
    {
        "id": "h_2",
        "name": "Elbphilharmonie Hamburg (Elphi)（エルプフィルハーモニー・ハンブルク）",
        "category": "Landmark", "rating": "★4.8", "locationZone": "city",
        "lat": 53.5413, "lng": 9.9842, "kids": True, "rain": True, "shopping": False, "free": True,
        "desc_en": "Herzog & de Meuron-designed landmark concert hall combining a wave-like glass superstructure atop a historic 1966 brick warehouse at Hamburg harbor.",
        "desc_ja": "ヘルツォーク＆ド・ムーロン設計のガラス建築。歴史的赤レンガ倉庫の上に波打つガラスが載るハンブルク港のシンボル。",
        "desc_es": "Sala de conciertos icónica diseñada por Herzog & de Meuron que combina una superestructura de cristal ondulado sobre un almacén de ladrillo.",
        "desc_zh": "由 Herzog & de Meuron 设计的浪涌玻璃地标音乐厅。在1966年老红砖仓库上方耸立着波浪形玻璃结构。",
        "desc_fr": "Salle de concert emblématique conçue par Herzog & de Meuron surmontant un ancien entrepôt en brique.",
        "de": "Imposantes Konzerthaus von Herzog & de Meuron mit kühnem Glasaufbau auf einem historischen Backspeicher.",
        "tip_en": "📸 Pick up a free Plaza Ticket at the ground ticket counter to ride the 82-meter curved escalator ('The Tube') up to the 37m outdoor observation deck!",
        "tip_ja": "📸 発券カウンターで無料のプラザ入場券（Plaza Ticket）を受け取り、全長82mの曲面エスカレーター『The Tube』で37m高さの風が吹き抜ける屋外パノラマデッキへ！",
        "tip_es": "📸 Recoge la entrada gratuita Plaza Ticket en taquilla para subir por la escalera mecánica curva de 82m hasta el mirador exterior.",
        "tip_zh": "📸 可在1楼票务柜台免费领取 Plaza 观景台门票！搭乘长达82米的弧形隧道电梯（The Tube）升至37米高环形露台。",
        "tip_fr": "📸 Prenez un billet gratuit Plaza Ticket au guichet pour emprunter l'escalator courbe de 82m vers la terrasse panoramique.",
        "tip_de": "📸 Kostenloses Plaza-Ticket am Schalter holen und mit der 82m langen gebogenen Rolltreppe ('Tube') zum Panoramadeck fahren.",
        "price_en": "Plaza Free (Concerts Varies)", "price_ja": "展望プラザ無料（公演料別途）", "price_es": "Plaza gratis (Conciertos varía)", "price_zh": "观景广场免费（演出门票另计）", "price_fr": "Plaza gratuite (Concerts variable)", "price_de": "Plaza frei (Konzertkarten variieren)",
        "name_en": "Elbphilharmonie Concert Hall", "name_ja": "Elbphilharmonie Hamburg (Elphi)（エルプフィルハーモニー・ハンブルク）", "name_es": "Filarmónica del Elba", "name_zh": "易北爱乐厅", "name_fr": "Philharmonie de l'Elbe", "name_de": "Elbphilharmonie Hamburg"
    },
    # 3. Speicherstadt
    {
        "id": "h_3",
        "name": "Speicherstadt（シュパイヒャーシュタット / 世界遺産赤レンガ倉庫街）",
        "category": "Landmark", "rating": "★4.8", "locationZone": "city",
        "lat": 53.5433, "lng": 9.9922, "kids": True, "rain": False, "shopping": False, "free": True,
        "desc_en": "UNESCO World Heritage site built between 1883 and 1927, the world's largest warehouse complex resting on oak piles along canal waterways.",
        "desc_ja": "1883〜1927年建設の世界遺産。運河の水路沿いにオーク材の杭で支えられた赤レンガ倉庫群が連なる世界最大の倉庫街。",
        "desc_es": "Patrimonio de la Humanidad por la UNESCO, el complejo de almacenes sobre pilares de roble más grande del mundo entre canales.",
        "desc_zh": "建于1883至1927年间的世界文化遗产。矗立于运河水系橡木桩基础上的世界最大规模红砖历史仓库群。",
        "desc_fr": "Site classé UNESCO, le plus grand complexe d'entrepôts au monde sur pieux en chêne le long des canaux.",
        "de": "UNESCO-Welterbe und größter zusammenhängender Lagerhauskomplex der Welt auf Eichenpfählen in den Fleeten.",
        "tip_en": "📸 Stand on the Poggenmühlenbrücke bridge at dusk to shoot the classic postcard photo of Wasserschloss illuminated between two canal branches!",
        "tip_ja": "📸 日没時の『Poggenmühlenbrücke』橋の上が絶景アングル！2つの運河の分岐点に立つ水上城館『Wasserschloss』のライトアップが水面に映えます。",
        "tip_es": "📸 Sitúate en el puente Poggenmühlenbrücke al atardecer para fotografiar el edificio Wasserschloss iluminado entre canales.",
        "tip_zh": "📸 黄昏蓝调时刻打卡 Poggenmühlenbrücke 铁桥！拍摄立于双干运河汇合处的“水上城堡”（Wasserschloss）倒影佳作。",
        "tip_fr": "📸 Placez-vous sur le pont Poggenmühlenbrücke à la tombée du jour pour photographier le Wasserschloss illuminé.",
        "tip_de": "📸 Zur blauen Stunde auf der Poggenmühlenbrücke stehen für das klassische Motiv des beleuchteten Wasserschlosses im Fleet.",
        "price_en": "Free Access", "price_ja": "散策無料", "price_es": "Acceso libre", "price_zh": "免费游览", "price_fr": "Accès libre", "price_de": "Kostenlos",
        "name_en": "Speicherstadt Warehouse District", "name_ja": "Speicherstadt（シュパイヒャーシュタット / 世界遺産赤レンガ倉庫街）", "name_es": "Distrito Speicherstadt", "name_zh": "仓库城", "name_fr": "Speicherstadt", "name_de": "Speicherstadt Hamburg"
    },
    # 4. Kontorhausviertel & Chilehaus
    {
        "id": "h_4",
        "name": "Kontorhausviertel & Chilehaus（コントーアハウス地区＆チリハウス）",
        "category": "Landmark", "rating": "★4.7", "locationZone": "city",
        "lat": 53.5483, "lng": 10.0019, "kids": True, "rain": False, "shopping": False, "free": True,
        "desc_en": "UNESCO-listed 1920s Brick Expressionist office district featuring Fritz Höger's Chilehaus, shaped like a massive ocean liner's sharp bow.",
        "desc_ja": "1920年代のレンガ表現主義建築群（世界遺産）。建築家フリッツ・ヘーガー作『チリハウス（Chilehaus）』の船首のように尖った角部が見事。",
        "desc_es": "Distrito de oficinas expresionista de ladrillo de los años 20 (UNESCO) con el edificio Chilehaus en forma de proa de buque.",
        "desc_zh": "联合国教科文组织1920年代砖木表现主义办公区。大师 Fritz Höger 设计的 Chilehaus 宛如巨轮尖锐的船首斜插云霄。",
        "desc_fr": "Quartier d'affaires expressionniste en brique des années 1920 (UNESCO) avec l'immeuble Chilehaus en forme de proue de navire.",
        "de": "UNESCO-Welterbe-Ensemble des Backsteinexpressonismus der 1920er Jahre mit dem chilehaus im Stil eines Schiffsbugs.",
        "tip_en": "📸 Stand at the intersection of Fischertwiete and Burchardstraße to look directly up at the razor-sharp 45-degree angle corner of Chilehaus!",
        "tip_ja": "📸 『Fischertwiete』と『Burchardstraße』の交差点の角へ！Chilehausの鋭角45度に研ぎ澄まされた船首のような角部を見上げる構図が最高です。",
        "tip_es": "📸 Colócate en el cruce de Fischertwiete y Burchardstraße para ver la esquina en ángulo agudo del Chilehaus.",
        "tip_zh": "📸 站在 Fischertwiete 与 Burchardstraße 交叉路口！抬头仰拍 Chilehaus 呈45度极尽犀利的“船首”外墙角。",
        "tip_fr": "📸 Placez-vous au croisement de Fischertwiete et Burchardstraße pour photographier l'angle aigu spectaculaire.",
        "tip_de": "📸 An der Kreuzung Fischertwiete/Burchardstraße stehen und den rasiermesserscharfen Schiffsbug-Winkel nach oben fotografieren.",
        "price_en": "Free Access", "price_ja": "見学無料", "price_es": "Acceso libre", "price_zh": "免费参观", "price_fr": "Accès libre", "price_de": "Kostenlos",
        "name_en": "Chilehaus & Kontorhaus District", "name_ja": "Kontorhausviertel & Chilehaus（コントーアハウス地区＆チリハウス）", "name_es": "Chilehaus y Kontorhausviertel", "name_zh": "智利大厦与写字楼区", "name_fr": "Chilehaus et quartier des comptoirs", "name_de": "Kontorhausviertel & Chilehaus"
    },
    # 5. Hamburger Rathaus & Rathausmarkt
    {
        "id": "h_5",
        "name": "Hamburger Rathaus & Rathausmarkt（ハンブルク市庁舎＆市庁舎前広場）",
        "category": "Landmark", "rating": "★4.8", "locationZone": "city",
        "lat": 53.5503, "lng": 9.9928, "kids": True, "rain": True, "shopping": False, "free": True,
        "desc_en": "Palatial 1897 Neo-Renaissance city hall with 647 rooms, featuring a 112m spire tower, Hygieia courtyard fountain, and elaborate state rooms.",
        "desc_ja": "バッキンガム宮殿より部屋数が多い647室を誇る1897年建造のネオ・ルネサンス宮殿風市庁舎。中央の112mの塔と中庭のヒュギエイアの噴水が印象的。",
        "desc_es": "Palaciego ayuntamiento neorrenacentista de 1897 con 647 habitaciones, torre de 112m y patio con la Fuente de Higía.",
        "desc_zh": "建于1897年媲美王宫的新文艺复兴风格市府大楼。拥有647间房间、112米高的中央尖塔与中庭希吉亚健康女神喷泉。",
        "desc_fr": "Hôtel de ville néo-renaissance grandiose de 1897 aux 647 pièces avec une tour de 112m et sa cour intérieure.",
        "de": "Neurenaissance-Rathaus von 1897 mit 647 Räumen, 112m hohem Turm und dem Hygieia-Brunnen im Innenhof.",
        "tip_en": " Walk into the quiet inner courtyard (Innenhof) behind the main hall to admire the bronze Hygieia Fountain commemorating the 1892 cholera epidemic.",
        "tip_ja": " 市庁舎中央のアーチをくぐって静かな中庭（Innenhof）へ！1892年のコレラ終息を記念して造られたブロンズ製のヒュギエイアの噴水（Hygieia-Brunnen）が隠れた見どころです。",
        "tip_es": " Entra al patio interior por el arco central para ver la Fuente de Higía de bronce que conmemora la epidemia de 1892.",
        "tip_zh": " 穿过主楼中央拱门推步进入中庭（Innenhof）！观赏为纪念1892年霍乱疫情平息而建的铜雕希吉亚健康女神喷泉（Hygieia-Brunnen）。",
        "tip_fr": " Entrez dans la cour intérieure calme pour admirer la fontaine d'Hygie en bronze.",
        "tip_de": " Durch das Torbogen-Portal in den ruhigen Innenhof gehen, um den bronzenen Hygieia-Brunnen von 1895 zu besichtigen.",
        "price_en": "Courtyard Free (Guided Tour €5)", "price_ja": "中庭無料（内部ガイドツアー: 5ユーロ）", "price_es": "Patio gratis (Tour guiado 5€)", "price_zh": "中庭免费（导览5欧）", "price_fr": "Cour gratuite (Visite guidée 5 €)", "price_de": "Innenhof frei (Führung 5 €)",
        "name_en": "Hamburg City Hall", "name_ja": "Hamburger Rathaus & Rathausmarkt（ハンブルク市庁舎＆市庁舎前広場）", "name_es": "Ayuntamiento de Hamburgo", "name_zh": "汉堡市政厅", "name_fr": "Hôtel de ville de Hambourg", "name_de": "Hamburger Rathaus & Rathausmarkt"
    },
    # 6. Hauptkirche St. Michaelis (Michel)
    {
        "id": "h_6",
        "name": "Hauptkirche St. Michaelis (Michel)（聖ミヒャエリス教会）",
        "category": "Landmark", "rating": "★4.7", "locationZone": "city",
        "lat": 53.5483, "lng": 9.9789, "kids": True, "rain": True, "shopping": False, "free": True,
        "desc_en": "Hamburg's iconic 1762 Baroque Protestant church known affectionate as 'Michel', featuring a copper-covered 132-meter clock tower.",
        "desc_ja": "『ミヒェル』の愛称で親しまれる1762年建造のバロック様式プロテスタント教会。銅板に覆われた高さ132mの時計塔が航海の目印。",
        "desc_es": "Iglesia barroca de 1762 conocida como 'Michel' con una torre con reloj recubierta de cobre de 132 metros.",
        "desc_zh": "法兰克福老航海者心目中的灯塔。建于1762年巴洛克风格新教大教堂，拥有132米高的包铜钟楼尖塔。",
        "desc_fr": "Église baroque de 1762 surnommée 'Michel' avec son clocher en cuivre de 132 mètres guidant los marins.",
        "de": "Wahrzeichen Hamburgs von 1762 im Barockstil mit 132m hohem kupferverkleidetem Turm.",
        "tip_en": " Listen for the traditional 'Türmer' brass trumpeter playing a chorale from the 106m tower platform every day at 10:00 AM and 9:00 PM!",
        "tip_ja": " 毎日午前10:00と夜21:00に注目！106mの塔の上からトランペット奏者（Türmer）が東西南北に向かって讃美歌を吹奏する歴史的儀式を塔下で聴くことができます。",
        "tip_es": " Escucha el trompetista tradicional Türmer tocar desde la plataforma de la torre todos los días a las 10:00 y a las 21:00 h.",
        "tip_zh": " 每天上午10点与夜间21点准时抬头聆听！号手（Türmer）会在106米高空四面吹响传统赞美诗长号。",
        "tip_fr": " Écoutez le trompettiste traditionnel jouer un choral depuis la tour tous les jours à 10h et 21h.",
        "tip_de": " Täglich um 10:00 und 21:00 Uhr dem 'Türmer' lauschen, der vom Turm ein Trompetensignal in alle vier Himmelsrichtungen bläst.",
        "price_en": "Church Free (Tower €8)", "price_ja": "聖堂無料（塔登頂: 8ユーロ）", "price_es": "Iglesia gratis (Torre 8€)", "price_zh": "教堂免费（登塔8欧）", "price_fr": "Église gratuite (Tour 8 €)", "price_de": "Kirche frei (Turm 8 €)",
        "name_en": "St. Michael's Church", "name_ja": "Hauptkirche St. Michaelis (Michel)（聖ミヒャエリス教会）", "name_es": "Iglesia de San Miguel", "name_zh": "圣米歇尔大教堂", "name_fr": "Église Saint-Michel de Hambourg", "name_de": "Hauptkirche St. Michaelis (Michel)"
    },
    # 7. Hamburger Hafen & Landungsbrücken
    {
        "id": "h_7",
        "name": "Hamburger Hafen & Landungsbrücken（ハンブルク港＆ザンクト・パウリ桟橋）",
        "category": "Landmark", "rating": "★4.7", "locationZone": "city",
        "lat": 53.5458, "lng": 9.9669, "kids": True, "rain": False, "shopping": False, "free": True,
        "desc_en": "Germany's largest seaport featuring the historic 1907 St. Pauli floating piers (Landungsbrücken), harbor tours, and massive container ships.",
        "desc_ja": "ドイツ最大の巨大港。1907年建造の浮き桟橋『ザンクト・パウリ桟橋』から港湾クルーズ船が交差し、巨大コンテナ船が行き交う。",
        "desc_es": "El puerto más grande de Alemania con los muelles flotantes históricos de St. Pauli de 1907 y recorridos en barco.",
        "desc_zh": "德国最大海港。始于1907年的 St. Pauli 巨型水上浮动码头长廊，大型集装箱货轮与观光游船在此穿梭交织。",
        "desc_fr": "Le plus grand port d'Allemagne avec les embarcadères flottants de St. Pauli de 1907 et balades en bateau.",
        "de": "Größter Seehafen Deutschlands mit den historischen schwimmenden St. Pauli Landungsbrücken von 1907.",
        "tip_en": "🎟️ Take HADAG Harbor Ferry Line 62 (Bridge 3) using a standard HVV public transport ticket for a budget-friendly 1-hour round-trip cruise past Övelgönne beach!",
        "tip_ja": "🎟️ 3番桟橋から『HADAG定期フェリー62番線』に乗車！一般的な一日乗車券（HVV ticket）のまま、巨大コンテナ船をすり抜ける格安1時間港湾クルーズが楽しめます。",
        "tip_es": "🎟️ ¡Toma el ferri HADAG línea 62 (Muelle 3) con el billete normal de transporte público HVV para un crucero económico!",
        "tip_zh": "🎟️ 在3号码头搭乘 HADAG 62号渡轮！刷通用 HVV 公共交通一日券即可畅享超划算的1小时美景港湾游船。",
        "tip_fr": "🎟️ Prenez le ferry HADAG ligne 62 au ponton 3 avec un ticket de transport public classique pour une croisière économique !",
        "tip_de": "🎟️ Die HADAG-Hafenfähre Linie 62 an Brücke 3 mit einem normalen HVV-Tagesticket für eine preiswerte Hafenrundfahrt nutzen!",
        "price_en": "Free Stroll (Ferry €3.80 / Tour €18)", "price_ja": "桟橋無料（フェリー3.80ユーロ/クルーズ18ユーロ）", "price_es": "Paseo gratis (Ferry 3,80€)", "price_zh": "散步免费（渡轮3.80欧）", "price_fr": "Promenade gratuite (Ferry 3,80 €)", "price_de": "Promenade frei (Fähre 3,80 €)",
        "name_en": "Hamburg Harbor & St. Pauli Piers", "name_ja": "Hamburger Hafen & Landungsbrücken（ハンブルク港＆ザンクト・パウリ桟橋）", "name_es": "Puerto de Hamburgo y Landungsbrücken", "name_zh": "汉堡港与圣保利码头", "name_fr": "Port de Hambourg et Landungsbrücken", "name_de": "Hamburger Hafen & Landungsbrücken"
    },
    # 8. Alter Elbtunnel
    {
        "id": "h_8",
        "name": "Alter Elbtunnel (St. Pauli Elbtunnel)（旧エルベトンネル）",
        "category": "Landmark", "rating": "★4.7", "locationZone": "city",
        "lat": 53.5458, "lng": 9.9664, "kids": True, "rain": True, "shopping": False, "free": True,
        "desc_en": "Historic 1911 underwater tunnel 24 meters beneath the Elbe river, spanning 426 meters with vintage lifts and maritime ceramic tile reliefs.",
        "desc_ja": "1911年開通。エルベ川の24m水底を貫く全長426mの歴史的水底トンネル。クラシックなレトロエレベーターと魚モチーフのセラミック壁画が映える。",
        "desc_es": "Túnel subterráneo histórico de 1911 a 24m bajo el río Elba, de 426m de longitud con ascensores vintage.",
        "desc_zh": "始于1911年下穿易北河水底24米深的426米长历史隧道。配有古董车辆大电梯与精致的海鲜海洋瓷砖浮雕。",
        "desc_fr": "Túnel sous-marin historique de 1911 sous le fleuve Elbe à 24m de profondeur avec ascenseurs vintage.",
        "de": "Historischer Unterwassertunnel von 1911 unter der Elbe (24m tief, 426m lang) mit alten Fahrzeugaufzügen.",
        "tip_en": "📸 Walk through the tunnel to the south bank (Steinwerder) to enjoy the panoramic skyline view of Landungsbrücken and St. Michaelis church reflecting over the water!",
        "tip_ja": "📸 トンネルを歩いて対岸の『Steinwerder』へ！階段を登って地表へ出ると、対岸の桟橋と聖ミヒャエリス教会の尖塔を正面に望む穴場のパノラマ写真が撮影できます。",
        "tip_es": "📸 Camina por el túnel hasta la orilla sur (Steinwerder) para disfrutar de la vista panorámica del puerto.",
        "tip_zh": "📸 徒步穿过426米隧道抵达南岸（Steinwerder）！登上地表，俯瞰对岸圣保利码头与大教堂尖塔构成的天际线全景大片。",
        "tip_fr": "📸 Traversez le tunnel vers la rive sud (Steinwerder) pour admirer le panorama sur le port.",
        "tip_de": "📸 Zu Fuß durch den Tunnel zur Südseite (Steinwerder) gehen: Von dort hat man den besten Blick auf die Landungsbrücken und den Michel.",
        "price_en": "Free Pedestrian Access", "price_ja": "歩行者通行無料", "price_es": "Acceso peatonal gratis", "price_zh": "行人免费通行", "price_fr": "Gratuit pour piétons", "price_de": "Kostenlos für Fußgänger",
        "name_en": "Old Elbe Tunnel", "name_ja": "Alter Elbtunnel (St. Pauli Elbtunnel)（旧エルベトンネル）", "name_es": "Antiguo Túnel del Elba", "name_zh": "旧易北河隧道", "name_fr": "Vieux tunnel sous l'Elbe", "name_de": "Alter Elbtunnel Hamburg"
    },
    # 11. Hamburger Kunsthalle
    {
        "id": "h_11",
        "name": "Hamburger Kunsthalle（ハンブルク美術館）",
        "category": "Museum & Gallery", "rating": "★4.7", "locationZone": "city",
        "lat": 53.5550, "lng": 10.0025, "kids": True, "rain": True, "shopping": False, "free": False,
        "desc_en": "Major European art museum spanning 3 connected buildings holding Caspar David Friedrich's iconic 'Wanderer above the Sea of Fog', Rembrandt, and Manet.",
        "desc_ja": "3つの赤レンガ・現代館が繋がる美術館。カスパー・ダーヴィト・フリードリヒの至宝『雲海の上の旅人』やレンブラント、マネの名画を展示。",
        "desc_es": "Gran museo de arte europeo que alberga la icónica obra 'El caminante sobre el mar de nubes' de Friedrich y pinturas de Rembrandt.",
        "desc_zh": "由三栋相连建筑组成的欧洲知名艺术馆。收藏有 Caspar David Friedrich 镇馆名画《云海之上的旅人》及伦勃朗、马奈珍品。",
        "desc_fr": "Grand musée d'art européen abritant le chef-d'œuvre 'Le Voyageur contemplant une mer de nuages' de Friedrich.",
        "de": "Bedeutendes Kunstmuseum in drei Gebäuden mit Caspar David Friedrichs 'Der Wanderer über dem Nebelmeer'.",
        "tip_en": "🖼️ Head straight to Room 16 in the Lichtwark-Bau to stand directly in front of Caspar David Friedrich's world-famous masterwork 'Wanderer above the Sea of Fog'!",
        "tip_ja": "🖼️ 旧館（Lichtwark-Bau）の第16展示室へ直行！ドイツ・ロマン派最高峰の傑作『雲海の上の旅人（Der Wanderer über dem Nebelmeer）』を静かに観賞できます。",
        "tip_es": "🖼️ Dirígete a la sala 16 del edificio histórico para ver la famosa pintura 'El caminante sobre el mar de nubes'.",
        "tip_zh": "🖼️ 直奔旧馆 Lichtwark-Bau 16号展厅！近距离沉浸观赏传世名作《云海之上的旅人》（Wanderer above the Sea of Fog）。",
        "tip_fr": "🖼️ Rendez-vous dans la salle 16 du bâtiment ancien pour admirer le tableau mythique de Caspar David Friedrich.",
        "tip_de": "🖼️ Direkt in Raum 16 des Lichtwark-Baus gehen, um Caspar David Friedrichs 'Wanderer über dem Nebelmeer' im Original zu sehen.",
        "price_en": "Entry: €14", "price_ja": "入場料: 14ユーロ", "price_es": "Entrada: 14€", "price_zh": "门票：14 欧元", "price_fr": "Entrée : 14 €", "price_de": "Eintritt: 14 €",
        "name_en": "Hamburg Art Museum", "name_ja": "Hamburger Kunsthalle（ハンブルク美術館）", "name_es": "Kunsthalle de Hamburgo", "name_zh": "汉堡艺术馆", "name_fr": "Kunsthalle de Hambourg", "name_de": "Hamburger Kunsthalle"
    },
    # 21. Fischmarkt (Altona)
    {
        "id": "h_21",
        "name": "Fischmarkt (Altona)（アルトナの魚市場＆フィッシュオークションホール）",
        "category": "Shopping", "rating": "★4.6", "locationZone": "city",
        "lat": 53.5453, "lng": 9.9547, "kids": True, "rain": False, "shopping": True, "free": True,
        "desc_en": "Historic Sunday morning fish market operating since 1703 along the Elbe, famed for loud auctioneers, fresh seafood, live rock music, and beer.",
        "desc_ja": "1703年から続く日曜早朝限定の歴史的魚市場。大声で魚やフルーツを競り落とす威勢の良い商人、魚競売ホール（Fischauktionshalle）での生演奏ライブが名物。",
        "desc_es": "Mercado de pescado dominical histórico desde 1703 junto al Elba con subastadores ruidosos, marisco fresco y música en vivo.",
        "desc_zh": "始于1703年仅在周日清晨营业的百年鱼市。拍卖呼喊声不绝于耳，鱼拍卖大厅（Fischauktionshalle）内更有摇滚乐队现场演奏。",
        "desc_fr": "Marché aux poissons dominical historique depuis 1703 avec criée animée, fruits de mer et musique rock en direct.",
        "de": "Kult-Sonntagsmarkt seit 1703 am Elbufer mit Marktschreiern, frischem Fisch und Live-Musik in der Fischauktionshalle.",
        "tip_en": "⏰ Open ONLY Sunday mornings (5:00 AM – 9:30 AM in summer; 7:00 AM in winter)! Step inside the Fischauktionshalle to drink a beer and listen to live rock covers.",
        "tip_ja": "⏰ 毎週日曜日早朝（夏場5:00〜9:30、冬場7:00〜）限定開催！1907年建造の赤い魚競売ホール（Fischauktionshalle）内でモーニングビールを片手にロック生演奏を聞くのが至高。",
        "tip_es": "⏰ ¡Abierto SÓLO los domingos por la mañana! Entra en la sala Fischauktionshalle a tomar una cerveza con música en directo.",
        "tip_zh": "⏰ 仅于每周日清晨开放（夏季5:00-9:30；冬季7:00起）！步入红砖 Fischauktionshalle 大厅，喝一杯早晨啤酒听摇滚乐。",
        "tip_fr": "⏰ Ouvert UNIQUEMENT le dimanche matin ! Entrez dans la Fischauktionshalle pour boire une bière en écouteant du rock en direct.",
        "tip_de": "⏰ NUR sonntags morgens geöffnet! In der Fischauktionshalle ein morgendliches Bier trinken und der Live-Band lauschen.",
        "price_en": "Free Entry (Food €4–€10)", "price_ja": "入場無料（屋台4〜10ユーロ）", "price_es": "Entrada libre (Comida 4€–10€)", "price_zh": "免费参观（小吃4-10欧）", "price_fr": "Gratuit (Food 4 €–10 €)", "price_de": "Eintritt frei (Imbiss 4 €–10 €)",
        "name_en": "Altona Fish Market", "name_ja": "Fischmarkt (Altona)（アルトナの魚市場＆フィッシュオークションホール）", "name_es": "Mercado de Pescado de Altona", "name_zh": "阿尔托纳鱼市", "name_fr": "Marché aux poissons d'Altona", "name_de": "Altonaer Fischmarkt & Fischauktionshalle"
    },
    # 38. Fischbrötchen-Buden
    {
        "id": "h_38",
        "name": "Fischbrötchen-Buden an den Landungsbrücken（桟橋のフィッシュブレートヒェン屋台群）",
        "category": "Café & Bistro", "rating": "★4.6", "locationZone": "city",
        "lat": 53.5458, "lng": 9.9675, "kids": True, "rain": False, "shopping": False, "free": False,
        "desc_en": "Iconic waterfront kiosks along the Landungsbrücken piers serving Hamburg's essential street food: crispy rolls packed with pickled Bismarck herring, smoked salmon, or North Sea shrimp.",
        "desc_ja": "ザンクト・パウリ桟橋沿いに並ぶハンブルクの定番ソウルフード屋台。酢漬けニシン（Bismarckherring）や北海小エビを挟んだパンサンド（Fischbrötchen）の専門店。",
        "desc_es": "Puestos en el muelle de Landungsbrücken que sirven el bocadillo de pescado (Fischbrötchen) con arenque, salmón o gambas.",
        "desc_zh": "沿 St. Pauli 码头长廊分布的当地街头小吃档。主打夹入腌渍鲱鱼（Bismarckhering）、烟熏三文鱼或北海小虾的鲜鱼面包汉堡（Fischbrötchen）。",
        "desc_fr": "Kiosques sur les embarcadères servant le sandwich au poisson (Fischbrötchen) au hareng, saumon ou crevettes.",
        "de": "Kult-Imbissbuden an den Landungsbrücken für den echten Hamburger Fischbrötchen-Genuss mit Bismarckhering oder Krabben.",
        "tip_en": "🍽️ Order 'Bismarckhering-Brötchen mit Zwiebeln' (pickled herring roll with onions) at Brücke 10 for the freshest catch directly overlooking the harbor traffic!",
        "tip_ja": "🍽️ 10番桟橋前にある有名店『Brücke 10』で『Bismarckhering-Brötchen（酢漬けニシンサンド・玉ねぎ添え）』を注文！港を行き交う大船を眺めながら食べるのが地元の流儀。",
        "tip_es": "🍽️ Pide un 'Bismarckhering-Brötchen' (bocadillo de arenque con cebolla) en el puesto Brücke 10 frente al puerto.",
        "tip_zh": "🍽️ 推荐在10号码头的著名小档 Brücke 10 点一份“Bismarckhering-Brötchen”（洋葱酸鲱鱼鲜包，约4.50欧）！",
        "tip_fr": "🍽️ Commandez un 'Bismarckhering-Brötchen' (sandwich au hareng avec oignons) au stand Brücke 10 !",
        "tip_de": "🍽️ An Brücke 10 ein frisches Bismarckhering-Brötchen mit Zwiebeln bestellen und den Hafenblick genießen!",
        "price_en": "Fischbrötchen: €4.50–€7.50", "price_ja": "魚パンサンド: 4.50〜7.50ユーロ", "price_es": "Bocadillo de pescado: 4,50€–7,50€", "price_zh": "鲜鱼面包：4.50-7.50欧", "price_fr": "Sandwich poisson : 4,50 €–7,50 €", "price_de": "Fischbrötchen: 4,50 €–7,50 €",
        "name_en": "St. Pauli Fish Roll Kiosks", "name_ja": "Fischbrötchen-Buden an den Landungsbrücken（桟橋のフィッシュブレートヒェン屋台群）", "name_es": "Puestos de Fischbrötchen en Landungsbrücken", "name_zh": "圣保利码头鲜鱼面包档", "name_fr": "Kiosques à Fischbrötchen de Landungsbrücken", "name_de": "Fischbrötchen-Buden an den Landungsbrücken"
    },
    # 50. Lübeck Altstadt & Holstentor (Suburban)
    {
        "id": "h_50",
        "name": "Lübeck: Altstadt & Holstentor (UNESCO)（リューベック：世界遺産旧市街＆ホルステン門）",
        "category": "Landmark", "rating": "★4.9", "locationZone": "suburban",
        "lat": 53.8664, "lng": 10.6797, "kids": True, "rain": True, "shopping": False, "free": True,
        "desc_en": "UNESCO World Heritage 'Queen of the Hanseatic League' 45 min from Hamburg, famous for its 1477 twin-towered red-brick Holstentor gate and Niederegger marzipan.",
        "desc_ja": "ハンブルクから列車で45分。『ハンザ同盟の女王』と称される世界遺産都市。1477年建造の2つの尖塔を持つ赤レンガのホルステン門（Holstentor）とマジパン（Marzipan）が象徴。",
        "desc_es": "Ciudad patrimonio UNESCO 'Reina de la Liga Hanseática' a 45 min de Hamburgo con la famosa puerta de ladrillo Holstentor de 1477.",
        "desc_zh": "距离汉堡45分钟车程的世界遗产名城，被称为“汉萨同盟之女王”。拥建于1477年双塔红砖 Holstentor 城门与 Niederegger 杏仁糖（Marzipan）。",
        "desc_fr": "Reine de la Ligue Hanséatique (UNESCO) à 45 min de Hambourg avec la porte médiévale Holstentor de 1477 et le massepain.",
        "de": "UNESCO-Welterbe-Stadt 'Königin der Hanse' mit dem weltberühmten Holstentor von 1477 und Niederegger Marzipan.",
        "tip_en": "🍽️ Visit Café Niederegger opposite the Town Hall to taste authentic Lübeck Marzipan walnut cake and buy chocolate-covered marzipan treats in the 2nd floor museum shop!",
        "tip_ja": "🍽️ 市庁舎前の老舗『Café Niederegger』へ！2階のマジパン博物館を見学後、伝統のアーモンド菓子マジパン入りのくるみケーキ（Marzipantorte）を味わうのが王道です。",
        "tip_es": "🍽️ Visita el Café Niederegger frente al Ayuntamiento para probar la tarta de mazapán y comprar mazapán cubierto de chocolate.",
        "tip_zh": "🍽️ 前往市政厅正对面的老字号 Café Niederegger！观赏2楼杏仁糖博物馆并现场品尝传统的核桃杏仁糖蛋糕（Marzipantorte）。",
        "tip_fr": "🍽️ Visitez le Café Niederegger en face de l'Hôtel de Ville pour déguster le gâteau au massepain traditionnel !",
        "tip_de": "🍽️ ins Café Niederegger gegenüber dem Rathaus gehen, das Marzipan-Museum im 2. Stock besuchen und Marzipantorte probieren!",
        "price_en": "Town Free (Holstentor €8)", "price_ja": "旧市街散策無料（ホルステン門内部: 8ユーロ）", "price_es": "Ciudad gratis (Holstentor 8€)", "price_zh": "古城免费（城门内部8欧）", "price_fr": "Ville gratuite (Holstentor 8 €)", "price_de": "Altstadt frei (Holstentor 8 €)",
        "name_en": "Lübeck Old Town & Holsten Gate", "name_ja": "Lübeck: Altstadt & Holstentor (UNESCO)（リューベック：世界遺産旧市街＆ホルステン門）", "name_es": "Casco Antiguo de Lübeck y Holstentor", "name_zh": "吕贝克古城与荷尔斯登门", "name_fr": "Vieille ville de Lübeck et Holstentor", "name_de": "Lübeck: Altstadt & Holstentor (UNESCO)"
    },
    # 52. Schloss Schwerin (Suburban)
    {
        "id": "h_52",
        "name": "Schloss Schwerin（シュヴェリーン城）",
        "category": "Landmark", "rating": "★4.9", "locationZone": "suburban",
        "lat": 53.6242, "lng": 11.4189, "kids": True, "rain": True, "shopping": False, "free": False,
        "desc_en": "Fairytale island palace in Lake Schwerin featuring 653 rooms, golden domes, and romantic French Orangery gardens, dubbed the 'Neuschwanstein of the North'.",
        "desc_ja": "シュヴェリーン湖の島に浮かぶ『北のノイシュヴァンシュタイン城』と称されるおとぎ話のような歴史主義宮殿。金のドーム屋根とオランジェリー庭園が美しい。",
        "desc_es": "Palacio de ensueño en una isla del lago Schwerin con 653 habitaciones, cúpulas doradas y jardines románticos.",
        "desc_zh": "屹立于什韦林湖岛之上的童话水上宫殿，誉为“北方的新天鹅堡”。拥有653间房间、金光闪闪的圆顶与法式宫廷花园。",
        "desc_fr": "Château féerique situé sur une île du lac de Schwerin avec ses dômes dorés et jardins à la française.",
        "de": "Märchenhaftes Residenzschloss auf einer Insel im Schweriner See mit goldenen Kuppeln und Barockgarten.",
        "tip_en": "📸 Walk across the castle bridge into the Orangery garden (Orangeriegarten) to capture the golden main dome reflected over Lake Schwerin!",
        "tip_ja": "📸 城の橋を渡って裏手のオランジェリー庭園（Orangeriegarten）へ！湖越しに黄金の主ドームといくつもの塔が水面に浮かぶ絵はがきビューが撮れます。",
        "tip_es": "📸 Camina por el puente hacia los jardines de la Orangerie para fotografiar la cúpula dorada reflejada en el lago.",
        "tip_zh": "📸 穿过城堡拱桥步入 Orangeriegarten 橘园花圃！以波光粼粼的湖水为前景，拍摄主金顶倒映水面的大景。",
        "tip_fr": "📸 Traversez le pont vers les jardins de l'Orangerie pour photographier le dôme doré se reflétant dans le lac.",
        "tip_de": "📸 Über die Schlossbrücke in den Orangeriegarten gehen für das perfekte Foto der goldenen Kuppel über dem See.",
        "price_en": "Palace: €8.50 (Gardens Free)", "price_ja": "宮殿: 8.50ユーロ（庭園無料）", "price_es": "Palacio: 8,50€ (Jardines gratis)", "price_zh": "宫殿：8.50 欧元（花园免费）", "price_fr": "Palais : 8,50 € (Jardins gratuits)", "price_de": "Schloss: 8,50 € (Garten frei)",
        "name_en": "Schwerin Castle", "name_ja": "Schloss Schwerin（シュヴェリーン城）", "name_es": "Castillo de Schwerin", "name_zh": "什韦林城堡", "name_fr": "Château de Schwerin", "name_de": "Schloss Schwerin"
    }
]

# Write to data/cities/hamburg.json
fpath = "data/cities/hamburg.json"
data = {
    "cityName": "Hamburg, Germany",
    "spots": hamburg_spots
}

with open(fpath, 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print(f"🎉 Successfully created {len(hamburg_spots)} spots in data/cities/hamburg.json")
