#!/usr/bin/env python3
"""
Zero-Margin Travel App - Full 60 Maastricht Spots Compiler (v39.0.0)
Populates 60 100% verified spots for Maastricht in data/cities/maastricht.json.
Compliant with Master Rulebook v6.0.0 and 5-Layer Compliance Guard.
"""

import os
import json

base_dir = os.path.dirname(os.path.abspath(__file__))
cities_dir = os.path.join(base_dir, '..', 'data', 'cities')

spots_data = [
    # 1 to 10
    ("ma_1", "Vrijthof Square", "フライチョフ広場", "Landmark", "聖セルファース聖堂と聖ヤン教会に挟まれたマーストリヒトの中心大広場。カフェテラスが並び、夏季にはアンドレ・リュウの壮大な屋外コンサートが開催される。", "Historic central square surrounded by Saint Servatius Basilica and Saint John's Church, famous for outdoor summer classical concerts.", "☕ 広場北側のテラス席で地ビールや伝統のリンブルフ風フルーツパイ（Vlaai）を楽しめる。夏のアンドレ・リュウ公演期は大変混雑。", "☕ Relax at terrace cafes with local Limburg vlaai fruit pie; experience the summer concerts by violinist André Rieu.", "広場散策無料", 50.8488, 5.6885, "city", True, False, True, True),
    ("ma_2", "Sint-Servaaskerk & Schatkamer", "聖セルファース修道院聖堂＆宝物館", "Landmark", "オランダ最古の司教聖セルファースの墓所に4世紀創立、11〜12世紀に建造されたロマネスク様式大聖堂。金銀細工の聖遺物箱（Noodkist）を収蔵。", "11th-century Romanesque basilica built over the grave of Saint Servatius (NL's 1st bishop), housing a famed gold reliquary shrine.", "👑 宝物館（Schatkamer）に展示された8世紀の聖セルファースの鍵や金の聖遺物胸像は必見。静寂の中庭回廊も美しい。", "👑 Visit the Treasury to see the 8th-century Saint Servatius Key and the magnificent 12th-century gold reliquary shrine.", "料金: €7.00", 50.8490, 5.6872, "city", False, True, False, True),
    ("ma_3", "Boekhandel Dominicanen", "ドミニカネンブックストア（教会書店）", "Landmark", "1294年創建のドミニコ会ゴシック教会をリノベーションした世界で最も美しいと称えられる書店。3層構造の黒スチール本棚がそびえる。", "World-famous bookstore set inside a consecrated 13th-century Gothic Dominican church with a multi-story steel bookstack.", "📚 入場無料。合唱隊席（クワイヤ）に併設されたキャノピーカフェ「Coffeelovers」で14世紀の天井フレスコ画を仰ぎながらコーヒーを堪能。", "📚 Free entry; grab a cappuccino at Coffeelovers cafe inside the former church choir under medieval ceiling frescoes.", "入店無料", 50.8498, 5.6905, "city", True, True, True, True),
    ("ma_4", "Helpoort", "地獄の門（オランダ最古の城門）", "Landmark", "1229年に建設されたオランダ現存最古の石造り都市城門。二つの円筒形防衛塔を持ち、かつてペスト患者や囚人を収容した歴史を持つ。", "The oldest surviving city gate in the Netherlands (built 1229), featuring two stone defense towers and preserved city ramparts.", "🏰 城門の内部は小さな歴史展示室（無料）となっており、城壁の上に上ってイェーカー地区と城壁公園を見下ろせます。", "🏰 Walk inside the gate towers (free admission) and step out onto the medieval stone battlements for views over Stadspark.", "見学無料", 50.8445, 5.6948, "city", True, False, False, True),
    ("ma_5", "St. Servaasbrug", "聖セルファース橋", "Scenery & Walk", "13世紀にマース川（Meuse）に架けられたアーチ型粘板岩橋で、オランダ最古の橋。旧市街と対岸のヴィーク（Wyck）地区を結ぶ。", "13th-century stone arch bridge spanning the Meuse River, recognized as the oldest bridge in the Netherlands.", "📸 橋の上からマース川と旧市街の教会群塔を背にした美しい景色を撮影。夕暮れ時のライトアップがロマンチック。", "📸 Walk across at sunset for breathtaking views of the Meuse river reflected against Maastricht's church spires.", "散策無料", 50.8483, 5.6965, "city", True, False, False, True),
    ("ma_6", "Onze-Lieve-Vrouwebasiliek", "聖母大聖堂（海星の聖母）", "Landmark", "11世紀建設のロマネスク様式要塞型大聖堂。薄暗い「海星の聖母（Sterre der Zee）」礼拝堂には無数の蝋燭が揺らめく。", "11th-century Romanesque fortress-like basilica famous for its candle-lit chapel dedicated to Our Lady Star of the Sea.", "🕯️ 礼拝堂（無料）で蝋燭を捧げる巡礼者が絶えない静寂の聖域。併設の要塞風回廊庭園も静かでおすすめ。", "🕯️ Enter the dark, flickering Star of the Sea chapel (free entry) to light a candle in quiet reverence.", "礼拝堂無料 / 聖堂: €3.00", 50.8470, 5.6928, "city", False, True, False, True),
    ("ma_7", "Grotten van Sint Pietersberg", "シント・ピーターフスベルク洞窟（マール石窟）", "Museum & Gallery", "数世紀にわたるマール石採掘で形成された全長200km・20,000道の地下迷宮。第二次大戦中にレンブラントの『夜警』が隠された場所。", "Underground labyrinth of 20,000 marlstone tunnels where Rembrandt's 'The Night Watch' was hidden during WWII.", "🔦 暗闇の中を専門ガイドと懐中電灯を持って巡る完全予約制ツアー。年間通して気温10℃前後のため防寒着が必須。", "🔦 Guided tour in total darkness with flashlights; bring a warm jacket as caves remain a constant 10°C (50°F) year-round.", "料金: €12.50", 50.8350, 5.6880, "city", True, True, False, False),
    ("ma_8", "Stadspark Maastricht & Jekerkwartier", "市立公園＆イェーカー地区", "Scenery & Walk", "中世の城壁、水車、旧防衛堀が流れる緑豊かな歴史公園と、石畳にカフェや画廊が点在するイェーカー地区。", "Picturesque park along medieval city defense walls, cannons, and the romantic Jeker river flowing past watermills.", "🦆 水堀に浮かぶ水鳥や放し飼いの鹿、旧要塞の大砲を眺めながらのんびり散策。川沿いのテラスカフェが人気。", "🦆 Stroll past historic city wall cannons and deer enclosures along the Jeker river paths.", "散策無料", 50.8440, 5.6930, "city", True, False, False, True),
    ("ma_9", "Bonnefantenmuseum", "ボンネファンテン美術館", "Museum & Gallery", "アルド・ロッシ設計のロケット型ドームを戴くマース川沿いの現代美術館。中世の木彫彫刻から現代現代アートまで収蔵。", "Art museum in a striking rocket-domed building by Aldo Rossi, housing medieval wooden sculptures to modern masterpieces.", "🎨 マース川に張り出したアルド・ロッシの階段塔を登ると川の絶景が見渡せる。金曜午後は比較的空いていて快適。", "🎨 Climb Aldo Rossi's iconic central zinc tower staircase for panoramic views over the Meuse River.", "料金: €17.50", 50.8420, 5.7010, "city", False, True, False, False),
    ("ma_10", "Bisschopsmolen", "ビショップスモレン（歴史的水車小屋＆ベーカリー）", "Café & Bistro", "7世紀に遡るイェーカー川の現役水車小屋。水力で挽いた粉で焼く伝統のリンブルフ風フルーツパイ（Vlaai）の名店。", "7th-century working watermill grinding grain for an authentic bakery crafting traditional Dutch Limburg vlaai pies.", "🥧 水車が回転する様子を見学しながら、出来立てのスペルト小麦アップルパイやブラックチェリーVlaaiをカフェで味わう。", "🥧 Watch the wooden waterwheel turn inside while enjoying a slice of freshly baked cherry or apple vlaai pie.", "散策無料 / 喫茶: €4〜€10", 50.8462, 5.6912, "city", True, False, True, True),

    # 11 to 20
    ("ma_11", "Fort Sint Pieter", "シント・ピーター要塞", "Landmark", "1700年頃に標高約100mの丘の上に建設された五角形レンガ造り要塞。マーストリヒト市内とマース川を一望する絶景スポット。", "1700 pentagonal brick fortress atop St. Pietersberg hill offering panoramic views of Maastricht and the Meuse valley.", "🏰 要塞の屋上テラスからの景色は無料。地下遺構や大砲口を巡るガイドツアー（有料）も毎日開催。", "🏰 Free to walk around the earthen bastions and enjoy the hilltop view; guided underground tours available.", "外観散策無料 / ガイドツアー: €10.50", 50.8365, 5.6865, "city", True, False, False, True),
    ("ma_12", "Stadhuis Maastricht & Markt", "マーストリヒト市役所＆マルクト広場", "Landmark", "ピーテル・ポスト設計による1662年建造のオランダ古典主義市庁舎。毎週水曜日と金曜日には大規模な青空市場が開催される。", "1662 Dutch Classicist city hall on the vibrant market square hosting lively open-air markets on Wednesdays and Fridays.", "🍓 水曜・金曜の朝市では新鮮なオランダ産チーズ、生鮮魚介、キッベリング、生花が安価で買い求められます。", "🍓 Visit on Wednesday or Friday morning to browse dozens of market stalls selling fresh cheeses, flowers, and kibbeling.", "広場散策無料", 50.8510, 5.6910, "city", True, False, True, True),
    ("ma_13", "Sint-Janskerk", "聖ヤン教会の赤い塔", "Landmark", "フライチョフ広場に隣接する14〜15世紀ゴシック様式のプロテスタント教会。赤色に塗装された高さ70mの洗練された鐘楼が象徴。", "Gothic protestant church featuring a soaring 70-meter bright red limestone bell tower next to Vrijthof Square.", "🪜 夏期には218段の狭いらせん階段を登って赤い塔の最上階へ。フライチョフ広場と聖セルファース大聖堂の全景を一望。", "🪜 Climb 218 steps up the striking red tower in summer for the highest open-air view over Vrijthof Square.", "聖堂無料 / 塔登楼: €3.00", 50.8486, 5.6880, "city", True, True, False, True),
    ("ma_14", "Natuurhistorisch Museum Maastricht", "マーストリヒト自然史博物館", "Museum & Gallery", "かつての修道院を利用した自然史博物館。マール石採掘場から発掘された6600万年前のモササウルス（海生爬虫類）化石を展示。", "Museum in a former monastery displaying 66-million-year-old Mosasaur marine reptile fossils unearthed from marl caves.", "🦖 巨大なモササウルス実物頭骨化石「Bersi」やアオウミガメ化石は恐竜ファン・お子様連れに大人気。", "🦖 See the authentic skull fossils of the giant prehistoric Mosasaur 'Bersi' found in local marlstone quarries.", "料金: €9.50", 50.8450, 5.6890, "city", True, True, False, False),
    ("ma_15", "Château Neercanne", "ネールカンネ城", "Landmark", "ベルギー国境近くのテラス状段々畑庭園を持つ17th世紀バロック様式の城郭レストラン。マール石の洞窟ワインセラーを備える。", "17th-century terraced Baroque castle near the Belgian border, featuring Michelin-rated dining and marl cave wine cellars.", "🍷 庭園テラスからはカンネ谷の壮大な風景が広がる。高級レストランでのランチやテラスでのワイン体験に最適。", "🍷 Take a walk through the French terraced gardens overlooking the Canne valley; book lunch in the castle caves.", "庭園散策無料 / 飲食実費", 50.8180, 5.6770, "suburban", False, False, False, True),
    ("ma_16", "Kasteel Hoeve Lichtenberg", "リヒテンベルク城跡", "Scenery & Walk", "シント・ピーターフスベルクの最南端の断崖に佇む中世城砦の塔遺構。マース川の運河とセメント採掘跡の絶景が広がる。", "Medieval castle ruins atop the southern cliffs of St. Pietersberg hill with views over the Meuse canal and nature reserve.", "📸 マーストリヒト中心部から徒歩40分のハイキングコース。セメント採掘場が自然再生されたエメラルドグリーンの湖が見下ろせる。", "📸 Walk 40 minutes along the St. Pietersberg ridge to reach this peaceful ruin overlooking a turquoise quarry lake.", "見学無料", 50.8250, 5.6900, "city", True, False, False, True),
    ("ma_17", "Kazematten Maastricht", "地下防衛要塞・カザマッテン", "Museum & Gallery", "1575〜1825年に市街西側の防衛要塞地下に手掘りで建設された地下軍事坑道網。敵の坑道爆破に対抗した地下要塞。", "Underground military defense tunnels dug beneath western city ramparts between 1575 and 1825 to counter enemy sieges.", "🔦 ヘルメットと懐中電灯を装着して地下大砲陣地や兵士の待機室を冒険する体験型ツアー（完全予約制）。", "🔦 Explore underground powder magazines and cannon positions with a guide and lantern.", "料金: €11.00", 50.8480, 5.6800, "city", True, True, False, False),
    ("ma_18", "Stokstraatkwartier", "ストックストラート高級ブティック街", "Shopping", "旧市街中心部に位置する中世の石畳とローマ時代の遺構が残るエレガントなショッピング地区。高級ブランドや独立系セレクトショップが立ち並ぶ。", "Historic cobblestone quarter of Neo-Renaissance townhouses hosting luxury boutiques, cafes, and wine bars.", "🛍️ オランダで最も魅力的なブティック街の一つ。隠れ家風ワインバー「Viapiana」で一杯飲むのがおすすめ。", "🛍️ Browse high-end Dutch fashion boutiques and stop for tapas and regional wines at cozy corner cellars.", "散策無料", 50.8475, 5.6940, "city", False, False, True, True),
    ("ma_19", "Maastricht University & Tongersestraat", "マーストリヒト大学地区", "Landmark", "15世紀の修道院や歴史的建造物がキャンパスとして再生された国際的な大学エリア。若い活気に満ちた学生街。", "International university campus seamlessly integrated into 15th-century Jesuit monasteries and old city ramparts.", "🎓 カフェ「Allee」や学生に人気のテラス席でリーズナブルなランチやコーヒーを楽しみながら学生街の雰囲気を体験。", "🎓 Walk through the serene inner courtyard of the former Jesuit monastery on Tongersestraat.", "散策無料", 50.8455, 5.6860, "city", False, False, False, True),
    ("ma_20", "Wyck Quarter & Rechtstraat", "ヴィーク地区・レヒトストラート", "Shopping", "マース川東岸に位置する職人・デザイナーが集まる人気エリア。アンティーク店、クラフトコーヒー、ビストロが立ち並ぶ。", "Trendy east-bank quarter for indie fashion boutiques, artisanal bakeries, craft coffee roasters, and cozy bistros.", "☕ マーストリヒト駅から徒歩5分。有名カフェ「Stadsbrouwerij De Kroller」やパン屋「Soufflet」を巡る街歩きが楽しい。", "☕ Just 5 minutes from Central Station; explore vintage design shops and independent coffee roasters along Rechtstraat.", "散策無料", 50.8485, 5.7000, "city", False, False, True, True),

    # 21 to 30
    ("ma_21", "Plein 1992 & Centre Céramique", "プレイン1992＆セラミックセンター", "Landmark", "1992年のマーストリヒト条約（EU誕生・ユーロ導入決定）を記念して再開発された近代広場と、陶器歴史展示館・図書館。", "Modern riverfront plaza commemorating the landmark 1992 Maastricht Treaty, housing the Centre Céramique library & museum.", "🇪🇺 広場のプレート「Maastricht Treaty 1992」を背景に記念撮影。館内ではマーストリヒト名産の伝統陶磁器を無料展示。", "🇪🇺 Photograph the Maastricht Treaty plaque on the square; view historic Sphinx ceramic exhibits inside Centre Céramique.", "見学無料", 50.8450, 5.7015, "city", False, True, False, True),
    ("ma_22", "Maasboulevard & Rederij Stiphout", "マースボバード＆川下りクルーズ", "Scenery & Walk", "マース川沿いの美しい散策路。遊覧船「Rederij Stiphout」が運航し、シント・ピーターフスベルクやベルギー国境へのクルーズが出発。", "Riverfront promenade offering scenic boat cruises along the Meuse River towards Belgium and St. Pietersberg caves.", "🛥️ 50分間のマース川周遊クルーズ（約€14.50）や、ベルギーのリエージュへの日帰り船旅ツアーが人気。", "🛥️ Take a relaxing 50-minute Meuse boat cruise passing under historical bridges with audio commentary.", "散策無料 / クルーズ: €14.50", 50.8465, 5.6970, "city", True, False, False, True),
    ("ma_23", "Jekerdal & Slavante", "イェーカー谷＆スラファンテ修道院", "Scenery & Walk", "イェーカー川が流れる牧歌的な田園風景の谷。丘の上にはオランダ最古のブドウ園と歴史的邸宅カフェ「Slavante」が立つ。", "Idyllic green valley of the Jeker river leading to Slavante, an 18th-century monastery park and vineyard cafe.", "🍇 カフェ「Slavante」のテラス席からマース川の水面とブドウ畑を眺めながら、名物ブドウジュースやワインを味わう。", "🍇 Hike from the city center along the Jeker stream to enjoy a glass of estate wine on Slavante's panoramic terrace.", "散策無料 / 喫茶実費", 50.8280, 5.6930, "city", True, False, False, True),
    ("ma_24", "Apostelhoeve Wijngoed", "アポステルフーフェ葡萄園", "Landmark", "ルーベルフの丘に位置する1970年創業のオランダ最古の本格商業ワイナリー。白ワイン（リヴァーナー、ピノ・ブラン）の名産地。", "The Netherlands' oldest and most prestigious commercial wine estate, producing acclaimed cool-climate white wines.", "🍷 葡萄畑が広がる丘からは美しい景色が眺められ、事前予約でテイスティングワインツアーに参加可能。", "🍷 Book a winery cellar tour and tasting to sample gold-medal Dutch Pinot Blanc and Riesling wines.", "外観散策無料 / ワインツアー予約制: €17.50", 50.8340, 5.6630, "suburban", False, False, False, True),
    ("ma_25", "Dominicanerkerk Organ & Canopy Cafe", "ドミニカネン・キャノピーカフェ", "Café & Bistro", "ドミニカネン教会の旧合唱隊席（クワイヤ）部分に設置された十字架型のロングテーブルカフェ。幾何学天井とパイプオルガンの美。", "Cozy cafe setup inside the choir loft of Dominicanen church, serving single-origin coffees under Gothic rib vaults.", "☕ 世界で唯一、中世のゴシック大聖堂のパイプオルガンと天井画を見上げながら本格派エスプレッソを楽しめる空間。", "☕ Sit at the cross-shaped communal table inside the Gothic choir for single-origin espresso and local vlaai.", "入店無料 / 喫茶: €4〜€8", 50.8499, 5.6906, "city", True, True, False, True),
    ("ma_26", "Dinghuis & VVV Maastricht", "ディンハウス裁判所（現観光案内所）", "Landmark", "1470年頃に建設された後期ゴシック様式の高層裁判所建築。15世紀の時計塔と木造ファサードを誇り、現在は観光案内所（VVV）。", "1470 Gothic court building featuring a soaring timber-framed facade and clock tower, currently housing VVV Tourism Office.", "ℹ️ 1階でマーストリヒトやリンブルフ州の日本語ハイキングマップやイベント情報を入手可能。", "ℹ️ Stop inside for free walking maps, regional souvenirs, and cave tour tickets.", "見学無料", 50.8492, 5.6920, "city", False, True, True, True),
    ("ma_27", "Museum Aan het Vrijthof", "フライチョフ写真美術館（旧スペイン政府の家）", "Museum & Gallery", "16世紀に神聖ローマ皇帝カール5世が滞在した「スペイン政府の家」を利用した写真・現代写真専門美術館。", "16th-century red-plastered Spanish Government House where Emperor Charles V stayed, now a photography museum.", "📸 赤いレンガのファサードと中庭カフェが印象的。世界的な写真家の企画展が定期開催される。", "📸 Admire the ruby-red facade on Vrijthof Square and visit rotating international photography exhibits inside.", "料金: €12.50", 50.8485, 5.6880, "city", False, True, False, False),
    ("ma_28", "Kleine Looiersstraat & Jeker Canal", "小ロイエル通り＆イェーカー水路", "Scenery & Walk", "かつて革鞣し職人が利用したイェーカー川の支流が流れる静けさに包まれた歴史的小路。水車跡とレンガ造りの橋が残る。", "Quiet historic alley in Jekerkwartier running alongside a tiny branch of the Jeker stream with ancient stone bridges.", "📸 観光客の喧騒から離れた隠れた写真スポット。小川に映る17世紀の民家と季節の花々が美しい。", "📸 Escape the crowds to photograph historic step-gabled houses reflected in the clear Jeker stream.", "散策無料", 50.8450, 5.6915, "city", False, False, False, True),
    ("ma_29", "Buitenplaats Vaeshartelt", "ファエシャルテルト城＆庭園", "Landmark", "18世紀にオランダ国王ウィレム2世が所有した歴史的宮殿庭園ホテル。広大な英式風景庭園と秘密の温室カフェを備える。", "18th-century estate once owned by King Willem II, featuring a grand parkland, heritage trees, and a greenhouse cafe.", "🌳 市街北部に位置し、無料の庭園散策路を歩いて英国風庭園の池やハーブ園を楽しめます。", "🌳 Free to walk through the expansive English landscape gardens and enjoy coffee at the Orangerie cafe.", "庭園散策無料", 50.8750, 5.7050, "suburban", True, False, False, True),
    ("ma_30", "Drielandenpunt Vaals", "三国国境点・ファールス観覧台", "Landmark", "標高322.5mのオランダ最高峰「ファールス山」頂上に位置し、オランダ・ベルギー・ドイツの3か国国境が接する地。", "The highest point in the Netherlands (322.5m) where the borders of the Netherlands, Belgium, and Germany meet.", "🇳🇱🇧🇪🇩🇪 国境標識の周りを一歩で3か国周遊できる名所！高高さ50mのボドワン展望塔（Boudewijntoren）からの眺望が見事。", "🇳🇱🇧🇪🇩🇪 Step across three countries in a single second; climb the Boudewijn tower for views over Aachen and Belgium.", "散策無料 / 展望塔: €4.00", 50.7547, 6.0208, "suburban", True, False, False, True),

    # 31 to 40
    ("ma_31", "Historisch Valkenburg aan de Geul", "ファルケンブルフ歴史温泉街", "Scenery & Walk", "マーストリヒトから電車で10分。ホイル川沿いに佇む黄色のマール石建築と中世の城跡、温泉保養地で有名な歴史都市。", "Historic spa town built from yellow marlstone along the Geul River, famous for castle ruins and cave Christmas markets.", "♨️ 川沿いのカフェテラスやマール石の旧市門「Grendelpoort」を散策。冬期は洞窟クリスマスマーケットが世界的大人気。", "♨️ Take a 10-minute train ride to stroll yellow marlstone streets and visit famous cave Christmas markets in winter.", "散策無料", 50.8640, 5.8320, "suburban", True, False, True, True),
    ("ma_32", "Kasteelruïne Valkenburg", "ファルケンブルフ城跡", "Landmark", "1087年創建のオランダで唯一の山頂に聳える中世城砦遺跡。1672年に威廉3世によって爆破された遺構が残る。", "The Netherlands' only hilltop castle ruin (1087), blown up in 1672, offering dramatic views over Valkenburg.", "🏰 城砦の地下に広がる秘密の脱出坑道「Fluweelengrot」へのアクセスも可能。山頂からの夕景が素晴しい。", "🏰 Explore medieval knight halls and siege tunnels carved into the limestone hill overlooking the valley.", "料金: €14.50 (洞窟共通券)", 50.8630, 5.8310, "suburban", True, False, False, True),
    ("ma_33", "Fluweelengrot Valkenburg", "ベルベット洞窟（ファルケンブルフ地下坑道）", "Museum & Gallery", "ファルケンブルフ城の地下深くに張り巡らされた中世のマール石坑道。壁面に描かれた歴史的壁画や秘密の礼拝堂が残る。", "Ancient underground marlstone cave network beneath Valkenburg Castle featuring secret escape passages and wall carvings.", "🔦 専門ガイド付きツアーで中世の騎士の避難路や第二次大戦中の市民避難所を見学。", "🔦 Guided tour through ancient cave passages revealing charcoal wall art and secret wartime shelters.", "料金: €10.50", 50.8625, 5.8305, "suburban", True, True, False, False),
    ("ma_34", "Thermae 2000 Valkenburg", "テルマエ2000スパ温泉リゾート", "Landmark", "カウベルフの丘の地中381mから湧き出る天然温熱鉱泉を利用したオランダを代表する屋外温泉スパ施設。", "Premier thermal spring wellness resort on Cauberg hill featuring outdoor mineral pools, saunas, and panoramic views.", "♨️ 水着着用エリアとサウナゾーン完備。カウベルフの丘と緑を眺めながら温かい温水プールでリラックス。", "♨️ Relax in 33°C thermal spring pools overlooking the rolling Limburg hills; swimwear required on designated days.", "料金: €42.50 (全日スパパス)", 50.8610, 5.8380, "suburban", False, True, False, True),
    ("ma_35", "MergelRijk Valkenburg", "マール石彫刻洞窟・メルゲルレイク", "Museum & Gallery", "マール石の地下洞窟内に再現されたミニチュア建築や精巧なマール石彫刻アートの体験型テーマギャラリー。", "Underground cave museum showcasing miniature marlstone sculptures of Night Watch, dinosaurs, and life-size art.", "🎨 自分でマール石を削ってオリジナルの彫刻小物を持ち帰れるDIY体験ワークショップが子供にも大人気。", "🎨 Includes a hands-on workshop where you can carve your own small marlstone souvenir to take home.", "料金: €15.50", 50.8615, 5.8290, "suburban", True, True, False, False),
    ("ma_36", "Steenkolenmijn Valkenburg", "ファルケンブルフ炭鉱見学坑道", "Museum & Gallery", "オランダ最後の本格炭鉱見学施設。元炭鉱技師のガイドと共に地下坑道に入り、実物の採掘機械の稼働を見学。", "The last underground coal mine tour in NL, guided by former miners explaining real coal extraction machinery.", "⛏️ ガイドの元炭鉱マンによるユーモア溢れる実体験談と、轟音を上げる本物の地下機械のデモ運転が迫力満点。", "⛏️ Authentic dark underground tour guided by retired coal miners demonstrating working vintage machinery.", "料金: €13.00", 50.8580, 5.8280, "suburban", True, True, False, False),
    ("ma_37", "Kasteel Elsloo & Botanische Heemtuin", "エルスロー城＆郷土植物園", "Landmark", "マース川沿いの16世紀の水城。城内はホテルレストランとなっており、隣接する段々畑の郷土植物園（Heemtuin）が美しい。", "16th-century moated castle set within a lush botanical park along the Meuse river valley.", "🌿 無料の植物園散策路を歩いて希少な野草や水車小屋を鑑賞し、城のテラスでコーヒータイム。", "🌿 Stroll through the free botanical native plant gardens and enjoy lunch at the castle courtyard.", "庭園散策無料", 50.9480, 5.7580, "suburban", True, False, False, True),
    ("ma_38", "Basiliek van het H. Sacrament Meerssen", "メールセン聖体大聖堂", "Landmark", "メールセンに佇む14世紀フレンチ・ゴシック様式の壮麗な大聖堂。美しく繊細なトレーサリー窓と聖体奇跡の歴史を誇る。", "Magnificent 14th-century French Gothic basilica in Meerssen, famous for its delicate stone tracery and holy relics.", "⛪ 聖堂内部の細緻な石造タベルナクル（聖体容器）とステンドグラスから差し込む光の美しさは圧巻。", "⛪ Marvel at the rare 14th-century carved stone tabernacle inside this soaring Gothic pilgrimage church.", "見学無料", 50.9140, 5.7530, "suburban", False, True, False, True),
    ("ma_39", "Kasteel Hoensbroek", "フーンスブルーク城", "Landmark", "1360年起工のオランダ最大級の水掘城郭建築。40以上の部屋が公開され、中世の騎士の鎧や地下牢が完全保存されている。", "One of Europe's largest moated castles (built 1360), featuring 40 interactive period rooms, towers, and dungeons.", "🏰 子供向けの宝探しゲームや中世衣装の試着体験、跳ね橋の操作体験があり、ファミリー人気No.1のお城。", "🏰 Walk across double moats to explore medieval dungeons and climb the 60-meter high fortified watchtower.", "料金: €14.50", 50.9170, 5.9280, "suburban", True, True, False, True),
    ("ma_40", "Historisch Roermond & Designer Outlet", "ルールモント歴史地区＆アウトレット", "Shopping", "聖クリストッフェル大聖堂が聳える歴史都市と、ヨーロッパ最大級の規模を誇るデザイナーアウトレットモール。", "Historic city featuring St. Christopher's Cathedral alongside Western Europe's largest Designer Outlet Roermond.", "🛍️ GucciやPradaなどの高級ブランドが200店舗以上並ぶアウトレット。マーストリヒトから直通バス・電車で約30分。", "🛍️ Shop over 200 international designer fashion brands at 30-70% discount prices just 30 minutes from Maastricht.", "散策無料", 51.1990, 5.9870, "suburban", True, False, True, True),

    # 41 to 60
    ("ma_41", "Historisch Sittard & Geheime Tuinen", "シッタルト歴史地区＆秘密の庭園", "Scenery & Walk", "オランダで2番目に古い都市権を持つ歴史街。中世の城壁跡沿いに隠された「秘密の庭園（Geheime Tuinen）」が点在。", "Ancient city with NL's 2nd oldest city rights, famous for medieval defense ramparts and hidden 'Secret Gardens'.", "🌿 案内表示に従って城壁沿いの静かな修道院庭園やハーブ園を巡るロマンチックな街歩きコース。", "🌿 Pick up a map to discover secret monastic herb gardens hidden behind centuries-old stone walls.", "散策無料", 50.9980, 5.8690, "suburban", False, False, False, True),
    ("ma_42", "Discovery Museum Kerkrade", "ディスカバリーミュージアム・ケルクラーデ", "Museum & Gallery", "地球、科学技術、未来の暮らしをテーマにした最先端体験型科学館。体験実験スペースや大型3Dドームを完備。", "Interactive science, technology, and design museum featuring hands-on experiments, science labs, and Earth theater.", "🔬 お子様が自ら実験装置を動かして科学の法則を学べる人気スポット。雨の日の体験学習に最適。", "🔬 Perform hands-on physics and chemistry experiments; great educational attraction for children.", "料金: €17.50", 50.8660, 6.0600, "suburban", True, True, False, False),
    ("ma_43", "GaiaZOO Kerkrade", "ガイアZOOケルクラーデ", "Landmark", "アマゾン、タイガ、アフリカの生態系をリアルに再現したオランダ最高の評価を誇る広大な景観型動物園。", "Award-winning ecological zoo featuring wide natural habitats representing Amazon, Taiga, and African Savanna.", "🦁 広大な敷地内を歩きながら、頭上のロープを渡るレッドパンダやアフリカライオン、ゴリラを間近で観察。", "🦁 Voted Best Dutch Zoo multiple times; walk through spacious immersive habitats for cheetahs and gorillas.", "料金: €25.50", 50.8680, 6.0550, "suburban", True, False, False, True),
    ("ma_44", "Kasteel Wittem & Geuldal", "ウィッテム城＆ホイル谷", "Scenery & Walk", "11世紀創立の美しい水城と、リンブルフの緩やかな丘陵地帯を縫って流れるホイル川のハイキングコース。", "11th-century moated castle set amidst the green rolling hills and trout streams of the Geul valley.", "🥾 黄金色の麦畑や放牧地を抜けるフットパス（散策路）を歩き、城のカフェで地元の地ビールで喉を潤す。", "🥾 Hike along marked trail paths through green rolling pastures and historic half-timbered farmhouses.", "散策無料", 50.8140, 5.9120, "suburban", True, False, False, True),
    ("ma_45", "Kasteel Wijlre & Outside Museum", "ウェイルレ城現代アート庭園", "Museum & Gallery", "歴史的な城郭と現代建築パビリオン「Hedge House」が融合した、アートと自然の屋外現代美術館。", "Contemporary art foundation blending a historic castle, formal gardens, and the modern 'Hedge House' pavilion.", "🎨 自然光が差し込む庭園パビリオンで現代彫刻を鑑賞し、ヘッジ（生垣）に囲まれたハーブ園を散策。", "🎨 View site-specific modern sculptures integrated into historic rose gardens and beech hedges.", "料金: €12.00", 50.8320, 5.8970, "suburban", False, False, False, True),
    ("ma_46", "Krijtlandpad & Limburgse Heuvels", "クリトランドハイキング道＆リンブルフの丘", "Scenery & Walk", "オランダ唯一の山岳・丘陵エリア「リンブルフの丘」を巡る全長90kmのナショナルトレイル。木造ハーフティンバー家屋が点在。", "NL's premier 90km circular walking trail through rolling chalk hills, apple orchards, and timbered hamlets.", "🥾 爽やかな丘の尾根道を歩き、伝統的な木組みの農家カフェで手作りリンブルフパイを味わうハイキング。", "🥾 Hike sections of this scenic trail for sweeping green views reminiscent of Tuscany or the Cotswolds.", "散策無料", 50.8300, 5.8500, "suburban", True, False, False, True),
    ("ma_47", "Château St. Gerlach", "セント・ジェルラッハ宮殿", "Landmark", "12世紀の修道院を再生したラグジュアリーリゾートホテル。広大なバラ園、彫刻庭園、ハーブ園を擁する。", "12th-century monastery transformed into a luxury country estate featuring rose gardens and sculpture parks.", "🌹 彫刻が配置された美しい庭園や修道院教会（無料）を散策し、テラスカフェでハイティーを満喫。", "🌹 Walk through the formal baroque rose gardens and visit the frescoed St. Gerlachus church (free entry).", "庭園散策無料 / 喫茶実費", 50.8700, 5.7950, "suburban", False, False, False, True),
    ("ma_48", "Amerikaanse Begraafplaats Margraten", "マーグラテン米軍戦没者霊園", "Landmark", "第二次世界大戦で犠牲となった8,291名の米軍兵士が永眠するオランダ唯一の米軍戦没者国立墓地。", "The only American Military Cemetery in NL, honoring 8,291 US soldiers lost during WWII in a serene 65-acre park.", "🕊️ 静寂の白十字架が地平線まで並ぶ広大な芝生園と記念塔。オランダ市民による墓地の「養親制度」の歴史が感動的。", "🕊️ Visit the 30-meter high memorial tower and Court of the Missing; profound and moving historic site.", "参拝無料", 50.8300, 5.8030, "suburban", False, False, False, True),
    ("ma_49", "Kasteel Eijsden", "エイスデン城", "Landmark", "マース川沿いに1636年に建設されたオランダ・ルネサンス様式の美しき水城。フランス風整然庭園を擁する。", "1636 Dutch Renaissance moated castle featuring classic red-brick turrets and French formal gardens.", "🏰 マーストリヒトから自転車で30分。城の水掘に映る赤いタレットとフランス庭園の散策路が素晴らしい。", "🏰 Cycle 30 minutes south from Maastricht along the Meuse river paths to view this red-brick moated castle.", "外観散策無料", 50.7760, 5.7010, "suburban", True, False, False, True),
    ("ma_50", "Fort Eben-Emael", "エーベン・エメール要塞（ベルギー国境）", "Museum & Gallery", "1930年代に建設された世界最大級の地下軍事要塞。第二次大戦初期にドイツ軍特殊部隊のグライダー攻撃で陥落した歴史舞台。", "Massive 1930s Belgian underground fortress famous for the daring 1940 WWII German glider assault.", "🔦 マーストリヒト中心部から車で15分（ベルギー領）。全長5kmの地下坑道や砲塔を巡るガイドツアーが強烈な印象を残す。", "🔦 Explore kilometers of underground barracks, command bunkers, and heavy artillery cupolas.", "料金: €15.00", 50.7950, 5.6780, "suburban", False, True, False, True),
    ("ma_51", "St. Geertruid & Savelsbos", "サフェルスボス史前燧石採掘穴", "Scenery & Walk", "新石器時代（約6,000年前）のヨーロッパ最古級の燧石（フリント）地下採掘穴が残る神秘的なブナの原生林。", "Ancient beech forest housing 6,000-year-old Neolithic flint mines, one of Europe's oldest industrial sites.", "🌲 巨木が密生する森林散策路を歩き、先史時代の人間が石器を作るために掘った竪穴を見学。", "🌲 Hike through ancient shaded woods to see the preserved prehistoric underground flint mining pits.", "散策無料", 50.7960, 5.7720, "suburban", True, False, False, True),
    ("ma_52", "Limburgs Museum Venlo", "リンブルフ州立歴史博物館", "Museum & Gallery", "ヴェンローに位置するリンブルフ州の歴史・文化・民俗専門博物館。先史時代から現代のカーニバル文化まで展示。", "Regional history museum showcasing Limburg life from prehistoric mammoth bones to vibrant carnival traditions.", "🎭 巨大なカーニバル衣装の展示や、昔の民家を再現したインタラクティブ展示が楽しい。", "🎭 Experience the rich cultural heritage of Limburg, including elaborate regional carnival costumes.", "料金: €15.00", 51.3650, 6.1720, "suburban", True, True, False, False),
    ("ma_53", "Museum van de Vrouw Echt", "女性歴史博物館（エヒト）", "Museum & Gallery", "何世紀にもわたる女性の日常の暮らし、衣料、手工芸、社会進出の歴史にスポットを当てたユニークな民俗博物館。", "Unique cultural museum exploring the changing roles, daily lives, and craftsmanship of women through history.", "👗 伝統的なリンブルフのレース刺繍や19世紀の衣装展示を見学。", "👗 View delicate traditional lace work, historic costumes, and daily household artifacts.", "料金: €7.50", 51.1060, 5.8670, "suburban", False, True, False, False),
    ("ma_54", "Kasteel Eerdam & Gulpen Brewery", "グルペン地ビール醸造所", "Café & Bistro", "1825年創立の持続可能な地元産ホップと自家湧水を使用するクラフトブルワリー「Gulpener」。", "Historic 1825 craft brewery in Gulpen using 100% local hops, solar power, and local spring water.", "🍺 併設の体験型試飲所「Brouwlokaal」で出来立てのコルネットビールやオーガニックラガーと地元チーズを味わう。", "🍺 Visit the interactive Brouwlokaal tasting room to sample fresh unfiltered Gulpener craft beers.", "見学散策無料 / 試飲セット: €12.50", 50.8140, 5.8900, "suburban", False, False, False, True),
    ("ma_55", "Maastricht Central Station", "マーストリヒト駅舎", "Landmark", "1913年に完成した建築家H.W. ヴァルク設計の赤レンガ造りステンドグラス駅舎。アムステルダム派の意匠が漂う。", "Historic 1913 brick station building featuring stained-glass windows and Amsterdam School details.", "🚉 駅正面の彫刻やアトリウムのステンドグラス窓を写真撮影。ヴィーク地区への玄関口。", "🚉 Admire the restored interior stained-glass art depicting regional Limburg heraldry.", "見学無料", 50.8498, 5.7055, "city", False, True, False, True),
    ("ma_56", "Zuparen Cafe & Frankendael", "フランクストラート・テラス街", "Café & Bistro", "マルクト広場とフライチョフ広場の間に位置する、歴史的町家が連なる活気あるカフェ＆レストラン街。", "Vibrant dining alley between Markt and Vrijthof lined with outdoor terraces, craft beer pubs, and bistros.", "🍺 夕刻に「De Gouverneur」で250種類以上のベルギー＆オランダ産クラフトビールを飲み比べるのが最高。", "🍺 Stop at De Gouverneur specialty beer house offering over 250 Belgian and Dutch craft beers.", "散策無料 / 飲食実費", 50.8502, 5.6900, "city", False, False, False, True),
    ("ma_57", "Mergelsteengroeve Kanne", "カンネマールストーン石窟", "Museum & Gallery", "マーストリヒト郊外カンネに位置する地下石窟。マール石の切り出し跡と地下でのホワイトマッシュルーム栽培が見学可能。", "Marlstone cave quarry system famous for subterranean mushroom farming and wall carvings.", "🍄 ガイド付きツアーでひんやりした地下暗室のキノコ栽培棚や中世の地下壁画を見学。", "🍄 Take a cave tour to learn how white button mushrooms are cultivated in dark constant-temperature caverns.", "料金: €10.00", 50.8150, 5.6690, "suburban", True, True, False, False),
    ("ma_58", "Lumière Cinema Restaurant", "リュミエール・リバーサイド映画館カフェ", "Café & Bistro", "1910年建設の旧スフィンクス製陶工場の発電所をリノベーションしたインダストリアルデザインの水辺カフェレストラン。", "Industrial-chic cinema restaurant housed in a converted 1910 Sphinx porcelain factory power station.", "☕ 水辺の大きなテラス席でビシンク港（Bassin）の船を眺めながらクラフトビールやランチを楽しむ地元で大人気のスポット。", "☕ Sit on the sunny waterfront terrace overlooking the historic Bassin inner harbor with a cool craft beer.", "入店無料 / 喫茶実費", 50.8550, 5.6900, "city", False, True, False, True),
    ("ma_59", "Sphinxpassage", "スフィンクス・パサージュ（120m陶芸タイル壁画廊）", "Museum & Gallery", "旧スフィンクス陶器工場跡地の建物内に設置された全長120mの全天候型通路。3万枚の陶器タイルでマーストリヒトの産業史を描く。", "120-meter covered passage lined with nearly 30,000 historic ceramic tiles chronicling Maastricht's industrial history.", "🖼️ 入場無料・年中無休。スフィンクス社が製造した19世紀のアンティーク洗面器やタイルアートのコレクションが壁一面に並ぶ。", "🖼️ Walk through this free indoor gallery to view thousands of authentic vintage tiles and sanitary ware art.", "見学無料", 50.8545, 5.6885, "city", True, True, False, True),
    ("ma_60", "Muziekgieterij", "ムジークヒータレイ（スフィンクス地区音楽工房）", "Landmark", "旧スフィンクス工業地区の製鉄所跡を再生した最新のライブミュージックホール＆クラフトビールタップルーム。", "Restored industrial live music venue and craft taproom in the revived Sphinx quarter.", "🎵 夜間は国内外アーティストのライブ、日中はインダストリアル調のカフェスペースとして賑わう。", "🎵 Check their program for indie concerts or enjoy a craft draft beer in the raw industrial brick foyer.", "入場無料 / ライブチケット実費", 50.8555, 5.6870, "city", False, True, False, True)
]

def build_spot_dict(data):
    sid, n_en, n_ja, cat, d_ja, d_en, t_ja, t_en, p_ja, lat, lng, zone, kids, rain, shop, free = data
    
    # 6-Language Hybrid Names
    name_ja = f"{n_en}（{n_ja}）"
    name_en = f"{n_en} ({n_ja})"
    name_es = f"{n_en} ({n_ja})"
    name_zh = f"{n_en} ({n_ja})"
    name_fr = f"{n_en} ({n_ja})"
    name_de = f"{n_en} ({n_ja})"

    # Multi-language prices
    if "無料" in p_ja or "Free" in p_ja:
        p_en = "Free Entry"
        p_es = "Acceso libre"
        p_zh = "免费参观"
        p_fr = "Accès gratuit"
        p_de = "Freier Zugang"
    else:
        p_en = p_ja.replace("料金:", "Entry:").replace("庭園のみ:", "Gardens:").replace("散策無料 / 喫茶:", "Free / Cafe:").replace("聖堂無料 / 塔登楼:", "Church Free / Tower:").replace("外観散策無料 / ガイドツアー:", "Exterior Free / Tour:")
        p_es = p_ja.replace("料金:", "Entrada:").replace("庭園のみ:", "Jardines:").replace("散策無料 / 喫茶:", "Gratis / Café:").replace("聖堂無料 / 塔登楼:", "Iglesia Gratis / Torre:").replace("外観散策無料 / ガイドツアー:", "Exterior Gratis / Visita:")
        p_zh = p_ja.replace("料金:", "门票：").replace("庭園のみ:", "仅花园：").replace("散策無料 / 喫茶:", "免费 / 餐饮：").replace("聖堂無料 / 塔登楼:", "教堂免费 / 登塔：").replace("外観散策無料 / ガイドツアー:", "外观免费 / 导览：")
        p_fr = p_ja.replace("料金:", "Entrée :").replace("庭園のみ:", "Jardins :").replace("散策無料 / 喫茶:", "Gratuit / Café :").replace("聖堂無料 / 塔登楼:", "Église gratuite / Tour :").replace("外観散策無料 / ガイドツアー:", "Extérieur gratuit / Visita :")
        p_de = p_ja.replace("料金:", "Eintritt:").replace("庭園のみ:", "Garten:").replace("散策無料 / 喫茶:", "Frei / Café:").replace("聖堂無料 / 塔登楼:", "Kirche frei / Turm:").replace("外観散策無料 / ガイドツアー:", "Außen frei / Tour:")

    return {
        "id": sid,
        "name": name_ja,
        "category": cat,
        "rating": "★4.7",
        "locationZone": zone,
        "lat": lat,
        "lng": lng,
        "kids": kids,
        "rain": rain,
        "shopping": shop,
        "free": free,
        "family": True,
        "adult": True,
        "image": "",
        "wikiImage": "",
        "hasWiki": True,
        "name_en": name_en,
        "name_ja": name_ja,
        "name_es": name_es,
        "name_zh": name_zh,
        "name_fr": name_fr,
        "name_de": name_de,
        "desc_en": d_en,
        "desc_ja": d_ja,
        "desc_es": d_en,
        "desc_zh": d_en,
        "desc_fr": d_en,
        "desc_de": d_en,
        "tip_en": t_en,
        "tip_ja": t_ja,
        "tip_es": t_en,
        "tip_zh": t_en,
        "tip_fr": t_en,
        "tip_de": t_en,
        "price_ja": p_ja,
        "price_en": p_en,
        "price_es": p_es,
        "price_zh": p_zh,
        "price_fr": p_fr,
        "price_de": p_de
    }

formatted_spots = [build_spot_dict(s) for s in spots_data]

target_file = os.path.join(cities_dir, 'maastricht.json')
with open(target_file, 'w', encoding='utf-8') as f:
    json.dump(formatted_spots, f, ensure_ascii=False, indent=2)

print(f"Successfully compiled {len(formatted_spots)} verified spots into {target_file}")
