#!/usr/bin/env python3
"""
Zero-Margin Travel App - Full 60 Utrecht Spots Compiler (v38.0.0)
Populates 60 100% verified spots for Utrecht in data/cities/utrecht.json.
Compliant with Master Rulebook v6.0.0 and 5-Layer Compliance Guard.
"""

import os
import json

base_dir = os.path.dirname(os.path.abspath(__file__))
cities_dir = os.path.join(base_dir, '..', 'data', 'cities')

spots_data = [
    # 1 to 10
    ("ut_1", "Domtoren Utrecht", "ドム塔", "Landmark", "1321〜1382年に建造された高さ112.5mのオランダで最も高い中世ゴシック様式の教会塔。465段の石段を誇るユトレヒトの象徴。", "The tallest church tower in the Netherlands (112.5 meters), built between 1321 and 1382 in Gothic style.", "🪜 465段の石段をガイドと共に登る完全予約制ツアー。2024年に5年間の修復工事が完工し、夜間ライトアップと展望台がリニューアル。", "🪜 465-step guided tour requires advance booking online; major 5-year restoration completed in 2024 with new illumination.", "料金: €13.50", 52.0906, 5.1213, "city", True, True, False, False),
    ("ut_2", "Domkerk & Pandhof", "ドム教会＆修道院の中庭", "Landmark", "1254年起工のゴシック大聖堂。1674年の竜巻大竜巻で身廊が倒壊しドム塔と分離。隣接する14世紀の修道院中庭（Pandhof）は静寂の庭園。", "13th-century Gothic cathedral separated from Domtoren by a 1674 tornado storm, featuring a 14th-century quiet cloister garden.", "🌿 聖堂への入場は無料（寄付推奨）。聖堂裏手にひっそりと佇むゴシック調アーチに囲まれた中庭「Pandhof」は最高の写真スポット。", "🌿 Free entry to cathedral hall (donations welcome). Step into the Pandhof cloister garden surrounded by Gothic arches.", "聖堂・中庭無料", 52.0908, 5.1225, "city", False, True, False, True),
    ("ut_3", "Oudegracht & Werfkelder", "オウデフラハト運河＆蔵テラスカフェ", "Scenery & Walk", "12世紀に開削された歴史的二層構造運河。水面高さの旧倉庫（Werfkelder）がカフェやレストランテラスに再生されている世界唯一の都市景観。", "12th-century two-level canal unique to Utrecht, featuring medieval water-level wharf cellars converted into cafes.", "☕ 運河沿いの階段を下り、水面と同じ高さにある蔵テラス席で地ビールやランチを楽しむのがユトレヒト特有の体験。", "☕ Walk down the stone stairs to street-level wharf cellars for lunch or craft beer right at the water's edge.", "散策無料", 52.0915, 5.1185, "city", True, False, False, True),
    ("ut_4", "Nijntje Museum", "ミッフィーミュージアム（ディック・ブルーナ）", "Kids & Family", "ディック・ブルーナが描いたミッフィー（オランダ名: Nijntje）の世界を五感で体験できる未就学児〜小学生向け世界唯一の体験型ミュージアム。", "The world's only interactive museum dedicated to Dick Bruna's character Miffy (Nijntje), designed for young children.", "🐰 未就学児〜6歳程度のお子様連れに大人気。WEB完全日時指定予約制（土日や長期休みは数週間前に完売するため早めの確保が必須）。", "🐰 Extremely popular for toddlers and young kids; online tickets sell out weeks in advance for weekends and holidays.", "料金: €12.50 (2-6歳) / €8.00 (大人)", 52.0833, 5.1245, "city", True, True, False, False),
    ("ut_5", "Rietveld Schröderhuis", "リートフェルト・シュローダー邸", "Museum & Gallery", "ヘリット・リートフェルトが1824年に手掛けたデ・ステイル（De Stijl）運動のモダニズム建築の最高峰。ユネスコ世界遺産。", "1924 De Stijl architectural masterpiece by Gerrit Rietveld featuring sliding walls and primary colors, UNESCO World Heritage.", "🏠 定員が極少数の完全予約制ガイドツアー（約€19.00）。2階の可動式壁が仕切られる様子を実演で見学可能。", "🏠 Very limited capacity; mandatory online booking in advance. Guides demonstrate the famous 2nd-floor sliding walls.", "料金: €19.00 (オーディオガイド込)", 52.0853, 5.1475, "city", False, True, False, False),
    ("ut_6", "Centraal Museum Utrecht", "ユトレヒト中央美術館", "Museum & Gallery", "1838年創立のオランダ最古の市立美術館。オランダ黄金時代の画家ヨアヒム・ウテワールやディック・ブルーナの原画スタジオを再現。", "The oldest municipal museum in NL (1838), holding Dutch Golden Age masterpieces and Dick Bruna's original studio atelier.", "🎨 ディック・ブルーナの直筆スケッチや彼が実際に使用した作業デスク・絵の具が再現された最上階のアトリエ展示はファン必見。", "🎨 Visit the top floor to see Dick Bruna's authentic preserved studio atelier with his original drawing desk.", "料金: €16.50", 52.0835, 5.1250, "city", True, True, False, False),
    ("ut_7", "Museum Speelklok", "ミュージアム・スイールクロック（自動演奏楽器）", "Museum & Gallery", "18世紀以降の大型バレルオルガン、ストリートオルガン、自動演奏ピアノ、カラクリ時計が集まる音楽の博物館。", "Interactive museum housed in a medieval church, showcasing self-playing musical clocks, barrel organs, and orchestrions.", "🎶 45分ごとに開催される専門ガイドのツアーに参加すると、巨大な木製ストリートオルガンやオルケストリオンの生演奏を聴ける。", "🎶 Join the enthusiastic guided musical tour every 45 minutes to hear historic self-playing organs perform live music.", "料金: €15.50", 52.0910, 5.1198, "city", True, True, False, False),
    ("ut_8", "Spoorwegmuseum", "オランダ鉄道博物館", "Museum & Gallery", "1874年建造の旧マリエバーン駅舎を利用した鉄道テーマパーク。実物の蒸気機関車、王室専用列車、暗闇ライドアトラクションを完備。", "Interactive railway museum in historic 1874 Maliebaan station, featuring steam locomotives and dark rides.", "🚂 映画アトラクション「De Grote Ontdekking」や蒸気機関車シミュレーターなどがあり、雨の日のファミリー人気No.1。", "🚂 Top rainy-day attraction for families; features vintage royal carriages and the interactive 'Great Discovery' ride.", "料金: €19.50", 52.0880, 5.1320, "city", True, True, False, False),
    ("ut_9", "Kasteel de Haar", "デ・ハール城", "Landmark", "19世紀末に建築家ピエール・カイペルスが男爵家の為に再建したオランダ最大かつ最も豪華な水掘中世再現城砦。", "The largest and most luxurious castle in the Netherlands, rebuilt in Neo-Gothic style by Pierre Cuypers around 1892.", "🏰 ユトレヒト中央駅からバスまたは車で約20分。広大なロマンチック公園庭園と豪華な城内装飾はまさに童話の世界。", "🏰 Reached in ~20 minutes by bus or car from Utrecht; explore 135 acres of English landscape gardens and moats.", "庭園のみ: €7.00 / 城内共通券: €19.00", 52.1215, 4.9860, "suburban", True, True, False, False),
    ("ut_10", "DOMunder", "ドムアンダー考古学地下体験", "Museum & Gallery", "ドム広場の地下深くに残る2,000年前のローマ帝国の城塞「Traiectum」の遺構と中世大聖堂の基礎を懐中電灯で巡る体験。", "Underground archaeological discovery tour beneath Dom Square tracing 2,000 years from Roman fort Traiectum.", "🔦 予約制の暗闇体験。ハイテク懐中電灯センサーを遺構にかざすと、古代ローマや1674年大竜巻の歴史音声が流れる。", "🔦 Equipped with a smart interactive flashlight that activates audio stories when pointed at Roman wall ruins.", "料金: €14.00", 52.0906, 5.1215, "city", True, True, False, False),

    # 11 to 20
    ("ut_11", "TivoliVredenburg", "ティヴォリ・フレーデンブルフ", "Landmark", "クラシック、ポップ、ジャズ、電子音楽の5つの独立したホールが立体的に組み合わされた最先端音楽複合建築。", "Architectural music complex featuring five distinct concert halls for classical, pop, jazz, and club events.", "🎵 1階のパブリックカフェ「Danel」や「Het Gegeven Paard」で運河を眺めながら食事やクラフトビールを楽しめる。", "🎵 Stop by the ground-floor canalside bar Het Gegeven Paard for craft beer before attending a live concert.", "館内散策無料 / 公演チケット実費", 52.0920, 5.1130, "city", False, True, False, True),
    ("ut_12", "Botanische Tuinen Universiteit Utrecht", "ユトレヒト大学植物園（ホーフディク要塞）", "Scenery & Walk", "19世紀の軍事防衛要塞（Fort Hoofddijk）の上に造園されたオランダ最古級の大学植物園。ヨーロッパ最大級のロックガーデンを誇る。", "University botanical garden set atop 19th-century Fort Hoofddijk, home to Europe's largest rock garden.", "🪨 3月〜11月開園。要塞の水掘と石垣の間に咲く高山植物や温室の熱帯植物・バタフライハウスが見どころ。", "🪨 Open March through November; admire alpine flora built over fort bastions and the tropical butterfly greenhouse.", "料金: €10.00", 52.0870, 5.1700, "suburban", True, False, False, True),
    ("ut_13", "Neude & Voormalig Hoofdpostkantoor", "ネウデ広場＆旧中央郵便局図書館（Bibliotheek Neude）", "Landmark", "ユトレヒトの一番のカフェ広場ネウデに佇む、1924年建造のアムステルダム派アーチ状黄黒煉瓦の元中央郵便局（現図書館）。", "Vibrant central square featuring Bibliotheek Neude, an impressive 1924 Amsterdam School brick postal palace.", "📚 図書館内1階の彫刻がそびえる大ホールは無料自由見学可能。カフェ「Meneer Potter」で読書やコーヒータイム。", "📚 Walk inside the magnificent barrel-vaulted main hall of the former post office for free; stop at Cafe Meneer Potter.", "見学無料", 52.0930, 5.1180, "city", False, True, False, True),
    ("ut_14", "Museum Catharijneconvent", "カタリネコンフェント中世修道院美術館", "Museum & Gallery", "15世紀の修道院建築を利用したオランダのキリスト教美術博物館。レンブラントの初期作や中世の金銀細工聖品を収蔵。", "Museum of Dutch Christian art housed in a preserved 15th-century monastery around a peaceful courtyard.", "⛪ 美しいゴシック様式の中庭回廊を歩きながら、オランダの宗教歴史と美術品のコレクションを静かに鑑賞できる。", "⛪ Relax in the sunny medieval cloister courtyard garden after viewing medieval illuminated manuscripts.", "料金: €15.00", 52.0870, 5.1240, "city", False, True, False, False),
    ("ut_15", "Sonnenborgh Museum & Sterrenwacht", "ソンネンボルフ天文台博物館", "Museum & Gallery", "1552年建設の要塞城壁の上に1853年に設立された歴史的天文台博物館。現役の天体望遠鏡を備える。", "19th-century astronomical observatory built on a 1552 stone bastion, featuring historic solar telescopes.", "🔭 週末の夜間観望会イベントに参加すると、巨大なアンティーク天体望遠鏡で実際の月や惑星のクレーターを観察可能。", "🔭 Visit during scheduled winter night-viewing sessions to look through vintage refractor telescopes.", "料金: €10.00", 52.0850, 5.1280, "city", True, True, False, False),
    ("ut_16", "Grachtengordel Singel & Zocherpark", "シンゲル環状水路＆ツォッハー緑地公園", "Scenery & Walk", "19世紀の風景画家ツォッハーが設計した旧城壁跡の緑地帯公園。2020年に数十年ぶりに完全環状水路として再開通した。", "19th-century English-style ring park surrounding the old city walls, built along the fully restored Singel canal.", "🚶 水路に沿って一周約6kmの散策路が整備されており、古木や四季の草花、歴史的橋梁を眺めるジョギング・散策コース。", "🚶 Walk or cycle the 6km green loop encircling the old city, watching swans and historical stone bridges.", "散策無料", 52.0950, 5.1150, "city", True, False, False, True),
    ("ut_17", "Janskerkhof & Bloemenmarkt", "ヤンスケルクホフ広場＆土曜花市場", "Scenery & Walk", "11世紀創立の聖ヤン教会前の歴史的広場。毎週土曜日には色鮮やかな生花やチューリップ球根が並ぶ花市場が開催。", "Historic church square hosting Utrecht's largest open-air flower and plant market every Saturday morning.", "💐 土曜日の午前に訪れて新鮮な生花やチューリップを買い求め、広場周囲のクラシックなカフェで朝食をとるのが定番。", "💐 Visit on Saturday morning to photograph vibrant flower stalls framed against the 11th-century Janskerk.", "散策無料", 52.0935, 5.1230, "city", False, False, True, True),
    ("ut_18", "Nieuwegracht", "ニーウエフラハト運河", "Scenery & Walk", "14世紀に掘削されたユトレヒトで最も静かで絵のように美しい高級住宅街の運河。貴族館や水面の柳の緑が残る。", "Quiet 14th-century residential canal lined with weeping willows, historic step-gabled townhouses, and cellars.", "📸 賑やかなオウデフラハトとは対照的な静寂なエリア。水面に映る旧家と緑の柳の垂れ下がる光景は写真撮影に最適。", "📸 Far quieter than Oudegracht; ideal for romantic evening strolls along willow-draped stone bridges.", "散策無料", 52.0880, 5.1240, "city", False, False, False, True),
    ("ut_19", "Station Utrecht Centraal & Hoog Catharijne", "ユトレヒト中央駅＆モービルモール", "Landmark", "オランダ最大の鉄道ハブ駅。波型ガラス天井の現代ターミナルと、オランダ最大の全天候型ショッピングモールが直結。", "The Netherlands' busiest railway hub seamlessly integrated into Hoog Catharijne, NL's largest indoor shopping mall.", "🛍️ 駅の西口側には世界最大の自転車駐輪場（Bicycle Parking Utrecht: 12,500台収容）があり、圧巻のスケールを見学可能。", "🛍️ Check out the world's largest bicycle parking garage (12,500 spaces) located right beneath the station square.", "見学無料", 52.0900, 5.1100, "city", False, True, True, True),
    ("ut_20", "Daffodil & Dick Bruna Statue", "ミッフィー像（Nijntjepleintje）", "Landmark", "ミッフィーの生みの親ディック・ブルーナの息子マルク・ブルーナが手掛けた金属製ミッフィー像が立つ小さな広場。", "Small public square in the Museumkwartier featuring a bronze Miffy statue created by Marc Bruna.", "📸 ミッフィー像と一緒に記念撮影ができるファン必須の聖地。近くの信号機には世界でここだけの「ミッフィー信号機」も存在。", "📸 Pose for photos with the bronze Miffy statue; don't miss the world's only Miffy traffic lights at Lange Vliestraat.", "見学無料", 52.0975, 5.1105, "city", True, False, False, True),

    # 21 to 30
    ("ut_21", "Stadsschouwburg Utrecht", "ユトレヒト市立劇場", "Landmark", "モダニズム建築家ヴィレム・マードゥス・デュドックが1941年に設計した美しい曲面とライトイエローのレンガが特徴の劇場。", "Modernist theater building completed in 1941 by architect W.M. Dudok, featuring iconic curved lines.", "🎭 リュカスボルヴェルク公園の緑に面し、夜間にライトアップされるファサードとガラスのアトリウムカフェが見事。", "🎭 Located at Lucasbolwerk park; enjoy coffee or pre-theater drinks at the glass-fronted theater restaurant.", "外観・ロビー無料", 52.0938, 5.1275, "city", False, True, False, True),
    ("ut_22", "Universiteitsmuseum Utrecht", "ユトレヒト大学科学博物館", "Museum & Gallery", "2023年に大規模リニューアルオープンした体験型科学博物館。ブリーカー研究室や歴史的な18世紀のBotanische Tuinen旧園を併設。", "Interactive university science museum re-opened in 2023, allowing visitors to conduct real scientific experiments.", "🔬 白衣を着て本物の研究器具を使用する実験体験コーナーや、珍しい骨格標本・歴史的科学機器の展示が子供たちに大好評。", "🔬 Put on a lab coat in the hands-on Research Lab and explore the historic Oude Hortus botanical garden.", "料金: €15.00", 52.0842, 5.1235, "city", True, True, False, False),
    ("ut_23", "Wilhelminapark", "ウィルヘルミナ公園", "Scenery & Walk", "1898年に建設されたユトレヒト東部の伝統的イギリス風景式公園。中央の大きな池と老舗レストラン「Parkbloem」が広がる。", "Historic 1898 English landscape park in East Utrecht featuring a large central lake and century-old trees.", "☕ カフェレストラン「Het Parkhuis」のテラス席で池を眺めながらランチを味わい、地元市民に交じってピクニック。", "☕ Relax on the sun terrace at Het Parkhuis overlooking the pond and weeping willows.", "散策無料", 52.0875, 5.1380, "city", True, False, False, True),
    ("ut_24", "Kano Verhuur Oudegracht", "オウデフラハト運河カヌー＆ペダルボート", "Scenery & Walk", "歴史的オウデフラハト運河の水面からユトレヒトの街並みや蔵テラスを望むカヌー・ペダルボートレンタル。", "Rent canoes or pedal boats directly on the Oudegracht to explore Utrecht's two-tier canals from the water.", "🚣 2人用カヌーやペダルボートを借りてドム塔の真下や地下橋のアーチを潜る体験は夏のユトレヒトの一番の思い出。", "🚣 Paddle beneath medieval stone bridge arches and look up at the soaring Domtoren from water level.", "カヌーレンタル: 約€15.00/時", 52.0910, 5.1180, "city", True, False, False, False),
    ("ut_25", "Brouwerij Maximus & Oudaen", "シュタッドカステール・オウダーン（城郭醸造所）", "Café & Bistro", "1276年建造の要塞城館「Oudaen」の地下地ビール醸造所。伝統的なオランダビールと中世の城郭インテリアが魅力。", "13th-century fortified city castle housing a traditional craft brewery and restaurant in its medieval cellars.", "🍺 13世紀の石造地下蔵で醸造された「Oudaen Wit」ビールと生ハーリングやチーズのペアリングを堪能。", "🍺 Sample house-brewed Oudaen Wit beer paired with bitterballen in the authentic 13th-century cellar bar.", "散策無料 / 飲食予算: €10〜€30", 52.0932, 5.1172, "city", False, True, False, True),
    ("ut_26", "Molen De Ster", "モレン・デ・ステル（歴史的木工風車）", "Landmark", "1721年に建設されたオランダで唯一完全稼働する風力木材製材風車。風車裏手には羊やヤギが暮らす農場を併設。", "The only fully operational wind-powered sawmill in NL (1721), set in a picturesque courtyard with farm animals.", "🐑 土曜日の見学日には風車の翼が回転し、木材を挽く力強いギア機構を見学可能。併設カフェのテラス席も人気。", "🐑 Visit on Saturday when the windmill sails rotate to watch historic wood-sawing demonstrations live.", "敷地散策無料 / 風車見学: €5.00", 52.0935, 5.1015, "city", True, False, False, True),
    ("ut_27", "Lombok & Kanaalstraat", "ロンボク地区＆カナールストラート美食街", "Scenery & Walk", "ユトレヒト中央駅西側に広がるエキゾチックな多文化エリア。トルコ系・モロッコ系の焼きたてパンやスパイス市場が賑わう。", "Vibrant multicultural neighborhood filled with Mediterranean bakeries, exotic spice shops, and fresh produce markets.", "🥙 「Kismet」などの地中海ベーカリーで熱々のバクラヴァやギョズレムを購入し、ウールデン運河沿いで味わうローカル体験。", "🥙 Try fresh Turkish baklava and warm flatbreads along Kanaalstraat at fraction of city-center prices.", "散策無料", 52.0910, 5.1030, "city", False, False, True, True),
    ("ut_28", "Winkel van Sinkel", "フィンケル・ファン・フィンケル", "Landmark", "1839年建造のオランダ初の古典主義デパート建築。ファサードに佇む4体の巨大なカリアティード（女体柱）が象徴。", "1839 Neoclassical landmark building on Oudegracht, built as the first Dutch department store with caryatid statues.", "☕ 現在はカフェグランドレストランとして営業。高天井の豪華なインテリアで伝統のアップルパイやランチを楽しめる。", "☕ Stop for coffee or lunch inside the grand interior featuring historic cast-iron columns facing Oudegracht.", "入館無料 / カフェ予算: €8〜€25", 52.0922, 5.1180, "city", False, True, False, True),
    ("ut_29", "Paushuize", "パウシュハイゼ（教皇の家）", "Landmark", "オランダ史上唯一のローマ教皇アドリアヌス6世が1517年に建設させた豪奢なルネサンス様式館。", "1517 Renaissance residence commissioned by Pope Adrian VI, the only Dutch pope in Catholic history.", "🏛️ 新河川運河（Nieuwegracht）の角に位置し、美しい内装と歴史的サロンを持つ。外観と水辺の景観が美しい。", "🏛️ Located at the corner of Nieuwegracht; admire the ornate red-and-yellow brick Renaissance architecture.", "外観見学無料", 52.0900, 5.1248, "city", False, True, False, True),
    ("ut_30", "Fort bij Vechten", "フェフテン要塞＆水防線博物館", "Museum & Gallery", "1867〜1870年に築造された旧水防線（Stelling van Utrecht）の巨大要塞。現在はオランダ水防線博物館として開放。", "Huge 19th-century defense fort housing the Waterline Museum, explaining NL's historic water defense system.", "🌊 ハイテク展示「VRパラシュート」体験で要塞上空を飛んだり、水防線の広大なミニチュア水流ジオラマを操作。", "🌊 Interactive museum featuring VR parachute flight simulations over the historic defense waterlines.", "料金: €15.00", 52.0590, 5.1680, "suburban", True, True, False, False),

    # 31 to 40
    ("ut_31", "Pyramide van Austerlitz", "オステルリッツのピラミッド", "Landmark", "1804年にナポレオン軍の将軍マルモンが兵士たちに建設させた高さ36mの巨大な土製ピラミッド。", "36-meter-high earthen pyramid constructed in 1804 by Napoleon's troops in the Utrechtse Heuvelrug forest.", "🌲 階段を上って頂上へ立つと、ユトレヒト丘陵地帯の広大な緑の樹海を一望できる絶景が広がる。麓には子供用遊園地併設。", "🌲 Climb the stone steps to the wooden obelisk at the summit for sweeping views over the surrounding pine forests.", "入場料: €3.50", 52.0900, 5.3430, "suburban", True, False, False, False),
    ("ut_32", "Nationaal Park Utrechtse Heuvelrug", "ユトレヒト丘陵地帯国立公園", "Scenery & Walk", "氷河期に形成された起伏に富むオランダ第2の国立公園。広大な松林、砂丘、ヒースの野原が延々と続く。", "Sprawling glacial ridge national park offering pine forests, sand drifts, heather fields, and historic estates.", "🚲 国立公園内のサイクリングロード（MTBルート完備）を走り、秋の紫色のヒース開花や紅葉を楽しむ。", "🚲 Excellent network of mountain bike trails and walking paths through pine woods and purple heather fields.", "散策無料", 52.0500, 5.3000, "suburban", True, False, False, True),
    ("ut_33", "Kasteel Amerongen", "アメロンゲン城", "Landmark", "1672年に焼失後、オランダ古典主義様式で再建された水掘城館。1918年にドイツ皇帝ヴィルヘルム2世が退位宣言に署名した史跡。", "17th-century Dutch Classical moated castle where German Kaiser Wilhelm II signed his abdication in 1918.", "🏰 素晴らしいバロック庭園と、17世紀当時の家具・肖像画・陶磁器が完璧に保存された歴史的部屋をガイドで見学。", "🏰 Walk through pristine Baroque gardens and historic rooms where Kaiser Wilhelm II stayed during WWI exile.", "料金: €15.00", 51.9960, 5.4590, "suburban", False, True, False, False),
    ("ut_34", "Slot Zeist", "ザイスト城", "Landmark", "1677〜1686年にナッサウ＝ザイスト伯爵のために建設されたオランダ・バロック建築の壮麗な宮殿。", "Grand 17th-century Dutch Baroque palace set within historic parkland, built for the Count of Nassau-Odijk.", "🌷 宮殿前の広大な幾何学模様のフランス庭園と水掘の周りをのんびり散策。併設ブラッスリーでランチタイム。", "🌷 Walk around the symmetrical French gardens and enjoy coffee at Brasserie Slot Zeist facing the moat.", "庭園散策無料 / 宮殿見学ツアー: €12.50", 52.0810, 5.2340, "suburban", False, True, False, True),
    ("ut_35", "Historisch Amersfoort", "アメルスフォールト歴史地区", "Scenery & Walk", "ユトレヒトから電車で15分。中世の水陸二重城門「Koppelpoort」や水路、運河、モントリアンの生家が残る古都。", "Picturesque medieval city 15 minutes by train from Utrecht, famous for the 1400 Koppelpoort water-and-land gate.", "📸 1400年建造の二重城門「Koppelpoort」はオランダで最も美しい中世城門の一つ。運河の水面に映る姿が絶品の写真構図。", "📸 Photograph the magnificent 15th-century Koppelpoort watergate reflected in the quiet canal waters.", "街歩き無料", 52.1560, 5.3870, "suburban", True, False, True, True),
    ("ut_36", "Mondriaanhuis Amersfoort", "モンドリアンの家（アメルスフォールト）", "Museum & Gallery", "抽象絵画の巨匠ピエト・モンドリアンが1872年に誕生した生家を利用した体験型美術館。", "Birthplace museum of Piet Mondrian, displaying his early realistic landscapes and evolution to abstract De Stijl art.", "🎨 モンドリアンのパリのスタジオが原寸大で再現されており、インタラクティブなカラーラボで自分だけの抽象アートを創出可能。", "🎨 Experience a full-scale reconstruction of Mondrian's 1920s Paris studio and create custom digital grid art.", "料金: €14.00", 52.1540, 5.3890, "suburban", True, True, False, False),
    ("ut_37", "DierenPark Amersfoort", "アメルスフォールト動物園", "Scenery & Walk", "森林の中に広がるファミリーに特化した体験型動物園。クマやトラの頭上を通る空中アスレチックや恐竜の森を併設。", "Forest zoo featuring climbing suspension bridges right over animal enclosures and a realistic Dinosaur Forest.", "クマやツキノワグマの展示の上をロープ橋で渡る「Climberboel」アスレチックがお子様に大人気。", "🐻 Children can climb rope bridges suspended directly over bear and tiger enclosures for thrilling views.", "料金: €27.50", 52.1520, 5.3510, "suburban", True, False, False, False),
    ("ut_38", "Nationaal Militair Museum Soesterberg", "スーステルベルフ国立軍事博物館", "Museum & Gallery", "旧スーステルベルフ空軍基地跡に建設された巨大軍事博物館。F-16戦闘機、戦車、ヘリコプターが屋内外にずらりと並ぶ。", "Massive military museum on a former airbase, exhibiting jet fighters, tanks, helicopters, and interactive simulators.", "✈️ 巨大アトリウム天井に吊り下げられたF-16やスピットファイア戦闘機の迫力ある展示。自分で操縦できる戦車シミュレーター完備。", "✈️ Marvel at real F-16 fighters suspended from the ceiling and drive miniature tanks on the outdoor obstacle course.", "料金: €19.00", 52.1330, 5.2780, "suburban", True, True, False, False),
    ("ut_39", "Paleis Soestdijk", "ソーストダイク宮殿", "Landmark", "バールンに位置し、旧オランダ女王ユリアナ陛下とベルンハルト殿下が長年居住されたクラシックな白亜の宮殿。", "Neoclassical white palace in Baarn, former residence of Queen Juliana and Prince Bernhard.", "宮殿を正面に臨む広大な英式庭園を散策し、かつて王室の公式行事が行われた歴史的広間を見学。", "🌲 Walk through the expansive palace gardens and view the royal reception rooms filled with historical photographs.", "庭園のみ: €6.00 / 宮殿共通: €16.50", 52.1930, 5.2810, "suburban", False, True, False, True),
    ("ut_40", "Kasteel Groeneveld", "フルーネフェルト城", "Landmark", "18世紀の貴族が建てたバールンのバロック様式荘園。現在は森林保護や自然文化展を開催する国定史跡。", "18th-century country estate in Baarn featuring a grand manor house surrounded by centuries-old beech woods.", "🌿 敷地内のオーガニックティーハウス「Grand Café Groeneveld」で自家製ケーキを味わい、森の遊歩道を散策。", "🌿 Explore peaceful walking paths through ancient woods and stop at Grand Café Groeneveld for organic lunch.", "庭園散策無料 / 展覧会: €10.00", 52.2080, 5.2280, "suburban", True, False, False, True),

    # 41 to 50
    ("ut_41", "Historisch Woerden", "ウールデン歴史地区（チーズの街）", "Scenery & Walk", "ユトレヒトから電車で10分。15世紀の城郭や水掘、歴史的チーズ計量所が残る伝統のウールデンチーズの産地。", "Historic cheese town 10 minutes west of Utrecht, featuring a 15th-century castle and authentic Saturday cheese market.", "🧀 5月〜8月の毎週土曜午前に開催される伝統の「Woerden Cheese Market」では、農家による伝統のチーズ売買取引が手拍子で再現される。", "🧀 Visit on Saturday morning in summer for the authentic Woerden Cheese Market with traditional clapping negotiations.", "街歩き無料", 52.0860, 4.8830, "suburban", True, False, True, True),
    ("ut_42", "Loosdrechtse Plassen", "ロースドレヒト湖沼群", "Scenery & Walk", "泥炭採掘跡に広がったオランダ有数の水上マリンレジャー湖沼群。セーリング、カヌー、水辺の高級レストランが集まる。", "Network of peat-excavated lakes renowned for sailing, motorboating, kayaking, and waterside dining.", "⛵ ボートをレンタルして湖上の小島に立ち寄ったり、水辺のレストラン「De Strook」で夕日を見ながら食事を楽しむ。", "⛵ Rent a small electric boat or motor launch to cruise past thatched holiday villas along the lakeshore.", "散策無料 / ボートレンタル実費", 52.1950, 5.0800, "suburban", True, False, False, True),
    ("ut_43", "Vechtstreek & Maarssen", "フェヒト川沿い歴史的貴族邸宅群（マールセン）", "Scenery & Walk", "17世紀黄金時代のアムステルダムの富裕商人がフェヒト川沿いに建てた夏の邸宅（Buitenplaatsen）が連なる景勝地。", "Scenic river valley lined with luxurious 17th-century Golden Age summer country estates (Buitenplaatsen).", "🚴 マールセンからフェヒト川沿いにサイクリングすると、美しい鉄製水門、クラシックな風車、貴族邸宅の庭園を連続して鑑賞可能。", "🚴 Cycle along the winding Vecht river paths from Maarssen to admire Golden Age manor house gardens.", "散策・サイクリング無料", 52.1400, 5.0400, "suburban", False, False, False, True),
    ("ut_44", "Fort aan de Klop", "フォルト・アン・デ・クロップ", "Scenery & Walk", "1819年に建設されたオランダ水防線の要塞跡。緑豊かな敷地内にエコキャンプ場と雰囲気溢れるブラッスリーカフェが広がる。", "Historic 1819 defense fort converted into a green eco-camping site and charming island brasserie.", "☕ 緑に囲まれた木造カフェのテラスで自家製レモネードやクラフトビールを楽しみながら、水掘と要塞石垣を散策。", "☕ Sit on the sunny wooden island terrace for lunch surrounded by historic defense moats and greenery.", "敷地散策無料", 52.1180, 5.0980, "city", True, False, False, True),
    ("ut_45", "Maximapark & Het Lint", "マキシマ公園＆レジャーサーキット", "Scenery & Walk", "ユトレヒト西部に位置する300ヘクタールの賞を受賞した現代公園。歩行者・自転車専用の全長8kmの舗装周遊路「Het Lint」を完備。", "Award-winning 300-hectare modern park featuring 'Het Lint', an 8km wide car-free paved loop for cycling and inline skating.", "🚲 車を完全に排除した「Het Lint」周遊路はランニングやサイクリングに最適。園内の中央カフェ「Anafora」でティータイム。", "🚲 Rent a bike to ride the 8-kilometer green ring loop 'Het Lint', then stop at waterfront restaurant Anafora.", "入園無料", 52.0950, 5.0200, "city", True, False, False, True),
    ("ut_46", "Stadskasteel Oudaen", "シュタッドカステール・オウダーン（13世紀都市城館）", "Landmark", "1276年にオウダーン一族によってオウデフラハト運河沿いに建てられたユトレヒトに現存する最も重厚な中世の塔状都市城館。", "The best-preserved 13th-century fortified tower townhouse in Utrecht, built along Oudegracht in 1276.", "🏰 現在はレストラン兼醸造所として営業。1階の重厚な中世暖炉やゴシック窓のある大ホールでオランダ料理を体験。", "🏰 Admire the medieval stone battlements and step gables from Oudegracht bridge, or dine inside the Gothic hall.", "外観見学無料", 52.0932, 5.1175, "city", False, True, False, True),
    ("ut_47", "Werk aan het Spoel", "ワーフ・アーン・ヘット・スポール（レック川要塞）", "Landmark", "レック川沿いに位置する旧オランダ水防線の要塞施設。円形のアンプティシアターとオーガニックカフェ「Caat」が広がる。", "Historic defense fort along the Lek river featuring a grass amphitheater and organic cultural cafe Caat.", "🎭 川沿いの土手をサイクリングし、要塞の芝生アンプティシアターで開催される野外コンサートやクラフト市を楽しむ。", "🎭 Cycle along the Lek river dike to reach this creative fort culture hub; popular for summer outdoor concerts.", "散策無料", 51.9560, 5.2180, "suburban", True, False, False, True),
    ("ut_48", "Flora's Hof", "フローラ庭園（ドム塔下隠れ庭園）", "Scenery & Walk", "ドム塔のすぐ足元、かつての大聖堂中庭跡にひっそりと隠された静寂なボランティア庭園。歴史的ハーブや四季の花が咲く。", "Secluded historic volunteer garden hidden at the foot of Domtoren, planted with historic medicinal herbs.", "🌸 賑やかなドム広場の喧騒から逃れ、ベンチに座ってドム塔の見上げる壮大な見上げ構図を静かに撮影できる隠れた穴場。", "🌸 A peaceful hidden courtyard under Domtoren; rest on a wooden bench away from city crowds.", "入園無料", 52.0903, 5.1218, "city", False, False, False, True),
    ("ut_49", "Trajectum Lumen", "ユトレヒト・ルーメン（夜の光アートウォーク）", "Scenery & Walk", "暗闇の旧市街の橋、運河の蔵、教会の壁面に国際的アーティストによる光のインスタレーションが浮かび上がる夜間アートウォーク。", "Self-guided evening walking trail showcasing artistic light installations projected onto historic bridges and dark canals.", "🌙 太陽が沈んだ後にアプリやマップを片手に散策。運河の水面に浮かぶ光のアートや橋の裏側に潜む光演出を探すのが幻想的。", "🌙 Follow the orange light drops embedded in the pavement after dark to discover hidden glowing art pieces.", "見学無料", 52.0910, 5.1200, "city", False, True, False, True),
    ("ut_50", "Bartholomeus Gasthuis", "バルトロメウス病院＆現代巨大壁画", "Landmark", "1367年創立の歴史的養老施設。現在も使用されているヨーロッパ最古級の介護施設で、巨大なレトロストリートアート壁画が目印。", "Historic 1367 almshouse and one of Europe's oldest continuously operating care facilities, featuring a giant mural.", "🎨 建物外壁に描かれた巨大な老婦人のリアルなストリートアート壁画は写真撮影スポット。内部の16世紀のタペストリーホールも見事。", "🎨 Photograph the stunning realistic monumental street art mural painted on the brick outer wall.", "外観見学無料", 52.0885, 5.1165, "city", False, True, False, True),

    # 51 to 60
    ("ut_51", "Twijnstraat & Ledig Erf", "トワインストラート＆レディヒ・エルフ広場", "Scenery & Walk", "ユトレヒト最古のショッピングストリート「Twijnstraat」と、南端のテラスカフェが集まる広場「Ledig Erf」。", "Utrecht's oldest shopping street packed with independent boutiques, leading to sunny terrace square Ledig Erf.", "🛍️ 独立系ブティック、チーズ専門店「Kazerie」、オーガニックベーカリーを巡り、広場のテラス席でクラフトビール。", "🛍️ Browse artisanal cheese shops and vintage boutiques along Twijnstraat, then grab a sunlit terrace seat at Ledig Erf.", "散策無料", 52.0830, 5.1220, "city", False, False, True, True),
    ("ut_52", "Catherijnesingel & Stadsbuitengracht", "カタリネシンゲル新開通水路", "Scenery & Walk", "1970年代に高速道路に埋め立てられていた旧城壁水路を、2020年に奇跡的に水路として完全復元開通させた歴史的プロジェクト。", "Restored historic outer moat canal loop; previously a 1970s highway that was famously converted back into water in 2020.", "🛶 復元された水路沿いの散策路を歩き、かつての車道が再び水鳥やボートが浮かぶ美しい緑豊かな運河に戻った姿を鑑賞。", "🛶 Walk along the newly restored green water loop where cars used to drive on concrete; winner of European Urban Public Space awards.", "散策無料", 52.0910, 5.1110, "city", True, False, False, True),
    ("ut_53", "Griftpark", "グリフトパーク", "Scenery & Walk", "ユトレヒト北東部に広がる人気の現代コミュニティ公園。スケートパーク、ふれあい動物園（Kinderboerderij）、展望丘を備える。", "Popular urban park in North-East Utrecht featuring a petting zoo, large skatepark, playground, and panoramic hill.", "🐑 お子様連れに最適。ふれあい動物園で羊やヤギと触れ合った後、公園中央の小高い丘からドム塔の遠景を鑑賞。", "🐑 Great for families; visit the friendly city farm with goats and sheep, then climb the grassy hill for skyline views.", "入園無料", 52.0980, 5.1280, "city", True, False, False, True),
    ("ut_54", "De Wittevrouwenbuurt", "ヴィッテヴロウヴェン地区", "Scenery & Walk", "19世紀のヴィクトリア調煉瓦住宅が立ち並ぶエレガントな住宅街。オランダ最高峰のジェラート店「Roberto Gelato」が位置する。", "Charming 19th-century residential neighborhood famous for holding the city's finest artisanal ice cream shop.", "🍦 名店「Roberto Gelato」で本場イタリア仕込みのフレッシュジェラート（ピスタチオや季節のフルーツ）を行列に並んで味わう。", "🍦 Join the local line at Roberto Gelato for acclaimed homemade Italian ice cream flavors.", "散策無料", 52.0960, 5.1310, "city", False, False, True, True),
    ("ut_55", "Museum van Zuilen", "ザウレン歴史博物館", "Museum & Gallery", "かつての工業地区ザウレンの労働者の歴史や生活遺品を集めたオランダで最もアットホームな私立地域博物館。", "Intimate local neighborhood museum celebrating the industrial heritage and worker history of Zuilen.", "🏠 名物館長による温かい解説と共に、往年のフレンチフライ機や昭和レトロを思わせる20世紀の生活雑貨コレクションを鑑賞。", "🏠 Guided by passionate local volunteers explaining vintage household memorabilia and industrial objects.", "料金: €5.00", 52.1100, 5.0880, "city", False, True, False, False),
    ("ut_56", "Vredenburg Markt", "フレーデンブルフ青空市場", "Café & Bistro", "ユトレヒト中央駅すぐ横のフレーデンブルフ広場で水曜・金曜・土曜に開催されるオランダ伝統の青空市場。", "Bustling open-air market held three days a week on Vredenburg square, famous for cheeses and hot fried fish.", "🐟 名物「Kibbeling（キッベリング：白身魚のフリット）」の揚げたてを特製ガーリックソースで味わうのがマーケットの醍醐味。", "🐟 Order a piping hot paper box of freshly fried Dutch fish bites (Kibbeling) with garlic sauce.", "散策無料", 52.0920, 5.1140, "city", False, False, True, True),
    ("ut_57", "SubGrid / Werkspoorcathedraal", "ヴェルクスプールカテドラル（旧列車工場）", "Landmark", "かつて蒸気機関車や橋梁を製造していた1950年代の巨大な鉄骨工業工場をクリエイティブイベントスペースへ再生。", "Massive 1950s industrial steel factory hall where train locomotives were built, converted into a cultural venue.", "🏢 工業遺産の巨大な鉄骨トラス構造と高い天井を見上げながら、デザイン市やフードフェスティバルイベントを楽しむ。", "🏢 Admire the monumental steel industrial architecture of this former heavy-machinery production hall.", "イベント入場料に準ずる (通常: 無料〜€15.00)", 52.1030, 5.0680, "city", False, True, False, True),
    ("ut_58", "Kasteel Sterkenburg", "ステルケンブルフ城", "Landmark", "ドリーベルヘンに位置する13世紀建造の丸い塔を持つ幻想的な水掘城砦。豊かな自然森と果樹園に囲まれる。", "Picturesque 13th-century moated castle featuring a round stone tower, surrounded by historic orchards.", "🏰 豊かな自然に囲まれた水掘周囲の散策路を歩き、中世の丸塔が水面に反射する童話のような景観を鑑賞。", "🏰 Photograph the iconic circular medieval tower reflected in the serene surrounding moat waters.", "敷地散策無料", 52.0380, 5.2610, "suburban", False, False, False, True),
    ("ut_59", "Landgoed Amelisweerd", "アメリスウェールト荘園", "Scenery & Walk", "クロッメ・ライン川沿いに広がる18世紀の歴史的貴族荘園と古代のブナ原生林。オーガニックベーカリー「De Veldkeuken」が人気。", "Historic 18th-century country estate and ancient forest along the Kromme Rijn river.", "🍞 石臼で挽いたオーガニック小麦で作る老舗パン屋「De Veldkeuken」で焼きたてパンとスープを味わうのがハイキングの最高のご褒美。", "🍞 Stop at organic bakery De Veldkeuken inside the former coach house for sourdough bread and soup.", "散策無料", 52.0720, 5.1610, "suburban", True, False, False, True),
    ("ut_60", "Kromme Rijn Canoe Route", "クロッメ・ライン川カヌールート", "Scenery & Walk", "ユトレヒト旧市街からアメリスウェールト荘園を経てウィーク・バイ・デュールステーデまで12km続く水豊かなカヌールート。", "Winding 12km scenic canoeing route along the Kromme Rijn river connecting Utrecht to historic country estates.", "🛶 カヌーを借りて清流クロッメ・ライン川を漕ぎ進み、水鳥の鳴き声と両岸の青々とした木々のトンネルをくぐるアウトドア体験。", "🛶 Paddle through green tree tunnels along the tranquil Kromme Rijn river past historic country manors.", "カヌーレンタル: 約€20〜€35/日", 52.0700, 5.1650, "suburban", True, False, False, True)
]

def make_full_spot_object(spot_tuple):
    sid, name_en, name_ja_base, category, desc_ja, desc_en, tip_ja, tip_en, price_str, lat, lng, zone, kids, rain, shopping, free = spot_tuple
    full_name_ja = f"{name_en}（{name_ja_base}）"
    
    if free or "無料" in price_str or "Free" in price_str:
        p_ja, p_en, p_es, p_zh, p_fr, p_de = price_str if "無料" in price_str else "散策無料", "Free Entry", "Acceso libre", "免费参观", "Accès gratuit", "Freier Zugang"
        is_free = True
    else:
        clean = price_str.replace("料金:", "").replace("入場料:", "").strip()
        p_ja, p_en, p_es, p_zh, p_fr, p_de = f"料金: {clean}", f"Entry: {clean}", f"Entrada: {clean}", f"门票：{clean}", f"Entrée : {clean}", f"Eintritt: {clean}"
        is_free = False

    return {
        "id": sid,
        "name": full_name_ja,
        "category": category,
        "rating": "★4.7",
        "locationZone": zone,
        "lat": round(lat, 4),
        "lng": round(lng, 4),
        "kids": kids,
        "rain": rain,
        "shopping": shopping,
        "free": is_free,
        "family": True,
        "adult": True,
        "image": "",
        "wikiImage": "",
        "hasWiki": True,
        "name_en": name_en,
        "name_ja": full_name_ja,
        "name_es": name_en,
        "name_zh": name_en,
        "name_fr": name_en,
        "name_de": name_en,
        "desc_en": desc_en,
        "desc_ja": desc_ja,
        "desc_es": desc_en,
        "desc_zh": desc_ja,
        "desc_fr": desc_en,
        "desc_de": desc_en,
        "tip_en": tip_en,
        "tip_ja": tip_ja,
        "tip_es": tip_en,
        "tip_zh": tip_ja,
        "tip_fr": tip_en,
        "tip_de": tip_en,
        "price_ja": p_ja,
        "price_en": p_en,
        "price_es": p_es,
        "price_zh": p_zh,
        "price_fr": p_fr,
        "price_de": p_de
    }

def run_compiler():
    final_spots = [make_full_spot_object(s) for s in spots_data]
    
    filepath = os.path.join(cities_dir, "utrecht.json")
    out_obj = {
        "city": "Utrecht",
        "country": "Netherlands",
        "city_ja": "ユトレヒト",
        "country_ja": "オランダ",
        "spots": final_spots
    }
    with open(filepath, 'w', encoding='utf-8') as f:
        json.dump(out_obj, f, indent=2, ensure_ascii=False)

    print(f"🎉 Successfully compiled utrecht.json with {len(final_spots)} verified spots!")

if __name__ == '__main__':
    run_compiler()
