#!/usr/bin/env python3
"""
Zero-Margin Travel App - Dutch Cities Database Expansion & Integration (v32.0.0)
Integrates verified Dutch travel spot datasets across 5 Dutch cities:
- amsterdam.json (20 spots: a_1 to a_20, refined with 6-language precision & Aha! insights)
- rotterdam.json (5 spots: ro_1 to ro_5)
- the_hague.json (2 spots: dh_1, dh_2)
- utrecht.json (2 spots: ut_1, ut_2)
- maastricht.json (4 spots: maa_1 to maa_4)
"""

import os
import json

base_dir = os.path.dirname(os.path.abspath(__file__))
cities_dir = os.path.join(base_dir, '..', 'data', 'cities')

ROTTERDAM_DATA = {
  "city": "Rotterdam",
  "country": "Netherlands",
  "city_ja": "ロッテルダム",
  "country_ja": "オランダ",
  "spots": [
    {
      "id": "ro_1",
      "name": "Erasmusbrug（エラスムス橋）",
      "category": "Landmark",
      "rating": "★4.8",
      "locationZone": "city",
      "lat": 51.909,
      "lng": 4.4869,
      "kids": False,
      "rain": False,
      "shopping": False,
      "free": True,
      "family": True,
      "adult": True,
      "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/41/Erasmusbrug_Rotterdam_2017.jpg/330px-Erasmusbrug_Rotterdam_2017.jpg",
      "wikiImage": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/41/Erasmusbrug_Rotterdam_2017.jpg/330px-Erasmusbrug_Rotterdam_2017.jpg",
      "hasWiki": True,
      "desc_en": "Iconic cable-stayed bridge with a 139-meter-high asymmetrical pylon spanning the Nieuwe Maas, nicknamed 'The Swan' (De Zwaan).",
      "desc_ja": "『白鳥（デ・ズワーン）』の愛称で親しまれる、新マース川に架かる主塔高139mの非対称斜張橋。ロッテルダムの象徴的景観。",
      "desc_es": "Emblemático puente atirantado con un pilón asimétrico de 139 m sobre el río Nuevo Mosa, conocido como 'El Cisne'.",
      "desc_zh": "横跨新马斯河的斜拉桥（主塔高139米），因优美曲线被昵称为“天鹅桥”（De Zwaan），是鹿特丹的地标。",
      "desc_fr": "Pont à haubans emblématique avec un pylône asymétrique de 139 mètres sur la Nouvelle Meuse, surnommé 'Le Cygne'.",
      "desc_de": "Ikonische Schrägseilbrücke mit einem 139 Meter hohen asymmetrischen Pylon über die Neue Maas, genannt 'Der Schwan'.",
      "tip_en": "📸 Stroll along the Wilhelminapier at sunset for panoramic photos of the bridge and modern high-rises reflecting across the river.",
      "tip_ja": "📸 夕暮れ時にウィルヘルミナ埠頭（Wilhelminapier）側から撮影すると、ライトアップされた橋と対岸の高層ビル群が川面に美しく映り込みます。",
      "tip_es": "📸 Camina por el Wilhelminapier al atardecer para capturar los mejores reflejos del puente en el agua.",
      "tip_zh": "📸 傍晚漫步至威廉敏娜码头（Wilhelminapier），可捕捉大桥亮灯与两岸现代化摩天大楼倒映水面的绝美全景。",
      "tip_fr": "📸 Promenez-vous sur le Wilhelminapier au coucher du soleil pour les plus belles photos du pont.",
      "tip_de": "📸 Spazieren Sie bei Sonnenuntergang am Wilhelminapier entlang für tolle Fotos mit Spiegelungen.",
      "name_en": "Erasmus Bridge",
      "name_ja": "Erasmusbrug（エラスムス橋）",
      "name_es": "Puente Erasmo (Erasmusbrug)",
      "name_zh": "伊拉斯谟大桥 (天鹅桥)",
      "name_fr": "Pont Érasme",
      "name_de": "Erasmusbrücke",
      "price_en": "Free Entry",
      "price_ja": "通行・散策無料",
      "price_es": "Acceso libre",
      "price_zh": "免费通行",
      "price_fr": "Accès gratuit",
      "price_de": "Freier Zugang"
    },
    {
      "id": "ro_2",
      "name": "Markthal Rotterdam（マルクトハル）",
      "category": "Landmark",
      "rating": "★4.7",
      "locationZone": "city",
      "lat": 51.9202,
      "lng": 4.4868,
      "kids": True,
      "rain": True,
      "shopping": True,
      "free": True,
      "family": True,
      "adult": True,
      "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6f/Markthal_Rotterdam_2015.jpg/330px-Markthal_Rotterdam_2015.jpg",
      "wikiImage": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6f/Markthal_Rotterdam_2015.jpg/330px-Markthal_Rotterdam_2015.jpg",
      "hasWiki": True,
      "desc_en": "Monumental horseshoe-shaped residential arch containing a vast indoor gourmet food hall covered by an expansive digital art ceiling mural.",
      "desc_ja": "住居と一体化した巨大な馬蹄型建築。内側のアーチ天井一面には『豊穣の角』と題された鮮やかなデジタルアートが広がる屋内市場。",
      "desc_es": "Gran mercado cubierto bajo un arco residencial con un espectacular mural artístico en el techo.",
      "desc_zh": "兼具住宅功能的巨型马蹄形室内美食集市，拱形天顶装饰着色彩斑斓的艺术壁画《丰收之角》。",
      "desc_fr": "Marché couvert spectaculaire en forme de fer à cheval sous une fresque murale numérique géante.",
      "desc_de": "Spektakuläre hufeisenförmige Markthalle mit einer riesigen Decken-Kunstinstallation.",
      "tip_en": "🍽️ Free to walk inside. Grab freshly made warm Dutch stroopwafels, kibbeling, or cheese samples from the central ground-floor artisanal stalls.",
      "tip_ja": "🍽️ 入館無料。中央エリアに並ぶ屋台で焼き立ての特大ストロープワッフルやキッベリング（白身魚フライ）、ゴーダチーズの試食を楽しむのが醍醐味です。",
      "tip_es": "🍽️ Entrada gratuita. Degusta stroopwafels calientes y quesos en los puestos artesanales del centro.",
      "tip_zh": "🍽️ 免费进场。推荐品尝中庭摊位现烤的焦糖煎饼（Stroopwafel）、香脆炸鱼块（Kibbeling）与各种风味奶酪。",
      "tip_fr": "🍽️ Entrée libre. Dégustez des gaufres chaudes (stroopwafels) et du fromage hollandais aux stands du centre.",
      "tip_de": "🍽️ Eintritt frei. Probieren Sie frische Stroopwafels und Kibbeling an den Marktständen.",
      "name_en": "Markthal Rotterdam",
      "name_ja": "Markthal Rotterdam（マルクトハル）",
      "name_es": "Markthal Rotterdam",
      "name_zh": "鹿特丹拱形市场 (Markthal)",
      "name_fr": "Markthal Rotterdam",
      "name_de": "Markthal Rotterdam",
      "price_en": "Free Entry",
      "price_ja": "入館無料",
      "price_es": "Acceso libre",
      "price_zh": "免费入场",
      "price_fr": "Accès gratuit",
      "price_de": "Freier Zugang"
    },
    {
      "id": "ro_3",
      "name": "Kijk-Kubus & Kubuswoningen（キューブハウス＆展示ハウス）",
      "category": "Landmark",
      "rating": "★4.5",
      "locationZone": "city",
      "lat": 51.92,
      "lng": 4.49,
      "kids": True,
      "rain": True,
      "shopping": False,
      "free": False,
      "family": True,
      "adult": True,
      "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d3/Kubuswoningen_Rotterdam_2018.jpg/330px-Kubuswoningen_Rotterdam_2018.jpg",
      "wikiImage": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d3/Kubuswoningen_Rotterdam_2018.jpg/330px-Kubuswoningen_Rotterdam_2018.jpg",
      "hasWiki": True,
      "desc_en": "Innovative complex of tilted cube-shaped houses designed by Piet Blom in 1984, with one unit preserved as a show museum (Kijk-Kubus).",
      "desc_ja": "建築家ピート・ブロムが都市の森をイメージして設計した45度傾いた六角柱のキューブ住宅群。1棟が内部見学用博物館（キイク・キューブ）として公開中。",
      "desc_es": "Conjunto de casas cúbicas inclinadas a 45 grados diseñadas por Piet Blom, con una de ellas abierta como museo.",
      "desc_zh": "由建筑师皮特·布洛姆于1984年设计的立体树林概念倾斜方块屋住宅群，其中一栋被设为公开展示馆（Kijk-Kubus）。",
      "desc_fr": "Ensemble architectural unique de maisons cubiques inclinées à 45 degrés, dont une est transformée en maison-témoin.",
      "desc_de": "Außergewöhnliche Wohnanlage aus um 45 Grad gekippten Würfelhäusern von Piet Blom.",
      "tip_en": "🏢 Walking around the exterior forest courtyard is free. Step inside the Kijk-Kubus (~€3.00) to see custom angled carpentry and tilted living spaces.",
      "tip_ja": "🏢 敷地内の通路や外観見学は無料。内部公開館『Kijk-Kubus』（入場料約€3.00）に入ると、斜めの壁に合わせた特注家具や傾いた居住空間を体験できます。",
      "tip_es": "🏢 El exterior es gratuito. Entra a la Kijk-Kubus (~3€) para experimentar la vida en paredes inclinadas.",
      "tip_zh": "🏢 穿行外部庭院通道免费。建议购票进入展示房内部（Kijk-Kubus，约€3.00），体验倾斜墙壁下的独特空间设计。",
      "tip_fr": "🏢 Extérieur gratuit. Visitez la maison-témoin Kijk-Kubus (~3 €) pour découvrir l'agencement intérieur.",
      "tip_de": "🏢 Außenbereich frei. Das Schauhaus Kijk-Kubus (~3 €) zeigt das Wohnen in schrägen Wänden.",
      "name_en": "Cube Houses (Kijk-Kubus)",
      "name_ja": "Kijk-Kubus & Kubuswoningen（キューブハウス＆展示ハウス）",
      "name_es": "Casas Cubo (Kubuswoningen)",
      "name_zh": "立体方块屋 (Kubuswoningen)",
      "name_fr": "Maisons Cubes (Kubuswoningen)",
      "name_de": "Kubus-Häuser (Kubuswoningen)",
      "price_en": "Free Grounds / Museum: ~€3.00",
      "price_ja": "外観無料 / 内部見学: 約€3.00",
      "price_es": "Exterior gratis / Museo: ~3,00 €",
      "price_zh": "外观免费 / 内部参观：约3.00 欧元",
      "price_fr": "Extérieur gratuit / Musée : ~3,00 €",
      "price_de": "Außenbereich frei / Museum: ca. 3,00 €"
    },
    {
      "id": "ro_4",
      "name": "Depot Boijmans Van Beuningen（デポ・ボイマンス・ファン・ベーニンゲン）",
      "category": "Museum & Art",
      "rating": "★4.7",
      "locationZone": "city",
      "lat": 51.9142,
      "lng": 4.4736,
      "kids": False,
      "rain": True,
      "shopping": False,
      "free": False,
      "family": True,
      "adult": True,
      "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c8/Depot_Boijmans_Van_Beuningen_2021.jpg/330px-Depot_Boijmans_Van_Beuningen_2021.jpg",
      "wikiImage": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c8/Depot_Boijmans_Van_Beuningen_2021.jpg/330px-Depot_Boijmans_Van_Beuningen_2021.jpg",
      "hasWiki": True,
      "desc_en": "The world's first publicly accessible museum art storage facility, housing over 155,000 works behind 1,664 reflective mirror panels with a rooftop birch forest.",
      "desc_ja": "1,664枚の鏡面ガラスで覆われ、155,000点以上の所蔵品を保管する世界初の全面公開型美術館収蔵庫（デポ）。屋上に白樺の空中庭園が広がる。",
      "desc_es": "El primer depósito de arte de museo del mundo accesible al público, con más de 155.000 obras y paneles de espejo.",
      "desc_zh": "世界上首座对公众开放的博物馆艺术收藏库，在1664块反射镜面玻璃后保管着超过15.5万件藏品，屋顶建有高空白桦林。",
      "desc_fr": "Le premier entrepôt d'art muséal au monde accessible au public, abritant plus de 155 000 œuvres.",
      "desc_de": "Das weltweit erste öffentlich zugängliche Museumskunstdepot mit über 155.000 Kunstwerken hinter einer Spiegelfassade.",
      "tip_en": "🎟️ Mandatory advance online ticket. Take the glass elevator to the 6th-floor rooftop restaurant and birch garden for a 360-degree skyline panorama.",
      "tip_ja": "🎟️ 完全事前オンライン日時予約制です。最上階6階の屋上庭園からは、鏡面ボウル越しにロッテルダムの摩天楼を360度見渡す絶景が楽しめます。",
      "tip_es": "🎟️ Reserva online obligatoria. Sube en el ascensor de cristal a la azotea para una vista panorámica de 360 grados.",
      "tip_zh": "🎟️ 必须提前在线预订时间段。乘坐透明玻璃电梯直达6层屋顶花园，可俯瞰鹿特丹城市天际线360度全景。",
      "tip_fr": "🎟️ Billet en ligne obligatoire. Montez sur le toit pour une vue panoramique à 360° sur la ville.",
      "tip_de": "🎟️ Online-Buchung Pflicht. Der Dachgarten im 6. Stock bietet ein spektakuläres 360-Grad-Panorama.",
      "name_en": "Depot Boijmans Van Beuningen",
      "name_ja": "Depot Boijmans Van Beuningen（デポ・ボイマンス・ファン・ベーニンゲン）",
      "name_es": "Depot Boijmans Van Beuningen",
      "name_zh": "博伊曼斯·范·伯宁恩艺术仓库 (Depot)",
      "name_fr": "Depot Boijmans Van Beuningen",
      "name_de": "Depot Boijmans Van Beuningen",
      "price_en": "Entry: €20.00",
      "price_ja": "入場料: €20.00",
      "price_es": "Entrada: 20,00 €",
      "price_zh": "入场费：20.00 欧元",
      "price_fr": "Entrée : 20,00 €",
      "price_de": "Eintritt: 20,00 €"
    },
    {
      "id": "ro_5",
      "name": "Werelderfgoed Kinderdijk（キンデルダイクの風車群 / 世界遺産）",
      "category": "Landmark",
      "rating": "★4.8",
      "locationZone": "suburban",
      "lat": 51.8889,
      "lng": 4.6311,
      "kids": True,
      "rain": False,
      "shopping": False,
      "free": True,
      "family": True,
      "adult": True,
      "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/KinderdijkWindmills.jpg/330px-KinderdijkWindmills.jpg",
      "wikiImage": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/KinderdijkWindmills.jpg/330px-KinderdijkWindmills.jpg",
      "hasWiki": True,
      "desc_en": "UNESCO World Heritage network of 19 monumental 18th-century drainage windmills standing along scenic peat canals.",
      "desc_ja": "低地オランダの水管理の歴史を物語る、18世紀に建造された19基の巨大風車群が並ぶユネスコ世界文化遺産。",
      "desc_es": "Red de 19 molinos de viento del siglo XVIII declarada Patrimonio de la Humanidad por la UNESCO.",
      "desc_zh": "被联合国教科文组织列为世界文化遗产的19座18世纪历史古风车群，矗立在宁静的排水运河两岸。",
      "desc_fr": "Réseau de 19 moulins à vent du XVIIIe siècle classé au patrimoine mondial de l'UNESCO.",
      "desc_de": "UNESCO-Weltkulturerbe mit 19 historischen Windmühlen aus dem 18. Jahrhundert zur Polderentwässerung.",
      "tip_en": "⛴️ Walking and cycling along the main canal dike path is completely free. Paid tickets are required for museum windmills and boat cruises.",
      "tip_ja": "⛴️ 堤防上の遊歩道・自転車道は完全無料で散策可能です。有料チケットは博物館風車の内部見学や巡回クルーズ船の利用時に必要となります。",
      "tip_es": "⛴️ El paseo a pie o en bici por el dique es gratuito. El billete es necesario solo para los molinos museo y el barco.",
      "tip_zh": "⛴️ 沿运河堤坝散步和骑行完全免费。仅进入博物馆风车内部和搭乘游船需要购票。",
      "tip_fr": "⛴️ L'accès aux berges à pied et à vélo est gratuit. Le billet payant est requis pour les moulins musées et la croisière.",
      "tip_de": "⛴️ Der Weg entlang der Mühlen ist frei zugänglich für Fußgänger und Radfahrer. Tickets nur für Museumsmühlen und Boot.",
      "name_en": "Kinderdijk Windmills (UNESCO)",
      "name_ja": "Werelderfgoed Kinderdijk（キンデルダイクの風車群 / 世界遺産）",
      "name_es": "Molinos de Kinderdijk (UNESCO)",
      "name_zh": "小孩堤防风车群 (Kinderdijk / 世界遗产)",
      "name_fr": "Moulins de Kinderdijk (UNESCO)",
      "name_de": "Windmühlen von Kinderdijk (UNESCO)",
      "price_en": "Free Canal Walk / Visitor Ticket: from ~€16.00",
      "price_ja": "堤防散策無料 / 見学チケット: 約€16.00〜",
      "price_es": "Paseo gratis / Entrada desde ~16,00 €",
      "price_zh": "堤道散步免费 / 参观套票：约16.00 欧元起",
      "price_fr": "Promenade gratuite / Billet dès ~16,00 €",
      "price_de": "Weg frei / Besucherticket: ab ca. 16,00 €"
    }
  ]
}

THE_HAGUE_DATA = {
  "city": "The Hague",
  "country": "Netherlands",
  "city_ja": "ハーグ",
  "country_ja": "オランダ",
  "spots": [
    {
      "id": "dh_1",
      "name": "Mauritshuis（マウリッツハイス美術館）",
      "category": "Museum & Art",
      "rating": "★4.8",
      "locationZone": "city",
      "lat": 52.0804,
      "lng": 4.3143,
      "kids": False,
      "rain": True,
      "shopping": False,
      "free": False,
      "family": True,
      "adult": True,
      "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cb/Mauritshuis_The_Hague.jpg/330px-Mauritshuis_The_Hague.jpg",
      "wikiImage": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cb/Mauritshuis_The_Hague.jpg/330px-Mauritshuis_The_Hague.jpg",
      "hasWiki": True,
      "desc_en": "17th-century palace housing the Royal Cabinet of Paintings, world-famous for Vermeer's Girl with a Pearl Earring and Rembrandt's masterpieces.",
      "desc_ja": "フェルメールの『真珠の耳飾りの少女』『デルフトの眺望』やレンブラントの傑作を所蔵する17世紀のオランダ王立絵画館。",
      "desc_es": "Palacio del siglo XVII que alberga obras maestras como 'La joven de la perla' de Vermeer y obras de Rembrandt.",
      "desc_zh": "17世纪古典宫殿式荷兰皇家美术馆，收藏有维米尔名作《戴珍珠耳环的少女》、《代尔夫特风景》及伦勃朗多幅杰作。",
      "desc_fr": "Palais du XVIIe siècle abritant La Jeune Fille à la perle de Vermeer et des chefs-d'œuvre de Rembrandt.",
      "desc_de": "Palast aus dem 17. Jahrhundert mit Meisterwerken wie Vermeers 'Mädchen mit dem Perlenohrring' und Rembrandt.",
      "tip_en": "🖼️ Vermeer's 'Girl with a Pearl Earring' is in Room 15. Book the 10:00 AM opening slot or visit after 3:30 PM to view it without crowds.",
      "tip_ja": "🖼️ 『真珠の耳飾りの少女』は第15室に展示されています。混雑を避けるなら10:00開館直後の第1枠か、15:30以降の夕方の時間帯がベストです。",
      "tip_es": "🖼️ 'La joven de la perla' está en la sala 15. Visítala a primera hora (10:00) o a partir de las 15:30 para evitar aglomeraciones.",
      "tip_zh": "🖼️ 镇馆之宝《戴珍珠耳环的少女》位于第15展厅。建议预约上午10:00首场或下午15:30之后入馆避开旅游团人群。",
      "tip_fr": "🖼️ 'La Jeune Fille à la perle' se trouve en salle 15. Réservez à l'ouverture à 10h00 ou après 15h30.",
      "tip_de": "🖼️ 'Das Mädchen mit dem Perlenohrring' befindet sich in Raum 15. Am besten um 10:00 Uhr oder nach 15:30 Uhr besuchen.",
      "name_en": "The Mauritshuis",
      "name_ja": "Mauritshuis（マウリッツハイス美術館）",
      "name_es": "Museo Mauritshuis",
      "name_zh": "莫瑞泰斯皇家美术馆 (Mauritshuis)",
      "name_fr": "Musée Mauritshuis",
      "name_de": "Mauritshuis-Museum",
      "price_en": "Entry: €21.00",
      "price_ja": "入場料: €21.00",
      "price_es": "Entrada: 21,00 €",
      "price_zh": "入场费：21.00 欧元",
      "price_fr": "Entrée : 21,00 €",
      "price_de": "Eintritt: 21,00 €"
    },
    {
      "id": "dh_2",
      "name": "Het Binnenhof & Hofvijver（ビネンホフ＆ホフフェイフェルの池）",
      "category": "Landmark",
      "rating": "★4.6",
      "locationZone": "city",
      "lat": 52.0797,
      "lng": 4.3128,
      "kids": False,
      "rain": False,
      "shopping": False,
      "free": True,
      "family": True,
      "adult": True,
      "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/36/Binnenhof_Den_Haag.jpg/330px-Binnenhof_Den_Haag.jpg",
      "wikiImage": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/36/Binnenhof_Den_Haag.jpg/330px-Binnenhof_Den_Haag.jpg",
      "hasWiki": True,
      "desc_en": "13th-century Gothic castle complex that served as the political heart of the Netherlands for centuries, set beside the Hofvijver lake.",
      "desc_ja": "13世紀建造の騎士の館を中心に、数世紀にわたりオランダ政治の中枢を担ってきた歴史的城郭建築群。",
      "desc_es": "Complejo de castillo gótico del siglo XIII y corazón político histórico de los Países Bajos junto al lago Hofvijver.",
      "desc_zh": "始建于13世纪的哥特式城堡建筑群，长久以来作为荷兰政治核心，倒映在宁静的霍夫菲弗尔湖面之上。",
      "desc_fr": "Complexe médiéval du XIIIe siècle et cœur politique historique des Pays-Bas au bord de l'étang du Hofvijver.",
      "desc_de": "Gotischer Gebäudekomplex aus dem 13. Jahrhundert und historisches politisches Zentrum der Niederlande am Hofvijver.",
      "tip_en": "⚠️ Note: The Binnenhof is undergoing major renovation through 2028+ (interior and inner courtyards are closed to the public). The exterior view across the Hofvijver lake remains open.",
      "tip_ja": "⚠️ 注意：ビネンホフは大規模改修工事中（2028年以降まで継続見込み）のため、内部および中庭への立ち入りは制限されています。対岸のランゲ・フェイフェルベルフ通りから池越しに望む外観の眺望は自由に見学可能です。",
      "tip_es": "⚠️ Nota: En obras de reforma hasta 2028+ (interior y patio cerrados). La vista exterior desde el lago Hofvijver sigue accesible.",
      "tip_zh": "⚠️ 重要提示：目前整个国会大厦区域正在进行大规模闭门修缮（预计至少持续至2028年后，内部及中庭不对外开放）。可在对岸湖畔步道远眺古堡外观。",
      "tip_fr": "⚠️ Important : En travaux de rénovation jusqu'en 2028+ (intérieur et cour fermés). La vue extérieure depuis le lac reste accessible.",
      "tip_de": "⚠️ Hinweis: Wegen Großrenovierung bis mindestens 2028 innen und im Innenhof geschlossen. Der Blick vom Seeufer ist frei.",
      "name_en": "The Binnenhof & Hofvijver",
      "name_ja": "Het Binnenhof & Hofvijver（ビネンホフ＆ホフフェイフェルの池）",
      "name_es": "Binnenhof y lago Hofvijver",
      "name_zh": "荷兰国会大厦与霍夫菲弗尔湖 (Binnenhof)",
      "name_fr": "Le Binnenhof et Hofvijver",
      "name_de": "Der Binnenhof und Hofvijver",
      "price_en": "Free Lake View (Interior Closed for Renovation)",
      "price_ja": "池畔外観無料（改修工事中につき内部立入不可）",
      "price_es": "Vista exterior gratis (Interior cerrado por obras)",
      "price_zh": "湖畔外观免费（内部修缮关闭中）",
      "price_fr": "Vue extérieure gratuite (Intérieur fermé pour travaux)",
      "price_de": "Seeblick frei (Innen wegen Renovierung geschlossen)"
    }
  ]
}

UTRECHT_DATA = {
  "city": "Utrecht",
  "country": "Netherlands",
  "city_ja": "ユトレヒト",
  "country_ja": "オランダ",
  "spots": [
    {
      "id": "ut_1",
      "name": "Domtoren（ドム塔）",
      "category": "Landmark",
      "rating": "★4.8",
      "locationZone": "city",
      "lat": 52.0906,
      "lng": 5.1213,
      "kids": False,
      "rain": False,
      "shopping": False,
      "free": False,
      "family": True,
      "adult": True,
      "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6e/Domtoren_Utrecht_2019.jpg/330px-Domtoren_Utrecht_2019.jpg",
      "wikiImage": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6e/Domtoren_Utrecht_2019.jpg/330px-Domtoren_Utrecht_2019.jpg",
      "hasWiki": True,
      "desc_en": "The tallest church tower in the Netherlands (112.5m), built between 1321 and 1382, offering 465-step guided climbs to sweeping panoramic views.",
      "desc_ja": "1382年に完成したオランダで最も高い教会塔（高さ112.5m）。465段の石段ガイドツアーでユトレヒト一望のパノラマを楽しめる。",
      "desc_es": "La torre de iglesia más alta de los Países Bajos (112,5 m), con 465 escalones y vistas panorámicas espectaculares.",
      "desc_zh": "荷兰最高的教堂钟楼（高112.5米），建于1321至1382年间，可攀登465级台阶俯瞰全城景观。",
      "desc_fr": "La plus haute tour d'église des Pays-Bas (112,5 m), offrant une vue panoramique après 465 marches.",
      "desc_de": "Der höchste Kirchturm der Niederlande (112,5 m) mit 465 Stufen und Rundumblick über die Stadt.",
      "tip_en": "🎟️ Mandatory advance online booking for guided tours. The 50 carillon bells are still played live by hand on Saturday mornings.",
      "tip_ja": "🎟️ ガイドツアー制につきWEB事前予約が必須です。塔内に備わる50個の歴史的カリヨン鐘は現在も手動演奏されており、土曜の午前中などに美しい生演奏が街中に響き渡ります。",
      "tip_es": "🎟️ Reserva online obligatoria. Los sábados por la mañana se puede escuchar el carillón de campanas tocado en vivo.",
      "tip_zh": "🎟️ 登塔须参加导览团并提前在线订票。塔内配有50口古钟琴，每周六上午仍由琴师手工现场演奏钟琴乐曲。",
      "tip_fr": "🎟️ Réservation obligatoire en ligne. Le carillon de 50 cloches est joué en direct le samedi matin.",
      "tip_de": "🎟️ Führung online vorab buchen. Das Glockenspiel wird samstags morgens noch von Hand live gespielt.",
      "name_en": "Dom Tower (Domtoren)",
      "name_ja": "Domtoren（ドム塔）",
      "name_es": "Torre Dom de Utrecht",
      "name_zh": "圆顶大教堂钟楼 (Domtoren)",
      "name_fr": "Tour Dom d'Utrecht",
      "name_de": "Utrechter Domturm",
      "price_en": "Guided Tour: €14.50",
      "price_ja": "ガイドツアー入場: €14.50",
      "price_es": "Visita guiada: 14,50 €",
      "price_zh": "导览登塔票：14.50 欧元",
      "price_fr": "Visite guidée : 14,50 €",
      "price_de": "Führung: 14,50 €"
    },
    {
      "id": "ut_2",
      "name": "Rietveld Schröderhuis（リートフェルト・シュレーダー邸 / 世界遺産）",
      "category": "Museum & Art",
      "rating": "★4.7",
      "locationZone": "city",
      "lat": 52.0853,
      "lng": 5.1475,
      "kids": False,
      "rain": True,
      "shopping": False,
      "free": False,
      "family": True,
      "adult": True,
      "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Rietveld_Schroder_House_2017.jpg/330px-Rietveld_Schroder_House_2017.jpg",
      "wikiImage": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Rietveld_Schroder_House_2017.jpg/330px-Rietveld_Schroder_House_2017.jpg",
      "hasWiki": True,
      "desc_en": "UNESCO World Heritage architectural masterpiece of the De Stijl movement, designed in 1924 by Gerrit Rietveld with primary colors and flexible sliding walls.",
      "desc_ja": "ヘリット・リートフェルトが1924年に設計したデ・ステイル様式の最高傑作。原色と可動式間仕切り壁を備えた近代建築のユネスコ世界文化遺産。",
      "desc_es": "Obra maestra del movimiento De Stijl diseñada por Gerrit Rietveld en 1924, declarada Patrimonio de la Humanidad.",
      "desc_zh": "风格派（De Stijl）运动建筑代表作，由建筑师里特费尔德于1924年设计，运用三原色与可滑动空间隔板，列入世界文化遗产。",
      "desc_fr": "Chef-d'œuvre architectural du mouvement De Stijl conçu en 1924 par Gerrit Rietveld, classé UNESCO.",
      "desc_de": "UNESCO-Weltkulturerbe der De-Stijl-Bewegung, 1924 von Gerrit Rietveld mit Primärfarben und Schiebewänden entworfen.",
      "tip_en": "🎟️ Mandatory advance online booking for multimedia audio tours. The audio guide demonstrates how the upper floor converts from open space to separate rooms.",
      "tip_ja": "🎟️ 定員制のオーディオガイド見学のため、数週間前のチケット確保が必須です。2階フロアが可動間仕切りによって一つの大空間から個室へと変幻自在に変わる仕組みは必見です。",
      "tip_es": "🎟️ Visitas con audioguía y reserva previa obligatoria con semanas de antelación.",
      "tip_zh": "🎟️ 须提前在官网预订时段。语音导览会演示二楼推拉隔板如何将大空间变为独立居室。",
      "tip_fr": "🎟️ Visite avec audioguide sur réservation préalable indispensable des semaines avant.",
      "tip_de": "🎟️ Vorabbuchung zwingend erforderlich. Der Audioguide erklärt die flexible Raumaufteilung.",
      "name_en": "Rietveld Schröder House (UNESCO)",
      "name_ja": "Rietveld Schröderhuis（リートフェルト・シュレーダー邸 / 世界遺産）",
      "name_es": "Casa Rietveld Schröder (UNESCO)",
      "name_zh": "施罗德住宅 (Rietveld Schröderhuis / 世界遗产)",
      "name_fr": "Maison Rietveld Schröder (UNESCO)",
      "name_de": "Rietveld-Schröder-Haus (UNESCO)",
      "price_en": "Entry + Audio Tour: €19.00",
      "price_ja": "入場料（ガイド込）: €19.00",
      "price_es": "Entrada + audio: 19,00 €",
      "price_zh": "门票（含语音导览）：19.00 欧元",
      "price_fr": "Entrée + audioguide : 19,00 €",
      "price_de": "Eintritt + Audioguide: 19,00 €"
    }
  ]
}

MAASTRICHT_DATA = {
  "city": "Maastricht",
  "country": "Netherlands",
  "city_ja": "マーストリヒト",
  "country_ja": "オランダ",
  "spots": [
    {
      "id": "maa_1",
      "name": "Vrijthof（フライトホフ広場）",
      "category": "Landmark",
      "rating": "★4.8",
      "locationZone": "city",
      "lat": 50.8494,
      "lng": 5.6883,
      "kids": False,
      "rain": False,
      "shopping": False,
      "free": True,
      "family": True,
      "adult": True,
      "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cd/Vrijthof_Maastricht_2016.jpg/330px-Vrijthof_Maastricht_2016.jpg",
      "wikiImage": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cd/Vrijthof_Maastricht_2016.jpg/330px-Vrijthof_Maastricht_2016.jpg",
      "hasWiki": True,
      "desc_en": "Grand historic town square framed by plane trees, the twin monumental basilicas of St. Servatius and St. John, and outdoor terraces.",
      "desc_ja": "聖セルファース聖堂と聖ヤン教会が並び立つマーストリヒトの中心大広場。オープンテラスのカフェが並ぶ。",
      "desc_es": "La gran plaza central de Maastricht, flanqueada por las basílicas de San Servacio y San Juan y terrazas de cafés.",
      "desc_zh": "马斯特里赫特的中心历史大广场，耸立着圣塞尔法斯圣殿与圣约翰教堂两座地标，周围露天啤酒咖啡座林立。",
      "desc_fr": "La grande place centrale bordée par les deux basiliques historiques et de nombreuses terrasses de cafés.",
      "desc_de": "Der historische Hauptplatz mit den zwei Basiliken St. Servatius und St. Johann und belebten Terrassen.",
      "tip_en": "☕ Grab a terrace seat in the late afternoon to admire the setting sun illuminating the distinctive red limestone tower of Sint-Janskerk.",
      "tip_ja": "☕ 夕暮れ時に広場のテラス席に座り、夕日に染まる聖ヤン教会の赤い砂岩の鐘楼を眺めながら地元リンブルフビールを味わうのが至福の過ごし方です。",
      "tip_es": "☕ Siéntate en una terraza al atardecer para ver iluminada la torre roja de Sint-Janskerk.",
      "tip_zh": "☕ 建议傍晚在露天咖啡座小憩，欣赏落日余晖将圣约翰教堂独特的红色砂岩塔楼染上暖金色。",
      "tip_fr": "☕ Installez-vous en terrasse en fin d'après-midi pour admirer la tour rouge de l'église Saint-Jean au soleil couchant.",
      "tip_de": "☕ Genießen Sie am späten Nachmittag auf einer Terrasse den Blick auf den roten Turm der Sint-Janskerk.",
      "name_en": "Vrijthof Square",
      "name_ja": "Vrijthof（フライトホフ広場）",
      "name_es": "Plaza Vrijthof",
      "name_zh": "弗莱特霍夫广场 (Vrijthof)",
      "name_fr": "Place du Vrijthof",
      "name_de": "Vrijthof-Platz",
      "price_en": "Free Walk",
      "price_ja": "散策無料",
      "price_es": "Acceso libre",
      "price_zh": "免费散步",
      "price_fr": "Accès gratuit",
      "price_de": "Freier Zugang"
    },
    {
      "id": "maa_2",
      "name": "Sint-Servaasbrug（セルファース橋）",
      "category": "Landmark",
      "rating": "★4.7",
      "locationZone": "city",
      "lat": 50.8497,
      "lng": 5.6961,
      "kids": False,
      "rain": False,
      "shopping": False,
      "free": True,
      "family": True,
      "adult": True,
      "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cd/Sint_Servaasbrug_Maastricht_2016.jpg/330px-Sint_Servaasbrug_Maastricht_2016.jpg",
      "wikiImage": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cd/Sint_Servaasbrug_Maastricht_2016.jpg/330px-Sint_Servaasbrug_Maastricht_2016.jpg",
      "hasWiki": True,
      "desc_en": "13th-century limestone arch bridge spanning the Maas river, recognized as one of the oldest surviving bridges in the Netherlands.",
      "desc_ja": "マース川に架かる13世紀建造の石造アーチ橋。現存するオランダ最古級の歴史的橋梁として知られ、旧市街とウィック地区を結ぶ。",
      "desc_es": "Puente de piedra de arcos del siglo XIII sobre el río Mosa, considerado uno de los más antiguos de los Países Bajos.",
      "desc_zh": "横跨马斯河的13世纪石拱桥，被公认为荷兰现存最古老的桥梁之一，连接老城区与时尚的威克区（Wyck）。",
      "desc_fr": "Pont en pierre à arches du XIIIe siècle sur la Meuse, considéré comme l'un des plus vieux ponts des Pays-Bas.",
      "desc_de": "Steinbogenbrücke aus dem 13. Jahrhundert über die Maas, gilt als eine der ältesten Brücken der Niederlande.",
      "tip_en": "🚶 Walk across at golden hour for reflections of the old town church spires across the river. Connects directly to the boutique-lined Wyck quarter.",
      "tip_ja": "🚶 夕暮れ時に渡ると、マース川に映る旧市街の教会の尖塔と街並みが絶景です。対岸のウィック（Wyck）地区にはお洒落なセレクトショップが並んでいます。",
      "tip_es": "🚶 Crúzalo al atardecer para disfrutar de las mejores vistas del río y el casco antiguo.",
      "tip_zh": "🚶 傍晚漫步过桥，可将马斯河两岸古老教堂的尖塔与倒影尽收眼底，桥东侧连通着Wyck街区。",
      "tip_fr": "🚶 Traversez au coucher du soleil pour une vue magnifique sur les flèches de la vieille ville.",
      "tip_de": "🚶 Überqueren Sie die Brücke bei Sonnenuntergang für einen tollen Blick auf die Altstadt.",
      "name_en": "Saint Servatius Bridge",
      "name_ja": "Sint-Servaasbrug（セルファース橋）",
      "name_es": "Puente de San Servacio (Sint-Servaasbrug)",
      "name_zh": "圣塞尔法斯桥 (Sint-Servaasbrug)",
      "name_fr": "Pont Saint-Servais",
      "name_de": "Sint-Servaas-Brücke",
      "price_en": "Free Entry",
      "price_ja": "通行無料",
      "price_es": "Acceso libre",
      "price_zh": "免费通行",
      "price_fr": "Accès gratuit",
      "price_de": "Freier Zugang"
    },
    {
      "id": "maa_3",
      "name": "Grotten van Sint-Pieter（聖ピータースベルク洞窟・地下迷宮）",
      "category": "Landmark",
      "rating": "★4.6",
      "locationZone": "city",
      "lat": 50.8342,
      "lng": 5.6869,
      "kids": True,
      "rain": True,
      "shopping": False,
      "free": False,
      "family": True,
      "adult": True,
      "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/ca/Grotten_Sint-Pietersberg.jpg/330px-Grotten_Sint-Pietersberg.jpg",
      "wikiImage": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/ca/Grotten_Sint-Pietersberg.jpg/330px-Grotten_Sint-Pietersberg.jpg",
      "hasWiki": True,
      "desc_en": "Subterranean labyrinth of hand-hewn limestone quarry tunnels used as WWII bomb shelters and a historic hiding place for Rembrandt's The Night Watch.",
      "desc_ja": "石灰岩（マール）採掘によって生まれた手掘り地下坑道網。第二次世界大戦時の防空壕や『夜警』の隠し金庫として使われた歴史を持つ。",
      "desc_es": "Laberinto subterráneo de canteras de caliza donde se refugió la población y se escondió 'La ronda de noche' en la Segunda Guerra Mundial.",
      "desc_zh": "由手工开凿石灰石矿道构成的地下迷宫，二战期间曾作为防空避难所并秘密藏匿过伦勃朗的《夜巡》名画。",
      "desc_fr": "Labyrinthe souterrain de galeries creusées dans le calcaire ayant servi d'abri pendant la guerre.",
      "desc_de": "Unterirdisches Labyrinth aus Stollen, das im Zweiten Weltkrieg als Versteck für 'Die Nachtwache' diente.",
      "tip_en": "🧥 Cave temperature is 10–12°C year-round with total darkness. Sturdy walking shoes and a warm sweater are mandatory. Guided lantern tours must be booked online via Explore Maastricht.",
      "tip_ja": "🧥 洞窟内は年間を通じて気温10〜12℃と冷え込み、明かりが一切ない暗闇です。暖かい上着と歩きやすい靴が必須です。見学は公式ランタンガイドツアー（事前WEB予約）限定です。",
      "tip_es": "🧥 Temperatura constante de 10-12 °C. Imprescindible calzado cómodo y chaqueta. Visita solo con guía de linternas.",
      "tip_zh": "🧥 洞内全年恒温10–12°C且一片漆黑，请务必准备保暖外套和平底鞋。仅限参加官网预约的提灯导览团入内。",
      "tip_fr": "🧥 Température constante de 10-12 °C. Veste chaude et chaussures fermées obligatoires. Visite guidée à la lanterne sur réservation.",
      "tip_de": "🧥 Ständige Temperatur von 10–12 °C. Warme Kleidung und festes Schuhwerk zwingend erforderlich.",
      "name_en": "Mount Saint Peter Caves (Grotten)",
      "name_ja": "Grotten van Sint-Pieter（聖ピータースベルク洞窟・地下迷宮）",
      "name_es": "Cuevas de San Pedro (Grotten van Sint-Pieter)",
      "name_zh": "圣彼得堡地下洞穴迷宫",
      "name_fr": "Grottes du mont Saint-Pierre",
      "name_de": "Grotten von Sint-Pieter",
      "price_en": "Guided Tour: from ~€9.95",
      "price_ja": "ガイドツアー入場: 約€9.95〜",
      "price_es": "Visita guiada desde ~9,95 €",
      "price_zh": "导览团票：约9.95 欧元起",
      "price_fr": "Visite guidée dès ~9,95 €",
      "price_de": "Führung ab ca. 9,95 €"
    },
    {
      "id": "maa_4",
      "name": "Hoge Brug / Hoeg Brögk（ホーエ橋）",
      "category": "Landmark",
      "rating": "★4.6",
      "locationZone": "city",
      "lat": 50.8464,
      "lng": 5.6983,
      "kids": False,
      "rain": False,
      "shopping": False,
      "free": True,
      "family": True,
      "adult": True,
      "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/eb/Hoge_Brug_Maastricht_2016.jpg/330px-Hoge_Brug_Maastricht_2016.jpg",
      "wikiImage": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/eb/Hoge_Brug_Maastricht_2016.jpg/330px-Hoge_Brug_Maastricht_2016.jpg",
      "hasWiki": True,
      "desc_en": "Modern steel pedestrian and bicycle arch bridge across the Maas, known in local dialect as 'Hoeg Brögk', linking the city park to the Céramique district.",
      "desc_ja": "マース川に架かる近代的な歩行者・自転車専用スチールアーチ橋（地元方言名: Hoeg Brögk）。城壁公園とセラミック地区を結ぶ。",
      "desc_es": "Moderno puente peatonal de acero sobre el río Mosa (en dialecto local: 'Hoeg Brögk'), que une el parque con el distrito Céramique.",
      "desc_zh": "跨越马斯河的现代化钢结构人行与自行车拱桥（当地方言称作“Hoeg Brögk”），连接古城墙公园与陶瓷新区。",
      "desc_fr": "Passerelle piétonne et cyclable moderne en acier sur la Meuse (en dialecte : 'Hoeg Brögk') reliant le parc à Céramique.",
      "desc_de": "Moderne stählerne Fußgänger- und Fahrradbrücke über die Maas (im lokalen Dialekt: 'Hoeg Brögk').",
      "tip_en": "📸 The high apex of the bridge offers sweeping photography angles of river barges cruising past against the skyline of the historic city.",
      "tip_ja": "📸 橋の中央最頂部は見晴らしが良く、マース川を行き交うリバークルーズ船と歴史的街並みを同時に収める絶好の撮影スポットです。",
      "tip_es": "📸 El punto más alto del puente ofrece magníficas vistas panorámicas para fotografiar el río y la ciudad.",
      "tip_zh": "📸 桥拱最高处视野开阔，是拍摄马斯河上穿梭往来的内河驳船与两岸历史街景全景的绝佳机位。",
      "tip_fr": "📸 Le point culminant de la passerelle offre un superbe panorama pour photographier les bateaux et la ville.",
      "tip_de": "📸 Der Scheitelpunkt der Brücke bietet einen tollen Fotoblick auf die Schiffe und die Kirchtürme.",
      "name_en": "Hoge Brug (Hoeg Brögk)",
      "name_ja": "Hoge Brug / Hoeg Brögk（ホーエ橋）",
      "name_es": "Puente Hoge Brug (Hoeg Brögk)",
      "name_zh": "高桥 (Hoge Brug / 方言: Hoeg Brögk)",
      "name_fr": "Hoge Brug (Hoeg Brögk)",
      "name_de": "Hoge Brug (Hoeg Brögk)",
      "price_en": "Free Entry",
      "price_ja": "通行無料",
      "price_es": "Acceso libre",
      "price_zh": "免费通行",
      "price_fr": "Accès gratuit",
      "price_de": "Freier Zugang"
    }
  ]
}

def create_dutch_city_files():
    print("🚀 Writing new Dutch city JSON files...")
    
    # 1. Rotterdam
    with open(os.path.join(cities_dir, 'rotterdam.json'), 'w', encoding='utf-8') as f:
        json.dump(ROTTERDAM_DATA, f, indent=2, ensure_ascii=False)
    print("  - Created rotterdam.json (5 spots: ro_1..ro_5)")

    # 2. The Hague
    with open(os.path.join(cities_dir, 'the_hague.json'), 'w', encoding='utf-8') as f:
        json.dump(THE_HAGUE_DATA, f, indent=2, ensure_ascii=False)
    print("  - Created the_hague.json (2 spots: dh_1, dh_2)")

    # 3. Utrecht
    with open(os.path.join(cities_dir, 'utrecht.json'), 'w', encoding='utf-8') as f:
        json.dump(UTRECHT_DATA, f, indent=2, ensure_ascii=False)
    print("  - Created utrecht.json (2 spots: ut_1, ut_2)")

    # 4. Maastricht
    with open(os.path.join(cities_dir, 'maastricht.json'), 'w', encoding='utf-8') as f:
        json.dump(MAASTRICHT_DATA, f, indent=2, ensure_ascii=False)
    print("  - Created maastricht.json (4 spots: maa_1..maa_4)")

if __name__ == '__main__':
    create_dutch_city_files()
