import json

hamburg_spots = [
    # 1. Miniatur Wunderland
    {
        "id": "h_1",
        "name": "Miniatur Wunderland（ミニチュアワンダーランド）",
        "category": "Kids & Family", "rating": "★4.9", "locationZone": "city",
        "lat": 53.5438, "lng": 9.9888, "kids": True, "rain": True, "shopping": False, "free": False,
        "desc_en": "World's largest model railway exhibition in Speicherstadt featuring over 1,100 trains, interactive daytime/nighttime lighting cycles, and miniature airport.",
        "desc_ja": "シュパイヒャーシュタット内にある世界最大の動く鉄道模型・ジオラマテーマパーク。1,100編成超の列車、15分毎の昼夜ライティング、ミニ飛行機離着陸が精巧。",
        "desc_es": "La exposición de ferromodelismo más grande del mundo en Speicherstadt con más de 1.100 trenes y un aeropuerto en miniatura a escala.",
        "desc_zh": "坐落于仓库城的全球最大动态微缩景观模型世界。拥有1100多列运行列车、15分钟昼夜交替灯光系统与飞行飞机的微型机场。",
        "desc_fr": "La plus grande exposition de modélisme ferroviaire du monde à Speicherstadt avec plus de 1 100 trains et son aéroport miniature.",
        "de": "Größte Modellbahnanlage der Welt in der Speicherstadt mit über 1.100 Zügen, Knopfdruckaktionen und Knuffingen Airport.",
        "tip_en": "🎟️ Book fixed time-slot tickets online 3-6 weeks in advance! Visiting during late-night extended opening hours (after 8:00 PM) offers zero waiting and nighttime illuminations.",
        "tip_ja": "🎟️ 公式サイトでの数週間前Web事前予約が絶対必須！夜間特別営業枠（20:00以降）を狙うと並び時間ゼロで幻想的なジオラマ夜景を楽しめます。",
        "tip_es": "🎟️ ¡Reserva las entradas con hora fija por internet con 3 a 6 semanas de antelación! Ven pasadas las 20:00 h sin esperas.",
        "tip_zh": "🎟️ 必须提前3-6周在官网预订定时门票！特别推荐晚间延长营业场次（20:00后），免去排队且可独享夜景灯光秀。",
        "tip_fr": "🎟️ Réservez vos billets à créneau horaire en ligne des semaines à l'avance ! Privilégiez les nocturnes après 20h.",
        "tip_de": "🎟️ Zeitfenster-Tickets 3–6 Wochen im Voraus online buchen! Die Abendschichten ab 20:00 Uhr ohne Wartezeiten nutzen.",
        "price_en": "Entry: €20", "price_ja": "入場料: 20ユーロ", "price_es": "Entrada: 20€", "price_zh": "门票：20 欧元", "price_fr": "Entrée : 20 €", "price_de": "Eintritt: 20 €",
        "name_en": "Miniatur Wunderland", "name_ja": "Miniatur Wunderland（ミニチュアワンダーランド）", "name_es": "Miniatur Wunderland", "name_zh": "微缩景观世界", "name_fr": "Miniatur Wunderland", "name_de": "Miniatur Wunderland"
    },
    # 2. Elbphilharmonie Hamburg
    {
        "id": "h_2",
        "name": "Elbphilharmonie Hamburg (Elphi)（エルプフィルハーモニー・ハンブルク）",
        "category": "Landmark", "rating": "★4.8", "locationZone": "city",
        "lat": 53.5413, "lng": 9.9842, "kids": True, "rain": True, "shopping": False, "free": True,
        "desc_en": "Herzog & de Meuron-designed landmark concert hall combining a wave-like glass superstructure atop a historic 1966 brick warehouse at Hamburg harbor.",
        "desc_ja": "ヘルツォーク＆ド・ムーロン設計のガラス建築。歴史的赤レンガ倉庫の上に波打つガラスが載るハンブルク港のシンボル。",
        "desc_es": "Sala de conciertos icónica diseñada por Herzog & de Meuron que combina una superestructura de cristal ondulado sobre un almacén de ladrillo.",
        "desc_zh": "由 Herzog & de Meuron 设计的浪涌玻璃地标音乐厅。在1966年老红砖仓库上方耸立着波浪形玻璃结构。",
        "desc_fr": "Salle de concert emblématique conçue par Herzog & de Meuron surmontant un ancien entrepôt en brique.",
        "de": "Imposantes Konzerthaus von Herzog & de Meuron mit kühnem Glasaufbau auf einem historischen Backspeicher.",
        "tip_en": "📸 Pick up a free Plaza Ticket at the ground ticket counter to ride the 82-meter curved escalator ('The Tube') up to the 37m outdoor observation deck!",
        "tip_ja": "📸 発券カウンターで無料のプラザ入場券（Plaza Ticket）を受け取り、全長82mの曲面エスカレーター『The Tube』で37m高さの風が吹き抜ける屋外パノラマデッキへ！",
        "tip_es": "📸 Recoge la entrada gratuita Plaza Ticket en taquilla para subir por la escalera mecánica curva de 82m hasta el mirador exterior.",
        "tip_zh": "📸 可在1楼票务柜台免费领取 Plaza 观景台门票！搭乘长达82米的弧形隧道电梯（The Tube）升至37米高环形露台。",
        "tip_fr": "📸 Prenez un billet gratuit Plaza Ticket au guichet pour emprunter l'escalator courbe de 82m vers la terrasse panoramique.",
        "tip_de": "📸 Kostenloses Plaza-Ticket am Schalter holen und mit der 82m langen gebogenen Rolltreppe ('Tube') zum Panoramadeck fahren.",
        "price_en": "Plaza Free (Concerts Varies)", "price_ja": "展望プラザ無料（公演料別途）", "price_es": "Plaza gratis (Conciertos varía)", "price_zh": "观景广场免费（演出门票另计）", "price_fr": "Plaza gratuite (Concerts variable)", "price_de": "Plaza frei (Konzertkarten variieren)",
        "name_en": "Elbphilharmonie Concert Hall", "name_ja": "Elbphilharmonie Hamburg (Elphi)（エルプフィルハーモニー・ハンブルク）", "name_es": "Filarmónica del Elba", "name_zh": "易北爱乐厅", "name_fr": "Philharmonie de l'Elbe", "name_de": "Elbphilharmonie Hamburg"
    },
    # 3. Speicherstadt
    {
        "id": "h_3",
        "name": "Speicherstadt（シュパイヒャーシュタット / 世界遺産赤レンガ倉庫街）",
        "category": "Landmark", "rating": "★4.8", "locationZone": "city",
        "lat": 53.5433, "lng": 9.9922, "kids": True, "rain": False, "shopping": False, "free": True,
        "desc_en": "UNESCO World Heritage site built between 1883 and 1927, the world's largest warehouse complex resting on oak piles along canal waterways.",
        "desc_ja": "1883〜1927年建設の世界遺産。運河の水路沿いにオーク材の杭で支えられた赤レンガ倉庫群が連なる世界最大の倉庫街。",
        "desc_es": "Patrimonio de la Humanidad por la UNESCO, el complejo de almacenes sobre pilares de roble más grande del mundo entre canales.",
        "desc_zh": "建于1883至1927年间的世界文化遗产。矗立于运河水系橡木桩基础上的世界最大规模红砖历史仓库群。",
        "desc_fr": "Site classé UNESCO, le plus grand complexe d'entrepôts au monde sur pieux en chêne le long des canaux.",
        "de": "UNESCO-Welterbe und größter zusammenhängender Lagerhauskomplex der Welt auf Eichenpfählen in den Fleeten.",
        "tip_en": "📸 Stand on the Poggenmühlenbrücke bridge at dusk to shoot the classic postcard photo of Wasserschloss illuminated between two canal branches!",
        "tip_ja": "📸 日没時の『Poggenmühlenbrücke』橋の上が絶景アングル！2つの運河の分岐点に立つ水上城館『Wasserschloss』のライトアップが水面に映えます。",
        "tip_es": "📸 Sitúate en el puente Poggenmühlenbrücke al atardecer para fotografiar el edificio Wasserschloss iluminado entre canales.",
        "tip_zh": "📸 黄昏蓝调时刻打卡 Poggenmühlenbrücke 铁桥！拍摄立于双干运河汇合处的“水上城堡”（Wasserschloss）倒影佳作。",
        "tip_fr": "📸 Placez-vous sur le pont Poggenmühlenbrücke à la tombée du jour pour photographier le Wasserschloss illuminé.",
        "tip_de": "📸 Zur blauen Stunde auf der Poggenmühlenbrücke stehen für das klassische Motiv des beleuchteten Wasserschlosses im Fleet.",
        "price_en": "Free Access", "price_ja": "散策無料", "price_es": "Acceso libre", "price_zh": "免费游览", "price_fr": "Accès libre", "price_de": "Kostenlos",
        "name_en": "Speicherstadt Warehouse District", "name_ja": "Speicherstadt（シュパイヒャーシュタット / 世界遺産赤レンガ倉庫街）", "name_es": "Distrito Speicherstadt", "name_zh": "仓库城", "name_fr": "Speicherstadt", "name_de": "Speicherstadt Hamburg"
    },
    # 4. Kontorhausviertel & Chilehaus
    {
        "id": "h_4",
        "name": "Kontorhausviertel & Chilehaus（コントーアハウス地区＆チリハウス）",
        "category": "Landmark", "rating": "★4.7", "locationZone": "city",
        "lat": 53.5483, "lng": 10.0019, "kids": True, "rain": False, "shopping": False, "free": True,
        "desc_en": "UNESCO-listed 1920s Brick Expressionist office district featuring Fritz Höger's Chilehaus, shaped like a massive ocean liner's sharp bow.",
        "desc_ja": "1920年代のレンガ表現主義建築群（世界遺産）。建築家フリッツ・ヘーガー作『チリハウス（Chilehaus）』の船首のように尖った角部が見事。",
        "desc_es": "Distrito de oficinas expresionista de ladrillo de los años 20 (UNESCO) con el edificio Chilehaus en forma de proa de buque.",
        "desc_zh": "联合国教科文组织1920年代砖木表现主义办公区。大师 Fritz Höger 设计的 Chilehaus 宛如巨轮尖锐的船首斜插云霄。",
        "desc_fr": "Quartier d'affaires expressionniste en brique des années 1920 (UNESCO) avec l'immeuble Chilehaus en forme de proue de navire.",
        "de": "UNESCO-Welterbe-Ensemble des Backsteinexpressonismus der 1920er Jahre mit dem chilehaus im Stil eines Schiffsbugs.",
        "tip_en": "📸 Stand at the intersection of Fischertwiete and Burchardstraße to look directly up at the razor-sharp 45-degree angle corner of Chilehaus!",
        "tip_ja": "📸 『Fischertwiete』と『Burchardstraße』の交差点の角へ！Chilehausの鋭角45度に研ぎ澄まされた船首のような角部を見上げる構図が最高です。",
        "tip_es": "📸 Colócate en el cruce de Fischertwiete y Burchardstraße para ver la esquina en ángulo agudo del Chilehaus.",
        "tip_zh": "📸 站在 Fischertwiete 与 Burchardstraße 交叉路口！抬头仰拍 Chilehaus 呈45度极尽犀利的“船首”外墙角。",
        "tip_fr": "📸 Placez-vous au croisement de Fischertwiete et Burchardstraße pour photographier l'angle aigu spectaculaire.",
        "tip_de": "📸 An der Kreuzung Fischertwiete/Burchardstraße stehen und den rasiermesserscharfen Schiffsbug-Winkel nach oben fotografieren.",
        "price_en": "Free Access", "price_ja": "見学無料", "price_es": "Acceso libre", "price_zh": "免费参观", "price_fr": "Accès libre", "price_de": "Kostenlos",
        "name_en": "Chilehaus & Kontorhaus District", "name_ja": "Kontorhausviertel & Chilehaus（コントーアハウス地区＆チリハウス）", "name_es": "Chilehaus y Kontorhausviertel", "name_zh": "智利大厦与写字楼区", "name_fr": "Chilehaus et quartier des comptoirs", "name_de": "Kontorhausviertel & Chilehaus"
    },
    # 5. Hamburger Rathaus & Rathausmarkt
    {
        "id": "h_5",
        "name": "Hamburger Rathaus & Rathausmarkt（ハンブルク市庁舎＆市庁舎前広場）",
        "category": "Landmark", "rating": "★4.8", "locationZone": "city",
        "lat": 53.5503, "lng": 9.9928, "kids": True, "rain": True, "shopping": False, "free": True,
        "desc_en": "Palatial 1897 Neo-Renaissance city hall with 647 rooms, featuring a 112m spire tower, Hygieia courtyard fountain, and elaborate state rooms.",
        "desc_ja": "バッキンガム宮殿より部屋数が多い647室を誇る1897年建造のネオ・ルネサンス宮殿風市庁舎。中央の112mの塔と中庭のヒュギエイアの噴水が印象的。",
        "desc_es": "Palaciego ayuntamiento neorrenacentista de 1897 con 647 habitaciones, torre de 112m y patio con la Fuente de Higía.",
        "desc_zh": "建于1897年媲美王宫的新文艺复兴风格市府大楼。拥有647间房间、112米高的中央尖塔与中庭希吉亚健康女神喷泉。",
        "desc_fr": "Hôtel de ville néo-renaissance grandiose de 1897 aux 647 pièces avec une tour de 112m et sa cour intérieure.",
        "de": "Neurenaissance-Rathaus von 1897 mit 647 Räumen, 112m hohem Turm und dem Hygieia-Brunnen im Innenhof.",
        "tip_en": " Walk into the quiet inner courtyard (Innenhof) behind the main hall to admire the bronze Hygieia Fountain commemorating the 1892 cholera epidemic.",
        "tip_ja": " 市庁舎中央のアーチをくぐって静かな中庭（Innenhof）へ！1892年のコレラ終息を記念して造られたブロンズ製のヒュギエイアの噴水（Hygieia-Brunnen）が隠れた見どころです。",
        "tip_es": " Entra al patio interior por el arco central para ver la Fuente de Higía de bronce que conmemora la epidemia de 1892.",
        "tip_zh": " 穿过主楼中央拱门推步进入中庭（Innenhof）！观赏为纪念1892年霍乱疫情平息而建的铜雕希吉亚健康女神喷泉（Hygieia-Brunnen）。",
        "tip_fr": " Entrez dans la cour intérieure calme pour admirer la fontaine d'Hygie en bronze.",
        "tip_de": " Durch das Torbogen-Portal in den ruhigen Innenhof gehen, um den bronzenen Hygieia-Brunnen von 1895 zu besichtigen.",
        "price_en": "Courtyard Free (Guided Tour €5)", "price_ja": "中庭無料（内部ガイドツアー: 5ユーロ）", "price_es": "Patio gratis (Tour guiado 5€)", "price_zh": "中庭免费（导览5欧）", "price_fr": "Cour gratuite (Visite guidée 5 €)", "price_de": "Innenhof frei (Führung 5 €)",
        "name_en": "Hamburg City Hall", "name_ja": "Hamburger Rathaus & Rathausmarkt（ハンブルク市庁舎＆市庁舎前広場）", "name_es": "Ayuntamiento de Hamburgo", "name_zh": "汉堡市政厅", "name_fr": "Hôtel de ville de Hambourg", "name_de": "Hamburger Rathaus & Rathausmarkt"
    },
    # 6. Hauptkirche St. Michaelis (Michel)
    {
        "id": "h_6",
        "name": "Hauptkirche St. Michaelis (Michel)（聖ミヒャエリス教会）",
        "category": "Landmark", "rating": "★4.7", "locationZone": "city",
        "lat": 53.5483, "lng": 9.9789, "kids": True, "rain": True, "shopping": False, "free": True,
        "desc_en": "Hamburg's iconic 1762 Baroque Protestant church known affectionate as 'Michel', featuring a copper-covered 132-meter clock tower.",
        "desc_ja": "『ミヒェル』の愛称で親しまれる1762年建造のバロック様式プロテスタント教会。銅板に覆われた高さ132mの時計塔が航海の目印。",
        "desc_es": "Iglesia barroca de 1762 conocida como 'Michel' con una torre con reloj recubierta de cobre de 132 metros.",
        "desc_zh": "法兰克福老航海者心目中的灯塔。建于1762年巴洛克风格新教大教堂，拥有132米高的包铜钟楼尖塔。",
        "desc_fr": "Église baroque de 1762 surnommée 'Michel' avec son clocher en cuivre de 132 mètres guidant los marins.",
        "de": "Wahrzeichen Hamburgs von 1762 im Barockstil mit 132m hohem kupferverkleidetem Turm.",
        "tip_en": " Listen for the traditional 'Türmer' brass trumpeter playing a chorale from the 106m tower platform every day at 10:00 AM and 9:00 PM!",
        "tip_ja": " 毎日午前10:00と夜21:00に注目！106mの塔の上からトランペット奏者（Türmer）が東西南北に向かって讃美歌を吹奏する歴史的儀式を塔下で聴くことができます。",
        "tip_es": " Escucha el trompetista tradicional Türmer tocar desde la plataforma de la torre todos los días a las 10:00 y a las 21:00 h.",
        "tip_zh": " 每天上午10点与夜间21点准时抬头聆听！号手（Türmer）会在106米高空四面吹响传统赞美诗长号。",
        "tip_fr": " Écoutez le trompettiste traditionnel jouer un choral depuis la tour tous les jours à 10h et 21h.",
        "tip_de": " Täglich um 10:00 und 21:00 Uhr dem 'Türmer' lauschen, der vom Turm ein Trompetensignal in alle vier Himmelsrichtungen bläst.",
        "price_en": "Church Free (Tower €8)", "price_ja": "聖堂無料（塔登頂: 8ユーロ）", "price_es": "Iglesia gratis (Torre 8€)", "price_zh": "教堂免费（登塔8欧）", "price_fr": "Église gratuite (Tour 8 €)", "price_de": "Kirche frei (Turm 8 €)",
        "name_en": "St. Michael's Church", "name_ja": "Hauptkirche St. Michaelis (Michel)（聖ミヒャエリス教会）", "name_es": "Iglesia de San Miguel", "name_zh": "圣米歇尔大教堂", "name_fr": "Église Saint-Michel de Hambourg", "name_de": "Hauptkirche St. Michaelis (Michel)"
    },
    # 7. Hamburger Hafen & Landungsbrücken
    {
        "id": "h_7",
        "name": "Hamburger Hafen & Landungsbrücken（ハンブルク港＆ザンクト・パウリ桟橋）",
        "category": "Landmark", "rating": "★4.7", "locationZone": "city",
        "lat": 53.5458, "lng": 9.9669, "kids": True, "rain": False, "shopping": False, "free": True,
        "desc_en": "Germany's largest seaport featuring the historic 1907 St. Pauli floating piers (Landungsbrücken), harbor tours, and massive container ships.",
        "desc_ja": "ドイツ最大の巨大港。1907年建造の浮き桟橋『ザンクト・パウリ桟橋』から港湾クルーズ船が交差し、巨大コンテナ船が行き交う。",
        "desc_es": "El puerto más grande de Alemania con los muelles flotantes históricos de St. Pauli de 1907 y recorridos en barco.",
        "desc_zh": "德国最大海港。始于1907年的 St. Pauli 巨型水上浮动码头长廊，大型集装箱货轮与观光游船在此穿梭交织。",
        "desc_fr": "Le plus grand port d'Allemagne avec les embarcadères flottants de St. Pauli de 1907 et balades en bateau.",
        "de": "Größter Seehafen Deutschlands mit den historischen schwimmenden St. Pauli Landungsbrücken von 1907.",
        "tip_en": "🎟️ Take HADAG Harbor Ferry Line 62 (Bridge 3) using a standard HVV public transport ticket for a budget-friendly 1-hour round-trip cruise past Övelgönne beach!",
        "tip_ja": "🎟️ 3番桟橋から『HADAG定期フェリー62番線』に乗車！一般的な一日乗車券（HVV ticket）のまま、巨大コンテナ船をすり抜ける格安1時間港湾クルーズが楽しめます。",
        "tip_es": "🎟️ ¡Toma el ferri HADAG línea 62 (Muelle 3) con el billete normal de transporte público HVV para un crucero económico!",
        "tip_zh": "🎟️ 在3号码头搭乘 HADAG 62号渡轮！刷通用 HVV 公共交通一日券即可畅享超划算的1小时美景港湾游船。",
        "tip_fr": "🎟️ Prenez le ferry HADAG ligne 62 au ponton 3 avec un ticket de transport public classique pour une croisière économique !",
        "tip_de": "🎟️ Die HADAG-Hafenfähre Linie 62 an Brücke 3 mit einem normalen HVV-Tagesticket für eine preiswerte Hafenrundfahrt nutzen!",
        "price_en": "Free Stroll (Ferry €3.80 / Tour €18)", "price_ja": "桟橋無料（フェリー3.80ユーロ/クルーズ18ユーロ）", "price_es": "Paseo gratis (Ferry 3,80€)", "price_zh": "散步免费（渡轮3.80欧）", "price_fr": "Promenade gratuite (Ferry 3,80 €)", "price_de": "Promenade frei (Fähre 3,80 €)",
        "name_en": "Hamburg Harbor & St. Pauli Piers", "name_ja": "Hamburger Hafen & Landungsbrücken（ハンブルク港＆ザンクト・パウリ桟橋）", "name_es": "Puerto de Hamburgo y Landungsbrücken", "name_zh": "汉堡港与圣保利码头", "name_fr": "Port de Hambourg et Landungsbrücken", "name_de": "Hamburger Hafen & Landungsbrücken"
    },
    # 8. Alter Elbtunnel
    {
        "id": "h_8",
        "name": "Alter Elbtunnel (St. Pauli Elbtunnel)（旧エルベトンネル）",
        "category": "Landmark", "rating": "★4.7", "locationZone": "city",
        "lat": 53.5458, "lng": 9.9664, "kids": True, "rain": True, "shopping": False, "free": True,
        "desc_en": "Historic 1911 underwater tunnel 24 meters beneath the Elbe river, spanning 426 meters with vintage lifts and maritime ceramic tile reliefs.",
        "desc_ja": "1911年開通。エルベ川の24m水底を貫く全長426mの歴史的水底トンネル。クラシックなレトロエレベーターと魚モチーフのセラミック壁画が映える。",
        "desc_es": "Túnel subterráneo histórico de 1911 a 24m bajo el río Elba, de 426m de longitud con ascensores vintage.",
        "desc_zh": "始于1911年下穿易北河水底24米深的426米长历史隧道。配有古董车辆大电梯与精致的海鲜海洋瓷砖浮雕。",
        "desc_fr": "Túnel sous-marin historique de 1911 sous le fleuve Elbe à 24m de profondeur avec ascenseurs vintage.",
        "de": "Historischer Unterwassertunnel von 1911 unter der Elbe (24m tief, 426m lang) mit alten Fahrzeugaufzügen.",
        "tip_en": "📸 Walk through the tunnel to the south bank (Steinwerder) to enjoy the panoramic skyline view of Landungsbrücken and St. Michaelis church reflecting over the water!",
        "tip_ja": "📸 トンネルを歩いて対岸の『Steinwerder』へ！階段を登って地表へ出ると、対岸の桟橋と聖ミヒャエリス教会の尖塔を正面に望む穴場のパノラマ写真が撮影できます。",
        "tip_es": "📸 Camina por el túnel hasta la orilla sur (Steinwerder) para disfrutar de la vista panorámica del puerto.",
        "tip_zh": "📸 徒步穿过426米隧道抵达南岸（Steinwerder）！登上地表，俯瞰对岸圣保利码头与大教堂尖塔构成的天际线全景大片。",
        "tip_fr": "📸 Traversez le tunnel vers la rive sud (Steinwerder) pour admirer le panorama sur le port.",
        "tip_de": "📸 Zu Fuß durch den Tunnel zur Südseite (Steinwerder) gehen: Von dort hat man den besten Blick auf die Landungsbrücken und den Michel.",
        "price_en": "Free Pedestrian Access", "price_ja": "歩行者通行無料", "price_es": "Acceso peatonal gratis", "price_zh": "行人免费通行", "price_fr": "Gratuit pour piétons", "price_de": "Kostenlos für Fußgänger",
        "name_en": "Old Elbe Tunnel", "name_ja": "Alter Elbtunnel (St. Pauli Elbtunnel)（旧エルベトンネル）", "name_es": "Antiguo Túnel del Elba", "name_zh": "旧易北河隧道", "name_fr": "Vieux tunnel sous l'Elbe", "name_de": "Alter Elbtunnel Hamburg"
    },
    # 9. HafenCity
    {
        "id": "h_9",
        "name": "HafenCity（ハーフェンシティ）",
        "category": "Landmark", "rating": "★4.6", "locationZone": "city",
        "lat": 53.5417, "lng": 9.9986, "kids": True, "rain": False, "shopping": False, "free": True,
        "desc_en": "Europe's largest urban waterfront redevelopment project covering 157 hectares, featuring sustainable modern architecture, promenades, and harbor basins.",
        "desc_ja": "旧港湾倉庫街を最新都市へと刷新する157ヘクタールの欧州最大規模ウォーターフロント再開発地区。先端建築と水辺プロムナードが魅力。",
        "desc_es": "El proyecto de reurbanización marítima más grande de Europa de 157 hectáreas con arquitectura moderna y paseos marítimos.",
        "desc_zh": "全欧洲规模最大的滨水城市更新重构区（157公顷）。集最前沿现代建筑、水岸悬空步道与港湾码头于一体。",
        "desc_fr": "Le plus grand projet de réaménagement urbain portuaire d'Europe sur 157 hectares avec architecture avant-gardiste.",
        "de": "Größtes innerstädtisches Stadtentwicklungsprojekt Europas auf 157 Hektar am Wasser.",
        "tip_en": "📸 Stroll along Marco-Polo-Terrassen to capture modern glass architecture reflecting on the water alongside historic floating pontoon boats.",
        "tip_ja": "📸 マルコ・ポーロ・テラス（Marco-Polo-Terrassen）へ！モダンな大ガラスビル群と水面に浮かぶクラシックボートが対比を成す素晴らしい撮影スポットです。",
        "tip_es": "📸 Pasea por Marco-Polo-Terrassen para fotografiar la arquitectura de cristal reflejada sobre los pontones de agua.",
        "tip_zh": "📸 漫步于马可波罗露台（Marco-Polo-Terrassen）！拍摄现代通透玻璃幕墙与水面古董系泊艇构成的空间感大片。",
        "tip_fr": "📸 FLânez sur Marco-Polo-Terrassen pour photographier l'architecture de verre se reflétant sur l'eau.",
        "tip_de": "📸 Über die Marco-Polo-Terrassen schlendern und die moderne Architektur am Wasser fotografieren.",
        "price_en": "Free Access", "price_ja": "散策無料", "price_es": "Acceso libre", "price_zh": "免费游览", "price_fr": "Accès libre", "price_de": "Kostenlos",
        "name_en": "HafenCity District", "name_ja": "HafenCity（ハーフェンシティ）", "name_es": "HafenCity", "name_zh": "哈芬城", "name_fr": "HafenCity", "name_de": "HafenCity Hamburg"
    },
    # 10. Binnenalster & Außenalster
    {
        "id": "h_10",
        "name": "Binnenalster & Außenalster（ビンネンアルスター湖＆アウセンアルスター湖）",
        "category": "Scenery & Walk", "rating": "★4.8", "locationZone": "city",
        "lat": 53.5539, "lng": 9.9961, "kids": True, "rain": False, "shopping": False, "free": True,
        "desc_en": "Two iconic artificial lakes created in the 13th century in central Hamburg, famous for the 60m Alsterfontäne jet, sailing boats, and 7.4km park perimeter path.",
        "desc_ja": "13世紀にアルスター川を堰き止めて造られたハンブルク中心部の2大巨大湖。高さ60mの噴水『アルスターフォンテーヌ』と7.4kmの周遊遊歩道が広がる。",
        "desc_es": "Dos lagos emblemáticos creados en el siglo XIII en el centro de Hamburgo con el gran chorro de agua Alsterfontäne de 60m.",
        "desc_zh": "建于13世纪位于市中心的标志性双连湖泊。拥有高达60米喷涌的 Alsterfontäne 湖中大喷泉与7.4公里长的湖畔绿荫步道。",
        "desc_fr": "Deux grands lacs emblématiques du XIIIe siècle au cœur de Hambourg avec le jet d'eau Alsterfontäne de 60m.",
        "de": "Zwei große Alsterseen im Herzen Hamburgs mit der 60 Meter hohen Alsterfontäne und Segelbooten.",
        "tip_en": " Rent a wooden rowing boat or stand-up paddleboard at 'Barca' or 'Bootshaus Bar' on the Außenalster lake, and row right past grand white villas!",
        "tip_ja": " 外湖（Außenalster）東岸の『Bootshaus Bar』で手漕ぎボートやSUPをレンタル！白い高級邸宅の並ぶ水路を優雅に水上散歩できます。",
        "tip_es": " Alquila una barca de remos en la orilla del lago Außenalster y navega frente a las grandes villas blancas.",
        "tip_zh": " 在外湖（Außenalster）湖畔的 Bootshaus Bar 租用木桨划艇或 SUP 划板！在白净豪宅环绕的碧波湖面上荡桨。",
        "tip_fr": " Louez une barque à rames sur le lac Außenalster pour naviguer au pied des grandes villas blanches !",
        "tip_de": " Am Außenalster-Ufer ein Tretboot oder Stand-Up-Paddle mieten und an den weißen Alstervillen vorbeipaddeln.",
        "price_en": "Lake Free (Boat Rental €14/hr)", "price_ja": "散策無料（ボート貸出: 14ユーロ/時間）", "price_es": "Lago gratis (Barca 14€/h)", "price_zh": "湖畔免费（租船14欧/时）", "price_fr": "Lac gratuit (Barque 14 €/h)", "price_de": "See frei (Boot mieten 14 €/Std.)",
        "name_en": "Alster Lakes", "name_ja": "Binnenalster & Außenalster（ビンネンアルスター湖＆アウセンアルスター湖）", "name_es": "Lagos del Alster", "name_zh": "阿尔斯特内湖与外湖", "name_fr": "Lacs de l'Alster", "name_de": "Binnenalster & Außenalster"
    },
    # 11. Hamburger Kunsthalle
    {
        "id": "h_11",
        "name": "Hamburger Kunsthalle（ハンブルク美術館）",
        "category": "Museum & Gallery", "rating": "★4.7", "locationZone": "city",
        "lat": 53.5550, "lng": 10.0025, "kids": True, "rain": True, "shopping": False, "free": False,
        "desc_en": "Major European art museum spanning 3 connected buildings holding Caspar David Friedrich's iconic 'Wanderer above the Sea of Fog', Rembrandt, and Manet.",
        "desc_ja": "3つの赤レンガ・現代館が繋がる美術館。カスパー・ダーヴィト・フリードリヒの至宝『雲海の上の旅人』やレンブラント、マネの名画を展示。",
        "desc_es": "Gran museo de arte europeo que alberga la icónica obra 'El caminante sobre el mar de nubes' de Friedrich y pinturas de Rembrandt.",
        "desc_zh": "由三栋相连建筑组成的欧洲知名艺术馆。收藏有 Caspar David Friedrich 镇馆名画《云海之上的旅人》及伦勃朗、马奈珍品。",
        "desc_fr": "Grand musée d'art européen abritant le chef-d'œuvre 'Le Voyageur contemplant une mer de nuages' de Friedrich.",
        "de": "Bedeutendes Kunstmuseum in drei Gebäuden mit Caspar David Friedrichs 'Der Wanderer über dem Nebelmeer'.",
        "tip_en": "🖼️ Head straight to Room 16 in the Lichtwark-Bau to stand directly in front of Caspar David Friedrich's world-famous masterwork 'Wanderer above the Sea of Fog'!",
        "tip_ja": "🖼️ 旧館（Lichtwark-Bau）の第16展示室へ直行！ドイツ・ロマン派最高峰の傑作『雲海の上の旅人（Der Wanderer über dem Nebelmeer）』を静かに観賞できます。",
        "tip_es": "🖼️ Dirígete a la sala 16 del edificio histórico para ver la famosa pintura 'El caminante sobre el mar de nubes'.",
        "tip_zh": "🖼️ 直奔旧馆 Lichtwark-Bau 16号展厅！近距离沉浸观赏传世名作《云海之上的旅人》（Wanderer above the Sea of Fog）。",
        "tip_fr": "🖼️ Rendez-vous dans la salle 16 du bâtiment ancien pour admirer le tableau mythique de Caspar David Friedrich.",
        "tip_de": "🖼️ Direkt in Raum 16 des Lichtwark-Baus gehen, um Caspar David Friedrichs 'Wanderer über dem Nebelmeer' im Original zu sehen.",
        "price_en": "Entry: €14", "price_ja": "入場料: 14ユーロ", "price_es": "Entrada: 14€", "price_zh": "门票：14 欧元", "price_fr": "Entrée : 14 €", "price_de": "Eintritt: 14 €",
        "name_en": "Hamburg Art Museum", "name_ja": "Hamburger Kunsthalle（ハンブルク美術館）", "name_es": "Kunsthalle de Hamburgo", "name_zh": "汉堡艺术馆", "name_fr": "Kunsthalle de Hambourg", "name_de": "Hamburger Kunsthalle"
    },
    # 12. Internationales Maritimes Museum Hamburg
    {
        "id": "h_12",
        "name": "Internationales Maritimes Museum Hamburg（国際海洋博物館）",
        "category": "Museum & Gallery", "rating": "★4.8", "locationZone": "city",
        "lat": 53.5436, "lng": 10.0003, "kids": True, "rain": True, "shopping": False, "free": False,
        "desc_en": "World's largest private maritime collection inside Speicherstadt's oldest warehouse (Kaispeicher B), spanning 9 decks with 50,000 ship models and 3,000 years of seafaring history.",
        "desc_ja": "倉庫街最古の赤レンガ倉庫『カイシュパイヒャーB』内の世界最大級の私立海洋博物館。9個のデッキに5万隻の精密船模型と3000年の航海史を展示。",
        "desc_es": "La mayor colección marítima privada del mundo en el almacén más antiguo de Speicherstadt, con 9 cubiertas y 50.000 maquetas de barcos.",
        "desc_zh": "位于仓库城最古老仓库 Kaispeicher B 内的全球最大私人航海博物馆。分设9层甲板展厅，陈列5万只微缩精细船模与3000年航海史。",
        "desc_fr": "La plus grande collection maritime privée au monde dans le plus vieil entrepôt de Speicherstadt, répartie sur 9 ponts.",
        "de": "Größte maritime Privatsammlung der Welt im ältesten Speichergebäude (Kaispeicher B) mit 9 Ausstellungsdecks.",
        "tip_en": " Take Deck 9 to view Peter Tamm's legendary bone ship models made by French prisoners of war from livestock bones during the Napoleonic Wars!",
        "tip_ja": " 最上階『Deck 9』へ直行！ナポレオン戦争期のフランス軍捕虜が支給肉の骨から削り出した繊細を極める『骨製船模型（Bone Ships）』は奇跡の完成度です。",
        "tip_es": " Sube a la cubierta 9 para ver las maquetas de barcos hechas de hueso por prisioneros de guerra de las Guerras Napoleónicas.",
        "tip_zh": " 登顶最上方第9层甲板展区（Deck 9）！观赏拿破仑战争时期法国战俘利用吃剩下兽骨精雕细琢而成的奇迹“骨雕船模”（Bone Ships）。",
        "tip_fr": " Montez au pont 9 pour admirer les maquetas de bateaux en os sculptées par des prisonniers de guerre napoléoniens.",
        "tip_de": " Auf Deck 9 die faszinierenden Knochenschiffe besichtigen, die französische Kriegsgefangene aus Tierknochen schnitzten.",
        "price_en": "Entry: €17", "price_ja": "入場料: 17ユーロ", "price_es": "Entrada: 17€", "price_zh": "门票：17 欧元", "price_fr": "Entrée : 17 €", "price_de": "Eintritt: 17 €",
        "name_en": "International Maritime Museum", "name_ja": "Internationales Maritimes Museum Hamburg（国際海洋博物館）", "name_es": "Museo Marítimo Internacional", "name_zh": "国际航海博物馆", "name_fr": "Musée maritime international de Hambourg", "name_de": "Internationales Maritimes Museum Hamburg"
    },
    # 15. Cap San Diego
    {
        "id": "h_15",
        "name": "Cap San Diego（カプ・サン・ディエゴ号）",
        "category": "Landmark", "rating": "★4.7", "locationZone": "city",
        "lat": 53.5433, "lng": 9.9767, "kids": True, "rain": True, "shopping": False, "free": False,
        "desc_en": "World's largest seaworthy museum cargo ship built in 1961, permanently moored at Überseebrücke with full access to engine room, shaft tunnel, and bridge.",
        "desc_ja": "1961年建造の航行可能な世界最大の博物館貨物船『白鳥（White Swan）』。巨大な機関室、プロペラシャフトトンネル、船橋（操舵室）を自由探検。",
        "desc_es": "El buque de carga museo navegable más grande del mundo (1961) amarrado en el puerto con acceso a la sala de máquinas y el puente.",
        "desc_zh": "建于1961年目前全球规模最大且依然具备适航能力的博物馆货轮（誉为南大西洋白天鹅）。开放庞大的轮机舱、轴隧道与船长指挥驾驶台。",
        "desc_fr": "Le plus grand cargo musée navigable au monde (1961) amarré au port avec accès libre aux machines et au passerelle.",
        "de": "Größtes seetüchtiges Museumsschiff der Welt von 1961 an der Überseebrücke mit freiem Zugang zum Maschinenraum.",
        "tip_en": " Climb down into the narrow 40-meter shaft tunnel (Wellentunnel) running deep inside the ship's hull along the giant propeller shaft!",
        "tip_ja": " 船底最深部にある全長40mのプロペラ軸トンネル（Wellentunnel）へ！暗く狭い鋼鉄のトンネルを探索する冒険感がたまりません。",
        "tip_es": " Desciende al estrecho túnel del eje de la hélice de 40 metros en lo más profundo del casco del barco.",
        "tip_zh": " 沿着狭窄梯步深入船底最深处40米长的螺旋桨驱动轴隧道（Wellentunnel）！体验沉浸式机械工程穿行。",
        "tip_fr": " Descendez dans le tunnel étroit du arbre d'hélice de 40 mètres au fond de la coque du navire.",
        "tip_de": " In den 40 Meter langen Wellentunnel im tiefen Bauch des Schiffs hinabsteigen und die Propellerwelle erkunden.",
        "price_en": "Entry: €11", "price_ja": "入場料: 11ユーロ", "price_es": "Entrada: 11€", "price_zh": "门票：11 欧元", "price_fr": "Entrée : 11 €", "price_de": "Eintritt: 11 €",
        "name_en": "Cap San Diego Museum Ship", "name_ja": "Cap San Diego（カプ・サン・ディエゴ号）", "name_es": "Buque Museo Cap San Diego", "name_zh": "圣迭戈角号博物馆货轮", "name_fr": "Navire musée Cap San Diego", "name_de": "Cap San Diego Museumsschiff"
    },
    # 18. Mahnmal St. Nikolai
    {
        "id": "h_18",
        "name": "St. Nikolai Memorial (Mahnmal St. Nikolai)（聖ニコライ教会廃墟記念碑）",
        "category": "Landmark", "rating": "★4.6", "locationZone": "city",
        "lat": 53.5475, "lng": 9.9906, "kids": True, "rain": True, "shopping": False, "free": False,
        "desc_en": "Haunting 1874 Neo-Gothic church ruins destroyed during 1943 WWII air raids, featuring a 147m spire, glass elevator, and underground anti-war museum.",
        "desc_ja": "1943年大空襲で破壊されたネオ・ゴシック教会の尖塔廃墟。高さ147mの塔内にシースルーガラスエレベーターと地下反戦歴史展示館を備える。",
        "desc_es": "Impresionantes ruinas de la iglesia neogótica destruida en la II Guerra Mundial con una torre de 147m y ascensor panorámico de cristal.",
        "desc_zh": "1943年二战空袭中被炸毁的新哥特式大教堂残留废墟。高达147米的黑褐色空心尖塔内装有观景玻璃电梯与地下反战展览。",
        "desc_fr": "Ruines impressionnantes de l'église néo-gothique détruite en 1943 avec sa flèche de 147m et son ascenseur panoramique.",
        "de": "Eindrucksvolle Kirchenruine von 1874 als Mahnmal für die Opfer des Weltkrieges mit 147m hohem Turm.",
        "tip_en": " Ride the glass elevator inside the hollowed spire up to the 76-meter open-air platform for a view directly over Speicherstadt and Rathaus!",
        "tip_ja": " 空洞化された黒い塔内部のシースルーガラスエレベーターで地上76m展望台へ！市庁舎と倉庫街を遮るものなく見下ろす展望が広がります。",
        "tip_es": " Sube en el ascensor de cristal por el interior de la torre hasta la plataforma a 76 metros de altura.",
        "tip_zh": " 搭乘中空尖塔内部的透明全景玻璃电梯升至76米观景台！直面俯瞰市府大楼与仓库城赤砖街区。",
        "tip_fr": " Montez dans l'ascenseur en verre à l'intérieur du clocher creux jusqu'à la plateforme à 76 mètres.",
        "tip_de": " Mit dem Glaskabinenaufzug im Inneren des hohlen Turms auf die 76m hohe Aussichtsplattform fahren.",
        "price_en": "Ruins Free (Elevator & Museum €6)", "price_ja": "廃墟無料（エレベーター＆博物館: 6ユーロ）", "price_es": "Ruinas gratis (Ascensor 6€)", "price_zh": "废墟免费（电梯与展馆6欧）", "price_fr": "Ruines gratuites (Ascenseur 6 €)", "price_de": "Ruine frei (Aussichtsturm 6 €)",
        "name_en": "St. Nikolai Memorial Spire", "name_ja": "St. Nikolai Memorial (Mahnmal St. Nikolai)（聖ニコライ教会廃墟記念碑）", "name_es": "Memorial de San Nicolás", "name_zh": "圣尼古拉教堂废墟纪念塔", "name_fr": "Mémorial Saint-Nicolas de Hambourg", "name_de": "Mahnmal St. Nikolai Hamburg"
    },
    # 19. Planten un Blomen
    {
        "id": "h_19",
        "name": "Planten un Blomen（プランテン・ウン・ブローメン公園）",
        "category": "Scenery & Walk", "rating": "★4.8", "locationZone": "city",
        "lat": 53.5606, "lng": 9.9819, "kids": True, "rain": False, "shopping": False, "free": True,
        "desc_en": "47-hectare central park featuring Europe's largest Japanese Garden, tea house, rose garden, tropical greenhouses, and summer evening illuminated water light concerts.",
        "desc_ja": "欧州最大級の日本庭園、茶室、バラ園、大温室を備える47ヘクタールの広大な中央公園。夏の夜の『光と水の噴水コンサート』が有名。",
        "desc_es": "Parque central de 47 hectáreas con el jardín japonés más grande de Europa, rosaleda y conciertos nocturnos de agua y luz en verano.",
        "desc_zh": "占地47公顷的中央绿洲。拥有全欧洲规模最大的日式庭园、茶室、玫瑰园与夏季夜晚著名的“光与水音乐喷泉秀”。",
        "desc_fr": "Grand parc de 47 hectares abritant le plus grand jardin japonais d'Europe, une roseraie et des spectacles d'eau et de lumière.",
        "de": "47 Hektar großer Park im Herzen Hamburgs mit dem größten Japanischen Garten Europas und den sommerlichen Wasserlichtkonzerten.",
        "tip_en": " Visit May to September at 10:00 PM (or 9:00 PM in spring) at the Parksee lake to watch the live-performed illuminated musical water-light fountain show for free!",
        "tip_ja": " 5月〜9月の夜22:00（春秋は21:00）に園内のParksee湖畔へ！オルガン奏者が生演奏する『光と水の音楽噴水ショー（Wasserlichtkonzerte）』が完全無料で観賞できます。",
        "tip_es": " Ven a las 22:00 h en verano al lago Parksee para ver el espectáculo gratuito de luces, agua y música en directo.",
        "tip_zh": " 推荐5月至9月夜间22点（春秋季21点）围观 Parksee 湖畔！现场免费观赏伴随风琴现场演奏的“水与光音乐喷泉秀”。",
        "tip_fr": " Venez à 22h en été au lac Parksee pour le spectacle gratuit de fontaines lumineuses en musique !",
        "tip_de": " Von Mai bis September um 22:00 Uhr am Parksee das kostenlose Wasserlichtkonzert mit Live-Musik genießen.",
        "price_en": "Free Access", "price_ja": "入園無料", "price_es": "Acceso libre", "price_zh": "免费入园", "price_fr": "Accès libre", "price_de": "Kostenlos",
        "name_en": "Planten un Blomen Park", "name_ja": "Planten un Blomen（プランテン・ウン・ブローメン公園）", "name_es": "Parque Planten un Blomen", "name_zh": "植物与花卉公园", "name_fr": "Parc Planten un Blomen", "name_de": "Planten un Blomen Hamburg"
    },
    # 21. Fischmarkt (Altona)
    {
        "id": "h_21",
        "name": "Fischmarkt (Altona)（アルトナの魚市場＆フィッシュオークションホール）",
        "category": "Shopping", "rating": "★4.6", "locationZone": "city",
        "lat": 53.5453, "lng": 9.9547, "kids": True, "rain": False, "shopping": True, "free": True,
        "desc_en": "Historic Sunday morning fish market operating since 1703 along the Elbe, famed for loud auctioneers, fresh seafood, live rock music, and beer.",
        "desc_ja": "1703年から続く日曜早朝限定の歴史的魚市場。大声で魚やフルーツを競り落とす威勢の良い商人、魚競売ホール（Fischauktionshalle）での生演奏ライブが名物。",
        "desc_es": "Mercado de pescado dominical histórico desde 1703 junto al Elba con subastadores ruidosos, marisco fresco y música en vivo.",
        "desc_zh": "始于1703年仅在周日清晨营业的百年鱼市。拍卖呼喊声不绝于耳，鱼拍卖大厅（Fischauktionshalle）内更有摇滚乐队现场演奏。",
        "desc_fr": "Marché aux poissons dominical historique depuis 1703 avec criée animée, fruits de mer et musique rock en direct.",
        "de": "Kult-Sonntagsmarkt seit 1703 am Elbufer mit Marktschreiern, frischem Fisch und Live-Musik in der Fischauktionshalle.",
        "tip_en": "⏰ Open ONLY Sunday mornings (5:00 AM – 9:30 AM in summer; 7:00 AM in winter)! Step inside the Fischauktionshalle to drink a beer and listen to live rock covers.",
        "tip_ja": "⏰ 毎週日曜日早朝（夏場5:00〜9:30、冬場7:00〜）限定開催！1907年建造の赤い魚競売ホール（Fischauktionshalle）内でモーニングビールを片手にロック生演奏を聞くのが至高。",
        "tip_es": "⏰ ¡Abierto SÓLO los domingos por la mañana! Entra en la sala Fischauktionshalle a tomar una cerveza con música en directo.",
        "tip_zh": "⏰ 仅于每周日清晨开放（夏季5:00-9:30；冬季7:00起）！步入红砖 Fischauktionshalle 大厅，喝一杯早晨啤酒听摇滚乐。",
        "tip_fr": "⏰ Ouvert UNIQUEMENT le dimanche matin ! Entrez dans la Fischauktionshalle pour boire une bière en écouteant du rock en direct.",
        "tip_de": "⏰ NUR sonntags morgens geöffnet! In der Fischauktionshalle ein morgendliches Bier trinken und der Live-Band lauschen.",
        "price_en": "Free Entry (Food €4–€10)", "price_ja": "入場無料（屋台4〜10ユーロ）", "price_es": "Entrada libre (Comida 4€–10€)", "price_zh": "免费参观（小吃4-10欧）", "price_fr": "Gratuit (Food 4 €–10 €)", "price_de": "Eintritt frei (Imbiss 4 €–10 €)",
        "name_en": "Altona Fish Market", "name_ja": "Fischmarkt (Altona)（アルトナの魚市場＆フィッシュオークションホール）", "name_es": "Mercado de Pescado de Altona", "name_zh": "阿尔托纳鱼市", "name_fr": "Marché aux poissons d'Altona", "name_de": "Altonaer Fischmarkt & Fischauktionshalle"
    },
    # 22. Reeperbahn & St. Pauli
    {
        "id": "h_22",
        "name": "Reeperbahn & St. Pauli（レーパーバーン＆ザンクト・パウリ地区）",
        "category": "Landmark", "rating": "★4.5", "locationZone": "city",
        "lat": 53.5497, "lng": 9.9625, "kids": False, "rain": False, "shopping": False, "free": True,
        "desc_en": "Hamburg's world-famous entertainment and red-light boulevard in St. Pauli, packed with music clubs, theaters, bars, and Beatles history.",
        "desc_ja": "『世界で最も罪深い1マイル』と称されるザンクト・パウリの繁華街。ライブハウス、劇場、バー、ビートルズゆかりの聖地が集結。",
        "desc_es": "El mundialmente famoso bulevar de ocio y zona roja de Hamburgo en St. Pauli con clubes de música, teatros y bares.",
        "desc_zh": "闻名遐迩的圣保利红灯区与夜生活娱乐大道。全长约1公里，布满了音乐俱乐部、剧院与摇滚传奇迹点。",
        "desc_fr": "Boulevard du divertissement et quartier rouge légendaire de Hambourg à St. Pauli avec ses salles de concert et bars.",
        "de": "Weltberühmte Vergnügungs- und Rotlichtmeile im Stadtteil St. Pauli mit Clubs, Theatern und Kneipen.",
        "tip_en": "📸 Walk to Beatles-Platz at the corner of Reeperbahn and Große Freiheit to photograph the stainless-steel silhouettes of the Fab Four on a vinyl record motif floor!",
        "tip_ja": "📸 レーパーバーンとGroße Freiheit通りの角にある『ビートルズ広場（Beatles-Platz）』へ！黒いレコード風の地面に浮かぶメンバー4人のステンレスシルエット像が名物です。",
        "tip_es": "📸 Acércate a la plaza Beatles-Platz para fotografiar las siluetas de acero inoxidable de los Fab Four sobre un vinilo.",
        "tip_zh": "📸 游览位于 Reeperbahn 转角处的披头士广场（Beatles-Platz）！在巨大黑胶唱片地面上打卡甲壳虫乐队四人的不锈钢剪影雕塑。",
        "tip_fr": "📸 Rendez-vous sur la Beatles-Platz pour photographier les silhouettes en acier inox des Beatles sur un vinyle géant.",
        "tip_de": "📸 Auf dem Beatles-Platz an der Großen Freiheit die Edelstahl-Silhouetten der Fab Four auf der Vinyl-Bodenplatte fotografieren.",
        "price_en": "Free Access", "price_ja": "散策無料", "price_es": "Acceso libre", "price_zh": "免费游览", "price_fr": "Accès libre", "price_de": "Kostenlos",
        "name_en": "Reeperbahn Nightlife District", "name_ja": "Reeperbahn & St. Pauli（レーパーバーン＆ザンクト・パウリ地区）", "name_es": "Reeperbahn y St. Pauli", "name_zh": "绳索街与圣保利街区", "name_fr": "Reeperbahn et St. Pauli", "name_de": "Reeperbahn & St. Pauli"
    },
    # 25. Alsterarkaden
    {
        "id": "h_25",
        "name": "Alsterarkaden（アルスター・アルケード）",
        "category": "Landmark", "rating": "★4.7", "locationZone": "city",
        "lat": 53.5511, "lng": 9.9922, "kids": True, "rain": True, "shopping": True, "free": True,
        "desc_en": "Venetian-style white vaulted arcade built in 1843 along the Kleine Alster canal, housing luxury boutiques, outdoor terrace cafes, and swans.",
        "desc_ja": "1843年建造のヴェネツィア風の白い連続アーチ回廊。クライネ・アルスター運河沿いに並び、高級ブティックと水辺のテラスカフェが美しく調和。",
        "desc_es": "Galería de arcos blancos de estilo veneciano construida en 1843 a lo largo del canal Kleine Alster con cafeterías.",
        "desc_zh": "建于1843年威尼斯拱廊风格的白色柱廊长廊。沿 Kleine Alster 运河延伸，设有一线精品店与水畔露天咖啡卡座。",
        "desc_fr": "Arcades blanches de style vénitien construites en 1843 le long du canal Kleine Alster avec terrasses de café.",
        "de": "Venedig-inspiriertes weißes Rundbogen-Ensemble von 1843 an der Kleinen Alster mit edlen Geschäften und Cafés.",
        "tip_en": "☕ Sit at an outdoor table along the canal to feed swans while enjoying coffee and cake looking straight across at Hamburg City Hall!",
        "tip_ja": "☕ 運河沿いのカフェテラス席へ！優雅に泳ぐ白鳥を眺めながら、対岸のハンブルク市庁舎の尖塔を望む贅沢なカフェタイムが過ごせます。",
        "tip_es": "☕ Siéntate en una mesa de terraza junto al canal para contemplar los cisnes con vistas al Ayuntamiento de Hamburgo.",
        "tip_zh": "☕ 选择沿运河的水畔露天桌面就座！一边观赏在水面游弋的优雅天鹅，一边隔水遥望对岸汉堡市政厅尖塔。",
        "tip_fr": "☕ S'installer en terrasse le long du canal pour admirer les cygnes avec vue sur l'Hôtel de Ville !",
        "tip_de": "☕ Auf der Terrasse am Fleet sitzen, die Alster-Schwäne beobachten und den Blick auf das Rathaus genießen.",
        "price_en": "Free Access", "price_ja": "散策無料", "price_es": "Acceso libre", "price_zh": "免费游览", "price_fr": "Accès libre", "price_de": "Kostenlos",
        "name_en": "Alster Arcades", "name_ja": "Alsterarkaden（アルスター・アルケード）", "name_es": "Arcadas del Alster", "name_zh": "阿尔斯特拱廊", "name_fr": "Arcades de l'Alster", "name_de": "Alsterarkaden Hamburg"
    },
    # 38. Fischbrötchen-Buden
    {
        "id": "h_38",
        "name": "Fischbrötchen-Buden an den Landungsbrücken（桟橋のフィッシュブレートヒェン屋台群）",
        "category": "Café & Bistro", "rating": "★4.6", "locationZone": "city",
        "lat": 53.5458, "lng": 9.9675, "kids": True, "rain": False, "shopping": False, "free": False,
        "desc_en": "Iconic waterfront kiosks along the Landungsbrücken piers serving Hamburg's essential street food: crispy rolls packed with pickled Bismarck herring, smoked salmon, or North Sea shrimp.",
        "desc_ja": "ザンクト・パウリ桟橋沿いに並ぶハンブルクの定番ソウルフード屋台。酢漬けニシン（Bismarckherring）や北海小エビを挟んだパンサンド（Fischbrötchen）の専門店。",
        "desc_es": "Puestos en el muelle de Landungsbrücken que sirven el bocadillo de pescado (Fischbrötchen) con arenque, salmón o gambas.",
        "desc_zh": "沿 St. Pauli 码头长廊分布的当地街头小吃档。主打夹入腌渍鲱鱼（Bismarckhering）、烟熏三文鱼或北海小虾的鲜鱼面包汉堡（Fischbrötchen）。",
        "desc_fr": "Kiosques sur les embarcadères servant le sandwich au poisson (Fischbrötchen) au hareng, saumon ou crevettes.",
        "de": "Kult-Imbissbuden an den Landungsbrücken für den echten Hamburger Fischbrötchen-Genuss mit Bismarckhering oder Krabben.",
        "tip_en": "🍽️ Order 'Bismarckhering-Brötchen mit Zwiebeln' (pickled herring roll with onions) at Brücke 10 for the freshest catch directly overlooking the harbor traffic!",
        "tip_ja": "🍽️ 10番桟橋前にある有名店『Brücke 10』で『Bismarckhering-Brötchen（酢漬けニシンサンド・玉ねぎ添え）』を注文！港を行き交う大船を眺めながら食べるのが地元の流儀。",
        "tip_es": "🍽️ Pide un 'Bismarckhering-Brötchen' (bocadillo de arenque con cebolla) en el puesto Brücke 10 frente al puerto.",
        "tip_zh": "🍽️ 推荐在10号码头的著名小档 Brücke 10 点一份“Bismarckhering-Brötchen”（洋葱酸鲱鱼鲜包，约4.50欧）！",
        "tip_fr": "🍽️ Commandez un 'Bismarckhering-Brötchen' (sandwich au hareng avec oignons) au stand Brücke 10 !",
        "tip_de": "🍽️ An Brücke 10 ein frisches Bismarckhering-Brötchen mit Zwiebeln bestellen und den Hafenblick genießen!",
        "price_en": "Fischbrötchen: €4.50–€7.50", "price_ja": "魚パンサンド: 4.50〜7.50ユーロ", "price_es": "Bocadillo de pescado: 4,50€–7,50€", "price_zh": "鲜鱼面包：4.50-7.50欧", "price_fr": "Sandwich poisson : 4,50 €–7,50 €", "price_de": "Fischbrötchen: 4,50 €–7.50 €",
        "name_en": "St. Pauli Fish Roll Kiosks", "name_ja": "Fischbrötchen-Buden an den Landungsbrücken（桟橋のフィッシュブレートヒェン屋台群）", "name_es": "Puestos de Fischbrötchen en Landungsbrücken", "name_zh": "圣保利码头鲜鱼面包档", "name_fr": "Kiosques à Fischbrötchen de Landungsbrücken", "name_de": "Fischbrötchen-Buden an den Landungsbrücken"
    },
    # 39. Old Commercial Room
    {
        "id": "h_39",
        "name": "Old Commercial Room（オールド・コマーシャル・ルーム）",
        "category": "Café & Bistro", "rating": "★4.6", "locationZone": "city",
        "lat": 53.5481, "lng": 9.9794, "kids": True, "rain": True, "shopping": False, "free": False,
        "desc_en": "Historic 1795 maritime restaurant opposite St. Michaelis church famous for serving authentic Hamburg Labskaus (salted corned beef stewed with beets, topped with fried egg and herring).",
        "desc_ja": "聖ミヒャエリス教会向かいにある1795年創業の老舗船員レストラン。ハンブルクの伝統郷土料理『ラブスカウス（Labskaus）』の元祖名店。",
        "desc_es": "Restaurante marítimo histórico de 1795 frente a la iglesia de San Miguel famoso por servir el genuino Labskaus de Hamburgo.",
        "desc_zh": "面向圣米歇尔教堂始于1795年的古老水手餐厅。以提供最纯正地道的汉堡百年水手水煮牛肉泥特产“Labskaus”著称。",
        "desc_fr": "Restaurant maritime historique de 1795 face à l'église Saint-Michel célèbre pour son authentique Labskaus.",
        "de": "Historisches Gastspielhaus von 1795 gegenüber dem Michel, weltberühmt für seinen echten Hamburger Labskaus.",
        "tip_en": "🍽️ Order the signature 'Original Hamburger Labskaus' served with a fried egg, pickled gherkin, and rollmops herring—a traditional sailors' dish packed with rich flavor!",
        "tip_ja": "🍽️ 名物『Original Hamburger Labskaus』を注文！コンビーフとビーツの煮込みに目玉焼き、ピクルス、酢漬けニシンが乗った航海士伝承の滋味深い味です。",
        "tip_es": "🍽️ Pide el 'Original Hamburger Labskaus' servido con huevo frito, pepinillo y arenque empacado.",
        "tip_zh": "🍽️ 必点镇店招牌“Original Hamburger Labskaus”（配煎蛋、酸黄瓜与鲱鱼卷，约24欧）！感受大航海时代水手的美食遗产。",
        "tip_fr": "🍽️ Commandez l'authentique 'Original Hamburger Labskaus' servi avec un œuf au plat et un rollmops !",
        "tip_de": "🍽️ Den 'Original Hamburger Labskaus' mit Spiegelei, Gewürzgurke und Rollmops bestellen!",
        "price_en": "Labskaus: €22–€26", "price_ja": "ラブスカウス: 22〜26ユーロ", "price_es": "Labskaus: 22€–26€", "price_zh": "牛肉泥餐：22-26欧", "price_fr": "Labskaus : 22 €–26 €", "price_de": "Labskaus: 22 €–26 €",
        "name_en": "Old Commercial Room Restaurant", "name_ja": "Old Commercial Room（オールド・コマーシャル・ルーム）", "name_es": "Restaurante Old Commercial Room", "name_zh": "老商务间水手餐厅", "name_fr": "Restaurant Old Commercial Room", "name_de": "Old Commercial Room Hamburg"
    },
    # 48. HADAG-Hafenfähren Linie 62
    {
        "id": "h_48",
        "name": "HADAG-Hafenfähren (Linie 62)（HADAG港湾定期フェリー62番線）",
        "category": "Scenery & Walk", "rating": "★4.8", "locationZone": "city",
        "lat": 53.5458, "lng": 9.9669, "kids": True, "rain": False, "shopping": False, "free": False,
        "desc_en": "Public transport ferry running from Landungsbrücken Pier 3 to Finkenwerder, offering a scenic 1-hour round-trip cruise past container cranes and Övelgönne beach.",
        "desc_ja": "第3桟橋からフィンケンヴェルダーへ向かう公共定期フェリー。通常の一日乗車券で乗車でき、巨大コンテナ船や砂浜の横を巡る人気の水上ルート。",
        "desc_es": "Ferri de transporte público que va del Muelle 3 a Finkenwerder ofreciendo un crucero panorámico con billete normal.",
        "desc_zh": "从 St. Pauli 3号码头通往 Finkenwerder 的水上公共巴士。使用常规交通车票即可享受沿途经过巨大吊车与水岸的1小时景观游船。",
        "desc_fr": "Ferry de transport public reliant le ponton 3 à Finkenwerder pour un circuit panoramique au tarif classique.",
        "de": "Linienfähre von Brücke 3 nach Finkenwerder – die günstigste Hafenrundfahrt mit dem normalen HVV-Fahrschein.",
        "tip_en": "📸 Grab a seat on the open-air upper deck to photograph towering container cranes up close as the ferry cruises past the Neumühlen terminal!",
        "tip_ja": "📸 2階のオープンエアデッキ席を確保！ノイミューレンターミナル付近を通過する際、見上げるような超巨大キリンキリン（コンテナクレーン）の圧巻写真を撮影できます。",
        "tip_es": "📸 Consigue sitio en la cubierta superior abierta para fotografiar las grúas de contenedores gigantes de cerca.",
        "tip_zh": "📸 抢占顶层露天甲板看台！在渡轮经过 Neumühlen 集装箱码头时，近距离仰拍耸立云霄的超级机械龙门吊。",
        "tip_fr": "📸 Installez-vous sur le pont supérieur découvert pour photographier les grues géantes de près.",
        "tip_de": "📸 Einen Platz auf dem Freideck oben sichern, um die riesigen Containerbrücken aus nächster Nähe zu fotografieren.",
        "price_en": "HVV Ticket Valid (€3.80)", "price_ja": "HVV共通乗車券適用（3.80ユーロ）", "price_es": "Billete HVV válido (3,80€)", "price_zh": "HVV通用车票适用（3.80欧）", "price_fr": "Ticket HVV valable (3,80 €)", "price_de": "HVV-Fahrkarte gültig (3,80 €)",
        "name_en": "HADAG Harbor Ferry 62", "name_ja": "HADAG-Hafenfähren (Linie 62)（HADAG港湾定期フェリー62番線）", "name_es": "Ferri del Puerto HADAG 62", "name_zh": "HADAG 62号港湾渡轮", "name_fr": "Ferry du port HADAG 62", "name_de": "HADAG-Hafenfähre Linie 62"
    },
    # 50. Lübeck Altstadt & Holstentor (Suburban)
    {
        "id": "h_50",
        "name": "Lübeck: Altstadt & Holstentor (UNESCO)（リューベック：世界遺産旧市街＆ホルステン門）",
        "category": "Landmark", "rating": "★4.9", "locationZone": "suburban",
        "lat": 53.8664, "lng": 10.6797, "kids": True, "rain": True, "shopping": False, "free": True,
        "desc_en": "UNESCO World Heritage 'Queen of the Hanseatic League' 45 min from Hamburg, famous for its 1477 twin-towered red-brick Holstentor gate and Niederegger marzipan.",
        "desc_ja": "ハンブルクから列車で45分。『ハンザ同盟の女王』と称される世界遺産都市。1477年建造の2つの尖塔を持つ赤レンガのホルステン門（Holstentor）とマジパン（Marzipan）が象徴。",
        "desc_es": "Ciudad patrimonio UNESCO 'Reina de la Liga Hanseática' a 45 min de Hamburgo con la famosa puerta de ladrillo Holstentor de 1477.",
        "desc_zh": "距离汉堡45分钟车程的世界遗产名城，被称为“汉萨同盟之女王”。拥建于1477年双塔红砖 Holstentor 城门与 Niederegger 杏仁糖（Marzipan）。",
        "desc_fr": "Reine de la Ligue Hanséatique (UNESCO) à 45 min de Hambourg avec la porte médiévale Holstentor de 1477 et le massepain.",
        "de": "UNESCO-Welterbe-Stadt 'Königin der Hanse' mit dem weltberühmten Holstentor von 1477 und Niederegger Marzipan.",
        "tip_en": "🍽️ Visit Café Niederegger opposite the Town Hall to taste authentic Lübeck Marzipan walnut cake and buy chocolate-covered marzipan treats in the 2nd floor museum shop!",
        "tip_ja": "🍽️ 市庁舎前の老舗『Café Niederegger』へ！2階のマジパン博物館を見学後、伝統のアーモンド菓子マジパン入りのくるみケーキ（Marzipantorte）を味わうのが王道です。",
        "tip_es": "🍽️ Visita el Café Niederegger frente al Ayuntamiento para probar la tarta de mazapán y comprar mazapán cubierto de chocolate.",
        "tip_zh": "🍽️ 前往市政厅正对面的老字号 Café Niederegger！观赏2楼杏仁糖博物馆并现场品尝传统的核桃杏仁糖蛋糕（Marzipantorte）。",
        "tip_fr": "🍽️ Visitez le Café Niederegger en face de l'Hôtel de Ville pour déguster le gâteau au massepain traditionnel !",
        "tip_de": "🍽️ ins Café Niederegger gegenüber dem Rathaus gehen, das Marzipan-Museum im 2. Stock besuchen und Marzipantorte probieren!",
        "price_en": "Town Free (Holstentor €8)", "price_ja": "旧市街散策無料（ホルステン門内部: 8ユーロ）", "price_es": "Ciudad gratis (Holstentor 8€)", "price_zh": "古城免费（城门内部8欧）", "price_fr": "Ville gratuite (Holstentor 8 €)", "price_de": "Altstadt frei (Holstentor 8 €)",
        "name_en": "Lübeck Old Town & Holsten Gate", "name_ja": "Lübeck: Altstadt & Holstentor (UNESCO)（リューベック：世界遺産旧市街＆ホルステン門）", "name_es": "Casco Antiguo de Lübeck y Holstentor", "name_zh": "吕贝克古城与荷尔斯登门", "name_fr": "Vieille ville de Lübeck et Holstentor", "name_de": "Lübeck: Altstadt & Holstentor (UNESCO)"
    },
    # 52. Schloss Schwerin (Suburban)
    {
        "id": "h_52",
        "name": "Schloss Schwerin（シュヴェリーン城）",
        "category": "Landmark", "rating": "★4.9", "locationZone": "suburban",
        "lat": 53.6242, "lng": 11.4189, "kids": True, "rain": True, "shopping": False, "free": False,
        "desc_en": "Fairytale island palace in Lake Schwerin featuring 653 rooms, golden domes, and romantic French Orangery gardens, dubbed the 'Neuschwanstein of the North'.",
        "desc_ja": "シュヴェリーン湖の島に浮かぶ『北のノイシュヴァンシュタイン城』と称されるおとぎ話のような歴史主義宮殿。金のドーム屋根とオランジェリー庭園が美しい。",
        "desc_es": "Palacio de ensueño en una isla del lago Schwerin con 653 habitaciones, cúpulas doradas y jardines románticos.",
        "desc_zh": "屹立于什韦林湖岛之上的童话水上宫殿，誉为“北方的新天鹅堡”。拥有653间房间、金光闪闪的圆顶与法式宫廷花园。",
        "desc_fr": "Château féerique situé sur une île du lac de Schwerin avec ses dômes dorés et jardins à la française.",
        "de": "Märchenhaftes Residenzschloss auf einer Insel im Schweriner See mit goldenen Kuppeln und Barockgarten.",
        "tip_en": "📸 Walk across the castle bridge into the Orangery garden (Orangeriegarten) to capture the golden main dome reflected over Lake Schwerin!",
        "tip_ja": "📸 城の橋を渡って裏手のオランジェリー庭園（Orangeriegarten）へ！湖越しに黄金の主ドームといくつもの塔が水面に浮かぶ絵はがきビューが撮れます。",
        "tip_es": "📸 Camina por el puente hacia los jardines de la Orangerie para fotografiar la cúpula dorada reflejada en el lago.",
        "tip_zh": "📸 穿过城堡拱桥步入 Orangeriegarten 橘园花圃！以波光粼粼的湖水为前景，拍摄主金顶倒映水面的大景。",
        "tip_fr": "📸 Traversez le pont vers les jardins de l'Orangerie pour photographier le dôme doré se reflétant dans le lac.",
        "tip_de": "📸 Über die Schlossbrücke in den Orangeriegarten gehen für das perfekte Foto der goldenen Kuppel über dem See.",
        "price_en": "Palace: €8.50 (Gardens Free)", "price_ja": "宮殿: 8.50ユーロ（庭園無料）", "price_es": "Palacio: 8,50€ (Jardines gratis)", "price_zh": "宫殿：8.50 欧元（花园免费）", "price_fr": "Palais : 8,50 € (Jardins gratuits)", "price_de": "Schloss: 8,50 € (Garten frei)",
        "name_en": "Schwerin Castle", "name_ja": "Schloss Schwerin（シュヴェリーン城）", "name_es": "Castillo de Schwerin", "name_zh": "什韦林城堡", "name_fr": "Château de Schwerin", "name_de": "Schloss Schwerin"
    },
    # 61. Designer Outlet Neumünster (Suburban)
    {
        "id": "h_61",
        "name": "Designer Outlet Neumünster / Soltau（デザイナー・アウトレット・ノイミュンスター / ソルタウ）",
        "category": "Shopping", "rating": "★4.6", "locationZone": "suburban",
        "lat": 54.0539, "lng": 9.9472, "kids": True, "rain": True, "shopping": True, "free": True,
        "desc_en": "Northern Germany's largest luxury outlet village featuring 120+ designer fashion boutiques with 30–70% discounts and traditional regional architecture.",
        "desc_ja": "北ドイツ最大規模の高級アウトレットモール。120以上の人気ハイブランドが30〜70%オフで並ぶオープンエアショッピングビレッジ。",
        "desc_es": "El pueblo de compras de outlet de lujo más grande del norte de Alemania con más de 120 boutiques de diseñadores.",
        "desc_zh": "北德规模最大的名品奥特莱斯购物村。拥有120余家国际高档时装品牌，全年提供三至七折震撼优惠。",
        "desc_fr": "Le plus grand village outlet de luxe du nord de l'Allemagne avec plus de 120 boutiques de marque.",
        "de": "Norddeutschlands größtes Designer-Outlet-Village mit über 120 Markenboutiquen und 30–70% Rabatt.",
        "tip_en": "🚌 Take the direct shuttle bus or regional RE7 train from Hamburg Hauptbahnhof to Neumünster, then take line 7/77 directly to the main entrance!",
        "tip_ja": "🚌 ハンブルク中央駅からRE7号線でノイミュンスター駅へ行き、駅前から7/77番バスで直行！インフォメーションデスクでパスポートを提示すると追加10%オフクーポンが貰えます。",
        "tip_es": "🚌 Toma el tren regional RE7 desde la estación de Hamburgo hasta Neumünster y luego el autobús 7/77 al outlet.",
        "tip_zh": "🚌 在汉堡中央车站搭乘 RE7 区域列车至 Neumünster 站，换乘 7/77号公交车直达！凭外籍护照可去客服中心领取9折折上折优惠券。",
        "tip_fr": "🚌 Prenez le train régional RE7 depuis la gare de Hambourg puis le bus 7/77 vers l'entrée principale du centre !",
        "tip_de": "🚌 Mit dem RE7 vom Hauptbahnhof bis Neumünster fahren und mit der Buslinie 7/77 direkt vor den Haupteingang fahren.",
        "price_en": "Free Entry (Shopping)", "price_ja": "入館無料（ショッピング）", "price_es": "Entrada libre (Compras)", "price_zh": "免费入场（购物）", "price_fr": "Entrée libre", "price_de": "Freier Eintritt",
        "name_en": "Neumünster Designer Outlet", "name_ja": "Designer Outlet Neumünster / Soltau（デザイナー・アウトレット・ノイミュンスター / ソルタウ）", "name_es": "Outlet Designer Outlet Neumünster", "name_zh": "诺伊明斯特设计师奥特莱斯", "name_fr": "Designer Outlet Neumünster", "name_de": "Designer Outlet Neumünster"
    }
]

# Write to data/cities/hamburg.json
fpath = "data/cities/hamburg.json"
data = {
    "cityName": "Hamburg, Germany",
    "spots": hamburg_spots
}

with open(fpath, 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print(f"🎉 Successfully created {len(hamburg_spots)} spots in data/cities/hamburg.json")
