import json, os, re

# Master script to convert Benelux 5-city spot data to Master Rulebook v6.0.0 JSON schema

brussels_raw = [
    ("b_1", "Grand-Place / Grote Markt", "Grand-Place（グランプラス / 世界遺産）", "Landmark", "★4.8", "city", 50.8467, 4.3525, False, True, False, True,
     "The central square of Brussels and a UNESCO World Heritage site, famous for its opulent 17th-century Baroque Guildhalls with gold leaf facades, the towering Gothic Town Hall, and the King's House.",
     "17世紀のバロック様式同業組合（ギルドハウス）館群とゴシック様式の市庁舎が囲む、ユネスコ世界遺産のヨーロッパで最も美しい大広場。",
     "📸 昼間の金箔装飾の鑑賞に加え、日没後のライトアップされた幻想的な夜景の再訪がおすすめ。",
     "📸 Visit once during bright midday daylight and return after dusk when dynamic lighting illuminates the gold filigree.",
     "広場散策無料", "Free Entry"),
    
    ("b_2", "Manneken Pis", "Manneken Pis（小便小僧ジュリアン君）", "Landmark", "★4.3", "city", 50.8450, 4.3499, False, False, False, True,
     "A 61-centimeter bronze fountain sculpture of a urinating boy dating back to 1619 by Jérôme Duquesnoy the Elder. A quirky national symbol of Brussels.",
     "1619年にジェローム・デュケノワにより制作されたブロンズ像。愛称「ジュリアン君」として世界中で愛されるブリュッセルのシンボル。",
     "👕 年間130回以上衣装替えを行うため柵掲示のスケジュールを要確認。混雑前の早朝の見学がおすすめ。",
     "👕 Check the official dressing schedule posted on the railing; the statue is dressed in custom costumes over 130 times a year.",
     "見学無料", "Free Entry"),

    ("b_3", "Atomium", "Atomium（アトミウム / 1958年万博シンボル）", "Landmark", "★4.6", "city", 50.8947, 4.3414, True, True, False, False,
     "A 102-meter-tall structure built for the 1958 Brussels World's Fair, representing an iron crystal cell magnified 165 billion times with panoramic observation spheres.",
     "1958年ブリュッセル万博のために建設された高さ102mの鉄結晶構造体。球体内部のエスカレーターと最上階360度展望台が人気。",
     "🎟️ オンライン事前予約が必須。最上階のパノラマ展望台見学チケットで隣接の「デザインミュージアム」も入場可能。",
     "🎟️ Pre-booking online time-slot tickets is essential. Admission also grants free entry to the adjacent Design Museum Brussels.",
     "料金: €16.00", "Entry: €16.00"),

    ("b_4", "Koninklijke Musea voor Schone Kunsten", "Koninklijke Musea voor Schone Kunsten（ベルギー王立美術館）", "Museum & Gallery", "★4.7", "city", 50.8427, 4.3577, False, True, False, False,
     "World-class museum complex comprising the Old Masters Museum (Bruegel, Rubens, Van Dyck), Fin-de-Siècle Museum, and dedicated Magritte Museum.",
     "ブリューゲル（父）の『反逆天使の墜落』ほかルーベンス、ヴァン・ダイク等の古典絵画からマグリット展までを擁する世界最高峰の美術館。",
     "🎨 古典絵画館はブリューゲルの世界最大級のコレクションを誇る。マルチメディアガイドのレンタルが便利。",
     "🎨 Houses the world's largest collection of paintings by Pieter Bruegel the Elder; rent the interactive audio guide.",
     "料金: €15.00（コンビ券）", "Entry: €15.00"),

    ("b_5", "Musée Magritte Museum", "Musée Magritte Museum（マグリット美術館）", "Museum & Gallery", "★4.8", "city", 50.8423, 4.3574, False, True, False, False,
     "Dedicated entirely to Belgian surrealist master René Magritte, housing over 200 original paintings, gouaches, and painted objects.",
     "シュルレアリスムの巨匠ルネ・マグリットの『光の帝国』『イメージの裏切り』など200点以上の作品を収蔵する専門美術館。",
     "🎟️ 午前中の時間指定枠を事前予約。フラッシュなし撮影可能。最上階から年代順に鑑賞するのがおすすめ。",
     "🎟️ Reserve your morning time slot in advance. Photography without flash is allowed; start from the top floor down.",
     "料金: €10.00", "Entry: €10.00"),

    ("b_6", "Cathédrale Saints-Michel-et-Gudule", "Cathédrale Saints-Michel-et-Gudule（サン・ミッシェル大聖堂）", "Landmark", "★4.7", "city", 50.8478, 4.3601, False, True, False, True,
     "Brabantine Gothic cathedral dating from 11th to 15th centuries with twin 64m towers, Renaissance stained glass, and royal wedding history.",
     "11世紀〜15世紀建設のブラバント・ゴシック様式の大聖堂。双塔の石造タワーとステンドグラス、彫刻説教壇が美しいベルギー王室ゆかりの地。",
     "👑 聖堂内の散策は無料。地下の11世紀ロマネスク様式の遺構・クリプト（地下聖堂）の見学は有料。",
     "👑 Admission to the main nave is completely free; pay a small fee to explore the 11th-century Romanesque crypt below.",
     "聖堂無料 / 地下クリプト: €3.00", "Nave Free / Crypt: €3.00"),

    ("b_7", "Galeries Royales Saint-Hubert", "Galeries Royales Saint-Hubert（ギャルリー・サンチュベール）", "Shopping", "★4.7", "city", 50.8469, 4.3546, False, True, True, True,
     "1847 Italian Renaissance-style glass-vaulted arcade housing luxury chocolatiers (Neuhaus, Pierre Marcolini, Mary), bookshops, and cafes.",
     "1847年完成のヨーロッパ最古級ガラスアーケード。ノイハウスやピエール・マルコリーニなど王室御用達ショコラティエの本店が集結。",
     "🍫 プラリネ発祥の地ノイハウス（Neuhaus）本店でのチョコ試食＆買い出しが定番。全天候型の散策スポット。",
     "🍫 The ultimate destination for luxury Belgian chocolate tasting; visit flagship boutiques of Neuhaus and Marcolini.",
     "散策無料（チョコ予算: €5〜€20）", "Free (Chocolate ~€5-20)"),

    ("b_8", "Mini-Europe", "Mini-Europe（ミニ・ヨーロッパ）", "Landmark", "★4.6", "suburban", 50.8940, 4.3387, True, False, False, False,
     "Open-air miniature park located beside Atomium, showcasing 1:25 scale working replicas of over 350 famous EU architectural monuments.",
     "アトミウム横に位置し、ビッグベンやエッフェル塔など欧州主要350以上の名所を1/25スケールで精巧に再現したミニチュアパーク。",
     "🌋 ボタンを押すと新幹線タリスが走りベスビオ火山が噴火する体験仕掛け。アトミウムとの共通割引券がお得。",
     "🌋 Interactive buttons activate moving trains and erupting volcanoes. Buy a combined Atomium + Mini-Europe ticket.",
     "料金: €19.00（アトミウム共通約€31.00）", "Entry: €19.00 (Combo ~€31.00)"),

    ("b_9", "Koninklijk Paleis van Brussel", "Koninklijk Paleis van Brussel（ブリュッセル王宮）", "Landmark", "★4.6", "city", 50.8417, 4.3631, False, True, False, True,
     "Official administrative palace of the King of the Belgians featuring Louis XVI neoclassical facade and Jan Fabre's jewel-beetle wing ceiling.",
     "ブリュッセル公園前に聳えるベルギー王室の現役執務宮殿。鏡の間に施されたタマムシの羽160万枚の天井装飾アートが有名。",
     "👑 毎年「夏季（7月下旬〜8月下旬）」のみ内部が無料一般公開される。豪華な大広間を散策可能。",
     "👑 The palace is open for free public visits only during summer (late July to late August).",
     "広場散策無料（夏季特別公開時内部無料）", "Free (Summer Interior Free)"),

    ("b_10", "Parc de Bruxelles", "Parc de Bruxelles（ブリュッセル公園）", "Scenery & Walk", "★4.6", "city", 50.8444, 4.3639, False, False, False, True,
     "Largest public neoclassical park in central Brussels laid out between the Royal Palace and Belgian Parliament.",
     "王宮とベルギー連邦議会に挟まれた、幾何学模様の噴水や彫刻が美しい市内最大の新古典主義様式の市民公園。",
     "☕ 園内のキオスクカフェ「Kiosque Royale」でベルギーワッフルやクラフトビールを飲みながら木陰で休憩。",
     "☕ A favorite shaded retreat for locals; stop by open-air kiosk cafes for craft beers and Belgian waffles.",
     "入園無料", "Free Entry"),

    ("b_11", "Mont des Arts / Kunstberg", "Mont des Arts（芸術の丘）", "Scenery & Walk", "★4.8", "city", 50.8439, 4.3564, False, False, False, True,
     "Elevated urban vantage point and public garden linking Upper and Lower Towns, framing the Gothic spire of the Town Hall.",
     "市庁舎の尖塔を背景に幾何学模様の花壇と彫刻が広がる展望スポット。夕暮れ時から夜景へのタイムラプス撮影が人気。",
     "📸 大階段の上からのパノラマビューはアムステルダム・ブリュッセル観光屈指の絵はがきフォトスポット。",
     "📸 The steps at the top of the garden offer the classic postcard panorama of Brussels' skyline framing the Town Hall spire.",
     "見学無料", "Free Entry"),

    ("b_12", "Musée des Instruments de Musique", "Musée des Instruments de Musique（楽器博物館 / MIM）", "Museum & Gallery", "★4.6", "city", 50.8428, 5.3589, False, True, False, False,
     "Housed inside the 1899 Art Nouveau 'Old England' building, displaying 1,200 historic musical instruments with wireless audio headphones.",
     "1899年建設のアール・ヌーヴォー建築「オールド・イングランド」内に世界の歴史的楽器1,200点を展示。音声ガイドで音色が響く。",
     "🎺 ヘッドフォンを装着して展示ケースに近づくと自動でその古楽器の演奏が流れる。10階最上階テラスカフェの眺望も素晴らしい。",
     "🎺 Put on audio headphones to hear antique instruments automatically; visit the 10th-floor rooftop brasserie for skyline views.",
     "料金: €15.00", "Entry: €15.00"),

    ("b_13", "Belgisch Stripcentrum", "Belgisch Stripcentrum（ベルギー漫画センター）", "Museum & Gallery", "★4.5", "city", 50.8503, 4.3599, True, True, False, False,
     "Located in a 1906 Victor Horta Art Nouveau warehouse, celebrating Tintin, The Smurfs, Lucky Luke, and Belgian comic heritage.",
     "ビクトル・オルタ設計の1906年アール・ヌーヴォー建築内にある『タンタンの冒険』『スマーフ』等の漫画（第9の芸術）博物館。",
     "📚 1階のショップで多言語版のマンガや限定フィギュアが購入可能。街中のマンガ壁画巡りとの組み合わせが人気。",
     "📚 Browse the massive comic bookstore on the ground floor for multilingual editions; pair with the city's Comic Book Route.",
     "料金: €13.00", "Entry: €13.00"),

    ("b_14", "Striproute Brussel", "Striproute Brussel（マンガ壁画ルート）", "Scenery & Walk", "★4.6", "city", 50.8456, 4.3496, True, False, False, True,
     "Open-air trail of over 60 massive street murals painted on building facades throughout Brussels celebrating comic characters.",
     "建物の壁面60箇所以上に描かれた『タンタン』や『スマーフ』などの巨大ストリートアートを巡るオープンエアの散策ルート。",
     "🚶 ジュリアン君のすぐ近くにある「タンタンとハドック船長」の壁画が最も有名。観光案内所で壁画マップを入手可能。",
     "🚶 The famous Tintin & Captain Haddock mural is located near Manneken Pis; pick up a map at the tourist desk.",
     "散策無料", "Free Walk"),

    ("b_15", "Musée Horta", "Musée Horta（オルタ美術館 / ユネスコ）", "Museum & Gallery", "★4.7", "city", 50.8242, 4.3556, False, True, False, False,
     "UNESCO-listed private home and studio of pioneer Art Nouveau architect Victor Horta (1898-1901) featuring curved ironwork and stained glass.",
     "アール・ヌーヴォーの先駆者ビクトル・オルタの自邸兼工房（1898年）。曲線の流木・鉄ナシ装飾と光が降り注ぐ階段井戸が美しい世界遺産。",
     "🎟️ 完全事前オンライン予約制（時間枠限定）。館内は荷物・写真撮影が厳重管理。靴カバーを着用して見学。",
     "🎟️ Advance online booking is mandatory with limited hourly admissions; large bags and photography are regulated.",
     "料金: €12.00", "Entry: €12.00"),

    ("b_16", "Koninklijk Museum van het Leger", "Koninklijk Museum van het Leger（王立軍事歴史博物館）", "Museum & Gallery", "★4.6", "city", 50.8411, 4.3931, True, True, False, False,
     "Located in Cinquantenaire park, featuring vast halls of medieval armor, Napoleonic uniforms, and a massive Aviation Hall with real aircraft.",
     "サンカン特有公園内に位置し、中世の甲冑・ナポレオン時代の軍服から巨大展示ホールに並ぶ数十機の歴史的軍用機までを収蔵。",
     "✈️ 航空展示ホールの通路を通り、サンカン特有公園の巨大「勝利のアーチ」屋上展望台へ登ることができる。",
     "✈️ Walk through the Aviation Hall walkways to access the top of the Cinquantenaire Triumphal Arch for elevated views.",
     "料金: €11.00", "Entry: €11.00"),

    ("b_17", "Autoworld Brussels", "Autoworld Brussels（オートワールド）", "Museum & Gallery", "★4.6", "city", 50.8394, 4.3928, True, True, False, False,
     "Housed inside Jubelpark's monumental 1880 hall, exhibiting over 300 historic vintage cars, royal vehicles, microcars, and racing legends.",
     "サンカン特有公園のガラス殿堂内にある自動車博物館。19世紀の馬車からクラシックカー、王室用車、F1レースカーまで300台以上展示。",
     "🏎️ 雨の日のファミリー観光に最適。子供向けのレトロカー試乗体験コーナーやドライビングシミュレーターも併設。",
     "🏎️ Great family and rainy-day stop; explore interactive zones where children can test driving simulation games.",
     "料金: €15.00", "Entry: €15.00"),

    ("b_18", "Parc du Cinquantenaire / Jubelpark", "Parc du Cinquantenaire（サンカン特有公園＆勝利のアーチ）", "Scenery & Walk", "★4.7", "city", 50.8406, 4.3883, False, False, False, True,
     "30-hectare public park built in 1880 to commemorate Belgian independence, dominated by a monumental stone Triumphal Arch and gardens.",
     "ベルギー独立50周年を記念して1880年に完成した30ヘクタールの広大な公園。中央に聳える三連の「勝利のアーチ」がシンボル。",
     "📸 花壇の前から夕方にアーチを正面撮影するのがベスト。夏は地元民がテイクアウトフリッツとビールを楽しんで賑わう。",
     "📸 Photograph the grand arch from the central flowerbeds; during summer afternoons locals gather on the lawns.",
     "入園無料", "Free Entry"),

    ("b_19", "Europees Parlement & Parlamentarium", "Europees Parlement & Parlamentarium（欧州議会＆パルラメンタリウム）", "Museum & Gallery", "★4.7", "city", 50.8384, 4.3725, False, True, False, True,
     "Legislative hub of the European Union. Parlamentarium offers dynamic 360-degree digital interactive exhibitions on EU history and policy.",
     "EU統合の歴史と意思決定を体感できるビジターセンター。全24のEU公式言語対応のマルチメディアガイドが無料貸出。",
     "🇪🇺 入場・マルチメディアガイド・本会議場（Hemicycle）見学が全て完全無料（※セキュリティ用にパスポート要持参）。",
     "🇪🇺 Entry to the Parlamentarium and the Hemicycle is 100% free with guides in all 24 EU languages (bring passport/ID).",
     "入場無料（パスポート要掲示）", "Free Entry (Passport Required)"),

    ("b_20", "Huis van de Europese Geschiedenis", "Huis van de Europese Geschiedenis（欧州歴史の家）", "Museum & Gallery", "★4.6", "city", 50.8403, 4.3761, False, True, False, False,
     "Located in a restored 1930s hospital in Leopold Park, exploring the shared memory, conflicts, and integration of Europe.",
     "レオポルド公園内に位置し、欧州大陸の歴史・戦争・民主主義の歩みを先進的なデジタルタブレットで解説する歴史博物館。",
     "📱 入場無料。入口で貸し出されるインタラクティブタブレットで各展示の深掘り解説を日本語・英語等で体験可能。",
     "📱 Admission is completely free; pick up an interactive tablet guide at the entrance to engage with interactive displays.",
     "入場無料", "Free Entry"),

    ("b_21", "Jeanneke-Pis & Delirium Café", "Jeanneke-Pis & Delirium Café（ジャンネケピス＆デリリウムカフェ）", "Café & Bistro", "★4.5", "city", 50.8484, 4.3540, False, True, False, True,
     "Jeanneke-Pis is the 1987 female counterpart fountain to Manneken Pis. Opposite stands Delirium Café, holding a Guinness record for 2,000+ beers.",
     "ジュリアン君の女の子版「ジャンネケピス像」と、2,000種類以上のベルギービールでギネス記録を持つ世界的に有名なビアカフェ。",
     "🍺 夕方早めの時間帯を狙ってDeliriumへ入り、厚い「ビール聖書」メニューからトラピストビールやランビックを堪能。",
     "🍺 The alley gets packed at night; visit Delirium in the late afternoon to try rare Trappist and lambic fruit beers on tap.",
     "像見学無料（ビール飲食予算: €5〜€18）", "Free (Beer ~€5-18)"),

    ("b_22", "Het Zinneke / Zinneke Pis", "Het Zinneke / Zinneke Pis（小便犬ジネケ像）", "Landmark", "★4.3", "city", 50.8488, 4.3468, False, False, False, True,
     "Bronze street sculpture created in 1998 by Tom Frantzen, depicting a stray mongrel dog urinating against a street bollard.",
     "1998年制作。男の子・女の子に続くブリュッセルの小便アート第3弾「小便犬ジネケ像」。サン＝ジェリ地区の角に佇む。",
     "🐶 男の小僧・女の子像と合わせてブリュッセルの「小便3大彫刻コンプリート散策」を楽しむのが定番。",
     "🐶 Completes the peeing statue trio of Brussels; located in the trendy Saint-Géry design and cafe district.",
     "見学無料", "Free Entry"),

    ("b_23", "Sint-Gorikshallen", "Sint-Gorikshallen（サン＝ジェリ屋内市場ホール）", "Café & Bistro", "★4.5", "city", 50.8477, 4.3475, False, True, False, True,
     "19th-century Flemish Neo-Renaissance covered market hall built over Brussels' 979 AD founding island, now a cultural cafe space.",
     "1881年完成のネオ・ルネサンス様式カバー付市場。中央の噴水跡を囲むカフェバーで地ビールやクラフト料理を楽しめる。",
     "🍺 夜は地元の学生やクリエイターが集まる賑やかなバーへ変貌。テラス席で地ビールを楽しむのがおすすめ。",
     "🍺 The central interior fountain is preserved inside the bar area; grab an outdoor table on the square for craft beers.",
     "入場無料（飲食予算: €5〜€18）", "Free (Food/Drink ~€5-18)"),

    ("b_24", "Sint-Katelijne & Vismet", "Sint-Katelijne & Vismet（サント・カトリーヌ魚市場地区）", "Café & Bistro", "★4.6", "city", 50.8512, 4.3481, False, False, False, True,
     "Historic harbor basin district centered around Saint Catherine Church, lined with cobblestone quays and seafood bistros.",
     "かつての旧港ドック跡に立ち並ぶシーフードの立ち飲みバーや生牡蠣スタンドが有名なブリュッセル一番のグルメ海鮮地区。",
     "🦪 名物立ち飲み屋「Noordzee / La Mer du Nord」でマテ貝の鉄板焼きやイカフリットを白ワインと共に立ち食いするのが絶品。",
     "🦪 Stop by the historic fishmonger bar Noordzee to stand at high tables while enjoying grilled razor clams and white wine.",
     "散策無料（海鮮スタンド予算: €10〜€25）", "Free (Seafood ~€10-25)"),

    ("b_25", "Vlooienmarkt Vossenplein", "Vlooienmarkt Vossenplein（ジュ・ド・ボール広場蚤の市）", "Shopping", "★4.5", "city", 50.8359, 4.3468, False, False, True, True,
     "Authentic daily open-air flea market operating every single morning since 1919 in the heart of Marolles district.",
     "1919年から年中無休で毎朝開催される伝統の蚤の市。アンティーク家具・レコー・古本・レトロ雑貨が所狭しと並ぶ。",
     "🧥 掘り出し物を狙うなら週末の朝7:30〜9:00が狙い目。見学後はマロール地区のレトロカフェでコーヒータイム。",
     "🧥 Arrive between 7:30 AM and 9:00 AM on weekend mornings for the best antique finds; stop into a traditional brown cafe after.",
     "散策無料（買い出し自由）", "Free Walk"),

    ("b_26", "Justitiepaleis & Poelaertplein", "Justitiepaleis & Poelaertplein（最高裁判所＆プエラール広場）", "Landmark", "★4.6", "city", 50.8373, 4.3515, False, False, False, True,
     "Monumental 19th-century courthouse designed by Joseph Poelaert. Place Poelaert in front offers panoramic views over the Lower Town.",
     "19世紀建造のヨーロッパ最大級の石造裁判所。前のプエラール広場からはブリュッセル旧市街全域とグランプラスの尖塔が見渡せる。",
     "🌅 広場横の無料ガラスエレベーター「Ascenseur Poelaert」でマロール地区へ一気に下れる。夕暮れの日没鑑賞に最高。",
     "🌅 Ride the free glass Ascenseur Poelaert elevator connecting the square to Marolles; great spot for watching the sunset.",
     "見学無料", "Free Entry"),

    ("b_27", "De Marollen", "De Marollen（マロール下町地区）", "Scenery & Walk", "★4.6", "city", 50.8367, 4.3481, False, False, True, True,
     "Brussels' historic working-class neighborhood packed with antique shops, vintage thrift stores, indie design studios, and taverns.",
     "最高裁判所の足元に広がる庶民的な歴史地区。アンティークショップ、ヴィンテージ古着店、伝統のカフェが軒を連ねる。",
     "🛍️ Rue Haute（オート通り）とRue Blaes（ブラエス通り）のアンティーク店街を歩き、ソーセージ付きマッシュポテト（Stoemp）を味わう。",
     "🛍️ Walk down Rue Haute and Rue Blaes for eclectic antique shopping, stopping by traditional brasseries for stoemp.",
     "散策無料", "Free Walk"),

    ("b_28", "Koninklijke Muntschouwburg", "Koninklijke Muntschouwburg（モネ劇場 / ベルギー王立歌劇場）", "Landmark", "★4.6", "city", 50.8497, 4.3546, False, True, False, True,
     "Belgium's premier neoclassical opera and ballet theater on Place de la Monnaie, historically famous as the starting point of the 1830 Revolution.",
     "1830年のベルギー独立革命の引き金となった歴史的歌劇場。新古典主義様式の豪華な内部でオペラやバレエ公演が催される。",
     "🎭 ガイド付き建築ツアーで豪華なロココ調ホールを鑑賞するか、夜のオペラ公演チケットを公式予約。",
     "🎭 Check the schedule for guided architectural tours of the auditorium staterooms, or book tickets for opera productions.",
     "公演チケット各種 / ガイドツアー約€12.00", "Show Tickets Var / Tour ~€12.00"),

    ("b_29", "Koninklijke Serres van Laken", "Koninklijke Serres van Laken（ラーケン王立温室 / 春季限定公開）", "Landmark", "★4.9", "suburban", 50.8864, 4.3601, False, True, False, False,
     "Monumental 19th-century Art Nouveau glass-and-steel domed greenhouses designed by Alphonse Balat for King Leopold II holding rare botanicals.",
     "アルフォンス・バラ設計。毎年「春の3〜4週間（4月中旬〜5月上旬）」のみ一般公開される王室所有のアール・ヌーヴォーガラス大温室群。",
     "🌺 オンライン事前予約が数時間で完売する超人気スポット。日没後のライトアップ温室ナイトツアーが絶景。",
     "🌺 Open to the public for only 3 to 4 weeks each spring (mid-April to early May). Tickets sell out within hours of release.",
     "料金: €5.00（事前完全予約制）", "Entry: €5.00 (Advance Booking Required)"),

    ("b_30", "Choco-Story Brussels", "Choco-Story Brussels（チョコ・ストーリー体験型チョコレート博物館）", "Museum & Gallery", "★4.7", "city", 50.8462, 4.3512, True, True, True, False,
     "Interactive chocolate museum near Grand-Place tracing cocoa from Mayan roots to Belgian pralines with live master demonstrations.",
     "マヤ文明のカカオの起源からベルギーチョコの歴史までを体験型展示で紹介。ショコラティエによる実演とチョコ試食が充実。",
     "🍫 30分おきにデモキッチンで開催される出来立て生プラリネの作成実演＆温かい出来立てチョコ試食が大人気。",
     "🍫 Live praline-making demonstrations occur every 30 minutes in the demonstration kitchen with warm freshly made samples.",
     "料金: €14.00", "Entry: €14.00"),

    ("b_31", "Museum van het Natuurwetenschappen", "Museum van het Natuurwetenschappen（王立自然史博物館 / 恐竜ギャラリー）", "Museum & Gallery", "★4.7", "city", 50.8369, 4.3764, True, True, False, False,
     "Houses the world-famous Dinosaur Gallery—the largest exhibition hall in Europe dedicated entirely to dinosaurs with 30 complete skeletons.",
     "1878年にベルニサール炭鉱で発見された30体のイグアノドン完全全身骨格を誇る、ヨーロッパ最大級の恐竜ギャラリー。",
     "🦖 ファミリー層人気No.1。入口で発見探検ブックレットを入手し、上階の進化ギャラリーや化石展示を散策。",
     "🦖 Top-tier destination for kids; pick up the interactive discovery track booklet at the entrance and visit the Evolution Gallery.",
     "料金: €13.00", "Entry: €13.00"),

    ("b_32", "Cantillon Brouwerij", "Cantillon Brouwerij（カンティヨン伝統ランビック醸造所）", "Landmark", "★4.8", "city", 50.8416, 4.3353, False, True, False, True,
     "The last operating traditional spontaneous-fermentation brewery in Brussels (1900), producing oak-barrel-aged Lambic, Gueuze, and Kriek.",
     "空気中の野生酵母で自然発酵させる1900年創業のブリュッセル唯一の伝統ランビック醸造所。オーク樽熟成の醸造工程が見学可能。",
     "🍺 案内パンフレット片手に歴史的銅製窯や木樽部屋を見学後、タップルームで新鮮な酸味のグーズやクリエック（チェリー）を試飲。",
     "🍺 Take the self-guided tour through wooden barrel aging rooms and copper coolships, ending with a tasting of sour lambic beers.",
     "料金: €9.50（試飲2種付）", "Entry: €9.50 (2 Tastings Incl.)"),

    ("b_33", "Maison Dandoy", "Maison Dandoy（メゾン・ダンドワ本店 / ワッフル＆スペキュロス）", "Café & Bistro", "★4.6", "city", 50.8465, 4.3518, False, True, True, True,
     "Brussels' historic bakery operating since 1829, famous for handmade spiced speculoos biscuits and authentic hot Belgian waffles.",
     "1829年創業の老舗菓子店。伝統木型で抜くスパイスクッキー「スペキュロス」と焼きたてモチモチのベルギーワッフルが名物。",
     "ワッフルは「外サクサク中フワフワのブリュッセル風」と「濃厚で甘いリエージュ風」の食べ比べがおすすめ。",
     "🧇 Visit the tea room near Grand-Place to compare the dense sugary Liège Waffle against the light crispy Brussels Waffle.",
     "テイクアウト/喫茶予算: €5〜€15", "Waffle/Biscuit ~€5-15"),

    ("b_34", "Église Notre-Dame des Victoires au Sablon", "Église Notre-Dame des Victoires au Sablon（サブロン教会）", "Landmark", "★4.7", "city", 50.8402, 4.3561, False, True, False, True,
     "15th-century Brabantine High Gothic church built by the Crossbowmen's Guild, featuring soaring 14m stained glass and marble chapels.",
     "15世紀に弓手ギルドによって建立されたブラバント・ブラバンティン・ゴシック建築の傑作。高さ14mの大ステンドグラスが幻想的。",
     "⛪ 見学無料。晴れた日の午前中に訪れると、色鮮やかな光が白い石造りの聖堂内に差し込み神秘的な写真を撮影可能。",
     "⛪ Free entry; step inside on sunny mornings when colored sunlight streams through the 14-meter-tall stained glass windows.",
     "見学無料", "Free Entry"),

    ("b_35", "De Zavel / Le Sablon", "De Zavel / Le Sablon（グラン・サブロン＆プチ・サブロン広場）", "Scenery & Walk", "★4.7", "city", 50.8397, 4.3558, False, False, True, True,
     "Refined aristocratic district ringed with premier chocolatiers (Marcolini, Wittamer), antique galleries, and Petit Sablon guild garden.",
     "最高級ショコラティエの本店や骨董店が集まるエレガントな地区。中世職人ギルドブロンズ像48体が囲むプチ・サブロン庭園が美しい。",
     "🌳 プチ・サブロン庭園のベンチでひと休みしながらギルド像を鑑賞。週末は骨董市も開催される。",
     "🌳 Relax on the benches of the Petit Sablon garden to admire the Gothic fountain surrounded by miniature carved guild statues.",
     "散策無料", "Free Walk"),

    ("b_36", "Train World", "Train World（トレイン・ワールド / ベルギー鉄道博物館）", "Museum & Gallery", "★4.8", "suburban", 50.8781, 4.3792, True, True, False, False,
     "Official museum of the National Railway Company of Belgium in historic 1887 Schaerbeek station, featuring Europe's oldest steam engine Pays de Liège.",
     "1887年の歴史的駅舎内にある鉄道博物館。ヨーロッパ最古の蒸気機関車「Pays de Liège」や王室専用列車、運転シミュレーターを展示。",
     "🚂 実際にクラシックな客車に乗り込んだり、実物大の鉄道橋を歩いたり、運転席シミュレーターを操作可能。",
     "🚂 Step inside authentic vintage sleeping cars, walk over a full-scale railway bridge installation, and operate simulators.",
     "料金: €15.00", "Entry: €15.00"),

    ("b_37", "Koninklijk Paleis van Laken", "Koninklijk Paleis van Laken（ラーケン宮殿）", "Landmark", "★4.5", "suburban", 50.8872, 4.3592, False, False, False, True,
     "The private primary residence of the Belgian Royal Family, situated in a sprawling wooded estate in northern Brussels near Atomium.",
     "ラーケンの広い森林敷地内に位置するベルギー国王一家の私的居城。アトミウム観光と合わせた公園散策が人気。",
     "👑 宮殿敷地自体は非公開だが、広大な庭園外周囲やレオポルド1世記念塔の遊歩道は自由に散策可能。",
     "👑 The residence itself is private, but the surrounding parklands provide scenic walking paths when combined with Atomium.",
     "外観・公園散策無料", "Free Park Walk"),

    ("b_38", "Plantentuin Meise", "Plantentuin Meise（メイゼ植物園 / 92ヘクタール大植物園）", "Scenery & Walk", "★4.7", "suburban", 50.9281, 4.3314, True, True, False, False,
     "One of the largest botanical gardens in the world (92 hectares), featuring 12th-century Bouchout Castle and Palace of Plants glasshouse.",
     "92ヘクタールの世界最大級の植物園。12世紀のブーシャウト城や巨大温室群「Palace of Plants」、オオオニバスのプールを完備。",
     "🌺 温室内で直径2m超の巨大オオオニバスを鑑賞し、シャクナゲの森の上に架かる木製空中回廊を散策。",
     "🌺 Explore giant Victoria amazonica water lilies in the tropical glasshouse and walk the wooden canopy bridge walkway.",
     "料金: €12.00", "Entry: €12.00"),

    ("b_39", "Maison du Roi / Broodhuis", "Maison du Roi / Broodhuis（王の家 / ブリュッセル市立博物館）", "Museum & Gallery", "★4.6", "city", 50.8468, 4.3524, False, True, False, False,
     "Neo-Gothic palace facing Town Hall on Grand-Place, displaying municipal history and the official wardrobe collection of Manneken Pis.",
     "グランプラスの市庁舎向かいに聳えるネオ・ゴシック建築。ブリュッセルの歴史資料とジュリアン君の衣装（1,000着以上）を保管。",
     "👗 最上階の展示室には宇宙服や民族衣装、ロックスタースーツなど世界中から寄贈されたジュリアン君の衣装コレクションがずらり。",
     "👗 Head to the top floor to view the extensive wardrobe room of Manneken Pis featuring miniature astronaut suits and rock outfits.",
     "料金: €10.00", "Entry: €10.00"),

    ("b_40", "Abdij Ter Kameren", "Abdij Ter Kameren（カンブル修道院）", "Scenery & Walk", "★4.6", "city", 50.8183, 4.3736, False, False, False, True,
     "Former 12th-century Cistercian abbey nestled in a valley south of Ixelles, featuring French terraced water gardens and peaceful cloisters.",
     "12世紀創立のシトー会修道院跡。フランス式テラス庭園、静かな回廊、池が広がるブリュッセル南部の美しい隠れ家スポット。",
     "🌿 都会の喧騒から離れた静寂の緑地。庭園を散策した後はそのまま南側のカンブルの森（Bois de la Cambre）へ繋がる。",
     "🌿 A quiet elegant green sanctuary away from the downtown core; stroll the terraced lawns and continue into Bois de la Cambre.",
     "見学無料", "Free Entry"),

    ("b_41", "Bois de la Cambre", "Bois de la Cambre（カンブルの森＆ロビンソン島）", "Scenery & Walk", "★4.7", "city", 50.8108, 4.3756, True, False, False, True,
     "Massive 120-hectare English landscape park featuring an expansive boating lake with the central Chalet Robinson restaurant island.",
     "ユネスコ世界遺産のソワニュの森に繋がる120ヘクタールの広大な公園。中央の池に浮かぶ「ロビンソン島」へは手漕ぎ渡し船で渡る。",
     "渡り船（コイン制）に乗って島へ渡り、水辺のレストラン「Chalet Robinson」でランチや地ビールを楽しむのが名物。",
     " Take the small wooden ferry raft across to Chalet Robinson island for drinks or weekend brunch surrounded by water.",
     "入園無料（渡し船片道約€1.00）", "Free (Ferry ~€1.00)"),

    ("b_42", "Zoniënwoud / Forêt de Soignes", "Zoniënwoud（ソワニュの森 / ユネスコ世界遺産）", "Scenery & Walk", "★4.8", "suburban", 50.7833, 4.4167, False, False, False, True,
     "4,400-hectare ancient beech forest on the southern edge of Brussels, recognized as part of UNESCO World Heritage Ancient Beech Forests.",
     "樹齢200年を超えるブナの大木が聳える「ブナの大聖堂」。4,400ヘクタールにおよぶユネスコ自然世界遺産の原生林保護区。",
     "🌲 レンタサイクルで標識付きの森林サイクリングルートを走り、巨木に囲まれた神秘的な自然空間を散策。",
     "🌲 Rent a bike and cycle along the marked woodland paths to explore towering 200-year-old beech tree canopies.",
     "入園無料", "Free Entry"),

    ("b_43", "Slagveld van Waterloo / Mémorial 1815", "Slagveld van Waterloo（ワーテルロー古戦場＆ライオンの丘）", "Landmark", "★4.7", "suburban", 50.6800, 4.4056, True, True, False, False,
     "Historic battlefield 20 minutes south of Brussels where Napoleon was defeated in 1815, featuring the 40m conical Lion's Mound and museum.",
     "1815年にナポレオンが最終的敗北を喫した歴史的戦場。高さ40mの「ライオンの丘」と地下のインタラクティブ体験館が広がる。",
     "🪜 226段の石階段を登ってライオン像の頂上へ立つと、広大な戦場跡の全景を360度見渡すことができる。",
     "🪜 Climb the 226 steep stone steps to the summit of the Lion's Mound for a clear panoramic perspective over the battlefield.",
     "料金: €23.00（共通パス）", "Entry: €23.00 (Combo Pass)"),

    ("b_44", "Historisch Leuven: Stadhuis & Oude Markt", "Historisch Leuven（ルーヴェン旧市街：市庁舎＆最長バー街）", "Landmark", "★4.7", "suburban", 50.8798, 4.7005, False, False, True, True,
     "20 minutes by train from Brussels. Home to KU Leuven (1425), late-Gothic Town Hall with 236 statues, and Oude Markt bar square.",
     "1425年創立のルーヴェン大学の学術都市。236体の彫刻で覆われたゴシック様式市庁舎と「世界一長いカウンター」と呼ばれるバー街が有名。",
     "🍺 ステラ・アルトワ発祥の地。30軒以上のカフェテラスが連なる「Oude Markt」で焼きたてフリッツと地ビールを堪能。",
     "🍺 Grab a seat on the outdoor terrace of Oude Markt square lined with over 30 continuous pub terraces serving Belgian beers.",
     "街歩き無料（市庁舎ツアー: €4.00）", "Walk Free (Town Hall Tour €4.00)"),

    ("b_45", "Kasteel van Gaasbeek", "Kasteel van Gaasbeek（ハースベーク城）", "Landmark", "★4.6", "suburban", 50.7967, 4.1883, False, False, False, True,
     "Romantic moated fairytale castle in Pajottenland hills featuring medieval towers, Renaissance tapestries, and Italian terraced gardens.",
     "パヨッテンラントの小高い丘に佇む水掘に囲まれたロマンチックな中世の城。ルネサンス調のタペストリーやイタリア式庭園が見事。",
     "🏰 お城の見学と合わせて、周辺の伝統タバーンで自然発酵ランビックビール（GueuzeやKriek）を味わうのが名物。",
     "🏰 Combine your castle visit with a tour of the traditional Pajottenland countryside to sample farmhouse Lambic beers.",
     "料金: 城内€12.00 / 庭園散策無料", "Castle €12.00 / Garden Free"),

    ("b_46", "Hallebos / The Blue Forest", "Hallebos（ハレの森 / 青い絨毯の青紫色の森・春限定）", "Scenery & Walk", "★4.9", "suburban", 50.7083, 4.2389, False, False, False, True,
     "Public forest famous for its magical purple-blue carpet of millions of blooming wild bluebells covering the forest floor in spring.",
     "毎年4月中旬〜5月上旬のわずか数週間、一面に野生のイングリッシュ・ブルーベルが咲き誇り「青い絨毯」となる幻想的な森。",
     "📸 ピーク時は青紫色の花が満開となる。花を保護するため遊歩道から外れずに散策。ハレ駅から無料シャトルバスが運行。",
     "📸 Peak bluebell bloom typically occurs between mid-April and early May; stick strictly to designated walking paths.",
     "見学無料", "Free Entry"),

    ("b_47", "Historisch Mechelen", "Historisch Mechelen（メヘレン歴史地区＆聖ロンバウツ塔）", "Landmark", "★4.7", "suburban", 51.0281, 4.4808, False, False, True, True,
     "20 minutes by train from Brussels. Features 97m St. Rombout's Tower, UNESCO Beguinage, Het Anker brewery (Gouden Carolus beer).",
     "ブリュッセルから電車で20分。高さ97mの聖ロンバウツ塔やユネスコ世界遺産のベギンホフ、名醸造所ヘット・アンカーが広がる古都。",
     "🪜 聖ロンバウツ塔の514段の階段を登りガラス張りのSkywalkへ出ると、晴れた日にはブリュッセルとアントワープの両方が見える。",
     "🪜 Climb 514 steps of St. Rombout's Tower to walk out onto the glass Skywalk platform with views of Brussels and Antwerp.",
     "街歩き無料（塔登攀: €8.00）", "Walk Free (Tower Climb €8.00)"),

    ("b_48", "Frietkoten & Maison Antoine", "Maison Antoine & Frietkoten（アントワーヌ名物フリッツスタンド）", "Café & Bistro", "★4.7", "city", 50.8381, 4.3789, True, False, False, True,
     "Authentic traditional Belgian fry stall serving double-fried Belgian potatoes in paper cones topped with over 20 artisanal sauces.",
     "1948年創業。ジョルダン広場に佇むブリュッセル最高峰のフリッツ（フレンチフライ）名店。牛脂で2度揚げしたサクサクポテト。",
     "🍟 二度揚げのサクサクフリッツにアンドルーズソースやサムライソースをトッピング。隣接のカフェテラスへ持ち込み可能。",
     "🍟 Order a large cone with sauce at Maison Antoine; nearby bar terraces allow you to bring your paper cone onto their tables.",
     "予算: €4〜€8", "Budget ~€4-8"),

    ("b_49", "Fin-de-Siècle Museum", "Fin-de-Siècle Museum（世紀末美術館）", "Museum & Gallery", "★4.7", "city", 50.8425, 4.3578, False, True, False, False,
     "Part of the Royal Museums dedicated to the 1900s artistic zenith across Impressionism, Art Nouveau, and Symbolism (Ensor, Khnopff, Horta).",
     "1900年代前後のアール・ヌーヴォー、象徴主義、インプレッショニズムの黄金期を回顧する美術館。ジェームズ・アンソール等の作品。",
     "🎨 地下へ向かって階段状に広がる吹抜けギャラリー。最下層のアール・ヌーヴォー工芸家具やガラス器コレクションが見事。",
     "🎨 Galleries descend underground around a multi-story atrium; check out the Art Nouveau furniture and glassware on lower levels.",
     "料金: €10.00", "Entry: €10.00"),

    ("b_50", "Musée BELvue", "Musée BELvue（ベルヴュー歴史博物館）", "Museum & Gallery", "★4.5", "city", 50.8419, 4.3601, False, True, False, False,
     "Situated next to the Royal Palace in an 18th-century former hotel, exploring Belgium's democracy, monarchy, and social history.",
     "王宮横の18世紀の建物を利用し、ベルギーの建国史・民主主義・王室の歴史をテーマ別に分かりやすく解説する国立歴史博物館。",
     "🇧🇪 地下階からは1731年の火災で焼失したカール5世の「クーデンベルグ宮殿地下遺構」へ直接アクセス可能。",
     "🇧🇪 The basement level provides direct access to the subterranean archaeological ruins of the 16th-century Coudenberg Palace.",
     "料金: €10.00", "Entry: €10.00"),

    ("b_51", "Paleis van Coudenberg", "Paleis van Coudenberg（クーデンベルグ宮殿地下遺構）", "Landmark", "★4.6", "city", 50.8422, 4.3603, False, True, False, True,
     "Subterranean archaeological remains of the former medieval palace of the Dukes of Burgundy and Charles V, buried beneath Place Royale.",
     "1731年の火災で地上から姿を消した、ブルゴーニュ公や神聖ローマ皇帝カール5世の伝説の中世宮殿の地下石造遺構。",
     "🔦 現代のロワイヤル広場の道路の真下に残る巨大な地下回廊や旧イザベル通りの石畳、宴会場跡を懐中電灯で探索。",
     "🔦 Walk through the underground vaulted cellars and ancient Rue Isabelle street pavement beneath modern street traffic.",
     "料金: €10.00", "Entry: €10.00"),

    ("b_52", "Villa Empain", "Villa Empain（ヴィラ・アンパン / アール・デコ芸術センター）", "Museum & Gallery", "★4.7", "city", 50.8067, 4.3853, False, False, False, False,
     "1930s Art Deco architectural masterpiece built for Baron Louis Empain featuring polished granite, gold leaf, marble, and outdoor pool.",
     "1930年にルイ・アンパン男爵のために建てられたアール・デコ建築の最高峰。花崗岩・金箔・大理石と洗練された中庭プールが特徴。",
     "📸 青い水面とアール・デコ調の石柱回廊が美しい屋外プール中庭は、ブリュッセル屈指のエレガントな写真撮影スポット。",
     "📸 The blue swimming pool courtyard surrounded by Art Deco stone pergolas offers striking architectural photography.",
     "料金: €12.00", "Entry: €12.00"),

    ("b_53", "Sint-Gillis & Flagey Architecture Walks", "Sint-Gillis & Flagey（サン＝ジレ＆フラジェ・アール・ヌーヴォー建築街）", "Scenery & Walk", "★4.7", "city", 50.8258, 4.3589, False, False, False, True,
     "Residential quarters of Saint-Gilles and Ixelles celebrated for having Europe's highest concentration of preserved Art Nouveau townhouses.",
     "アール・ヌーヴォー様式の邸宅が欧州で最も美しく保存されたサン＝ジレ地区。鉄細工のバルコニーやステンドグラスの装飾が美しい。",
     "🚶 ブルグマン通りやデファクス通りを歩き、ファサードに施されたグラフィティ装飾や洗練されたドアノブの造形美を観察。",
     "🚶 Pick up an Art Nouveau walking itinerary to spot decorative sgraffito wall murals and curved ironwork along Rue Defacqz.",
     "散策無料", "Free Walk"),

    ("b_54", "Flageyplein & Maison de la Radio", "Flageyplein & Maison de la Radio（フラジェ広場＆旧ラジオ局Le Paquebot）", "Scenery & Walk", "★4.6", "city", 50.8275, 4.3725, False, False, False, True,
     "Place Flagey in Ixelles anchored by the 1938 Art Deco radio building Le Paquebot, surrounded by Ixelles Ponds and outdoor cafes.",
     "1938年建設の客船型アール・デコ建築「Le Paquebot」が聳える池畔の広場。カフェ「Café Belga」や週末のフードマーケットで賑わう。",
     "☕ イクセル池を望む「Café Belga」のテラス席でエスプレッソやベルギーホワイトビールを楽しみながら地元民気分を体感。",
     "☕ Sit on the terrace of Café Belga facing the ponds for an espresso or Belgian white beer; sample fresh oysters from food trucks.",
     "散策無料（カフェ予算: €5〜€18）", "Free (Cafe ~€5-18)"),

    ("b_55", "Église Notre-Dame du Finistère & Rue Neuve", "Rue Neuve & Notre-Dame du Finistère（ヌーヴ通り＆フィニステル教会）", "Shopping", "★4.5", "city", 50.8522, 4.3556, False, True, True, True,
     "Brussels' busiest pedestrian retail high street lined with international stores, mid-way housing 18th-century Baroque Finistère Church.",
     "ブリュッセル一番の歩行者専用ショッピングストリート「ヌーヴ通り」。通りの中ほどに静かなバロック様式のフィニステル教会が佇む。",
     "🛍️ 買い物で疲れたらフィニステル教会の重厚なパイプオルガンとパイプラインが輝く静寂の聖堂内へ入ってリフレッシュ。",
     "🛍️ Step inside the quiet Baroque church of Notre-Dame du Finistère for a moment of quiet away from the retail bustle.",
     "散策無料", "Free Walk"),

    ("b_56", "Avenue Louise & Boulevard de Waterloo", "Avenue Louise & Boulevard de Waterloo（ルイーズ通り高級ブランド街）", "Shopping", "★4.6", "city", 50.8328, 4.3608, False, True, True, True,
     "Premier high-end fashion and luxury boulevard lined with haute-couture designer flagship stores (Chanel, Hermès, Louis Vuitton).",
     "シャネル、エルメス、ルイ・ヴィトンなどの高級メゾンが立ち並ぶブリュッセル随一のエレガントな高級ショッピング街。",
     "🛍️ ワーテルロー通りのハイブランドのウィンドウショッピングを楽しみ、ガラス屋根の「Galerie Louise」アーケードへ。",
     "🛍️ Stroll down Boulevard de Waterloo for luxury window shopping, then walk into the covered Galerie Louise passage.",
     "散策無料", "Free Walk"),

    ("b_57", "Moeder Lambic", "Moeder Lambic（ムーデル・ランビック・クラフトビール専門店）", "Café & Bistro", "★4.8", "city", 50.8464, 4.3481, False, True, False, True,
     "Leading modern craft beer temple featuring over 30 rotating taps of rare artisanal lambics, sours, and Belgian microbrews.",
     "ベルギー全国から厳選された30種類の生のクラフトビールと激レアなランビックをタップで提供するビール愛好家の聖地。",
     "🍺 カウンターのソムリエに好みの味を相談し、オーガニックパンと農家直送チーズの盛り合わせと共に自然発酵ビールをテイスティング。",
     "🍺 Ask the beer sommeliers behind the bar for recommendations; order a charcuterie board paired with an unblended draft lambic.",
     "飲食予算: €10〜€25", "Budget ~€10-25"),

    ("b_58", "Hallen van Schaarbeek", "Hallen van Schaarbeek（スカールベーク市場ホール芸術センター）", "Landmark", "★4.5", "city", 50.8603, 4.3725, False, True, False, True,
     "Restored 19th-century iron-and-glass municipal market hall transformed into a multi-disciplinary contemporary arts center.",
     "19世紀の鉄とガラスの旧市場建築を現代サーカス・ダンス・音楽フェスティバルの会場へと再生したインダストリアルアート空間。",
     "🎭 公式サイトで最新のサーカス・コンテンポラリーダンス・アクロバット公演のスケジュールをチェック。",
     "🎭 Check their seasonal program for international contemporary circus, acrobatics, and dance festivals hosted in the main hall.",
     "イベントチケット各種", "Event Tickets Various"),

    ("b_59", "Planetarium de Bruxelles", "Planetarium de Bruxelles（ブリュッセル・プラネタリウム）", "Museum & Gallery", "★4.6", "suburban", 50.8933, 4.3361, True, True, False, False,
     "One of the largest planetariums in Europe featuring a 23-meter full-dome projection screen with digital simulations of galaxies.",
     "アトミウム近くのハイゼル地区に位置する直径23mの巨大ドームスクリーンを誇るヨーロッパ最大級のデジタルプラネタリウム。",
     "🚀 アトミウムやミニ・ヨーロッパとの組み合わせに最適。多言語音声アナウンス付きの宇宙探査上映ショーが充実。",
     "🚀 Great family educational stop when visiting the Atomium; check show times for multilingual audio broadcasts.",
     "料金: €9.00", "Entry: €9.00"),

    ("b_60", "Koninklijke Bibliotheek van België / KBR", "Koninklijke Bibliotheek van België（ベルギー国立図書館 / KBR）", "Museum & Gallery", "★4.7", "city", 50.8436, 4.3556, False, True, False, False,
     "National library on Mont des Arts housing KBR Museum inside 15th-century Palace of Nassau Chapel with illuminated manuscripts.",
     "芸術の丘に佇む国立図書館。15世紀のナッソー宮殿礼拝堂跡にある「KBRミュージアム」ではブルゴーニュ公の羊皮紙彩飾手稿を展示。",
     "📖 タッチパネルで600年前の手写本のページをめくる体験が可能。5階のパブリック屋上食堂「Albert」からの旧市街の景色も抜群。",
     "📖 Use interactive digital stations to turn pages of 600-year-old manuscripts, then visit the 5th-floor rooftop cafeteria.",
     "料金: €11.00", "Entry: €11.00")
]

def format_spot_json(raw_tuple):
    sid, name_raw, name_ja_full, category, rating, zone, lat, lng, kids, rain, shopping, free, desc_en, desc_ja, tip_ja, tip_en, price_ja, price_en = raw_tuple
    
    # Clean english base name
    name_en_clean = name_raw.split(' / ')[0].strip()
    
    # Family flag: kids true or category/spot suitable
    family = True if (kids or category in ['Landmark', 'Scenery & Walk', 'Museum & Gallery']) else True
    adult = True
    
    return {
        "id": sid,
        "name": name_ja_full,
        "category": category,
        "rating": rating,
        "locationZone": zone,
        "lat": lat,
        "lng": lng,
        "kids": kids,
        "rain": rain,
        "shopping": shopping,
        "free": free,
        "family": family,
        "adult": adult,
        "image": "",
        "wikiImage": "",
        "hasWiki": False,
        "name_en": name_en_clean,
        "name_ja": name_ja_full,
        "name_es": name_en_clean,
        "name_zh": name_en_clean,
        "name_fr": name_en_clean,
        "name_de": name_en_clean,
        "desc_en": desc_en,
        "desc_ja": desc_ja,
        "desc_es": desc_en,
        "desc_zh": desc_en,
        "desc_fr": desc_en,
        "desc_de": desc_en,
        "tip_en": tip_en,
        "tip_ja": tip_ja,
        "tip_es": tip_en,
        "tip_zh": tip_en,
        "tip_fr": tip_en,
        "tip_de": tip_en,
        "price_ja": price_ja,
        "price_en": price_en,
        "price_es": price_en,
        "price_zh": price_en,
        "price_fr": price_en,
        "price_de": price_en
    }

brussels_spots = [format_spot_json(r) for r in brussels_raw]

with open('data/cities/brussels.json', 'w', encoding='utf-8') as f:
    json.dump(brussels_spots, f, indent=2, ensure_ascii=False)

print(f"Successfully written {len(brussels_spots)} spots to brussels.json")
