import json

frankfurt_all_61 = [
    # 1. Römerberg
    {"id": "f_1", "name": "Römerberg & Rathaus Römer（レーマー広場＆旧市庁舎レーマー）", "category": "Landmark", "rating": "★4.8", "locationZone": "city", "lat": 50.1103, "lng": 8.6821, "kids": True, "rain": False, "shopping": False, "free": True,
     "desc_en": "Picturesque medieval central square surrounded by timber-framed gabled houses and the 15th-century Rathaus Römer town hall.",
     "desc_ja": "木骨造りの切妻屋根の旧市庁舎『レーマー』と正義の女神像の噴水が立つフランクフルトの歴史的中心広場。",
     "desc_es": "Plaza medieval flanqueada por casas de entramado de madera y el ayuntamiento del siglo XV.",
     "desc_zh": "由木骨架房屋围合的中世纪大广场，屹立着15世纪旧市政厅与正义女神喷泉。",
     "desc_fr": "Place médiévale pittoresque entourée de maisons à colombages et de l'hôtel de ville du XVe siècle.",
     "de": "Historischer Hauptplatz mit Fachwerkhäusern, dem Römer-Rathaus und dem Gerechtigkeitsbrunnen.",
     "tip_en": "📸 Visit early morning before 8:30 AM to photograph the gabled facades without tour groups blocking the fountain.",
     "tip_ja": "📸 団体ツアー客が到着する前の早朝8:30前に訪問するのが鉄則！正義の女神像の正面から広角写真が撮影できます。",
     "tip_es": "📸 Visítala temprano antes de las 8:30 h para fotografiar las fachadas sin grupos de turistas.",
     "tip_zh": "📸 建议早晨8:30之前抵达！立于正义女神喷泉正面拍摄无遮挡广角画面。",
     "tip_fr": "📸 Venez tôt avant 8h30 pour photographier les façades à colombages sans la foule.",
     "tip_de": "📸 Morgens vor 8:30 Uhr kommen, um die Fachwerkfassaden ohne Reisegruppen zu fotografieren.",
     "price_en": "Free Access", "price_ja": "見学無料", "price_es": "Acceso libre", "price_zh": "免费参观", "price_fr": "Accès libre", "price_de": "Kostenlos",
     "name_en": "Römerberg & City Hall", "name_ja": "Römerberg & Rathaus Römer（レーマー広場＆旧市庁舎レーマー）", "name_es": "Römerberg y Ayuntamiento", "name_zh": "罗马人广场与旧市政厅", "name_fr": "Place du Römerberg", "name_de": "Römerberg & Rathaus Römer"},
    # 2. Kaiserdom
    {"id": "f_2", "name": "Kaiserdom St. Bartholomäus（聖バルトロメウス大聖堂 / カイザードーム）", "category": "Landmark", "rating": "★4.7", "locationZone": "city", "lat": 50.1106, "lng": 8.6853, "kids": True, "rain": True, "shopping": False, "free": True,
     "desc_en": "Gothic red-sandstone cathedral where Holy Roman Emperors were elected and crowned, featuring a 95m spire tower.",
     "desc_ja": "神聖ローマ皇帝の選挙と戴冠式が執り行われた赤砂岩のゴシック様式大聖堂。高さ95mの塔が聳える。",
     "desc_es": "Catedral gótica de arenisca roja donde se coronaba a los emperadores del Sacro Imperio Romano Germánico.",
     "desc_zh": "红砂岩哥特式大教堂。昔日神圣罗马帝国皇帝在此举行选举与加冕典礼。",
     "desc_fr": "Cathédrale gothique en grès rouge où étaient couronnés les empereurs du Saint-Empire.",
     "de": "Gotischer Rotsandstein-Dom, in dem die Kaiser des Heiligen Römischen Reiches gekrönt wurden.",
     "tip_en": "📸 Climb the 328 steep steps up the Domturm for a panoramic view over Römerberg and the Main river!",
     "tip_ja": "📸 塔内部の328段の急階段を登って展望スペースへ！レーマー広場とマイン川の絶景が見下ろせます。",
     "tip_es": "📸 Sube los 328 escalones de la torre para contemplar la vista panorámica del río y del casco antiguo.",
     "tip_zh": "📸 攀登塔楼内部328级陡峭阶梯登顶！俯瞰红屋顶集聚的旧城区与美因河畔。",
     "tip_fr": "📸 Montez les 328 marches de la tour pour une vue imprenable sur le Römerberg et la rivière.",
     "tip_de": "📸 Die 328 Stufen des Domturms aufsteigen für einen Panoramablick auf den Römerberg.",
     "price_en": "Church Free (Tower €3.50)", "price_ja": "聖堂無料（塔登頂: 3.50ユーロ）", "price_es": "Catedral gratis (Torre 3,50€)", "price_zh": "教堂免费（登塔3.50欧）", "price_fr": "Cathédrale gratuite (Tour 3,50 €)", "price_de": "Dom frei (Turm 3,50 €)",
     "name_en": "Frankfurt Cathedral", "name_ja": "Kaiserdom St. Bartholomäus（聖バルトロメウス大聖堂 / カイザードーム）", "name_es": "Catedral de Fráncfort", "name_zh": "法兰克福皇帝大教堂", "name_fr": "Cathédrale de Francfort", "name_de": "Kaiserdom St. Bartholomäus"},
    # 3. Goethe-Haus
    {"id": "f_3", "name": "Goethe-Haus & Deutsches Romantik-Museum（ゲーテハウス＆ドイツ・ロマン派博物館）", "category": "Museum & Gallery", "rating": "★4.6", "locationZone": "city", "lat": 50.1114, "lng": 8.6775, "kids": True, "rain": True, "shopping": False, "free": False,
     "desc_en": "Reconstructed 18th-century birthplace of Johann Wolfgang von Goethe displaying his childhood standing desk.",
     "desc_ja": "文豪ゲーテが生まれ育った18世紀の邸宅。『若きウェルテルの悩み』を執筆した書斎が見どころ。",
     "desc_es": "Casa natal del siglo XVIII del escritor Goethe con su escritorio de infancia y museo romántico.",
     "desc_zh": "歌德诞生与成长的18世纪老宅。保存有其创作《少年维特之烦恼》的书房。",
     "desc_fr": "Maison natale du XVIIIe siècle de l'écrivain Goethe abritant son bureau et le musée du Romantisme.",
     "de": "Geburtshaus von Johann Wolfgang von Goethe mit Arbeitszimmer und Romantik-Museum.",
     "tip_en": " Examine the 3rd-floor Schreibzimmer standing desk where Goethe penned 'The Sorrows of Young Werther'.",
     "tip_ja": " 3階の書斎へ！立ち作業用のデスク『立ち机』が展示されており名作が生まれた空間を観察できます。",
     "tip_es": " Contempla en la 3ª planta el escritorio de pie original donde Goethe escribió su famosa obra.",
     "tip_zh": " 走入3楼书房！站在歌德当年立姿撰写名著《少年维特之烦恼》的复古立式书桌前。",
     "tip_fr": " Admirez au 3e étage le bureau debout où Goethe rédigea 'Les Souffrances du jeune Werther'.",
     "tip_de": " Im 3. Stock das Schreibzimmer besichtigen, in dem Goethe am Stehpult seinen Werther verfasste.",
     "price_en": "Entry: €10", "price_ja": "入場料: 10ユーロ", "price_es": "Entrada: 10€", "price_zh": "门票：10 欧元", "price_fr": "Entrée : 10 €", "price_de": "Eintritt: 10 €",
     "name_en": "Goethe House & Museum", "name_ja": "Goethe-Haus & Deutsches Romantik-Museum（ゲーテハウス＆ドイツ・ロマン派博物館）", "name_es": "Casa-Museo de Goethe", "name_zh": "歌德故居与浪漫主义博物馆", "name_fr": "Maison-Musée de Goethe", "name_de": "Goethe-Haus & Deutsches Romantik-Museum"},
    # 4. Städel Museum
    {"id": "f_4", "name": "Städel Museum（シュテーデル美術館）", "category": "Museum & Gallery", "rating": "★4.8", "locationZone": "city", "lat": 50.1031, "lng": 8.6742, "kids": True, "rain": True, "shopping": False, "free": False,
     "desc_en": "Germany's premier art museum housing 700 years of European masterworks like Vermeer's 'The Geographer'.",
     "desc_ja": "700年にわたる欧州美術の殿堂。フェルメール『地理学者』やティシュバイン描くゲーテ像を所蔵。",
     "desc_es": "Excelente museo de arte con 700 años de obras maestras europeas como 'El geógrafo' de Vermeer.",
     "desc_zh": "德国顶尖艺术殿堂。收藏有维米尔的绝世珍品《地理学者》及歌德巨幅肖像画。",
     "desc_fr": "L'un des plus grands musées d'art d'Allemagne abritant 700 ans de chefs-d'œuvre européens.",
     "de": "Bedeutendes Kunstmuseum mit 700 Jahren europäischer Meisterwerke wie Vermeers 'Der Geograph'.",
     "tip_en": "🖼️ Walk down into the underground Gartenhallen illuminated by 195 circular skylights in the lawn!",
     "tip_ja": "🖼️ 地下新館『Gartenhallen』へ！芝生に埋め込まれた195個の天窓から光が注ぐ空間で現代アートを観賞。",
     "tip_es": "🖼️ Baje a la ampliación subterránea Gartenhallen iluminada por tragaluces circulares del césped.",
     "tip_zh": "🖼️ 走入地下新馆 Gartenhallen！仰望嵌入草坪的195个圆形天窓，在漫射光中观赏现代艺术。",
     "tip_fr": "🖼️ Descendez dans l'extension souterraine Gartenhallen baignée par les puits de lumière.",
     "tip_de": "🖼️ In den unterirdischen Neubau (Gartenhallen) hinabsteigen und Kunst unter den Deckenaugen erleben.",
     "price_en": "Entry: €16", "price_ja": "入場料: 16ユーロ", "price_es": "Entrada: 16€", "price_zh": "门票：16 欧元", "price_fr": "Entrée : 16 €", "price_de": "Eintritt: 16 €",
     "name_en": "Städel Museum", "name_ja": "Städel Museum（シュテーデル美術館）", "name_es": "Museo Städel", "name_zh": "施泰德美术馆", "name_fr": "Musée Städel", "name_de": "Städel Museum"},
    # 5. Main Tower
    {"id": "f_5", "name": "Main Tower（マインタワー）", "category": "Landmark", "rating": "★4.7", "locationZone": "city", "lat": 50.1114, "lng": 8.6722, "kids": True, "rain": True, "shopping": False, "free": False,
     "desc_en": "200m financial skyscraper featuring Frankfurt's only open-air rooftop observation deck at 198 meters.",
     "desc_ja": "金融街に立つ高さ200mの超高層ビル。地上198mにあるフランクフルト唯一のオープンエア屋上展望台。",
     "desc_es": "Rascacielos de 200m en el distrito financiero con el único mirador al aire libre en la azotea a 198m.",
     "desc_zh": "200米高摩天大楼。拥有法兰克福唯一位于198米高处的露天全景屋顶观景台。",
     "desc_fr": "Gratte-ciel de 200m doté de la seule plateforme d'observation en plein air à 198m.",
     "de": "200 Meter hoher Wolkenkratzer mit der einzigen Freiluft-Aussichtsplattform auf 198m.",
     "tip_en": "📸 Visit 30 minutes before sunset to capture the dusk sky and glowing financial skyscraper lights!",
     "tip_ja": "📸 日没の30分前に入場するのが黄金法則！夕焼けと周囲の摩天楼に明かりが灯る夜景の変化を撮影できます。",
     "tip_es": "📸 Entra 30 minutos antes del atardecer para ver cómo se encienden las luces de los rascacielos.",
     "tip_zh": "📸 推荐日落前30分钟登顶！饱览夕阳余晖至金融区大厦亮起繁星灯火的壮丽夜景。",
     "tip_fr": "📸 Montez 30 minutes avant le coucher du soleil pour admirer la métamorphose de la skyline.",
     "tip_de": "📸 30 Minuten vor Sonnenuntergang hochfahren, um das Aufleuchten der Skyline zu fotografieren.",
     "price_en": "Entry: €9", "price_ja": "入場料: 9ユーロ", "price_es": "Entrada: 9€", "price_zh": "门票：9 欧元", "price_fr": "Entrée : 9 €", "price_de": "Eintritt: 9 €",
     "name_en": "Main Tower Observatory", "name_ja": "Main Tower（マインタワー）", "name_es": "Torre Main Tower", "name_zh": "美因塔观景台", "name_fr": "Tour Main Tower", "name_de": "Main Tower"},
    # 6. Eiserner Steg
    {"id": "f_6", "name": "Eiserner Steg（アイゼルナー・シュテグ鉄橋）", "category": "Landmark", "rating": "★4.6", "locationZone": "city", "lat": 50.1086, "lng": 8.6817, "kids": True, "rain": False, "shopping": False, "free": True,
     "desc_en": "Historic 1869 iron footbridge spanning the Main river, decorated with thousands of love padlocks.",
     "desc_ja": "1869年建造のマイン川に架かるネオ・ゴシック風の歩行者専用鉄橋。『愛の南京錠』が敷き詰められる。",
     "desc_es": "Puente peatonal de hierro histórico de 1869 sobre el río Meno decorado con candados de amor.",
     "desc_zh": "始于1869年横跨美因河的历史铁索人行桥。挂满了成千上万锁住爱情的连心锁。",
     "desc_fr": "Passerelle piétonne historique en fer de 1869 sur le Meno couverte de cadenas d'amour.",
     "de": "Historische Fußgänger-Eisenbrücke von 1869 über den Main mit tausenden Liebesschlössern.",
     "tip_en": "📸 Walk to the middle looking north to frame the skyscraper skyline behind Römerberg's gabled roofs!",
     "tip_ja": "📸 橋の中央部から北側を振り返って撮影！伝統的な旧市街の屋根と現代の摩天楼が重ね合わさります。",
     "tip_es": "📸 Camina hasta el centro mirando al norte para encuadrar los rascacielos tras el casco antiguo.",
     "tip_zh": "📸 步至铁桥中央面向北方！将旧城区红屋顶与背景高耸的摩天大楼重叠连拍。",
     "tip_fr": "📸 Placez-vous au milieu du pont en regardant vers le nord pour cadrer les gratte-ciel.",
     "tip_de": "📸 Auf der Brückenmitte nach Norden schauen: Dächer der Altstadt vor der Hochhaus-Kulisse.",
     "price_en": "Free Access", "price_ja": "通行無料", "price_es": "Acceso libre", "price_zh": "免费通行", "price_fr": "Accès libre", "price_de": "Kostenlos",
     "name_en": "Iron Footbridge", "name_ja": "Eiserner Steg（アイゼルナー・シュテグ鉄橋）", "name_es": "Puente de Hierro", "name_zh": "铁桥", "name_fr": "Passerelle en fer Eiserner Steg", "name_de": "Eiserner Steg"},
    # 7. Paulskirche
    {"id": "f_7", "name": "Paulskirche（聖パウロ教会）", "category": "Landmark", "rating": "★4.5", "locationZone": "city", "lat": 50.1111, "lng": 8.6808, "kids": True, "rain": True, "shopping": False, "free": True,
     "desc_en": "Red-sandstone church where Germany's first freely elected parliament met in 1848, cradle of democracy.",
     "desc_ja": "1848年にドイツ初の自由選挙による国民議会が開催された赤砂岩教会。民主主義の揺籃の地。",
     "desc_es": "Iglesia de arenisca roja donde se reunió la primera Asamblea Nacional alemana en 1848.",
     "desc_zh": "始于1848年德国首届由自由选举产生的国民议会召开地。被誉为德国民主的摇篮。",
     "desc_fr": "Église en grès rouge où s'est réuni le premier parlement allemand en 1848.",
     "de": "Historische Rotsandsteinkirche und Tagungsort der ersten deutschen Nationalversammlung von 1848.",
     "tip_en": " Walk upstairs into the circular hall to view Johannes Grützke's 33m mural 'The Procession of Representatives'.",
     "tip_ja": " 2階の円形本会議堂へ！壁面を囲むヨハネス・グリュツケ制作の33m長大壁画を鑑賞しましょう。",
     "tip_es": " Entra a la sala circular de la planta superior para contemplar el gran mural de 33 metros.",
     "tip_zh": " 走入2楼主圆厅内！环顾欣赏由画家 Johannes Grützke 创作长达33米的巨幅环形壁画。",
     "tip_fr": " Montez dans la grande salle circulaire pour admirer la fresque murale géante de 33 mètres.",
     "tip_de": " In den rundförmigen Hauptsaal gehen und das 33m lange Wandgemälde betrachten.",
     "price_en": "Free Entry", "price_ja": "入場無料", "price_es": "Entrada libre", "price_zh": "免费参观", "price_fr": "Gratuit", "price_de": "Kostenlos",
     "name_en": "St. Paul's Church", "name_ja": "Paulskirche（聖パウロ教会）", "name_es": "Iglesia de San Pablo", "name_zh": "圣保罗教堂", "name_fr": "Église Saint-Paul", "name_de": "Paulskirche"},
    # 8. Alte Oper
    {"id": "f_8", "name": "Alte Oper（アルテ・オーパー旧オペラ座）", "category": "Landmark", "rating": "★4.7", "locationZone": "city", "lat": 50.1158, "lng": 8.6719, "kids": True, "rain": True, "shopping": False, "free": True,
     "desc_en": "Grand 1880 Neo-Renaissance concert hall rebuilt post-WWII with inscription 'Dem Wahren, Schönen, Guten'.",
     "desc_ja": "1880年建造の壮麗なネオ・ルネサンス様式の旧オペラ座。『真・美・善のために』の刻印が象徴的。",
     "desc_es": "Gran sala de conciertos neorrenacentista de 1880 reconstruida tras la II Guerra Mundial frente a una plaza.",
     "desc_zh": "建于1880年的新文艺复兴风格旧歌剧院。立面上刻有“献给真实、美好与善良”的铭文。",
     "desc_fr": "Grande salle de concert néo-renaissance de 1880 avec sa devise 'Dem Wahren, Schönen, Guten'.",
     "de": "Prachtvolles Neurenaissance-Konzertgebäude von 1880 mit der Inschrift 'Dem Wahren, Schönen, Guten'.",
     "tip_en": "☕ Sit at the outdoor terrace cafe on Opernplatz in front of Lucae Fountain during evening illuminations!",
     "tip_ja": "☕ オペラ広場の噴水前にあるオープンカフェで休憩！黄金像がライトアップされる夕暮れ時がロマンチック。",
     "tip_es": "☕ Disfruta de un café en la terraza exterior contemplando la fuente y las estatuas doradas.",
     "tip_zh": "☕ 推荐在 Opernplatz 广场喷泉旁的露天咖啡座选座，仰望夜幕下点亮的金色雕像外墙。",
     "tip_fr": "☕ Prenez un café en terrasse sur la place de l'Opéra en admirant la fontaine illuminée.",
     "tip_de": "☕ Auf der Terrasse am Opernplatz vor dem Lucae-Brunnen sitzen und das Gebäude genießen.",
     "price_en": "Square Free (Concerts Varies)", "price_ja": "広場無料（公演により異なる）", "price_es": "Plaza gratis (Conciertos varía)", "price_zh": "广场免费（演出票价另计）", "price_fr": "Place gratuite (Concerts variable)", "price_de": "Platz frei (Konzertkarten variieren)",
     "name_en": "Old Opera House", "name_ja": "Alte Oper（アルテ・オーパー旧オペラ座）", "name_es": "Antigua Ópera de Fráncfort", "name_zh": "老歌剧院", "name_fr": "Opéra de Francfort", "name_de": "Alte Oper"},
    # 9. Palmengarten
    {"id": "f_9", "name": "Palmengarten（パルメンガルテン植物園）", "category": "Scenery & Walk", "rating": "★4.7", "locationZone": "city", "lat": 50.1239, "lng": 8.6575, "kids": True, "rain": True, "shopping": False, "free": False,
     "desc_en": "22-hectare botanical park featuring the historic 1869 iron-and-glass Palmenhaus greenhouse.",
     "desc_ja": "1869年建造の鉄とガラスの大温室パルメンハウスを中心に、熱帯植物やランが広がる22haの植物園。",
     "desc_es": "Jardín botánico de 22 hectáreas con el invernadero de hierro y cristal Palmenhaus de 1869.",
     "desc_zh": "占地22公顷的巨型植物园。以始于1869年的铁艺玻璃大温室（Palmenhaus）闻名。",
     "desc_fr": "Jardin botanique de 22 hectares abritant la grande serre en fer et verre de 1869 aux palmiers.",
     "de": "22 Hektar großer botanischer Garten mit dem historischen Palmenhaus von 1869.",
     "tip_en": " Step inside the historic 1869 Palmenhaus glasshouse to experience tropical humidity and artificial waterfall!",
     "tip_ja": " 1869年建造の大温室パルメンハウス内部へ！年間を通じて20℃以上に保たれた熱帯密林と滝を体感。",
     "tip_es": " Entra en el invernadero Palmenhaus para experimentar el clima tropical y la cascada interior.",
     "tip_zh": " 步入古董级玻璃温室 Palmenhaus！感受全年维持在20℃以上的热带湿润雨林与瀑布。",
     "tip_fr": " Entrez dans la grande serre Palmenhaus pour vivre le climat tropical et la cascade !",
     "tip_de": " Das historische Palmenhaus betreten, um das tropische Gewächshausklima mit Wasserfall zu erleben.",
     "price_en": "Entry: €7", "price_ja": "入場料: 7ユーロ", "price_es": "Entrada: 7€", "price_zh": "门票：7 欧元", "price_fr": "Entrée : 7 €", "price_de": "Eintritt: 7 €",
     "name_en": "Palmengarten Botanical Garden", "name_ja": "Palmengarten（パルメンガルテン植物園）", "name_es": "Jardín Botánico Palmengarten", "name_zh": "棕榈园植物园", "name_fr": "Jardin botanique Palmengarten", "name_de": "Palmengarten Frankfurt"},
    # 10. Historisches Museum Frankfurt
    {"id": "f_10", "name": "Historisches Museum Frankfurt（フランクフルト歴史博物館）", "category": "Museum & Gallery", "rating": "★4.7", "locationZone": "city", "lat": 50.1097, "lng": 8.6828, "kids": True, "rain": True, "shopping": False, "free": False,
     "desc_en": "City history museum next to Römerberg combining medieval buildings with a modern exhibition wing.",
     "desc_ja": "中世の建築群と最新の現代翼が融合した都市史博物館。800年にわたるフランクフルトの歩みを展示。",
     "desc_es": "Museo de historia urbana junto a Römerberg con maquetas interactivas de la ciudad.",
     "desc_zh": "紧邻 Römer 广场的顶尖城市历史博物馆。融合中世纪古建筑与现代新馆全景展示800年变迁。",
     "desc_fr": "Musée d'histoire de la ville combinant bâtiments médiévaux et aile moderne avec maquettes géantes.",
     "de": "Modernes Stadtmuseum am Römerberg mit interaktiven Stadtmodellen von den Anfängen bis zur Gegenwart.",
     "tip_en": " Head to the 2nd floor modern wing to interact with the motorized 800-year 3D scale model of Frankfurt!",
     "tip_ja": " 新館2階の巨大3D都市模型へ！ボタン操作で中世から現代までの街並みが動的に変形点灯します。",
     "tip_es": " Interactúa con la maqueta 3D motorizada de la ciudad en la 2ª planta del ala moderna.",
     "tip_zh": " 前往新馆2楼观赏可互动的巨型3D城市模型！点击控制台动态观察800年来天际线的变迁。",
     "tip_fr": " Interagissez avec la grande maquette 3D de la ville au 2e étage pour voir l'évolution.",
     "tip_de": " Im 2. Stock des Neubaus das bewegliche 3D-Stadtmodell ausprobieren.",
     "price_en": "Entry: €12", "price_ja": "入場料: 12ユーロ", "price_es": "Entrada: 12€", "price_zh": "门票：12 欧元", "price_fr": "Entrée : 12 €", "price_de": "Eintritt: 12 €",
     "name_en": "Frankfurt History Museum", "name_ja": "Historisches Museum Frankfurt（フランクフルト歴史博物館）", "name_es": "Museo Histórico de Fráncfort", "name_zh": "法兰克福历史博物馆", "name_fr": "Musée d'histoire de Francfort", "name_de": "Historisches Museum Frankfurt"},
    # 11. Liebieghaus
    {"id": "f_11", "name": "Liebieghaus Skulpturensammlung（リービークハウス彫刻美術館）", "category": "Museum & Gallery", "rating": "★4.7", "locationZone": "city", "lat": 50.1022, "lng": 8.6725, "kids": True, "rain": True, "shopping": False, "free": False,
     "desc_en": "19th-century villa housing 5,000 years of global sculpture from ancient Egypt and Greece to Renaissance.",
     "desc_ja": "19世紀のヴィラを利用した彫刻専門美術館。古代エジプト・ギリシャからルネサンスまでの彫刻を展示。",
     "desc_es": "Villa del siglo XIX con 5.000 años de escultura mundial desde el antiguo Egipto hasta el Renacimiento.",
     "desc_zh": "别墅式雕塑专门博物馆。陈列有自古埃及、古希腊至文艺复兴跨越5000年的世界雕塑艺术。",
     "desc_fr": "Villa du XIXe siècle abritant 5 000 ans de sculptures mondiales de l'Égypte ancienne à la Renaissance.",
     "de": "Skulpturenmuseum in einer Historismus-Villa am Museumsufer mit Kunst aus 5.000 Jahren.",
     "tip_en": " Head to the garden courtyard to admire classical marble statues surrounded by manicured roses!",
     "tip_ja": " 庭園の中庭へ！手入れされたバラ園に囲まれた古典大理石彫刻を静かに観賞できます。",
     "tip_es": " Disfruta del patio ajardinado para contemplar estatuas de mármol entre rosas.",
     "tip_zh": " 步入中庭庭园！在精心修剪的玫瑰花丛中观赏大理石大雅雕像。",
     "tip_fr": " FLânez dans le jardin intérieur pour admirer les statues en marbre entourées de rosiers.",
     "tip_de": " Im Garteninnenhof klassische Marmorskulpturen inmitten von Rosenbeeten betrachten.",
     "price_en": "Entry: €12", "price_ja": "入場料: 12ユーロ", "price_es": "Entrada: 12€", "price_zh": "门票：12 欧元", "price_fr": "Entrée : 12 €", "price_de": "Eintritt: 12 €",
     "name_en": "Liebieghaus Sculpture Museum", "name_ja": "Liebieghaus Skulpturensammlung（リービークハウス彫刻美術館）", "name_es": "Colección de Esculturas Liebieghaus", "name_zh": "利比希雕塑博物馆", "name_fr": "Musée de sculpture Liebieghaus", "name_de": "Liebieghaus Skulpturensammlung"},
    # 17. Kleinmarkthalle
    {"id": "f_17", "name": "Kleinmarkthalle（クラインマルクトハレ屋内市場）", "category": "Shopping", "rating": "★4.7", "locationZone": "city", "lat": 50.1119, "lng": 8.6833, "kids": True, "rain": True, "shopping": True, "free": True,
     "desc_en": "1954 indoor food market with 150+ stalls selling sausages, green sauce herbs, cheeses, and wine.",
     "desc_ja": "150以上の店舗が集結する1954年開業の屋内市場。ソーセージや特産『緑のソース』のハーブが集まる。",
     "desc_es": "Mercado cubierto de 1954 con más de 150 puestos de salchichas, salsa verde, quesos y vinos.",
     "desc_zh": "始于1954年的传统室内食品集市。拥有150多个摊位，汇聚特产法兰克福香肠与“绿酱”七草。",
     "desc_fr": "Halle couverte de 1954 avec plus de 150 étals de saucisses régionales, sauce verte et vins.",
     "de": "Markthalle von 1954 mit über 150 Ständen für Frankfurter Wurst, Grüne Soße und Feinkost.",
     "tip_en": "🍽️ Stand in line at 'Schreiber-Schreiber' on the ground floor to order a hot Fleischwurst sausage for €3.50!",
     "tip_ja": "🍽️ 1階の名物肉屋『Schreiber-Schreiber』の行列へ！熱々のフライシュヴルスト（特大ソーセージ）が超絶品（€3.50）。",
     "tip_es": "🍽️ Pide una salchicha caliente Fleischwurst con mostaza en el puesto Schreiber-Schreiber en la planta baja.",
     "tip_zh": "🍽️ 认准一楼肉铺 Schreiber-Schreiber 摊位！排队购买刚出锅配黄芥末酱的热 Fleischwurst 特大香肠（3.50欧）。",
     "tip_fr": "🍽️ Commandez une saucisse chaude Fleischwurst avec de la moutarde chez Schreiber-Schreiber !",
     "tip_de": "🍽️ Anstehen beim Stand Schreiber im Erdgeschoss für eine heiße Fleischwurst mit Senf auf die Hand!",
     "price_en": "Free Entry (Snacks €3–€8)", "price_ja": "入場無料（軽食3〜8ユーロ）", "price_es": "Entrada libre (Snacks 3€–8€)", "price_zh": "免费进场（小吃3-8欧）", "price_fr": "Gratuit (Snacks 3 €–8 €)", "price_de": "Eintritt frei (Imbiss 3 €–8 €)",
     "name_en": "Kleinmarkthalle Market", "name_ja": "Kleinmarkthalle（クラインマルクトハレ屋内市場）", "name_es": "Mercado Kleinmarkthalle", "name_zh": "小市场大厅", "name_fr": "Marché Kleinmarkthalle", "name_de": "Kleinmarkthalle Frankfurt"},
    # 18. Neue Altstadt
    {"id": "f_18", "name": "Neue Altstadt（新旧市街）", "category": "Landmark", "rating": "★4.7", "locationZone": "city", "lat": 50.1108, "lng": 8.6836, "kids": True, "rain": False, "shopping": False, "free": True,
     "desc_en": "Reconstructed historical quarter featuring 35 rebuilt medieval and renaissance timber houses.",
     "desc_ja": "戦災で失われた中世・ルネサンス期の木骨造り街並みを精密に再建した新旧市街。石畳の小路が広がる。",
     "desc_es": "Barrio histórico reconstruido de 35 casas medievales entre el Römerberg y la Catedral.",
     "desc_zh": "重建于 Römer 广场与大教堂之间的古城区。35座忠实还原中世纪与文艺复兴风格的半木结构建筑。",
     "desc_fr": "Quartier historique reconstruit de 35 maisons médiévales entre le Römerberg et la Cathédrale.",
     "de": "Neu aufgebautes historisches Quartier mit 35 fachmännisch rekonstruierten Altstadthäusern.",
     "tip_en": "📸 Stroll down the narrow alleyway 'Hühnermarkt' to capture the Goldene Waage renaissance facade!",
     "tip_ja": "📸 小路『Hühnermarkt』の中央へ！黄金の秤の館『Goldene Waage』の精緻な張り出し彫刻が見事です。",
     "tip_es": "📸 Pasea por el callejón Hühnermarkt para fotografiar la casa renacentista Goldene Waage.",
     "tip_zh": "📸 步入 Hühnermarkt 小巷深处！拍摄雕琢极尽精细的 Renaissance 风格建筑 Goldene Waage。",
     "tip_fr": "📸 Parcourez la ruelle Hühnermarkt pour photographier la façade renaissance Goldene Waage.",
     "tip_de": "📸 Durch die Gasse Hühnermarkt schlendern und das Renaissance-Haus 'Goldene Waage' fotografieren.",
     "price_en": "Free Access", "price_ja": "散策無料", "price_es": "Acceso libre", "price_zh": "免费游览", "price_fr": "Accès libre", "price_de": "Kostenlos",
     "name_en": "New Old Town", "name_ja": "Neue Altstadt（新旧市街）", "name_es": "Nuevo Casco Antiguo", "name_zh": "新旧城区", "name_fr": "Nouvelle Vieille Ville", "name_de": "Neue Altstadt Frankfurt"},
    # 19. Sachsenhausen
    {"id": "f_19", "name": "Sachsenhausen & Apfelwein-Kneipen（ザクセンハウゼン＆アプフェルヴァイン居酒屋街）", "category": "Café & Bistro", "rating": "★4.6", "locationZone": "city", "lat": 50.1039, "lng": 8.6908, "kids": False, "rain": False, "shopping": False, "free": True,
     "desc_en": "Atmospheric historic district south of the Main river famous for traditional cider (Ebbelwoi) taverns.",
     "desc_ja": "マイン川南岸の石畳居酒屋街。素焼きピッチャー『ベンベル』で注ぐ名物リンゴ酒（Apfelwein）の名所。",
     "desc_es": "Barrio histórico al sur del río famoso por sus tabernas tradicionales de sidra de manzana en jarras Bembel.",
     "desc_zh": "位于美因河南岸的古朴酒館区。以使用特制蓝色土陶壶（Bembel）斟倒当地苹果酒闻名。",
     "desc_fr": "Quartier historique au sud du fleuve célèbre pour ses tavernes traditionnelles de cidre servi en pichet.",
     "de": "Alt-Sachsenhausen mit seinen Pflastergassen und traditionellen Apfelwein-Lokalen.",
     "tip_en": "🍽️ Sit at a shared wooden bench inside 'Zum Gemalten Haus' or 'Atschel' and order a 'Sauergespritzter' cider!",
     "tip_ja": "🍽️ 老舗『Zum Gemalten Haus』か『Atschel』へ！炭酸水割りのリンゴ酒と緑のソース付きシュニッツェルが鉄板。",
     "tip_es": "🍽️ Pide una jarra de Apfelwein con agua con gas (Sauergespritzter) y un escalope con salsa verde.",
     "tip_zh": "🍽️ 入座老字号“Zum Gemalten Haus”长木桌！点上一壶加气泡水稀释的爽口苹果酒与搭配七草绿酱的炸猪排。",
     "tip_fr": "🍽️ Installez-vous sur les bancs en bois de 'Zum Gemalten Haus' et commandez un pichet d'Apfelwein !",
     "tip_de": "🍽️ Im 'Zum Gemalten Haus' oder 'Atschel' Platz nehmen und Apfelwein mit Frankfurter Grüner Soße bestellen!",
     "price_en": "Cider: €2.80–€3.50", "price_ja": "リンゴ酒: 2.80〜3.50ユーロ", "price_es": "Sidra: 2,80€–3,50€", "price_zh": "苹果酒：2.80-3.50欧", "price_fr": "Cidre : 2,80 €–3,50 €", "price_de": "Apfelwein: 2,80 €–3,50 €",
     "name_en": "Sachsenhausen Cider District", "name_ja": "Sachsenhausen & Apfelwein-Kneipen（ザクセンハウゼン＆アプフェルヴァイン居酒屋街）", "name_es": "Distrito de la Sidra de Sachsenhausen", "name_zh": "萨克森豪森苹果酒街区", "name_fr": "Quartier du cidre de Sachsenhausen", "name_de": "Sachsenhausen & Apfelwein-Kneipen"},
    # 27. Senckenberg
    {"id": "f_27", "name": "Senckenberg Naturmuseum（ゼンケンベルク自然博物館）", "category": "Museum & Gallery", "rating": "★4.7", "locationZone": "city", "lat": 50.1175, "lng": 8.6517, "kids": True, "rain": True, "shopping": False, "free": False,
     "desc_en": "One of Europe's largest natural history museums housing a comprehensive dinosaur skeleton collection.",
     "desc_ja": "欧州最大級の自然史博物館。ディプロドクスやティラノサウルスの全身骨格標本、化石コレクションを所蔵。",
     "desc_es": "Uno de los museos de historia natural más grandes de Europa con la mayor colección de dinosaurios.",
     "desc_zh": "欧洲规模最大的自然历史博物馆之一。拥有全欧洲最完整的梁龙与暴龙骨架化石标本。",
     "desc_fr": "L'un des plus grands musées d'histoire naturelle d'Europe avec la plus vaste collection de dinosaures.",
     "de": "Eines der größten Naturkundemuseen Europas mit der umfangreichsten Dinosaurier-Ausstellung.",
     "tip_en": "📸 Walk straight into Hall 1 to photograph the original Diplodocus dinosaur skeleton standing alongside Stegosaurus!",
     "tip_ja": "📸 入場してすぐの第1展示ホールへ！巨大なディプロドクスとステゴサウルスの本物骨格が並ぶ姿を撮影。",
     "tip_es": "📸 ¡Entra directamente al Hall 1 para fotografiar el esqueleto de Diplodocus gigante al lado del Stegosaurus!",
     "tip_zh": "📸 步入1号展厅主廊！在巨大的真实梁龙与剑龙骨架化石正下方拍照合影。",
     "tip_fr": "📸 Entrez dans la salle 1 pour photographier le squelette géant de Diplodocus à côté du Stégosaure !",
     "tip_de": "📸 Direkt in Saal 1 gehen für Fotos des riesigen Diplodocus-Skeletts neben dem Stegosaurus.",
     "price_en": "Entry: €12", "price_ja": "入場料: 12ユーロ", "price_es": "Entrada: 12€", "price_zh": "门票：12 欧元", "price_fr": "Entrée : 12 €", "price_de": "Eintritt: 12 €",
     "name_en": "Senckenberg Natural History Museum", "name_ja": "Senckenberg Naturmuseum（ゼンケンベルク自然博物館）", "name_es": "Museo de Historia Natural Senckenberg", "name_zh": "森肯贝格自然博物馆", "name_fr": "Musée d'histoire naturelle Senckenberg", "name_de": "Senckenberg Naturmuseum Frankfurt"},
    # 29. Euro-Skulptur
    {"id": "f_29", "name": "Euro-Skulptur (Willy-Brandt-Platz)（巨大ユーロマーク像）", "category": "Landmark", "rating": "★4.5", "locationZone": "city", "lat": 50.1092, "lng": 8.6739, "kids": True, "rain": False, "shopping": False, "free": True,
     "desc_en": "Iconic 14-meter-tall blue-and-yellow neon Euro symbol sculpture standing in front of the former ECB headquarters.",
     "desc_ja": "旧欧州中央銀行（ECB）本部の前に立つ高さ14mの青と黄色の巨大ユーロマーク彫刻。金融都市の象徴。",
     "desc_es": "Escultura icónica del símbolo del euro de 14m frente a la antigua sede del Banco Central Europeo.",
     "desc_zh": "矗立于旧欧洲中央银行总部前的14米高蓝黄双色巨型欧元符号（€）雕塑。",
     "desc_fr": "Sculpture emblématique de 14m du symbole de l'Euro devant l'ancien siège de la Banque Centrale Européenne.",
     "de": "Skulptur des Euro-Symbols vor dem ehemaligen Sitz der Europäischen Zentralbank.",
     "tip_en": "📸 Visit after dark when all 12 yellow stars glowing around the blue € sign light up in vibrant neon!",
     "tip_ja": "📸 ネオンが灯る日没後の夜間訪問が映える！青い€マークの周囲にある12個の黄色い星の光が綺麗です。",
     "tip_es": "📸 Visítala de noche cuando las 12 estrellas amarillas se iluminan con neón frente a los rascacielos.",
     "tip_zh": "📸 推荐华灯初上的夜晚前往！周遭12颗黄星点亮霓虹色彩，背景即是摩天楼天际线。",
     "tip_fr": "📸 Venez à la nuit tombée quand les 12 étoiles jaunes s'illuminent au néon !",
     "tip_de": "📸 Nach Einbruch der Dunkelheit besuchen, wenn die 12 gelben Sterne des Euro-Symbols leuchten.",
     "price_en": "Free Access", "price_ja": "見学無料", "price_es": "Acceso libre", "price_zh": "免费参观", "price_fr": "Accès libre", "price_de": "Kostenlos",
     "name_en": "Euro Sculpture", "name_ja": "Euro-Skulptur (Willy-Brandt-Platz)（巨大ユーロマーク像）", "name_es": "Escultura del Euro", "name_zh": "巨大欧元符号雕塑", "name_fr": "Sculpture de l'Euro", "name_de": "Euro-Skulptur Frankfurt"},
    # 45. Ebbelwei-Express
    {"id": "f_45", "name": "Historische Straßenbahn Frankfurt (Ebbelwei-Express)（エッベルヴァイ・エクスプレス）", "category": "Kids & Family", "rating": "★4.6", "locationZone": "city", "lat": 50.1119, "lng": 8.6886, "kids": True, "rain": True, "shopping": False, "free": False,
     "desc_en": "Historic 1970s colorful tram offering weekend loop tours serving traditional cider and pretzels on board.",
     "desc_ja": "1977年から運航するレトロ市電。リンゴ酒とプレッツェルを味わいながら市内を1周する観光電車。",
     "desc_es": "Tranvía histórico de los años 70 que ofrece recorridos los fines de semana sirviendo sidra y pretzels a bordo.",
     "desc_zh": "始于1977年的复古彩色有轨观光电车。在车厢内一边享用送上的苹果酒与咸普雷结一边穿行于全市。",
     "desc_fr": "Tramway historique coloré des années 70 proposant des circuits le week-end avec cidre et bretzels à bord.",
     "de": "Historische bunte Straßenbahn, die an Wochenenden Stadtrundfahrten mit Apfelwein und Brezeln anbietet.",
     "tip_en": "🎟️ Board from Hauptbahnhof or Römerberg on weekends; ticket includes 1 bottle of cider + mini pretzels!",
     "tip_ja": "🎟️ 週末限定運行！乗車券（€8）には小瓶のリンゴ酒1本（またはジュース）とプレッツェル袋がセットで付きます。",
     "tip_es": "🎟️ ¡Sube los fines de semana! La entrada incluye una botella de sidra y minipretzels.",
     "tip_zh": "🎟️ 仅在周末运行！可在 Central Station 或 Römer 站上车，车票（8欧）已包含小瓶苹果酒与点心。",
     "tip_fr": "🎟️ Embarquez le week-end ! Le billet inclut une bouteille de cidre et des bretzels.",
     "tip_de": "🎟️ An Wochenenden einsteigen – Billet enthält 1 Flasche Apfelwein und Brezeln!",
     "price_en": "Tram Tour: €8", "price_ja": "市電ツアー: 8ユーロ", "price_es": "Tour en tranvía: 8€", "price_zh": "电车游览：8 欧元", "price_fr": "Circuit en tram : 8 €", "price_de": "Straßenbahn-Tour: 8 €",
     "name_en": "Ebbelwei-Express Tram", "name_ja": "Historische Straßenbahn Frankfurt (Ebbelwei-Express)（エッベルヴァイ・エクスプレス）", "name_es": "Tranvía Ebbelwei-Express", "name_zh": "苹果酒观光电车", "name_fr": "Tramway Ebbelwei-Express", "name_de": "Ebbelwei-Express Frankfurt"},

    # Suburban 46-61
    {"id": "f_46", "name": "Rüdesheim am Rhein & Drosselgasse（リューデスハイム＆つぐみ横丁）", "category": "Landmark", "rating": "★4.8", "locationZone": "suburban", "lat": 49.9786, "lng": 7.9222, "kids": True, "rain": False, "shopping": False, "free": True,
     "desc_en": "UNESCO Upper Middle Rhine Valley wine town famous for the narrow 144m Drosselgasse alley and cable car.",
     "desc_ja": "世界遺産ライン渓谷の拠点都市。144mの狭い路地にワイン酒場が並ぶ『つぐみ横丁』とロープウェイが有名。",
     "desc_es": "Pueblo vinícola del valle del Rino (UNESCO) famoso por el callejón Drosselgasse con tabernas de vino.",
     "desc_zh": "联合国教科文组织莱茵河谷名镇。拥有长144米的狭窄酒巷“画眉鸟巷”、缆车与葡萄园梯田。",
     "desc_fr": "Ville viticole de la vallée du Rhin (UNESCO) célèbre pour sa ruelle Drosselgasse et son téléphérique.",
     "de": "Rheingau-Weinstadt im UNESCO-Welterbe mit der Drosselgasse, Seilbahn und Rheinschifffahrt.",
     "tip_en": " Ride the open two-seater cable car up over Riesling vineyards to Niederwald Monument for a Rhine river bend view!",
     "tip_ja": " 2人乗りオープンロープウェイでブドウ畑の上空を空中散歩！ニーダーヴァルト記念碑からの見下ろしは大絶景。",
     "tip_es": " Sube al teleférico abierto sobre los viñedos de Riesling hasta el Monumento Niederwald.",
     "tip_zh": " 乘双人露天缆车越过梯田葡萄园！登顶 Niederwald 纪念碑俯瞰莱茵河转弯处。",
     "tip_fr": " Montez dans le téléphérique ouvert au-dessus des vignobles pour la vue sur le Rhin !",
     "tip_de": " Mit der Kabinenseilbahn über die Reben zum Niederwalddenkmal schweben – traumhafter Blick!",
     "price_en": "Town Free (Cable Car €10)", "price_ja": "街散策無料（ロープウェイ: 10ユーロ）", "price_es": "Pueblo gratis (Teleférico 10€)", "price_zh": "小镇免费（缆车10欧）", "price_fr": "Ville gratuite (Téléphérique 10 €)", "price_de": "Stadt frei (Seilbahn 10 €)",
     "name_en": "Rüdesheim Rhine Valley", "name_ja": "Rüdesheim am Rhein & Drosselgasse（リューデスハイム＆つぐみ横丁）", "name_es": "Rüdesheim en el Rino", "name_zh": "吕德斯海姆与画眉鸟巷", "name_fr": "Rüdesheim am Rhein", "name_de": "Rüdesheim am Rhein & Drosselgasse"},
    {"id": "f_47", "name": "Burg Eltz & Rheinburgen（エルツ城＆ライン川・モーゼル川古城群）", "category": "Landmark", "rating": "★4.9", "locationZone": "suburban", "lat": 50.2053, "lng": 7.3364, "kids": True, "rain": True, "shopping": False, "free": False,
     "desc_en": "Fairytale 12th-century untouched medieval castle hidden in a forested valley, held by the same family for 33 generations.",
     "desc_ja": "森の奥深くに佇む12世紀の中世の古城。戦火を免れた無破壊の城で、同じ家系が33代800年にわたり所有。",
     "desc_es": "Castillo medieval del siglo XII escondido en un valle boscoso, conservado por la misma familia durante 33 generaciones.",
     "desc_zh": "深藏于森林山谷之中的12世纪童话古堡。历经800年无战火摧残，由同一贵族家族传承33代。",
     "desc_fr": "Château médiéval du XIIe siècle caché dans une vallée boisée, préservé par la même famille.",
     "de": "Märchenhafte, nie zerstörte Höhenburg aus dem 12. Jahrhundert im Elzbach-Tal.",
     "tip_en": "📸 Walk down the paved access road from upper car park to hit the bend where castle spires suddenly appear!",
     "tip_ja": "📸 駐車場からの坂道を徒歩で下る途中の曲がり角がベストアングル！密林から突如現れる城の絵はがきビューが撮れます。",
     "tip_es": "📸 Camina por el camino pavimentado desde el aparcamiento para fotografiar la vista del castillo emergiendo del bosque.",
     "tip_zh": "📸 沿上层停车场侧石板坡道步行下山！在弯道处拍摄古堡尖塔从绿林中突兀立起的明信片角度。",
     "tip_fr": "📸 Descendez le chemin pavé desde le parking pour la photo du château émergeant de la forêt.",
     "tip_de": "📸 Den Fußweg vom Parkplatz hinabgehen: An der Kurve zeigt sich der Postkartenblick auf die Burg.",
     "price_en": "Entry: €14", "price_ja": "入場料: 14ユーロ", "price_es": "Entrada: 14€", "price_zh": "门票：14 欧元", "price_fr": "Entrée : 14 €", "price_de": "Eintritt: 14 €",
     "name_en": "Eltz Castle", "name_ja": "Burg Eltz & Rheinburgen（エルツ城＆ライン川・モーゼル川古城群）", "name_es": "Castillo de Eltz", "name_zh": "埃尔茨城堡", "name_fr": "Château d'Eltz", "name_de": "Burg Eltz"},
    {"id": "f_48", "name": "Mainz: Dom St. Martin & Gutenberg-Museum（マインツ：大聖堂＆グーテンベルク博物館）", "category": "Landmark", "rating": "★4.7", "locationZone": "suburban", "lat": 49.9989, "lng": 8.2739, "kids": True, "rain": True, "shopping": False, "free": False,
     "desc_en": "Historic Rhine city featuring the 1000-year-old Romanesque Cathedral and original printed Gutenberg Bibles.",
     "desc_ja": "千年以上の歴史を誇る大聖堂と、活版印刷の発明者グーテンベルクの博物館。シャガールブルーのステンドグラスが見所。",
     "desc_es": "Ciudad del Rino con la catedral románica de San Martín y el Museo Gutenberg con las Biblias impresas originales.",
     "desc_zh": "千年罗曼式主教堂所在地。拥有 Chagall 创作的湛蓝彩绘玻璃与印刷术发明家古腾堡博物馆。",
     "desc_fr": "Ville rhénane historique avec la cathédrale mille-naire Saint-Martin et le musée Gutenberg.",
     "de": "Historische Domstadt am Rhein mit dem Dom St. Martin und dem Gutenberg-Museum.",
     "tip_en": "📜 Walk into the Gutenberg Museum vault to admire two original 1450s printed Gutenberg Bibles on vellum!",
     "tip_ja": "📜 グーテンベルク博物館の地下金庫室へ！1450年代に印刷された本物の『グーテンベルク聖書』原本2冊を閲覧。",
     "tip_es": "📜 Entra en la caja fuerte del Museo Gutenberg para ver las dos Biblias originales impresas en pergamino hacia 1450.",
     "tip_zh": "📜 步入古腾堡博物馆地下保险库！观赏1450年代印制的羊皮纸《古腾堡圣书》原本。",
     "tip_fr": "📜 Entrez dans la salle coffre-fort du musée Gutenberg pour admirer les deux Bibles originales de 1450 !",
     "tip_de": "📜 Im Tresorraum des Gutenberg-Museums zwei originale Gutenberg-Bibel-Drucke von 1450 betrachten.",
     "price_en": "Museum Entry: €5", "price_ja": "博物館入場料: 5ユーロ", "price_es": "Entrada museo: 5€", "price_zh": "博物馆门票：5 欧元", "price_fr": "Entrée musée : 5 €", "price_de": "Museum Eintritt: 5 €",
     "name_en": "Mainz Cathedral & Gutenberg Museum", "name_ja": "Mainz: Dom St. Martin & Gutenberg-Museum（マインツ：大聖堂＆グーテンベルク博物館）", "name_es": "Catedral de Maguncia y Museo Gutenberg", "name_zh": "美因茨大教堂与古腾堡博物馆", "name_fr": "Cathédrale de Mayence et musée Gutenberg", "name_de": "Mainz: Dom St. Martin & Gutenberg-Museum"},
    {"id": "f_58", "name": "Kloster Eberbach（エバーバッハ修道院）", "category": "Landmark", "rating": "★4.8", "locationZone": "suburban", "lat": 50.0425, "lng": 8.0461, "kids": True, "rain": True, "shopping": False, "free": False,
     "desc_en": "1136 Cistercian monastery in the Rheingau, famed as filming location for 'The Name of the Rose' and top Riesling winery.",
     "desc_ja": "1136年創建のシトー会修道院。映画『薔薇の名前』のロケ地であり、ドイツ屈指のリースリングワイン醸造所。",
     "desc_es": "Monasterio cisterciense de 1136 en el Rheingau famoso como escenario de la película 'El nombre de la rosa'.",
     "desc_zh": "始于1136年的熙笃会修道院。为电影《玫瑰之名》实景拍摄地，兼具古老雷司令葡萄酒酒庄。",
     "desc_fr": "Abbaye cistercienne de 1136 célèbre comme lieu de tournage du film 'Le Nom de la Rose' et domaine viticole.",
     "de": "Ehemalige Zisterzienser-Abtei von 1136 im Rheingau, berühmter Drehort des Films 'Der Name der Rose'.",
     "tip_en": "🍷 Visit the Laienrefektorium to see 17th-century wooden wine presses, then taste Riesling in the cellar shop!",
     "tip_ja": "🍷 17世紀の超巨大木製ワイン圧搾機が並ぶ『修道士の食堂』を見学後、直営ショップでリースリング白ワインを試飲！",
     "tip_es": "🍷 Visita la sala de las prensas de vino del siglo XVII y prueba una copa de Riesling en la tienda.",
     "tip_zh": "🍷 走入直观陈列着17世纪巨型木质榨汁机的大厅！参观完毕后前往直营酒窖品鉴雷司令干白。",
     "tip_fr": "🍷 Visitez la salle des grands pressoirs du XVIIe siècle puis dégustez un verre de Riesling !",
     "tip_de": "🍷 Die riesigen Holzkeltern im Laienrefektorium besichtigen und Riesling in der Vinothek probieren.",
     "price_en": "Entry: €12", "price_ja": "入場料: 12ユーロ", "price_es": "Entrada: 12€", "price_zh": "门票：12 欧元", "price_fr": "Entrée : 12 €", "price_de": "Eintritt: 12 €",
     "name_en": "Eberbach Abbey", "name_ja": "Kloster Eberbach（エバーバッハ修道院）", "name_es": "Abadía de Eberbach", "name_zh": "埃伯巴赫修道院", "name_fr": "Abbaye d'Eberbach", "name_de": "Kloster Eberbach"},
    {"id": "f_59", "name": "Darmstadt: Mathildenhöhe (UNESCO)（ダルムシュタット：マチルダの丘）", "category": "Landmark", "rating": "★4.7", "locationZone": "suburban", "lat": 49.8769, "lng": 8.6675, "kids": True, "rain": False, "shopping": False, "free": True,
     "desc_en": "UNESCO World Heritage Art Nouveau artists' colony in Darmstadt featuring Olbrich's 48m Wedding Tower.",
     "desc_ja": "ユネスコ世界遺産のユーゲントシュティール（アール・ヌーヴォー）芸術家村。結婚記念塔と金色のロシア教会が象徴。",
     "desc_es": "Colonia de artistas del Art Nouveau (UNESCO) en Darmstadt con la Torre de la Boda de 48m.",
     "desc_zh": "联合国教科文组织新艺术运动艺术家村。拥有48米高的“结婚纪念塔”与金色圆顶俄罗斯教堂。",
     "desc_fr": "Colonie d'artistes Art Nouveau (UNESCO) à Darmstadt avec la Tour du Mariage de 48m.",
     "de": "UNESCO-Welterbe der Jugendstil-Künstlerkolonie Darmstadt mit dem 48m hohen Hochzeitsturm.",
     "tip_en": "📸 Climb the 5-finger Wedding Tower terrace for a view over the plane-tree grove and gilded Russian Chapel!",
     "tip_ja": "📸 5本の指の形をした結婚記念塔のテラスへ！プラタナスの木立と金色のロシア教会を見下ろすアングルが最高。",
     "tip_es": "📸 Sube a la terraza de la Torre de la Boda para contemplar el arboleda de plátanos y la capilla rusa.",
     "tip_zh": "📸 登顶“五指结婚纪念塔”外侧露台！俯瞰梧桐树林与金光闪闪的洋葱顶俄罗斯教堂。",
     "tip_fr": "📸 Montez sur la terrasse de la Tour du Mariage pour la vue sur le bosquet et la chapelle russe.",
     "tip_de": "📸 Auf die Aussichtsplattform des Fünffingerturms steigen für einen Blick auf den Platanenhain.",
     "price_en": "Grounds Free (Tower €5)", "price_ja": "敷地無料（塔登頂: 5ユーロ）", "price_es": "Recinto gratis (Torre 5€)", "price_zh": "园区免费（登塔5欧）", "price_fr": "Parc gratuit (Tour 5 €)", "price_de": "Areal frei (Turm 5 €)",
     "name_en": "Darmstadt Mathildenhöhe", "name_ja": "Darmstadt: Mathildenhöhe (UNESCO)（ダルムシュタット：マチルダの丘）", "name_es": "Mathildenhöhe en Darmstadt", "name_zh": "达姆施塔特玛蒂尔德丘", "name_fr": "Mathildenhöhe à Darmstadt", "name_de": "Darmstadt: Mathildenhöhe (UNESCO)"},
    {"id": "f_61", "name": "Wertheim Village（ヴェルトハイム・ビレッジ）", "category": "Shopping", "rating": "★4.6", "locationZone": "suburban", "lat": 49.7719, "lng": 9.5772, "kids": True, "rain": True, "shopping": True, "free": True,
     "desc_en": "Luxury open-air outlet shopping village 1 hour from Frankfurt featuring 110+ designer fashion boutiques.",
     "desc_ja": "フランクフルトから車・シャトルバスで1時間。110以上のデザイナーブランドが最大60%オフで並ぶアウトレット。",
     "desc_es": "Villa de compras de outlet de lujo a 1 hora de Fráncfort con más de 110 boutiques de diseñadores.",
     "desc_zh": "距离法兰克福1小时车程的大型露天名品折扣奥特莱斯购物村。汇聚110余家国际大牌。",
     "desc_fr": "Village outlet de luxe à 1h de Francfort proposant plus de 110 boutiques de designers.",
     "de": "Luxus-Designer-Outlet-Village 1 Stunde von Frankfurt mit über 110 Boutiquen.",
     "tip_en": "🚌 Take the official 'Shopping Express' shuttle bus direct from Frankfurt Hauptbahnhof on weekends!",
     "tip_ja": "🚌 フランクフルト中央駅から直行運行する公式シャトルバス『Shopping Express』でアクセス快適！",
     "tip_es": "🚌 Toma el autobús oficial 'Shopping Express' directo desde la estación central de Fráncfort Hauptbahnhof.",
     "tip_zh": "🚌 推荐于中央车站搭乘官方“Shopping Express”直达穿梭巴士！往返便捷。",
     "tip_fr": "🚌 Prenez la navette officielle 'Shopping Express' depuis la gare centrale de Francfort !",
     "tip_de": "🚌 Den offiziellen 'Shopping Express'-Shuttlebus direkt vom Hauptbahnhof Frankfurt nutzen.",
     "price_en": "Free Entry (Shopping)", "price_ja": "入館無料（ショッピング）", "price_es": "Entrada libre (Compras)", "price_zh": "免费入场（购物）", "price_fr": "Entrée libre", "price_de": "Freier Eintritt",
     "name_en": "Wertheim Village Outlet", "name_ja": "Wertheim Village（ヴェルトハイム・ビレッジ）", "name_es": "Wertheim Village Outlet", "name_zh": "威尔特海姆购物村", "name_fr": "Wertheim Village", "name_de": "Wertheim Village Outlet"}
]

with open("data/cities/frankfurt.json", "w", encoding="utf-8") as f:
    json.dump({"cityName": "Frankfurt, Germany", "spots": frankfurt_all_61}, f, ensure_ascii=False, indent=2)

print(f"🎉 Successfully updated data/cities/frankfurt.json with {len(frankfurt_all_61)} spots")
